### ISSUE TITLE
Parameter to remove metrics from queue after few retries. 

### ISSUE THREAD

**Issue by Nitesh-vaidyanath** [VictoriaMetrics/VictoriaMetrics#1026]
**Is your feature request related to a problem? Please describe.**

I am using vmagent to scrape prometheus metrics and rewrite to cortex,  "**vmagent_remotewrite_pending_data_bytes**" is growing as i am seeing error from cortex nginx "response body="**label value too long**". I have increased queues to 50 but still not seeing new metrics forwarded to cortex.  Why metrics are not being removed from queue after so many retires ?

**Describe the solution you'd like**
Adding configurable parameter which will remove metrics from the queue after few retires.

**Comment by hagen1778** [comment]
Hi @Nitesh-vaidyanath! 

> I have increased queues to 50 but still not seeing new metrics forwarded to cortex

Which exact parameter did you increase and what was the intent?

> Why metrics are not being removed from queue after so many retires ?

vmagent makes its best in order to deliver the data to configured destination. It will start drop data only if:
* in-memory buffers are full;
* on-disk persistent queue is full.

The data is delivered via remote-write protocol and as destination could be any system which supports this protocol. vmagent doesn't know what is the type of system which receives the data. Hence, it can't know how to parse such response errors. 

And I don't think it should parse such errors since it leads to unnecessary complexion and dependency on other systems implementation. If remote-write protocol does not describe such behavior explicitly, I don't see why it should be supported by any client/server.

**Comment by valyala** [comment]
Additional information: vmagent sends metrics to remote storage in batches. Each batch may contain many metrics. So vmagent cannot determine which particular metric from the batch led to error on remote storage side. The best it could do is to drop the whole batch after a few unsuccessful attempts to send it to remote storage.

**Comment by valyala** [comment]
Closing this issue as addressed.
