### ISSUE TITLE
hello,we found that a storage in the vm cluster restarted yesterday, and the error is as follows

### ISSUE THREAD

**Issue by mrbaowei** [VictoriaMetrics/VictoriaMetrics#1032]
![image](https://user-images.githubusercontent.com/16350494/105623062-b3fd0e80-5e51-11eb-9c11-3e23a9e3419c.png)

**Comment by hagen1778** [comment]
Hi @vizogood! The error warns that file on disk failed to decompress which is oftenly a sign of disk corruption. Could this be your case? Do you have a way to test disk health state?

**Comment by vizogood** [comment]
> The error warns that file on disk failed to decompress which is oftenly a sign of disk corruption. Could this be your case? Do you have a way to test disk health state?

Thanks @hagen1778 , It 's our own server. I checked that the health status of our ssd disk is normal.  What else could be the problem？

**Comment by aval13** [comment]
Hello @vizogood , just a thought: maybe the disk is fine, but the filesystem is broken.
Can you run maybe an md5sum on the 3 files mentioned in the printscreen and see if they complete successfully or some error is being thrown?

Also, since I'm also using VMC, i'm curious:
- what version are you running?
- I see the syslog reports "vm-storage" instead of "vmstorage-prod". Did you build the binary from source or are you using the binaries provided by this project?

Thank you.

**Comment by vizogood** [comment]
> Hello @vizogood , just a thought: maybe the disk is fine, but the filesystem is broken.
> Can you run maybe an md5sum on the 3 files mentioned in the printscreen and see if they complete successfully or some error is being thrown?
> 
> Also, since I'm also using VMC, i'm curious:
> 
> * what version are you running?
> * I see the syslog reports "vm-storage" instead of "vmstorage-prod". Did you build the binary from source or are you using the binaries provided by this project?
> 
> Thank you.

Hi @aval13 , thanks for your answer.
3 files mentioned in the printscreen no longer exists, maybe already merge by vm-storage?
our vm-storage version: vmstorage-20201228-002929-tags-v1.51.0-cluster-0-g66a19e007
we use the binaries provided by this project, syslog reports "vm-storage" because of we set SyslogIdentifier=vm-storage in systemd service file : ) 
![image](https://user-images.githubusercontent.com/16350494/106549614-513ffd00-654c-11eb-9ed5-95722e06ae01.png)

**Comment by hagen1778** [comment]
> Thanks @hagen1778 , It 's our own server. I checked that the health status of our ssd disk is normal. What else could be the problem？

Did you forcefully killed the VM process or machine rebooted abruptly? Process could be in the middle of flushing data on the disk, so some kind of "accidental power off" could result into partially written data.

**Comment by valyala** [comment]
@hagen1778 , VictoriaMetrics shouldn't corrupt or lose already stored data on unclean shutdown such as `accidental power off` or hardware reset. It writes data into a temporary directory, then calls [fsync](https://man7.org/linux/man-pages/man2/fsync.2.html) on the created files to make sure that the data is successfully flushed to disk, then atomically moves the created files from a temporary directory to a data directory, so they become visible for querying. The source files used in background merge are also deleted atomically at this moment. This guarantees that the stored data is always in consistent state unless the underlying disk storage is corrupted. See more details at https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282
