### ISSUE TITLE
Expose information about open file descriptors

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1037]
It's easy to lost database/storage node when machine reaches the open file limits 

Please expose information about open file descriptors as metric for single and storage node

It'd be good to add panel to dashboards a swell

**Comment by valyala** [comment]
Related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/402 .

**Comment by valyala** [comment]
The commit 9fb38569eb34236a66de4640c1f058922bf0d658 adds `process_open_fds` and `process_max_fds` metrics at `/metrics` page for all the VictoriaMetrics components. This commit will be included in the next release.

**Comment by jelmd** [comment]
Please use `-1` for `unlimited`.

**Comment by valyala** [comment]
@jelmd , `-1` will break alerts for queries like `process_open_fds < process_max_fds` or `process_open_fds * 0.9 < process_max_fds` .

**Comment by jelmd** [comment]
Ohhh, haven't used alert manager yet. That means `q < max > min` to filter out "out-of-bounds" values is just a grafana  thing? And thus things like `(process_open_fds < 2^32 > 0) < process_max_fds` etc. do not work?

Just wondering, because on 16bit (-1) == 2^16-1 and on 32bit platforms -1 == 2^32-1, so the transformation to 2^64-1 is not really correct and IMHO `unset` vs. `2^n-1` is still something different. Would be probably a non-brainer, if we would have something like `skip(q, min, max)` to filter out the noise first ;-) .

**Comment by valyala** [comment]
The `q < max > min` query works as expected in any contexts, i.e. it filters out values outside `[min ... max]` range. But if `process_max_fds` is set to `-1`, then users should be aware about this quirk and use more complicated query as you provided.

**Comment by valyala** [comment]
The `process_open_fds` and `process_max_fds` metrics are exposed by all the VictoriaMetrics components starting from [v1.54.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
