### ISSUE TITLE
Question: vmstorage CPU usage increase periodically

### ISSUE THREAD

**Issue by Guoyuechuan** [VictoriaMetrics/VictoriaMetrics#1046]
Hi,
I am using cluster version. The CPU usage of vmstorage nodes increases and then decreases per hour, which cause the vminsert node CPU usage increase and the ingestion rate decrease. I checked the metric `vm_concurrent_addrows_current` and it reached the max value. It seems like something in the vmstorage node gets stuck and it does not process any incoming data. Is there any idea?
Here is some metrics.
![image](https://user-images.githubusercontent.com/20922937/106578154-2f5d6f00-657a-11eb-990d-e7fda2119583.png)
![image](https://user-images.githubusercontent.com/20922937/106578202-3b493100-657a-11eb-82ad-e35a890dd7bb.png)
![image](https://user-images.githubusercontent.com/20922937/106578251-49974d00-657a-11eb-945d-da4d4f9ff7d6.png)
![image](https://user-images.githubusercontent.com/20922937/106578321-5ddb4a00-657a-11eb-8e3b-bea5012e9fbb.png)
![image](https://user-images.githubusercontent.com/20922937/106578445-79deeb80-657a-11eb-80d9-d3c48855f3ea.png)

**Comment by valyala** [comment]
This can be related to the following cases:

* Heavy `select` requests. Probably there are some requests at the beginning of every hour, which take a lot of CPU at vmstorage nodes. Take a look at `Query duration` graphs and at `/api/v1/status/top_queries` response at `vmselect` nodes. The `/api/v1/status/top_queries` handler is available starting from release `v1.51.0`.
* Increased time series churn rate at the beginning of every hour. Probably, some time series contain a set of labels with values that depend on the current hour. This may induce creation of big number of new time series in the beginning of every hour, since a time series is uniquely identified by its name plus a set of all its labels. `vmstorage` spends much more CPU and disk IO resources when it processes the first sample for new time series comparing to subsequent samples for already existing time series. Take a look at `Churn rate` graph in order to verify this case.
* Background merge process. VictoriaMetrics merges smaller data files into bigger files in background. See [this article for details](https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282). Usually this takes quite small amounts of CPU and disk IO resources, but sometimes it can take bigger amount of resources when merging bigger files. This issue can be verified by looking at the following graphs: `Active merges`, `LSM parts` and `Merge speed`.
* Some external app that runs every hour on `vmstorage` nodes. For example, an app that makes hourly backups.

It is also recommended running VictoriaMetrics components from [the latest release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since they can contain various bugfixes and performance optimizations comparing to older releases.

**Comment by Guoyuechuan** [comment]
Thanks for the reply. Sadly all these situations are not applied. There is not select requests. Active series and churn rate metrics are posted in issue #1043. There is no big part merging process. Each nodes has only `vmstorage`.
I guess it may related to the `currHourMetricIDs` and `prevHourMetricIDs` cache. Changing or creating these two caches may have high CPU load and block the writing progress. Is this possible?

**Comment by valyala** [comment]
@Guoyuechuan , thanks for the pointer! I tried fixing the issue in the commit c6a7288109c2c99b612a3bfa44c89643b89f919e . Could you build `vmstorage` from this commit and verify whether this reduces CPU spikes at the beginning of every hour? See [build instructions for cluster components](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by Guoyuechuan** [comment]
Thanks for the quick reply! I am using [v1.51.0-cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.51.0-cluster) according to the #1043 . It seems that everything is good.
This CPU spike problem is from the version v1.52. I will check out this fix.

**Comment by valyala** [comment]
@Guoyuechuan , thanks for the confirmation that spikes have been fixed. Closing the issue as fixed then.
