### ISSUE TITLE
active time series suddenly multiply by 2

### ISSUE THREAD

**Issue by guliangsi** [VictoriaMetrics/VictoriaMetrics#1054]
**Describe the bug**
Hello,

We encounter, for the 2nd time this week, ingestion problems in VictoriaMetrics.

Suddenly the number of active time series returned by the querie :  sum (vm_cache_entries {job=~"$job",instance=~"$instance. *",type="storage/hour_metric_ids"})
going from around 15million to almost double, between 28 and 32 million!

We fail to understand where these new timeseries are coming from. We haven't seen any increase in the number of timeseries on any of our Prometheus instances, as you can see on the prometheus_tsdb_head_series graph. (Timeseries breaks in the graph  correspond to stops of prometheus instances to work around the problem).

![prometheus_tsdb_head](https://user-images.githubusercontent.com/43655090/106913377-37e1b100-6704-11eb-884e-9fb9ceb1cc77.PNG)

This increase in active time series leads to overconsumption of CPU on vmstorage and therefore slow_inserts and rpc error Reroute. As a result, the ingestion rate decreases from about 400k / s to 150k / s.

The only solution we have found to work around the problem is to stop around 30 prometheus instances (out of 115 in total). After about 1 hour, the number of active time series goes down to a "normal" level, and we can then restart the prometheus that are off.

What could explain this doubling of the active time series? Is there anything else that can cause this increase in time series, such as a big user query... 
Expert advice would be welcome! I can provide other graphs if needed!

Thanks for your help 
Regards

**Screenshots**
![vm_pb_1](https://user-images.githubusercontent.com/43655090/106913402-3e702880-6704-11eb-9586-fd22f77efd66.PNG)
![vm_pb_2](https://user-images.githubusercontent.com/43655090/106913412-40d28280-6704-11eb-9f91-dc0e581f3094.PNG)
![vm_pb_3](https://user-images.githubusercontent.com/43655090/106913422-429c4600-6704-11eb-85b9-e1ae6daedce8.PNG)
![vm_pb_4](https://user-images.githubusercontent.com/43655090/106913430-44660980-6704-11eb-83d8-af3ebc8dccf4.PNG)
![vm_pb_5](https://user-images.githubusercontent.com/43655090/106913434-462fcd00-6704-11eb-9885-3a8a98017618.PNG)

**Version**
victoriametrics-cluster v1.48.0

**Comment by valyala** [comment]
The summary number of active time series can grow up to 2x in cluster version of VictoriaMetrics due to re-routing.

`vminsert` spreads incoming metrics among the configured list of `vmstorage` nodes. It calculates a hash over metric name and all its labels and uses the hash result for determining `vmstorage` node to send the metric to. This means that metrics belonging to a single time series are routed to a single `vmstorage` node under normal conditions. So the number of active time series is spread evenly among `vmstorage` nodes. When some `vmstorage` node cannot keep up with the incoming ingestion rate, then `vminsert` starts re-routing incoming samples from theis `vmstorage` node to the remaining `vmstorage` nodes. This increases the number of active time series on the remaining `vmstorage` nodes by `1/N` times where `N` is the number of `vmstorage` nodes in the cluster. The remaining `vmstorage` nodes start spending increased amounts of RAM, CPU time and disk IO when they start accepting data for new time series, which were re-routed from slow `vmstorage` node. This may result in "re-routing storm", when all the incoming samples are re-routed among all the the `vmstorage` node. This "storm" may result in 2x increase of active time series on every `vmstorage` nodes. So it is recommended to have at least 50% of spare RAM, CPU and disk IO resources on `vmstorage` nodes, so they could keep up with such "re-routing storm".

The "re-routing" storm can be triggered by the following conditions:
* Increased ingestion rate, which could exceed cluster capacity for a short period of time.
* Data ingestion for big number of new time series. `vmstorage` spends much more CPU and disk IO resources when it receives a sample for new time series compared to the case when it receives a sample for already existing time series. These resources are spent on registering various meta-information for the new time series. So if big number of new time series appear in a short period of time, then `vmstorage` can decrease the effective ingestion rate.

**Comment by guliangsi** [comment]
thank you for the answer @valyala 

So, if we double the number of vmstorage from 4 to 8 (so in total more CPU and RAM), we should be able to pass this kind of storm more calmly?

**Comment by valyala** [comment]
>  if we double the number of vmstorage from 4 to 8 (so in total more CPU and RAM), we should be able to pass this kind of storm more calmly?

Yes. In this case every `vmstorage` node will handle 1/2 of active time series compared to the current setup, so it will have enough resources for handling such issues.

**Comment by naveen-adisesha** [comment]
I noticed that a rolling update for the vmstorage seems to shift the metrics to other vmstoragenodes.  
1.  What happens if the storage node is back, will it go back to old distribution ? 
2.  Would it be a good idea to nack to vmagent to prevent upset to other storage nodes which can be shared by more tenants? Once upgrade is done it could continue its old distribution. 
3.  Do we see a  cascading effect of the metrics distribution during rolling update?
4.  Can we indicate to not change the distribution for some specific timeout, does it add value ? may be change in distribution can also impact disk space due to separate compaction ?  Also tell not to distribute since we are using it for multitenants. distribution could be per tenant instead of within a tenant as well. just some thoughts.
5. Does this behavior impact the deduplication logic when agents are in HA? 

Sorry for the long list of questions/doubts. But then consistent Memory usage seems to be important factor for metrics. 
Thank you.

**Comment by naveen-adisesha** [comment]
Thank you @valyala for clarifying the doubts. 

With -disableRouting will the insert nodes inform agent prior to dispatching rest of time series to the alive storage nodes ?  
If a storage node is down for a long time as indicated the data is stuck on vmagent until one performs a restore on the storage node.  May be disableRouting in this case needs to be a timer to give flexibility to manage upgrade while handling failure in traditional way.
In any case I would like to hold my request until I try the current solution and how much impact it has on my system.  Thanks again for your inputs.

**Comment by syepes** [comment]
The ` -disableRouting` option will be very interesting and helpful in the scenarios were we are sure to maintain and recover the lost nodes.

Will this option also handle the replication?
Meaning that if only one node is down, It can still continue to send data to the available nodes.

This should help prevent all the re-routing storm.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/791

**Comment by valyala** [comment]
FYI, the probability of the rerouting issue should be decreased starting from [v1.59.0](https://docs.victoriametrics.com/CHANGELOG.html#v1590), since it improves the registration speed for new time series on multi-CPU hosts. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1244 for details.

**Comment by valyala** [comment]
vminsert contains the improved re-routing mechanism starting from [v1.61.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It should reduce the probability, the duration and the severity of the global re-routing storm if all the `vmstorage` nodes cannot keep up with the current ingestion rate.

Additionally, vminsert v1.61.0 supports the ability to disable the rerouting with `-disableRerouting` command-line option. Below is the corresponding description for this option obtained from `/path/to/vminsert -help`:

>  -disableRerouting
>        Whether to disable re-routing when some of vmstorage nodes accept incoming data at slower speed compared to other storage nodes. By default the re-routing is enabled. Disabled re-routing limits the ingestion rate by the slowest vmstorage node. On the other side, disabled re-routing minimizes the number of active time series in the cluster

**Comment by valyala** [comment]
The next version of VictoriaMetrics will contain improved logic for data re-routing in the event if some of vmstorage nodes are temporarily unavailable or if some of vmstorage nodes temporarily slow down the processing speed for incoming data. The following improvements will be included in the next release of VictoriaMetrics cluster:
* Even series distribution among the remaining vmstorage nodes. Previously some vmstorage nodes could start receiving multiple times more series than other vmstorage nodes if some vmstorage nodes were unavailable or were slower than other vmstorage nodes.
* Reduced the maximum increase in the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) on the remaining vmstorage nodes after some vmstorage nodes become unavailable or become slow. It will be limited by 100% of the initial number of active time series per vmstorage node in the worst case (e.g. when vmstorage nodes have no enough resources to keep up with the increased load). Under normal conditions the increase in the number of active time series shouldn't exceed `1/N` of the initial number of active time series per vmstorage node, where `N` is the number of `vmstorage` nodes in the cluster. Previously the typical increase in the number of time series per vmstorage node after the re-routing was closer to 100%, while in the worst case it could reach `(N-1)`x.
* The placement of time series among `vmstorage` nodes doesn't depend on the order of `vmstorage` addresses passed to `-storageNode` command-line flag at `vminsert` nodes thanks to the changed consistent hashing algorithm (from [jump hash](https://arxiv.org/abs/1406.2294) to [rendezvous hash](https://www.eecs.umich.edu/techreports/cse/96/CSE-TR-316-96.pdf) ). Previously samples for the same time series could be placed to multiple `vmstorage` nodes if multiple `vminsert` nodes had different order of `vmstorage` nodes passed to `-storageNode` command-line flag. This could result in increased number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) across all the vmstorage nodes, which, in turn, could result in higher resource usage (RAM, CPU, disk IO, disk space) at `vmstorage` nodes.

These improvements should improve the stability of the mode with enabled rerouting in the cluster (e.g. when `-disableRerouting=false` command-line flag is passed to `vminsert`. The re-routing is disabled by default starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660) ).

The next release of VictoriaMetrics also adds an ability to drop incoming samples if vmstorage nodes are temporarily unavailable and/or overloaded if `-dropSamplesOnOverload` command-line flag is passed to `vminsert` nodes. By default vminsert slows down accepting new samples if vmstorage cannot keep up with the ingestion rate. This may result in increased number of pending samples at client side, which sends data to vminsert. This increases the delay between samples' generation and samples' ingestion into vmstorage. This may result in incomplete query results, which rely on recently ingested data (e.g. alerting and recording rules). In this case the `-dropSamplesOnOverload` mode may help receiving the most recently generated samples at the cost of dropping older samples. The number of dropped samples is tracked in per-`vmstorage` counter at `vminsert` nodes - `vm_rpc_rows_dropped_on_overload_total` . See more details at [changelog](https://docs.victoriametrics.com/CHANGELOG.html).

The features mentioned above can be tested by building cluster components of VictoriaMetrics from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) (currently this is 755e26e67b44962bada3a427e114d3f6ae284b5b ) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 .

**Comment by valyala** [comment]
FYI, the improvements mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337#issuecomment-1031538669 have been integrated into [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
FYI, `vminsert` in the next release (`v1.98.0`) will support `-disableReroutingOnUnavailable` command-line flag , which can be used for disabling re-routing even if some vmstorage nodes are temporarily unavailable. In this case `vminsert` pauses accepting new samples until all the vmstorage nodes return to the cluster. This allows completely eliminating issues related to the re-routing, such as increased RAM usage, CPU usage and disk IO usage on the remaining vmstorage nodes. See [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#improving-re-routing-performance-during-restart) for more details.

Closing this issue as addressed. Please open new issues related to re-routing in VictoriaMetrics cluster.
