### ISSUE TITLE
Lots of Rows ignored + small_timestamp errors during import from InfluxDB 1.8

### ISSUE THREAD

**Issue by vainkop** [VictoriaMetrics/VictoriaMetrics#1070]
**Describe the bug**
All VM stack including Grafana was started from the docker-compose from the repo:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml

During the import of a database from a remote InfluxDB 1.8.3 on AWS to VM also on AWS (same subnet, internal network) I see lots of "Rows ignored" + "small_timestamp" events on the VictoriaMetrics Grafana dashboard. The number is quite high ~ 270 Millions & counting.
Both machines have more that enough of resources.

Here's how I started it:
```
/vmctl influx --influx-addr "http://ip-10-0-0-152.ec2.internal:8086" --influx-database "db1" --vm-addr "http://localhost:8428"
```
```
InfluxDB import mode
Exploring scheme for database "db1"
fetching fields: command: "show field keys"; database: "db1"; retention: "autogen"
found 37 fields; skipped 8 non-numeric fields
fetching series: command: "show series"; database: "db1"; retention: "autogen"
found 5102 series
Found 30213 timeseries to import. Continue? [Y/n] y
30197 / 30213
```
After the number of timeseries went up to 30197 & 99.97% 0 p/s the overall progress slowed down dramatically (looks like it's stuck actually).
```
30203 / 30213 [--------------------------------------------------------------------->] 99.97% 0 p/s
```
Is there a way to import all data without "ignoring" any rows?

**Expected behavior**
Import all data correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28118190/107812233-715b9180-6d80-11eb-9631-63743fae8d39.png)
![image](https://user-images.githubusercontent.com/28118190/107816019-2f811a00-6d85-11eb-9d27-f0fe6c3ea72e.png)

**Comment by vainkop** [comment]
The `-retentionPeriod` in VM was not configured so it was default = 1 month & in our InfluxDB it was infinite & some of the data was quite old. After configuring the `--retentionPeriod=1200` (100 years yes)  the import succeeded.
Here's what gave my a "clue" :)
```
warn  VictoriaMetrics/lib/storage/storage.go:1535  warn occurred during rows addition: cannot insert row with too small timestamp 1610480786686 outside the retention; minimum allowed timestamp is 1610480926000; probably you need updating -retentionPeriod command-line flag; metricName: imu_messages_packet_timestamp{db="db1"}
```

**Comment by vainkop** [comment]
```
30213 / 30213 [-----------------------------------------------------------------------------------] 100.00% 1 p/s
2021/02/13 04:09:41 Import finished!
2021/02/13 04:09:41 VictoriaMetrics importer stats:
  idle duration: 14h42m32.83102125s;
  time spent while importing: 7h57m46.053669402s;
  total samples: 1393206545;
  samples/s: 48601.27;
  total bytes: 44.2 GB;
  bytes/s: 1.5 MB;
  import requests: 6966;
  import requests retries: 0;
2021/02/13 04:09:41 Total time: 7h57m51.097083843s
```
8 hours to import 44.2 GB does not sound very good.

**Comment by vainkop** [comment]
The following options seem to improve the overall process:
```
#!/bin/bash
for DB in $(cat databases); do
./vmctl influx \
  --influx-addr "http://ip-10-0-0-152.ec2.internal:8086" \
  --influx-database "$DB" \
  --vm-addr "http://localhost:8428" \
  --influx-concurrency=4 \
  --vm-concurrency=2 \
  -s
done
```
Influx has 4 core cpu
VM has 2 core cpu. `--vm-concurrency=2` is the default value but I've left it there in case I decide to change it later.

**Comment by vainkop** [comment]
Unfortunately the import process was still very very slow so I had to turn it off at some point.

I don't see anything special in the installation I have & whatever fields use some format which is not acceptable to VM are anyways skipped, but still the import progress is not fast enough to migrate in adequate time frame even with what looks like enough resources on both machines.

This is definitely a blocker for migration of the project from InfluxDB to VM. The DB size in InfluxDB is ~200Gb which is not much nowadays.

**Comment by hagen1778** [comment]
Hi @vainkop! Just want to add some clarification.
Your stats after the import are following
```
  idle duration: 14h42m32.83102125s;
  time spent while importing: 7h57m46.053669402s;
```
The idle duration is time while `vmctl` waits for data to process. Basically, it waits for influx to respond on the export queries. This is explained in more details [here](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmctl#importer-stats) along with recommendations what can be improved.
Also, I'm pretty sure that influx here is a bottleneck, since my experience shows a way better performance (see README examples). Maybe it is specific for your data set, if so would be great to get a fraction of insensitive data from your database on which I can reproduce the issue.

>  whatever fields in InfluxDB which have some format which is not acceptable to VM were supposed to be anyways skipped (which is not a good thing, better that they be transformed at least somehow, becasue skipping is data loss)

According to [docs](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#field-value)  measurement's `Field values can be floats, integers, strings, or Booleans.`. Vmctl skips string-type values since VM can store only float64 values. The info about skipping fields is printed before migration start to inform user about the fact of data skipping. I don't see how string values can be converted in something numeric.

> This is definitely a blocker for migration of the project from InfluxDB to VM. The DB size in InfluxDB is ~200Gb which is not much nowadays.

I know for sure that our users did a successful migration from influx to VM. I'm sorry to hear that it wasn't a case for you. We'll try to improve our software!

**Comment by vainkop** [comment]
@hagen1778 I'm sure that the problem is in the InfluxDB specific data.

If we decide to finish the migration to VM due to potentially higher performance of VM for the calculations we need then it probably makes sense to contact VM enterprise team to help us with that?

**Comment by hagen1778** [comment]
@vainkop sure! Feel free to reach us!
