### ISSUE TITLE
cluster version of vmagent

### ISSUE THREAD

**Issue by mxlxm** [VictoriaMetrics/VictoriaMetrics#1084]
**Is your feature request related to a problem? Please describe.**
* prevent SPOF.
* scrapework auto-dispatching.

**Describe the solution you'd like**

I'm using a customized version of vmagent, integrated [memberlist](https://github.com/hashicorp/memberlist) to build a gossip cluster, which supports:
* Auto-join and auto-drop of vmagent instance.
* `crc32(sw.ScrapeURL) % gossip.length = gossip.index` based scrapework auto-dispatching.

it works great, but also have some shortage: 
* we have to ensure all vmagent instance use the same config.
* all vmagent instances still need to fetch all instances with specified service discovery, only skip the scrapework.
* also, this modify aginsts [Community and contributions](https://github.com/victoriaMetrics/VictoriaMetrics/tree/cluster#community-and-contributions) with:
> * Avoid big external dependencies.
> * Fragile gossip protocols.

so, I'm not sure if we would accept this pr.

**Describe alternatives you've considered**
raft based cluster. or any other good idea?

**Comment by valyala** [comment]
@mxlxm , the commit e5ca8ac0db8e181a5b9c4798c04d92db4be40c49 adds ability to spread scrape targets among multiple `vmagent` instances with two additional command-line flags: `-promscrape.cluster.membersCount`  and `-promscrape.cluster.memberNum`. See [these docs](https://victoriametrics.github.io/vmagent.html#scraping-big-number-of-targets) for details.

**Comment by mxlxm** [comment]
very nice to see we would like to do this!
 
but these flags without dynamic update would make `vmagent` hard to use actually. 
* each member's issue would leads us to lose 1/n scrape within the down time.
* inconvenience for the cluster to shrink/grow. e.g. hpa with k8s.

maybe we can do it better.  
* add `-promscrape.cluster.token` flag use to join the cluster we want. disable cluster feature if empty.
* add `-promscrape.cluster.addrs` flag to set `load balancer` or `headless service` or every instance's addr for join.
* add `-promscrape.cluster.retryInterval` flag to set retryJoin interval.
* add `/cluster/join`,`/cluster/leave` endpoint to handle cluster shrink/grow events.

WDYT, @valyala

**Comment by valyala** [comment]
I'm afraid the schema with dynamic membership management of `vmagent` instances in the cluster goes against the the points you mentioned in the initial message. Such a schema has lower availability and debuggability in practice when compared to the [schema supported in vmagent starting from v1.55.0](https://victoriametrics.github.io/vmagent.html#scraping-big-number-of-targets). For example, the dynamic membership schema is vulnerable to the following hard-to-debug and hard-to-fix practical issues:
* Network splits, when `vmagent` instances temporarily lose connectivity between each other.
* Network delays, when the information about cluster configuration becomes out of sync on each `vmagent` instance. This may lead to consistency issues when some targets are simultaneously scraped by multiple `vmagent` instances while other targets aren't scraped by any `vmagent` instances.
* Operator errors, when unexpected `vmagent` instances mistakenly join the cluster (for example, staging instances join production cluster).

> each member's issue would leads us to lose 1/n scrape within the down time

`vmagent` may delay the first scrape after the start for up to `scrape_interval` (e.g. [one minute in default case](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file)). This time should be enough for `vmagent` restart in practical cases.

> inconvenience for the cluster to shrink/grow. e.g. hpa with k8s.

I'm unsure that the number of `vmagent` instances in the cluster needs to be changed frequently. So it should be OK to shut down all the `vmagent` instances before starting new ones in the case of cluster resize event.

**Comment by sc7565** [comment]
How can this be implemented in k8s and helm-charts?

**Comment by mxlxm** [comment]
> * Network splits, when vmagent instances temporarily lose connectivity between each other.
> * Network delays, when the information about cluster configuration becomes out of sync on each vmagent instance. This may lead to consistency issues when some targets are simultaneously scraped by multiple vmagent instances while other targets aren't scraped by any vmagent instances.

I think this depends on how we choose from CAP.
gossip IMO is an AP solution, does have these issues.
but if we choose CP, raft bases cluster can avoid these issues. 

> * Operator errors, when unexpected vmagent instances mistakenly join the cluster (for example, staging instances join production cluster).
 
this is why we need `-promscrape.cluster.token` flag here.

> vmagent may delay the first scrape after the start for up to scrape_interval (e.g. one minute in default case). This time should be enough for vmagent restart in practical cases.

for clusters deployed out of k8s, node failure or sth else like OOM without auto-restart static `membersCount` may increase this time to hours.

**Comment by mxlxm** [comment]
> How can this be implemented in k8s and helm-charts?

for the current schema, we can use statefulset, use `replicas` as `membersCount`, and pickup `sequence no`+1 from pod name as `memberNum` .

**Comment by xiaozongyang** [comment]
Sharding targets among alive `vmagent` instances may not be a good solution. IMO, there is a limit to the number of targets which a single `vmagent` is able to scrape, i.e. the upper bound of scraping ability. If we dispatch targets among `vmagent` instances whose cluster size is dynamic, a single instance will be overwhelming easily and keep restarting. 

In an extreme case, some instances are ready and join the gossip cluster early, these instances will get enormous targets that exceed the capacity of any single instance. They will crash or be killed due to `OOM`, so there will never be enough instances as we expected.

ping @mxlxm @valyala

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent.html) already supports sharding of scrape targets among multiple instances - see [these docs](https://docs.victoriametrics.com/vmagent/#scraping-big-number-of-targets).

If you just push data to vmagent via [one of the supported push protocols](https://docs.victoriametrics.com/vmagent/#how-to-push-data-to-vmagent), then it is easy to scale horizontally a cluster of `vmagent` instances by hiding them behind some load balancer such as [vmauth](https://docs.victoriametrics.com/vmauth/).

TL;DR; we aren't going to add fancy schemes for dynamic cluster configurations (e.g. various gossip, raft, paxos, etc. protocols), since they are hard to implement properly, hard to debug and easy to misconfigure and mis-use. See [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1084#issuecomment-789209875) for more details.

Closing the issue as won't implement.
