### ISSUE TITLE
Use SemVer for Cluster Docker images

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#110]
VM uses prefix+commit hash for docker versioning this is not really useful. Need to switch cluster versioning to semver

**Comment by valyala** [comment]
This process has been started with tag [v1.23.0-cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/v1.23.0-cluster).
Commands to create `v1.23.0-cluster` docker images:
```
git checkout v1.23.0-cluster
make package
```

This will build the following docker images:
```
victoriametrics/vminsert:v1.23.0-cluster
victoriametrics/vmselect:v1.23.0-cluster
victoriametrics/vmstorage:v1.23.0-cluster
```

In order to publish the docker images on docker hub, run `make publish`.
