### ISSUE TITLE
Question: Why is VictoriaMetrics timestamp precision millisecond (ms) only instead of nanosecond (ns)?

### ISSUE THREAD

**Issue by jhgoodwin** [VictoriaMetrics/VictoriaMetrics#1105]
Hi,

I was talking with a friend who was interested in using VictoriaMetrics, but noticed there is only millisecond (ms) precision for timestamps versus nanosecond (ns).

Is there a special reason?

Naively, it looks like someone can simply search for "/ 1000" or "/ 1e6" and find most of the places affected.

In his use case, he would need ns level precision and would like to treat it as a normal time.

**Comment by valyala** [comment]
There are the following reasons for using millisecond precision intead of nanosecond precision in VictoriaMetrics:
- originally it has been designed for storing monitoring and telemetry data. The majority of such data doesn't need higher than millisecond precision.
- originally VictoriaMetrics has been deisgned as a remote storage for Prometheus. The Prometheus itself has millisecond precision for timestamps.
-  Higher precision for timestamps may significantly decrease compression ratio for the stored data, since more digits must be processed and saved per each timestamp.

**Comment by jhgoodwin** [comment]
If someone wanted to add this feature in, do you have any suggestions?

It seems like a person could make it an option, but unless there is thought about how to upgrade the existing data, it would be safest to disallow changing the option on any existing database.

**Comment by valyala** [comment]
I'm afraid it can be too late for adding an option for increasing timestamp resolution into VictoriaMetrics, since the millisecond timestamp precision is wired at low levels of VictoriaMetrics architecture. Probably it would be better creating a fork and trying to switch it to higher-precision timestamps there.

Also it would be great to know more information about the use case for high-precision timestamps.

**Comment by ericharding** [comment]
Hi Valyala,
I talked with jhgoodwin about this a while ago because I was looking into options for storing prices and a variety of associated metrics coming from stock exchanges. This data is broadcast out over udp multicast at high enough speed that nanosecond precision is really needed for full detail.  Then I compute a few related values at each tick and it's very useful to plot those together over the course of a day and still be able to drill down to see the results of specific actions and how they affected the market.  

At first glance the performance and storage efficiency of VictoriaMetrics seemed like a good fit but the timestamp granularity was a show stopper.  There may be other show stoppers too, but this was what I ran into first.

**Comment by grayswander** [comment]
Hello, @valyala 

We are interested in evaluating VM as TSDB, for high frequency events analysis.
We would be more than glad to pay for Enterprise or SaaS version.

The show stopper now is precision and the ability to update metrics (we live in a world of unreliable sensors). 
We are ready to fork and implement all the lacking functionality ourselves, but we don't have capacity for long-term self-support.

If this functionality can be integrated in mainstream, after thorough testing, of course, this might be for our mutual benefit.

Would VictoriaMetrics be interested in such scenario?

**Comment by MaxThom** [comment]
I am also facing the same dilemma. I would like to replace influxdb or questdb with vm, but the precision is a stopper. Im in the aerospace business for rocket launch and satellite constellation.

**Comment by valyala** [comment]
We tried adding nanosecond precision for timestamps in VictoriaMetrics, but, unfortunately, this couldn't be done without breaking backwards compatibility :( So closing this feature request as won't implement.

P.S. It shouldn't be hard making a fork of VictoriaMetrics and changing millisecond precision for timestamps to nanoseconds, without maintaining backwards compatibility with the original VictoriaMetrics. We'll be glad referring this fork in our documentation.

**Comment by 0lionelzhang0** [comment]
Hello! Just wanted to add that we (also aerospace company) would also be very interested in this feature for our high rate data. Also more than happy to pay for Enterprise version with nanosecond timestamps.
