### ISSUE TITLE
Cluster Version: add auth key for delete series endpoint 

### ISSUE THREAD

**Issue by oOHenry** [VictoriaMetrics/VictoriaMetrics#1118]
The single node version provides the flag `-deleteAuthKey` to protect the delete series endpoint. But the cluster version don't has this flag.

**Comment by valyala** [comment]
The cluster version doesn't provide [authKey-based protection for various endpoints](https://victoriametrics.github.io/#security), because it is expected that such protection must be enforced at per-tenant level. E.g. each tenant can have distinct auth keys. If you need closing access to various sensitive endpoints in cluster version, then this must be done at a proxy sitting in front of `vmselect` nodes. This can be either specialized proxy such as [vmauth](https://victoriametrics.github.io/vmauth.html) or any other general-purpose proxy such as `nginx`.

**Comment by oOHenry** [comment]
Thx for explaining. I'll close this issue then.
