### ISSUE TITLE
Regular expressions in vmauth don't seem to be supported while documented so

### ISSUE THREAD

**Issue by istolpov** [VictoriaMetrics/VictoriaMetrics#1160]
# What

Documentation in https://victoriametrics.github.io/vmauth.html#auth-config suggests it is possible to have "/api/v1/label/[^/]+/values" route, while it doesn't seem the case.

# Reproduce

```
[root@vm00836 ~]# curl localhost:8427/api/v1/label/host/values -u ********
remoteAddr: "127.0.0.1:57134"; cannot determine targetURL: missing route for "/api/v1/label/host/values"

[root@vm00836 ~]# curl 'localhost:8427/api/v1/label/\[^/\]+/values' -u ********
{"status":"success","isPartial":false,"data":[]}
```
This suggests direct comparison of strings...

# Where
...and indeed:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3a8b2eed58df3619409064558f1a1cf8e24e5ecb/app/vmauth/target_url.go#L22

# Questions
Will the lack of `/label/[^/]+/values` impact Grafana's ability to provide contextual help in requests and query all values of the label? If so, is there workaround to make this work?

# Notes
In current https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3a8b2eed58df3619409064558f1a1cf8e24e5ecb/app/vmauth/README.md this regexp possibility is not stated. This suggests documentation mismatch, maybe the regex option has been removed in the past.

**Comment by valyala** [comment]
`vmauth` gained support for regular expressions starting from `v1.56.0` - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1112 . It looks like you refer the code from old version of `vmauth`, since the code for the latest version is here: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3be0e6b0878ed74e03c70f5d6ff217d69629c977/app/vmauth/target_url.go#L20-L26

**Comment by istolpov** [comment]
Ok, my bad, thanks for the explanation. For some reason I thought I looked at master branch.
