### ISSUE TITLE
Delete Data within the Specified time range

### ISSUE THREAD

**Issue by lv254165754** [VictoriaMetrics/VictoriaMetrics#1176]
It seems impossible to delete data within a specified time range in VictoriaMetrics.

But our IoT devices occasionally write the wrong data（Multiple time series are involved）.
Is there any way to delete the wrong data？

I referred to this issue[Delete time series in range time #164](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/164)
This is effective when time series and data points are relatively small.
But this seems difficult, with many time series having nearly a year's worth of data

**Comment by denisgolius** [comment]
@lv254165754 thanks for issue. The answer is the same - you can't delete the wrong data from VictoriaMetrics.😔

**Comment by lv254165754** [comment]
> @ lv254165754感谢您的问题。答案是相同的-您无法从VictoriaMetrics删除错误的数据。😔

Would you consider supporting this feature？ 
I don't know if that's technically possible.

**Comment by valyala** [comment]
Deleting time series on a specific time range is possible to implement, but it can be hard to implement due to the currently used architecture.

The workaround is to delete the whole time series and then re-insert the needed time series according to [these](https://victoriametrics.github.io/#how-to-delete-time-series) and [these](https://victoriametrics.github.io/#backfilling) docs.

**Comment by HosseyNJF** [comment]
If anyone needs a tool to help them deleting the unwanted time-series, I created one here: https://gist.github.com/HosseyNJF/5ca033f594469253f7d49525c1a02e78

**Comment by SRE-Rick** [comment]
不小心执行了curl -s' http://vmselect:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series?match[]=process_cpu_cores_available'  但是还未执行数据合并，可以恢复被删除的数据吗
