### ISSUE TITLE
Replication in Cluster Version

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#118]
Cluster version has no replication which is required for HA setup. There are several workaround but there is no internal solution.

Workarounds are explained [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#high-availability).

Let's use this issue to discuss the approach and decide what we are going to use.

**Comment by valyala** [comment]
See also the followimg docs about the current state of replication in cluster version of VictoriaMetrics:

- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#cluster-availability 
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#replication-and-data-safety

**Comment by gregwebs** [comment]
The current documentation doesn't properly state the limitations of the workarounds.

Currently the documentation recommends 2 HA setups. In the first, Victoria Metrics is HA, but Prometheus is not. The 2nd discusses running Prometheus pairs:

> If you have Prometheus HA pairs with replicas r1 and r2 in each pair, then configure each r1 to write data to victoriametrics-addr-1, while each r2 should write data to victoriametrics-addr-2.

AFAICT if r2 is down then the data will exist only in vm1 but not in vm2. This creates a permanent lower availability for data recorded during that period of data.

Similarly, if vm1 is down longer than r1 will queue its writes, there will be a permanent lower availability for data recorded during that time period.

So the HA setup can tolerate 1 AZ going down. However, it cannot tolerate 1 AZ going down temporarily at one time and then the other AZ going down temporarily at any other time. When the other AZ goes down, data will be unavailable.

To solve the issue of 1 Prom going down it seems like it might be possible for both Prom to write to both VM if VM can deal with duplicate writes. But to solve the issue of one VM going down it seems that some kind of data replication is required.

**Comment by valyala** [comment]
> AFAICT if r2 is down then the data will exist only in vm1 but not in vm2. This creates a permanent lower availability for data recorded during that period of data.

Correct. This scheme provides the same level of availability as Prometheus HA pairs - [the recommended approach for HA setup in Prometheus world](https://prometheus.io/docs/introduction/faq/#can-prometheus-be-made-highly-available), when a pair of identically configured Prometheus instances scrape the same set of targets across the same availability zone.

> To solve the issue of 1 Prom going down it seems like it might be possible for both Prom to write to both VM if VM can deal with duplicate writes.

This case is frequently asked by VictoriaMetrics users, so, hopefully, it will be implemented soon. Possible solution is to accept `-minScrapeInterval` flag value and to de-duplicate data points with timestamps closer than this value for each time series.

>  But to solve the issue of one VM going down it seems that some kind of data replication is required.

This issue has low priority when VictoriaMetrics is used as long-term storage for Prometheus, since Prometheus can [tolerate up to 2 hours of unavailability of remote storage](https://grafana.com/blog/2019/03/25/whats-new-in-prometheus-2.8-wal-based-remote-write/) and then write the buffered data when the remote storage becomes available.

**Comment by valyala** [comment]
FYI, cluster version of VictoriaMetrics supports application-level replication starting from [v1.36.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See more details about the replication [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#replication-and-data-safety).

Closing this issue as done.
