### ISSUE TITLE
High memory usage for vmsingle 1.57.1

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1191]
Hi there,
I have just upgraded vmsingle from 1.51.0 to 1.57.1 and I saw the difference in memory consumption between version 1.51.0 and 1.57.1.
When I use vmsingle 1.51.0, memory usage is about 10Gi, but vmsingle 1.57.1 is about 15Gi.
The active time series is about 5Mil in both case.
![Screenshot from 2021-04-07 09-23-42](https://user-images.githubusercontent.com/1458400/113804089-0a5ac780-9788-11eb-8075-9fec4b5b437f.png)

Could you plz help me?
Thanks.

**Comment by valyala** [comment]
@vuxuanlai , could you share memory profile from VictoriaMetrics `v1.57.1` when it consumes 15GB of RAM? See [how to collect memory profile](https://victoriametrics.github.io/#profiling). It is OK to attach the memory profile in the comment to this issue, since the profile doesn't contain any confidential information.

**Comment by vuxuanlai** [comment]
Hi @valyala ,

This is my [mem.pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6275477/mem.pprof.zip)
I used helm to deploy VM and the extraArgs as below:
![Screenshot from 2021-04-08 08-59-11](https://user-images.githubusercontent.com/1458400/113957120-de534b00-9848-11eb-9847-d75e77e4d42e.png)
- Dashboard for active time series:
![Screenshot from 2021-04-08 09-01-34](https://user-images.githubusercontent.com/1458400/113957262-18245180-9849-11eb-8c72-ada8512f1643.png)
- Dashboard for time series churn rate during the previous hour.
![Screenshot from 2021-04-08 09-03-30](https://user-images.githubusercontent.com/1458400/113957385-53bf1b80-9849-11eb-890b-dcd612439df2.png)
- Total number of (timestamp, value) data points in the database.
![Screenshot from 2021-04-08 09-04-22](https://user-images.githubusercontent.com/1458400/113957455-73eeda80-9849-11eb-9efd-12f8eca5cd70.png)
- Ingestion rate:
![Screenshot from 2021-04-08 09-05-23](https://user-images.githubusercontent.com/1458400/113957536-9aad1100-9849-11eb-84de-5ee71ccaee53.png)
- The number of slow inserts during the last 5 minutes:
![Screenshot from 2021-04-08 09-07-21](https://user-images.githubusercontent.com/1458400/113957668-dcd65280-9849-11eb-82a3-29071231f685.png)
- The number of slow loads of metric names during the last 5 minutes:
![Screenshot from 2021-04-08 09-08-02](https://user-images.githubusercontent.com/1458400/113957731-f4add680-9849-11eb-9a30-a91ab35389dd.png)

**Comment by valyala** [comment]
@vuxuanlai , thanks for the provided memory profile and graphs. The memory profile shows that the majority of memory is spent on the cache, which map metrics to internal series id on data ingestion. The size of this cache is proportional to the number of active series, which receive new samples during the last hour. Your workload has up to 6 million of active series. Usually this amount of series would require up to 6GB of RAM for the cache. The actual cache size can differ, since it depends on the average length of metric names plus all its labels for all the active time series. The size of the cache should remain the same between v1.51.0 and v1.57.1. So it is likely the additional memory usage is related to something else.

VictoriaMetrics has been switched from Go1.15 to Go1.16 in `v1.54.0`. Probably the new version of Go runtime needs more memory for bookkeeping. Try setting environment variable `GOGC=50` when starting VictoriaMetrics v1.57.1 and see whether this reduces memory usage.

Try also upgrading to [v1.58.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and running VictoriaMetrics with `-sortLabels` command-line flag. This flag can help reducing the size of the cache described above if metrics are ingested with random order of labels. See [the release notes](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) for details.

**Comment by vuxuanlai** [comment]
Thanks for your reply. I'll try v1.58.0 and observe it.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if the problem still exists.
