### ISSUE TITLE
cannot acquire lock on file "/storage/flock.lock": resource temporarily unavailable

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1214]
Hi there,
I'm facing issue as title when I update vmsingle chart.
```
{"ts":"2021-04-14T05:15:01.042Z","level":"fatal","caller":"VictoriaMetrics/app/vmstorage/main.go:86","msg":"cannot open a storage at /storage with -retentionPeriod=10d: cannot acquire lock on file \"/storage/flock.lock\": resource temporarily unavailable"}
```
vmsingle version: 1.58.0

**Comment by valyala** [comment]
This error usually means that another instance of VictoriaMetrics already runs and holds the lock on the `/storage/flock.lock` file. @f41gh7 , probably the upgrade procedure in [vmsingle helm chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single) doesn't wait until old instance is stopped?

**Comment by vuxuanlai** [comment]
Upgrading take a long time to finish. I resolved this case how scale vmsingle to 0 and wait about 5mins and then scale vmsingle to 1.

**Comment by shuaiganzi** [comment]
In a Kubernetes cluster, I deploy in vmsingle mode + CephFS + single-instance fashion. When a node malfunctions and goes down, the new pod can never start. Is this normal, and when will the lock be released?

**Comment by jiekun** [comment]
Hello @shuaiganzi, have you checked whether the `flock.lock` was still there after the previous pod was down? I don't have more context why it happens, but let's say if the file lock was not released properly (e.g. a ungraceful exit), and another pod was started and tried to access the file lock, then this could happen.

I'd like to know how the previous pod exited. Do you have the logs when it exits? I think it can only be considered as a bug if it happens after a graceful shutdown. Otherwise, you may need to manually handle the file lock.
