### ISSUE TITLE
Question about the vmstorage

### ISSUE THREAD

**Issue by weinux2020** [VictoriaMetrics/VictoriaMetrics#1231]
Hi, I have a vm-cluster, config  multiple vmstorage for vminsert and vmselect,  How is data stored and how to locate data? Like the hdfs? Thanks very much!

**Comment by valyala** [comment]
vminsert spreads incoming data among the configured `-storageNode` nodes. It uses consistent hashing over metric name plus all its labels for determining the vmstorage node to send data to. This means that all the data for the same metric (aka time series - it is identified by its name plus all its labels) usually goes to the same vmstorage node. This improves compression level for the stored data and improves query performance.

Data for the same time series can be spread among multiple vmstorage nodes under certain conditions:
* When the destination vmstorage node is temporarily unavailable or cannot keep up with the ingestion rate. Then new data is re-routed to the remaining vmstorage nodes.
* When new `-storageNode` entries are added to `vminsert` startup config. Then new data for a part of time series is written to new vmstorage nodes.

vmselect queries all the vmstorage nodes listed in `-storageNode` configs in parallel. There is no need in locating the data or the storage node with the data on yourself.

**Comment by weinux2020** [comment]
Thank you very much, looks a little bit like glusterfs.

**Comment by weinux2020** [comment]
@valyala 
Additional question:
If a vmstorage node is nearly full, the vminsert will automatically send data to other vmstorage node, and query request to this  vmstorage node provide data  unaffected , Is that right？
Thanks！

**Comment by valyala** [comment]
@weinux2020 , victoriametrics doesn't provide such functionality yet - vminsert continues writing data to all the vmstorage nodes even if some of them have no enough space. It is expected that every vmstorage node should have at least 20% of free space for `-storageDataPath` directory. This free space is needed for background merging of the stored data files into bigger files. See [this article for technical details](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282). If there is no enough free space for background merging, then the number of data files increases and this may result in slow down for both data ingestion and querying.

**Comment by weinux2020** [comment]
@valyala 
Thanks a lot, and what can I do when the vmstorage node is full? Only expand the disk?

**Comment by valyala** [comment]
> what can I do when the vmstorage node is full? Only expand the disk?

There are the following options:
* To expand the disk
* To remove unneeded data. This can be done by stopping vmstorage and then deleting unneeded directories under `<-storageDataPath>/data/{small,big}` directories. Every such sub-directory contains month-worth data and has a `YYYY_MM` name, where `YYYY` is the year and `MM` is the month. It is OK to remove these directories when `vmstorage` isn't working. It is also possible to remove sub-directories inside `YYYY_MM` directories. They have the following names: `rowsNum_blocksNum_YYYYMMDDHHMMSS.XXX_YYYYMMDDHHMMSS.XXX_randomHexNum`, where `YYYYMMDDHHMMSS.XXX_YYYYMMDDHHMMSS.XXX` is the time range for the data stored in the sub-directory.
* To re-configure `vminsert` nodes to skip vmstorage nodes with disk space shortage, e.g. just remove these nodes from `-storageNode` lists passed to `vminsert` nodes. The vmstorage nodes can be returned back to `-storageNode` lists for `vminsert` nodes when the old data is automatically deleted due to the configured `-retentionPeriod`.

**Comment by weinux2020** [comment]
@valyala 
That is helps me a lot, Thanks!

**Comment by valyala** [comment]
> If a vmstorage node is nearly full, the vminsert will automatically send data to other vmstorage node, and query request to this vmstorage node provide data unaffected , Is that right？

FYI, `vmstorage` gains support for `-storage.minFreeDiskSpaceBytes` command-line flag starting from [v1.67.0](https://docs.victoriametrics.com/CHANGELOG.html). This command-line flag instructs `vmstorage` to stop accepting new data when the `-storageDataPath` directory has less than the given amounts of free disk space. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/269 for details. See also [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#readonly-mode).

Closing this issue as answered.
