### ISSUE TITLE
Potential memory leak in vmagent=1.58.0

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#1235]
We tried to update vmagent from version 1.57.1 to 1.58.0, and got a steadily reproducing memory leak. Usually vmagent on our load profile uses about 20 Gb of ram, but on v1.58.0 it reaches 100+ Gb in couple minutes after start, and being killed by OOM.
Also, for some reason following metrics are starting to grow:
  - vmagent_remotewrite_pending_data_bytes
  - vm_persistentqueue_bytes_dropped_total

So also seems we have problems with sending data to vminserts.

Downgrade to v1.57.1 fixes everything. I tried the update / downgrade several times, it reproduces stably.

Sent the memory profiles to info@victoriametrics.com

**Comment by valyala** [comment]
Thanks for the provided memory profiles! These profiles show that `vmagent` v1.58.0 scrapes targets with bigger number of metrics compared to `vmagent` v1.57.1 . Could you share graphs for the following query on a time range covering v1.57.1 and v1.58.0 runs?

`topk(5, max(max_over_time(scrape_samples_scraped)) by (instance))`

The graph should show top targets with the maximum number of metrics.

It would be great also to share the graph on `sum(max_over_time(scrape_samples_scraped))` on the same time range. The graph shows the summary number of metrics scraped by vmagent across all the targets. It shouldn't change after the upgrade from v1.57.1 to v1.58.0 under normal conditions.

Probably `vmagent` v1.57.1 didn't scrape some targets with big number of metrics due to some bugs in service discovery. It is recommended using `stream_parse: true` option for scrape targets exposing big number of metrics (more than a few thousand) in order to reduce memory usage during scraping. See [these docs](https://docs.victoriametrics.com/vmagent.html#troubleshooting) for more details.

**Comment by wf1nder** [comment]
`topk(5, max(max_over_time(scrape_samples_scraped)) by (instance))`:

![Screenshot 2021-04-22 at 14 40 10](https://user-images.githubusercontent.com/4486762/115710019-8e14d680-a37a-11eb-8eb0-0e9b69ae3423.png)

`sum(max_over_time(scrape_samples_scraped))`:

![Screenshot 2021-04-22 at 14 41 25](https://user-images.githubusercontent.com/4486762/115710050-98cf6b80-a37a-11eb-95a2-3f1571ee8b40.png)

So looks like the amount of metrics is about the same. Also we do not see that any metrics are not collected or missing.

For some reason, it took longer today to run out of free memory: almost an hour, although yesterday it took a couple of minutes. It may have something to do with the fact that during yesterday's experiments, one of the targets for sending (vminsert) was unavailable. Maybe memory consumption may be affected by the fact that the lot of data is cached in the buffer for sending, or something.

![Screenshot 2021-04-22 at 14 52 15](https://user-images.githubusercontent.com/4486762/115710156-b4d30d00-a37a-11eb-839c-95b4d66ccdf4.png)

We tried to enable stream_parse earlier, but it was rolled back: in this mode, the timeout calculation works in a way that is not obvious to us: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1017#issuecomment-767235047

**Comment by f41gh7** [comment]
May i ask you to plot graphs for the following metrics with 1.58.0: 
```
process_resident_memory_anon_bytes
process_resident_memory_file_bytes
go_memstats_sys_bytes
go_memstats_heap_inuse_bytes
```

**Comment by wf1nder** [comment]
Sure, drew graphs for this and some more metrics:

![Screenshot 2021-04-23 at 09 17 45](https://user-images.githubusercontent.com/4486762/115827876-9706b600-a415-11eb-9924-cfb877aff9af.png)

At 6:46 upgraded 1.57.1 > 1.58.0, and at 8:03 downgraded back to 1.57.1
For some reason, this time the memory consumption did not reach the RAM limit in the container, but it was still high. Also, as you can see, some of the data to send to vminserts is dropped with v1.58.0.

**Comment by f41gh7** [comment]
@wf1nder  thanks!  

 One more question, did you change default value for flag `remoteWrite.queues` ? 

 And what about metric - `vmagent_remotewrite_retries_count_total` did it increase?

**Comment by valyala** [comment]
Try increasing `-remoteWrite.queues` command-line flag by 2x on v1.58.0 and see whether memory usage decreases in this case. If you didn't set `-remoteWrite.queues`, then set it to 10.

**Comment by valyala** [comment]
Try also building `vmagent` from the commit 52b4b1605eeb4384a78054132a7ac01cada8bb0a and verifying whether it uses lower amounts of memory when `-remoteWrite.queues` command-line flag is set to the value used for `vmagent` v1.57.1 .

**Comment by wf1nder** [comment]
> And what about metric - vmagent_remotewrite_retries_count_total did it increase?

No, it is always 0, even when vmagent reaches OOM, on all versions and "-remoteWrite.queues" values.

Thank you for your answers.

Today we began to catch an increasing in memory consumption and OOMs also on version 1.57.1 too :(

Yes, we previously increased the value of the "-remoteWrite.queues" setting to 3. Today, on your advice, I increased it to 10, and the problem went away on version 1.157.1: the memory consumption reaches about 40 Gb, as previously, and the growth stopped, everything is back to normal.

Then I did some experiments.

v1.58.0 with increased "-remoteWrite.queues=10": uses about 20-40 Gb long-term (about a hour), on average about 25 Gb. This is even less than was on v1.57.1! Everything fine, no OOMs, no growing of persistant queues.

Then I builded vmagent from master, which includes commit 52b4b16 as you asked.
With "-remoteWrite.queues=3" (as we used previously): it allocated about 50 Gb on start, persistant queue size began to grow immediately after start, and soon drops are began to appear. The memory consumption was about 50 Gb entire all the time it was running (30 mins). No OOMs, but problems with sending data to vminserts (queues size growth and drops appeared).

And version from master with "-remoteWrite.queues=10": everything totally fine, like on version 1.58.0 with "-remoteWrite.queues=10": no drops, queue size is 0. Memory consumption is in 20-40 Gb interval, mostly near 25.


It seems that the problem was in small number of configured queues. After increasing it to 10, everything returned to normal on all versions of vmagent. On 1.58.0 it uses even less memory.

Thank you!

Is there a right way to calculate the correct value of setting "-remoteWrite.queues" instead of setting it up empirically?

**Comment by wf1nder** [comment]
Enabled ```stream_parse: true```, and now it consumes 6 Gb of RAM. This is a significant optimization :)

**Comment by valyala** [comment]
> Is there a right way to calculate the correct value of setting "-remoteWrite.queues" instead of setting it up empirically?

The optimal value for `-remoteWrite.queues` depends on the following factors:
* The rate at which samples are sent to `-remoteWrite.url`. Higher rate usually needs higher `-remoteWrite.queues` value, since every queue (aka a connection to remote storage) has a limited bandwidth.
* The network latency between `vmagent` and remote storage pointed by `-remoteWrite.url`. Higher network latency requires higher `-remoteWrite.queues` value, since `vmagent` sends a packet and waits for the response from the storage before sending the next packet on a single queue. High network latency reduces the maximum bandwidth that can be achieved by a single connection.
* The remote storage performance for processing incoming data per single connection. Slower per-connection performance may need higher `-remoteWrite.queues` value.

Note that too high `-remoteWrite.queues` value can result in increased resource usage on both `vmagent` and remote storage sides. So it is recommended keeping it quite low.

The best indicator which shows that the `-remoteWrite.queues` value must be increased is `Persistent queue size` graph from the [official dashboard for vmagent](https://docs.victoriametrics.com/vmagent.html#monitoring) - if it shows non-zero values for extended periods of time, then it is likely `-remoteWrite.queues` value must be increased.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if the problem still exists.
