### ISSUE TITLE
victoriametrics v1.58 indexdb takes a lot more disk space than in earlier versions

### ISSUE THREAD

**Issue by MaxIsaev78** [VictoriaMetrics/VictoriaMetrics#1241]
**Describe the bug**
A while back, I installed victoriametrics 1.28, replaced our Prometheus with victoriametrics + vmagent on a test environment. It ran for a couple of months. Then we decided to install on new servers the latest victoriametrics  (1.58). With the same amount of targets and metrics as in our test env, we noticed that vm is taking up a lot more disk space than 1.28 version in our test env.
The issue seems to be with the indexdb folder under data directory of vm, which is in the latest version is 3 times bigger than the data folder.

To demonstrate the difference, I installed on 2 servers victoriametrics + vmagent (1.28 and 1.58 respectively, the vmagent version is the same on both servers). The amount of scrape targets and metrics is the same. Nothing reads from either victorimetrics.

Here is what disk usage looks like after a week:

Server 1 (v1.58):

53G     data
0         flock.lock
156G   indexdb
8.0K    metadata
4.0K    snapshots
8.0K    tmp
16K     vmagent-remotewrite-data

Server 2 (v.1.28)

45G     data
0       flock.lock
65G     indexdb
4.0K    snapshots
8.0K    tmp
16K     vmagent-remotewrite-data

**To Reproduce**
Install 1.58 vm

**Expected behavior**
Less space is occupied by indexdb

**Version**
```
Server 1
$ ./victoria-metrics-prod --version
victoria-metrics-20210408-064138-tags-v1.58.0-0-gedd1590ac

Server 2 
$ ./victoria-metrics-prod --version
victoria-metrics-20191009-135323-tags-v1.28.0-0-gf6334bff
```

**Used command-line flags**
The same flags on both servers:

--storageDataPath=/data/victoriametrics --maxInsertRequestSize=134217728 --search.maxUniqueTimeseries=1000000

**Comment by f41gh7** [comment]
Hello, disk usage for indexdb looks abnormal for both versions, usually it consumes 1/3 or 1/4 of data folder size. Seems like, you are storing high cardinality metrics. You can check at official grafana dashboard - troubleshooting section `churn rate` panel. 
  
  But increased indexdb disk usage is expected for newer release. Because 1.58 version has additional indexes, that must reduce queries latency and increase queries throughput.

**Comment by MaxSamsonov** [comment]
@f41gh7 Hello! Please advise if it's possible to get further details on index usage (Ex: what metrics are using most space or smth like this)

Thank you.

**Comment by dmitryk-dk** [comment]
Hi @MaxSamsonov ! Try to use [cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer). It shows how is metrics the number of unique time series stored in a time series database (TSDB).

**Comment by valyala** [comment]
VictoriaMetrics stores the following information in `indexdb`:

- `MetricName -> series_id` mapping, where:
  - `MetricName` is the canonical name for [time series](https://docs.victoriametrics.com/keyconcepts/#time-series). It consists of metric name plus all the `key="value"` labels for this time series, sorted alphabetically. For example, canonical name for the time series `up{job="foo",pod="123",instance="bar"}` is `up{instance="bar",job="foo",pod="123"}`;
  - `series_id` is the internal id, which uniquely identifies every time series seen by VictoriaMetrics during data ingestion.
  This mapping allows locating `series_id` by `MetricName` during data ingestion.
- `series_id -> MetricName` mapping, which is used for locating `MetricName` by `series_id` when VictoriaMetrics needs to return query results with all the original time series names and labels.
- `label => series_id` mapping per each `key="value"` label per each time series seen during data ingestion. For example, a time series is `up{foo="1",bar="baz"}` creates three `label -> series_id` entries in `indexdb`:
  - `{__name__="up"} -> series_id` - see [these docs](https://docs.victoriametrics.com/keyconcepts/#labels) about `__name__`
  - `{foo="1"} -> series_id`
  - `{bar="baz"} -> series_id`
  This mapping allows quickly locating time series by the given [series selectors](https://docs.victoriametrics.com/keyconcepts/#filtering). This mapping is known as "inverted index".
- Other auxiliary entries, which help increasing query performance.

As you can see, every new [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) creates many entries in `indexdb`. The number of entries is proportional to the average number of labels per each ingested time series. The size of `indexdb` is proportional to the total size of all the `MetricName` entries. Longer labels / label values lead to bigger `indexdb`. That's why it is important reducing [time series churn rate](https://docs.victoriametrics.com/faq/#what-is-high-churn-rate) in order to limit the size of `indexdb`.

`indexdb` size grows even under zero churn rate, since entries mentioned above are created per each day in order to speed up time series search on time ranges over a few days.

Closing the issue as addressed.
