### ISSUE TITLE
Migration from NFS to POSIX fs failed

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#1324]
**Describe the bug**
I plan to migrate the data from nfs to posix fs.

1. stop vmstorage
2. rsync -az /data/xx /ssd/xxx
3. update vmstorage storage path to /ssd/xxx
4. start vmstorage failed, it looks like the file path is stored in a file

```
2021-05-25T08:03:56.009Z	fatal	VictoriaMetrics/app/vmstorage/main.go:70	cannot open a storage at /ssd/alibjg-common-victoriametrics1-vm/vmstorage with -retentionPeriod=12: cannot open indexdb tables at "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb": cannot open curr indexdb table at "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9": cannot open indexDB "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9": cannot open table parts at "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9": cannot run transactions: cannot run transaction from "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/txn/16812028153E055D": invalid path to remove: invalid path "/data/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/813_2_16812028153E054C"; must start with "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/"
```

**Version**
```
vmstorage-20210524-131625-tags-v1.60.0-cluster-0-g25ed1f0c4
```

**Used command-line flags**
```
/home/common/vmcluster/vmstorage -memory.allowedPercent 60 -storageDataPath /data/alibjg-common-victoriametrics1-vm/vmstorage -retentionPeriod 12 -httpListenAddr :9200 -vminsertAddr :9201 -vmselectAddr :9202
```
->
```
/home/common/vmcluster/vmstorage -memory.allowedPercent 60 -storageDataPath /ssd/alibjg-common-victoriametrics1-vm/vmstorage -retentionPeriod 12 -httpListenAddr :9200 -vminsertAddr :9201 -vmselectAddr :9202
```

**Comment by valyala** [comment]
It is likely `vmstorage` has been shut down ungracefully on the first step before copying the data, e.g. without sending SIGINT signal to it and/or without waiting until `vmstorage` is gracefully terminated after receiving this signal. The `vmstorage` should put the following line into the log on successful graceful shutdown: `the vmstorage has been stopped`.

When `vmstorage` isn't shut down gracefully, then it may leave unfinished `transaction files` in `txn` directory. The error message mentions one of these files:
```
cannot run transaction from "/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/txn/16812028153E055D"
```

These files contain instructions on how to substitute old LSM parts with new LSM part in an atomic way after the background merge of old parts into new part is complete. See [this article for technical details](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282). If `vmstorage` is terminated during the transaction, then the transaction is replayed on the next `vmstorage` start. This guarantees that the transaction is performed in an atomic way even on ungraceful shutdown. Unfortunately the transaction couldn't be complete after copying the files to new directory, since the transaction file contains absolute paths to LSM parts instead of relative paths. E.g. these paths point to the old directory. There are the following workarounds for this issue:
* To remove the directory `/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/txn/`. This may result in partial data loss for the parts from the transaction if they were already removed.
* To update paths in all the files under `/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/txn/` directory, so they point to the new directory. For example, to substitute `/data/` prefix with `/ssd/` prefix in all the paths mentioned in all the files under `/ssd/alibjg-common-victoriametrics1-vm/vmstorage/indexdb/167820EAF7A15BD9/txn/` directory. This should guarantee the correctness of the transaction replay on the next start of `vmstorage`.

**Comment by faceair** [comment]
Thank you for your answer.

I added the config to supervisor
```
stopsignal=INT
stopwaitsecs=60
```
to ensure that vmstoregae is gracefully terminated.
I also changed the rsync command add the `--delete` flag: `rsync -av --delete /data/xxx/ /ssd/xxx`

Now I have successfully completed the migration. 🎉
