### ISSUE TITLE
Support for 'at' (@) modifier

### ISSUE THREAD

**Issue by grandich** [VictoriaMetrics/VictoriaMetrics#1348]
Trying to use 'at modifier' produces parsing error.

https://prometheus.io/blog/2021/02/18/introducing-the-@-modifier/
https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier

Example:
`node_arp_entries @ 1622559660000
`

"error when executing query=\"node_arp_entries @ 1622559660000\" for (time=1622560342520, step=300000): cannot recognize \"@ 1622559660000\"; unparsed data: \"node_arp_entries@ 1622559660000\""

**Comment by valyala** [comment]
In the mean time it is possible to use [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) features in order to solve typical tasks for `@` operator:

* Various `topk_{min,max,avg,last}`, `bottomk_{min,max,avg,last}` functions, which return up to `k` time series with the biggest or smallest min/max/first/last values. For example, `topk_last(3, q)` should return up to 3 time series from `q` with the biggest last value on the graph. This is essentially the same as `q and topk(3, q @ end())`. See [topk_last docs](https://docs.victoriametrics.com/MetricsQL.html#topk_last) for details.
* Various `range_{min,max,first,last}` functions, which return the max/min/last value per each time series on the given time range. For example, `range_last(q)` is equivalent to `q @ end()`. See [range_last docs](https://docs.victoriametrics.com/MetricsQL.html#range_last) for details.

**Comment by valyala** [comment]
The `@` modifier is available in VictoriaMetrics starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by tredondo** [comment]
The `@` modifier seems to always return samples at the current instant, regardless of what's specified.

I've filed #2414 with details.
