### ISSUE TITLE
Arbitrary CSV Writes Fail With 204s When One Metric Has an Improper Value

### ISSUE THREAD

**Issue by HisWingsVariable** [VictoriaMetrics/VictoriaMetrics#1349]
**Describe the bug**
```
1. URL: http://localhost:8978/api/v1/import/csv?format=1:label:source,2:label:test,3:metric:X,4:metric:Z
2. POST Data: ‘vm_debug,test_one,40,\n’
3. Alternate POST data: ‘vm_debug,test_one,40,a\n’
```

Given metric X and metric Z:
1. Metric X has a proper value (40)
2. Metric Z has an improper value (blank or 'a' string).

VM, on arbitrary csv write, will return a 204 but will never write the metric which is properly formatted.
In the event that you have a large CSV file with blanks this means that it will never write while VM communicates that all is well in the response. 

The fix is to write in 'nan' instead of blanks
1. POST Data: ‘vm_debug,test_one,40,nan\n’

I got this fix by asking on the Slack channel.

**To Reproduce**
See above.

**Expected behavior**
I would expect for VM to return an error message, as it does when you attempt to insert duplicate labels or metrics.

**Comment by valyala** [comment]
While VM returns 204 http status code when ingesting the incorrect CSV lines, it puts the following error messages in the log:

```
error when parsing csv line "vm_debug,test_one,40,": missing columns in the csv line "vm_debug,test_one,40,"; got 3 columns; want at least 4 columns; skipping this line

error when parsing csv line "vm_debug,test_one,40,a": cannot parse metric value for "Z" from "a": unparsed tail left after parsing float64 from "a": "a"; skipping this line
```

VictoriaMetrics returns 204 http status code when importing incorrectly formatted plaintext line-based data (e.g. [CSV](https://docs.victoriametrics.com/#how-to-import-csv-data), [JSON](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format), [OpenTSDB over http](https://docs.victoriametrics.com/#sending-opentsdb-data-via-http-apiput-requests) and [InfluxDB over http](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)), since it parses and processes each line individually. If a request contains many lines, while only a few lines are incorrectly formatted, then most users expect that all the valid lines are processed and ingested instead of returning the error if only a small percentage of lines cannot be parsed. That's why VictoriaMetrics logs parse errors and continues parsing the rest of lines in the request.

**Comment by NowBothWhiteAndRed** [comment]
Note that the case described in the ticket doesn't lead to the incorrect line being skipped while the correct one being written. Both lines end up not being written. So several hundred lines at a time with a few bad ones results in nothing ending up in VM.

**Comment by HisWingsVariable** [comment]
Correcting above, it's not a question of skipping lines as invalidating a line with an incorrect field.
So for the case below:
```
URL: http://localhost:8999/api/v1/import/csv?format=1:label:source,2:label:test,3:metric:A,4:metric:B,5:metric:C,6:metric:D,7:metric:E,8:metric:F,9:metric:G,10:metric:H,11:metric:I,12:metric:J,13:metric:K,14:metric:L,15:metric:M,16:metric:N,17:metric:O,18:metric:P,19:metric:Q,20:metric:R,21:metric:S,22:metric:T,23:metric:U,24:metric:V,25:metric:W,26:metric:X,27:metric:Y,28:metric:Z

DATA:
'vm_debug,test_one,73,63,62,18,35,78,9,93,60,31,22,28,63,60,2,20,12,95,18,19,80,77,8,1,illegal_value,80
vm_debug,test_one,42,23,65,63,32,3,90,68,68,35,46,60,74,46,91,75,88,91,47,33,96,10,40,92,18,18
'
```

The second line is written while the first one is skipped, as described by you. This is good so long as you want to only write in lines that don't have illegal_values. However, the real world case on my end has data which will always have some values that are missing. In this case, most of the lines would be skipped and I would not know why that this is the case without looking at the logs.

Now that I know that 'nan' is the proper value for a missing field the case is addressed on my end. But I only found that out by asking on slack.

**Comment by valyala** [comment]
> Not sure if it would make sense to return a message that says "n lines skipped due to them having wrong values" in the response.

While such message can be returned in HTTP responses, it cannot be returned when the data is sent over plain TCP or UDP (e.g. InfluxDB line protocol over TCP, Graphite protocol or OpenTSDB protocol over TCP/UDP).

Probably, VictoriaMetrics could accept a special query arg in HTTP requests to import APIs such as `fail_on_error=true`. In this case it could return the parse error on the first occurrence and drop all the previously parsed lines in the request.

**Comment by tredondo** [comment]
I ran into the same issue in #2420. Would it be possible to return an error code if zero records were parsed correctly out of a non-zero amount of input?

**Comment by valyala** [comment]
Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1077 .
