### ISSUE TITLE
vm_merge_need_free_disk_space not updated on 1.60+

### ISSUE THREAD

**Issue by freeseacher** [VictoriaMetrics/VictoriaMetrics#1373]
**Describe the bug**
We rely on `vm_merge_need_free_disk_space` metric for alerting on free space on vm-storage. 
Recently we got alert that we have too low disk space instead of Victoria cant do merges. 
During latest several weeks vm_merge_need_free_disk_space is 0

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
vmstorage-20210609-162833-tags-v1.61.0-cluster-0-g83adc2f3a
```

**Used command-line flags**

/opt/victoria-metrics/vmstorage-prod -bigMergeConcurrency=2 -dedup.minScrapeInterval=15s -finalMergeDelay=0s -httpListenAddr=:8482 -loggerFormat=json -loggerLevel=INFO -loggerOutput=stdout -memory.allowedPercent=60 -retentionPeriod=60 -search.maxUniqueTimeseries=5000000 -smallMergeConcurrency=4 -storageDataPath=/var/lib/victoria-metrics -vminsertAddr=:8400 -vmselectAddr=:8401

**Comment by valyala** [comment]
@freeseacher , could you build `vmstorage` from the commit 8055439fe4955140631b384187e8b67edab6eaee and verify whether it properly detects free disk space shortage and properly updates the `vm_merge_need_free_disk_space` metric? See [build instructions for cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by valyala** [comment]
@freeseacher , could you verify whether VictoriaMetrics properly updates `vm_merge_need_free_disk_space` metric starting from the release [v1.63.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by valyala** [comment]
It has been appeared that the `vm_merge_need_free_disk_space` metric could be reset to 0 when there is no need free disk space for optimal merges, but there are smaller parts exist which could be merged. This should be fixed in the following commits:
* Single-node - c2deee991189c46e9adf233bc0eab3000a023975
* Cluster - 1950f57316ec52a27a8bd356a8b7a76fb783c04b

**Comment by hagen1778** [comment]
Hey @valyala can we close this?

**Comment by valyala** [comment]
I think we can close this issue, since the `vm_merge_need_free_disk_space` metric now should work as expected - it must become bigger than 0 when there is no enough free disk space for optimal merges. Note that this may be OK in some cases - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1980#discussion_r772294658 for more context.

Closing this issue then.
