### ISSUE TITLE
Add option to load configuration file

### ISSUE THREAD

**Issue by KawaiDesu** [VictoriaMetrics/VictoriaMetrics#138]
Hello!

I would like to run VictoriaMetrics like a service via systemd (I'm packaging victoriametrics in the fact), but i don't want to change systemd service file every time i want to change some options. I could use unit override but it doesn't look very convenient. So it would be nice to add an option which loads targeted configuration file in simple format, like ini or maybe yaml.

**Comment by oOHenry** [comment]
Hi @KawaiDesu,
I packaged VictoriaMetrics too, you can solve the problem by using the systemd `EnvironmentFile` option:
```bash
cat /lib/systemd/system/victoria-metrics.service
[Unit]
Description=Prometheus :: victoria-metrics
Requires=basic.target network.target
After=basic.target network.target
Documentation=https://github.com/VictoriaMetrics/VictoriaMetrics
[Service]
User=nobody
Group=nogroup
EnvironmentFile=/etc/default/victoria-metrics-prod
ExecStart=/usr/bin/victoria-metrics-prod $ARGS
ExecStop=/bin/kill -s SIGTERM $MAINPID

[Install]
WantedBy=default.target

cat /etc/default/victoria-metrics-prod
ARGS=-retentionPeriod=24 -storageDataPath /var/lib/victoria-metrics/data
```
Just edit the options in `/etc/default/victoria-metrics-prod` and restart the service.

**Comment by valyala** [comment]
> I would like to run VictoriaMetrics like a service via systemd (I'm packaging victoriametrics in the fact)

There are package scripts for `deb` and `rpm` inside [package](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/package) folder. These scripts are called from Makefile build rules defined in [app/victoria-metrics/Makefile](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/victoria-metrics/Makefile). Probably, you could base your packaging scripts on the code inside `package` folder.

> i don't want to change systemd service file every time i want to change some options. I could use unit override but it doesn't look very convenient. So it would be nice to add an option which loads targeted configuration file in simple format, like ini or maybe yaml.

Agreed. Will think about the implementation for this feature. Something like accepting `-configFile` arg with path to `ini` file where command-line flags may be set.

**Comment by valyala** [comment]
@oOHenry , thanks for the solution! I'm unfamiliar with systemd and packaging for various Linux distros, so your insights are very valuable. Could you inspect the [pacakge](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/package) folder contents and help maintaining it together with the original authors of this folder @patsevanton  and @kmansoft ?

**Comment by valyala** [comment]
@KawaiDesu , just a reference on how to use `EnvironmentFile` option for loading command-line args - https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html#environmentfile-directive .

**Comment by kmansoft** [comment]
Why not implement a config file like `/etc/victoria-metrics.conf`?

Also it makes admin tasks a lot easier if you also support config file snippets in a directory like `/etc/victoria-metrics.d` which take priority over the `.conf` file.

This way the packages can include the `.conf` with a "standard" configuration - and users can override what they want / need using the `.d` directory. Upgrades then will overwrite the `.conf` because it won't be modified but the `.d` files if any will persist.

**Comment by patsevanton** [comment]
@valyala where store config file?
/etc/default/victoria-metrics-prod or /etc/default/victoria-metrics.conf or /etc/victoria-metrics.conf?

**Comment by valyala** [comment]
> @valyala where store config file?

`/etc/victoria-metrics.conf` looks fine to me

**Comment by KawaiDesu** [comment]
Personally, I wouldn't recommend to use `/etc/`.
Archwiki states that
> /etc | **System-essential** configuration files
> /etc/{pkg} | Configuration files for {pkg}

https://wiki.archlinux.org/index.php/Arch_package_guidelines#Directories

So, please, use `/etc/victoriametrics/victoriametrics.conf` or `/etc/victoria-metrics/victoria-metrics.conf` (use one that matches package name with or without hypen).

**Comment by KawaiDesu** [comment]
@oOHenry thanks for suggestion with `EnvironmentFile`. This is nice *workaround* while cli option is not yet implemented.
@valyala thanks for reference link.

**Comment by patsevanton** [comment]
@

**Comment by micoq** [comment]
@valyala A dedicated configuration file might be useful to hide the passwords displayed in the command line (for example with the option `httpAuth.password`).

**Comment by valyala** [comment]
FYI, VictoriaMetrics accepts config args via command-line flags starting from [v1.34.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/311 and [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#environment-variables) for details.

**Comment by Allineer** [comment]
Извините, я по-русски опишу.

Многие пользователи, я уверен, уже сейчас используют файлы с параметрами запуска компонентов VM, прописанные в параметре EnvironmentFile соответствующих systemd *.service файлов. И я так делаю - пример одного из моих файлов параметров для vmagent будет ниже.

У нас уже сейчас есть конфиги `-rule` для vmalert, `-promscrape.config` и `-remoteWrite.urlRelabelConfig` для vmagent и это действительно большие, важные, сложные файлы конфигурации.

В то же время, у нас есть большое число параметров командной строки для каждого компонента.
Да, я помню ваш аргумент, о том, что все они не нужны большинству пользователей - им достаточно прописать retention для хранилища и список таргетов.

Но, как показывает практика (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/576), параметры `-remoteWrite.*` тоже могут быть большим и сложным набором ключей, в котором можно запутаться. В то же время, я считаю костылём-полумерой делать отдельный конфиг только лишь для параметров `-remoteWrite.*`.

Я считаю, что имеет смысл и пришло время все параметры конфигурации всех компонентов vm* вынести в отдельный файл и запускать каждый компонент с единственным ключом `--config=`.
Это позволит структурировать параметры внутри файла, сделать их более понятными и наглядными, избежать множества ошибок.

И да, у одних пользователей содержимое конфига будет состоять из двух-трех параметров, а у кого-то будут простыни. Но конфиги будут понятными и логичными и для тех и для других.

У меня, практически домашнего пользователя, конфиг vmagent состоит из 15 параметров (пример ниже), конфиг valert - из 6 параметров, конфиги нод - из 9 параметров каждый.

```
OPTIONS="                                                 \
  -httpListenAddr=127.0.0.1:8429                          \
  -loggerOutput=stdout                                    \
  -memory.allowedPercent=10                               \
  -promscrape.config.strictParse=1                        \
  -promscrape.config=/.../targets.yaml                    \
  -promscrape.disableCompression=1                        \
  -remoteWrite.maxDiskUsagePerURL=10000000000             \
  -remoteWrite.showURL=1                                  \
  -remoteWrite.tmpDataPath=/.../vmagent                   \
  -remoteWrite.url=http://127.0.0.1:8428/api/v1/write     \
  -remoteWrite.url=http://127.0.0.1:8427/api/v1/write     \
  -remoteWrite.url=http://127.0.0.1:8426/api/v1/write     \
  -remoteWrite.urlRelabelConfig=/.../filters/system.yaml  \
  -remoteWrite.urlRelabelConfig=/.../filters/etc.yaml     \
  -remoteWrite.urlRelabelConfig=/.../filters/testing.yaml \
"
```

**Comment by valyala** [comment]
There are the following reasons why VictoriaMetrics components are configured via command-line flags instead of configuration files:

- It is easy to read documentation for every supported command-line flag in all the VictoriaMetrics components by running this component with `-help` flag. See [this example](https://docs.victoriametrics.com/#list-of-command-line-flags). This simplifies configuration of VictoriaMetrics components, since you can quickly find the needed docs for some command-line flags, or quickly find the needed command-line flag without googling.
- Command-line flags cannot be updated without service restart. This simplifies the code, which uses these command-line flags, since it may safely assume that they aren't changed when program runs. This also reduces the probability of hard-to-track bugs related to hot configuration update without service restart. Most users assume that config options in files can be updated and applied without the need to re-load the configured component. See, for example, [hot reload for some vmagent configs](https://docs.victoriametrics.com/vmagent/#configuration-update). So, if we add support for configuring VictoriaMetrics components via command-line flags, then we'll instantly get many feature requests and bug reports related to hot config updates. This may significantly complicate the code and introduce a lot of new bugs.
- It is already possible to pass command-line flags to VictoriaMetrics components from files as described [above](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/138#issuecomment-517281180).

Given these facts, we aren't going to switch from command-line flags to config files for VictoriaMetrics components. So closing this feature request as won't implement.
