### ISSUE TITLE
Graph missing some points

### ISSUE THREAD

**Issue by jcmoraisjr** [VictoriaMetrics/VictoriaMetrics#139]
**Describe the bug**

There are apparently some missing points when querying metrics with Grafana, no difference if zooming in or out, except the size of the missing part.

**To Reproduce**

Collect, wait and query time series without grouping range vectors, eg using rate().

**Expected behavior**

I expected to see almost the same graph querying Prometheus, Victoria Metrics or m3db.

**Screenshots**

![victoria-metrics](https://user-images.githubusercontent.com/1457820/62328247-f32ee700-b488-11e9-8394-cc6fe174475d.png)

**Version**

```
$ ./victoria-metrics-prod --version
victoria-metrics-20190725-211902-tags-v1.23.0-0-g89eb6d78
```

**Additional context**

I'm running some tests on service mesh implementations and using prometheus+grafana to track memory, cpu and network throughput of their components. At the same time, I'm also writing metrics to m3db and Victoria Metrics in order to use this same tests to also evaluate them.

Note that in the image attached I have some missing points on Victoria Metrics that doesn't exist on m3db or prometheus. Btw ignore the meaning of "CPU total", in fact I use rate() but this calculation hides the missing points.

Why is that happening? Which informations I can provide in order to better understand the relevant parts of my topology?

Some info:

- VictoriaMetrics deployment has just one instance without memory or CPU restrictions - host has 8GiB free RAM and 4 free CPUs
- rate(prometheus_remote_storage_samples_in_total[5m]) graph is ~9500
- queue config follows doc suggestion: max_shards: 100 and max_samples_per_send: 10000

**Comment by valyala** [comment]
@jcmoraisjr , try upgrading to [v1.23.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It contains a fix for [the similar issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/134). There is yet another fix available in the master branch - try [building VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources) from the latest commit and verifying whether the issue is fixed.

> Why is that happening? Which informations I can provide in order to better understand the relevant parts of my topology?

This could happen when the following conditions are met:
- Scrape interval between samples has non-zero jitter. For instance, the interval between the first and the second sample is 10 seconds, while the interval between the second and the third sample is 11 seconds.
- Grafana sends `step` arg to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries), which is smaller than the scrape interval for the given time series.

I'd suggest setting up VictoriaMetrics monitoring with the official dashboard for Grafana according [to these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring). This can save troubleshooting time in the future.

**Comment by valyala** [comment]
> I'm also writing metrics to m3db and Victoria Metrics in order to use this same tests to also evaluate them.

It would be great if you could provide feedback after finishing the testing. We are interested in the following details for the tested systems:
- CPU usage
- RAM usage
- Disk space usage
- Disk bandwidth usage
- Disk IO usage

**Comment by jcmoraisjr** [comment]
Hi, thanks for the fast reply. I updated to the latest code from master - fcc1666 - and apparently the missing points are a little less frequent but they are still there. I need a scrape interval of 3s on the current test but changed to 10s just to see if this can help:

scrape_interval: 3s

![3s](https://user-images.githubusercontent.com/1457820/62400197-bc260780-b554-11e9-8cf2-c95b43e4e86f.png)

scrape_interval: 10s

![10s](https://user-images.githubusercontent.com/1457820/62400200-c2b47f00-b554-11e9-8710-c06ba0c706fc.png)

Is there any data from my test environment which would help you to understand the behavior or reproduce the issue locally?

> It would be great if you could provide feedback after finishing the testing. We are interested in the following details for the tested systems:

Sure. Do you mean VictoriaMetrics numbers right? Note that this is a small environment - two small k8s clusters - created only to run our service mesh implementation poc. I'll update you with really interesing numbers as soon as we start our time series db poc.

**Comment by valyala** [comment]
Thanks for the graphs, @jcmoraisjr ! They clearly show that the issue is related to jitter for scrape interval. By default VictoriaMetrics looked back by 1+1/8 of the average scrape interval between data points for the previous data point. If it couldn't find the data point on this interval, it returned gap. For 3s scrape interval this means 3s*(1+1/8)=3.375s , so it returns gap if jitter between data points exceeds 0.375s.

> Is there any data from my test environment which would help you to understand the behavior or reproduce the issue locally?

There is no need in additional details, since I reproduced the issue for small scrape intervals with high jitter.

Latest commits in the master branch changed calculations for the maximum allowed jitter - now higher jitters are allowed on lower scrape intervals. This should removes the gaps for small scrape intervals. Try building from the latest commit on the master branch and verify whether the issue is gone.

**Comment by valyala** [comment]
@jcmoraisjr , try [v1.24.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It contains the fix described above.

**Comment by valyala** [comment]
> Do you mean VictoriaMetrics numbers right?

I meant VictoriaMetrics numbers in comparison to M3DB numbers on the same workload :)

**Comment by jcmoraisjr** [comment]
Hi, testing for about 3h now and the issue is apparently gone with 3s interval. Using several time frames in Grafana between 5m and 3h, without a single failure in the graphs. Thanks! Using 1.24.0 here.

> I meant VictoriaMetrics numbers in comparison to M3DB numbers on the same workload :)

Yep, I'll let you know as soon as we have the numbers =)

---

Just a final note, sharing my thoughts, not a big deal btw: I was expecting to see the exact same binary in the releases page and inside the container. Using xxd + diff I can see they differ just a little in an internal timestamp and in some no-idea-what because it probably was built twice.

**Comment by valyala** [comment]
> I was expecting to see the exact same binary in the releases page and inside the container. Using xxd + diff I can see they differ just a little in an internal timestamp and in some no-idea-what because it probably was built twice

The binary must be the same, since it is built via `make app-via-docker` for both binary release and docker image. The binary is indeed built twice, so internal timestamps may differ.
