### ISSUE TITLE
merge pushgateway into vmagent

### ISSUE THREAD

**Issue by ldpiuaeng** [VictoriaMetrics/VictoriaMetrics#1415]
**Is your feature request related to a problem? Please describe.**
Is it possible combine pushgateway into vmagent ?

**Comment by hagen1778** [comment]
Hi! Pushgateway and vmagent are different tools with different APIs. However, they're solving the same problem - pushing data into remote time series database. If that's the case, you can push metrics from your application in any of [supported formats](https://docs.victoriametrics.com/vmagent.html#features) directly to vmagent. Unlike pushgateway, vmagent respects provided metrics timestamps and forwards them to VM TSDB accordingly.
Please note, vmagent does not support pushgateway API:
1. no deletion/updates for recorded metrics (curl -X DELETE/PUT) since vmagent works differently - it doesn't wait to be scraped, it forwards accepted metrics as soon as possible.
2. No `/metrics/job/<JOB_NAME>/<LABEL_NAME>/<LABEL_VALUE>}` path support. Extra labels may be set via extra_label param instead. See https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-import-data-in-prometheus-exposition-format for details.

**Comment by valyala** [comment]
The commit 58d459e8a8c5212f79e943e78beface5cac2251c adds the ability to accept data in [Pushgateway protocol](https://github.com/prometheus/pushgateway#url) via `/api/v1/import/prometheus` endpoint. For example, the following line pushes `metric{label="abc",job="my_app",instance="host123"} 123` metric into VictoriaMetrics:

```
curl -d 'metric{label="abc"} 123' -X POST 'http://localhost:8428/api/v1/import/prometheus/metrics/job/my_app/instance/host123'
```

See [these docs](https://docs.victoriametrics.com/#how-to-import-data-in-prometheus-exposition-format) for more details.

This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent.html) gained support for [Pushgateway protocol](https://github.com/prometheus/pushgateway#url) starting from [v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3636
