### ISSUE TITLE
vms as datasource,grafana query_range missing some data

### ISSUE THREAD

**Issue by yonghuili1** [VictoriaMetrics/VictoriaMetrics#1421]
I write a exporter that expose two metrics , one is set timestamp offset 45m , another one is offset  5m, prometheus scrape them and remote write to VMS storage . when i want to show the metric in the grafana,there is something problem here ....
 I found the panel can not complete display all data which metric is offet 45m,but another metric is no problem. The magic is when I refresh the page  and the data is working well.

So I guess there is a bug that causes some data to be lost in query_range, Especially the metrics with a long offset timestamp～

**access this api** 
/api/datasources/proxy/404/api/v1/query_range?query=click_thru_rate_after_imp%7Bdata_source%3D"holo"%2Coverview%3D"true"%2Ccluster%3D"click-exporter-new"%2Cxhsenv%3D"prod"%7D&start=1625026000&end=1625026960&step=20

**first return：**

{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"__name__":"click_thru_rate_after_imp","data_source":"holo","hash_num":"0"}"values":[[1625026000,"0.13582022431366"],[1625026020,"0.13602705401984"],[1625026040,"0.13602705401984"],[1625026060,"0.13602705401984"],[1625026080,"0.13609433437669"],[1625026100,"0.13609433437669"],[1625026120,"0.13609433437669"],[1625026140,"0.136216169871"],[1625026160,"0.136216169871"],[1625026180,"0.136216169871"],[1625026200,"0.136993263732"],[1625026220,"0.136993263732"],[1625026240,"0.136993263732"],[1625026260,"0.136982635483"],[1625026280,"0.136982635483"],[1625026300,"0.136982635483"],[1625026320,"0.13759016327657"],[1625026340,"0.13759016327657"],[1625026360,"0.13759016327657"],[1625026380,"0.13729274035585"],[1625026400,"0.13729274035585"],[1625026420,"0.13729274035585"],[1625026440,"0.13769400578321"],[1625026460,"0.13769400578321"],[1625026480,"0.13769400578321"],[1625026500,"0.13748069585666"],[1625026520,"0.13748069585666"],[1625026540,"0.13748069585666"],[1625026560,"0.13763257438666"],[1625026580,"0.13763257438666"],[1625026600,"0.13763257438666"],[1625026620,"0.137434296993"],[1625026640,"0.137434296993"],[1625026660,"0.137434296993"],[1625026680,"0.13758355426378"],[1625026700,"0.13758355426378"],[1625026720,"0.13758355426378"],[1625026740,"0.13793938775575"],[1625026760,"0.13793938775575"],[1625026780,"0.13793938775575"],[1625026800,"0.13797930366534"],[1625026820,"0.13797930366534"],[1625026840,"0.13797930366534"],[1625026860,"0.13774662172454"],[1625026880,"0.13774662172454"],[1625026900,"0.13774662172454"],[1625026920,"0.13866980430976"],[1625026940,"0.13866980430976"],[1625026960,"0.13866980430976"]]}]}}

refresh the page：

{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"__name__":"click_thru_rate_after_imp","data_source":"holo","hash_num":"0"},"values":[[1625026320,"0.13759016327657"],[1625026340,"0.13759016327657"],[1625026360,"0.13759016327657"],[1625026380,"0.13729274035585"],[1625026400,"0.13729274035585"],[1625026420,"0.13729274035585"],[1625026440,"0.13769400578321"],[1625026460,"0.13769400578321"],[1625026480,"0.13769400578321"],[1625026500,"0.13748069585666"],[1625026520,"0.13748069585666"],[1625026540,"0.13748069585666"],[1625026560,"0.13763257438666"],[1625026580,"0.13763257438666"],[1625026600,"0.13763257438666"],[1625026620,"0.137434296993"],[1625026640,"0.137434296993"],[1625026660,"0.137434296993"],[1625026680,"0.13758355426378"],[1625026700,"0.13758355426378"],[1625026720,"0.13758355426378"],[1625026740,"0.13793938775575"],[1625026760,"0.13793938775575"],[1625026780,"0.13793938775575"],[1625026800,"0.13797930366534"],[1625026820,"0.13797930366534"],[1625026840,"0.13797930366534"],[1625026860,"0.13774662172454"],[1625026880,"0.13774662172454"],[1625026900,"0.13774662172454"],[1625026920,"0.13866980430976"],[1625026940,"0.13866980430976"],[1625026960,"0.13866980430976"]]}]}}

Obviously some data is missing....

**Comment by valyala** [comment]
@yonghuili1 , could you provide the following additional information?
* The type of VictoriaMetrics used - [cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) or [single-node](https://docs.victoriametrics.com/).
* The version of VictoriaMetrics used. It can be checked by passing `--version` to VictoriaMetrics binary or by inspecting `vm_app_version` metric if [the recommended monitoring of VictoriaMetrics has been set up](https://docs.victoriametrics.com/#monitoring). It is recommended trying [the latest available version](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - probably the issue has been already fixed there.
* The `-retentionPeriod` used.

Probably, the issue is related to [how VictoriaMetrics handles the backfilling](https://docs.victoriametrics.com/#backfilling). Probably, you need to set `-search.cacheTimestampOffset` command-line flag to the value exceeding the maximum timestamp offset from the current time for the ingested data. For example, `-search.cacheTimestampOffset=1h` would cover historical data with timestamp offsets up to a hour in the past from the current time.

**Comment by hagen1778** [comment]
Closing as inactive.
