### ISSUE TITLE
victoria-metrics  VSZ memory usage  

### ISSUE THREAD

**Issue by jicki** [VictoriaMetrics/VictoriaMetrics#1427]
**Describe the bug**

victoria-metrics  VSZ memory usage   `47.9g`  ,  `--memory.allowedPercent=10`

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20210524-130851-tags-v1.60.0-0-g08234aa7a

```

**Used command-line flags**
Please provide applied command-line flags used for running VictoriaMetrics and its components. 

```bash
/ $ free -m
              total        used        free      shared  buff/cache   available
Mem:         257875      157827       93674           9        6373       98874
Swap:             0           0           0
```

```
PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 1000     S    47.9g   0%  25   1% /victoria-metrics-prod --retentionPeriod=1 --dedup.minScrapeInterval=5s --storageDataPath=/storage --memory.allowedPercent=10
   15     0 1000     S     1676   0%  57   0% sh
   20    15 1000     R     1604   0%  58   0% top
```

**Comment by valyala** [comment]
The `-memory.allowedPercent` command-line flag limits the summary sizes of in-memory caches VictoriaMetrics can use. It doesn't limit the total memory usage. For example, VictoriaMetrics can need additional memory for data ingestion and/or for query processing. See the `./victoria-metrics-prod -help` output for the `-memory.allowedPercent` command-line flag:

>   -memory.allowedPercent float
        Allowed percent of system memory VictoriaMetrics caches may occupy. See also -memory.allowedBytes. Too low a value may increase cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from OS page cache which will result in higher disk IO usage (default 60)



It is recommended setting up [monitoring for VictoriaMetrics](https://docs.victoriametrics.com/#monitoring) in order to understand better the resource usage. It is also recommended upgrading to the [latest available version](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it may contain improvements and bug fixes, which could lead to issues. See also [troubleshooting docs](https://docs.victoriametrics.com/#troubleshooting).

**Comment by valyala** [comment]
Closing the issue as answered.
