### ISSUE TITLE
Prometheus Operator CRDs

### ISSUE THREAD

**Issue by silverbp** [VictoriaMetrics/VictoriaMetrics#1430]
Victoria Metrics states it works with Prometheus CRDs, is there an easy way to install the Prometheus Operator CRDs. A lot of other helm charts support installing the ServiceMonitor resource, but without the Prometheus Operator, the CRDs don't exist. Their new chart seems to want to do quite a bit. I can weed through that and disable almost everything. Wondering if there's an easier way.

**Comment by silverbp** [comment]
Well it does look like you can install the CRDs only.. like this..

`kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.47.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml`

That's from their upgrade guide..  https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by f41gh7** [comment]
> Well it does look like you can install the CRDs only.. like this..
> 
> `kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.47.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml`
> 
> That's from their upgrade guide.. https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

 Yep, it seems to be the easiest way. 

 Probably, we can include it into one of helm charts, but i'm not sure, that its good idea.

**Comment by micw** [comment]
It would be great if these CRDs are part of the helm chart (which can optionally be enabled). Otherwise, a manual non-helm operation is required to get all work. With this feature, the stack can really be used as a drop-in replacement for prometheus operator.

**Comment by willemm** [comment]
I'm not sure you're talking about, it seems like you've misunderstood the problem statement.  Or probably, what the term 'CRD' means, like 90% of people who work with k8s.  A CRD is a definition of what a resource spec looks like.  Like a DTD in xml, or a json-schema.  It basically defines which fields are present in a custom resource.

As an example, to be able to define a servicemonitor in kubernetes, the kubernetes server needs to know which fields a servicemonitor is supposed to have, and for that it needs the CRD of the type "servicemonitor".

The servicemonitor that you then deploy is called a CR (CustomResource), not a CRD.  I know, it's very confusing, but in this case the difference is important.


The problem in this case is that when you install victoriametrics, a lot of apps that declare servicemonitors will fail to deploy their metrics scrape settings because the prometheus-crd is not present on the cluster.

The solution is to install the manifest (preferrably the helm chart) mentioned above.  This solution works perfectly.

As an enhancement, it would be nice if people installing victoriametrics did not have to go through this extra step manually.  This can be accomplished simply by declaring the prometheus-operator-crds helm chart as an (optional) dependency in one of the victoria-metrics helm charts.


PS: Apologies if you did know the difference, but your sentence only makes sense if you replace 'CRD' with 'CR'.

**Comment by micw** [comment]
The tickets is about CRDs (not CRs). The scenario is the following:

I would like to monitor my K8S cluster with victoriametrics only. Most charts allow to activate a "service monitor" (CR). This CR requires a CRD from prometheus installed, otherwise the CR cannot be installed.

If I install victoriametrics only, the chart installs it's own CRDs. These differs from the CRDs that prometheus installs. So I cannot use a service monitor from an arbitrary chart.

Options:
* convince everyone to add CRs for victoriametrics CRDs to their charts (very unlikely to happen)
* install prometeus CRDs via external chart / yaml (works but is to be managed separately)
* install prometeus CRDs along victoriametrics chart (this feature request)

**Comment by valyala** [comment]
@Haleygo , could you look at this issue?

**Comment by Haleygo** [comment]
related https://github.com/VictoriaMetrics/helm-charts/issues/294

**Comment by Haleygo** [comment]
Hello @micw,
>install prometeus CRDs along victoriametrics chart (this feature request)

I don't really like this idea, victoriametrics operator&chart were inspired by prometheus operator&chart but created as independent products which don't rely on them. I think vm-operator supports auto-converting prometheus objects to help users migrating from prometheus-operator, which indicates prometheus-opeartor was installed already.
If users only want to monitor with victoriametrics, installing prometeus CRDs along victoriametrics chart brings duplicated set of CRDs(VMServiceScrape/servicemonitor, VMRule/PrometheusRule), and which set of CRDs should be managed after creation?
So ideally, resources need to be converted into vm CR before creating. In third-party charts who use prometheus CRs, those resources should be pretty stable and can be templated before `helm install`, so maybe we can create a new tool or subcmd in vm-operator to do that, and it can be integrated into some pipeline.
If below option sounds redundant for most cases, I still don't see the difference between having prometheus CRDs in vm-charts and applying them by hand(https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1430#issuecomment-873029910), both of them require users knowing they need have prometheus CRDs and there is no order requirement on installing vm and prometheus.
cc @f41gh7

**Comment by Haleygo** [comment]
The prometheus-operator-crds has been added as dependency of victoria-metrics-k8s-stack since [victoria-metrics-k8s-stack-0.23.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.23.0), you can enable it with prometheus-operator-crds.enabled now.
See https://github.com/VictoriaMetrics/helm-charts/issues/341 for details.
