### ISSUE TITLE
irate return wrong result

### ISSUE THREAD

**Issue by lcasi** [VictoriaMetrics/VictoriaMetrics#1446]
**Describe the bug**
a counter metric with name `network_device_ifoctects` remote_write data to vm cluster every 3 miniutes, when use irate to calculate,vm sometimes return wrong result.
**Screenshots**
![image](https://user-images.githubusercontent.com/47807658/125423530-ffec4af2-2dcf-4c8a-9d51-08426bb22384.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
vmselect-20210524-131622-tags-v1.60.0-cluster-0-g25ed1f0c4
```

**Used command-line flags**
vmselect
```shell
ExecStart=/data/app/vm/vmselect-prod -storageNode=node1:8401 -storageNode=node2:8401 -storageNode=node3:8401 -storageNode=node4:8401  -storageNode=node5:8401 -dedup.minScrapeInterval=1ms -search.maxQueryDuration=2m -replicationFactor=2
```
vmstorage
```shell
ExecStart=/data/app/vm/vmstorage-prod -retentionPeriod 12 -storageDataPath /mnt/storage02/vmstorage -search.maxUniqueTimeseries 3000000
```

**Comment by valyala** [comment]
@lcasi , could you share a graph for `irate(network_device_ifoctects[10m])` on the same time range without the graph for `network_device_ifoctects`?

**Comment by valyala** [comment]
Try also using `rate()` instead of `irate()`. `irate()` takes into account only the last two points before every returned timestamp on the graph, while `rate()` takes into account all the points on the given time range specified in square brackets - `[10m]` in the case above. See [this article](https://valyala.medium.com/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832) for more details.

**Comment by lcasi** [comment]
@valyala 

![image](https://user-images.githubusercontent.com/47807658/125799867-a2a63385-0d15-4907-9cb3-32280a2129ff.png)

**Comment by valyala** [comment]
This looks very weird - we cannot reproduce this behavior with the [latest version of VcitoriaMetrics](https://docs.victoriametrics.com/CHANGELOG.html). @lcasi , try changing the duration in square brackets for `rate()` and checking whether this updates the resulting graph. Try also using `increase()` instead of `rate()`.

**Comment by valyala** [comment]
It would be great if you could obtain raw samples from [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) on the time range displayed on the graph and investigating the returned samples. Probably there are some anomalies such as:
* irregular interval between sample timestamps
* value outliers

Such anomalies may affect `rate()` calculations. Such anomalies may be related to improperly configured Prometheus HA pairs (or vmagent HA pairs) and/or improperly configured relabeling rules, which result in merging of samples from multiple unrelated time series into a single series.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the problem still exists.
