### ISSUE TITLE
[Feature] Metric replication multi-AZ + multi-tenancy  

### ISSUE THREAD

**Issue by syepes** [VictoriaMetrics/VictoriaMetrics#1491]
**Is your feature request related to a problem? Please describe.**
We are trying to replicate metrics between to independent VM clusters that are using the tenant feature, while replicating the metrics its also important to have some minimal guaranty that the metrics will be send or resent of any of the clusters is temporary down.
The currently available option to replicate metrics does not offer a minimal guaranty (at high volumes) it would be nice if we could get one of the below solutions: 

**Describe the solution you'd like**
The two below options could help resolve this issue.

**1) [VMAgent -> VMInsert]** With VMAgent we can send metrics to it and it can ring buffer and send the data to multiple VMInserts (VMClusters), so if the metrics are received by the vmagent we have the guarantee it they will be sent to the other VMCluster’s as its persistent in the ring buffer.
This option does not work as the VMAgent currently does not support receiving metrics with the multi-tenancy and sending to other VMInsert's preserving the multi-tenant information

> **Solution: (Preferred)**
> It would be great if the VMAgent could support receiving metrics with the multi-tenancy and have the ability to send the metrics to its configured destinations but preserving the received multi-tenant information

**2) [VMInsert -> VMInsert]** With the vminsert (Multi-level cluster setup), if we use a central vminsert to send all the metrics then we configure it to replicate (resend) all the metrics to both of the VMClusters.

This option works but is one of the destination VMInsert's is temporary down, metrics can get lost as the current in-memory buffer [between the VMInsert's](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/349d45bbbe50099055a71b10bb33b0b1a3f49384/app/vminsert/netstorage/netstorage.go#L444-L447) is very small [100MB](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c3e6ce1db9d8c594357bc597d5c12d0beaf947a7/lib/consts/consts.go#L4)

> **Solution:**
> It would be great to have a way of configuring this hard-coded limit or even better to implement a similar ring buffer option like in VMAgent, this option would only be used when using the [multi-level cluster setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup)

**Comment by syepes** [comment]
Similar request https://github.com/VictoriaMetrics/VictoriaMetrics/issues/762

**Comment by valyala** [comment]
I think it would be better adding the ability to accept multi-tenant metrics at vmagent and to send them to remote storage systems with multi-tenant support. E.g. basically vmagent should be able to accept metrics via `/insert/<accountID>/...` urls in the same way as vminsert - https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format and then properly send them to `-remoteWrite.multitenantURL=http://vminsert:8480/`

The option with per-vmstorage on-disk buffer at vminsert won't work, since it makes vminsert nodes stateful instead of stateless. This also may result in partial query responses if some vmstorage nodes become unavailable or become slow for long periods of time. Currently vminsert re-routes incoming samples from the unavailable vmstorage node to the remaining available vmstorage nodes. If per-vmstorage on-disk buffers will be implemented, then the ingested samples can remain in the buffer for long period of time, while other samples ingested around the same time will be pushed to vmstorage nodes. This will result in hard-to-debug-and-fix partial responses at vmselect.

**Comment by syepes** [comment]
@valyala, Thanks for the response.
The VMAgent multi-tenant support would be a killer feature for the multi-az scenarios as it can guaranty and preserve the metrics at the cost of some disk storage :-)

**Comment by syepes** [comment]
#1505 WIP

**Comment by valyala** [comment]
`vmagent` gained multi-tenant support staring from [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmagent.html#multitenancy) for more details. Closing the feature request as done.
