### ISSUE TITLE
Wrong docker name in readme

### ISSUE THREAD

**Issue by hellozdp** [VictoriaMetrics/VictoriaMetrics#1492]
**Describe the bug**
```
docker run --rm --name vmui -p 8080:8080 victoriametrics/vmui
```

the name should be `victoriametrics/ui` in docker hub

**Comment by valyala** [comment]
The `victoriametrics/ui` is an old repository. It has been renamed to `victoriametrics/vmui` during the migration from [vmui repo](https://github.com/VictoriaMetrics/vmui) to [app/vmui directory](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui). So the docs at [app/vmui/README.md](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmui/README.md) are correct:

Run the following command from the root of VictoriaMetrics repository in order to build `victoriametrics/vmui` Docker image:

```
make vmui-release
```

Then run the built image with:

```
docker run --rm --name vmui -p 8080:8080 victoriametrics/vmui
```

Then navigate to `http://localhost:8080` in order to see the web UI.


P.S. Published [victoriametrics/vmui](https://hub.docker.com/r/victoriametrics/vmui) package at docker hub with `make vmui-publish-latest` command, so now the `docker run` command above works even if `make vmui-release` command wasn't run.

**Comment by denisgolius** [comment]
`vmui` was integrated to VictoriaMetrics Single - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmui . In  VictoriaMetrics Cluster `vmui` integrated into `vmselect` and available at `http://<vmselect>:8481/select/<accountID>/vmui/` - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format .
