### ISSUE TITLE
Can vmalert's recording-rule support queryRange set startTime for prometheus pull data delay?&Can vmalert's recording-rule support setting the time of DataSource's time series data as the time of aggregated metrics?

### ISSUE THREAD

**Issue by GerryYuan** [VictoriaMetrics/VictoriaMetrics#1514]
**Is your feature request related to a problem? Please describe.**
1、When prometheus is pulling the time series data delay, vmalert will be inaccurate when aggregating metrics data through the recording-rule. If you can set vmalert to pull data in the datasource, you can specify the start time, for example, pull the current time in advance The data of the first 10s will be better.

2、Can vmalert's recording-rule support setting the time of DataSource's time series data as the time of aggregated metrics?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hagen1778** [comment]
Hi @GerryYuan! Could be https://github.com/VictoriaMetrics/VictoriaMetrics/issues/668 relevant to your question?

**Comment by hagen1778** [comment]
Metrics delivery delay from the clients may indeed affect correctness of the data generated by vmalert because data may be not full or absent on the moment when vmalert evaluates the rule.
There is no an easy way to fix this or control. Proposed solution to check datasource timestamps won't work for the cases when there are many clients pushing data to VictoriaMetrics and only one of them is lagging.
There are two workarounds for this situation:
1. Configure an artificial offset for vmalert, so it will evaluate rules with some delay - see `datasource.lookback` flag for details. The value of the flag should account for possible delays in metrics delivery chain.
2. [Backfill missing data afterwards](https://docs.victoriametrics.com/vmalert.html#rules-backfilling) if sever delay happens.
