### ISSUE TITLE
VMInsert / VMSelect use DNS SRV records for VMStorage addresses

### ISSUE THREAD

**Issue by nickmy9729** [VictoriaMetrics/VictoriaMetrics#1516]
In order to make the VictoriaMetrics Cluster version more dynamic, it would be great if the vminsert and vmselect utilize DNS SRV records to get a list of vmstorage addresses.  This will also help VictoriaMetrics work better in a service mesh such as Consul or Istio.  I would expect to see a command-line flag like the following:

  -storageNodeSRV dnsname

AND

  -storageNodePort 8400

AND

  -storageNodeSRVRefreshInterval seconds
    every interval seconds refresh the DNS cache for storageNode addresses.

Where "dnsname" is a DNS SRV record that returns the following from DNS:

_sip._tcp.example.com.   3600 IN    SRV 10       60     5060 storage1.example.com.
_sip._tcp.example.com.   3600 IN    SRV 10       20     5060 storage2.example.com.

By supporting this command-line options would not need any updates when adding storage nodes.  The DNS could be refresh periodically to get an updated listing from the DNS SRV record.  In addition, if using a service mesh like Istio of Consul those records would be health checked by the mesh to ensure writes only go to healthy nodes.

**Comment by hagen1778** [comment]
Hi @nickmy9729! The idea is nice! I have a couple of concerns though.
1. vminsert already contains logic for health-checks and procedures to redirect traffic from faulty nodes.
2. it is important to be very careful with vmstorage addr discovery, because any changes to it may have severe effect on the cluster health. I personally would prefer cluster topology configuration be static as much as possible, and any changes to it should be made very carefully.

My own experience shows that service discovery is great for clients (services that would need to write or read from VM), but could be very harmful for cluster topology configuration, imho.

**Comment by YuriKravetc** [comment]
Hi @nickmy9729 
A follow-up on this feature request.
Feel free to update VictoriaMetrics to the latest version and let us know if this feature request is still required, so we can know if this issue is outdated and can be closed.
If you can share your own progress/experience or workarounds on this - it would be greatly appreciated.

**Comment by hagen1778** [comment]
vmselect and vminsert can automatically discover vmstorage nodes - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#automatic-vmstorage-discovery
