### ISSUE TITLE
Write performance degradation of vmstorage

### ISSUE THREAD

**Issue by xemxx** [VictoriaMetrics/VictoriaMetrics#1543]
**Describe the bug**
Our vmstorage has been upgraded from 1.47.0-cluster to 1.56.0-cluster and the data has been pending twice

We found that the tsid cache size and hit rate decreased

We replaced the binary directly and then restarted it with a signal grace

**To Reproduce**

can not reproduce

**Expected behavior**

**Logs**

upgrade log：
![image](https://user-images.githubusercontent.com/26523062/129695766-e6a81ad5-55fe-42a0-84ee-cd17fec7d4e2.png)

cache error log:

![image](https://user-images.githubusercontent.com/26523062/129696005-1bfe95c1-7a4d-4d93-94c9-796e9701d0ac.png)

The pid is not changed, so there is no automatic restart in between

![image](https://user-images.githubusercontent.com/26523062/129696244-d039a632-73aa-4f2a-a570-60438516d367.png)

**Screenshots**

This is the change in cache

![image](https://user-images.githubusercontent.com/26523062/129696748-10cb469d-703b-4f64-85a3-fbf993eb4a7d.png)

**Version**

v1.56.0-cluster

**Used command-line flags**

``` bash
/usr/local/bin/vmstorage-prod \
-retentionPeriod=12 \
-search.maxUniqueTimeseries=2000000 \
-storageDataPath=/data/sz-devops/data/victoria_metrics/vmstorage \
-memory.allowedPercent=70
```

**Comment by xemxx** [comment]
After reading the code, I think this is probably because the interval between writing the same metricID is too short, so the tsid cache already contains this metricID, but the indexDB does not write data to the hard disk.

[code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bd14b0887e2b7bed03ff37b86c117bb2c5aa6d6b/lib/storage/index_db.go#L3043:L3054)

**Comment by xemxx** [comment]
@valyala pealse take a look

**Comment by valyala** [comment]
VictoriaMetrics gained additional composite index in [v1.54.0](https://docs.victoriametrics.com/CHANGELOG.html#v1540) and in newer releases. VictoriaMetrics writes data to this index every time it sees new time series. A time series is uniquely determined by its name plus a set of its labels. If at least a single label value changes, then new time series is created. So if big number of new time series are created over time (aka high churn rate), then VictoriaMetrics uses bigger amounts of disk write IO after the upgrade from version prior v1.54.0 to v1.54.0 or higher.

@xemxx , could you share the `churn rate` graph from the [official dashboard for VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)?

There were also other issues, which could increase disk write IO usage such as [this one](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1338#issuecomment-863046999). These issues are fixed in the latest release, so it is recommended upgrading to it - see [the changelog](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by xemxx** [comment]
Thank you for your reply

This is `churn rate` graph
 
![image](https://user-images.githubusercontent.com/26523062/130024009-a41ca1c2-7a3d-49c3-b415-bd0a9f4956b1.png)

But if the tsid cache is cleared, then the others are considered to be new time series. So this `churn rate` will increase

We rolled back to v1.47.0 and this did not happen again

We will look at the issues you mentioned

**Comment by xemxx** [comment]
Thank you for your reply

This is `churn rate` graph
 
![image](https://user-images.githubusercontent.com/26523062/130024009-a41ca1c2-7a3d-49c3-b415-bd0a9f4956b1.png)

But if the tsid cache is cleared, then the others are considered to be new time series. So this `churn rate` will increase

We rolled back to v1.47.0 and this did not happen again

We will look at the issues you mentioned

**Comment by Yuri1Kravets** [comment]
@xemxx Hi, can we consider this issue as solved?

**Comment by YuriKravetc** [comment]
Closing the issue, feel free to reopen it if consider unsolved.
