### ISSUE TITLE
Ingested data is not evenly distributed across cluster nodes

### ISSUE THREAD

**Issue by sergeyberezansky** [VictoriaMetrics/VictoriaMetrics#1544]
**Describe the bug**
Hello,
Yesterday we have upgraded the cluster from version 1.54 to 1.64.0
I must admit that the ingestion rate has increased by around 30%, and we can now reach 300MB/sec ingestions in prometheus format instead of max. 220 we have reached previously.
However, I have noticed that data is now not distributed evenly.

We are storing data in around 700 series, with relatively high cardinality, and retention period of 14 days.
Total number of series stored is ~ 10 millions.
In previous version, the monitored free disk capacity across 4 nodes was always around 25-35%.
However, after the upgrade we see that on part of nodes (nodes 0, 3) the free capacity almost doesn't change (~40%),
while nodes 1, 2 of the cluster have reached 0% free space for a couple of times already.
![image](https://user-images.githubusercontent.com/66549633/129711702-206b50e9-af6c-4a34-b254-038430646634.png)

Apparently it seems that the data is not evenly distributed across nodes. I can provide you additional information upon request.
**To Reproduce**
I don't know exact steps of reproduction besides the information I've provided to you

**Expected behavior**
Even distribution of disk usage across nodes, and no such spikes

**Logs**
No specific logs can be seen regarding this, besides the re-routing that occurs on vminsert pod when one of the nodes reaches 0 free space.

**Screenshots**
This is the free space allocation graph of Victoria

For VictoriaMetrics health-state issues please provide full-length screenshots 
![screenshot-kmon svc prod weka io-2021 08 17-15_11_30](https://user-images.githubusercontent.com/66549633/129723668-d7c8090c-eb91-4d19-a917-c1cc13d5cbe5.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
vmstorage-20210816-054415-tags-v1.64.0-cluster-0-g75a034521
```

**Used command-line flags**
--retentionPeriod=14d --storageDataPath=/storage --envflag.enable=true --envflag.prefix=VM_ --loggerFormat=json --search.maxUniqueTimeseries=10000000

**Comment by hagen1778** [comment]
Hi @sergeyberezansky! Thanks for so detailed report!
I have a few questions. The "vmstorage.Ingestion Rate" looks a bit weird. It has a cumulative display option turned on, means it should show proportionally how many data points received by every storage node. But after update (the annotation mark on screenshot) shows only two lines. And only 12h later it starts looking normal - 4 storage nodes with even distribution. The "vmstorage.Datapoints" graph shows roughly the same picture. Do you know what is the reason of this? Can you correlate number of datapoints and used disk space by each storage node? Does nodes with exhausted disk space contain more datapoints or their index size is bigger?

Another interesting thing is "vmstorage.Merge speed" graph which shows intensity of background merging process. This process is busy with merging smaller parts of data into bigger ones. It is needed to maintain the limited number of files on disk and provide a better compression. Every ingestion request creates a small part, then small parts are merged into a new part, and so on multiple times. At some point they become a "big" part, a part with relatively high number of rows for "cold" (rarely accessed) data. The "healthy" "vmstorage.Merge speed" panel shows frequent storage/small merges and rare storage/big. But in your case it is opposite. Looks like for a long time there was no big merges happening. The merging does not happen if VM doesn't have enough disk space for efficient operation. Did you extend the disk space on those nodes?

> Total number of series stored is ~ 10 millions.

According to "Active time series" graph the number is about 100 millions. In normal operation, VM shards received series by available storage nodes. For 10 mil series you could expect to have 2.5 mil active series per storage node. Sometimes, due to contention or vmstorage unavailability rerouting happen - event when vminsert can't push data to specific vmstorage node. To avoid data loss it "reroutes" this data to different shard. If rerouting was active for all vminserts for a long time - you could expect that sharding won't work anymore. All shards will receive all metrics, then Grafana panel will show 40 mil active series - 10 mil at each storage node. But it still does not correlate with 100 millions on the screenshot.

**Comment by sergeyberezansky** [comment]
@hagen1778 thank you very much for your detailed answer.
Apparently something happened during upgrade and vminsert nodes did not route traffic to all vmstorage pods.
I found this after asking the question, and eventually restarted all the vmstorage pods - then the problem has indeed disappeared.

**Comment by valyala** [comment]
The next version of VictoriaMetrics will contain improved logic for data re-routing in the event if some of vmstorage nodes are temporarily unavailable or if some of vmstorage nodes temporarily slow down the processing speed for incoming data. The following improvements will be included in the next release of VictoriaMetrics cluster:
* Even series distribution among the remaining vmstorage nodes. Previously some vmstorage nodes could start receiving multiple times more series than other vmstorage nodes if some vmstorage nodes were unavailable or were slower than other vmstorage nodes.
* Reduced the maximum increase in the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) on the remaining vmstorage nodes after some vmstorage nodes become unavailable or become slow. It will be limited by 100% of the initial number of active time series per vmstorage node in the worst case (e.g. when vmstorage nodes have no enough resources to keep up with the increased load). Under normal conditions the increase in the number of active time series shouldn't exceed `1/N` of the initial number of active time series per vmstorage node, where `N` is the number of `vmstorage` nodes in the cluster. Previously the typical increase in the number of time series per vmstorage node after the re-routing was closer to 100%, while in the worst case it could reach `(N-1)`x.
* The placement of time series among `vmstorage` nodes doesn't depend on the order of `vmstorage` addresses passed to `-storageNode` command-line flag at `vminsert` nodes thanks to the changed consistent hashing algorithm (from [jump hash](https://arxiv.org/abs/1406.2294) to [rendezvous hash](https://www.eecs.umich.edu/techreports/cse/96/CSE-TR-316-96.pdf) ). Previously samples for the same time series could be placed to multiple `vmstorage` nodes if multiple `vminsert` nodes had different order of `vmstorage` nodes passed to `-storageNode` command-line flag. This could result in increased number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) across all the vmstorage nodes, which, in turn, could result in higher resource usage (RAM, CPU, disk IO, disk space) at `vmstorage` nodes.

These improvements should improve the stability of the mode with enabled rerouting in the cluster (e.g. when `-disableRerouting=false` command-line flag is passed to `vminsert`. The re-routing is disabled by default starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660) ).

The next release of VictoriaMetrics also adds an ability to drop incoming samples if vmstorage nodes are temporarily unavailable and/or overloaded if `-dropSamplesOnOverload` command-line flag is passed to `vminsert` nodes. By default vminsert slows down accepting new samples if vmstorage cannot keep up with the ingestion rate. This may result in increased number of pending samples at client side, which sends data to vminsert. This increases the delay between samples' generation and samples' ingestion into vmstorage. This may result in incomplete query results, which rely on recently ingested data (e.g. alerting and recording rules). In this case the `-dropSamplesOnOverload` mode may help receiving the most recently generated samples at the cost of dropping older samples. The number of dropped samples is tracked in per-`vmstorage` counter at `vminsert` nodes - `vm_rpc_rows_dropped_on_overload_total` . See more details at [changelog](https://docs.victoriametrics.com/CHANGELOG.html).

The features mentioned above can be tested by building cluster components of VictoriaMetrics from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) (currently this is 755e26e67b44962bada3a427e114d3f6ae284b5b ) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 .

**Comment by valyala** [comment]
FYI, the improvements mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337#issuecomment-1031538669 have been integrated into [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
