### ISSUE TITLE
Backup/Restore from single-node version to cluster version

### ISSUE THREAD

**Issue by salarali** [VictoriaMetrics/VictoriaMetrics#1552]
Is it possible to backup data from a single-node and restore it to a cluster version?

I know you can use vmrestore to utilize the backup to restore, but can it ingest a backup coming from a single node version?

I'm a little confused on if that will work? Isn't there some sharding that is done by vminsert when determining which vmstorage node to store data in?

**Comment by tenmozes** [comment]
Hi it's not possible to backup/restore data between single and cluster version because of different data format 
you can export-import data from single to cluster via vmctl https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics

vminsert does sharding between storage nodes, victoriametrics uses consistent sharing to determine correct node for timeserie

**Comment by salarali** [comment]
Ah, this is what I was looking for. Thanks for the quick reply. 

fyi, it wasn't clear from the documentation that single-cluster backup/restore would work or not.

**Comment by tenmozes** [comment]
@salarali thanks for feedback we will improve this section :)
