### ISSUE TITLE
Split prometheus.yml to multiple files to reduce maintenance efforts

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1559]
**Is your feature request related to a problem? Please describe.**
followed this prometheus feature, now our system easily has thousands lines of configuration with "sd" beside of file_sd
https://github.com/prometheus/prometheus/issues/8543

**Describe the solution you'd like**
as mentioned by prometheus there should be some way to include a directory to list all acceptable configurations for each sd

**Describe alternatives you've considered**
otherwise we can split the main configuration (global) separately with the scraping configurations, each type of sd input should has it's own configuration flagged file:
--kubernetes_sd_conf kub.yml --consul_sd_conf consu.yml

**Comment by valyala** [comment]
It would be great to provide an implementation in VictoriaMetrics compatible with Prometheus' one described at https://github.com/prometheus/prometheus/issues/8543 . Unfortunately it isn't ready yet. We have the following options:

1) To wait until Prometheus implementation is merged into source code and then implement the compatible one in VictoriaMetrics.
2) To design and implement our own solution for loading multiple files with scrape configs. I like the idea with `scrape_config_files` section proposed at https://github.com/prometheus/prometheus/issues/8543#issue-816814507 :
```yml
scrape_config_files:
- path/to/kubernetes_sd_configs1.yml
- glob/to/consul_sd_configs/*.yml
```
In this case vmagent would load scrape configs from the given paths and globs. Then the contents of these files would look like:
```yml
- job_name: k8s-pods
  kubernetes_sd_configs:
  - role: pod
    ...
- job_name: consul-targets
  consul_sd_configs:
  ...
```
Note that the top-level `scrape_configs` section is omitted in these files as suggested at https://github.com/prometheus/prometheus/issues/8543#issuecomment-809320226 . I like this idea, since it prevents from adding unsupported sections in these files.

I'd go with the second option, since it is unclear when the first option will be implemented in Prometheus. It is also unclear whether it will be easy to use, since the [design doc](https://docs.google.com/document/d/1BK_Gc3ixoWyxr9F5qGC07HEcfDPtb6z96mfqoGyz52Y/edit) looks a bit over-engineered :)

**Comment by renchili** [comment]
thanks a lot for your reply @valyala

**Comment by valyala** [comment]
The `scrape_config_files` section can be used in `-promscrape.config` file starting from [v1.65.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by pgassmann** [comment]
@valyala thank you for this nice feature, this really helps to simplify the configuration management. But currently changes in the scrape_config_files need a restart of vmagent.
It would be very nice, if changes in scrape config files are automatically detected, like with file_sd.
This would be useful when installing additional software on a host that has a metrics endpoint, we could just drop the static scrape config into a file, without having to restart vmagent.

**Comment by valyala** [comment]
> But currently changes in the scrape_config_files need a restart of vmagent.

`vmagent` can re-read `scrape_config_files` without restart - see [these docs](https://docs.victoriametrics.com/vmagent.html#configuration-update). If this doesn't work in the [latest version of vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), then please file a separate issue.
