### ISSUE TITLE
MetricsQL: is it possible to match text in a metric using regex backreferences ?

### ISSUE THREAD

**Issue by comete-geek** [VictoriaMetrics/VictoriaMetrics#1566]
Hi, I need to match an ip at 2 places in a metric like this:

```
netdata_mongodb_replication_state_state_average{﻿chart﻿=~﻿"mongodb_local.192.168.0.66_27018_state"﻿,﻿family﻿=﻿"replication and oplog"﻿,﻿dimension﻿=﻿"primary"﻿,﻿instance﻿=~﻿"192.168.0.66:19999"﻿}﻿ == ﻿1
```

I want the first ip in my result to be the same as the second one, so I tried to use group capturing and backreference like this:
```
netdata_mongodb_replication_state_state_average{﻿chart﻿=~﻿"mongodb_local.(.*)_27018_state"﻿,﻿family﻿=﻿"replication and oplog"﻿,﻿dimension﻿=﻿"primary"﻿,﻿instance﻿=~﻿"$1:19999"﻿}﻿ == ﻿1
```
But it doesn't seems to work. Is there any particular syntax to do this ?

Thanks a lot.

Morgan

**Comment by valyala** [comment]
It looks it is impossible to construct a PromQL or [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) query for selecting time series with identical parts in distinct labels :( There is a need in an additional function such as `label_equal(q, "label1", "label2")`, which should return all the time series from `q`, which have identical values for `label1` and `label2`. Then the following monstrous query could be used for this task:

```metricsql
label_equal(
  label_replace(
    label_replace(
      netdata_mongodb_replication_state_state_average{﻿﻿family﻿=﻿"replication and oplog"﻿,﻿dimension﻿=﻿"primary"﻿,﻿instance﻿=~﻿".*:19999"﻿}﻿,
      "instance_ip",
      "$1",
      "instance",
      "([^:]+):.*",
    ),
    "chart_ip",
    "$1",
    "chart",
    "mongodb_local.(^_+)_27018_state"
  ),
  "instance_ip",
  "chart_ip"
)
```

> if I want to use this for an alert for example, where do I put all these needed queries ? in a record group ?

This is a single query. It must be put into `expr` field of the alerting rule - see https://docs.victoriametrics.com/vmalert.html#alerting-rules

**Comment by valyala** [comment]
FYI, the [labels_equal](https://docs.victoriametrics.com/metricsql/#labels_equal) function is supported by VictoriaMetrics since [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5148).

This function makes possible to filter time series at query time if they contain identical values for different labels as [described in the comment above](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1566#issuecomment-1202327723).

Closing the issue as addressed then.
