### ISSUE TITLE
Promlems in Math on big numbers

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#157]
**Describe the bug**
sum(node_cpu_seconds_total{mode="idle"}) by (name) / sum(node_cpu_seconds_total) by (name)
returns straight line
![photo_2019-08-23 11 21 59](https://user-images.githubusercontent.com/1381404/63578017-47b11800-c598-11e9-85cc-dca3df032b40.jpeg)

but if add increase before the division 
![photo_2019-08-23 11 22 02](https://user-images.githubusercontent.com/1381404/63578054-57c8f780-c598-11e9-8f5c-ae9bab9aa05c.jpeg)

**Expected behavior**
Correct increase graph

**Version**
latest master

**Comment by valyala** [comment]
The first query - `sum(node_cpu_seconds_total{mode="idle"}) by (name) / sum(node_cpu_seconds_total) by (name)` - returns the average CPU load *since the last restart of the node with `node_exporter` when `node_cpu_seconds_total` is reset to zero*. It is OK if the line becomes straight with higher uptime of the node with `node_exporter`.

The second query - `sum(increase(node_cpu_seconds_total{mode="idle"}[5m])) by (name) / sum(increase(node_cpu_seconds_total[5m])) by (name)` - returns the average CPU load *during the interval set in the `increase` function - 5 minutes in this case*. So the line changes with CPU load.

Prometheus returns the same lines:

- [the first query](http://demo.robustperception.io:9090/graph?g0.range_input=1d&g0.expr=sum(node_cpu_seconds_total%7Bmode%3D%22idle%22%7D)%20by%20(name)%20%2F%20sum(node_cpu_seconds_total)%20by%20(name)&g0.tab=0)
- [the second query](http://demo.robustperception.io:9090/graph?g0.range_input=1d&g0.expr=sum(increase(node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B5m%5D))%20by%20(name)%20%2F%20sum(increase(node_cpu_seconds_total%5B5m%5D))%20by%20(name)&g0.tab=0)
