### ISSUE TITLE
support multiple quantiles

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#1573]
**Is your feature request related to a problem? Please describe.**

Often we want to display multiple quantiles on a graph (50%, 90%, 99%).  It would be easier to maintain dashboards, and probably more efficient, if a single function could return series for a set of quantiels.

**Describe the solution you'd like**
For any existing function taking a quantile scalar, let it optionally take a sequence of quantiles instead.  If that isn't possible, then I suppose make plural-named versions of each function.

When multiple quantiles are given, the output series should contain an extra label indicating the quantile.  My preference would be `quantile="50%"` for .5, etc., which are the human-readable labels we use on our graphs.

**Describe alternatives you've considered**
Currently in grafana we need to make a separate query for each quantile displayed in the graph.  It's probably inefficient, it's a maintenance burden when the query needs to be adjusted, and it's error-prone because the quantile in the query and the hard-coded display label can get out of sync.

**Comment by valyala** [comment]
Unfortunately it is non-trivial to use `(phi1, ..., phiN)` syntax due to MetricsQL restrictions. Such a syntax is equivalent so `union(phi1, ..., phiN)`. It unites time series returned by each arg and drops series with duplicate set of labels plus name. Numeric constants like 0.9 generate a time series without name and without labels, so `(phi1, ..., phiN)` becomes equivalent to `phi1`, since the rest of time series are deleted because they have euivalent set of labels and name.

**Comment by belm0** [comment]
I see.  It's a tradeoff, but perhaps consider using strings (`quantiles(("phi1", "phi2"), q)`)?  A disadvantage of variable number of positional args is that it limits future expansion of the function signature (new optional args, etc.).

**Comment by valyala** [comment]
IMHO, the `quantiles(("phi1", ..., "phiN"), q)` syntax is less intuitive than `quantiles("quantileLabel", phi1, ..., phiN, q)`. As for the limitation for the future expansion, it is better from readability, maintainability and usability PoV adding new functions instead of overriding already existing functions.

The `quantiles("quantileLabel", phi1, ..., phiN, q)` function is available in VictoriaMetrics starting from [v1.65.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [docs for this function](https://docs.victoriametrics.com/MetricsQL.html#quantiles).

Closing this feature request as done.

**Comment by belm0** [comment]
Thank you-- it's working well.

I was hoping to have friendly label values like `50%`, `80%`, etc.  I can't find a way to achieve it in Grafana other than making a field override for each series, which defeats part of the purpose of multiple-quantiles function.  (Not only efficiency, but less Grafana configuration to maintain.)

**Comment by belm0** [comment]
> I was hoping to have friendly label values like 50%, 80%

Rationale:  raw value like ".5" provides no context.  From "50%", graph reader has a good hint that it's a percentile.

**Comment by valyala** [comment]
It is expected that labels generated for `quantileLabel` match the actual `phi*` values passed to the function. If you need another label values, then the [label_map](https://docs.victoriametrics.com/MetricsQL.html#label_map) function can be used for providing the desired values. For example, the following query would return "50%" and "80%" in "phi" label:
```metricsql
label_map(
  quantiles("phi", 0.5, 0.8, some_metric),
  "phi", "0.5", "50%", "0.8", "80%"
)
```
