### ISSUE TITLE
vmalert: Add a flag for not setting alert end/resolve times

### ISSUE THREAD

**Issue by leizhag** [VictoriaMetrics/VictoriaMetrics#1586]
**Is your feature request related to a problem? Please describe.**
After updating/removing alert rules with large intervals (say 1h) in configuration files, its alerts could still be firing for 3x intervals (3h in this case).

**Describe the solution you'd like**
Currently, alert end times are set to [3 intervals from now](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5c63d69454fd89337eb0909903023e8f1b743027/app/vmalert/group.go#L340). We can add a flag to indicate end times should not be set, then resolve time can be controlled by Alertmanager itself - see [resolve_timeout param](https://prometheus.io/docs/alerting/latest/configuration/#configuration-file).

**Describe alternatives you've considered**
Resolve related alerts while updating/deleting an alert rule.

**Comment by hagen1778** [comment]
Sending auto-resolves when alert is removed from the config may complicate the process due to the following reasons:
1. config reload may become significantly slower due to need to make additional HTTP calls
2. no guarantees that alert will be resolved, since there are chances that resolve-call won't be delivered for some reason (and we can't afford endless retries during the config reload)

The new flag for disabling adding `endsAt` param to notifications may be added easily. The only thing which concerns me is that Prometheus always adds this param. Hence, some compatibility may be lost.
I wonder, if we should provide a way to configure the resolve time somehow? Maybe not globally, but per-rule/group. WDYT?
How many rules with 1h evaluation interval do you have?

**Comment by leizhag** [comment]
> 1. config reload may become significantly slower due to need to make additional HTTP calls
> 2. no guarantees that alert will be resolved, since there are chances that resolve-call won't be delivered for some reason (and we can't afford endless retries during the config reload)

No guarantee on this is ok to me. (Make HTTP calls after reloading config without retries.) When the resolve-call failed to be delivered, alerts still can be auto-resolved after 3x intervals.

> I wonder, if we should provide a way to configure the resolve time somehow? Maybe not globally, but per-rule/group. WDYT?

Global and group-level are both good enough to me.

> How many rules with 1h evaluation interval do you have?

10% groups (tens out of hundreds) have large evaluation intervals.

How about a flag like `max-resolve-duration`? With this, we can set `alert.End` to be `max(maxResolveDuration, time.Now().Add(3 * interval)`.

**Comment by valyala** [comment]
The commit 7df731ea910d249396cc28635c5c61c911605574 adds `-rule.maxResolveDuration` command-line flag for limiting auto-resolve duration for alerts. @leizhag , could you build `vmalert` from this commit according to [these docs](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) and verify whether this flag works for you?

**Comment by valyala** [comment]
The `-rule.maxResolveDuration` command-line flag is available starting from [vmalert v1.66.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
