### ISSUE TITLE
Some optimization logic was lost after the refactoring

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#1603]
Hi @valyala 
I noticed that in this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d05cac6c9859631b4f90de8a949d22ba10d6fe9f , the original filter logic has been removed. Should this optimization logic #781 #783 still be necessary now?

![image](https://user-images.githubusercontent.com/3659110/132453517-522e9ec5-3d76-4466-bf75-9348f0a49c62.png)

**Comment by valyala** [comment]
This logic has been removed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d05cac6c9859631b4f90de8a949d22ba10d6fe9f , because it became unused after the refactoring. The `getMetricIDsForTagFilterSlow` function was called from two places before the refactoring:

* From per-day index search. `filter=nil` arg was passed to this function here because production testing showed slowdown with the filter. See the corresponding comment at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d05cac6c9859631b4f90de8a949d22ba10d6fe9f#diff-31747331b2a09f4e4df81c672333af155957a49dfcfec9ac3834b29ac78aecaaL2387-L2389
* From global index search. This code has been removed in the commit - now global index search re-uses the per-day index search code. This means that the `filter` arg became unused for `getMetricIDsForTagFilterSlow()` function now.

Probably the `filter` arg can give performance advantage in some cases such as global index search. This needs to be tested in production though.

**Comment by faceair** [comment]
Would it be better if we remove the first and last filters ?
![image](https://user-images.githubusercontent.com/3659110/132886280-7eca316f-5275-4ae8-b7ad-37bde5aae6e1.png)

Another problem may be that HasCommonMetricIDs are not fast enough ? If the MetricIDs are sequential, we might be able to reuse something like the last lookup offset in the filter ?
![image](https://user-images.githubusercontent.com/3659110/132886870-f16aa431-0beb-4247-b1b9-f75a74caf351.png)

**Comment by faceair** [comment]
An index may contain a very large number of metricids, and the overhead of determining whether two very large metricids intersect is much larger and harder to optimize.
Matching regular expressions directly is much less overhead in the vast majority of cases.
My previous idea was wrong, sorry for that. 😢
