### ISSUE TITLE
how can i get one metrics in vm all points ???

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#1623]
how can i get one metrics in vm all points ???

**Comment by jiangxinlingdu** [comment]
i use  /api/v1/status/tsdb?match[]=metricsName  ,but i can't get metrics in tsdb have how much points

**Comment by jiangxinlingdu** [comment]
i see https://docs.victoriametrics.com/#tsdb-stats

**Comment by jiangxinlingdu** [comment]
> i see https://docs.victoriametrics.com/#tsdb-stats

![image](https://user-images.githubusercontent.com/6373972/133584770-d66ed589-695a-4e06-b39a-a4600508f42f.png)

**Comment by valyala** [comment]
The total number of datapoints stored in VictoriaMetrics is exported at `http://victoriametrics-host:8428/metrics` page via `vm_rows{type="storage/big"}` and `vm_rows{type="storage/small"}` metrics. These metrics are available via Grafana dashboard for VictoriaMetrics - see [these docs](https://docs.victoriametrics.com/#monitoring).

VictoriaMetrics doesn't provide an efficient way to get the number of datapoints per each metric. However, there is non-optimal way - to query the number of datapoints via `/api/v1/query` with [count_over_time](https://docs.victoriametrics.com/MetricsQL.html#count_over_time) function. For example, the following call would return the total number of samples for all the metrics with `metricName` name over the last year.

```metricsql
curl http://victoriametrics-host:8428/api/v1/query -d 'query=sum(count_over_time(metricName[1y]))'
```

Note that the query can be quite slow when `metricName` metrics contain big number of time series and/or samples, since it naturally finds all the matching time series for the last year and counts all the datapoints in them.

**Comment by jiangxinlingdu** [comment]
@valyala thanks
