### ISSUE TITLE
vmalert does not restart rule groups when only the interval field is changed

### ISSUE THREAD

**Issue by arramos84** [VictoriaMetrics/VictoriaMetrics#1641]
**Describe the bug**
When making changes to vmalert rule groups if only modifying/adding the `interval` field, then hitting the reload endpoint, the rule group is never restarted. If making a change to a rule itself in the group or adding a new rule to the group, then hot reloading works and the modified group will be restarted.

This may also be the case with the `concurrency` field as that and `interval` were later additions to the vmalert rule groups.

Ran with vmalert `1.64.1` `1.65.0` and `1.66.1` and still saw the issue

**To Reproduce**

- Change/Add `interval` field in a rule group with the appropriate values.
- Curl vmalert reload endpoint
- Observe that the rule group is never restarted

**Expected behavior**
Rule group should be restarted

**Logs**
No errors, just logs showing that the reload endpoint was hit but no rules restarted.

**Comment by valyala** [comment]
The issue must be fixed in the commit 0e35fc9538727f8c2ea4ae88cda9ab2223435010 . @arramos84 , could you build `vmalert` from this commit according to [these docs](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) and verify whether it properly reloads rule groups after `interval` and/or `concurrency` fields are changed? If everything works as expected, then the commit will be included in the next release.

**Comment by valyala** [comment]
The bugfix has been included in [vmalert v1.66.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@arramos84 , feel free re-opening the issue if it isn't fixed yet.
