### ISSUE TITLE
why use maxMetricIDsPerRow to limits the number of metricIDs in tag->metricIDs row

### ISSUE THREAD

**Issue by debuger6** [VictoriaMetrics/VictoriaMetrics#1650]
Hi, there is a question that why **mergeTagToMetricIDsRows** limits the number of metricIDs in tag->metricIDs row with **maxMetricIDsPerRow**. I think it's better not to limit, as merge all same prefix items to be a row not only can reduce storage but also improve query performance.

**Comment by valyala** [comment]
The limit on the number of metricIDs per row is needed in order to reduce the size of `index` and `metaindex` data structures created in `lib/mergeset`. These data structures consist of an array of [mergeset.blockHeader](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/mergeset/block_header.go#L12) and [mergeset.metaindexRow](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/mergeset/metaindex_row.go#L13), which, in turn, contain `firstItem` field. This field contains the first row in the corresponding `indexdb` data block. If each row could contain big number of metricIDs, then the `firstItem` would become big too. This would increase the size of `index` and `metaindex` in-memory data structures. Additionally, the summary size of all the rows in data block is limited by 64KB (in order to fit L1 CPU cache and get fast performance during packing/unpacking of the block). If the row size is big, then the number of rows per block is small. This reduces the efficiency of the index, since the ratio for `data_size` / `index_size` becomes small.

This is documented at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8ed95e82c645497b95f202313260ead4640ffb69/lib/storage/index_db.go#L3123-L3126

**Comment by zhenyuxie** [comment]
> The limit on the number of metricIDs per row is needed in order to reduce the size of `index` and `metaindex` data structures created in `lib/mergeset`. These data structures consist of an array of [mergeset.blockHeader](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/mergeset/block_header.go#L12) and [mergeset.metaindexRow](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/mergeset/metaindex_row.go#L13), which, in turn, contain `firstItem` field. This field contains the first row in the corresponding `indexdb` data block. If each row could contain big number of metricIDs, then the `firstItem` would become big too. This would increase the size of `index` and `metaindex` in-memory data structures. Additionally, the summary size of all the rows in data block is limited by 64KB (in order to fit L1 CPU cache and get fast performance during packing/unpacking of the block). If the row size is big, then the number of rows per block is small. This reduces the efficiency of the index, since the ratio for `data_size` / `index_size` becomes small.
> 
> This is documented at
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8ed95e82c645497b95f202313260ead4640ffb69/lib/storage/index_db.go#L3123-L3126

Thanks Valialkin. Your answer solved my doubt. Looking forward to having more communication with you, thanks again.

**Comment by zhenyuxie** [comment]
There is another question about maxMetricIDsPerRow that why use condition "mp.MetricIDsLen() < maxMetricIDsPerRow/2" to judge whether a row is complete, why not "mp.MetricIDsLen() < maxMetricIDsPerRow"

**Comment by valyala** [comment]
> There is another question about maxMetricIDsPerRow that why use condition "mp.MetricIDsLen() < maxMetricIDsPerRow/2" to judge whether a row is complete, why not "mp.MetricIDsLen() < maxMetricIDsPerRow"

Unfortunately I didn't remember details. This code has been introduced in the commit f52874dab4e976a805bc7c385d08a4ae47ef42ce two years ago. Probably it would be better to use `mp.MetricIDsLen() < maxMetricIDsPerRow`. This needs additional investigations.

**Comment by valyala** [comment]
Closing the question as answered.
