### ISSUE TITLE
Vmagent is not updated to v1.66.2

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#1657]
**Describe the bug**
error when upgrading vmagent helm chart from version 1.63.0 to version 1.66.2

**To Reproduce**
helm  upgrade --install vmagent vm/victoria-metrics-agent -f values.yaml -n namespace

**Logs**
{"ts":"2021-09-27T15:31:20.249Z","level":"panic","caller":"VictoriaMetrics/lib/persistentqueue/persistentqueue.go:152","msg":"FATAL: cannot acquire lock on file \"/tmpData/persistent-queue/1_1E2BDE0D40931185/flock.lock\": resource temporarily unavailable"}

**Version**
vmagent:v1.66.2

**Used command-line flags**
extraArgs:
  envflag.enable: "true"
  envflag.prefix: VM_
  loggerFormat: json
  promscrape.config: /etc/config/prometheus.yml

**Comment by valyala** [comment]
The error message suggests that the previous `vmagent` app wasn't shut down yet. It keeps the lock on the file in order to prevent from concurrent access to data files, which may lead to data corruption. The solution is to run `ps axu | grep vmagent`  and kill the previous version of `vmagent`. Additionally it is recommended looking into the log of the killed `vmagent` in order to understand why it wasn't shut down gracefully.

**Comment by Wyfy0107** [comment]
I have a similar issue but with vmsingle. I install vmsingle using helm and after upgrading, the new container can not accquire lock on the volume because the previous vmsingle container is still running. What would be the best procedure for upgrading with persistent volume then if we don't want downtime and terminate the old container?

**Comment by Wyfy0107** [comment]
@valyala Do you have any thoughts on this ?

**Comment by f41gh7** [comment]
> I have a similar issue but with vmsingle. I install vmsingle using helm and after upgrading, the new container can not accquire lock on the volume because the previous vmsingle container is still running. What would be the best procedure for upgrading with persistent volume then if we don't want downtime and terminate the old container?

It's not possible by design. It's recommended to use `rollingUpdate` strategy -`ReCreate`, since the same PVC cannot be used by multiple pods. 

 For High-Availability, I'd recommend to use Cluster version.

 For future readers, in case when persistence is enabled for `vmagent` chart.
```yaml
persistence:
  enabled: true
```
`ReCreate` strategy must be used.

```yaml
deployment:
  enabled: true
  strategy: 
   type: ReCreate
```
