### ISSUE TITLE
vmalert - port the `resendDelay` configuration 

### ISSUE THREAD

**Issue by ivansenic** [VictoriaMetrics/VictoriaMetrics#1665]
Seems that vmalert sets the `endsAt` at 3x of the evaluation interval. This is a guess since we have `30s` evaluation period and then `endsAt` is always `90s` from the `updatedAt`:

```
"endsAt":"2021-09-29T10:58:10.716Z" "updatedAt":"2021-09-29T10:56:40.716Z"
"endsAt":"2021-09-29T10:55:38.258Z" "updatedAt":"2021-09-29T10:54:08.259Z"
```

Prometheus has a 4x increase from either evaluation interval or a `resendDelay` configuration option, what ever is larger. Can this be ported so that we can have shorter evaluation periods and larger time spans to the `endsAt`? See configuration [option](https://github.com/prometheus/prometheus/blob/48a101be1b59dce6f9285b40d686be24f7793473/cmd/prometheus/main.go#L295) and [evaluation](https://github.com/prometheus/prometheus/blob/dc2f1993d8f88ff5d17d63c70688e97ec40973c1/rules/alerting.go#L481).

**Is your feature request related to a problem? Please describe.**
We come to situations where alertmanager is not notified in time and alertmanager resolves the alert too early because of the short `endsAt` values. The reason why this happens is irrelevant here, for us it's most likely a large amount of evaluation rules, but it could be infrastructure issues, `vmalert` pod going down or anything else.

**Describe the solution you'd like**
Allow configuration settings that can effectivelly increase `endsAt` and decouple it from the evaluation period.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by hagen1778** [comment]
Hi @ivansenic! https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2296 has been merged and will be available in the next release. Meanwhile, you can try to [build vmalert from sources](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources).

**Comment by mxsiegle** [comment]
Hi @hagen1778,

sorry for the question, but isn't this the opposite of what should happen? Right now it shortens the resolve duration, but for the issue described above I'd expect to have a longer duration instead.

i.e. if the VMAlert pod goes down and stops sending updates, Alertmanager resolves the alert. Previously it was set to 3 times of the group's interval and now it's capped at 4 times the group's interval. The new resendDelay variable just shortens this time.

Could we introduce an additional variable to configure the resolve duration to a custom value?
Let's say the group interval is 10s and e.g. because VMAlert crashed there are no more updates, that would mean the alert is resolved latest after 40s (4*10s). So every short infrastructure hiccup would cause all alerts to resolve. Once VMAlert comes back up maybe seconds later all alerts would fire again. A custom variable to set the delay to e.g. to 2 minutes would help in this case to prevent all alerts from firing again. Then one update within 2 minutes would be enough to not resolve any alerts.

Or maybe I misunderstand how it works?

**Comment by hagen1778** [comment]
Hi @mxsiegle! The `resendDelay` flag now acts as a minimum time used for alert's `End` param (or ValidUntil in other words). It would mean that if `group interval is 10s` and `resendDelay=1m` - alert will be resolved in 4 times of `resendDelay`: 4min. See details here: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/11ae1ae92432731989bfe8af1bd7e4e7384719fc/app/vmalert/group.go#L295-L305

By default, `resendDelay` is set to 0 in order to remain backward compatible with prev versions behaviour.

**Comment by mxsiegle** [comment]
Thanks @hagen1778. For some reason I read the first if statement wrong. `groupInterval < delta` instead of `groupInterval > delta`.
That was where my whole confusion came from but the other way around makes much more sense. What difference a single character can make :)
Thanks again.

**Comment by valyala** [comment]
vmalert supports `-rule.resendDelay` command-line flag starting from [v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
