### ISSUE TITLE
Combine vmagent and vmgateway functionality

### ISSUE THREAD

**Issue by arramos84** [VictoriaMetrics/VictoriaMetrics#1676]
As enterprise users of VictoriaMetrics Cluster solution we have had multiple versions of our VM ingestion pipeline. They have looked like this

1st - We ingested all data into `vminsert` and applied relabel rules across the board. This was applied to all tenants as `vminsert` does not have a way to apply relabel rules to a specific tenant or a way to reload relabel configs.

2nd - We now ingest data into `vmagent` cluster. Each tenant has a unique external label that allows us to identify their metrics and apply a unique relabel config to via `vmagent` `remoteWrite.urlRelabelConfig` and `remoteWrite.url`. Furthermore, using a sidecar watcher, `vmagent` can hot load relabel rules for specific tenants. This relabeled data is then written to `vminsert` which we no longer employ relabeling on.

3rd (Aspiring Solution) - We need a way to throttle tenants that may send us metrics with cardinality explosions or simply too much data. `vmagent` only seems to have a global (all tenants) hourly and daily limit on timeseries. Additionally, we see that `vmgateway` looks like it can provide the throttling needed at the accountID/tenant level. This looks great, but adds now another (3 total) services that need to ingest ALL of the requests before they can be written to `vmstorage`. This makes it more difficult to manage and adds an extra hop for all the data in the system.

Is there a way to add tenant specific relabeling in `vmgateway` similar to what `vmagent` has (at least it's doable with some k8s configs)? Since `vmagent` can purely be used as an ingestion tool for a multitenant cluster, it would seem to be a valid use case.

Thanks a lot for any help here!

**Comment by valyala** [comment]
We decided to don't add [vmgateway](https://docs.victoriametrics.com/vmgateway.html) functionality (e.g. per-tenant access control and rate limiting) into [vmagent](https://docs.victoriametrics.com/vmagent.html), since this may significantly complicate vmagent configuration and operation. This also will make vmagent less reliable. For example, if a single tenant will start sending big amounts of data, this may negatively impact all the other tenants, since all the data from all the tenants are processed by the same vmagent. So it is better from maintainability, reliability and extensibility points of view to use a separate service with custom logic for authorization, routing and rate limiting (such as vmgateway) in front of vmagent services.

**Comment by arramos84** [comment]
> We decided to don't add [vmgateway](https://docs.victoriametrics.com/vmgateway.html) functionality (e.g. per-tenant access control and rate limiting) into [vmagent](https://docs.victoriametrics.com/vmagent.html), since this may significantly complicate vmagent configuration and operation. This also will make vmagent less reliable. For example, if a single tenant will start sending big amounts of data, this may negatively impact all the other tenants, since all the data from all the tenants are processed by the same vmagent. So it is better from maintainability, reliability and extensibility points of view to use a separate service with custom logic for per-tenant authorization, routing and rate limiting (such as vmgateway) in front of vmagent services.

Hi @valyala , thanks for the response. Yes, Artem had let me know on a call a few weeks ago. I think we will be able to work with the existing arch. We might need to use a proxy of some sort to get the desired effect. Thanks!
