### ISSUE TITLE
query_range results not lining up with requested times

### ISSUE THREAD

**Issue by jacksontj** [VictoriaMetrics/VictoriaMetrics#171]
**Describe the bug**
when a query is sent to VM (e.g. `query_range?start=1564328340&end=1564501440&step=2853&query=sum(increase(nodeproxy_http_response_time_histogram_seconds_bucket{app%3D"349"}[10m])) by (le)` ) the data returned doesn't line up with the times given. For example, although the start was `1564328340` the first time returned was `1564326720`. This ends up causing a lot of issues as the points aren't where the caller expects. This ends up causing a lot of issues as the points aren't where the client expects-- and in the case of promxy this ends up causing data to look like its missing.

**To Reproduce**
Pcaps etc. are available in https://github.com/jacksontj/promxy/issues/202

**Expected behavior**
For a query_range prom response the start time should match the requested start and the values should be every `step` from that start time.

**Comment by valyala** [comment]
This is the intended behavior, which improves response caching inside VictoriaMetrics by aligning start and end of the requested time range to multiples of `step` value. The following solutions exist:
1) To remove the time range alignment for all the incoming requests at the cost of decreased response cache hit rate.
2) To remove the time range alignment only for big `steps` exceeding 5 minutes - the default staleness period in Prometheus.
3) To add a special query arg like `no_timerange_align`, so Promxy could pass this arg to VictoriaMetrics in order to disable time range alignment.

**Comment by jacksontj** [comment]
1 -- VM does internal caching for this? I would have expected external sources (e.g. trickster) to do this


Any of those 3 seem like viable options for my particular use-case; so I'll leave it up to you do pick for VM. Personally I'd prefer 1 as it makes things more accurate (also more like prometheus' API) -- since I imagine other API clients would have similar concerns with the inaccuracy. But like I said any of those 3 solve the issue I'm seeing :)

**Comment by valyala** [comment]
> VM does internal caching for this? I would have expected external sources (e.g. trickster) to do this

Yes, VM does internal response caching similar to [Trickster](https://github.com/Comcast/trickster). It can be disabled by passing `nocache=1` query arg to `/api/v1/query_range`. I removed `start` and `end` args adjustments when `nocache=1` query arg is passed to `/api/v1/query_range` in commit 9721d06c6aca2f2a618dbdb58cb3ed9072390ebc . This enables option 3 - `Promxy` can pass `nocache=1` to VictoriaMetrics in order to disable response caching together with time range alignment.

**Comment by jacksontj** [comment]
This should work for now, if/when you add support for prometheus' RemoteRead I'm not sure how we'd do the equivalent :/

**Comment by jacksontj** [comment]
https://github.com/jacksontj/promxy/pull/216 has added a `query_params` option to the servergroup to add arbitrary query params to the downstream request. I've added a specific callout in the example config as well -- but it might be worth calling out in w/e promxy docs you have as well :)

**Comment by valyala** [comment]
> This should work for now, if/when you add support for prometheus' RemoteRead I'm not sure how we'd do the equivalent :/

There are no plans to add `remote_read` API, since it is unclear how to stream big number of samples in [ReadResponse protobuf message](https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto) without buffering all of the samples in RAM.

There is an alternative, which Promxy can try using instead of `remote_read` API - see [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series).

> it might be worth calling out in w/e promxy docs you have as well

I'll update docs about promxy soon. They should contain information about `nocache=1` and missing [extended promql support](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL) when sending queries via Promxy.

**Comment by valyala** [comment]
fyi, the `nocache=1` fix is available in the release [v1.27.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by jacksontj** [comment]
> There is an alternative, which Promxy can try using instead of remote_read API - see /api/v1/export.

I might take a look into that later, for now the vast majority of calls are sent to the promql interface -- its just those last remaining "raw" points I need to fetch that would go through this new API (or through remote_read). At this point I don't think its a major perf win, but we'll see :)

> fyi, the nocache=1 fix is available in the release v1.27.2.

Thanks for the quick turnaround, its always nice to have bugs fixed up so quickly :)
