### ISSUE TITLE
vmselect return connection pool errors on storage down

### ISSUE THREAD

**Issue by johnatannvmd** [VictoriaMetrics/VictoriaMetrics#1767]
**Describe the bug**
We use vmselect for cross cluster search as a recommended solution. When one of the storage nodes fails, vmselect return `cannot obtain connection from a pool` instead of partial response.

![image](https://user-images.githubusercontent.com/4918448/139524936-f2a26435-3dd2-49be-b226-cc56afd3e392.png)

**To Reproduce**
vmselect with several storage nodes(6 for example), turn off 3 of them.

**Expected behavior**
vmselect should remove failed storage nodes from the pool, and return it back, when storage nodes became available again.

**Logs**
Grafana response
```
"error when exporting data for query=\"...<REDACTED>..\": error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage 10.120.137.211:8401: cannot obtain connection from a pool: cannot dial 10.120.137.211:8401: dial tcp4 10.120.137.211:8401: i/o timeout"
```
vmselect logs:
```
Oct 30 06:43:41 sjc01-c01-vic04 vmselect[6994]: warn        victoriametrics/app/vmselect/main.go:523        error in "/select/18/prometheus/api/v1/query?query=...<REDACTED>...": error when exporting data for query="...<REDACTED>..." on the time range (start=1635575980001, end=1635576160000): cannot fetch data for "AccountID=18, ProjectID=0, MinTimestamp=2021-10-30 06:39:40.001 +0000 UTC, MaxTimestamp=2021-10-30 06:42:40 +0000 UTC, TagFilters=[{...<REDACTED>..., IsNegative: false, IsRegexp: true}\n]": error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage 10.120.137.210:8401: cannot obtain connection from a pool: cannot dial 10.120.137.210:8401: dial tcp4 10.120.137.210:8401: i/o timeout
```

**Version**
1.63.0

**Used command-line flags**
-search.latencyOffset 0 \
-cacheDataPath /data/victoria/vmselect_autogen \
-httpListenAddr :8481 \
-replicationFactor 2 \
-search.maxQueryDuration 30s \
-dedup.minScrapeInterval 10s \
-search.logSlowQueryDuration 5s \
-search.resetCacheAuthKey ASDFQWER \
-selectNode 6 nodes \
-storageNode 12 nodes \
-loggerDisableTimestamps \
-memory.allowedPercent 20

**Comment by johnatannvmd** [comment]
Also this would be great if there was two separate options for timeouts. One for the query timeout, another for the storage timeout. First one will work when connection is good, but query is slow. Second one will work when connection between vmselect and vmstorage is unresponsive.

**Comment by valyala** [comment]
The `error when exporting data for query` error is emitted when the query to [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) endpoint contains the duration in square brackets at the end. Something like `/api/v1/query?query=up[1h]&time=...` . Such query returns raw samples for the given label selector (`up` in this case) on the given time range (`1h` - one hour) ending at the given `time`. This is basically data export. See [this article](https://valyala.medium.com/analyzing-prometheus-data-with-external-tools-5f3e5e147639) for more details.

By default VictoriaMetrics allows returning partial responses from usual queries to `/api/v1/query` and [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) if some of `vmstorage` nodes are temporarily unavailable. This is expected condition in cluster mode. It is automatically resolved when the unavailable `vmstorage` nodes return to the cluster. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for details.

VictoriaMetrics doesn't allow returning partial responses for data export queries if some of the `vmstorage` nodes aren't available. This protects from receiving partially exported data by third-party applications, which may improperly work when receiving partial data. @johnatannvmd , could you give more context for your use case in order to understand how the exported data is used later and whether it is OK if the exported data may miss a part of samples and series?

Probably it would be better setting up a separate set of `vmselect` nodes, which see only the `vmstorage` nodes from the given cluster, and then send export queries to this set of `vmselect` nodes.

**Comment by valyala** [comment]
See also [these docs on high availability in VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#high-availability).

**Comment by johnatannvmd** [comment]
@valyala Thanks for your response!

> VictoriaMetrics doesn't allow returning partial responses for data export queries if some of the vmstorage nodes aren't available
Is there any query parameters like `deny_partial_response` but to accept of partial response for /api/v1/query request?

> could you give more context for your use case in order to understand how the exported data is used later and whether it is OK if the exported data may miss a part of samples and series?
I do not export data in any cases, "Grafana response" is the error that Grafana shows me when I try to open some dashboards.

We built setup like this to achieve cross location replication(for redundancy) and HA.

![download (2)](https://user-images.githubusercontent.com/4918448/139830034-2bd4c658-12e7-46a5-87d2-87730065ee0a.png)
We heavily using tenants to separate metrics across internal teams, so replacement kafka with vmagent is not possible. Tennant IDs is the same across all locations.

Recently we have destruction testing where one of the location was air gapped for one hour. And we got errors that I mention above, during the test. Some of the queries works, some of them not.

> The error when exporting data for query error is emitted when the query to /api/v1/query endpoint contains the duration in square brackets at the end
I additionally checked the reported errors and there are all kind of queries, with and without square brackets.

Most of all I worry about this part of the message:
```
cannot obtain connection from a pool: cannot dial 10.120.137.211:8401: dial tcp4 10.120.137.211:8401: i/o timeout
```

Setup promxy for every tennant will be painful.

**Comment by johnatannvmd** [comment]
Looks like idea of separate timeouts for queries and storages, plus health checks between vmselect and vmstorage already mentioned here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/711#issuecomment-768305643

Also this would be great if we have storages' health metrics on the vmselect/vminsert side

**Comment by johnatannvmd** [comment]
@valyala thanks a lot for your help!

**Comment by valyala** [comment]
FYI, `vmselect` assumes that the response is full if it cannot receive the response from up to `-replicationFactor - 1` `vmstorage` nodes starting from [v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Note also that `vmselect` supports querying other `vmselect` nodes (aka multi-level cluster setup) starting from `v1.79.0` - see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup).

**Comment by valyala** [comment]
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2778 for details on multi-level select setup when a top-level vmselect nodes can be configured to query lower-level vmselect nodes from different VictoriaMetrics clusters.
