### ISSUE TITLE
[MetricsQL] Add LTTB function

### ISSUE THREAD

**Issue by joaopaulobdac** [VictoriaMetrics/VictoriaMetrics#1775]
## Is your feature request related to a problem? Please describe.
Hi! I'm considering using VictoriaMetrics instead of TimescaleDB for a project due to it's easier operation, scalability and query syntax, but the only feature missing is support for the LTTB algorithm:

[Uber Engineering Blog: The Billion Data Point Challenge: Building a Query Engine for High Cardinality Time Series Data](https://eng.uber.com/billion-data-point-challenge/)

[TimescaleDB: Largest Triangle Three Buckets](https://github.com/timescale/timescaledb-toolkit/blob/main/docs/lttb.md)

## Describe the solution you'd like
```
lttb(series_selector[d], resolution)
```

Where `resolution` is `Number of points the output should have.`

## Describe alternatives you've considered
Continue using TimescaleDB

**Comment by denisgolius** [comment]
@valyala, could you take a look ?

**Comment by joaopaulobdac** [comment]
One more link: [An SQL implementation of the ‘Largest Triangle Three Bucket’ algorithm](https://medium.com/@datylon/sampling-time-series-data-sets-fc16caefff1b)

**Comment by valyala** [comment]
@joaopaulobdac , thanks for filing the feature request! Could you share more details on the use case where the LTTB function is needed? Did you consider using the [rollup](https://docs.victoriametrics.com/MetricsQL.html#rollup) function instead? See [this article](https://valyala.medium.com/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832) for more details about the `rollup*` function usage.

**Comment by joaopaulobdac** [comment]
I use it to decrease the amount of data points sent to a custom chart I made using D3.js.

While I was making the chart, I encountered a problem where If I simulated for example 500K data points in the database (think an IoT sensor sending 1 reading every 60 seconds for 1 year), querying the data for the entire year period in SQL, sending it over HTTP and charting it in the browser was basically unusable. The request was like 25MB and charting was so slow that it hanged the page.

But using the LTTB function from the timescaledb-toolkit I can just pass it a resolution arg in the query, 1920 points for example, and it downsamples the result while retaining visual fidelity. Now the same request hardly exceeds 16KB and charting is practically instantaneous.

I don't use grafana, but I when I tried it I remember seeing that it uses the width of the chart to limit the amount of samples in the promQL query but I don't know if the method used retains visual fidelity or if it was just averaging.

The advantage of leaving this optimization to the database is that it can then be used with any visualization tool, be it grafana or a custom web page using a different chart library.

If I were to use the rollup function, would I have to draw 3 lines in the chart for the same time series? Would it also work for gauges instead of counters? Using LTTB, I would just make a normal query and VictoriaMetrics would downsample the result to the requested resolution.

**Comment by valyala** [comment]
VictoriaMetrics provides [`/api/v1/query_range`](https://docs.victoriametrics.com/keyconcepts/#range-query) endpoint for downsampling at query time. Grafana uses this endpoint when drawing graphs for [Prometheus-compatible datasources such as VictoriaMetrics](https://docs.victoriametrics.com/#grafana-setup).

The `LTTB` functionality cannot be added to [MetricsQL](https://docs.victoriametrics.com/metricsql/) in the form described [above](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1775#issuecomment-963127795), since MetricsQL is designed to work via [`/api/v1/query_range`](https://docs.victoriametrics.com/keyconcepts/#range-query) and [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#range). So it is unlikely that the `LTTB` functionality will be added to VictoriaMetrics.

Additional details: by default VictoriaMetrics uses [last_over_time](https://docs.victoriametrics.com/metricsql/#last_over_time) function for performing the downsampling at `/api/v1/query_range`. But it is possible to use any [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions) for the downsampling at query time.

Closing the feature request as won't implement.
