### ISSUE TITLE
why require Prometheus for this ? so usefull internal database

### ISSUE THREAD

**Issue by depfryer** [VictoriaMetrics/VictoriaMetrics#180]
Hi :smile: 

i'm frustrated by this : 

### Monitoring

VictoriaMetrics exports internal metrics in Prometheus format on the /metrics page. **Add this page to Prometheus' scrape config** in order to collect VictoriaMetrics metrics. There is an official Grafana dashboard for single-node VictoriaMetrics.

i'm not using prometheus but telegraf, and if i make a homemade soft and want to see internal metric ?

just add to command line option like `--internalSave *timing*` and it will savec each *timing* the actual set 

timing can be like "10m" for 10 minutes, "10s" 10 seconds ect ... (or only in second like int between 1 and X)

thank you for the great job :+1:

**Comment by hagen1778** [comment]
#30

**Comment by valyala** [comment]
@depfryer , this feature is on our road-map. Closing as duplicate for #30 .

**Comment by valyala** [comment]
@depfryer , self-scraping for `/metrics` page has been added in single-node version at the commit 9df5b2d1c35fb7f57ea11b42f36f05cefe48ac09 . It will be available in the next release of VictoriaMetrics.
In order to enable self-scraping, `-selfScrapeInterval` command-line flag must be set to non-zero value. For instance, `-selfScrapeInterval=10s` would enable self-scraping of `/metrics` page with 10 seconds interval.
