### ISSUE TITLE
What's the maximum number of rows a single insert can process

### ISSUE THREAD

**Issue by wangqiongkaka** [VictoriaMetrics/VictoriaMetrics#1808]
Is there any limitation that the maximum number of rows a single insert is 10K?
<img width="667" alt="89c5ae92027d87bf1d511fba8" src="https://user-images.githubusercontent.com/34996871/141295035-168abd64-6fca-4ecb-a3b7-2f96a1696338.png">

**Comment by YuriKravetc** [comment]
Hi,
The only such limiter is mentioned in - capacity planning documntation. So the CPU might be a limiter in your case.
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning
"The total number of CPU cores needed for all the vminsert nodes can be calculated from the ingestion rate: CPUs = ingestion_rate / 100K."

But most probably, what you should check is the Size limiter instead of rows limiter.
-maxInsertRequestSize size
    	The maximum size in bytes of a single Prometheus remote_write API request
    	Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 33554432)

**Comment by valyala** [comment]
@wangqiongkaka , which protocol do you use for data ingestion into VictoriaMetrics? If you use Prometheus remote_write protocol (e.g. if you push data to `/api/v1/write` endpoint), then the maximum request size is limited by `-maxInsertRequestSize` as @YuriKravetc mentioned above. If you send data from Prometheus, then you can tune `max_samples_per_send` option at `remote_write -> queue_config` section. See [these docs](https://docs.victoriametrics.com/#prometheus-setup) for details.

If you use other data ingestion protocols such as Influx line protocol, Graphite protocol, OpenTSDB put protocol, then the request size isn't limited - VcitoriaMetrics can accept arbitrary number of samples in a single request, since it processes the incoming data in streaming mode. See [these docs](https://docs.victoriametrics.com/#how-to-import-time-series-data) for details.

**Comment by wangqiongkaka** [comment]
> streaming

Thanks very much, I turned on streaming mode
