### ISSUE TITLE
Short connection, one time use, or connection renewable?

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1822]
**Is your feature request related to a problem? Please describe.**
As we find the data change time to time like this:
![image](https://user-images.githubusercontent.com/33677006/141965201-dd9494f7-0177-4930-8240-be27c66f131e.png)
We checked with the Kubernetes service provider, this is something complex to handle. On their side, the Kubernetes-API services is load-balanced but difficult to provide a query key to the fixed endpoint. so when the connection changed balanced target, the value changed.
**Describe the solution you'd like**
As we checked in Prometheus, this case is rare happened, in most time is most time only be one of the value.
I tried to read the difference between vmagent and Prometheus on handling this issue, it seems Prometheus using a single routine to scrap a target, with a global shared parent context, this will result to keep the same TCP connection established between the scraper with the Kubernetes status API server behind the load-balancer.
This part each time vmagent will New a new context
![image](https://user-images.githubusercontent.com/33677006/141966779-9c6b5742-b9e0-4201-aef2-834a85c61e2b.png)
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/09b0641ccb64807fc0cbcbc3cae39e9482261d0e/lib/promscrape/client.go#L161
From my understanding this will randomly drop the old TCP connection, just pick up one connection or renew a new connection.
This will lead the Kubernetes load-balancer balance to another status API server.  
**Describe alternatives you've considered**
It might be possible to set up logic to make a pool of connections to the target, just reuse the context, only renew it when tcp connection is expired or broken.

**Comment by denisgolius** [comment]
Hi @renchili !
Could you please add more information about your issue? Because **vmagent** reuse old connections.

**Comment by valyala** [comment]
`vmagent` should re-use connections to scrape targets by default as @denisgolius mentioned above. It may close the connection to scrape target in the following cases:
* On scrape timeout
* On network error
* If the scrape target closes the connection

`vmagent` exposes `vm_promscrape_dials_total` metric at `http://vmagent:8429/metrics`. This metric is incremented each time `vmagent` establishes new connection to any scrape target. Usually new connection is established just immediately after the old connection is dropped. It would be great [monitoring this metric](https://docs.victoriametrics.com/vmagent.html#monitoring) in order to determine the churn rate for new connections to scrape targets. It may be useful to monitor `vm_promscrape_dial_errors_total` metric, which shows the number of failed attempts to connect to scrape targets.

`vmagent` also exposes the `vm_promscrape_conns` metric, which shows the current number of connections established to all the scrape targets.

**Comment by renchili** [comment]
Thanks for all your replies.
The question is 
![image](https://user-images.githubusercontent.com/33677006/142108313-cfa11ebd-0326-48fe-8899-6f6b2b3604e5.png)
As shown in the picture the QPS of Kubernetes-apiservice changed, after consulting the cloud service provider. This is caused by the load-balancer shifting the connection to another endpoint.
![image](https://user-images.githubusercontent.com/33677006/142108589-38fe9470-d8d5-4743-b6aa-12bfb45d6d8e.png)
If it is possible can we establish and keep the connection. Make the connection has some affinity that can point to the same kubernetes-apiserver, unless the TCP connection condition changed.

Maybe my assumption is not correct, but if the TCP connection is always the same connection, it should be the same endpoint. 
We not only scrape this k8s by this vmagent, is hard to know which TCP connection be renewed.
![image](https://user-images.githubusercontent.com/33677006/142124591-d9847286-f10c-44d2-b613-0249d1ce963b.png)
As shown in the screenshot, personally did not get the reason why the value flap before but is not flapping for now.
We just increased the `-http.connTimeout=3600s` so far, but we did not think this is the best way to archive this.

**Comment by renchili** [comment]
For more I simulated the scrape with python code, using session keeping the result be same for the session lifetime.
![image](https://user-images.githubusercontent.com/33677006/142129022-db4f1a32-ed9c-4a71-a71a-0a9b48f3cdd7.png)

**Comment by denisgolius** [comment]
> We checked with the Kubernetes service provider, this is something complex to handle. On their side, the Kubernetes-API services is load-balanced but difficult to provide a query key to the fixed endpoint. so when the connection changed balanced target, the value changed.

Try to set up the collection of metrics directly from the services, not through the Load Balancer and check if the problem described at the beginning will occur.

**Comment by renchili** [comment]
We cannot get to the direct endpoint, the Kubernetes apiservice is provided by the cloud provider as AWS or other cloud providers. Their Kubernetes is behind a domain name on ELB, we are not able to touch the real endpoint server

**Comment by denisgolius** [comment]
> We cannot get to the direct endpoint, the Kubernetes apiservice is provided by the cloud provider as AWS or other cloud providers. Their Kubernetes is behind a domain name on ELB, we are not able to touch the real endpoint server

What about to set up `vmagent` that will scrape metrics and send them to your monitoring?

**Comment by renchili** [comment]
> > We cannot get to the direct endpoint, the Kubernetes apiservice is provided by the cloud provider as AWS or other cloud providers. Their Kubernetes is behind a domain name on ELB, we are not able to touch the real endpoint server
> 
> What about to set up `vmagent` that will scrape metrics and send them to your monitoring? I mean to place `vmagent` to the infrastructure which you need to monitor.

sorry reply you 1 year's later. What you said, we discussed many time with the cloud vendor, is not that possible.
And but, still confused this metric why it variant.

**Comment by valyala** [comment]
`vmagent` by default keeps open HTTP connections to scrape targets for up to 2x`scrape_interval` - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e963d6c789c2d6583651e1b47175f82b117be56b/lib/promscrape/client.go#L83 . This effectively makes connection keep-alive for long durations, since every connection to every scrape target is re-used every `scrape_interval`. Connections can be closed on the following events:

- Scrape errors, if the remote target is unreachable for some reason. Scrape errors can be monitored for a particular target via [`up` metric](https://docs.victoriametrics.com/vmagent/#automatically-generated-metrics).
- Scrape timeout, if the remote target cannot be scraped during the configured `scrape_timeout`. See [`scrape_configs` docs](https://docs.victoriametrics.com/sd_configs/#scrape_configs) for details on `scrape_timeout`. Note that the `scrape_timeout` is automatically capped by `scrape_interval`. For example, if you configure scraping some target with `scrape_interval: 10s`, then the maximum possible `scrape_timeout` is also `10s`, even if it is set to `1h` in the configs. Scrape timeouts can be monitored for a particular target via [`scrape_duration_seconds` metric](https://docs.victoriametrics.com/vmagent/#automatically-generated-metrics).
- If the scrape target forcibly closes the connection established by `vmagent`. For example, if there are some timeouts or request limits configured at the scrape target side (or proxy side if the target is scraped via proxy).
- If `disable_keepalive: true` option is set for the given scrape target in [scrape_configs](https://docs.victoriametrics.com/sd_configs/#scrape_configs). Then a new connection is established for every scrape.
- If `vmagent` runs with `-promscrape.disableKeepAlive` command-line flag. Then a new connection is established for every scrape.

As for the first picture at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1822#issuecomment-971131458 , the proxy (Cloud k8s api proxy on the picture) is free to send every incoming query to different backends (k8s API server on the picture), even if all these queries are received from `vmagent` over the same persistent connection. This is how typical HTTP proxy and load balancer works contrary to TCP proxy. So, in general this is a bad strategy to rely on the assumption that the proxy forwards every request from the same HTTP keep-alive connection to the same backend.

@renchili , try upgrading [vmagent](https://docs.victoriametrics.com/vmagent.html) to [the latest available release](https://docs.victoriametrics.com/CHANGELOG.html) and see whether this helps resolving the issue. The `v1.97.1` release of `vmagent` contains enhancements on scraping targets, which return big number of metrics. This may reduce the probability of scrape timeout errors, which, in turn, may reduce connection churn rate for your case.

Closing the issue as answered.

@renchili , please open a new issue if you still experience the same problems with the [latest available vmagent release](https://docs.victoriametrics.com/CHANGELOG.html).
