### ISSUE TITLE
MetricsQL: possible to use limitk to get sorted series from sort_by_label?

### ISSUE THREAD

**Issue by tedpearson** [VictoriaMetrics/VictoriaMetrics#1920]
I've got a metric with a label that is sortable. I'd like to graph only one series, the one with the greatest label. Optionally, I would also like to graph the Nth series sorted by this label.

I don't think this operation is possible with the current MetricsQL functions. I've tried `limitk(1, sort_by_label(metric, "label_name"))`, but limitk seems to sort by a predictable hash function even if the time series are already sorted. I've also tried using `limit_offset` but it works the same way. Can anyone confirm or deny if there's any way to do something like this?

For more context, I'm trying to store forecast data, which is re-written every hour. I'd like to display the most recently written forecast. Since VM doesn't support overwriting metrics, the two approaches I can see are either delete the time series before each update, or use a different label for each update. I've implemented the delete-then-write approach as a workaround since I can't figure out how to query only the most recently written label.

**Comment by valyala** [comment]
The `delete-then-write` approach isn't recommended. VictoriaMetrics deletes time series lazily during background merge of smaller data parts into bigger data parts. So it needs to maintain the set of deleted time series in memory in order to filter out the deleted time series during queries. This means that VictoriaMetrics needs additional memory for holding the deleted time series ids. This also means that the query performance slows down with the number of deleted time series. See more details [here](https://docs.victoriametrics.com/#how-to-delete-time-series).

As for the [limitk](https://docs.victoriametrics.com/MetricsQL.html#limitk) and [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) functions, they return a randomized subset of time series out of the input set of time series. I think it would be great adding an additional function, which would return the first `k` time series out of time series passed to it. For example, `limitk_stable(3, sort_by_label(...))`.

See the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/951 .

**Comment by valyala** [comment]
The [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function must preserve the order of time series passed to it starting from the commit 1da19c0afbae98fbb403825e6f6129555789c290 . This commit will be included in the next release. In the mean time it is possible to build VictoriaMetrics from this commit according to [build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the `limit_offset` function works as expected.

**Comment by tedpearson** [comment]
Thanks a bunch for jumping into this. I've recompiled and installed, and will do some testing soon.

**Comment by tedpearson** [comment]
In limited testing `limit_offset` is indeed respecting time series sorting order. I'll get rid of my delete-then-write hack. (While not advised and certainly an ugly hack, it worked without issue so far)

**Comment by tedpearson** [comment]
Can confirm this is working correctly and is working great for my use case.

**Comment by valyala** [comment]
@tedpearson , thanks for the confirmation! VictoriaMetrics should preserve the order of input time series for [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing the feature request as done.

**Comment by githubsach** [comment]
Hi @valyala, 

Few more findings, its preserve the order if sort by value, but if use the sort_by_label_numeric it breaks.
Observed on latest version.

Thanks!

**Comment by githubsach** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1920
