### ISSUE TITLE
Instant query API returns inconsistent values

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/VictoriaMetrics#1941]
**Describe the bug**

The vmselect query api may return different value when called sequencely for a few times.

**To Reproduce**
Steps to reproduce the behavior. (omit sensitive information)

I have written a tiny python script to reproduce this issue:
```python
import requests


def query():
    url = 'http://{host}/query=max_over_time(histogram_quantile(0.9, idc_level_latency{source_idc="a", destination_idc="b", task_name="task1"})[5m:1m])&time=1639474506'

    payload = {}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)

    print(response.json()["data"]["result"][0]["value"])


def main():
    for i in range(30):
        query()


if __name__ == "__main__":
    main()

```

the output is:
```
[1639474506, '0.001914470893641866']
[1639474506, '0.001914470893641866']
[1639474506, '1.024']   //   <---  the outlier
[1639474506, '0.001914470893641866']
[1639474506, '0.001914470893641866']
[1639474506, '0.001914470893641866']
[1639474506, '0.001914470893641866']
[1639474506, '0.001914470893641866']
[1639474506, '0.0036141378690984563']
[1639474506, '0.11522263540299307']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.11522263540299307']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
[1639474506, '0.0019144706242073834']
```

**Expected behavior**

The values should be consistent.

**Version**

We use cluster version, including four to five vmselect/vmstorage/vminsert respectively.
Version is v1.61.0.

**Used command-line flags**
Please provide applied command-line flags used for running VictoriaMetrics and its components.

**Comment by valyala** [comment]
It is likely `vmselect` sometimes returns partially responses due to some reasons. Try adding `deny_partial_response=1` query arg to `/api/v1/query` - this should prevent from returning partial responses. In this case `vmselect` should return an error instead of partial response. See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability for more details.

**Comment by chenlujjj** [comment]
@valyala Thanks for your reply. I tried adding `deny_partial_response=1` to query args and rerun the script, but it didn't work. There are still outliers sometimes.

**Comment by chenlujjj** [comment]
Are there any other things I can do to help debug this issue ?

**Comment by valyala** [comment]
@chenlujjj , try simplifying the query and check whether the issue remains reproducible. For example, the initial query `max_over_time(histogram_quantile(0.9, idc_level_latency{source_idc="a", destination_idc="b", task_name="task1"})[5m:1m])` can be substituted with `histogram_quantile(0.9, idc_level_latency{source_idc="a", destination_idc="b", task_name="task1"})`. If the issue is still reproducible with the updated query, then it is likely it is related to `histogram_quantile()` instead of `max_over_time()`. If the `histogram_quantile(...)` continues returning inconsistent results, then it can be simplified further to `idc_level_latency{source_idc="a", destination_idc="b", task_name="task1"}`. It is likely this query will return multiple time series with distinct `le` labels. Verify whether VictoriaMetrics consistently returns the same results during this query execution. This technique should allow narrowing down the issue to the most simple query, where the issue is still reproducible.

**Comment by chenlujjj** [comment]
Thanks for the advice, I will try it.

**Comment by chenlujjj** [comment]
The issue cannot be reproduced when the initial query is substituted with `histogram_quantile(0.9, idc_level_latency{source_idc="a", destination_idc="b", task_name="task1"})`. So it seems like the problem is caused by `max_over_time ` function ？

**Comment by chenlujjj** [comment]
@valyala  Hi, any update on this issue ?

**Comment by valyala** [comment]
@chenlujjj , could you upgrade VictoriaMetrics cluster to `v1.73.1` and see whether this helps fixing the issue?

`vmselect` should report errors returned from `vmstorage` nodes starting from [v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Previously such errors were suppressed by default unless `-search.denyPartialResponse` command-line flag is passed to `vmselect` (see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for more details). These errors must be returned to the caller instead of returning partial response, since these errors contain useful information on how to fix the error at `vmstorage` node. So, starting from `v1.73.1`, `vmselect` may return partial response only if some of vmstorage nodes are temporarily unreachable / unavailable (for instance, during `vmstorage` maintenance and/or upgrade).
