### ISSUE TITLE
vmagent to support samples ordering among multiple remoteWrite.queues

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1948]
**Is your feature request related to a problem? Please describe.**
By default vmagent sends data to -remoteWrite.url via 4 parallel queues (aka -remoteWrite.queues=4). Certain samples for the same time series can be sent in parallel, so remote storage could receive them in out of order. This has no any effect on VictoriaMetrics TSDB, but may be rejected by other receiving systems like Cortex.
For context please see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1149#issuecomment-808134594

**Describe the solution you'd like**
Would be great if vmagent could guarantee the order of samples among multiple `remoteWrite.queues`. This will improve compatibility with other systems in Prometheus ecosystem. 

**Describe alternatives you've considered**
As alternative, we can wait until the issue of rejecting out-of-order samples will be solved on the Prometheus TSDB side - see https://github.com/prometheus/prometheus/issues/8534

**Comment by Allex1** [comment]
_vmagent is a tiny but mighty agent which helps you collect metrics from various sources and store them in VictoriaMetrics or `any other Prometheus-compatible storage systems` that support the remote_write protocol._ 🙄

**Comment by valyala** [comment]
A temporary workaround is to run vmagent with `-remoteWrite.queues=1` command-line flag. This instructs vmagent to send data to remote storage via a single connection. This guarantees that the data will be sent in increasing order of timestamps. See [vmagent troubleshooting section](https://docs.victoriametrics.com/vmagent.html#troubleshooting) for more details.

**Comment by CrashLaker** [comment]
Hi all,
i've just found out about VictoriaMetrics' feature `-remoteWrite.queues=1` when looking for a solution to the `out of order` problem.
i've a system which grabs data from many sources to ingest them into thanos via prometheus `remote_write`. problem is that i'm facing many `out or order` errors due to parallel ingest.
I'm wondering if I could use `vmagent` + `-remoteWrite.queues=1` to buffer all those metrics + reorder them before sending to thanos. is this possible?

regards,
C.

**Comment by valyala** [comment]
> I'm wondering if I could use vmagent + -remoteWrite.queues=1 to buffer all those metrics + reorder them before sending to thanos. is this possible?

This depends on how these samples are [ingested](https://docs.victoriametrics.com/vmagent/#how-to-push-data-to-vmagent) into [vmagent](https://docs.victoriametrics.com/vmagent/). Just try this scheme and report results here.

Closing the feature request as won't implement, since Prometheus, Thanos, Cortex and Mimir gain support for ingesting of out of order samples - see https://github.com/prometheus/prometheus/issues/8535
