### ISSUE TITLE
Evaluation of records and alerts containing a metric in Victoria metrics returns empty results

### ISSUE THREAD

**Issue by brucelee138** [VictoriaMetrics/VictoriaMetrics#1953]
**Describe the bug**
The alerts and record rules containing a metric is not working properly (with me).
Querying the metric itself works without any issue.

curl http://$VM_SELECT:8481/select/0/prometheus/api/v1/query --data-urlencode 'query= kube_node_labels{job="kubernetes-service-endpoints"}' | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "kube_node_labels",
          "instance": "192.168.158.15:8080",
...
}

But after setting it up as a record like below in the VM alert configmap
      - record: test
        expr: kube_node_labels{job="kubernetes-service-endpoints"}

curl http://$VM_SELECT:8481/select/0/prometheus/api/v1/query --data-urlencode 'query=test' | jq
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": []
  }
}

Could you please provide any tips for troubleshooting this further as we could not find any indications from the logs?

**To Reproduce**
The issue had occurred randomly in a setup while testing.

**Expected behavior**
The alerts and record rules to work as the metric is available (and able to query successfully)

**Logs**
No errors in any of the Victoria Metrics components related to this.

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

See how to setup monitoring here:
* [monitoring for single-node VictoriaMetrics](https://docs.victoriametrics.com/#monitoring)
* [montioring for VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)

**Version**
Victoria metrics cluster-1.69.0-1

**Used command-line flags**
Please provide applied command-line flags used for running VictoriaMetrics and its components. 
PFA [Victoria_metrics_args.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7724671/Victoria_metrics_args.txt)

**Comment by hagen1778** [comment]
Hi @brucelee138! Thanks for your request.
To debug if everything is correct you need to check two things:
1. Does vmalert actually gets the data
2. Is it able to forward data to remote write destination

For the p1 please check vmalert UI on page /groups to see if your recording rule has non-zero `Samples` field:
![image](https://user-images.githubusercontent.com/2902918/146318352-10881af4-2179-4cd5-ab73-c93f6903d438.png)
This field shows how many samples was received for the given expression during the **last** evaluation. If it is 0 or there is an error - then for some reason it didn't get results.
You can also check it via metrics exposed on the /metrics page:
```
vmalert_recording_rules_last_evaluation_samples{recording="testForExistingMetric", group="TestGroup", id="17156063009697213675"} 3
vmalert_recording_rules_last_evaluation_samples{recording="testForNonExistingMetric", group="TestGroup", id="8502240443863727911"} 0
```
Also ensure you're not using any extra filtering in your rules, like `extra_filter_labels` param.

For the p2 please verify vmalert can send results successfully to the remote write destination.
On the /metrics page look for metrics prefixed with `vmalert_remotewrite`. They should help you to determine if there any errors or how many samples were sent to remote write destination.

I'd also recommend installing vmalert dashboard https://grafana.com/grafana/dashboards/14950.

Another thing to add is that /query API handler may be tricky, since it is evaluated for the current moment of time. You might want to try /export API or /query_range API to see if there are samples for your recording rules. Also keep in mind, that by default VictoriaMetrics ingested datapoints aren't visible for 30s. This behaviour is controlled via `search.latencyOffset` flag.

**Comment by hagen1778** [comment]
Closed due to lack of activity.
