### ISSUE TITLE
Grafana an error when querying from VM, but the query from prometheus is normal

### ISSUE THREAD

**Issue by k8sre** [VictoriaMetrics/VictoriaMetrics#1999]
**Describe the bug**
All queries from VM will errors.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
t=2021-12-23T02:23:23+0000 lvl=eror msg="Exemplar query failed" logger=tsdb.prometheus query="process_files_open_files{application=\"demo\"}" err="[]v1.ExemplarQueryResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||..."

**Screenshots**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/35365219/147178524-de87ef6f-208c-4f34-b3da-424d3bb56428.png">

**Version**
Grafana: 8.3.3

 /vmselect-prod --version
vmselect-20211220-173504-tags-v1.71.0-cluster-0-g28a0d3faa

/vmstorage-prod --version
vmstorage-20211220-173542-tags-v1.71.0-cluster-0-g28a0d3faa

/vminsert-prod --version
vminsert-20211220-173413-tags-v1.71.0-cluster-0-g28a0d3faa

<img width="424" alt="image" src="https://user-images.githubusercontent.com/35365219/147179187-d98ec0ed-1df5-4281-8cbe-9785180082d8.png">

**Comment by hagen1778** [comment]
Hi @k8sre! Thanks for the request!
The error you see in logs is related to [exemplars](https://grafana.com/docs/grafana/latest/basics/exemplars/) only, not to regular queries. VictoriaMetrics [does not support exemplars yet](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1169) and supposed to return an empty placeholder instead. Apparently, in a new version of Grafana response parsing for exemplars changed a bit and that's why you observe these errors. https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2000 suppose to fix it.

**Comment by valyala** [comment]
VictoriaMetrics must return the proper response stub from `/api/v1/query_exemplars` handler starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed.

**Comment by dafu-wu** [comment]
> 

Does this mean that the storage Exemplar is supported？

**Comment by hagen1778** [comment]
No @dafu-wu, it returns a stub - just an empty response. This response will be correctly parsed by Grafana and will not trigger any errors.
