### ISSUE TITLE
differential snapshots and incremental backups

### ISSUE THREAD

**Issue by ThomasADavis** [VictoriaMetrics/VictoriaMetrics#203]
**Is your feature request related to a problem? Please describe.**

When doing a backup of a large dataset, being able to just backup between two points in time would be nice, instead of creating a backup from a snapshot that dates back to beginning.

**Describe the solution you'd like**

Ability to snapshot between two points in time, one point being NOW, the other point sometime in the past, for example, 1 day, 1 week, 1 month..  it does not have to be super accurate; just enough to reduce the size to the backup.

**Describe alternatives you've considered**

Backing up a TB of data sucks.  Backing up smaller chunks is better.

**Comment by hagen1778** [comment]
Hi @ThomasADavis !
Yes, I think that's a good idea. Would be nice if snapshots endpoint accept time-range which can be used to find all relevant parts in storage and make the hard-links. 

More info about snapshots - https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282

**Comment by ThomasADavis** [comment]
In looking at my current data sizes:
```
/glusterfs/nvme-ec0/dae-vmetric-1/data/big/snapshots
[root@dae-vmetric-1 snapshots]# du -sh
733G	.
[root@dae-vmetric-1 snapshots]# cd ..
[root@dae-vmetric-1 big]# du -sh
797G	.
[root@dae-vmetric-1 big]# ls
2019_04  2019_05  2019_06  2019_07  2019_08  2019_09  2019_10  snapshots
[root@dae-vmetric-1 big]# du -sh *
47G	2019_04
103G	2019_05
97G	2019_06
78G	2019_07
171G	2019_08
195G	2019_09
64G	2019_10
44G	snapshots
[root@dae-vmetric-1 big]# 
```
Can I just backup just the 2019_05 big directory for example, and then restore from it if needed?

Is the data in each month separate from the other months?

I'm also wondering about the small directory..

```
[root@dae-vmetric-1 small]# du -sh *
115M	2019_04
85M	2019_05
5.0M	2019_06
42M	2019_07
470M	2019_08
318M	2019_09
368M	2019_10
319M	snapshots
[root@dae-vmetric-1 small]# 
```

**Comment by valyala** [comment]
> Can I just backup just the 2019_05 big directory for example, and then restore from it if needed?

yes, you can back up each month separately.

> Is the data in each month separate from the other months?

yes. Take into account that VictoriaMetrics supports back-filling, so it can add new data to directories with previous months after such data is ingested into it.

> I'm also wondering about the small directory..

`small` and `big` directories have the same structure - they contain subdirectories (partitions) with per-month data. The only difference is that `small` directory contains recently added data with small sizes, while `big` directory contains older data with bigger sizes. `small` directory can be mounted to faster persistent storage such as SSD in order to reduce query latency when querying recently added data.

> Would be nice if snapshots endpoint accept time-range which can be used to find all relevant parts in storage and make the hard-links.

Though this can work, this would complicate restoring from backup. The easier solution is to use third-party incremental backup tools for backing up VictoriaMetrics snapshots. Snapshots usually have common big files, so incremental backup would save a lot of network bandwidth and time comparing to full backup. Such a tool can make full backups once a month and make incremental backups more frequently - once a day or once a hour. See https://medium.com/@mattlyons0/incremental-backups-with-rsync-9c8e3f14c2c as an example. Don't forget following symlinks when making backups from snapshots (this is usually `-L` flag for such tools as `rsync` and `cp`).

Probably, we should create special-purpose tool for making incremental backups from snapshots. @hagen1778 , could you take a look at this approach?

**Comment by ThomasADavis** [comment]
So thinking about this..

One question - what timing does the rollover from the small to the big is used?  Is it based on time, or size?  Can I assume that if a small directory that was generated in one month, will end up in that month's big directory, or will it end up in the current month's directory, ie, small was generated at 11:00pm last day of month, but rollup didn't occur until 1am the next month ( a 3 hour period); where does that rollup go?  into the current month, or the month that generated the small data?  And is the timestamps based on localtime, or are they normalized to GMT?

Can we assume then that any previous month in the big directory is static then?  Only the current month will be changing?

If so, then my plan is to dump each month separately.  Then, do:

create a snapshot at 12:00 AM, on the 1st day of the month.

Each day, create a new snapshot of that day (possibly at midnight..)

Diff the two snapshots - this should generate a list of files that have changed between the two snapshots.

Yes, the snapshot will grow each day, until it rolls over the next month.  On the 1st day of the next month, create a dump of the previous month.  At some point in the future, purge the dumps that are differential snapshots..

This fulfills the promise we've made to the researchers, that we can easily grow/shrink a version of the db for their work, and good model for our disaster recovery process (easy to get a base in place, then grow it back to normal later..)

**Comment by valyala** [comment]
> what timing does the rollover from the small to the big is used? Is it based on time, or size?

It is based on the available RAM size, which is calculated as `host_RAM_size * <-memory.allowedPercent>`, where `-memory.allowedPercent` is the corresponding command-line flag value. See [the code for `maxRowsPerSmallPart` function](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/partition.go#L25).
This allows the OS keeping recently added data in OS page cache, which reduces load on disk IO.

> Can I assume that if a small directory that was generated in one month, will end up in that month's big directory, or will it end up in the current month's directory, ie, small was generated at 11:00pm last day of month, but rollup didn't occur until 1am the next month ( a 3 hour period); where does that rollup go? into the current month, or the month that generated the small data?

Data from `small` subdirectory goes to the corresponding `big` subdirectory when `small` subdirectory has enough data to merge into `big` subdirectory. Smaller amounts of data remains in `small` subdirectories.

Data is split among per-month directories using timestamps from data points, not the insertion time. This means that the inserted historical data goes to the corresponding directories for historical months, not the current month.

> And is the timestamps based on localtime, or are they normalized to GMT?

All the timestamps are normalized to GMT.

> Can we assume then that any previous month in the big directory is static then? Only the current month will be changing?

This is true unless you backfill historical data for the previous months. Your plan should work if all the ingested data is inserted with the current timestamp. Always make backups from [snapshots](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-work-with-snapshots), not from live data, even for historical months. Otherwise the resulting backup can be in inconsistent state.

**Comment by valyala** [comment]
@ThomasADavis , see [vmbackup](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md) tool for full and incremental backups of VictoriaMetrics data on S3 and GCS. The tool will be included into the next VictoriaMetrics release. Now it can be built from sources according to [these instructions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md#how-to-build-from-sources).

**Comment by valyala** [comment]
The `vmbackup` tool is available in `vmutils-*.tar.gz` archive starting from [v1.29.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed.

The following article explains how `vmbackup` works - https://medium.com/@valyala/speeding-up-backups-for-big-time-series-databases-533c1a927883 .

@ThomasADavis , feel free re-opening it if you have additional questions or concerns.
