### ISSUE TITLE
vmselect returns different timing data for each refresh

### ISSUE THREAD

**Issue by yxxhero** [VictoriaMetrics/VictoriaMetrics#2068]
**Describe the bug**
vmselect returns different timing data for each refresh
3 vmselect: replicationFactor 2
3 vminsert: replicationFactor 2
3 vmstorage 

**To Reproduce**
install https://github.com/VictoriaMetrics/helm-charts  v1.71.0

**Expected behavior**
vmselect returns same timing data for each refresh

**Logs**

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
https://github.com/VictoriaMetrics/helm-charts  v1.71.0

```

**Used command-line flags**
vmselect:
args:
    - --cacheDataPath=/cache
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-0.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster.:8401
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-1.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8401
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-2.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8401
    - --envflag.enable=true
    - --envflag.prefix=VM_
    - --loggerFormat=json
env:
    - name: VM_dedup_minScrapeInterval
      value: 30s
    - name: VM_search_maxQueryLen
      value: "20971520"
    - name: VM_dedup_minScrapeInterval
      value: 1ms
    - name: VM_replicationFactor
      value: "2"

vminsert:
args:
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-0.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8400
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-1.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8400
    - --storageNode=victoria-metrics-victoria-metrics-cluster-vmstorage-2.victoria-metrics-victoria-metrics-cluster-vmstorage.victoria-metrics-cluster:8400
    - --envflag.enable=true
    - --envflag.prefix=VM_
    - --loggerFormat=json
env:
    - name: VM_maxConcurrentInserts
      value: "256"
    - name: VM_insert_maxQueueDuration
      value: 1m
    - name: VM_replicationFactor
      value: "2"

vmstorage:
    - --retentionPeriod=1
    - --storageDataPath=/storage
    - --envflag.enable=true
    - --envflag.prefix=VM_
    - --loggerFormat=json

**Comment by YuriKravetc** [comment]
Hi,
Can you elaborate further on the mentioned issue and ideally provide some screenshots?
Thanks,

**Comment by valyala** [comment]
@yxxhero , the provided configuration for `vmselect` has the following issues:
* The `VM_dedup_minScrapeInterval` environment variable must be set only once. It is set twice - to 30s and to 1ms in the provided config. See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety for details.
* Try removing the `VM_replicationFactor` environment variable at `vmselect`. If `-replicationFactor` at `vmselect` is set to `N`, where `N > 1`, then `vmselect` doesn't wait for response from `N-1` slowest `vmstorage` nodes during request processing, since it assumes that responses from the rest of `vmstorage` nodes contain full data. This may be false if `vminsert` couldn't replicate some data to `N` vmstorage nodes according to the provided `-replicationFactor=N` option. In this case `vmselect` may return response calculated on incomplete data. So it is recommended removing `VM_replicationFactor` env var from `vmselect` configs. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1207 .
* It is also recommended setting `-search.denyPartialResponse` command-line flag at `vmselect` nodes, since by default `vmselect` may return partial responses if some of `vmstorage` nodes are temporarily unavailable. This may lead to different results during each refresh. See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability for details.

**Comment by yxxhero** [comment]
@YuriKravetc  @valyala Thanks very much.

**Comment by yxxhero** [comment]
@valyala The problem of inconsistency of data returned by each refresh is solved by setting -dedup.minScrapeInterval=30s of vmselect, which is consistent with the ScrapeInterval of prometheus. However, vmstorage has missing data.
cmd args:
```bash
vmselect:
    -search.maxQueryLen=20971520
    -dedup.minScrapeInterval=30s
    -search.disableCache
    -search.denyPartialResponse
vminsert:
    -maxConcurrentInserts=256
    -insert.maxQueueDuration=1m
    -replicationFactor=2
vmstorage: no args
```

**Comment by valyala** [comment]
> However, vmstorage has missing data.

Could you provide an example time series of missing data? It would be great to attach screenshots for such a time series and raw samoles from the time series, whuch can be obtained via export API - see [these docs](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format). Note that cluster version of VictoriaMetrics has slightly different urls because of tenant id - see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format)

**Comment by yxxhero** [comment]
@valyala  
screenshots:

access all vmstorage:
![fa60bf7ef921abd2bbc34710c2b3b1de](https://user-images.githubusercontent.com/11087727/150053416-544ae7d3-0ffe-4995-86e2-336ce123871d.png)

only access storage-0:
![storage-0](https://user-images.githubusercontent.com/11087727/150054098-2a5d505d-6499-4141-a358-3e550c38eb85.png)

only access storage-1:
![storgae-1](https://user-images.githubusercontent.com/11087727/150054142-e58bee64-368b-4b62-a10a-5f7bbd4c88f6.png)

only access storage-2:
![storage-2](https://user-images.githubusercontent.com/11087727/150054196-6d48b843-c4ce-45b1-a62b-a1a2970ce628.png)

access prometheus[prome access localdata, remote write to vm]:
![p](https://user-images.githubusercontent.com/11087727/150054356-7fa87484-f4fe-4afb-bbe4-3eb0ac87aa7a.png)

**Comment by yxxhero** [comment]
@valyala Thanks very much.

**Comment by yxxhero** [comment]
@valyala @YuriKravetc ping

**Comment by valyala** [comment]
@yxxhero , it looks like you are querying each `vmstorage` node separately. This is unexpected. All the `vmselect` nodes must be configured with the same list `vmstorage` nodes passed via `-storageNode` command-line flag. When `vmselect` receives incoming query, it fetches the needed data from all the `vmstorage` nodes passed to `-storageNode` command-line flag in parallel, then it merges the received data and returns the result. While it is possible to run `vmselect` nodes with distinct list of `vmstorage` nodes in [some cases](https://docs.victoriametrics.com/guides/guide-vmcluster-multiple-retention-setup.html), this isn't recommended in general case, since in this case every `vmselect` will return only a part of data stored in the cluster.

**Comment by valyala** [comment]
Closing the issue as answered.
