### ISSUE TITLE
[Question] How to delete time series in cluster version

### ISSUE THREAD

**Issue by agrimal** [VictoriaMetrics/VictoriaMetrics#207]
Hello,

I'm trying to find a way to delete time series for specific instances in cluster version. The documentation in unclear for me. What URL do I have to query ?
I suppose i have to query the insert daemon, I tried the following :
- `http://<victoriametrics-addr>:8481/api/v1/admin/tsdb/delete_series?match[]=<timeseries_selector_for_delete>`
- `http://<victoriametrics-addr>:8481/select/1/prometheus/api/v1/admin/tsdb/delete_series?match[]=<timeseries_selector_for_delete>`
Without success.

Another thing, i don't find the `-deleteAuthKey` option on vminsert, vmstorage or vmselect daemons help. Am i missing something ?

**Comment by valyala** [comment]
The correct url is: `http://<victoriametrics-addr>:8481/delete/<tenantID>/prometheus/api/v1/admin/tsdb/delete_series?match[]=<timeseries_selector_for_delete>`. Added it to [README.md for cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md) in the commit bf6fe234b213c7c059e40c71fc18c1d197a12e3b .

Note that the `delete_series` handler should be used only in exceptional cases such as deletion of accidentally ingested incorrect time series. It shouldn't be used on a regular basis, since it carries non-zero overhead.

**Comment by agrimal** [comment]
Ok thanks, delete done with success.

What about the `-deleteAuthKey` option in cluster version ? Is it implemented ?
Because it is not in the output of `vmselect --help`.

**Comment by valyala** [comment]
> What about the -deleteAuthKey option in cluster version ? Is it implemented ?

Sorry, I missed this question in the first message. Cluster version doesn't support `-deleteAuthKey`, since it is expected that each tenant should have its own auth key, which should be verified by authorization, accounting and resource limiting proxy sitting in front of VictoriaMetrics cluster. Such a proxy is missing in VictoriaMetrics source code, since it is highly specific to particular use case and customer.

We are happy to help implementing this proxy for particular use case. Contact us at info@victoriametrics.com for more details.

**Comment by agrimal** [comment]
Ok, thanks for the answers
