### ISSUE TITLE
Expose Metrics description

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#210]
**Is your feature request related to a problem? Please describe.**
Single and cluster version expose own metrics. Good to have documentation where user can find description for these metrics

**Comment by valyala** [comment]
FYI, part of these metrics are described in the [official VictoriaMetrics dashboards for Grafana](https://grafana.com/orgs/victoriametrics).

**Comment by pavdmyt** [comment]
It would be very helpful to have some docs with the list of exposed metrics and short description.

**Comment by valyala** [comment]
A technical workaround is to grep VictoriaMetrics source code for particular metric name and then investigate how it is used in the code.

**Comment by valyala** [comment]
FYI, VictoriaMetrics components support an ability to expose `TYPE` and `HELP` comments per each exported metric at `/metrics` page starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). This functionality is disabled by default. Pass `-metrics.exposeMetadata` command-line flag to the VictoriaMetrics component in order to enable this functionality. This may be useful when Google Cloud Prometheus is used for scraping metrics from VictoriaMetrics components. See [this issue](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#missing-metric-type) for details.

**Comment by valyala** [comment]
The most important metrics are used and documented in [the official VictoriaMetrics dashboards for Grafana](https://grafana.com/orgs/victoriametrics) and in [the official alreting rules for VictoriaMetrics components](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker#alerts).

We aren't going to document all the metrics exposed by VictoriaMetrics components, since these metrics may be added, adjusted and removed with every new release. If you need obtaining an information about some of the exposed metric, then search for the metric name in the source code of VictoriaMetrics repository.

Closing this feature request as won't implement.

**Comment by tiny-pangolin** [comment]
now that Victoriametrics supports storing metadata from the TYPE and HELP fields it would be useful to document what these metrics mean on the /metrics endpoint. This would enable humans to see this information tools like explore metrics in Grafana and so AI using our skills and mcp server can comprehend what these metrics mean.

**Comment by makasim** [comment]
The documentation part could be tracked in the issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6997#issuecomment-3702418693
