### ISSUE TITLE
Get wrong result by func Increase

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#2108]
I recently encountered a strange problem that the calculation result of func increase  is wrong.

I have a metric `simple:rpc_client_started_total` , raw data :
![image](https://user-images.githubusercontent.com/32037815/151284104-30f2993c-986e-4ab4-b2d5-b897c1d0e5e3.png)

After `increase` :
![image](https://user-images.githubusercontent.com/32037815/151284018-83ce845d-b2c4-4ba7-9c30-61e089538cc9.png)

There are 15 minutes of calculation results that are completely wrong.

vmcluster version: 1.70.0

**Comment by jiangxinlingdu** [comment]
you can see vmstorage original data ，maybe this metrics counter drop，I've had this problem in rabbitmq metrics is counter drop https://github.com/rabbitmq/rabbitmq-server/discussions/2781，so I you to make sure that you metrics

**Comment by Buddruggy** [comment]
> 

the first pic is raw data, yes, the value of this metric dropped, but not to zero, Will this lead to data calculation errors?

**Comment by Buddruggy** [comment]
> you can see vmstorage original data ，maybe this metrics counter drop，I've had this problem in rabbitmq metrics is counter drop [https://github.com/rabbitmq/rabbitmq-server/discussions/2781，so](https://github.com/rabbitmq/rabbitmq-server/discussions/2781%EF%BC%8Cso) I you to make sure that you metrics

the first pic is raw data, yes, the value of this metric dropped, but not to zero, Will this lead to data calculation errors?

**Comment by valyala** [comment]
@Buddruggy , the [increase()](https://docs.victoriametrics.com/MetricsQL.html#increase) function expects that the inner time series cannot decrease their values in time. E.g. it works correctly only with [counter time series](https://prometheus.io/docs/concepts/metric_types/#counter). If a time series drops in time, then `increase()` may return unexpected results. It is unclear whether this is your case because `increase()` results are masked with the outer `sum()`. It would be great if you could remove the outer `sum()` from both raw data and `increase()` data and to reduce the number of time series on the graph by adding more specific [label filters](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors) to `simple:rpc_client_started_total`, while making sure that the issue is still present on the remaining time series.

Note also that VictoriaMetrics calculates `increase()` slightly differently comparing to Prometheus. See [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html#metricsql) for more details.

**Comment by Buddruggy** [comment]
@valyala I am sorry for the raw data no longer exists,  and indeed,  the value of the metric `simple:rpc_client_started_total` should be always bigger than before. so i fixed this bad case before writing the data to vminsert. thank you very much for your explanation.
