### ISSUE TITLE
The data seen from grafana after using VictoriaMetrics is skewed

### ISSUE THREAD

**Issue by czhfe** [VictoriaMetrics/VictoriaMetrics#2152]
The data seen from grafana after using VictoriaMetrics is skewed.

> **Direct query from prometheus**

![image](https://user-images.githubusercontent.com/19341806/152768985-1f3da7e8-5b7f-4210-bc15-971d98d13872.png)

> **Search from VictoriaMetrics**

![image](https://user-images.githubusercontent.com/19341806/152769023-37d5a6d3-41a6-4996-be66-8873611a89b9.png)

**Comment by hagen1778** [comment]
Hi @czhfe! Could you please show the exact query you're using for plotting the graph from the screenshot?
It is likely caused by difference between `rate` implementation in VictoriaMetrics and Prometheus. 
See also https://docs.victoriametrics.com/MetricsQL.html
and https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e

**Comment by valyala** [comment]
Closing the issue because of inactivity.
