### ISSUE TITLE
Slow /prometheus/api/v1/labels endpoint

### ISSUE THREAD

**Issue by rbizos** [VictoriaMetrics/VictoriaMetrics#2200]
**Is your feature request related to a problem? Please describe.**
In grafana 8, the metrics browser uses /prometheus/api/v1/labels endpoint to load labels names. This is pretty slow in VictoriaMetrics as it needs to scan all label/values for the time-range in the index. In our case, we have a cluster with 100M  active time-series, this takes more than 30s (which we defined as timeout). This happens each time a user opens the metrics browser so it can happen often. 

**Describe the solution you'd like**
It would be great to store those labels for fast queries while ingesting new metrics. As labels keys are often quite limited compared with label values, it would be pretty cheap to store (few kB daily).
It could be done as a mergeset with only the labels names in stead of label + values that are in the indexDB. This would speed up considerably the api call.

**Describe alternatives you've considered**
We considered adding a caching proxy

**Additional context**
I  would be happy to provide any help on the development of the feature

**Comment by denisgolius** [comment]
@valyala please could you take a look?

**Comment by valyala** [comment]
The `/api/v1/labels` should be quite fast in general, since it uses binary search over `{label="value"} -> internal_metric_id` entries at `indexdb` for looking up unique label names. Binary search should work fast even for billions of entries if the number of unique `label` names isn't big (this is usually the case in most practical workloads, since label names are generated by humans (e.g. engineers :)) ).

It has been appeared that there was a bug in `/api/v1/labels` code, which fall back to full scan instead of binary search when it encountered `artificial` entries. This could slow down the `/api/v1/labels` significantly when the database contains big number of registered time series. The bug has been fixed in the commit b71be42d9065417ed2b49807e93f80b970ca8cbe .

@rbizos , could you build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether this fixes the issue with slow `/api/v1/labels` endpoint? If you use cluster version of VictoriaMetrics, then you need to build `vmstorage` component from ee066aa0d5bf6d7bdefc3ae2c0cfdcdfbdcb8c2f according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by rbizos** [comment]
Hello @valyala,

Thanks a lot once again for your quick answer. From my tests in local it  seems it seems similar with previous version, in my test it takes around 2s to serve /api/v1/labels for both. May I ask what **artificial** entries are in the index ?

**What I used to test was:**

- one of each vm components in local

- avalanche with this command

`docker run quay.io/freshtracks.io/avalanche --remote-url=http://local-ip:8480/insert/0/prometheus/api/v1/write --metric-count=50000 --series-count=10 --label-count=25`

**Comment by valyala** [comment]
@rbizos , thanks for the update! The commit didn't skip properly composite tag entries. The commit 2ebc3d21c3012fd3cb489ff34432a8105ddb3130 should address this issue in `vmstorage`. Could you build `vmstorage` from this commit and check `/api/v1/labels` performance again?

> May I ask what artificial entries are in the index ?

The index contains `{label="value"} -> metricID` entries. There are two types of `artificial` entries in the index:
* Entries with `0xff` label. They are named `graphite reverse tag` entries. They contain reverse metric name at `value` for speeding up the search for Graphite metrics with a wildcard in the middle of metric name such as `foo.*.bar.baz`. E.g. when performing the query `{__name__=~"foo.[^.]*.bar.baz"}`.
* Entries with labels starting from `0xfe` char. Such entries contain e.g. composite index for speeding up search for filters containing a metric name with at least a single filter on label. For example, this index is used when searching for `metric{label="foo"}`, but it isn't used for searching for `{label="foo"}`, e.g. when the metric name is empty.

**Comment by rbizos** [comment]
Thanks your for the explanation. 
It went from 2-3s to 2-3 ms with the same input, that's pretty fast in comparison. I can't wait to try it out on our production cluster. Thanks a lot for your fix, that was very fast !

**Comment by valyala** [comment]
Commits mentioned above have been included in [VictoriaMetrics v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This should speed up requests to `/api/v1/labels` when the database contains big number of time series. Closing the issue as fixed.
