### ISSUE TITLE
evaluation_interval not found in type promscrape.GlobalConfig

### ISSUE THREAD

**Issue by akme** [VictoriaMetrics/VictoriaMetrics#2218]
After upgrading to v1.73.0 vmagent started to fail on startup with the provided error:
```
2022-02-18T12:58:27.037Z        fatal   VictoriaMetrics/lib/promscrape/scraper.go:105   cannot read "/etc/prometheus/prometheus.yml": cannot parse Prometheus config from "/etc/prometheus/prometheus.yml": cannot unmarshal data: yaml: unmarshal errors:
  line 3: field evaluation_interval not found in type promscrape.GlobalConfig; pass -promscrape.config.strictParse=false command-line flag for ignoring unknown fields in yaml config
```

Config contains:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
```

Previous versions work well with this config.

**Comment by Wolfeg** [comment]
check this section
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#unsupported-prometheus-config-sections

**Comment by hagen1778** [comment]
Hi @akme! In v1.73.0 config processing was turned to the strict mode by default. Strict mode verifies that config file does not contain unsupported fields, and `evaluation_interval` is one of such fields. Rules evaluation (it is what `evaluation_interval` param controls) should be done via [vmalert](https://docs.victoriametrics.com/vmalert.html). On VictoriaMetrics single or vmagent this config line has no effect.

**Comment by akme** [comment]
Thank you guys for the explanation!

**Comment by hagen1778** [comment]
Hi @pollynesterovich! As was mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2218#issuecomment-1046511196, `evaluation_interval` never had an effect for vmsingle/vmagent scrape configurations. The field  `evaluation_interval` in Prometheus config defines how frequently recording/alerting rules should be evaluated. Since vmagent/vmsingle do not support alerting/recording rules - this field does not make sense.

For rules evaluation you'll need to use [vmalert](https://docs.victoriametrics.com/vmalert.html) - it does support this configuration parameter. Let me know if you have any questions.

**Comment by pollynesterovich** [comment]
@[hagen1778](https://github.com/hagen1778) thanks.
