### ISSUE TITLE
why range_query only support 40 days ?

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2240]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/acbea6c1ee162227d4ef8d11cf39b1abe6e2c7cd/lib/storage/index_db.go#L2413

the max date of range_query will be 40 days.
and I don't find any code for split long term in vm-select code.

so, I think the `const maxDaysForPerDaySearch = 40` should as a cmd line flag.
then user will decide how long can be query.

thanks.

**Comment by valyala** [comment]
VictoriaMetrics maintains two inverted indexes for the search of time series by label filters:
* Global index. It contains entries for all the time series registered during the configured [-retentionPeriod](https://docs.victoriametrics.com/#retention).
* Per-day index. It is split into per-day partitions, where each partition contains entries only for [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) at that particular day. This index allows speeding up searches for time series over small time ranges (up to 40 days) under [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate), when big number of old time series are substituted with new time series every day.

If the selected time range exceeds 40 days, then VictoriaMetrics falls back to global index search. See the corresponding code:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/acbea6c1ee162227d4ef8d11cf39b1abe6e2c7cd/lib/storage/index_db.go#L2217-L2235

The 40 days limit has been chosen because is is usually more effective to search in global index than to perform more than 40 independent searches in per-day index for every day from the selected time range.

**Comment by ahfuzhang** [comment]
thanks. :-)
yyds
