### ISSUE TITLE
How to limit vmselect memory usage

### ISSUE THREAD

**Issue by mmkkoo** [VictoriaMetrics/VictoriaMetrics#2246]
At present, our vmselect memory usage is very high，my system os memory is 32GB，when i set -memory.allowedBytes=10GB，vmselect application memory is high！
<img width="719" alt="image" src="https://user-images.githubusercontent.com/42405491/155477026-18fc729d-eab2-49fd-a4e2-e374d01b9843.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/42405491/155477089-a30f7782-e70f-4c5c-9455-c881c050e801.png">

**Comment by valyala** [comment]
The `-memory.allowedPercent` and `-memory.allowedBytes` command-line flags limit the total size of various in-memory caches. The total memory usage can exceed the specified limits, since `vmselect` uses additional memory for processing the currently executed queries. This memory can be limited with the following command-line flags:
* `-search.maxConcurrentRequests`
* `-search.maxPointsPerTimeseries`
* `-search.maxSamplesPerSeries`

Default values for these flags work OK in most cases, so there is no need to tune them. Too high values for these flags may result in increased memory usage for `vmselect`.

See descriptions for these command-line flags [here](https://docs.victoriametrics.com/#list-of-command-line-flags).

**Comment by mmkkoo** [comment]
Thank you for your reply，i will modify the relevant parameters
