### ISSUE TITLE
Confusing duplication of the READMEs

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#2282]
While submitting [my first doc PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2266), I was confused as to what file to edit. There are (at least) **three** READMEs that look essentially identical:

1. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/README.md
2. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md - I see a "make docs sync" commit there. Is that done after each change to `docs/README.md`? Why isn't `/README.md` a symlink to `docs/README.md`?
3. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/Single-server-VictoriaMetrics.md - again that "make docs sync" commit.

Why do these separate but (nearly) identical docs exist? Can all but one be a symlink? If not, can we have a single source of truth, with warnings at the top of the other files that they're automatically generated? That would help contributors figure out what file to edit, and we'd have a clear history. Right now each of these files has a different set of contributors.

![image](https://user-images.githubusercontent.com/33569/156863657-79bd3950-38db-4b0f-ab0d-6ee1f566a494.png)
![image](https://user-images.githubusercontent.com/33569/156863664-298a80ec-439e-481d-83b4-aee8e7effcde.png)
![image](https://user-images.githubusercontent.com/33569/156863671-dda3ab52-9508-44ad-a7bd-836aea9a6a86.png)

**Comment by hagen1778** [comment]
Hi @dandv! The docs are confusing indeed.
The reason for such a structure is that we as maintainers want docs to satisfy the following requirements:
* all docs should be present in the same repo
* all docs should be always up-to-date

If you check, [all packages](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app) has their own `README.md`  file inside. And when we change anything docs related - we do it there.
Then, before release, we do `make docs-sync` command to update the `docs` folder. That's why the number of contributors is different.

The `docs` folder is used by https://pages.github.com/ to generate the https://docs.victoriametrics.com. The way how pages work implies all documentation files to exist in one folder. So this is why we do this `make docs-copy` thing.

The [Single-server-VictoriaMetrics.md](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/Single-server-VictoriaMetrics.md) exists to make it a part of navigation bar here: 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/2902918/156991723-22f8d02f-c0d8-4224-95f9-fc8a4fb28149.png">


I agree, that process is not clear for contributors. If you have ideas how to improve the process - let me know.

**Comment by dandv** [comment]
Thanks for the explanation. Seems like /docs` could be the single source of truth for the overall Victoria Metrics documentation, and the packages have separate READMEs.

What would happen if [`/README.md`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md) were a symlink to [`/docs/README.md`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/README.md)?

**Comment by hagen1778** [comment]
> What would happen if [/README.md](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md) were a symlink to [/docs/README.md](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/README.md)?

I wasn't aware symlinks work for gihub. If yes, this could simplify things. Have you tried it before?

**Comment by hagen1778** [comment]
Closing the issue as stale

**Comment by dandv** [comment]
Unstale out of curiosity.

I see the same duplicate READMEs but the [last README PR I submitted](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5523/files) was applied to all three. How was this issue resolved?

**Comment by hagen1778** [comment]
It was followed-up by the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/35dd6e5e8e180e8153c2d1b7c5e3a3918b77bda9,

**Comment by dandv** [comment]
So there's a docs-sync tool it seems.

**Comment by hagen1778** [comment]
Not a tool, a Makefile command - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e374c227fe079a6f30fc98e80fe32e04d3c2c3b/Makefile#L527-L536
