### ISSUE TITLE
Federation export Prometheus data in second

### ISSUE THREAD

**Issue by yangtaoran** [VictoriaMetrics/VictoriaMetrics#2327]
I use federation command `http://<victoriametrics-addr>:8428/federate?match[]=<timeseries_selector_for_federation>` to export Prometheus metrics data, I find the time series's timestamp unit is millisecond. But I hope it is second, so how can I configure some what param？

**Comment by hagen1778** [comment]
Hi @yangtaoran!
The federation API is supposed to return timestamps in **milliseconds**. You can see the example from Prometheus API - http://demo.robustperception.io:9090/federate?match[]=up.
Btw, using **seconds** instead of **milliseconds** may result into data collision and information loss, since VM stores data with milliseconds precision.

**Comment by yangtaoran** [comment]
Thanks @hagen1778 , I solved the question in another way.
