### ISSUE TITLE
Make Deduplication Unnecessary For vmselect In HA Mode

### ISSUE THREAD

**Issue by emypar** [VictoriaMetrics/VictoriaMetrics#2351]
When running VictoriaMetrics in HA cluster mode there is a penalty (1), CPU and latency wise, associated with the deduplication of multiple time series received from the `vmstorage` replicas. While this can be mitigated somewhat by the use of `-replicationFactor=N`, the latter comes with the risk of using partial data if the the first N responses come from `vmstorage`'s that were recently started, for instance.

This feature request suggests a new (2) operating mode to make deduplication unnecessary as follows:
* each `vmstorage` keeps track of the timestamp when it became fully operational and it advertise it to `vmselect` upon connection
* when `vmselect` has to retrieve data for a `from` - `to` window, it will send the request to one of the `vmstorage` units that has been `operational since` >= `from`, selected in a circular fashion
* if no `vmselect` matching the above can be found then fallback to the current query all or up to replication factor w/ the deduplication of the results

(1) We are using VictoriaMetrics for large Kubernetes clusters w/ > 3,500 nodes, and > 60,000 pods
(2) We suggest this **in addition to** the current operating modes to avoid changes in behavior for customers that are not interested in this feature

**Comment by valyala** [comment]
`vminsert` shards incoming time series among available `vmstorage` nodes via [consistent hash](https://en.wikipedia.org/wiki/Consistent_hashing) over time series name plus its labels:

```
vmstorage_node = consistent_hash(vmstorage_nodes, metric_name{labels})
```

This means equally distributed time series among available `vmstorage` nodes. This also means that every query must fetch data from all the available `vmstorage` nodes, since time series needed for the query can be stored on all the `vmstorage` nodes.

When `-replicationFactor=N` is set to value greater than 1 at `vminsert` nodes (e.g. when replication is enabled), then `vminsert` writes `N-1` copies of incoming samples to `N-1` distinct `vmstorage` nodes additionally to the node selected with consistent hashing. This uniformly distributes data replicas across all the available `vmstorage` nodes.

This makes impossible the proposed optimization, since:
* Every query may need data, which is stored on all the `vmstorage` nodes in the same way as when the replication is disabled.
* It is impossible to determine a set of `vmstorage` nodes, which contain the needed data per each incoming query.
 
There is a possibility to skip results from up to `N-1` `vmstorage` nodes if all the data used in the query is replicated `N` times among distinct `vmstorage` nodes. This guarantees that at least a single copy remains available when skipping results from up to `N-1` `vmstorage` nodes. This optimization can be enabled by passing `-replicationFactor=N` to `vmselect` nodes. Note that this optimization can result in incomplete results if the requested data has less than `N` copies among `vmstorage` nodes.

**Comment by jiekun** [comment]
Closed as answered. Feel free to reopen it if you have more questions on this topic.
