### ISSUE TITLE
vminsert: ability to specify tls ciphers

### ISSUE THREAD

**Issue by mariastroe** [VictoriaMetrics/VictoriaMetrics#2404]
**Is your feature request related to a problem? Please describe.**
Right now, on vminsert you can only enable tls and specify the paths to certificate and key files.

**Describe the solution you'd like**
I would like an additional flag to let me specify the tls cipher suites that I want, instead of using the default ones.

**Comment by dmitryk-dk** [comment]
Hi @mariastroe ! Thank you for your request. Can you please define where you need tls cipher suite implemetation. 
When you create client to vminsert or between vminsert and `vmstorage`?

**Comment by mariastroe** [comment]
After a quick look, I saw that all VictoriaMetrics cluster components support tls.
This being said, it would be nice if all components that support tls (vmauth, vminsert, vmstorage, vmselect) would have also the option to specify the desired ciphersuite.

**Comment by valyala** [comment]
Note that `-tls` command-line flag enables TLS for incoming HTTP requests at TCP address specified via `-httpListenAddr` command-line flag. The `-tls` command-line flag doesn't enable TLS for communication between cluster components of VictoriaMetrics - `vminsert`, `vmselect` and `vmstorage`, since they communicate with custom non-http protocol over plain TCP. A separate command-line flag - `-cluster.tls` - must be specified in order to enable TLS for communications between cluster components. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection) for details.

The next release of all the VictoriaMetrics components will support `-tlsCipherSuites` command-line flag. This flag accepts comma-separated list of allowed TLS cipher suites for incoming HTTPS requests at `-httpListenAddr`. See [the list of supported TLS cipher suites](https://pkg.go.dev/crypto/tls#pkg-constants).

Additionally, the next release of vmstorage will support `-cluster.tlsCipherSuites` command-line flag, which can be used for configuring the allowed TLS cipher suites for TLS communications between cluster components if `-cluster.tls` command-line flag is set. See more details [in these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection).

In the mean time the `-tlsCipherSuites` command-line flag can be tested by building VictoriaMetrics components from source code as explained [here](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment]
The `-tlsCipherSuites` and `-cluster.tlsCipherSuites` command-line flags are available in VictoriaMetrics components starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
