### ISSUE TITLE
Unexpected behavior for absent_over_time in v1.75.0 cluster

### ISSUE THREAD

**Issue by mrsdpz** [VictoriaMetrics/VictoriaMetrics#2415]
**Describe the bug**

absent_over_time  query cant get  result

**To Reproduce**
for example,I have two computer
computer-1
computer-2

 shutdown  computer-1
then run
absent_over_time(sum(increase(node_time_seconds[1m])) by (instance))

or run

absent_over_time(sum(increase(node_time_seconds{instance=~'computer-1|computer-2'}[1m])) by (instance))

The query result is empty

but run

absent_over_time(sum(increase(node_time_seconds{instance=~'computer-1'}[1m])) by (instance))

It's OK!

**Expected behavior**
When I roll back to v1.72.0-cluster,everything is ok

I find the issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130

Maybe it was introduced this time

**Version**
cluster v1.75.0
```

**Comment by mrsdpz** [comment]
@YuriKravetc When is it expected to be repaired?

**Comment by andywu1998** [comment]
because there are too many days nobody replies me, so I copy text from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130: 


hi, I don't think this function below matches the Prometheus definition of absent_over_time
```
// aggregateAbsentOverTime collapses tss to a single time series with 1 and nan values.
//
// Values for returned series are set to nan if at least a single tss series contains nan at that point.
// This means that tss contains a series with non-empty results at that point.
// This follows Prometheus logic - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130
func aggregateAbsentOverTime(ec *EvalConfig, expr metricsql.Expr, tss []*timeseries) []*timeseries {
	rvs := getAbsentTimeseries(ec, expr)
	if len(tss) == 0 {
		return rvs
	}
	for i := range tss[0].Values {
		for _, ts := range tss {
			if math.IsNaN(ts.Values[i]) {
				rvs[0].Values[i] = nan
				break
			}
		}
	}
	return rvs
}
```
the function above means that tss contains a series with non-empty results at that point. but we can see the definition of absent_over_time on https://prometheus.io/docs/prometheus/latest/querying/functions/ .

it says that

absent_over_time(v range-vector) returns an empty vector if the range vector passed to it has any elements and a 1-element vector with the value 1 if the range vector passed to it has no elements.

it means that: return 1 when all the time series at that point is Nan, return 1 if any time series has elements

But in the code above, absent_over_time will return nan when just only one time series has a nan value.

So I think the correct code is below:
change `if math.IsNaN(ts.Values[i]) { ` to ` if !math.IsNaN(ts.Values[i]) { `
```
func aggregateAbsentOverTime(ec *EvalConfig, expr metricsql.Expr, tss []*timeseries) []*timeseries {
	rvs := getAbsentTimeseries(ec, expr)
	if len(tss) == 0 {
		return rvs
	}
	for i := range tss[0].Values {
		for _, ts := range tss {
			if !math.IsNaN(ts.Values[i]) {
				rvs[0].Values[i] = nan
				break
			}
		}
	}
	return rvs
}
```

**Comment by Amper** [comment]
@hagen1778 do you mind if I reclassify and close this issue as well as https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5201?
