### ISSUE TITLE
"duplicate output timeseries" error when counting more than one metric

### ISSUE THREAD

**Issue by tredondo** [VictoriaMetrics/VictoriaMetrics#2459]
**Describe the bug**
I have two metrics for financial data, `bid` and `ask`, with a `symbol` label. I want to count how many values are in each metric over some duration, e.g. how many bids and asks for AAPL.

**To Reproduce**
`count_over_time({__name__=~"(bid|ask)", symbol="AAPL" })` produces
> error when executing query=[...] duplicate output timeseries: {symbol="AAPL"}

Note that neither `bid` nor `ask` appears in that error.

**Expected behavior**
I expect counts for each of the two series, because the following queries work as expected:
`count_over_time({__name__=~"(bid)", symbol=~"AAPL" })` (returns an array of one object)
`count_over_time({__name__=~"(bid)", symbol=~"AAPL|GOOG" })` (returns an array of two objects)
`count_over_time({__name__=~"(ask)", symbol=~"AAPL|GOOG" })` (returns an array of two objects)

But when I set `{__name__=~"(bid|ask)"`, I get the error above.

**Logs**
Same error as above.

**Version**
victoria-metrics-20220318-175816-tags-v1.75.0-0-g87d356348

**Comment by hagen1778** [comment]
Hi @tredondo!
This is expected behaviour. `count_over_time` is a [transform](https://docs.victoriametrics.com/MetricsQL.html#transform-functions) function and it drops metric `name`. Because of this, the resulting metrics set collides - its labels aren't unique anymore.
To fix the issue you need either explicitly specify to not drop metric names `count_over_time({__name__=~"(bid|ask)", symbol="AAPL" }) keep_metric_names`.

**Comment by tredondo** [comment]
That worked, thanks!
