### ISSUE TITLE
vmctl : vmctl to import the data from Prometheus to VM, but the import is stuck at 0%

### ISSUE THREAD

**Issue by qiu-peng20** [VictoriaMetrics/VictoriaMetrics#2469]
Hi. I am using latest version vmctl to import the data from Prometheus to VM, but the import is stuck at 0%
root@vida-849f8979b4-qglhq:/# ./vmctl-prod prometheus --prom-snapshot=/data/snapshots/20220411T071749Z-4d65822107fcfd52 --vm-addr=http://10.98.90.213:8480
Prometheus import mode
Prometheus snapshot stats:
  blocks found: 1;
  blocks skipped by time filter: 0;
  min time: 1649548800000 (2022-04-10T00:00:00Z);
  max time: 1649613600000 (2022-04-10T18:00:00Z);
  samples: 3290846971;
  series: 933059.
Found 1 blocks to import. Continue? [Y/n] y
0 / 1 [________________________________________________________________________] 0.00% ? p/s

What could be the reasons? And how to debug this?

Thanks in advance/(ㄒoㄒ)/~~

**Comment by qiu-peng20** [comment]
And there's no way out
Found 1 blocks to import. Continue? [Y/n] y
0 / 1 [________________________________________________________________________] 0.00% ? p/s
0 / 1 [________________________________________________________________________] 0.00% ? p/s-
 Execution cancelled
0 / 1 [________________________________________________________________________] 0.00% ? p/s
0 / 1 [________________________________________________________________________] 0.00% ? p/s
0 / 1 [________________________________________________________________________] 0.00% ? p/s

**Comment by hagen1778** [comment]
Hi @qiu-peng20! Thanks for request!
Yeah, seems like vmctl is missing tools for debugging. Maybe additional progress bar or interval heartbeats could help here. I'll think what can be done here.

Alternatively, you can try to check if vmctl generates any egress load. Try to check the network on the host where you run vmctl, or check [VM metrics](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#monitoring) to see if it receives something.

**Comment by qiu-peng20** [comment]
root@vida-5f5859fbd8-vgkph:/# ./vmctl-prod prometheus --prom-snapshot=/prometheus/snapshots/20220426T025904Z-268447a4189deb99 --vm-addr=http://10.37.205.27:8480 --prom-filter-time-end=2021-11-01T00:00:00Z --prom-concurrency=3
Prometheus import mode
Prometheus snapshot stats:
  blocks found: 40;
  blocks skipped by time filter: 39;
  min time: 1635292800000 (2021-10-27T08:00:00+08:00);
  max time: 1635876000000 (2021-11-03T02:00:00+08:00);
  samples: 36729829788;
  series: 3350375.
* Stats numbers are based on blocks meta info and don't account for applied filters.
Found 1 blocks to import. Continue? [Y/n] y
0 / 1 [________________________________________________________________________] 0.00% ? p/s

**Comment by hagen1778** [comment]
Thanks for response @qiu-peng20! Which version of vmctl do you use? I see there is a [pending PR for vmctl](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2486) which suppose to display some additional info about importing progress. Is it an option to [try to build vmctl ](https://docs.victoriametrics.com/vmctl.html#how-to-build)from that branch and try again?

**Comment by qiu-peng20** [comment]
Excuse me, why does the transmission efficiency gradually decrease over time?
start：
![image](https://user-images.githubusercontent.com/55682965/167362235-7adfd697-2a10-46c2-878a-031398151180.png)

After a while：
![image](https://user-images.githubusercontent.com/55682965/167362291-27a77a8e-a935-4da8-9f2b-a651c729f930.png)

**Comment by hagen1778** [comment]
> Excuse me, why does the transmission efficiency gradually decrease over time?

There could be multiple answers:
1. vmctl importer has buffers to accumulate datapoints before sending. But the counter of accepted samples is increased right after they were received. Accepting samples is fast operation, sending a batch is much slower. Hence, at the very beginning whule buffers are empty the rate of accepted samples changes very fast. But when time comes to flush a batch - the importer blocks until batch transmission is finished. This may have impact on the speed you're seeing in the logs.
2. Data transferring might have some fluctuations up & down in processing speed. It is better to see the average speed, not the current one.
3. Reading data from Prometheus snapshot might be uneven in terms of speed, depending on size of blocks and metrics they contain.
4. Remote storage might be faster at the beginning while filling its buffers. And become slower on flushing them, or due to background merges.


If you configure [monitoring](https://docs.victoriametrics.com/#monitoring) for your VictoriaMetrics instance, do you also see the datapoints ingestion degradation on the dashboard?

**Comment by qiu-peng20** [comment]
Thans!!!，If vmctl repeatedly imports data, does vm have aggregate operations 😄

**Comment by hagen1778** [comment]
If you afraid of data duplication or overlapping because of multiple identical import process, then it is worth to configure data [deduplication](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication) on the VictoriaMetrics side.

Or I understood the question wrong?

**Comment by Vladyslav-Miletskyi** [comment]
Maybe
>For cluster version it is additionally required to specify the --vm-account-id flag. See more details for cluster version here.

**Comment by hagen1778** [comment]
Closing due to lack of inactivity
