### ISSUE TITLE
VicotriaMetrics OOM killed by system

### ISSUE THREAD

**Issue by Planck0591** [VictoriaMetrics/VictoriaMetrics#2476]
**Describe the bug**
We have used victoriametrics cluster version 1.73.1 for a month.
Most of time it run fast and stable,we love it.
But we found it sometimes still be killed by system oom killer.
This time we used all default config, and I checked vmstorage-prod and vminsert-prod logs, I did not found some warn or error log useful.
So I uploaded grafana dashboard,but we deployed vmagent in vm cluster together,so these dashboards miss some part.
Could someone give me any advice?
![image](https://user-images.githubusercontent.com/79493220/163700088-d263d8ad-0241-4d15-9002-254fa1d7bd66.png)
![image](https://user-images.githubusercontent.com/79493220/163700114-8ec25ea3-27f6-447d-9537-5a74110b2ce2.png)
![image](https://user-images.githubusercontent.com/79493220/163700137-a1b8b5dd-d383-478f-afc0-f6a538241633.png)
![image](https://user-images.githubusercontent.com/79493220/163700164-8eea7b9c-8e5f-4f86-9f52-fd8d5555347a.png)
![image](https://user-images.githubusercontent.com/79493220/163700208-593c249a-e0ad-49a8-b960-4220ab199619.png)
![image](https://user-images.githubusercontent.com/79493220/163700227-1cbaea41-acac-4de8-9ce5-1023aa62c737.png)
![image](https://user-images.githubusercontent.com/79493220/163700258-c6e2b610-4450-4ebf-865b-8d1007e33b2a.png)
![image](https://user-images.githubusercontent.com/79493220/163700283-18711f1b-2fad-4013-9251-21a1560d99d9.png)
![image](https://user-images.githubusercontent.com/79493220/163700306-e439b118-a84f-4c8f-854b-ee5c3f2942f8.png)
![image](https://user-images.githubusercontent.com/79493220/163700321-3fcfca0c-49c0-4455-bd1e-e23825d6290e.png)
![image](https://user-images.githubusercontent.com/79493220/163700338-e2579467-13c8-4a5d-a880-3a129ecc93da.png)

**Comment by hagen1778** [comment]
Hi @Planck0591! Sorry to hear you have issues with VM.

First of all, I'd recommend you updating to [1.76.1](https://docs.victoriametrics.com/CHANGELOG.html#v1761) since it contains memory usage improvements.

The second thing is trying increasing allowed/available memory for vmstorage nodes. From the "SlowInserts" panel it is clear that storage nodes has not enough memory for caches, which results in very high % of slow inserts. Normally, this value should not exceed 1-2%. If you use the [recommended set of alerts](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/26b78ad707af75074df1d5444add07a4b261ad6a/deployment/docker/alerts.yml#L184-L198), you'd be notified about this.

"Rows rerouted to"/"Rows rerouted from" graphs show that some storage nodes are unavailable or unable to keep up with the ingestion speed. This is basically a crash recovery scenario and it shouldn't be permanent if your system is stable. Rerouting consumes additional resources and affects the sharding of time series. In short, if you 3 storage nodes and 1000 of time series - they will be evenly split among the nodes. When one storage goes off and rerouting triggers, 1000 is divided by 2, which means each storage node needs to store and process 500 series. Processing the series requires resources, memory first of all. The less Active Series you have, the less RAM you need. So that might be also a cause of too high mem consumption.

Please note, memory limits in VictoriaMetrics are used to control caches size only. These limits don't take into account additional memory, which may be needed for processing incoming queries. See more details below:
https://docs.victoriametrics.com/FAQ.html#how-to-set-a-memory-limit-for-victoriametrics-components

**Comment by Planck0591** [comment]
@hagen1778 Thank you very much for your suggestions, I will update to 1.76.1 right now and increese meachines number to suply more memory.

**Comment by hagen1778** [comment]
Closing as inactive
