### ISSUE TITLE
[VictoriaMetrics cluster] Failed to get most metrics after update from 1.75.0 to 1.76.1

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [VictoriaMetrics/VictoriaMetrics#2485]
**Describe the bug**
Most of the metrics got lost after update from 1.75.0 to 1.76.1

**To Reproduce**
I upgraded the VictoriaMetrics cluster version  from 1.75.0 to 1.76.1 (Helm chart 0.8.1).
After that, all the metrics from pods was lost (few node metrics were still present). 
For example, `container_cpu_usage_seconds_total` showed labels but the graph was empty.
Version 1.75.0 worked without issues.
It was still possible to check the previous old metrics in the timeline.
When rolled back to version 1.75.0, the metrics started to show up again.

**Expected behavior**
The metrics should work after upgrade.

I could not find anything useful in the logs related to this issue.
My issue is very similar to this one: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/290
However, clearing up the `/vm-data/cache` folder on both  `vmstorage-vmetrics-0` and `vmstorage-vmetrics-0` pods did not help.

**Comment by luhhujbb** [comment]
Same issues, with a too many series calling the series endpoints. With the same solution, a roll back to 1.75.0 fix the issue.

**Comment by valyala** [comment]
> Same issues, with a "too many series error" calling the series endpoints. With the same solution, a roll back to 1.75.0 fix the issue.

@luhhujbb , could you look into `vmselect` and `vmstorage` logs? It is likely you hit the `-search.maxSeries` limit, which has been introduced in [v1.76.0](https://docs.victoriametrics.com/CHANGELOG.html#v1760). In this case the logs should contain error messages about this limit. The limit prevents from excess resource usage when Grafana sends requests to [/api/v1/series](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) in order to obtain metric names, label names or label values for auto-suggestion. If you feel that the default limit is too low, feel free to increase it. For example,  passing `-search.maxSeries=1000000` command-line flag to `vmselect` would increase the limit to a million. Note that this can result in higher CPU and RAM usage.

**Comment by jiekun** [comment]
Hi. I'm going to close this issue due to inactivity. If you have more info to provide, feel free to re-open it.
