### ISSUE TITLE
Default retention period should be at least one year

### ISSUE THREAD

**Issue by heliodor** [VictoriaMetrics/VictoriaMetrics#249]
From the first paragraph describing VictoriaMetrics:
VictoriaMetrics "can be used as long-term remote storage for Prometheus."

As such, having `retentionPeriod` default to 1 month seems arguably wrong. I'd default it to at least 12 months. I doubt people using products in this space tend to think of one month as "long-term".

**Comment by valyala** [comment]
Agreed, but it may be too late to change the default `retentionPeriod`, since this may silently break expectations for existing users. I.e. they expect one month retention by default, but it silently changes to 12 months after the upgrade.

**Comment by AeroNotix** [comment]
Also, not being able to control a sub-month precision makes certain use-cases difficult.

**Comment by valyala** [comment]
There are plans for implementing sub-month retention precision - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/173 . It can be implemented by removing data points outside the retention during merges of smaller parts into bigger parts. This is so-called `lazy` retention enforcement. See [this article](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282) in order to understand what does `part` mean in the context of VictoriaMetrics storage.

**Comment by valyala** [comment]
VictoriaMetrics supports arbitrary [retention periods](https://docs.victoriametrics.com/#retention) in the range 24h - 100y (24 hours - 100 years) starting from `v1.45.0` - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/173) for details.

We aren't going to change the default retention period, since it will break backwards compatibility: e.g. when users, who run VictoriaMetrics with the default one month retention, will upgrade to the release with the default retention of one year, then they won't be happy.

Closing this feature request as won't implement.

**Comment by AeroNotix** [comment]
What if I need more than a year? I want my children's children to be able to scroll all the way back!

**Comment by macegr** [comment]
> users, who run VictoriaMetrics with the default one month retention, will upgrade to the release with the default retention of one year, then they won't be happy.

I will say that users who lose data they weren't expecting tend to be unhappier than those who accidentally keep extra data. Like me, today, for example.

If you don't want to change the default, please update the setup documentation with some **bright red text** that declares loudly what the default retention period is, and suggests changing it if 30 days isn't enough.

I found out by losing a month of two of irreplaceable test data. Oops.

Someone who finds out they've stored 5 months of data when they only wanted one has a really easy fix. Someone who thought they had 5 months of data but only has one doesn't have any real solution.

**Comment by makasim** [comment]
@macegr Sorry you ran into this, and thanks for the feedback. Losing data you expected to keep is definitely worse than accidentally retaining extra data.

Unfortunately, we can’t change the default retention now without risking breaking existing installations or causing storage issues for other users.

Your point about documentation is valid, though. We should make the default retention period much more visible in the setup docs and clearly recommend adjusting it when 30 days is not enough.

Which quick start or setup guide did you follow? We’d like to improve it.

**Comment by macegr** [comment]
I started here: https://docs.victoriametrics.com/victoriametrics/quick-start/ and once running mostly focused on the API documentation.

**Comment by hagen1778** [comment]
> If you don't want to change the default, please update the setup documentation with some bright red text that declares loudly what the default retention period is, and suggests changing it if 30 days isn't enough.

I don't think it is practical. No one expects installtion from a quick start becoming a production-level installation. 
And to become a production-level installation much more than retention setting should be done:
1. Monitoring
2. Security
3. Backups
4. Resource usage limits

It is expected for users to go through https://docs.victoriametrics.com/victoriametrics/quick-start/#productionization before relying on the installtion. I suggest we add `Retention` section there.

**Comment by makasim** [comment]
> I suggest we add Retention section there.

👍 Makes sense to me.

**Comment by macegr** [comment]
Note that the "Productionization" section is _part of_ the Quick Start page, and therefore if you add recommendations for retention settings there, that's precisely what I asked for. 👍
