### ISSUE TITLE
VMAlert: Support for multiple remote write 

### ISSUE THREAD

**Issue by sreejith-vk** [VictoriaMetrics/VictoriaMetrics#2522]
**Is your feature request related to a problem? Please describe.**
I use ALERTS{} and ALERT_FOR_STATE{} metrics as input for some meaningful Grafana dashboards. These dashboards use a combination of various alerts in firing state to perform automated root cause analysis. For this to work with the vmalert I need to remote write to my Grafana Datasource which is different from the one I use for storing recording rule data. Hence the support for multiple remote writes in vmalert is required.

**Describe the solution you'd like**
To support multiple `url` parameters under `remote write` in vmalert. 

**Describe alternatives you've considered**
At present, the last imported URL parameter is applied when vmalert starts up. If in case of technical challenges, will it be technically feasible to add these two metrics ALERTS{} and ALERT_FOR_STATE{} to vmalert-server:8880/metrics ?

Any suggestions for alternative solutions or features are welcome.

**Additional context**
Multiple VM remote write is supported by vmagent.

**Comment by f41gh7** [comment]
Possible workaround - use `vmagent` with multiple remote-writes as `remoteWrite.url` value for the `vmalert`.

**Comment by sreejith-vk** [comment]
Sorry, didn't get you. I am trying to collect ALERTS and ALERT_FOR_STATE data. This data is not present in vmagent.

**Comment by brucelee138** [comment]
The lack of multiple remote write supports affects when we try sending any chained recording rules to a remote source other than VMstorage. The base record is not stored and so not available for evaluating the dependent recording rule and so only the base recording rule is sent to the remote source over remote write.

**Comment by valyala** [comment]
> Sorry, didn't get you. I am trying to collect ALERTS and ALERT_FOR_STATE data. This data is not present in vmagent.

Currently `vmagent` doesn't support multiple `-remoteWrite.url` options in order to replicate `ALERTS` and `ALERT_FOR_STATE` metrics across multiple remote storage systems as described [here](https://docs.victoriametrics.com/vmalert.html#alerts-state-on-restarts). The workaround is to point `-remoteWrite.url` at `vmalert` to [vmagent](https://docs.victoriametrics.com/vmagent.html), which is configured to replicate incoming data into multiple remote storage systems. `vmagent` supports multiple `-remoteWrite.url` options specifically for this case - see [these docs](https://docs.victoriametrics.com/vmagent.html#replication-and-high-availability).

**Comment by Haleygo** [comment]
dup with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/694

**Comment by jiekun** [comment]
Please track and discuss in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/694
