### ISSUE TITLE
union returns only the second rate

### ISSUE THREAD

**Issue by dmitpanov** [VictoriaMetrics/VictoriaMetrics#26]
Hi there,
I'm trying to substitute following 2 expressions:
`rate(node_network_receive_bytes_total{device="eth0",instance="10.128.150.61:9100",job="main"}[1m])`
and
`rate(node_network_transmit_bytes_total{device="eth0",instance="10.128.150.61:9100",job="main"}[1m])
`
with 
`WITH (
cf = {device="eth0",instance="10.128.150.61:9100",job="main"}
)
(rate(node_network_transmit_bytes_total{cf}), rate(node_network_receive_bytes_total{cf})) offset 1m`

but that query for some reason returns only the second metric of the union.

Is that expected?  Or had I missed something in ExtendedPromQL docs?
Kind regards.

**Comment by valyala** [comment]
`rate` strips time series name and leaves only time series labels. These labels are identical for queries `q1` and `q2` in the union: `(rate(q1), rate(q2))`, so the union ignores time series from `rate(q2)`. Possible fixes:
1) To use `label_set` in order to set distinct labels for the united time series:
```promql
(
    label_set(rate(q1), "direction", "transmit"),
    label_set(rate(q2), "direction", "receive"),
)
```
2) To filter by `__name__` in a single query:
```promql
rate({__name__=~"node_network_(transmit|receive)_bytes_total",device="eth0",instance="10.128.150.61:9100",job="main"})
```
