### ISSUE TITLE
Some metrics are no longer readable on vmselect >= 1.77.0

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#2629]
We encountered strange behavior: when updating the cluster from v1.74.0 to v1.77.1, part of the metrics stopped being read, vmselect returns an empty result when querying, as if these time series don't exist. The difference between broken metrics is that they are scraped by vmagent with 2s scrape interval. And still available metrics are collected with 30s scrape interval.

Experimentally we found out that the behavior returns to normal when downgrading vmselect to version 1.76.1, while other components (vmagent, vminsert, vmstorage) still on latest version 1.77.1. Upgrading vmselect to 1.77.0 or 1.77.1 breaks metrics with 2s scrape interval.

vminsert runs with options:
```
-enableTCP6 -loggerLevel=INFO -httpListenAddr=:8480 -memory.allowedPercent=60 -http.shutdownDelay=15s -disableRerouting -storageNode=<>
```

vmstorage runs with options:
```
-enableTCP6 -loggerLevel=INFO -retentionPeriod=12 -storageDataPath=/var/lib/vmstorage/0 -httpListenAddr=:8490 -vminsertAddr=:8400 -vmselectAddr=:8450 -bigMergeConcurrency=4 -smallMergeConcurrency=4 -memory.allowedPercent=30
```

vmselect run with options:
```
-enableTCP6 -loggerLevel=INFO -httpListenAddr=:8481 -http.shutdownDelay=15s -search.maxConcurrentRequests=32 -dedup.minScrapeInterval=30s -storageNode=<>
```

On vmselect we using `-dedup.minScrapeInterval=30s` option, because most of our metrics are collected with interval 30s. And recently added metrics with scrape interval 2s are also correctly handled with this option until update to 1.77.0+.
And I noticed an oddity. On vmselect version 1.76.1 or older, if I specify `-dedup.minScrapeInterval` option to 2s, or anything less than 11s, metrics collected with 2s interval disappears. And if `-dedup.minScrapeInterval` set to 12s or more, 30s in our normal use, those metrics become available again.
Looks like on 1.77.0+ something is changed, and metrics collected with 2s interval are missing with any value of `-dedup.minScrapeInterval=`.

**Comment by wf1nder** [comment]
vmselect v1.77.2 also have this issue.

**Comment by valyala** [comment]
@wf1nder , could you provide a few sample queries, which stop returning time series in VictoriaMetrics v1.77+?

**Comment by valyala** [comment]
@wf1nder , could you also provide the graph for the `stale_samples_over_time(m[30s])`, where `m` must be substituted with the [time series selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors), which selects the time series with 2s scrape interval?

**Comment by wf1nder** [comment]
We use 2s scrape intervals for metrics that exist for a short time (which exports by some batch tasks), from a ~30 seconds to an hour or so.
Now I have discovered that some of these metrics become visible for a short time on v1.77+, and these are metrics that are exported for about 10 minutes or longer. Other metrics that are exported for 0-2 minutes are not displayed at all, as I wrote above.

Graph of metric with 2s interval, which exports within 40 minutes, with vmselect v1.76.1:
![Screen Shot 2022-05-23 at 15 54 57](https://user-images.githubusercontent.com/4486762/169825416-66768bfc-d0e2-4a2d-a20d-c9c9df33a51d.png)

vmselect v1.77.2:
![Screen Shot 2022-05-23 at 15 55 12](https://user-images.githubusercontent.com/4486762/169825943-795dc063-da95-4575-9c98-ee042cbdea30.png)

> @wf1nder , could you provide a few sample queries, which stop returning time series in VictoriaMetrics v1.77+?

Simple metric request, even without labels, like:
```
teamcity_agent_info
```



> @wf1nder , could you also provide the graph for the `stale_samples_over_time(m[30s])`, where `m` must be substituted with the [time series selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors), which selects the time series with 2s scrape interval?

Query:
```
stale_samples_over_time(scanned_offers[30s])
```

v1.76.1:
![Screen Shot 2022-05-23 at 15 56 05](https://user-images.githubusercontent.com/4486762/169826476-0901402c-fc55-4e43-a5b3-5a2be539a964.png)

v1.77.2:
![Screen Shot 2022-05-23 at 15 56 17](https://user-images.githubusercontent.com/4486762/169826507-b345c266-c665-48f9-9f14-2b2e90e02943.png)

**Comment by valyala** [comment]
@wf1nder , thanks for the provided details and sorry for the long delay with response. The issue is most likely related to https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0d86644d65de5f30be3c592da4a88ecd02a7a41b , which changes the deduplication logic. `vmselect` v1.77.0 and newer versions leaves the last sample per each discrete 30 second interval if it runs with `-dedup.minScrapeInterval=30s`, while previous releases were leaving the first sample per each discrete 30 second interval - see [deduplication docs](https://docs.victoriametrics.com/#deduplication) for details.

If short-living series contain [staleness markers](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) at the end of every 30 second interval, then such series become invisible after applying `-dedup.minScrapeInterval=30s`, since the de-duplication leaves only staleness markers. `vmagent` may insert staleness markers in different cases described [here](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers). For example, if the metric disappears for a short period of time and then appears again, then `vmagent` may insert staleness marker when it scrapes a set of metrics without the given metric.

**Comment by wf1nder** [comment]
@valyala, thank you for the answer, and I also apologize for the long reaction from me.

Indeed, I disabled staleness markers on the magent side via the option `-promscrape.nostalgemarkers=true`, and the problem went away: with vmselect version v1.77.0 and higher, metrics no longer disappear, the behavior is back to how it was before v1.77.0.
In general, our problem can be considered solved, we simply will not use staleness markers. But is this behavior correct?
If I understood correctly, it turns out that deduplication leaves the last sample, which is a some sort of service data (staleness marker), and at the same time, without leaving useful data (metric samples)?

**Comment by valyala** [comment]
> If I understood correctly, it turns out that deduplication leaves the last sample, which in this case is a some sort of service data (staleness marker), and at the same time, without leaving useful data (metric samples)?

The staleness marker is used by [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) query engine in order to determine the timestamp after which it should stop returning data for time series matching `some_series_name{optional="labels"}`. Staleness markers shouldn't be removed during de-duplication, since otherwise VictoriaMetrics would continue returning data after the deleted staleness marker for up to 5 minutes (usually for up to `2 * scrape_interval`, where `scrape_interval` is the interval between raw samples for the particular time series). This may break some queries such as `sum(some_metric)` if `some_metric` time series changes some label value. For example, it had `some_metric{label="foo"}` name until some timestamp and after that it has been renamed to `some_metric{label="bar"}`. If stale markers are removed then the `sum(some_metric)` would show 2x spike around the given timestamp.

> with vmselect version v1.77.0 and higher, metrics no longer disappear, the behavior is back to how it was before v1.77.0.

Thanks for the confirmation. Then closing the issue as resolved.
