### ISSUE TITLE
query with a single time series selector get response: 'duplicate output timeseries'

### ISSUE THREAD

**Issue by eddietanshuo** [VictoriaMetrics/VictoriaMetrics#2651]
**Describe the bug**

![image](https://user-images.githubusercontent.com/103412360/170697718-14601d54-a06d-477b-8bea-933790aad679.png)

> The query is:
`_95_percentile{Name="xxxxxx", __endpoint__="xxxxxxx", name="xxxxxxxx"}`

> The response is:
`422: error when executing query="_95_percentile{Name=\"xxxxxx\", __endpoint__=\"xxxxxxx\", name=\"xxxxx\"}" on the time range (start=1653630570000, end=1653652170000, step=15000): cannot execute query: duplicate output timeseries: _95_percentile{Department="xxxx", Name="xxxxxxxxx", __endpoint__="xxxxxxxxx", icop="xxxx", name="xxxxxxx"}`

**Raw sample**
use `/api/v1/export` to get raw samples from the vmstorage, we get two metric:

`{"__name__":"_95_percentile","Name":"xxxxxx","name":"xxxxxx","Department":"xxx","__endpoint__":"xxxxxxx","icop":"xxxxx"}`

`{"__name__":"_95_percentile","name":"xxxxxxx","Name":"xxxxxx","Department":"xxxx","__endpoint__":"xxxxxxx","icop":"xxxxx"}`

**Guess**

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757

I see both `name` and `Name` serialize into the same canonical tag key which is `"\x00\x01\x40"`, vmstorage will use this key to sort tags and construct metric name, so if someone remote write metrics like `test{name:"aaa", Name:"bbb"}` will not guarantee the order.

**Comment by valyala** [comment]
@eddietanshuo , thanks for the bugreport and for the root cause analysis. Confirming the issue - can be triggered with the following steps:

1) To push multiple metrics with at two identical labels from [this list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757), where one label starts from uppercase, while another label starts from lowercase. For example, `foo{name="v1",Name="v2"}` - the metric contains two `name` labels - one starts from lowercase - another one starts from uppercase.

2) To query the metric with such metrics. VictoriaMetrics returns `duplicate output timeseries` error.

### The reason for the issue:

VictoriaMetrics converts incoming metric name with its labels to a `canonical form` in order to determine the time series to push the metric value. The `canonical form` contains labels sorted by name in general case, so metric values with the same set of labels, but with different order of these labels could be written into the same time series.

For example, the canonical form for  `foo{x="y",baz="v1",bar="v2"}` and `foo{bar="v2",baz="v1",x="y"}` is `foo{bar="v2",baz="v1",x="y"}`.

The sort order of labels in canonical form is augmented for labels from [the list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757). Such labels are moved to the beginning of the list in `canonical form`. For example, the canonical form for `foo{bar="baz",name="x"}` is `foo{name="x",bar="baz"}`. This is needed in order to physically group together the data for time series with identical `label=value` pairs from [the list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757). This is an optimization, which reduces disk read iops during querying, since VictoriaMetrics can read a big block of data belonging to the same label instead of reading big number of smaller blocks scattered across the disk.

The issue is that VictoriaMetrics gives identical priority for labels from [this list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757) if they start from both lowercase and uppercase char. This makes canonical labels' sorting non-deterministic, e.g. `foo{name="a",Name="b"}` may be transformed to both `foo{name="a",Name="b"}` and `foo{Name="b",name="a"}` canonical forms. So VictoriaMetrics creates two distinct time series for such a metric and pushes incoming samples to a random series out of these series.

This is a shortcoming of the algorithm, which is used for generating `canonical form` for incoming metrics. Unfortunately, I don't know how to fix it properly right now, so it doesn't break already existing data :( One possible solution is to detect and merge such time series during querying. But it would be better to fix the root cause of the issue in order to prevent from creating multiple physical time series for a single logical time series.

### The workaround

To avoid pushing metrics to VictoriaMetrics with duplicate labels from [the list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e99bbb9678318c78bcfad79f6e84710d398ee2d/lib/storage/metric_name.go#L740-L757), where one label starts from lowercase, while another label starts from uppercase.

**Comment by eddietanshuo** [comment]
Thanks for your nice explain. I will close this issue.
