### ISSUE TITLE
Question - Prometheus to VM guide

### ISSUE THREAD

**Issue by cihantunali** [VictoriaMetrics/VictoriaMetrics#2694]
Hello,
I am using prometheus with below exporters. Is VM compatible with these exporters? Can I use Grafana dashboards with VM like prometheus? Do you have any guide to move prometheus to VM? After migration, I do not want to use prometheus, my setup will be VM+Grafana instead of Prometheus+Grafana. Any help appreciated.

- node_exporter
- redis_exporter
- rabbitmq_exporter
- windows_exporter
- blackbox_exporter
- snmp_exporter
- elasticsearch_exporter
- haproxy_exporter

**Comment by dmitryk-dk** [comment]
Hi @cihantunali ! You can read documentation here about VM
https://grafana.sandbox.victoriametrics.com/d/gFFU1y9nk/victoriametrics-github-downloads?orgId=1&var-ds=sandbox-monitoring&var-platform=amd64&var-ver=1.77.2&viewPanel=9

Also It can be used as drop-in replacement for Prometheus in Grafana, because it supports [Prometheus querying API](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#prometheus-querying-api-usage).

And you can check 
https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-scrape-prometheus-exporters-such-as-node-exporter

It might be helpful for you

**Comment by cihantunali** [comment]
Hello @dmitryk-dk !
Thank you for quick reply, unfortunately I could not login the first link that sent. I learned that I can forward requests from Prometheus to VM easly but with this way, I have to have Prometheus and VM together which I do not want it. Do you have any info about it? Thanks.

**Comment by denisgolius** [comment]
> Hello @dmitryk-dk ! Thank you for quick reply, unfortunately I could not login the first link that sent. I learned that I can forward requests from Prometheus to VM easly but with this way, I have to have Prometheus and VM together which I do not want it. Do you have any info about it? Thanks.

Hi @cihantunali !
As @dmitryk-dk  wrote before you can setup and use VM Single as drop-in replacement for Prometheus. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml which contains vmagent that will scrape data from exporters and will send it to VictoriaMetrics Single https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml#L21 .

You can set up VictoriaMetrics in docker containers or as systemd services - see https://github.com/patsevanton/victoriametrics-rpm and https://www.vultr.com/docs/install-and-configure-victoriametrics-on-debian .
We have some [guides](https://docs.victoriametrics.com/guides/) and other [articles ](https://docs.victoriametrics.com/Articles.html) that might be helpful.

**Comment by jelmd** [comment]
@cihantunali FWIW wrt. snmp_exporter: If you need something more flexible and efficient tool, have a look at its fork on https://github.com/jelmd/snmp-export (standalone, i.e. no prometheus tools needed) ;-)
