### ISSUE TITLE
lib/storage: partial time series lost when query time range within one day at the retention date

### ISSUE THREAD

**Issue by eddietanshuo** [VictoriaMetrics/VictoriaMetrics#2698]
**Describe the bug**
- We set one db's retentionPeriod to 1 day, another db's retentionPeriod to 1 year
- The query expression is in count of all time series
- We query the data at 2022/06/08 14:00 GMT+8 several times, each time we set different time range. Here is our result (right one is the db with one day retention)

> 06-07 21:00 - 06-07 22:00 GMT+8 [PROBLEM]
![image](https://user-images.githubusercontent.com/103412360/172587879-38b8488a-6279-4652-870a-d1a02852a5bc.png)

> 06-07 21:00 - 06-08 09:00 GMT+8 [OK]
![image](https://user-images.githubusercontent.com/103412360/172593729-40402e01-3712-4a81-b82c-3624fc60e25d.png)

> 06-07 21:00 - 06-08 07:00 GMT+8 [PROBLEM]
![image](https://user-images.githubusercontent.com/103412360/172594394-282110a4-0971-4a0f-a8c4-78f6d4d20168.png)

> 06-07 21:00 - 06-08 07:59 GMT+8 [PROBLEM]
![image](https://user-images.githubusercontent.com/103412360/172594765-622eeade-c91e-4baf-b194-36e109bcf5ee.png)

> 06-07 21:00 - 06-08 08:05 GMT+8 [OK]
![image](https://user-images.githubusercontent.com/103412360/172594927-33a8466a-e4a7-400f-a1c2-d337450dcc71.png)

**Expected behavior**
Since we set the retentionPeriod to 1d, we expect that we could at least get the correct data within 24h. For instance, in our case we query at  `2022/06/08 14:00 GMT+8` and should get correct result at time range  `06-07 14:00 - 06-08 14:00 GMT+8`

**Version**
1.77.0-cluster

**Guess**
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1ee1e986dad75a0fbff3c658385e9fa4699e25b2/lib/storage/partition.go#L1197-L1204

![未命名文件 (22)](https://user-images.githubusercontent.com/103412360/172650774-9a523d0f-7d88-45bf-8306-692fe6d2bd29.png)

Partition merge parts and delete blocks which max timestamp is less than `now() - retentionPeriod`. However the index only created when the time series ingest the first timestamp at that day after 00:00 am. Hence it will result in a `gap zone` which is the red area in the above graph. Those time series created during the gap zone will lose even they are continuously ingesting new datapoints.

**Suggestion**
To eliminate the `gap zone`, we could try to round deadline from `now() - retentionPeriod` to `deadline = now() - retentionPeriod;  newDeadline := time.Date(deadline.Year(), deadline.Month(), deadline.Day(), 0, 0, 0, 0, UTC)`

**Comment by eddietanshuo** [comment]
@valyala  Could you please help us with this issue. Thanks a lot !!

**Comment by valyala** [comment]
@eddietanshuo , thanks for filing the detailed bugreport and providing the [pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2702). I'll look into this issue soon.

**Comment by valyala** [comment]
@eddietanshuo , could you build VictoriaMetrics cluster components from the commit c5ac1761539b9a5d71c50f1c244a9bf2fa3f6dfc according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether this fixes the issue?

Note that you need to build and run all the cluster components - `vminsert`, `vmselect` and `vmstorage` from this commit, since the upcoming release changes the communication protocol between `vmselect` and `vmstorage` in backwards-incompatible way, so cluster components from the previous releases may communicate improperly with the new cluster components - see [changelog](https://docs.victoriametrics.com/CHANGELOG.html) for details.

**Comment by valyala** [comment]
The bugfix has been included in [VictoriaMetrics v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing the issue as fixed.

@eddietanshuo , feel free re-opening the issue if it still exists in VictoriaMetrics v1.78.0 .

**Comment by valyala** [comment]
Re-opening the issue, since it has been appeared that this issue is still there because of gradual indexdb re-population introduced at cf1a8bce6bfe725f3f363c8ad78d422b18141369 in an attempt to fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401 . See also 1f28b46ae9350795af41cbfc3ca0e8a5af084fce .

**Comment by valyala** [comment]
The issue should be fixed in the release [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html) - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401#issuecomment-1654787024 for details.

@eddietanshuo , please re-open the issue if it still presents in v1.92.0.
