### ISSUE TITLE
Question about using NFS/AWS EFS

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#27]
Hello,

I am looking at potentially using VictoriaMetrics and storing the data on a NFS or an AWS EFS (Amazon's NFS) share. I know if the past with some other databases, using NFS shares has been discouraged. I was wondering if VictoriaMetrics has been tested using NFS, or even supports it usage?

Thanks in advance.

**Comment by valyala** [comment]
We didn't test VictoriaMetrics with NFS shares. It should work.
But I'd recommend using [Google Compute Engine disks](https://cloud.google.com/compute/docs/disks/#pdspecs) or [Amazon EBS](https://aws.amazon.com/ebs/) instead, since they provide better reliability comparing to NFS. Google disks are preferred, since they are protected from data corruption / loss and they are faster than Amazon EBS.

**Comment by hagen1778** [comment]
Just want to add that [vertical scalability benchmarks](https://medium.com/@valyala/measuring-vertical-scalability-for-time-series-databases-in-google-cloud-92550d78d8ae) were conducted on Google Cloud.

**Comment by BenB196** [comment]
Thanks for the information, I am still determining whether to use a cloud provider or my own setup for storing data, but wanted to confirm that NFS would be a suitable file system to use.

**Comment by valyala** [comment]
@BenB196 , it would be great if you'll return to this thread with results regarding NFS usage as a storage for VictoriaMetrics.
