### ISSUE TITLE
Question: How important is 30% empty disk space requirement for vmstorage

### ISSUE THREAD

**Issue by salarali** [VictoriaMetrics/VictoriaMetrics#2711]
Based on the documentation, we should have atleast 30% disk space free for vmstorage in cluster mode. How important is that threshold?

I recently was using around 95% disk space (5% free). I extended the disk space so that there is around 35% disk free now. But the moment I did that, there were a lot of Active Merges started happening.

Is there a metric that I can use to see that there are some processes not happening anymore because of less disk space? Or should I also try to reach for the 30% threshold.

Old disk space: 2TB. New extended disk space: 3TB.

**Comment by hagen1778** [comment]
Hi @salarali!
It is recommended at least 20% of free disk space. I made a clarification here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2728

The docs also contain explanation of [why is that](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#storage):
```
VictoriaMetrics doesn't merge parts if their summary size exceeds free disk space. This prevents from potential out of disk space errors during merge. The number of parts may significantly increase over time under free disk space shortage. This increases overhead during data querying, since VictoriaMetrics needs to read data from bigger number of parts per each request. That's why it is recommended to have at least 20% of free disk space under directory pointed by -storageDataPath command-line flag.
```

There is a metric which shows if merge was delayed due to insufficient disk space - `vm_merge_need_free_disk_space`. But I won't recommend using it for alerts or for defining health state. It is okay if merge was delayed. It is not okay if there is a trend for increasing of number of such delays. However, VM will still continue to function even with delayed merges, but not so efficient.

**Comment by salarali** [comment]
Thanks for the detailed information!
