### ISSUE TITLE
Flag configuration disclosure

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2753]
**Describe the bug**
 Currently, all VictoriaMetrics components disclosure its configuration at `/flag` page. There is no way to protect it by application itself.

**Expected behavior**

 There must be the way to protect this endpoint. It's especially relevant for`vmauth` and `vmgateway` which could be run without any proxy in front of it.  

I suggest to introduce new flag `-flagAuthKey=some-value`.

**Comment by f41gh7** [comment]
cc @valyala  @dima-vm

**Comment by valyala** [comment]
FYI, the severity of this issue isn't high, since VictoriaMetrics components already hides values for command-line containing `key`,  `pass`, `token` and `secret` in their names when exposing them at `/flags` page:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aeeaf877ac93e80b2bd486f70fff115e4911f264/lib/flagutil/flag.go#L15

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aeeaf877ac93e80b2bd486f70fff115e4911f264/lib/flagutil/secret.go#L21-L26

**Comment by valyala** [comment]
All the VictoriaMetrics components support `-flagsAuthKey` command-line flag for protecting the `/flags` page from unauthorized access starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
