### ISSUE TITLE
VMUI: instant query support/fix 

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/VictoriaMetrics#2781]
**Describe the bug**
It seems like `VMUI` doesn't support instant queries in the past, only the last data points could be selected. 
When I open `Table` or `JSON` tab in VMUI I see query like this one is sending to the VictoriaMetrics API:
```
https://vmselect.example.com/select/0/prometheus/api/v1/query?query=sum(scrape_samples_scraped)&start=1655222779.519&end=1656059720&step=2324.835
```
which afaik make no sense, as in the case of[ instant query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) which is `/api/v1/query` there should be only `time` parameter, but not `start` and `end`.
Otherwise, in case of [range query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) which is `/api/v1/query_range` there should be a different API URL call.

**To Reproduce**
Open up `JSON` or `Table` tabs and check the HTTP query in Developer mode of the Browser

**Expected behavior**
I personally thought that `JSON` and `Table` tabs would implement Instant query, so in that case we should use only the `time`
parameter, which should be possible to choose

**Screenshots**
<img width="1439" alt="Screenshot 2022-06-24 at 11 56 01" src="https://user-images.githubusercontent.com/5423271/175514507-7ec7ed49-6fb0-44e6-8581-4c53a6f28ac4.png">

**Version**
```
/ # /vmselect-prod --version
vmselect-20220621-091123-tags-v1.78.0-cluster-0-g24097f241
```

**Comment by hagen1778** [comment]
cc @Loori-R

**Comment by valyala** [comment]
FYI, the issue has been fixed in the commit 2e9ae40d56a09bbb5bee850b2b0986269322a9bb . Now `JSON` and `Table` views in [vmui](https://docs.victoriametrics.com/#vmui) should show results for the end of the selected time range.

This commit will be included in the next release. In the meantime it is possible to build cluster components of VictoriaMetrics according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) from this commit and make sure the issue is fixed.

**Comment by Vladikamira** [comment]
Thanks, guys!

**Comment by valyala** [comment]
FYI, the bugfix for the issue has been added to [VictoriaMetrics v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
