### ISSUE TITLE
how to set the  -external.alert.source  

### ISSUE THREAD

**Issue by Songdantes** [VictoriaMetrics/VictoriaMetrics#2807]
**Is your feature request related to a problem? Please describe.**

In order to see the monitoring information more clearly , I want to custom the alert url

the external.alert.source  default is (/api/v1/groupID/alertID/status)

**Describe the solution you'd like**

I want to put off the '/api/v1' ,  the final url is   xxx.com/groupID/alertID/status , how can I set  the **-external.alert.source** ?

**For example;**
I want to this 
https://vmalert-prod.xxx.com/15984873028928896350/12315514153193558552/status
not 
https://vmalert-prod.xxx.com/api/v1/15984873028928896350/12315514153193558552/status

**Comment by valyala** [comment]
@hagen1778 , could you look into this question?

**Comment by Songdantes** [comment]
Can we find a way to solve this problem？ @valyala @hagen1778

**Comment by hagen1778** [comment]
Hi @Songdantes! You can override the url and path with `-external.url` and `-external.alert.source` respectively. You can also use [templating](https://pkg.go.dev/text/template) in `-external.alert.source`, including accessing alert's labels, expression, etc. Unfortunately, alert_id and group_id are not available in templating.
We can either add these params to templating engine, or allow configuring url prefix in the future.
As a workaround, try using reverse proxy in order to strip `/api/v1` on requests to `https://vmalert-prod.xxx.com`.

**Comment by Songdantes** [comment]
@hagen1778  thank you, I made a reverse proxy resolved this problem.
