### ISSUE TITLE
label_values from grafana works inconsistently with prometheus when label == "app"

### ISSUE THREAD

**Issue by SmilingNavern** [VictoriaMetrics/VictoriaMetrics#282]
**Describe the bug**
label_values(label) query from grafana returns something that looks like set of timestamps. In prometheus this query returns values for label accross all metrics.

label_values(metric, label) works as expected.

**To Reproduce**
Setup grafana, prometheus and VictoriaMetrics. Create dashboard with variables and use label_values(label) with prometheus and with VM. See the different output.

**Expected behavior**
I would expect that label_values(label) returns values for all metrics with such a label.

**Version**
victoriametrics/vmstorage:v1.29.5-cluster

**Comment by SmilingNavern** [comment]
I've got strange results. It doesn't work only with label `app` which returns timestamps. Other labels that i've tested return correct result.

Here is screenshot for label app:
![Screenshot from 2019-12-27 13-24-10](https://user-images.githubusercontent.com/1247679/71514658-c43e6500-28b0-11ea-8bac-246f82daff2e.png)

Any ideas?

**Comment by valyala** [comment]
Grafana requests [/api/v1/label/<label_name>/values](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values) API for `label_values(label_name)`, while it requests [/api/v1/series?match[]=<query>&start=...&end=...](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) and filters out results from it for `label_values(query, label_name)`.

The `/api/v1/label/<label_name>/values` handler doesn't accept time range, so it returns all the values for the given `<label_name>`, while `/api/v1/series` handler accepts time range (see `start=...&end=...` in the query to `/api/v1/series`), so it returns values only for the given time range.

It looks like your data contains time series with a lot of `app` label values shown on the screenshot from the previous time range. Try the following workaround: `label_values({app=~".+"}, app)`. It should select all the `app` label values on the given time range. Note that this workaround can work slower than just `label_values(app)` if the given time range contains high number of time series with `app` label, since Grafana selects metainformation for all the time series with `app` label on the given time range. The number of selected time series can be narrowed down by adding more specific label filters to `query`. For instance, if you scrape data with Prometheus and `app` label is added by Prometheus, then try `label_values(up, app)` query, since `up` metric is automatically generated by Prometheus for each scraped target.

**Comment by valyala** [comment]
Closing this question as answered.
