### ISSUE TITLE
Inconsistent results of multiple queries from vmselect

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#2832]
**Version**
vmselect: v1.69.0-cluster
vminsert: v1.69.0-cluster
vmstorage: v1.69.0-cluster

vmagent:  v1.72.0
vmalert: v1.72.0

prometheus: 2.35.0

**Issue description**
We deployed a prometheus Deployment with 2 replica  and  a vmagent/vmalert Deployment  also with 2 replica  for scraping  same targets in a  k8s cluster. And all timeseries were written to two isolated tenant in vminsert.  Then, We start to query a same metric from the two tenant's datasources.  The vmstorage and vmselect enabled deduplicate with dedup.minScrapeInterval 15s, that equals with prometheus and vmagent/vmalert scrape/evaluate interval.  The vminsert args replicationFactor had been set to 2.

When we queried a metrics many times  from the vmagent/vmalert tenent, appeared an expected  consistent results .
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/28862139/177367740-594793f7-c11d-4c57-8a11-aabd46871536.png">

But we found some inconsistent results when queried some identical metrics many times from the prometheus tenant.
<img width="1308" alt="wecom-temp-682c66e4d1f80df5702a78726d248a7b" src="https://user-images.githubusercontent.com/28862139/177367009-e430d837-9e2a-49ee-bfca-7cb27d140548.png">

It confused us for a long time. We don't know reasons. We have attempted to query  many metrics and always got inconsistent results. 
As an aside, when we scale down the prometheus Deployment with 1 replica, all inconsistent results disappeared.  We consider that may be a bug or some error configs. Could anyone help to analyze the question or give us any advice?  If need other information, we have a pleasure to provide.

**Comment by valyala** [comment]
It is likely Prometheus replicas write samples for the configured recording rules with identical timestamps. E.g. the first Prometheus replica generates samples for `instance:node_cpu:rate:sum` metric with the same timestamps (with millisecond precision) as the second Prometheus replica, but with different values (for instance, if Prometheus replicas evaluate recording rules at slightly different times, but store them with identical timestamps). `vminsert` stores samples for every time series in two distinct `vmstorage` instances according to `-replicationFactor=2` at `vminsert`. This means that `vmselect` needs to de-duplicate samples for the same time series obtained from multiple `vmstorage` nodes during queries. If these samples contain the same timestamp, but different values, then the `vmselect` can return different graphs during repeated execution of the same query because [de-duplication in VictoriaMetrics](https://docs.victoriametrics.com/#deduplication) leaves arbitrary value for samples with identical timestamps (with millisecond precision), which belong to the same time series. The same issue can affect identically configured `vmagent` instances as well. The solution is to pass different values to `-promscrape.cluster.name` command-line flag per each identically configured `vmagent` replica. See [these docs](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets) for details.

It looks like identically configured `vmalert` replicas usually evaluate recording rules at different times, so the de-duplication consistently leaves samples from a single `vmalert` replica. @hagen1778 , could you confirm this?

Unfortunately I'm unaware of reliable workaround for this issue for Prometheus other than rewriting queries in recording rules, so they return more stable results when executed multiple times at around the same time. For example, it isn't recommended to use [irate](https://docs.victoriametrics.com/MetricsQL.html#irate), since it tends to return jumpy results - see [this article](https://valyala.medium.com/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832) for details. It is better to use `rate()` instead.

**Comment by hagen1778** [comment]
> @hagen1778 , could you confirm this?

No. By default, vmalert HA pairs will produce samples with identical timestamps. Added clarification here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2838

**Comment by okzheng** [comment]
Thanks for your detailed reply. @valyala  According to the above explanation, I have understood that each of two vmstorages left a different sample with same timestamp but with different value when samples need to deduplicated.
