### ISSUE TITLE
assisted merges result in vmstorage slow query and ingest

### ISSUE THREAD

**Issue by eddietanshuo** [VictoriaMetrics/VictoriaMetrics#2836]
**Describe the bug**

Hello @valyala, another issue need your help.  One of our vm cluster had searching and slow ingesting problem this noon.

> slow ingesting  
![image](https://user-images.githubusercontent.com/103412360/177540917-0413d1d1-413c-407e-9099-b96e9feed07c.png)

> slow searching
![image](https://user-images.githubusercontent.com/103412360/177541660-cdd5ac6a-ea76-4d0a-b89c-e41a7f0a07a3.png)

We also observed that the load avg. rose apparently:

![image](https://user-images.githubusercontent.com/103412360/177541971-c7b2c874-82b0-4541-9ec5-8967d7921c9b.png)

After some research, we find the parts number was high and triggered a assisted merge:

![image](https://user-images.githubusercontent.com/103412360/177542227-99e12369-9876-487c-aeb3-1fee50eb81a0.png)

The parts counter during the time range is:

![image](https://user-images.githubusercontent.com/103412360/177546473-ca5d38f9-e61e-4e3d-9173-fb3e618bacaa.png)
 

**What we expect**
It's harmful to block all searches till the parts merge done.
Since the parts merging should continue for more than 60s, and if the merge small parts lead to merge big parts, the duration will become more than 30 minutes. During this time, all tcp connections from vmselect will be blocked and released, which could result in conn dial again and again. Further more, vmselect will wait for n-m vmstorage nodes return results, if one of vmstorage node is doing merge, all query will be hold during a very long time. 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/741dd4727348997bb7b5183992ef45030208110a/lib/storage/partition.go#L562-L575

We have a very high ingesting rate, it's possible to have more than 256 parts sometimes. We hope victoriametrics could have a relatively more flexible strategy to disable this lock feature. For example, add an option to allow search during merging.

**Comment by valyala** [comment]
VictoriaMetrics prioritizes data ingestion over queries when it has no enough resources (CPU and disk IO) for processing the current workload. This strategy works better than prioritizing queries over data ingestion under resource shortage, since otherwise queries will be executed over increasingly stale data.

Note that the data ingestion prioritization is enabled **only under resource (mostly CPU and/or disk IO) shortage** for the current workload. If VictoriaMetrics has enough free resources for the current workload, then it processes both data ingestion requests and query requests without any prioritization.

If VictoriaMetrics has enough free CPU and disk IO for the current workload, then it merges data in background - see [these docs](https://docs.victoriametrics.com/#storage) for details. If it has no enough free resources for background merges, then the number of parts on disk grows until the [hardcoded limit](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/01f55bc66b3c5e4e600ffe8754b27041b2beda5b/lib/storage/partition.go#L50) is reached. After that VictoriaMetrics starts merging parts directly during data ingestion requests in order to keep the number of parts on disk under control. This is named as `assisted merge`. The limit is currently set to 256 parts per partition. While it is possible to raise the limit, this will result in higher slowdown during queries, since VictoriaMetrics checks all the parts on every query.

If you encounter non-zero rate for assisted merges (e.g. `rate(vm_assisted_merges_total) > 0`), then it is likely VictoriaMetrics has no enough resources for the current workload. The following solutions exist:
- To identify the bottleneck (this is most likely CPU or disk IO) and add more resources to VictoriaMetrics.
- To reduce the workload.

**Comment by jiekun** [comment]
Close as answered.
