### ISSUE TITLE
Whether limit parameters can be passed on api/v1/series API

### ISSUE THREAD

**Issue by thislyc** [VictoriaMetrics/VictoriaMetrics#2841]
**Is your feature request related to a problem? Please describe.**
Api/v1/series API returns too much data at one time. Can you add a limit parameter to control the number of returns or add paging parameters

**Describe the solution you'd like**
add a limit parameter to control the number of returns or add paging parameters

**Comment by dmitryk-dk** [comment]
Hi @thislyc ! Thank you for you request, but currently you can define ```start```  and  ```end``` requests params and limit number of series. 
By default, VictoriaMetrics returns time series for the last 5 minutes from /api/v1/series. 
Also you can define flag ```-search.maxSeries``` which will limits the number of time series, which may be returned from [/api/v1/series](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers). This endpoint is used mostly by Grafana for auto-completion of metric names, label names and label values. Queries to this endpoint may take big amounts of CPU time and memory when the database contains big number of unique time series because of [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate). In this case it might be useful to set the ```-search.maxSeries``` to quite low value in order limit CPU and memory usage.

**Comment by thislyc** [comment]
> Hi @thislyc ! Thank you for you request, but currently you can define `start` and `end` requests params and limit number of series. By default, VictoriaMetrics returns time series for the last 5 minutes from /api/v1/series. Also you can define flag `-search.maxSeries` which will limits the number of time series, which may be returned from [/api/v1/series](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers). This endpoint is used mostly by Grafana for auto-completion of metric names, label names and label values. Queries to this endpoint may take big amounts of CPU time and memory when the database contains big number of unique time series because of [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate). In this case it might be useful to set the `-search.maxSeries` to quite low value in order limit CPU and memory usage.

Hi @dmitryk-dk ,Thank you for you reply,but I'm sure I used the `start` and `end` requests params parameters，because the number of relevant indicators is still large, I think if i can use the match[] parameter as the search and the limit parameter as the limit, it is equivalent to realizing a simple search function.

**Comment by f41gh7** [comment]
It seems, that limit is not applied properly. Instead of limiting output, it limits maxSeries value and return error on reaching it.

 Affected APIs:
1) /api/v1/series
2) graphite/tags/autoComplete/tags

 Maybe others.

**Comment by f41gh7** [comment]
FYI @dmitryk-dk

**Comment by f41gh7** [comment]
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4339

**Comment by valyala** [comment]
FYI, the `limit` query arg for [/api/v1/series](https://docs.victoriametrics.com/#prometheus-querying-api-usage) should work properly starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Now the `limit` number of items is returned from the API if it returns more than the `limit` entries. Previously it was returning `limit exceeded error` in this case.
