### ISSUE TITLE
vmalert:  allow spliting rules among multipe instances

### ISSUE THREAD

**Issue by loyispa** [VictoriaMetrics/VictoriaMetrics#2872]
**Is your feature request related to a problem? Please describe.**
The current vmalert high-availability solution is enough for most of users , however it maybe a potential problem for the user who has a lot of rules to execute. It will be good if we have a simple but effective mechanism to spread the rules among multipe instances.  For my case, we need executing 8,000+ rules per 30 seconds in production, and the amount is still continuously increasing.

**Describe the solution you'd like**

Just like vmagent [does](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets) . I've polished a pull request, and hope it could be accepted.

**Describe alternatives you've considered**

**Additional context**

**Comment by hagen1778** [comment]
Hello! Thanks for request and pull request!
Vmalert component doesn't do a lot of work. It just runs queries and writes results back. The most of the work is always on the datasource side, which processes received queries. Hence, I've never expected vmalert to be under heavy load or require clustering mode. So my question is the following: why exactly you need to cluster vmalert? what is the bottleneck you're facing with it?

I also have concerns regarding sharding by groups. There are no guarantees groups are equally complex (have similar number of rules). Usually, people split rules in groups using following categories: application or component, type: alerting or recording rules, evaluation intervals. Hence, adding a cluster mode by groups may result into vmalert shards with different type of loads.
Sharding by rules is also not ideal, because it breaks rules chaining where rule B depends on results from rule A. If these rules will end up on different shards, the chaining will become very unreliable.

**Comment by loyispa** [comment]
@hagen1778   Thanks for your kindly replying. 
I just begin transfering to the new vm architecture, and Vmalert needs about 400 CPU utilization on the almost empty storage.  I'm a little worried about what extent CPU will grow with data ingesting.  Maybe we should put this idea aside before i collect enough information.  
Another minor problem is  that vmalert would use 4~5 times cpu higher than  than ususlly while reloading rules (i.e. receive -HUP signal), and last for about 10 seconds. Whether clustering could refine the problem to some extent?

**Comment by hagen1778** [comment]
>  Vmalert needs about 400 CPU utilization

is it possible to collect CPU profile from one of such instances? See how to do it:
```
curl http://0.0.0.0:8880/debug/pprof/profile > cpu.pprof
```
The command for collecting CPU profile waits for 30 seconds before returning.

Would be also great to collect CPU profile during config reloading. Thanks!

**Comment by loyispa** [comment]
Reloading issue may be affected by lots of rule files. It's now about twice cpu than normal after merging part of rules file.
[pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9167201/pprof.zip)

**Comment by hagen1778** [comment]
Thanks! It is helpful. From the profiles it seems like the most of CPU resource is consumed by garbage collection. Could you please also collect profile for objects allocation in vmalert's memory? Try the following command:
```
go tool pprof -alloc_objects  http://localhost:8880/debug/pprof/heap
```
Although, what is the exact version of vmalert you're collecting profiles from?
Thanks!

**Comment by loyispa** [comment]
Sorry for the late reply. Here is the profile:
[heap.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9186487/heap.pb.gz)

I'm using the latest release version:  `vmalert-20220714-170947-tags-v1.79.0-0-gd3116d986`

**Comment by hagen1778** [comment]
Hello! Sorry for the late reply - I was away last 2w.
I've checked the profile and it doesn't show what I'm looking for. According to it, there is not that much of allocations so it can cause any harm. So I tried to reproduce "heavy" load on vmalert locally. I've configured ~500 alerting rules within 20 groups, each with 3s eval interval. This config generates 100 queries per second to my local VM storage and produces ~600 active alerts. I didn't notice any CPU load higher than 5%. The CPU and mem profile also didn't show any hot places in the code.
It could be that attached profiles were taken not in the right moment, or not from the right processes. Wdyt about having the call where we can look together at what happens? Let me know if that an option by sending the invite to roman @ victoriametrics.com.
Thanks!

**Comment by Haleygo** [comment]
@hagen1778  
I'd like to bring some thoughts about vmalert cluster sharding:
1. Right now, vmalert support [HA mode](https://docs.victoriametrics.com/vmalert.html#ha-vmalert), and [deduplication](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication) is needed on remoteWrite side. But the value for `-dedup.minScrapeInterval` can be tricky if groups got different interval like 30s and 60s. Sharding according to interval might help here.
2. With multiple vmalert, all of them will do evaluation for all the group, put multiple times query pressure on vmcluster side, and those results will be "wasted" then because of deduplication.
>There are no guarantees groups are equally complex (have similar number of rules). Usually, people split rules in groups using following categories: application or component, type: alerting or recording rules, evaluation intervals. Hence, adding a cluster mode by groups may result into vmalert shards with different type of loads.

Maybe it's not about average vmalert's load cause normally vmalert doesn't consume too much. But with sharding, users can  reduce load on vmcluster side if they want HA vmalert.
