### ISSUE TITLE
need parallel query in vm-select and vm-storage to reduce query latency

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2886]
look this pic:
![image](https://user-images.githubusercontent.com/4198375/179721300-08ae0134-1dc0-4592-a918-a6a779127510.png)

if those two expression can run parallel, the latency will reduce ablout 30%.

----
and, in vm-storage:
see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2d1366353cc320712328088670bb95f4169c9d02/lib/vmselectapi/server.go#L869
there is only one coroutine to query metric data. add more coroutines might be faster.
thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for the feature request!

VictoriaMetrics tries optimizing binary operations `q1 op q2` by executing `q1` and then applying common labels from `q1` time series to `q2` before its execution according to [series matching rules](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching). This allows reducing the number of time series selected by `q2` in practical cases. For example, if `foo` in `foo / bar` matches time series with common label `x="y"`, then VictoriaMetrics converts `bar` to `bar{x="y"}` before execution. This means that `foo` and `bar` cannot be executed in parallel in this case. But there are cases, when parallel execution is possible, when common labels cannot be pushed from one side of the binary operation to another side like in the `sum(...) / sum(...)` case.

The commit f992f96a88f1b381a9ac6830eab01c5d793213f5 enables parallel processing of both sides of binary operator in cases when common labels cannot be pushed down from one side of the binary operator to another side. Note that VictoriaMetrics components must have enough free resources for executing both sides of binary operator in parallel in order to reduce execution times. Otherwise the resulting query execution time will be the same or bigger comparing to the case with sequential execution of both sides of binary operator.

The commit f992f96a88f1b381a9ac6830eab01c5d793213f5 will be included in the next release of VictoriaMetrics. In the meantime it is possible to build `vmselect` from this commit and verify whether it improves execution times for your queries. See [how to build vmselect from source code](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

> there is only one coroutine to query metric data. add more coroutines might be faster.

This loop locates data blocks on disk at `vmstorage` and sends the located data blocks to `vmselect`. This loop can have the following bottlenecks:

- CPU for locating data block on disk
- disk read IO for reading the located data blocks from disk
- network bandwidth for sending the data blocks to `vmselect`

The most likely bottleneck in this case is either disk read IO or network bandwidth. A single CPU core has little chances to be a bottleneck in this loop. So splitting the loop across multiple goroutines won't help, since it won't lift bottlenecks on disk read IO or network bandwidth.

**Comment by ahfuzhang** [comment]
thanks.
In this case, vm-storage's CPU/memory/IO_read/IO_write usage is all very low.
I think do parallel first is better, than user can set correct coroutine count to fit all kinds of resource usage.
Of course, parallel code is hard to write in vulkan mode. 
Like clickhouse, it's a good chance to add simd and jit feature to vm, and make vm speed up 10 times again.  :-)

**Comment by valyala** [comment]
FYI, VictoriaMetrics [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) supports parallel querying of the left and right side of binary operator in cases described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2886#issuecomment-1188956126). Closing this feature request as done.

As for other performance optimizations, let's open a new feature request for further discussions.

**Comment by ahfuzhang** [comment]
yyds
thanks.

**Comment by valyala** [comment]
FYI, VictoriaMetrics [v1.81.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) automatically executes [union()](https://docs.victoriametrics.com/MetricsQL.html#union) args in parallel. Previously they were executed sequentially.
