### ISSUE TITLE
Sorts the numbers wrong 

### ISSUE THREAD

**Issue by Artesfrost** [VictoriaMetrics/VictoriaMetrics#2887]
**Describe the bug**

sort
sort_by_label
sort_by_label_desc

It just sorts the numbers wrong and that's it

**Screenshots and qvery**

If i use something like this
````
sort(sum(rate(slurp_requests_duration_seconds_bucket[$__rate_interval])) by (le))
````
We can see that sorting is not working correctly
![Screenshot 2022-07-19 at 14 07 03](https://user-images.githubusercontent.com/56085856/179736277-2e1547ee-3ea8-4b79-8996-5c82f6c73328.png)
Or 
````
sort_by_label((sum(slurp_requests_duration_seconds_bucket) by (le)), "le")
````
here also
![Screenshot 2022-07-19 at 14 06 15](https://user-images.githubusercontent.com/56085856/179736195-c764c296-c3a7-4f3d-ba5e-c9507f4f2c5d.png)
````
sort_by_label_desc((sum(slurp_requests_duration_seconds_bucket) by (le)), "le")
````
![Screenshot 2022-07-19 at 14 05 56](https://user-images.githubusercontent.com/56085856/179736239-8c1156c1-b072-4531-9f9f-ec6bb3ebb508.png)

**Version**

Victoria metrics -  v1.78.0
Grafana - v9.0.2

**Comment by dmitryk-dk** [comment]
Hi @Artesfrost ! Thank you for your request! This issue is related to grafana.
You can try to change options for Y Axes in grafana side:
1. Use data format as time series bucket 
2. Change bucket bound

<img width="395" alt="Screenshot 2022-07-21 at 14 15 14" src="https://user-images.githubusercontent.com/12189570/180201975-1f4ab1d1-f530-49ea-941f-b07e89c98356.png">

**Comment by dmitryk-dk** [comment]
@Artesfrost can we close the issue?

**Comment by Artesfrost** [comment]
@dmitryk-dk  Maybe yes. But in this issue, I used panel "Heatmap (new)".
I could not check your advice, because the panel doesn't work  "Heatmap"  in grafana v9+.
I will check it in the next release grafana.
