### ISSUE TITLE
Latest Docker image is for AMD64 only and is missing ARM, etc.

### ISSUE THREAD

**Issue by scottwallacesh** [VictoriaMetrics/VictoriaMetrics#2911]
**Describe the bug**
The latest image (dated Jul 25, 2022 at 8:44 am, uploaded by [denysholius](https://hub.docker.com/u/denysholius) (@denisgolius)) is only for `linux/amd64` and is missing the `linux/arm/v7` and `linux/386` architectures.

**To Reproduce**
Download the `latest` tag and attempt to run on non-AMD64 architecture.

**Expected behavior**
A `latest` image should be able to run on, say, `linux/arm/v7`.

**Comment by denisgolius** [comment]
Hi @scottwallacesh !
We recommend to use a tag that identifies a particular version of VictoriaMetrics in docker because it prevent your environment from fails and do not use `latest` tag because it can contains not production version with some test features. See https://codefresh.io/blog/docker-tagging-strategies-deploying-production/

So try to pull `victoriametrics/victoria-metrics:v1.79.0` - it should works perfectly.

**Comment by scottwallacesh** [comment]
Okay but previously `latest` had all three architectures and this is a departure from what was done previously.

One might argue that there should be a `stable` tag or, perhaps, a `nightly` or `dev` tag for unstable releases or ones that contain test features.

**Comment by AlekSi** [comment]
The advice to use a version tag is a good one, but that does not mean that `latest` can be broken :)

**Comment by mvadu** [comment]
I agree with @denisgolius  on using a specific version, but then its another maintenance expected out of each user. If they forget to upgrade fairly regularly they will be running many versions behind. Shouldn't the `:latest` be more of what is current production ready version and use specific `dev` or `test` tags to target specific testcases?

**Comment by valyala** [comment]
FYI, the `latest` tag now should point to the upcoming `v1.79.1` release.

> Shouldn't the :latest be more of what is current production ready version and use specific dev or test tags to target specific testcases?

I think it is better to have the `stable` tag for the latest stable release, while continue using the `latest` tag for the latest builds from the main branch, which can contain unpolished features and/or bugs.

But the `stable` tag isn't a good solution yet, since you never know which particular release you run from this tag and when you need to upgrade the docker image from this tag.

**Comment by valyala** [comment]
The next releases of VictoriaMetrics will be published at DockerHub with the following `*stable` image tags:

* `stable` - all the open source VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html)
* `cluster-stable` - all the open source [cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) - `vminsert`, `vmselect` and `vmstorage`
* `enterprise-stable` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html), [vmgateway](https://docs.victoriametrics.com/vmgateway.html), [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html).
* `enterprise-cluster-stable` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) [cluster components](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) of VictoriaMetrics - `vminsert`, `vmselect` and `vmstorage`.

See also [this comment regarding latest image tags](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3505#issuecomment-1360120882).

Closing this issue as done.
