### ISSUE TITLE
vmagent(v1.76.1 =>v1.79.0) how <ec2_sd_config> works in china region

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#2917]
Hi，I am using vmagent on ec2 in china region, and I found that <ec2_sd_config> can't work because of aws endpoint.

The ec2 endpoint in China region is different from ec2 endpoint in global.

So how can I pass the china region ec2 endpoint to vmagent？

I am updated vmagent to v1.79.0.

vmagent config
![image](https://user-images.githubusercontent.com/73687556/181412693-e8a478e7-8b6f-4120-be36-61bab8fb00d9.png)

EC2 discovery
![image](https://user-images.githubusercontent.com/73687556/181412752-1848b45a-8b86-4b33-8e91-8588f006f853.png)

**Comment by valyala** [comment]
@f41gh7 , could you help with this question?

**Comment by valyala** [comment]
It has been appeared that `vmagent` was ignoring the `endpoint` option in [ec2_sd_configs](https://docs.victoriametrics.com/sd_configs.html#ec2_sd_configs) since [v1.77.0](https://docs.victoriametrics.com/CHANGELOG.html#v1770). This has been fixed in the commit f2816ef03142a7a1106917c7829a59830efcd8f6 . This commit will be included in the next release. In the meantime it is possible to build vmagent from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether it properly accepts `endpoint` option in `ec2_sd_configs` section.

**Comment by tripitakav** [comment]
Thank you. I'll try

**Comment by valyala** [comment]
@tripitakav , the bugfix for this issue has been included in [vmagent v1.79.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@tripitakav , feel free re-opening the issue if `vmagent v1.79.2` still doesn't handle properly the `endpoint` option at `ec2_sd_config`.
