### ISSUE TITLE
Upgrade from v1.30.5 to v1.79.0

### ISSUE THREAD

**Issue by lukyanov** [VictoriaMetrics/VictoriaMetrics#2927]
I want to upgrde VictoriaMetrics (using official Docker image) from v1.30.5 to the latest version (v1.79.0). Could you help me to understand if it is safe to do so?

**Comment by dmitryk-dk** [comment]
Hi @lukyanov ! Thank for your question. Yes it is safety, but you have to be prepared for some things:
1. significantly more CPU may be used initially if deduplication has been configured
2. you can roll back if you updated from a version older than 1.30
2. vmselect may not respond correctly during the cluster update, the protocol version has changed there, after updating the storage, you need to update the version of the insert and select

Also take a look into vmalert if you are using it.
since 1.75 there is a breaking change to vmalert’s API.
