### ISSUE TITLE
`-search.maxUniqueTimeseries` cannot be set for vmselect

### ISSUE THREAD

**Issue by djluck** [VictoriaMetrics/VictoriaMetrics#293]
**Describe the bug**
When attempting to pass `-search.maxUniqueTimeseries` to vmselect, it fails with the error "flag provided but not defined".  Also the `/metrics` endpoint does not include this flag in the `flag` metrics.

**To Reproduce**
Start vmselect and pass `-search.maxUniqueTimeseries=[some_number]`.

**Expected behavior**
It should work :)

**Version**
`vmselect-20200121-153055-tags-v1.32.6-cluster-0-g9eaa2ab8`

**Additional context**
For large datasets I'm hitting the error `the number or matching unique timeseries exceeds 300000; either narrow down the search or increase -search.maxUniqueTimeseries`, this is why I'm trying to set this flag.

**Comment by valyala** [comment]
`-search.maxUniqueTimeseries` flag must be set at `vmstorage`. It doesn't exist at `vminsert`.

**Comment by djluck** [comment]
Thanks for the explanation. Sorry for wasting your time!

**Comment by valyala** [comment]
No problems. I think this is due to lack of good documentation for [cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md). [Single-node version docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md) are much better in this sense. This should be eventually fixed.
