### ISSUE TITLE
why every select  always need to query all vmstorage Node

### ISSUE THREAD

**Issue by z7658329** [VictoriaMetrics/VictoriaMetrics#2933]
why every select request， always need to query all vmstorage Node？

**Comment by YuriKravetc** [comment]
Hi,
Every select request is sent to `vmselect` first, then `vmselect` queries all `vmstorage` nodes because `vmselect` does not know where the specific (required/queried) time series are stored.

**Comment by kannan-rafay** [comment]
Hi, wouldnt this have over-ahead to all storage nodes in the cluster when there is more concurrent queries ? just curious on how this model would scale when we have 10s /100s of storage nodes for bigger saas apps

**Comment by YuriKravetc** [comment]
Hi @kannan-rafay,
It will scale just fine. The process of searching which vmstorage contains required data does not consume too many resources. 
Please refer to this scalability doc for more details:
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-resizing-and-scalability

**Comment by kannan-rafay** [comment]
thanks for the link , could you please give some insights on how vmstorage searching happens when vmselect is queried .

**Comment by YuriKravetc** [comment]
@valyala Hi, can you help with details for the question above, please?

**Comment by sharninder** [comment]
@kannan-rafay I'm not a Victoria Metrics developer but I can answer that yes there is an index and its created/updated when a series hits a particular vmstorage node.

**Comment by kannan-rafay** [comment]
fine thank you guys  just happened to look into the code , looks like vmselect sends the request to all the vmstorage instances in the cluster, vmstorage has indexdb to look up the series data , well  a metric will not be part of all the vmstorage instances in a cluster however vminsert always tries to write a metric to one vmstorage (by the docs), or  may be to N when earlier instances arent available for some reason , so with that understanding , likely maximum 20% ( hypothetical number) of vmstorage instances will have a specific metric data  , say in a cluster of 100 vmstroage instances , 80 of them will just receive the request to just lookup the unavailable series in indexdb for the requested metric, does this bring in any limitation on concurrent queries in a cluster ? this would help us to model our cluster accordingly

**Comment by valyala** [comment]
> does this bring in any limitation on concurrent queries in a cluster?

`vmselect` queries all the `vmstorage` nodes in the cluster on every incoming request. This scales well, since `vminsert` evenly spreads incoming time series among available `vmstorage` nodes in the cluster. This means that the required work for locating the needed time series is evenly spread among available `vmstorage` nodes in the cluster. Adding more `vmstorage` nodes to the cluster reduces per-`vmstorage` load and increases cluster capacity for the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series), the data ingestion rate and the maximum available queries' rps.

There is a practical limit on the number of `vmstorage` nodes in a single cluster. This limit is related to the network bandwidth. Higher network bandwidth allows building VictoriaMetrics clusters with bigger number of `vmstorage` nodes. VictoriaMetrics cluster capacity for both data ingestion and queries rps should scale almost linearly by up to 50-100 `vmstorage` nodes.

Note that every request is processed by a single `vmselect` node, e.g. `vmselect` requests all the needed data from all the `vmstorage` nodes and then processes the data on all the available CPU cores at a single `vmselect` node. This means that the performance for heavy queries, which process billions of samples over millions of time series, can be limited by the number of CPU cores per `vmselect` node. See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning for details.

If scalability limits of a single VictoriaMetrics cluster are hit, then the way forward is to run multiple VictoriaMetrics clusters behind tenant-aware router, which could route data and requests from a particular tenants to a particular cluster. See, for example, [vmauth](https://docs.victoriametrics.com/vmauth.html) and [vmgateway](https://docs.victoriametrics.com/vmgateway.html).

**Comment by z7658329** [comment]
> fine thank you guys just happened to look into the code , looks like vmselect sends the request to all the vmstorage instances in the cluster, vmstorage has indexdb to look up the series data , well a metric will not be part of all the vmstorage instances in a cluster however vminsert always tries to write a metric to one vmstorage (by the docs), or may be to N when earlier instances arent available for some reason , so with that understanding , likely maximum 20% ( hypothetical number) of vmstorage instances will have a specific metric data , say in a cluster of 100 vmstroage instances , 80 of them will just receive the request to just lookup the unavailable series in indexdb for the requested metric, does this bring in any limitation on concurrent queries in a cluster , guess it will ? any POC on this case ? this would help us to model our cluster accordingly

so  when add a new vmstoreage into storage cluster, how  vmselect detect the new vmstorage? and i wonder if some vmstorages offline, is there a health check in vmselect, to maintain those vmstorages

**Comment by z7658329** [comment]
> > fine thank you guys just happened to look into the code , looks like vmselect sends the request to all the vmstorage instances in the cluster, vmstorage has indexdb to look up the series data , well a metric will not be part of all the vmstorage instances in a cluster however vminsert always tries to write a metric to one vmstorage (by the docs), or may be to N when earlier instances arent available for some reason , so with that understanding , likely maximum 20% ( hypothetical number) of vmstorage instances will have a specific metric data , say in a cluster of 100 vmstroage instances , 80 of them will just receive the request to just lookup the unavailable series in indexdb for the requested metric, does this bring in any limitation on concurrent queries in a cluster , guess it will ? any POC on this case ? this would help us to model our cluster accordingly
> 
> so when add a new vmstoreage into storage cluster, how vmselect detect the new vmstorage? and i wonder if some vmstorages offline, is there a health check in vmselect, to maintain those vmstorages

![image](https://user-images.githubusercontent.com/5474723/183802355-77fd8669-abfe-48f4-b048-8dc102eec1e3.png)

when add a new vmstorage, should restart all vmselect and vminsert nodes.... Why is it designed like this？

**Comment by hagen1778** [comment]
> so when add a new vmstoreage into storage cluster, how vmselect detect the new vmstorage?
It does not. You need to update the vmselect configuration in order to add a new vmstorage node to the list.

>  i wonder if some vmstorages offline, is there a health check in vmselect, to maintain those vmstorages
if one of the storages is offline vmselect will detect that and response to the client will be marked as `partial` - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability

**Comment by valyala** [comment]
> when add a new vmstorage, should restart all vmselect and vminsert nodes.... Why is it designed like this？

The list of `vmstorage` nodes in the cluster must be passed explicitly to all the `vmselect` and `vminsert` nodes via `-storageNode` command-line flag. This design decision serves the following purposes:

- It simplifies debugging of the cluster. If something goes wrong, operator knows for sure the exact list of `vmstorage` nodes, which are visible to every `vmselect` and `vminsert` node in the cluster, since the list is explicitly passed to every `vmselect` and `vminsert` node at startup and cannot be changed after that.
- It allows building flexible cluster setups. For instance, it allows running multiple groups of `vmstorage` nodes with different configs such as [retention](https://docs.victoriametrics.com/#retention), [deduplication](https://docs.victoriametrics.com/#deduplication) or [downsampling](https://docs.victoriametrics.com/#downsampling) in a single cluster. Then multiple groups of `vminsert` nodes can write data to a particular group of `vmstorage` nodes, while `vmselect` nodes can query the global data from all the `vmstorage` nodes. At the same time, another groups of `vmselect` nodes can query the data only from the specified group of `vmstorage` nodes.

See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/270

**Comment by Howie59** [comment]
if we have multiple vmstorage nodes and one unavaliable, vmselect still query all nodes, which will lead to long query(refer barrel effect)

**Comment by valyala** [comment]
> if we have multiple vmstorage nodes and one unavaliable, vmselect still query all nodes, which will lead to long query

`vmselect` doesn't wait for `N-1` slowest `vmstorage` nodes where `N` is the value of `-replicationFactor` command-line flag passed to `vmselect`. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/711 .

**Comment by jiekun** [comment]
Many helpful comments here. Thank you for all your input. I think the original question is answered so let me close this issue.
