### ISSUE TITLE
some data is missing when calling `/metrics`

### ISSUE THREAD

**Issue by jaehleeee** [VictoriaMetrics/VictoriaMetrics#2936]
I used cluster version of victoriaMetrics. and also want to use grafana dashboard from `https://grafana.com/grafana/dashboards/11176.`

version is 1.69

But there is some missing data, for example `vm_data_size_bytes` or `vm_rows` in grafana dashboard.
I think the reason is no such data in `/metrics` page. (Of course, there are many data in the page except `vm_data_` or `vm_rows`)

So I want to ask how to get that data.

**Comment by YuriKravetc** [comment]
Hi,

Please elaborate what are you using to scrape this metric?
Also what datasource is set for this dashboard?

**Comment by jaehleeee** [comment]
@YuriKravetc 

> Please elaborate what are you using to scrape this metric?

I don't know how to answer that exactly.
I think I used vm-agent to scrape and set some prometheus scrape config such like that.

```
"-promscrape.config=/prometheus.yml",
...

---
...
prometheus.yml: |
      global:
            scrape_interval: 1m
            evaluation_interval: 1m
      
      scrape_configs:
        - job_name: vm_metrics
          metrics_path: '/metrics'
          static_configs:
            - targets: ["insight-vm-insert:8480", "insight-vm-select:8481", "insight-vm-storage01:8482", "insight-vm-storage02:8482", "insight-vm-storage03:8482"]

```

> Also what datasource is set for this dashboard?

Data source is vm-select.
`http://insight-vm-select/select/0/prometheus`

**Comment by YuriKravetc** [comment]
Can you check for this metric in Grafana explore, please?

![image](https://user-images.githubusercontent.com/30324382/183069347-a746ddd7-c62f-4d95-bfa0-a2aa1e2c24ce.png)

**Comment by jaehleeee** [comment]
@YuriKravetc 
What things do I have to check?
There are no metrics, vm_rows and vm_data_size_bytes.

**Comment by YuriKravetc** [comment]
I have tested it and there seems to be no issues with this metric visibility.
Simply put - for your case there are 2 possible reasons:
1. Misconfiguration on the scraping part - this metric is not scraped at all due to misconfiguration.
2. Incorrect datasource. 

If you are using vmagent to scrape this metric from vmstorage - it should be scraped and shown correctly.
If you check the `/metrics` endpoint on vmstorage it should be visible there.
(You can do it by using vmui of vmagent -> targets -> vmstorage -> responce.

Can you make a screenshot of datasources in Grafana explore and the targets response from vmagent?

![image](https://user-images.githubusercontent.com/30324382/183075335-589e7044-a3d1-4d7a-90c0-01f82c67e630.png)

**Comment by jaehleeee** [comment]
@YuriKravetc 
Thank you for kind answer.
I confirmed vm metrics about row and data from stroage(`/metrics`). (but there is no metrics about rows and data from agent`/metrics`)
I think it is scaping issue of agent.
I will change scraping config.

Is there any modification point of my vm-agent scrap config I wrote in comment above?

**Comment by jaehleeee** [comment]
@YuriKravetc 
When I call `http://vm-agent:8429/targets`, then I got correct response that I configure modules like vm-storage, vm-insert, vm-select.

**Comment by hagen1778** [comment]
Hi @jaehleeee! 
It could be that you're using recent dashboard revision with older cluster version, so some metrics which are expected to be dsiplayed on dashboard aren't yet present in the cluster.
Please, see the revision list for dashboard and pick the one which corresponds to your cluster version. If your cluster is of 1.69 version, then you need dashboard revision 16: `Overview for cluster VictoriaMetrics v1.64.0 or higher`

**Comment by jaehleeee** [comment]
@hagen1778 
Thank you for your help.
I have changed garfana dashboard revisions that you recommended.
But there are some issues about dashboard. 
When I change time range, some pannels or charts are not working. Is it ok?

**Comment by hagen1778** [comment]
Hello @jaehleeee! What is exactly meant by `not working`? Are they showing NoData or an error?
If NoData is shown, it is likely data is missing for selected filters in the top panel in Grafana (you could have selected specific instance in filters, which didn't exist yet for picked time range). Or it could be that there are just no metrics in configured datasource.
If you're getting an error - please check its text in order to understand why it is returned.

**Comment by jaehleeee** [comment]
@hagen1778 
Of course, I already set instances and I could get normal chart result.
But When I changed time range, then some charts are suddenly not working.

**Comment by hagen1778** [comment]
I still don't understand what `not working` means - are they're just empty or do you see an error?
If they're empty - it might be those metrics weren't collected at that time. Which specific panels arent working for you?

**Comment by hagen1778** [comment]
So it can be that data is just missing.  At which time range it happens? Does it continue to happen from now for a few days back? Which specific panels arent working for you?

**Comment by jaehleeee** [comment]
@hagen1778 
For example, `Disk Space Usage` or `Datapoint Average Size` chart in Overview row.
These charts can be shown  only in 30 minutes time range. If I extend time range to 1 hour or more, then these charts will be no data.

**Comment by hagen1778** [comment]
That is weird. It is likely something is wrong with caches or datasource itself. I suggest you follow https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results
