### ISSUE TITLE
vmagent to support scrape tenant metrics in pull mode

### ISSUE THREAD

**Issue by Fury76** [VictoriaMetrics/VictoriaMetrics#2943]
**Is your feature request related to a problem? Please describe.**
we hope that vmagent can support the ingestion of multi tenant metrics, because the data scale of each tenant is different. Some tenants are small, but they also need to deploy a vmagent instance, and high availability and redundant deployment need to be considered. The waste of resources is very serious, And increased operation and maintenance costs

**Comment by valyala** [comment]
The linked pull request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2950

**Comment by valyala** [comment]
`vmagent` [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) supports specifying `__tenant_id__` label at scrape targets in order to route metrics scraped from the target to the given `__tenant_id__`. See [these docs](https://docs.victoriametrics.com/vmagent.html#multitenancy) for details.
