### ISSUE TITLE
Upgrade/downgrade without downtime

### ISSUE THREAD

**Issue by zamazan4ik** [VictoriaMetrics/VictoriaMetrics#2944]
Hi.

After reading the documentation it is not clear for me, is it possible to upgrade/downgrade VictoriaMetrics without downtime? I found no mention in the documentation about such an option. Would be great, if you describe zero-downtime upgrade/downgrade scenario too. If it is not possible, please explicitly mention it somewhere.

Thanks in advance!

**Comment by valyala** [comment]
Single-node VictoriaMetrics cannot be restarted / upgraded or downgraded without downtime, since it needs to be gracefully shut down and then started again. See https://docs.victoriametrics.com/#how-to-upgrade-victoriametrics .

[Cluster version of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) can be restarted / upgraded / downgraded without downtime if the following conditions are met:
- If every component of the cluster - `vminsert`, `vmselect` and `vmstorage` - has at least 2 instances.
- If the cluster has enough compute resources (CPU, RAM, disk IO, network bandwidth) to perform rolling restart of all its components.
- If the version used for upgrade / downgrade is compatible with the currently running version. The [CHANGELOG](https://docs.victoriametrics.com/CHANGELOG.html) contains compatibility notes for the published releases.

See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#updating--reconfiguring-cluster-nodes for details on cluster upgrade.
