### ISSUE TITLE
vmalert evaluate incorrect alert when using absent

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#2976]
**Describe the bug**
When we use absent at a slow pulled metric for monitoring the metric missing, the vmalert triggered an incorrect alert.
alert rule:
```
expr: absent(Mongodb_CPUUtilization) == 1
for: 10m
```
We expect that if the metric was missing for 10 min, the vmalert would reported an alert.
The vmalert reported the rule was triggered when the rule was added to the vmalert.  But when query in grafana with vmcluster datasource, the metric was not missing. It just was scraped from a target with a delayed timestamp.  And the action was inconsistent with Prometheus which also evaluated with the same rule but not triggered alerts.
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/28862139/184312045-6fe0228e-3092-4150-9106-1a76af581007.png">

When we replace to using absent_over_time, it returned to a correct result without any alerts.
```
expr: absent_over_time(Mongodb_CPUUtilization[10m]) == 1
```
However, we still guess it may be a bug for the function absent, so report to here.

flag:
evaluate_interval: 30s
scrape_interval:60s
version:
every vm component with version v1.79.2

**Comment by hagen1778** [comment]
> The vmalert reported the rule was triggered when the rule was added to the vmalert. 

Are you saying that once you added the mentioned alerting rule, vmalert fired the alert without waiting for 10m?

> And the action was inconsistent with Prometheus which also evaluated with the same rule but not triggered alerts.

How data goes into VM? Is it Prometheus pushing data via remote-write? Do you observe any delays in data delivery between Prometheus and VM?

**Comment by okzheng** [comment]
> Are you saying that once you added the mentioned alerting rule, vmalert fired the alert without waiting for 10m?
The meaning was that vmalert fired the alert for the rule after 10m. But Prometheus did not trigger alerts according the rule, and the rule was still in inactive state.

We deployed vmagent/vmalert and Prometheus for scraping same targets and evaluating same rules. TimeSeries have been written to different tenants in a vmcluster as datasource.
when querying the alert rule expr, two datasources return same results as the above picture. It seems vmalert had a strange evaluation for the rule.

**Comment by hagen1778** [comment]
Hm, vmalert doesn't do anything query specific. All types of queries are identical: they either return series in response or not. It doesn't check response values, that's it.
What is happening, I think, is how Prometheus and VictoriaMetrics detect stale series. 

Prometheus always uses a const value of `5m`. If there are no samples on this interval - time series is deemed as stale.

VictoriaMetrics makes an attempt to detect interval after which time series becomes stale. It is calculated as the median of the intervals between the first 20 data points in the requested time range. In this way, VictoriaMetrics automatically adjusts the lookbehind window to detect stale series.

vmalert uses [instant API](https://docs.victoriametrics.com/keyConcepts.html#instant-query) for executing rules. This API is always executed in the one moment of time, so VM has no way to detect the staleness using the median method since it doesn't have enough data points. So in this case it falls back on the `step` param send with query. If `step` is missing, it falls back to `5m`.

`vmalert` does send `step` param when executing rule queries. The `step`, by default, is equal to `evaluationInterval` and is controlled via following command-line flag:
```
  -datasource.queryStep duration
     queryStep defines how far a value can fallback to when evaluating queries. For example, if datasource.queryStep=15s then param "step" with value "15s" will be added to every query.If queryStep isn't specified, rule's evaluationInterval will be used instead.
```
If you're wondering why `vmalert` does this adjustment - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1232.

So in this case, if you want behaviour to be consistent with Prometheus - try setting `-datasource.queryStep=5m`. However, I don't think this is the best way to solve this. The default of `5min` in Prometheus is nothing more than just a constant. The approach of checking `absent_over_time` on the range you think is tolerable for a metric to be `absent` is far more intuitive and natural.

**Comment by okzheng** [comment]
Thanks for your reply. @hagen1778 You are right. However, it will lose accuracy if setting `-datasource.queryStep=5m` than step with evaluationInterval by default. So it was still inconsistent with Prometheus?  Could I use `-search.maxLookback` for vmselect to approach the target?
In addition, because some timeseries samples always were written to vmagent with latency between 1min and 3min using remote write protocol, these timeseries would be considered a series stale. Then some alert rules based on instant values always were evaluated with none values, these were never triggered. So I configurated `datasource.lookback=3m` for vmalert to attempt to resolve the issue. Does the configuration affect evaluation about timeseries which were written within evaluationInterval?

**Comment by hagen1778** [comment]
> However, it will lose accuracy if setting -datasource.queryStep=5m than step with evaluationInterval by default.

Why? Do you observe different values when sending the same instant query at the same moment of time but with different `step` value?

> So it was still inconsistent with Prometheus?

Do you mean staleness detection? If yes, this is intentional inconsistency. It was added for supporting scenarios when data points are collect within intervals bigger than `5m`. It is also useful for detecting stale series faster. Consider the case when metric is scraped every 10s and then its host goes down. VictoriaMetrics will detect it is absent within a minute, while Prometheus will always need at least 5mins.

> Could I use -search.maxLookback for vmselect to approach the target?

Yes, it looks very similar. 

> Does the configuration affect evaluation about timeseries which were written within evaluationInterval?

Do you mean will this take effect on all queries sent by vmalert? Yes, it will. Each rule execution will be shifted by `3m` in past. In other words, all rules will be executed at `now()-3m` moment of time.

**Comment by hagen1778** [comment]
>  It means vmalert evaluates some rules with range query, for example function x_over_time. In that condition, bigger step got lower accuracy.

No. Specified `step` param for [instant](https://docs.victoriametrics.com/keyConcepts.html#instant-query) query will not affect the vector range specified in `[<dur>]`. It will only adjust how far in past VM should look for last recorded data point.
