### ISSUE TITLE
Self-collected internal metrics

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#30]
In Prometheus agnostic setup there is no way to collect internal metrics

Possible solution:
- add flag which informs application to store internal metrics to storage

**Comment by albertdb** [comment]
+1 When Prometheus is deployed in Kubernetes and VictoriaMetrics elsewhere, scraping metrics is not trivial (and redundant since they follow the path VictoriaMetrics -> Prometheus -> VictoriaMetrics).

**Comment by valyala** [comment]
FYI, self-scraping for `/metrics` page has been added in single-node version at the commit 9df5b2d1c35fb7f57ea11b42f36f05cefe48ac09 . It will be available in the next release of VictoriaMetrics.
In order to enable self-scraping, `-selfScrapeInterval` command-line flag must be set to non-zero value. For instance, `-selfScrapeInterval=10s` would enable self-scraping of `/metrics` page with 10 seconds interval.

**Comment by valyala** [comment]
The `-selfScrapeInterval` flag is available starting from [v1.32.8](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by syepes** [comment]
@valyala
So this new flag can be enabled on all three components (inter,select and storage)?

**Comment by valyala** [comment]
> So this new flag can be enabled on all three components (inter,select and storage)?

Unfortunately no. The `-selfScrapeInterval` flag is available only in single-node version of VictoriaMetrics. It is unclear how to label self-scraped metrics for cluster components, so they could be grouped and filtered later. So we decided to don't add self-scraping to cluster version. Cluster version is much more complex in setup than single-node version, so setting up Prometheus for scraping metrics from cluster components looks like not so hard additional task.
