### ISSUE TITLE
VMUI: add labels autocomplete

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3006]
**Is your feature request related to a problem? Please describe.**
Would be great if VMUI could support the label's keys and values autocompletion like Prometheus interface does.

**Describe the solution you'd like**
Auto suggest label keys and values like in the following example:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/2902918/185887573-d06dc2af-0310-4b51-813d-edb552ea2ea4.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/2902918/185887622-9062e565-bb50-405c-821b-568453974abd.png">

cc @Loori-R

**Comment by jicki** [comment]
Prometheus Func complete 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/9e87cd8d-82fb-4dd5-afb2-259802649061)

**Comment by jicki** [comment]
@hagen1778 When can this feature be implemented? Thank you very much.

**Comment by Loori-R** [comment]
Hello, @jicki! At the moment, we are developing this feature and plan to submit a PR later this week.

**Comment by hagen1778** [comment]
Hi @jicki !
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5051 has been merged today and will be likely included into the next release.
Meanwhile, you can try building it on your own by checking out the `master` branch and executing following commands from the repo's root:
```
 make vmui-build
 make vmui-update
 make victoria-metrics
```
The last command builds single-node VM binary which you can run and test the embedded vmui features.

**Comment by valyala** [comment]
While the auto-complete feature looks great overall, I have the following concerns:

1. Make sure that vmui doesn't pre-load any information related to auto-completion when the autocomplete checkbox is disabled, since loading this information can significantly increase load on both VictoriaMetrics server and the VMUI itself.
2. It looks like VMUI pre-loads the list of available metric names via `/api/v1/label/__name__/values` endpoint on the initial page load when user didn't enter anything into the `query` field. This can significantly increase load on VictoriaMetrics server if it contains large number of unique metric names (for example, if it contains millions of unique Graphite metrics). This also can significantly slow down VMUI if it needs to pre-load millions of unique metric names. It would be great to limit the number of pre-loaded metric names, label names and label values in order to prevent from high resource usage at VMUI. VictoriaMetrics accepts an optional `limit` query arg at `/api/v1/labels` and `/api/v1/label/<labelName>/values` endpoints - see [these docs](https://docs.victoriametrics.com/#prometheus-querying-api-enhancements) for details. It would be great if VMUI would set the limit to some sensible value like 1000 or 10000, and then automatically disable the auto-completion if this limit is reached in the response from VictoriaMetrics.
3. The `/api/v1/labels` and `/api/v1/label/.../values` APIs may become very slow when the database contains hundreds of millions of unique time series because of [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate) and when `match[]` query arg is passed to these APIs. This may make the auto-complete feature unusable while simultaneously significantly increasing the load on VictoriaMetrics server.
4. It is better to specify `start` and `end` query args when querying `/api/v1/labels` and `/api/v1/label/.../values`, since by default VictoriaMetrics returns values from these APIs for time series seen during the last day. See https://docs.victoriametrics.com/#prometheus-querying-api-enhancements for details.

I personally don't like the current implementation because of the issues described above. An additional issue is very low signal/noise for the information provided by the auto-complete feature, e.g. it show a ton of information to the user, and this information blinks on every keystroke and generates non-trivial load on both VictoriaMetrics server and the user's web browser, while in reality the user needs only a small fraction of the displayed auto-complete information. We need to think better on how to reduce the load on VictoriaMetrics server and web browser, while simultaneously increasing the amounts of useful information displayed to the user. For example, how about requiring the user to press some hotkey (such as `cmd+space`) in order to trigger auto-complete instead if triggering it with every keystroke.

**Comment by valyala** [comment]
[vmui](https://docs.victoriametrics.com/#vmui) gains support for advanced auto-complete for label values and label names starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done.

@Loori-R , let's add an ability to show suggestions related to the current cursor position at the query input when auto-completion is disabled and `cmd+space` is pressed.
