### ISSUE TITLE
vmselect: query takes a long time when matched data is huge

### ISSUE THREAD

**Issue by Howie59** [VictoriaMetrics/VictoriaMetrics#3017]
our production have 1000 servers, each serve has 10~30 net card, agent report data every 30s

when i query latest 10 minutes data, vmselect would take a long time 2 response(nearly 10~20s)

is there a solution?

**Comment by valyala** [comment]
@Howie59 , try trace the heavy query either via [vmui](https://docs.victoriametrics.com/#vmui) or via [http api](https://docs.victoriametrics.com/#query-tracing). The trace will show query processing places where the query spends the most time. It is recommended upgrading to [the latest available version of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it contains the best query tracing functionality.

See also [these docs on how to troubleshoot slow queries](https://docs.victoriametrics.com/Troubleshooting.html#slow-queries).

**Comment by Howie59** [comment]
ref https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2896

**Comment by Howie59** [comment]
> Hi @Howie59! Did you manage to fetch a trace for your query?

sry, vm is deployed in Intranet

**Comment by jiekun** [comment]
@Howie59 Hi. I think it's still possible to get the trace for your query, using features on VMUI. Please consider using it: https://docs.victoriametrics.com/#query-tracing

Since this issue has been staled for a long time, I'm closing it for now. Feel free to re-open it if you could provide more info.
