### ISSUE TITLE
api/v1/series returned labels beyond range time

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#3107]
After upgraded vmcluster to v1.79.2, the api `api/v1/series` returned labels beyond the time range. 
`curl http://10.1.1.5:8481/select/1/prometheus/api/v1/series?match%5B%5D=trs_engine_up%7Bjob%3D~%22trs-engine%22%7D&start=1663059757&end=1663063357`
When using the command above to query specific timeseries, the vmselect return some timeseries existed only before the start timestamp. Even if query other timeseries, the problem was not disappear.

**Comment by hagen1778** [comment]
Hello! 
The described behaviour is intentional for the sake of performance. 
`api/v1/series` does initial search in the per-day index and returns all the data which matches the filter. That's why the lowest time range for a time filter will be `1d`. 
In order to filter out results which exceed specified time range as in your example, VM has to unpack data blocks and check their headers. This step was skipped in order to improve performance of this API handler. Usually, `/api/v1/series` is used by Grafana for autocompletion. So faster it is, the better is user's experience. It also enables better caching for subsequent calls while browsing through Grafana dashboards.

**Comment by okzheng** [comment]
Grafana function label_values(metric, label)	uses the api endpoint `/api/v1/series`. If `/api/v1/series` return timeseries beyond the time range,  Grafana variables would display more unnecessary results.

**Comment by hagen1778** [comment]
This is the tradeoff we'd like to have as a default behavior. We prefer a faster response to a response with filtered series for this specific API handler. The thinking behind this is the following:
1. The faster response is the better
2. In most cases, more returned values for this handler don't affect the user's experience. 
3. Requests rounded to 1d are better cached, taking into account that users usually use 3h, 24h and 48h time ranges for dashboards.

**Comment by lgogolin** [comment]
Instead of `label_values` You can use `query_result` - that uses range query

Smal example below:

`query_result(count by (owner_name)(count_over_time(kube_pod_owner{cluster="$cluster",namespace="$namespace",owner_kind=~"$kind"}[$__range])))`

and use regex to retrieve label names:
`/"([^"]+)"/`

**Comment by aponchaut** [comment]
Hello,

How to exclude one or more "owner_name" with the "query_result" operator and the regex expression?
This is more accessible with label_values.

Regards

**Comment by parkjeongryul** [comment]
> The described behaviour is intentional for the sake of performance.
api/v1/series does initial search in the per-day index and returns all the data which matches the filter. That's why the lowest time range for a time filter will be 1d.

Hi,

VM document mentions that default time range is 5m.
If the actual time range is 1d, is the documentation wrong?

https://docs.victoriametrics.com/url-examples.html?highlight=1d#apiv1series
> By default VictoriaMetrics returns time series seen during the last 5 minutes. An arbitrary time range can be set via start and end query args.

**Comment by valyala** [comment]
@parkjeongryul , thanks for the pointer to incorrect docs! The commit e094c8e21465f1cc49558f8e1b7c60512dc7fd62 updates the documentation accordingly.

If you need obtaining the exact set of series, which received at least a single sample on the `[start..end]` time range, then instead of `/api/v1/series?start=<start>&end=<end>&match[]=<query>` you can send the following request to [/api/v1/query](https://docs.victoriametrics.com/keyConcepts.html#instant-query):

```
/api/v1/query?time=<end>&query=last_over_time(<query>[<end-start>])
```

This function uses [last_over_time()](https://docs.victoriametrics.com/MetricsQL.html#last_over_time) function over the `<end-start>` lookbehind window in order to obtaining all the time series for the given `<query>` on the `(<start> ... <end>]` time range.

For example, the `/api/v1/series?match[]=trs_engine_up{job=~"trs-engine"}&start=1663059757&end=1663063357` must be replaced with `/api/v1/query?query=last_over_time(trs_engine_up{job=~"trs-engine"}[1h])&time=1663063357`

Note that the request to `/api/v1/query` may be slower to execute than the request to `/api/v1/series`, since `/api/v1/query` needs to check whether the actual data exists on the given time range for the selected time series.

**Comment by parkjeongryul** [comment]
I found this issue in my grafana.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/25222969/231744197-07f864b7-4c9a-44db-b37c-16c6732659f8.png">

Grafana request this api internally like below.
Many dashboard use this api like namespace variable. (also default kubernetes dashboard in victoria metrics stack chart)

```
http://vmselect.admin.pgrcl1.io.navercorp.com/select/0/prometheus/api/v1/series?end=1678352097&match%5B%5D=kube_pod_info&start=1678330497
```

So when there is so many series in that day, grafana has an error for limit. (because it always get 1d time series regardless of start&end)

Anyway, Thanks for update documents.
