### ISSUE TITLE
Increase or rate function doesn't automatically adjusted reset counter value?

### ISSUE THREAD

**Issue by rightly** [VictoriaMetrics/VictoriaMetrics#3126]
**Describe the bug**
When counter value is initialized, my graph is weired.

**To Reproduce**
use bind_exporter and scrape it.

**Expected behavior**
I hope Victoria Metrics adjusts it well so that the value does not fall out on the graph.

**Screenshots**
<img width="1152" alt="GcSS0" src="https://user-images.githubusercontent.com/17899505/190983818-b355070b-3e19-4de0-86ce-93e5c8b1cd3e.png">
- green line query: sum by (instance) (increase(bind_incoming_queries_total{type="A"})/60)
- blue line query: bind_incoming_queries_total{type="A"}/60

**Version**
cluster-1.81.2

**Comment by rightly** [comment]
I understand that Prometheus behaves as follows.
In principle, the value of the counter type metric should always be monotonically increased. However, if the process is re-run, the value of that metric may be reset to zero. In particular, in the case of the Kubernetes environment, the pod is often relocated, so it is a common situation. Prometheus treats the counter metric as resetting to 0 and then rising again when the value of the counter metric decreases.

For example, suppose that the value of a counter type metric was 100 at time t1 and 40 at time t2 after 10 seconds. If you measure the change, it is measured. However, if it is a Counter metric, we calculate that the process is re-executed on any interval between t1 and t2 and the metric is reset to zero and then raised to 50. So the change is 40.

**Comment by dmitryk-dk** [comment]
HI @rightly ! Can you dd lookbehind window into your increase request 
```
sum by (instance) (increase(bind_incoming_queries_total{type="A"}[1m])/60)
```
And show graph hat you get?

**Comment by rightly** [comment]
@dmitryk-dk 
Hi !! 
This is the result of performing the query below.
It looks the same.

![image](https://user-images.githubusercontent.com/17899505/191643461-4a761f2d-36dd-4bae-a167-a34ff5524a6a.png)
- sum by (instance) (increase(bind_incoming_queries_total{type="A"}[1m])/60)

**Comment by dmitryk-dk** [comment]
Hi @rightly ! No it doesn't. Now it shows you real image of your process. 
You should always use functions `increase` with lookbehind window. 
MetricsQL takes into account the previous point before the window in square brackets for range functions such as [rate](https://docs.victoriametrics.com/MetricsQL.html#rate) and [increase](https://docs.victoriametrics.com/MetricsQL.html#increase). This allows returning the exact results users expect for increase(metric[$__interval]) queries instead of incomplete results Prometheus returns for such queries.

Also you can check some information from this article
https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e
