### ISSUE TITLE
What's the mechanism / magic behind the low storage requirement of VictoriaMetrics?

### ISSUE THREAD

**Issue by unisqu** [VictoriaMetrics/VictoriaMetrics#319]
What's the mechanism / magic behind the low storage requirement of VictoriaMetrics?

Would like to know how / where is the code that keeps the data at lesser than 0.5 bytes.

Can you elaborate on this?

**Comment by hagen1778** [comment]
Hi @unisqu! Pls see https://medium.com/faun/victoriametrics-achieving-better-compression-for-time-series-data-than-gorilla-317bc1f95932
It would be better to ask such questions in Slack since it is neither `Bug` nor `Feature request`.
Thanks!

**Comment by valyala** [comment]
The following articles also can be useful in order to understand "the magic" behind low storage requirements for VictoriaMetrics:
* https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282
* https://medium.com/@valyala/wal-usage-looks-broken-in-modern-time-series-databases-b62a627ab704

@unisqu , feel free joining our slack channel at http://slack.victoriametrics.com/ .

**Comment by valyala** [comment]
Closing this question as answered.
