### ISSUE TITLE
Cardinality explorer

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3192]
**Is your feature request related to a problem? Please describe.**
I think some changes to cardinality explorer UI may be handful and improve the user's experience.

**Describe the solution you'd like**
1. Move `Labels with the highest number of series` section to the bottom, since it doesn't contribute to the goal of finding the cause of high cardinality. Or at least it is my understanding of the panel.
2. Change the sorting order of `Label=value pairs with the highest number of series` to ascending. If I'd be looking for labels that contribute the most in cardinality, I'll be looking for as low values as possible. And since table sorting happens on the frontend side, clicking on the table's column doesn't help me to find the pair with the lowest number of series. Perhaps, the section name should be changed accordingly.

cc @valyala @dmitryk-dk

**Comment by valyala** [comment]
1. The `Labels with the highest number of series` table allow locating specific labels, which increase the number of unique time series. For example, if this table would contain the `user_id` label at the top, then it definitely means that this label is used in the majority of time series stored in the database, and it is likely this label could lead to high cardinality. Of course there may be false positives such as `__name__`, `instance` and `job` labels, which present in every time series for obvious reasons. Probably, these three labels could be skipped in the table.

2. There is no sense to show `label=value` pairs with the smallest number of time series, since in most cases this table will contain thousands (or millions) of lines with the value `1`. For example, if there is a label `user_id` with a million unique values, then it is likely the `label=value pairs with the smallest number of series` would contain only `user_id=....  1` lines. While these lines may help quickly identifying that the `user_id` label could lead to high cardinality, this information isn't useful because the `Labels with the highest unique value` table already provides this information in much clearer way.

As for the `Label=value pairs with the highest number of series` table, it allows identifying potentially garbage `label=value` pairs, which present in big share of the ingested time series. Such pairs can be removed then via [relabeling](https://docs.victoriametrics.com/relabeling.html) if they are real garbage. This will reduce the growth of the `indexdb` data and will improve the registration speed for new time series.

So I think this feature request can be closed.
