### ISSUE TITLE
deduplication Does Not work

### ISSUE THREAD

**Issue by liyongxian** [VictoriaMetrics/VictoriaMetrics#3207]
**Describe the bug**
It would be great to [upgrade](https://docs.victoriametrics.com/#how-to-upgrade) 
to [the latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
and verify whether the bug is reproducible there.
It's also recommended to read the [troubleshooting docs](https://docs.victoriametrics.com/#troubleshooting).

**To Reproduce**
Steps to reproduce the behavior.
1.Prometheus remoteWrite to vm,Replicas of prometheus is 2,and scrape_interval config is 30s.
![image](https://user-images.githubusercontent.com/18571576/194525922-7b0a9e1a-f2ef-47c1-8894-c272ffddc4bb.png)

![image](https://user-images.githubusercontent.com/18571576/194525996-ac0d8166-5592-4efa-9349-dbfa2fb832d2.png)

2.Deploying VictoriaMetrics cluster By helm;
![image](https://user-images.githubusercontent.com/18571576/194526042-ae7373df-8332-4cad-933b-8843889ca53c.png)
3.Dashbord of grafana is different between  datasource of prometheus and vm.
Datasource of prometheus is fine.
![image](https://user-images.githubusercontent.com/18571576/194526595-d185ddbe-9483-422c-9d56-58826f38b983.png)
Metrics of Datasource vm is double of prometheus datasource.
![image](https://user-images.githubusercontent.com/18571576/194526845-ad006c76-9f7e-4b25-856f-cc8c2cb23c33.png)

**Expected behavior**
Dashbord of grafana is same between datasource of prometheus and vm.

**Logs**
Check if any warnings or errors were logged by VictoriaMetrics components
or components in communication with VictoriaMetrics (e.g. Prometheus, Grafana).

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

See how to setup monitoring here:

monitoring for VictoriaMetrics cluster.
**Configuration Of vminsert:**
![image](https://user-images.githubusercontent.com/18571576/194527531-4b1175a6-f4af-423a-b5b2-5481d3379173.png)
**Configuration Of vmselect:**
![image](https://user-images.githubusercontent.com/18571576/194527660-32d53295-cd19-4ba5-805c-de8b3cd92aad.png)
**Configuration Of vmstorage:**
![image](https://user-images.githubusercontent.com/18571576/194527770-1334ceb5-d09e-43e2-8ba7-06f75b3f988e.png)

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
**vmstorage-20220908-111837-tags-v1.81.2-cluster-0-ge9a0b803a**

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components.

**Comment by valyala** [comment]
Make sure that all the Prometheus replicas use identical configs, including `externalLabels` section. Prometheus adds labels defined in the `externalLabels` section into every scraped metric before sending it to the configured `remoteWrite.url`. So if Prometheus replicas contain different sets of labels in the `externalLabels` section, then this will result in duplicate metrics with different set of labels, which are stored to the remote storage (e.g. to the centralized VictoriaMetrics). This may result in unexpected query results if the query doesn't contain filters for unique `label=value` pairs set in `externalLabels` of one of the Prometheus instance.

Try performing the `up` query in VictoriaMetrics and in Prometheus and comparing the returned results. It is likely VictoriaMetrics will return duplicate time series with different sets of labels specified in the `externalLabels` section of Prometheus replicas. The fix is to specify identical sets of labels in the `externalLabels` section for Prometheus replicas, which scrape the same set of targets. In this case VictoriaMetrics should correctly [de-duplicate](https://docs.victoriametrics.com/#deduplication) stored metrics.

**Comment by liyongxian** [comment]
Thanks for your reply. After prometheus add externalLabels,It is fine.
