### ISSUE TITLE
What are the community's next plans?

### ISSUE THREAD

**Issue by aierui** [VictoriaMetrics/VictoriaMetrics#3248]
From the product dimension that like #129 ?

**Comment by jiekun** [comment]
Hi. Please refer: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/goals.md

Also VictoriaMetrics team is putting more focus on enhancing usability, bug fixes, and documentation, while continuing the development of new feature stream aggregation. Additionally, VictoriaLog is also under development.

Please feel free to comment on #129 if you have more ideas on product. I'm closing this issue for now since it's already outdated.
