### ISSUE TITLE
Clarification regarding ports usage in cluster version + few bonus questions

### ISSUE THREAD

**Issue by erkexzcx** [VictoriaMetrics/VictoriaMetrics#3280]
As far as I understand, these are default **HTTP** ports required:
 - `vminsert` - 8480
 - `vmselect` - 8481
 - `vmstorage` - 8482

All of them can be changed with identical flag `-httpListenAddr` parameter.

Additionally, `vmstorage` nodes have additional **TCP** ports that can also be changed using below parameters:
```
  -vminsertAddr string
     TCP address to accept connections from vminsert services (default ":8400")
  -vmselectAddr string
     TCP address to accept connections from vmselect services (default ":8401")
```

-------------------------

Now I am trying to setup a victoriametrics playground cluster to get myself more familiar with it. If I decide to use it in strict environment, I need to know the following:

- What ports needs to be open between nodes?
- Do those ports needs to be TCP (http) or UDP?
- Can I use reverse proxy with automated SSL (ACME) to encrypt traffic from/to/between components?
- Can I use different ports?

-------------------------

And now I have quite a few questions that I am unable to find answers [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html):

1. `vmstorage` nodes requires TCP, not HTTP ports open using `-vminsertAddr` and `-vmselectAddr`?
2. If I override above mentioned `-vminsertAddr` and `-vmselectAddr` ports, how do I tell `vminsert` and `vmselect` nodes about updated TCP ports?
3. If I decide to use reverse proxy with automated SSL (such as Traefik or Caddy) on HTTP ports, can I specify something like this on `vminsert` and `vmselect` nodes: `--storageNode="https://example.com"`? Or is it the only way using `-tls` flag and regular `host:ip` (without scheme)?
4. Same as above question, but what about `-vminsertAddr` and `-vmselectAddr` on `vmstorage` nodes?

-------------------------

Going through [documentation](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) I've also did not manage to understand the purpose of `-httpAuth.password` and `-httpAuth.username` fields. Are these for HTTP server? If so, how do I specify auth parameters for connections from e.g., `vmselect` to `vmstorage`? Can you clarify?

Also would be great if you update documentation [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) and mention `-vminsertAddr` and `-vmselectAddr` ports next to `By default the following TCP ports are used` (CTRL+F):
```
  -vminsertAddr string
     TCP address to accept connections from vminsert services (default ":8400")
  -vmselectAddr string
     TCP address to accept connections from vmselect services (default ":8401")
```

**Comment by erkexzcx** [comment]
So this is the scheme:
```
<client> --HTTP--> vminsert(port 8480) --TCP--> vmstorage(port 8400)
<client> --HTTP--> vmselect(port 8481) --TCP--> vmstorage(port 8401)
```

vmstorage nodes use http port 8482 only for troubleshooting. No inserts or selects through this port.

Also in vminsert and vmselect you can specify host:port. E.g.:
```
# vminsert
-storageNode "server1:8400,server2:8400"

# vmselect
-storageNode "server1:8401,server2:8401"
```

Good thing that at least one can use reverse proxy in front of vminsert and vmselect nodes with TLS termination.

Would be great if someone could provide above explanation in [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) for other newcomers like me. :)

**Comment by denisgolius** [comment]
@valyala @hagen1778 wdyt?

**Comment by valyala** [comment]
> What ports needs to be open between nodes?

VictoriaMetrics cluster components use the following TCP ports by default:

- `vmstorage` listens for incoming TCP connections from `vminsert` at port 8400
- `vmstorage` listens for incoming TCP connections from `vmselect` at port 8401
- `vminsert` listens for incoming HTTP requests at TCP port 8480
- `vmselect` listens for incoming HTTP requests at TCP port 8481
- `vmstorage` listens for incoming HTTP requests (mostly requests to `/metrics` aka [monitoring](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring) ) at TCP port 8482

> Do those ports needs to be TCP (http) or UDP?

VictoriaMetrics cluster components use only TCP

> Can I use reverse proxy with automated SSL (ACME) to encrypt traffic from/to/between components?

It is expected that all the components of a single VictoriaMetrics cluster run in an isolated low-latency and high-bandwidth network, since they may transfer big amounts of data over the network and may need low network latency for achieving high performance for both data ingestion and data querying. That's why it may be unnecessary to encrypt traffic between cluster components of VictoriaMetrics. If you still want encrypting the traffic between cluster components, then take a look at [mTLS protection docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection).

> Can I use different ports?

Yes - every TCP port mentioned above can be changed via the corresponding command-line flags if needed. See `-httpListenAddr`, `-vminsertAddr` and `-vmselectAddr` command-line flags [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#list-of-command-line-flags).

> vmstorage nodes requires TCP, not HTTP ports open using -vminsertAddr and -vmselectAddr?

Correct - VictoriaMetrics cluster components communicate via plain TCP (they use custom protocols) instead of HTTP.

> If I override above mentioned -vminsertAddr and -vmselectAddr ports, how do I tell vminsert and vmselect nodes about updated TCP ports?

Just pass `vmstorage` addresses to `-storageNode` command-line flags in the `host:port` format, where `port` is the updated port number.

> If I decide to use reverse proxy with automated SSL (such as Traefik or Caddy) on HTTP ports, can I specify something like this on vminsert and vmselect nodes: --storageNode="https://example.com"? Or is it the only way using -tls flag and regular host:ip (without scheme)?

`vminsert` and `vmselect` communicate with `vmstorage` via custom protocol over plain TCP connections. There is no HTTP here. So http proxies won't work here. Moreover, `vminsert` and `vmselect` nodes expect to communicate directly to all the `vmstorage` nodes in the cluster without third-party proxies or load-balancers. If you need encrypting the traffic between cluster components of VictoriaMetrics, then take a look at [mTLS docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection).

> Same as above question, but what about -vminsertAddr and -vmselectAddr on vmstorage nodes?

`vminsert` nodes connect to TCP address specified at `-vminsertAddr` command-line flag at `vmstorage`.
`vmselect` nodes connect to TCP address specified at `-vmselectAddr` command-line flag at `vmstorage`.

There is no HTTP traffic there - only custom protocols over plain TCP.

> I've also did not manage to understand the purpose of -httpAuth.password and -httpAuth.username fields. Are these for HTTP server?

`-httpAuth.password` and `-httpAuth.username` command-line flags are used for protecting HTTP endpoints at `-httpListenAddr` . The `-httpListenAddr` command-line flag is supported by all the VictoriaMetrics components. All the VictoriaMetrics components expose some common endpoints at this address such as [/metrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring) or [/debug/pprof/*](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling). `vminsert` and `vmselect` also accepts data and queries via various endpoints at this address - see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format).

> how do I specify auth parameters for connections from e.g., vmselect to vmstorage? Can you clarify?

It is expected that `vmselect`, `vminsert` and `vmstorage` communicate with each other over protected network. So there is no need in auth and encryption there. If you still need auth and encryption between cluster components, then take a look at [mTLS protection docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection).

> Also would be great if you update documentation [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) and mention -vminsertAddr and -vmselectAddr ports next to By default the following TCP ports are used

The `-vminsertAddr` and `-vmselectAddr` are **internal** ports for communication between cluster components. They shouldn't be exposed to untrusted networks. `vmstorage` doesn't accept HTTP requests at these ports. So there is no sense in mentioning them in [the monitoring docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring).

> vmstorage nodes use http port 8482 only for troubleshooting. No inserts or selects through this port.

Correct.

**Comment by erkexzcx** [comment]
FYI it is possible to specify such parameters and they work _just fine_ (theoretically) on both `vmselect` and `vminsert` nodes :
```
-storageNode "https://srv1.com,https://srv2.com"
```

Above configuration literally does not crash `vmselect` and `vminsert` nodes and seem to work just fine. It's just `vmstorage` nodes that does not accept `HTTP / GET` _hello_ message instead of proper _hello_ message.

What do you think about converting such plain TCP ports to HTTP ports, so user can put reverse proxy with TLS termination in front of it? It's just an idea (by no means I am expert in this), since `vmselect` and `vminsert` nodes seem to work just fine. :)

**Comment by valyala** [comment]
`vmselect` and `vmstorage` expect either hostnames or TCP addresses with ports at `-storageNode` command-line flag. If the port is missing, then the default port is used, e.g. `-storageNode=foobar` is automatically converted to `-storageNode=foobar:8400` at `vminsert` nodes and to `-storageNode=foobar:8401` at `vmselect` nodes.

The `-storageNode "https://srv1.com,https://srv2.com"` doesn't crash just by an accident.

> What do you think about converting such plain TCP ports to HTTP ports, so user can put reverse proxy with TLS termination in front of it?

It would be great to understand better the use case for such a configuration, given that it is recommended to run all the cluster components in the same subnetwork for performance, reliability and security reasons. See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#high-availability
