### ISSUE TITLE
vmstorage high cpu usage

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#329]
I'm using the cluster version of VictoriaMetrics with 16 vmstorage nodes and 18 cores per vmstorage node. vmstorage only uses a very low CPU when writing, about one or two cores. When I started the alarm query (QPS 1k), vmstorage used all the CPUs.
Can adding more nodes reduce the load? Or can we do something to reduce the overhead of uint64set.Add?
[pprof.vmstorage.samples.cpu.002.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4244252/pprof.vmstorage.samples.cpu.002.pb.gz)

**Comment by valyala** [comment]
@faceair , thanks for the CPU profile. I assume you run `v1.33.1-cluster`. The CPU profile shows that the majority of time is spent in inverted index search for time series matching the given label filters. This may be due to the following reasons:

* High number of unique time series matching individual label filters used in alerting queries. Could you provide the number of active time series from the official Grafana dashboard for cluster version of VictoriaMetrics? See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#monitoring) for details. Also it would be great if you could provide a sample of alerting queries issued to the cluster.
* Long time ranges for alerting queries, which spans more than one day. Could you provide time ranges used for the queries?
* High frequency for alerting queries. 1K queries per second looks too high for typical monitoring and alerting cases. Could you give more details on your use case? Probably the query rate could be significantly reduced. 

> Can adding more nodes reduce the load?

Adding more `vmstorage` nodes will reduce the number of active time series per each node, since such time series are evenly spread between all the `vmstorage` nodes. This should reduce CPU time used in inverted index search with label filters matching big number of time series. Note that `vmselect` fetches data from all the `vmstorage` nodes in the cluster for each incoming query. This means that each `vmstorage` node in the cluster takes part in processing all the 1K QPS. Probably you can split the cluster into smaller independent sub-clusters, so the incoming 1K QPS for alerting queries could be split among these sub-clusters.

> Or can we do something to reduce the overhead of uint64set.Add?

The `uint64set` is already heavily optimized for performance. It can process more than 100M calls per second per CPU core. I'll look into how to optimize it further.

**Comment by faceair** [comment]
Thank you for your quick reply.
1. The current active time series is 33.6 Mil.
2. Most queries look for metrics within the last ten minutes.
3. We have hundreds of thousands of alarms in total, so we also expect higher query QPS.

In most cases, each alarm query should hit less than 5 time series.
So there are only a few rules that match a lot of time series, which will also cause a lot of CPU utilization, right?
I'll check all our rules as soon.

**Comment by faceair** [comment]
Sorry, this is my mistake.

We use VictoriaMetrics through [carbonapi](https://github.com/go-graphite/carbonapi).  When [maxBatchSize](https://github.com/go-graphite/carbonapi/blob/8dad9e0b5dcda1481d84442728c95e2e2df51d85/zipper/broadcast/broadcast_group.go#L162) is greater than 0, it request the list of series using the api `/api/v1/series`, and then request each series in turn.

This may be useful for graphite, but unnecessary for VictoriaMetrics. I set `maxBatchSize` to 0, and the response time and cpu utilization of the VictoriaMetrics are reduced.

![image](https://user-images.githubusercontent.com/3659110/75165710-bfd1e380-575d-11ea-939a-95cc53ac912d.png)

Thanks for your help, I think this issue can be closed.

By the way, is the calling cost of `/api/v1/series` greater than`/api/v1/query_range` ?

**Comment by valyala** [comment]
> By the way, is the calling cost of /api/v1/series greater than /api/v1/query_range ?

The calling cost of `/api/v1/series` is usually lower than the calling cost for `/api/v1/query_range` for the same set of label filters on the same time range, since `/api/v1/series` fetches only time series names and labels and doesn't fetch data points. It is likely the `carbonapi` sets too big time range via `start` and `end` args when querying `/api/v1/series`. See https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers for details on query args for `/api/v1/series`. Could you investigate this and file an issue at [carbonapi](https://github.com/go-graphite/carbonapi) if this is your case?

**Comment by faceair** [comment]
On my fork branch, I have added the start and end timestamps of the original request to `/api/v1/series`, and I will confirm again through the log.

![image](https://user-images.githubusercontent.com/3659110/75177962-1a753a80-5772-11ea-97d6-72547ab2ede3.png)

**Comment by faceair** [comment]
I find the real reason now, because the [tldCacheDisabled](https://github.com/go-graphite/carbonapi/blob/8dad9e0b5dcda1481d84442728c95e2e2df51d85/zipper/zipper.go#L284) option is turned on by default. Each carbonapi instance will query the [full amount of metrics](https://github.com/go-graphite/carbonapi/blob/8dad9e0b5dcda1481d84442728c95e2e2df51d85/zipper/protocols/prometheus/prometheus_group.go#L620) within [60s](https://github.com/go-graphite/carbonapi/blob/8dad9e0b5dcda1481d84442728c95e2e2df51d85/zipper/zipper.go#L169). 
May not be turned on by default, it has too much impact on performance.
Anyway, thanks for your help.
