### ISSUE TITLE
vmui: add ability to analyze tracing from uploaded file

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#3308]
**Is your feature request related to a problem? Please describe.**
Sometimes it is helpful to analyze tracing from the uploaded files. 

**Describe the solution you'd like**
It would be awesome if vmui could have another tab where the user can choose a file and download it.
The file must contain tracing information in JSON format.
When a file is downloaded successfully, all tracing information shows for the user.

**Comment by valyala** [comment]
I think it would be better from usability PoV to provide an input textfield for the JSON trace, so the user could just copy-n-paste the JSON trace after obtaining it from command-line according to [query tracing docs](https://docs.victoriametrics.com/#query-tracing).

The input textfield for JSON trace is better than the file upload because of the following reasons:
- It is easier to copy-n-paste the JSON trace output from console instead of redirecting the trace output to file and then uploading the file to [vmui](https://docs.victoriametrics.com/#vmui).
- The textfield allows editing the JSON trace and instantly seeing the corresponding changes in the trace visualization. This makes trace debugging easier.

**Comment by valyala** [comment]
The ability to load and investigate query trace via [vmui](https://docs.victoriametrics.com/#vmui) is available in VictoriaMetrics starting from [v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
