### ISSUE TITLE
vmagent: conflict when remote write to thanos receive

### ISSUE THREAD

**Issue by yutian1224** [VictoriaMetrics/VictoriaMetrics#3319]
When upgrade vmagent to 1.82.0 or 1.83.0, our thanos can't store metrics.
But it is back to work after rolling back to 1.81.2 or before.

**Logs**
- in vmagent:
`VictoriaMetrics/app/vmagent/remotewrite/client.go:361   sending a block with size 110301 bytes to "1:secret-url" was rejected (skipping the block): status code 409; response body: forwarding request to endpoint thanos-a:10901: rpc error: code = AlreadyExists desc = store locally for endpoint thanos-a:10901: conflict`

- in thanos receive
`msg="Error on series with out-of-order labels" numDropped=10000`

**Version**
- thanos: 0.28.1
- vmagent: 1.82.0 & later

**Used command-line flags**
`-remoteWrite.url=http://thanos-distributer:9090/api/v1/receive -promscrape.streamParse -promscrape.noStaleMarkers -promscrape.suppressScrapeErrors -promscrape.config.strictParse=false`

**Comment by f41gh7** [comment]
Hello, it's expected behavior, Thanos rejects out-of-order samples. And vmagent doesn't provide any guarantees, that samples will be ordered.  As far as I know, grafana team allows out-of-order samples at Cortex and Mimir, probably, they will port it to the Thanos as well.

 As work around, you can try to change queues size to 1 at vmagent side, it usually helps in this case `-remoteWrite.queues=1`.

**Comment by yutian1224** [comment]
Thanks for the explanation.
If it is set to `remoteWrite.queues=1`, will the vmagent push speed decrease, resulting in a local backlog of metrics?
