### ISSUE TITLE
cluster dashboard "vminsert(All)/Rows per insert (All)" is blank

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#336]
**Describe the bug**
https://grafana.com/grafana/dashboards/11176
the cluster dashboard's panel which `vminsert(All)/Rows per insert (All)` seems invalid, it's show "No data".

**Additional context**
the panel's expr is ```sum(vm_rows_per_insert{job=~"$job", instance=~"$instance", quantile="0.99"}) by (instance) > 0```
i didn't found that name `vm_rows_per_insert` by curl `vminsert`'s /metrics api.

got this:
```
vm_rows_per_insert_bucket{type="influx",vmrange="9.5e-1...1.0e0"} 14134130
...
vm_rows_per_insert_bucket{type="influx",vmrange="4.0e2...4.5e2"} 5652
vm_rows_per_insert_sum{type="influx"} 758550240
vm_rows_per_insert_count{type="influx"} 36235654
```

**Comment by valyala** [comment]
oops, v1.34.0 broke the dasboard, since `vm_rows_per_insert` metric type has been changed from [Summary](https://prometheus.io/docs/concepts/metric_types/#summary) to VictoriaMetrics-specific [Histogram](https://medium.com/@valyala/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350).

@hagen1778 , could you publish the updated dashboards for v1.34.0 with the following query on this panel:

```
histogram_quantile(0.99, sum(increase(vm_rows_per_insert_bucket[5m])) by (instance, vmrange))
```

Note that the query won't work in Prometheus, since it doesn't know how to deal with VictoriaMetrics histograms. Probably, the panel should be removed from the dashboard, since it doesn't contain actionable information.

**Comment by hagen1778** [comment]
@n4mine plz see updated dashboard here https://grafana.com/grafana/dashboards/11176
Thanks for report!
