### ISSUE TITLE
One of the storage nodes slow let timeout to query metrics from vmselect

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#3378]
normal query：
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/6373972/203464471-1ccb7aef-d246-4cc6-b909-6986e7c9fff1.png">
but  vmstorage some questions let time more，20s or more than 30s：
 
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/6373972/203464577-c6b1c331-9392-4930-b11d-2823754b7926.png">
when  vmstorage slow skip select this，when vmstorage is ok continue to query this node

implementation logic is similar hystrix fuse
<img width="590" alt="image" src="https://user-images.githubusercontent.com/6373972/203465079-59130e0b-09c5-43e1-a207-7e2d3aba00e5.png">

**Comment by hagen1778** [comment]
Hi @jiangxinlingdu! What is the reason of one vmstorage being slow? How do you think the "fail threshold" should be calculated?

**Comment by jiangxinlingdu** [comment]
@hagen1778 underlying machine failure、machine I/O bottleneck and so on

**Comment by valyala** [comment]
`vmselect` doesn't wait for `N-1` slowest `vmstorage` nodes where `N` is the value of `-replicationFactor` command-line flag passed to `vmselect`. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/711 .

**Comment by jiangxinlingdu** [comment]
@valyala i see code good
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/6373972/204071494-c36bcfc9-dbeb-4dca-b514-eb4ea1547826.png">

**Comment by jiangxinlingdu** [comment]
@valyala if no set replicationFactor (default is 1), if there is a problem with one vmstorage, how to  skip this vmstorage

**Comment by valyala** [comment]
> if no set replicationFactor (default is 1), if there is a problem with one vmstorage, how to skip this vmstorage

Currently `vmselect` doesn't provide the ability to skip the slowest `vmstorage` node during querying if it runs with `-replicationFactor=1` command-line flag, since in this case the returned response may be incomplete. The workaround is to manually stop the slowest `vmstorage` nodes. In this case `vmselect` will notice the unavailable `vmstorage` node and will return incomplete results based on the data received from the remaining `vmstorage` nodes - see [cluster availability docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for more details.

**Comment by jiangxinlingdu** [comment]
@valyala 3q
