### ISSUE TITLE
Migrating Data between VM - Cluster Versions.

### ISSUE THREAD

**Issue by whitehatbuds** [VictoriaMetrics/VictoriaMetrics#3395]
Hello,

I'm here to seek some advise.
We are trying to migrate TBs of data from VM-Cluster Version => VM-Cluster Version (But different Persistent Volume (PV) type)

For large amount of data, I believe doing an "rsync" on the data storage directory between "src" to "dest" PV is faster.

When performing "Rsync" between the PVs,  should vm-cluster be shut down for both "src" and "dest" or can just the "src" be turned off while "dest" still receives new metric "data"?

Or do we need to introduce a 3rd VM-Instance to temporarily receive new metrics while both the old "src" and new "dest" is down.
And once the "rsync" is completed, we can use the "import / export" API to move the data from the 3rd to "dest" which contains a much smaller amount of data.

**Comment by zekker6** [comment]
Hello @whitehatbuds 

Yes, during migration both src and dst should be stopped as per this doc: https://docs.victoriametrics.com/?highlight=rsync#from-victoriametrics
Using 3rd cluster will work in this case.

Also, you can check out `vmctl` in native format: https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics
It is using VictoriaMetrics native protocol in order to achieve better data copying speed. `rsync`-ing data should still be faster, but if introducing 3rd cluster gives large operational overhead than `vmctl vm-native` might be a compromise between performance and migration complexity.
