### ISSUE TITLE
vmagent: optionally disable httpListenAddr completely

### ISSUE THREAD

**Issue by FlorinAndrei** [VictoriaMetrics/VictoriaMetrics#340]
**Is your feature request related to a problem? Please describe.**
I'm running multiple vmagent processes on a host, and they clash with regards to the httpListenAddr port. I have to make sure they each use a different port.

I'm not even using that port at all on the vmagent.

**Describe the solution you'd like**
I'd like a startup option that disables that listener completely.

**Describe alternatives you've considered**
Automation to avoid clashes, but ports are still wasted this way.

**Comment by valyala** [comment]
This mode has been added to `vmagent` in the commit c458b521a28c52c58a5b62b87e655982b8084c94 . Now it is possible to run `vmagent` with `-httpListenAddr=''`. In this case it won't open TCP port for http requests.

Note that `vmagent` cannot be monitored in this mode, since `/metrics` and `/targets` pages are exposed at `-httpListenAddr`. It also cannot accept data via Prometheus remote_write API (`/api/v1/write`) and via Influx line protocol (`/write`) in this mode.

**Comment by FlorinAndrei** [comment]
So, basically, this is useful when all you need the agent to do is scraping some remote source, and you want to reduce the number of used ports - like in my use case.

**Comment by valyala** [comment]
Yes. This feature is available starting from [v1.34.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
