### ISSUE TITLE
vmselect: add mem usage to slow log

### ISSUE THREAD

**Issue by matej-bellus-w** [VictoriaMetrics/VictoriaMetrics#3405]
**Is your feature request related to a problem? Please describe.**
We would like to have a better observability for slow metrics. 
Seeing how much memory is required by slow queries, would help us scale the cluster to right size.

**Describe the solution you'd like**
Add a field like `memory=123MB` to slow log output.

**Describe alternatives you've considered**
Alternatively, there option to scrape the system memory in higher intervals and colelate it to slow query execution time.

**Comment by valyala** [comment]
@matej-bellus-w , thanks for creating a feature request! I believe it is better to don't mix slow queries' logging with per-query memory usage logging, since:

1. slow queries may need pretty small amounts of memory
2. fast queries can lead to out of memory crashes

That's why it is better to have a separate ability to log queries, which need big amounts of memory. Let's close this feature request as obsolete by https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3553 then.

**Comment by valyala** [comment]
FYI, VictoriaMetrics provides [query tracing](https://docs.victoriametrics.com/#query-tracing) feature, which can be used for better understanding on why a particular query works slowly and how much resources does it use.
