### ISSUE TITLE
vmagent: scrape_series_added labels collision

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3406]
**Is your feature request related to a problem? Please describe.**
vmagent exposes metric `scrape_series_added` which has pre-defined labels `instance` and `jobs`. These label values are corresponding `instance` and `job` of the **target** vmagent scrapes. This violates the common approach for these labels to be used by a **scraper**. 
Consider the situation where **vmagent-monitoring** scrapes metrics from other **vmagent-team-dev** - what would be the label values for `scrape_series_added` metric scraped by **vmagent-monitoring** for "job=vmagent-team-dev"?

**Describe the solution you'd like**
Would be great to rename `instance` and `jobs` labels of `scrape_series_added` metric to `scrape_instance` and `scrape_job`.

**Comment by valyala** [comment]
The `scrape_series_added` metric is automatically generated by `vmagent` per each target scrape. `vmagent` automatically adds `instance` and `job` labels to this metric in the same way as it does for other automatically generated metrics such as `up` - see [these docs](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics). Prometheus does exactly the same - it automatically generates these metrics per each scrape and adds `instance` and `job` labels to these metrics. So changing these labels to something different such as `scrape_instance` and `scrape_job` would break compatibility with Prometheus. Addittionally, this will complicate the expected usage of these metrics in queries such as `sum(sum_over_time(scrape_series_added[1h]) by (job))` .

If a target exposes a metric with the name, which clashes with [automatically generated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics), then it would be great if `vmagent` could add `exported_` prefix to such metrics in order to avoid clashing. This aligns better with the behaviour when some labels in metrics collected from scrape targets clash with target labels - see `honor_labels`  option description [here](https://docs.victoriametrics.com/sd_configs.html#scrape_configs).

**Comment by valyala** [comment]
`vmagent` should automatically add `exported_` prefix to scraped metrics if their names clash with [automatically generated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics) after the commit 654e94f420c071b4d258b7496b7b6d6a33516e98 . This commit will be included in the next release.

**Comment by hagen1778** [comment]
I'm not convinced it is a good idea, frankly. I'd expect these labels (job, instance) to always reflect what and where it is scraped. When I can count on the value of these labels I can build meaningful dashboards and alerts. 
Solution you propose makes metric `scrape_series_added ` unpredictable. Its labels would depend on how these metrics are scraped (by vmagent itself or by separate vmagent).
If I understand it right.

**Comment by valyala** [comment]
[Automatically generated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics) aren't exported at `/metrics` page. They are generated by vmagent (and by Prometheus) on every scrape and then are sent to the configured remote storage. So these metrics cannot be scraped by another vmagent or by another Prometheus.

Metrics with reserved names (`up`, `scrape_samples_scraped`, etc.) may exist at `/metrics` page and clash with the automatically generated metrics in the following cases only:
- When metrics are scraped from [/federate](https://docs.victoriametrics.com/#federation) endpoint.
- When the exporter itself exposes its metrics under the reserved names.

In both cases it is better from debuggability and confusion reduction PoV to add `exported_` prefix to metrics scraped from the target if their names clash with the names of [automatically genetated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics). Otherwise these metrics will be mixed with automatically generated metrics in random order, increasing the level of confusion.

Therr is another option to solve the issue - when `honor_labels` option at [scrape_config](https://docs.victoriametrics.com/sd_configs.html#scrape_configs) is set to `true`, then do not generate automatic metrics at all, since there are high chances they will clash with the exported metric names when scraping [/federate](https://docs.victoriametrics.com/#federation) endpoint.

**Comment by valyala** [comment]
VictoriaMetrics adds `exported_` prefix to metrics provided by scrape targets if these metric names clash with [automatically generated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics) starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as addressed then.

**Comment by valyala** [comment]
FYI, `vmagent v1.87.0` and newer releases don't add `exported_` prefix to scraped metric names, which clash with the [automatically generated metric names](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics) if `honor_labels: true` option is explicitly set at the corresponding [scrape_config](https://docs.victoriametrics.com/sd_configs.html#scrape_configs). See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3557) for details.
