### ISSUE TITLE
vmagent: Cannot unmarshal Prometheus line

### ISSUE THREAD

**Issue by leonsp-ai** [VictoriaMetrics/VictoriaMetrics#3492]
**Describe the bug**
We are seeing regular "Cannot unmarshal Prometheus line" warnings in our logs. They are volume-dependent but there are currently ~70 warnings/hour. It looks like vmagent cannot parse an error message it might encounter while scraping metrics.

**To Reproduce**
1. Run vmagent v1.84.0 

**Expected behavior**
vmagent shouldn't try to parse (unmarshal) the contents of 4xx, 5xx, and connection errors

**Logs**
Distincts errors vmagent tried to parse:
```
cannot unmarshal Prometheus line "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"nodes \\\"ip-172-0-0-0.us-west-2.compute.internal\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"ip-172-0-0-0.us-west-2.compute.internal\",\"kind\":\"nodes\"},\"code\":404}": cannot unmarshal tags: missing value for tag "\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"nodes \\\"ip-172-0-0-0.us-west-2.compute.internal\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"ip-172-0-0-0.us-west-2.compute.internal\",\"kind\":\"nodes\"},\"code\":404}"

cannot unmarshal Prometheus line "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: dial tcp 172.0.0.0:10250: connect: connection refused\",\"code\":500}": cannot unmarshal tags: missing value for tag "\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: dial tcp 172.0.0.0:10250: connect: connection refused\",\"code\":500}"

cannot unmarshal Prometheus line "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: dial tcp 172.18.8.226:10250: connect: no route to host\",\"code\":500}": cannot unmarshal tags: missing value for tag "\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: dial tcp 172.18.8.226:10250: connect: no route to host\",\"code\":500}"

cannot unmarshal Prometheus line "{\"status\":\"TMC-13-0013\",\"error\":\"internal server error\",\"message\":\"internal\",\"timestamp\":\"2022-12-14T18:00:01.216258Z\"}": cannot unmarshal tags: missing value for tag "\"status\":\"TMC-13-0013\",\"error\":\"internal server error\",\"message\":\"internal\",\"timestamp\":\"2022-12-14T18:00:01.216258Z\"}"

cannot unmarshal Prometheus line "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: read tcp 172.0.0.0:13116-\\u003e172.0.0.1:10250: read: connection reset by peer\",\"code\":500}": cannot unmarshal tags: missing value for tag "\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: read tcp 172.0.0.0:13116-\\u003e172.0.0.1:10250: read: connection reset by peer\",\"code\":500}"

cannot unmarshal Prometheus line "Failed to fetch JSON response. TARGET: http://prometheus-server.monitoring.svc/api/v1/status/tsdb, ERROR: Get \"http://prometheus-server.monitoring.svc/api/v1/status/tsdb\": read tcp 172.0.0.0:59360->172.0.0.1:80: read: connection reset by peer": cannot parse value "to": unparsed tail left after parsing float64 from "to": "to"

cannot unmarshal Prometheus line "{\"timestamp\":\"2022-12-09T20:56:39.430+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/actuator/prometheus\"}": cannot unmarshal tags: missing value for tag "\"timestamp\":\"2022-12-09T20:56:39.430+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/actuator/prometheus\"}"

cannot unmarshal Prometheus line "<html><body><h1>Whitelabel Error Page</h1><p>This application has no configured error view, so you are seeing this as a fallback.</p><div id='created'>Fri Dec 09 17:28:37 GMT 2022</div><div>[6b99c10a-786] There was an unexpected error (type=Internal Server Error, status=500).</div><div></div></body></html>": cannot parse value "Error": unparsed tail left after parsing float64 from "Error": "Error"
```

**Screenshots**
n/a

**Version**
- victoriametrics/vmagent:v1.84.0
- victoria-metrics-agent 0.8.22

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components. 

```yaml
      promscrape.maxScrapeSize: "100MiB"
      promscrape.suppressScrapeErrors: true
      promscrape.suppressDuplicateScrapeTargetErrors: true
      promscrape.configCheckInterval: "1m" # check for changes to scrape config for reload
      remoteWrite.maxBlockSize: "100MiB"
 ```

**Comment by valyala** [comment]
`vmagent` should parse only responses with `200 OK` http status codes. It should log the `unexpected status code returned when scraping ... ` error when the scrape target returns non-200 http status code and when `-promscrape.suppressScrapeErrors` command-line flag is set to `false`. So, it looks like, the scraped targets really return invalid responses with 200 HTTP status codes in your case. This can be checked by navigating to the `http://vmagent:8429/targets` page and clicking the `response` link for the target with invalid response. This will instruct `vmagent` to query the target without parsing the response. If `vmagent` successfully opens the target response, which doesn't contain Prometheus metrics, then this means that the target returns this response with 200 OK http status code. The proper solution in this case is to fix the target, so it returns valid response in [Prometheus text exposition format](https://github.com/Showmax/prometheus-docs/blob/master/content/docs/instrumenting/exposition_formats.md).

Another approach to check the error is to ssh to the host where `vmagent` runs and to try manually query the target url displayed at `http://vmagent:8429/targets` page with `curl -v` and see which http response code the target returns.

**Comment by shirongxiao** [comment]
**Describe the bug:**
When VMagent attempts to collect a response larger than 500MB from a target, it throws a "cannot unmarshal Prometheus line" error. Upon inspecting the issue, I found that it occurs due to incomplete labels within the metrics, leading to errors such as "cannot unmarshal tags: missing closing quote for tag value" or "cannot unmarshal tags: missing value for tag". However, upon inspecting the data source, the corresponding metric labels appear to be complete. My test metrics consist of a single target containing 2 million metrics, each with 10 labels.
**Version：**
 v1.97.0
**Logs：**
 `{"ts":"2024-03-11T06:53:37.044Z","level":"error","caller":"VictoriaMetrics/lib/protoparser/prometheus/parser.go:231","msg":"error when scraping \"http://xxxx:8080/metrics\" from job \"default/vmsource\" with labels {container=\"metrics\",endpoint=\"http\",instance=\"xxxx:8080\",job=\"default/vmsource\",namespace=\"default\",pod=\"vmsource-7dff44dbcb-ppvbc\"}: cannot unmarshal Prometheus line \"my_histogram50658_bucket{A2Fuoq2js039FtkMH85=\\\"hKFbCkbvjfYqRS5eC5aB\\\",MNx1YHrbgzKvd=\\\"SrWjXQqLwezO3XejgFPctcW\\\",Mjoc2B1ZjH2=\\\"Rz5pYaOWHt42zqRkyVk0a906eZR9hgLE\\\",Q2PN2OcQbA=\\\"Q6qmzWSPMlb8W42bLAL2uGF\\\",SsfkxdpPB4Pkb5kQG=\\\"MFdmoyD2gkqZIJ55ip02uREl3IRw2MZP\\\",dgymE70nmopKlmB2Ij\": cannot unmarshal tags: missing value for tag \"dgymE70nmopKlmB2Ij\"; scrape errors can be disabled by -promscrape.suppressScrapeErrors command-line '
{"ts":"2024-03-11T06:53:38.493Z","level":"warn","caller":"VictoriaMetrics/lib/promscrape/scrapework.go:382",
"msg":"cannot scrape target \"http://xxxx:8080/metrics\" ({container=\"metrics\",endpoint=\"http\",in
stance=\"172.26.4.66:8080\",job=\"default/vmsource\",namespace=\"default\",pod=\"vmsource-7dff44dbcb-ppvbc\"
}) 1 out of 1 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read data from h
ttp://xxxx:8080/metrics: context deadline exceeded"}
 **command line:**
      - -promscrape.config.strictParse=false
      - -promscrape.config=/etc/vmagent/config_out/scrape.yml
      - -remoteWrite.maxDiskUsagePerURL=1073741824
      - -promscrape.maxScrapeSize=1024MB

**Comment by zekker6** [comment]
Hello @shirongxiao 
Based on the provided logs it seems like the request was cancelled due to the timeout. This can lead to response body not being completely loaded before the timeout and resulting in parsing error.

Could you check vmagent [metrics](https://docs.victoriametrics.com/vmagent/#automatically-generated-metrics) to see if that is the case?
You could use the following query to check if scrape is taking more than 80% time of the configured timeout:
```
scrape_duration_seconds / scrape_timeout_seconds > 0.8
```

If this is the case there are a few options which could help:
- increase scrape timeout(see these docs for parameters reference - https://docs.victoriametrics.com/sd_configs/#scrape_configs) - if scrape timeout is not explicitly defined the default value of `10s` is used. Note that scrape timeout cannot be higher than `scrape_interval`
- increase `scrape_interval` value - in case there is not enough time between scrapes to parse the response it is required to increase scrape interval itself
- increase amount of resources allocated to vmagent - it is required to find the bottleneck which does not allow vmagent to parse the response in time and increase amount of available resources
