### ISSUE TITLE
Influx line protocol timestamp precision

### ISSUE THREAD

**Issue by v98765** [VictoriaMetrics/VictoriaMetrics#35]
this is agent configuration with same default precision for any output.
```cat telegraf.conf
[agent]
  interval = "5m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "10s"
  flush_interval = "10s"
  flush_jitter = "0s"

  precision = ""
[[outputs.influxdb]]
  urls = ["http://influxdb.local:8086"]
[[outputs.influxdb]]
 urls = [ "http://vm.local:8428" ]
```
1. interval = 1m
snmp.conf
```
[[inputs.snmp]]
  interval = "1m"
  agents = [ "ip" ]
  version = 2
  community = "public"

  name = "polycom"
  [[inputs.snmp.field]]
   name = "uptime"
   oid = "1.3.6.1.2.1.1.3.0"

  [[inputs.snmp.field]]
   name = "Remote"
   oid = "1.3.6.1.4.1.2684.1.1.2.0"
   is_tag = true

  [[inputs.snmp.field]]
   name = "PercentPacketLoss"
   oid = "1.3.6.1.4.1.2684.1.1.21.0"
   conversion = "int"

  [[inputs.snmp.field]]
   name = "Jitter"
   oid = "1.3.6.1.4.1.2684.1.1.22.0"
   conversion = "int"
```
select from influx
```
> SELECT "Latency"  FROM "polycom" WHERE time >= 1558684500s and time <= 1558684800s
name: polycom
time                Latency
----                -------
1558684504000000000 55
1558684563000000000 55
1558684620000000000 55
1558684687000000000 55
1558684743000000000 56
>
```
select from vm
```
"values":[[1558684500,"55"],[1558684560,"55"],[1558684620,"55"],[1558684680,"55"],[1558684740,"55"],[1558684800,"56"]]
```
2. interval = 5min. Such a write error may occur.
snmp.conf
```
[[inputs.snmp]]
 interval = "5m"
 agents = [ "ip" ]
 version = 2
 community = "public"

 [[inputs.snmp.table]]
   name = "interface64"
   oid = "IF-MIB::ifXTable"
   inherit_tags = [ "location", "contact" ]

   [[inputs.snmp.table.field]]
     name = "Name"
     #oid = "IF-MIB::ifName"
     oid = "1.3.6.1.2.1.31.1.1.1.1"
     is_tag = true
```

influx
```1558559710000000000 134580430103583
1558560003000000000 134580666037847
1558560300000000000 134580921810007
1558560609000000000 134581167082106
1558560906000000000 134581416265458
1558561208000000000 134581649545641
```
vm
```
[[1558559700, u'134580198425146'],
[1558560000, u'134580430103583'],
[1558560300, u'134580921810007'],
[1558560600, u'134581167082106'],
[1558560900, u'134581167082106'],
[1558561200, u'134581416265458'],
[1558561500, u'134581649545641']]
```

**Comment by valyala** [comment]
1. InfluxDB stores timestamps with [nanosecond precision](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/#timestamp), while VictoriaMetrics stores timestamps with millisecond precision [similar to Prometheus](https://prometheus.io/docs/concepts/data_model/#samples). This means that timestamps are rounded to milliseconds when ingested into VictoriaMetrics via Influx line protocol.

2. VictoriaMetrics returns timestamps in [floating-point seconds similar to Prometheus](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats) for all the query responses, while InfluxDB returns timestamps in nanoseconds. This explains the resported timestamp results.

3. The [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) API doesn't return raw data stored in the database. It returns calculated data points at regular intervals equal to `step` value passed to the API. The calculation is simple - just use the last value before the given timestamp. That's why VictoriaMetrics returns duplicate value `134581167082106` for two timestamps in your results above. If you want raw values, then pass `query[duration]` query to  [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) API or use [export API](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics#how-to-export-time-series).
