### ISSUE TITLE
vmui: make step more friendly

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3510]
**Is your feature request related to a problem? Please describe.**
Currently, `step` value in VMUI is automatically adjusted and sometimes takes weird values:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/2902918/208687726-5650e25a-5a52-4954-a738-f13c47965651.png">

**Describe the solution you'd like**
Would be great to explicitly show the unit measurement for the step value (is it milliseconds, seconds?) and automatically round it to integer values.

**Comment by valyala** [comment]
See the related comments at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3521#discussion_r1055919431 and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3521#discussion_r1055916058 .

Summary:

* It is ok to round the step value to milliseconds as it was before.
* It would be great allowing users to enter user-readable steps with duration suffixes. For example, `123ms` or `5.4m` or `1.2h`. VictoriaMetrics already supports such `step` values.
* User-entered step values **shouldn't be rounded**, since this may confuse users.
* Automatically calculated steps may be rounded in order to improve response cache usage as described at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3521#discussion_r1055919431

**Comment by valyala** [comment]
See also the related bug - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3529

**Comment by valyala** [comment]
FYI, all the comments mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3510#issuecomment-1364368482 have been addressed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3561
