### ISSUE TITLE
[vmagent] Add an option to define maximum disk usage, and an option to not persist metric data on disk

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#352]
I think it would be useful to limit disk space used by vmagent persisting metrics data while it can't send it to vminsert. And when used space exceeds specified limit, start to drop oldest metrics data.

Also in some cases it is not necessery to persist data, for example if we have more than 1 scraping vmagent in dirrefent locations (HA-pair). So it also would be useful to be able to disable persisting any data to disk. Just drop metrics data when it couldn't sent it to vminsert.

**Comment by valyala** [comment]
@wf1nder , `vmagent` gained ability to limit the maximum disk space usage with the command-line flag `-remoteWrite.maxDiskUsagePerURL` at the commit 76036c18972d98cbbd72f0be989201702a45e6cf . Note that `vmagent` doesn't use disk-based buffer in general case when the rate for collecting new metrics is lower than the rate for writing these metrics to `-remoteWrite.url`. Read help for this flag for more details.

The `-remoteWrite.maxDiskUsagePerURL` flag will be added into the next release. In the mean time you can test it by building `vmagent` from `master` branch according to [these instructions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources).

**Comment by valyala** [comment]
@wf1nder , the `-remoteWrite.maxDiskUsagePerURL` command-line flag is available in `vmagent` starting from [v1.34.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done. Feel free re-opening it if you need additional functionality related to the original request.

As for adding an option to not persist metric data on disk, just set `-remoteWrite.maxdiskUsagePerURL` to small value (for example, 1). This will effectively disable persisting any data to disk, since the data is stored to disk in blocks and the minimal block size is 8 bytes.

**Comment by chrisfw** [comment]
@valyala , can you please tell me what the disk storage unit for the remoteWrite.maxdiskUsagePerURL is? Bytes?

**Comment by valyala** [comment]
Yes, it is in bytes. See `vmagent -help` output for more details:

>  -remoteWrite.maxDiskUsagePerURL int
    	The maximum file-based buffer size in bytes at -remoteWrite.tmpDataPath for each -remoteWrite.url. When buffer size reaches the configured maximum, then old data is dropped when adding new data to the buffer. Buffered data is stored in ~500MB chunks, so the minimum practical value for this flag is 500000000. Disk usage is unlimited if the value is set to 0

**Comment by chrisfw** [comment]
Thank you very much!

Regards,
Chris Whelan
