### ISSUE TITLE
vmalert record

### ISSUE THREAD

**Issue by hq2022** [VictoriaMetrics/VictoriaMetrics#3523]
if record use vmalert, when vmselect timeout or query slow, then this time metrics will missing, rate metrics will become abnormal,

**Comment by zekker6** [comment]
Hi @hq2022 
Single timeout for should not affect metrics too much usually.
In case this happens constantly you need to check why request finishes with timeout and fix the root cause.

Request failed with timeout is very likely to be caused by system being under provisioned, this may lead to errors for other parts of the system: writing data (for recording and regular write path), queries for reading (for recording and regular queries).

**Comment by hagen1778** [comment]
Looks like this issue is duplicating the following FR https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4043
