### ISSUE TITLE
explain potential cardinality statistics inaccuracy

### ISSUE THREAD

**Issue by vijexa** [VictoriaMetrics/VictoriaMetrics#3528]
**Describe the bug**
Hello, and thank you for this great project. 
I was trying to make use of cardinality stats from `/prometheus/api/v1/status/tsdb`, but returned series count in `seriesCountByMetricName` doesn't seem to be accurate. Series count is multiple times higher than what is expected and calculated by manually counting series from `/prometheus/api/v1/series`.

**To Reproduce**
Check metric series count in tsdb stats:
```
curl 'http://vmselect-vm-cluster:8481/select/0/prometheus/api/v1/status/tsdb?topN=10&date=2022-12-22' | jq '.data.seriesCountByMetricName' |  grep 'metric_name' -A 2 -B 1

      {
        "name": "metric_name",
        "value": 297613
      },
```

Retrieve metadata for all series of the same metric for the same day, then count unique series:
```
curl 'http://vmselect-vm-cluster:8481/select/0/prometheus/api/v1/series?start=2022-12-22T00:00:00Z&end=2022-12-22T23:59:59Z&match=metric_name' | jq '.data[]' -c  | wc -l

  122364
```

**Expected behavior**
Series count is expected to be the same in both cases, however it is very different. 

**Version**
`v1.81.2-cluster`, vmselect binary output with --version flag:
`vmselect-20220908-111729-tags-v1.81.2-cluster-0-ge9a0b803a`

**Comment by dmitryk-dk** [comment]
Hi @vijexa ! I have checked your requests on the 
[VictoriaMetrics play](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?topN=10&date=2022-12-28#/cardinality)

And i got next results 
`curl https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/status/tsdb?topN=10&date=2022-12-28 | jq '.data.seriesCountByMetricName' | grep 'flag' -A 2 -B 1`

```json
"seriesCountByMetricName":[{"name":"flag","value":1278}]
```

`curl 'https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/series?start=2022-12-28T00:00:00Z&end=2022-12-28T23:59:59Z&match[]=flag' | jq '.data[]' -c | wc -l`

`1278`

**Comment by vijexa** [comment]
Hello @dmitryk-dk,
Thank you for response! It looks like there's no difference for 2022-12-28 on play VM. However, I've checked a few other days on play VM and found the same issue for 2022-12-24:

```
curl 'https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/status/tsdb?topN=10&date=2022-12-24' | jq '.data.seriesCountByMetricName' |  grep 'flag' -A 2 -B 1

  {
    "name": "flag",
    "value": 1360
  },
```
```
curl 'https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/series?start=2022-12-24T00:00:00Z&end=2022-12-24T23:59:59Z&match[]=flag' | jq '.data[]' -c | wc -l

    1278
```

`/v1/status/tsdb` reports larger cardinality for metric `flag` on 2022-12-24.

**Comment by dmitryk-dk** [comment]
Hi @vijexa ! Sorry for the late delay I missed that you use the cluster version. Do you use a replication factor flag?

About our play  - this value can be a little different because tsdb checks all index when /api/v1/series/ make merges when return result

**Comment by valyala** [comment]
The [/api/v1/series](https://docs.victoriametrics.com/url-examples.html#apiv1series) works in the following way in VictoriaMetrics [cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html):

1. `vmselect` sends the `/api/v1/series` request to every `vmstorage` node in parallel.
2. Every `vmstorage` node locates all the time series matching the provided `match[]` [series selector](https://docs.victoriametrics.com/keyConcepts.html#filtering).
3. `vmselect` receives `metricName{labels}` entries from the step 2 for the matching time series from every `vmstorage` node.
4. `vmselect` de-duplicates identical `metricName{labels}` entries received from `vmstorage` nodes and returns the result to the client. Duplicate entries may appear because of the following reasons:
    * When the [replication](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) is enabled, then every incoming time series is stored at multiple distinct `vmstorage` nodes. Se multiple `vmstorage` nodes may return identical `metricName{labels}` entries.
    * When some of `vmstorage` nodes cannot keep up with the data ingestion rate (or if they become temporarily unavailable), then `vminsert` may start re-routing the incoming time series from the temporarily slow or temporarily unavailable `vmstorage` nodes to the remaining healthy nodes. This will result in duplicate `metricName{labels}` entries across multiple `vmstorage` nodes.

The [/api/v1/status/tsdb](https://docs.victoriametrics.com/#tsdb-stats) works in the following way at VictoriaMetrics cluster:

1. `vmselect` sends the `/api/v1/status/tsdb` request to every `vmstorage` node in parallel.
2. `vmstorage` collects tsdb stats by scanning the inverted index (aka `indexdb`). Specifically, it scans `metricName -> internal_series_id` index for collecting the stats for `seriesCountByMetricName`.
3. `vmstorage` fetches the collected tsdb stats from every `vmstorage` node and merges it. The `seriesCountByMetricName` stats is just summed across `vmstorage` nodes. This may lead to inflated values when samples for the same time series are spread across multiple `vmstorage` nodes as described above.

Additionally, sometimes `vmstorage` node may register multiple internal time series (aka `TSID`)  for the same original time series when many samples for the same new time series are sent to `vmstorage` in a short period of time. This may also lead to inflated values for `seriesCountByMetricName`.

**Comment by vijexa** [comment]
Yes, we use VM in cluster configuration. Configuration of the cluster that I've been using as an example is:
- 6 `vmstorage`
- 2 `vminsert`
- 2 `vmselect`
- replication factor 1 

So what you are saying is that `/api/v1/status/tsdb` cannot be relied on in cluster mode? Are there any plans to address this?

**Comment by jnadler** [comment]
We're facing this problem as well.   

I can understand why it might not be fixed - making TSDB stats mergeable across a cluster of vmstorage nodes sounds like a big job!

Can I suggest adding clear messaging to the documentation explaining that the numbers cannot be relied on in cluster mode.  We spent a bit of time believing that we could use this API as a part of our cardinality monitoring / cardinality defense solution, time that could have been saved if this limitation were in the docs.

At least two places it deserves a mention:
https://docs.victoriametrics.com/#tsdb-stats
https://docs.victoriametrics.com/#cardinality-explorer

The fact that it breaks cardinality explorer for all cluster users may provide some motivation for thinking of a solution here!

**Comment by valyala** [comment]
> Can I suggest adding clear messaging to the documentation explaining that the numbers cannot be relied on in cluster mode?

Absolutely agreed - the docs about cardinality explorer should mention that some stats can be inaccurate for VictoriaMetrics cluster, with the explanation of this fact. I also think that the source code responsible for calculating the stats for VictoriaMetrics cluster must contain a comment with the same explanation, so developers could figure out and understand the issue more quickly.

**Comment by hagen1778** [comment]
Related ticket https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3070

**Comment by hagen1778** [comment]
The info about possible inaccuracy was added to docs in PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4678
See https://docs.victoriametrics.com/#tsdb-stats
https://docs.victoriametrics.com/#cardinality-explorer-statistic-inaccuracy

**Comment by rajeshksv** [comment]
While it is clearly documented that, cardinality stats might be inaccurate due to replication and other factors, I noticed that, 
same metric is giving different series count when queried via same API but using different params

Scenario 1
http://<<endpoint>>/select/2491/vmui/#/cardinality?date=2024-09-05&match=&topN=10 
returns 3610 for `jmx_topic_send_record_50thPercentile`

Scenario 2
http://<<endpoint>>/select/2491/vmui/#/cardinality?date=2024-09-05&match=jmx_topic_send_record_50thPercentile&topN=10 
returns 11146 for `jmx_topic_send_record_50thPercentile`

(I got these results back to back and tried hitting it multiple times. Same result all times)

Why is this discrepancy ?

PS: If it helps, output of series query
`curl -s http://<<endpoint>>/select/2491/prometheus/api/v1/series -d 'match[]=jmx_bytes_in_per_sec_Count' | jq '.data | length'` 
returns 10970
