### ISSUE TITLE
export does not work

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#3563]
If one wants to export a TS with more than 30M samples, vm stops after ~ 30M samples, usually with an error message telling one to change `--search.maxSamplesPerTimeseries` parameter. This really sucks and is not, what one expects. 

**To Reproduce**
Create a TS with more than 35M samples and try to export it completely.

**Expected behavior**
VM should dump the full TS (or in the specified range) without applying `search.maxSamplesPerTimeseries` limit. Applying any limit on an export does simply make no sense at all from the user perspective (read | filter | dump). Furthermore it is a really questionable/annoying workflow, having to stop vmdb, change the start params, restart it, dumb the required data and if one is lucky and vmdb doesn't prevented it with a similar message again, stop the db, change the params back and restart it ...

**Used command-line flags**
```
curl -o ~/tmp/anubis.csv -d 'match[]=node_net_ip_InBcastPkts{gz="anubis"}' -d start=0 -d end=1672287256 -G http://${DB}:8428/api/v1/export/csv -d 'format=__name__,__timestamp__:unix_ms,gz,job,__value__' -d reduce_mem_usage=1

curl -o ~/tmp/anubis.csv -d 'match[]=node_net_ip_InBcastPkts{gz="anubis"}' -G http://${DB}:8428/api/v1/export/csv -d 'format=__name__,__timestamp__:unix_ms,gz,job,__value__' -d reduce_mem_usage=1

curl -o ~/tmp/anubis.csv -d 'match[]=node_net_ip_InBcastPkts{gz="anubis"}' -d start=0 -G http://${DB}:8428/api/v1/export/csv -d 'format=__name__,__timestamp__:unix_ms,gz,job,__value__' -d reduce_mem_usage=1

curl -o ~/tmp/anubis.csv -d 'match[]=node_net_ip_InBcastPkts{gz="anubis"}' -d start=0 -G http://${DB}:8428/api/v1/export/csv -d 'format=__name__,__timestamp__:unix_ms,gz,job,__value__'
```

**Comment by zekker6** [comment]
@jelmd Those limits are present in order to reduce chance of single query taking too many resources and slow down the system.
If those limits won't be enforced than any export query will be able to export all datapoints in DB which will definitely create too excessive load and might lead to DB being slow or crashing.
If it is needed to export large chunks of data you can split data chunks in smaller subsets and export one by one.

In case this is one-off task, you can create a replica with data contents restored from backup, tweak flags to very high values there and drop this environment after export will be processed.

**Comment by jelmd** [comment]
@zekker6 Well, when I want to **export** a TS, I do not really care about, how long it takes (and actually I do not know any database, which declines exports/retrieving data just because it could take too much resources - which are BTW: available anyway). If a task/query slows down the DB it gets logged in the slow-query log, doesn't it?

Playing around, try and error a whole day just to get a single TS out of a DB (whereby the exposed "records" are not even ordered by timestamps) is not an option. At least if stuff gets triggered via `/api/v1/export` such questionable artificial limits should be turned off on the fly. And if this takes really "too much" resources, it probably needs some optimization. I do not really understand, why a `read, filter, write` should be resource expensive at all...

**Comment by zekker6** [comment]
@jelmd You can set `--search.maxSamplesPerSeries=-1` in order to disable this limit, so it will be easier to export the data.

This limitation is aimed to reduce memory usage during unpacking raw data into samples for export. In cases where metric can contain a lot of datapoints DB will need to retrieve a lot of data from disk, unpack it and write as a part of export. If there will be no limitation in place there is a chance that multiple queries will get all available resources and this might result in OOM for DB which is highly undesirable.

In case of VictoriaMetrics queries coming into DB can be written by any users via Grafana, alerting/recording rules configuration provided to operations teams. This quite often leads to having a lot of queries which are trying to fetch a lot of data without a good reason to do so. For example, poorly written query for dashboard which will be evaluated every minute by every user who have dashboard opened can easily lead to resources exhaustion and OOM of DB.
So motivation to have this and other `--search.*` flags is to have a soft limit that will stop query processing before it will lead to crashes or instability and let the user know that query needs to be optimized.

**Comment by jelmd** [comment]
Motivation understood and good. However, applying it on exports [and not supporting an export specific flag, which allows one to overwrite it (e.g. like nolimit)] is IMHO bad design. So right now I'm forced to run always with `--search.maxSamplesPerSeries=-1` which makes this features effectively useless and makes the app vulnerable to unintentional DoS. :((

**Comment by jiekun** [comment]
@jelmd Hi. I think the original question has been answered. Feel free to re-open this issue if you have more questions.
