### ISSUE TITLE
Labels endpoint not returning CamelCase label names

### ISSUE THREAD

**Issue by vijexa** [VictoriaMetrics/VictoriaMetrics#3566]
Hello!

**Describe the bug**
`/api/v1/labels` endpoint is not returning label names that are in CamelCase. Those labels are actually processed by VM and it's possible to query them, they are just not visible in `/api/v1/labels` output.

**To Reproduce**
1. Insert metric that contains labels with CamelCase name
2. Query `/api/v1/labels`

For example, local VictoriaMetrics is set to scrape this `/metrics` endpoint from a local app:
```sh
> curl 'http://localhost:8080/metrics'

# HELP metric_with_camelcase_labels Test metric that contains a label with name in CamelCase
# TYPE metric_with_camelcase_labels counter
metric_with_camelcase_labels{CamelCase="foo",snake_case="bar"} 1
```
This is the output of `/api/v1/labels` in VM:
```sh
curl 'localhost:8428/api/v1/labels'

{
    "status": "success",
    "data": [
        "__name__",
        "instance",
        "job",
        "monitor",
        "snake_case"
    ]
}
```
Notice how it doesn't contain label named `CamelCase`. 

Local Prometheus that was set to scrape the same app doesn't have this issue:
```sh
curl 'localhost:9090/api/v1/labels'

{
    "status": "success",
    "data": [
        "CamelCase",
        "__name__",
        "instance",
        "job",
        "snake_case"
    ]
}
```
Notice that `CamelCase` is present.

**Expected behavior**
Label named `CamelCase` should be present in output of `/api/v1/labels`, like in Prometheus.

**Version**
`victoria-metrics-20221220-184310-heads-public-single-node-0-g1d7b5cb83`

**Comment by valyala** [comment]
@vijexa , thanks for filing the detailed bugreport! The bug should be fixed in the commit 41e00a0df7df284878fab2c9ffa60d3d74b50e66 . This commit will be included in the next release. In the meantime you can build VictoriaMetrics from this commit by following [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verifying whether VictoriaMetrics properly returns all the label names from [/api/v1/labels](https://docs.victoriametrics.com/url-examples.html#apiv1labels) endpoint.

**Comment by vijexa** [comment]
Thank you!

**Comment by valyala** [comment]
VictoriaMetrics should properly return label names, which start from the uppercase letter, starting from [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
