### ISSUE TITLE
Downsampling data

### ISSUE THREAD

**Issue by iamalryz** [VictoriaMetrics/VictoriaMetrics#36]
Is there ability to downsample data? 

For example, I need to store raw metrics for 1 month, and metrics aggregated by 30 minutes for 1 year.

**Comment by valyala** [comment]
VictoriaMetrics doesn't provide automatic downsampling at the moment. But it may be implemented using the following approach:
- To run multiple VictoriaMetrics instances (or clusters) with distinct retentions, since each VictoriaMetrics instance works with a single retention.
- To periodically scrape the required downsampled data via [/federate API](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics#federation) from the instance with raw data and store it in the instance with higher retention.

We are planning to add [recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) to VictoriaMetrics with the ability to export the recorded data into external storage (i.e. another VictoriaMetrics instance with higher retention).

**Comment by thulle** [comment]
I'm commenting part as a +1 on this being a requested feature, and part answering questions posted on reddit by @valyala about reasons to use VM.

To be able to downsample data like RRD in combination with the current storageefficiency of large amounts of timeseries, and being able to query this downsampled data transparently is imho. the featureset required for VM to become the obvious choice for devops/dashboards.
By transparently I mean that older data should be returned in lower resolution, without the querier having to make anything different. This would allow debugging issues using high resolution data as they happen and view trends over long time just by changing timerange in a dashboard, instead of having to modify queries & datasources in existing/pre-made dashboards or storing huge amounts of data.

**Comment by jujo1** [comment]
There appears to be limited updates on this topic. The need for downsampling (in particular OHLC bars) is paramount for use cases in financial price data. The objective is to store data long term at high frequency and most commonly use data at varying lower frequencies.

**Comment by valyala** [comment]
@jujo1 , did you try using `rollup_candlestick(m[d])` on the raw data? This function returns four time series per each input time series - `open`, `high`, `low` and `close`. See https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL for details.

Could you answer the following questions in order to understand better your use case:
1) What is the interval between data points in a single time series? Note that the minimal interval between data points supported by VictoriaMetrics is 1 millisecond.
2) How many unique time series are queried by a single query on average and on maximum?
3) What is the average and the maximum query interval? (hour, day, week, month, year, etc.)
4) Could you provide slow query for your case, so we could optimize it without resorting to down-sampling?

VictoriaMetrics is able to scan up to 50 millions of data points per second per CPU core, and the performance scales almost linearly with the number of CPU cores. For instance, 20 CPU cores can result in scan speed of up to 1 billion of data points per second.

Example calculations: if new points for each time series arrive every 100ms, then a single time series for one year would contain 10*3600*24*365=315M data points. This means that VictoriaMetrics could process up to 3 such time series per second on 20 CPU cores.

In the mean time you can create a custom script, which would periodically fetch down-sampled OHLC numbers from raw data and put them into a separate VictoriaMetrics instance for fast query processing on long time ranges.

**Comment by valyala** [comment]
FYI, it is possible to (ab)use deduplication for simple downsampling. For instance, if scrape interval for the ingested data is 15s, while `-dedup.minScrapeInterval` is set to 5m, then VictoriaMetrics will leave only a single sample per each 5m interval in the storage. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#deduplication) for details.

**Comment by valyala** [comment]
FYI, [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md) supports recording rules starting from [v1.37.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by bojleros** [comment]
Hi, Would you please give at least rough estimate on downsampling feature release? It is very nice that VM is capable of storing such huge amounts of series but we'd prefer to use our resources in more optimal way. In general old data is far less likely to be queried and even if this gets queried it is enough to have just 5m aggregates instead of full resolution. Its likely that current data is going to be querried quite often so downsampling means more resources for the most important data -> more efficiency.

**Comment by valyala** [comment]
> Would you please give at least rough estimate on downsampling feature release?

We already designed draft architecture for multi-level downsampling and are going to add it to VictoriaMetrics during the next 6 months.

**Comment by bojleros** [comment]
@valyala What is the overall plan? Are we going to be able to specify additional retention thresholds so datapoints will be downsampled as soon as their age breaches the thresholds? Would it be possible in simple single node deployments?

**Comment by raags** [comment]
Does downsampling here mean an aggregation across the sampled time range? How will the new data point be calculated? 

For e.g. in graphite, every metric can be configured with an aggregation function (min, max, avg, sum, etc) that is applied to the sample period. i.e. if 1 min goes down to 1 hour, for `http_requests_total` it should `sum(1h)`, while for `http_requets_duration` it should `avg(1h)`.

**Comment by valyala** [comment]
> What is the overall plan? Are we going to be able to specify additional retention thresholds so datapoints will be downsampled as soon as their age breaches the thresholds? Would it be possible in simple single node deployments?

Draft config will look like the following:

    -downsample 1d:1m,7d:5m,30d:1h

This means that downsampling is applied in the following way:
* Samples with timestamps closer than 1d (one day) to the current time aren't downsampled
* Samples with timestamps from 1d to 7d to the current time are downsampled with 1m (one minute) interval
* Samples with timestamps from 7d to 30d to the current time are downsampled with 5m interval
* Older samples are downsampled with 1h interval.

The functionality will be available in both single-node and cluster versions of VictoriaMetrics.

> Does downsampling here mean an aggregation across the sampled time range? How will the new data point be calculated?

The downsampling means leaving the first point on the configured interval. There is no any aggregation.

> in graphite, every metric can be configured with an aggregation function (min, max, avg, sum, etc) that is applied to the sample period. i.e. if 1 min goes down to 1 hour, for http_requests_total it should sum(1h), while for http_requets_duration it should avg(1h).

This type of downsampling is easy to misconfigure and is hard to reason about, so we decided postponing its implementation after simple downsampling mentioned above will be implemented.

**Comment by hekmon** [comment]
That is great news ! 

So it seams it is a kind of dynamic deduplication windows ? How dedup will work once downsampling is here ? Will it be merged with DS as DS can be configured to act as dedup ?

**Comment by valyala** [comment]
>  How dedup will work once downsampling is here ? Will it be merged with DS as DS can be configured to act as dedup ?

The `-dedup.minScrapeInterval` command-line flag will be left for backwards compatibility, while `simple downsampling` will re-use the deduplication code.

**Comment by razlo** [comment]
Hi @valyala,
Any news regarding the downsampling implementation?

Thanks! 🙏

**Comment by valyala** [comment]
Simple downsampling mentioned in the https://github.com/VictoriaMetrics/VictoriaMetrics/issues/36#issuecomment-686846353 is planned to be implemented in Q1 2021.

**Comment by isavcic** [comment]
> The downsampling means leaving the first point on the configured interval. There is no any aggregation.

Sorry, but this makes no sense in real-life scenarios. That first point might be an outlier value or even a null, thus skewing the downsampled period. avg() makes more sense in general use and is the default of other TSDBs.

**Comment by vainkop** [comment]
Too bad downsampling is not available yet.
I was about to propose a switch from InfluxDB to VM, but downsampling is a requirement, so it's a blocker.

**Comment by hdost** [comment]
Is there a design proposed for this already, if so how can we help?

**Comment by sc0rp10** [comment]
hi, @valyala!
Is there any news about downsampling?

**Comment by valyala** [comment]
The downsampling is at the top priority right now. The ETA is June 2021.

**Comment by acruise** [comment]
> Sorry, but this makes no sense in real-life scenarios. That first point might be an outlier value or even a null, thus skewing the downsampled period. avg() makes more sense in general use and is the default of other TSDBs.

Agreed, downsampling must aggregate in order to be useful. It'd be OK to only support simple aggregates like min/max/avg/count/sum at first. 

One extra wrinkle is that some aggregates should preserve necessary statistics, e.g. to avoid average-of-averages, you really want the finer-grained side of the downsample dataset to include not just the computed average, but also the (count, sum) that it was derived from.

**Comment by odinsy** [comment]
> The downsampling is at the top priority right now. The ETA is June 2021.

Any news? :)

**Comment by odinsy** [comment]
> The downsampling is at the top priority right now. The ETA is June 2021.

Any news? :)

**Comment by jinlongwang** [comment]
Will this ability only be available in the Enterprise Edition?

**Comment by isavcic** [comment]
> Will this ability only be available in the Enterprise Edition?

This man is onto something here.

**Comment by isavcic** [comment]
```go
if enough_people_need_the_feature && they_ask_for_it_for_a_long_time {
    make_it_an_enterprise_feature()
}
```

**Comment by valyala** [comment]
> Sorry, but this makes no sense in real-life scenarios. That first point might be an outlier value or even a null, thus skewing the downsampled period. avg() makes more sense in general use and is the default of other TSDBs.

While the `avg_over_time()` function may work well as a downsampling function for [gauges](https://prometheus.io/docs/concepts/metric_types/#gauge), it doesn't work for [counters](https://prometheus.io/docs/concepts/metric_types/#counter) in general case. It is better to get the first sample on every downsampling interval for counters instead, since it doesn't introduce the calculation error, e.g. `rate(m[d])` and `increase(m[d])` would return the same results before and after the downsampling for the downsampled interval `d`.

Additional notes:
* Samples downsampled with `avg` cannot be downsampled on a bigger interval after that, since [the average of averages doesn't equal to the real average](https://convalytics.com/statistics/taking-an-average-of-averages-why-its-wrong/).
* The `avg` loses spikes (aka min and max values) on the downsampled interval. The spikes can contain important information for some cases. For instance, they can help answering questions like `what was the maximum memory usage for the app on the given time range?`.
* Every type of the downsampling loses a part of the original information. The most optimal downsampling function is `histogram_over_time()` from [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html), since it saves the original values distribution and its results can be used for multi-level downsampling. See [more information about VictoriaMetrics histograms](https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350). Unfortunately, this function generates tens of output series for every input series, so the downsampled series can take more disk space than the original series.
* Most users expect that the downsampling is performed individually per each time series. But this rapidly changes with new montirogng types such as Kubernetes monitoring. It can generate new series at a high rate during each deployment or any k8s cluster state change (aka high churn rate). The per-series downsampling can be ineffective in reducing disk space and improving query performance for high churn rate series, since it doesn't reduce the number of series and cannot reduce significantly the number of samples per each series (because the original series are short).
* Both VictoriaMetrics and Prometheus return the last original sample value for each `step` interval requested via [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries), e.g. they the analogue of  `last_over_time()` function for the downsampling during querying. See more details about this [here](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness). The planned function for downsampling in VictoriaMetrics - `first_over_time()` - aligns better with the behavior of Prometheus and VictoriaMetrics, e.g. graphs over the original data and over the downsampled data will look similar.

As you can see, it is hard to provide a generic implementation, which covers the majority of edge cases. So we decided to start with the basic implementation aligned with the dynamic downsampling used in Prometheus and VictoriaMetrics during querying.

VictoriaMetrics already provides a tool, which can be set up for custom downsampling - [vmalert](https://docs.victoriametrics.com/vmalert.html). It allows setting up arbitrary downsampling type via [recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/). These rules are evaluated at regular interval against the `-datasource.url` (e.g. against VictoriaMetrics) and the evaluation results are sent to `-remoteWrite.url`. Note that `-datasource.url` and `-remoteWrite.url` can point to different databases with different settings including retention period. In this way it is possible to set up the downsampling only for long-term metrics, while leaving the rest of metrics in short-term storage.

> Will this ability only be available in the Enterprise Edition?

The downsampling will be available in enterprise package at start as promised on the [enterprise page](https://victoriametrics.com/enterprise.html). Later it can be backported to community edition of VictoriaMetrics.

**Comment by ahmadalli** [comment]
Clould you provide an estimation on when this would be available on community edition?

**Comment by valyala** [comment]
> Clould you provide an estimation on when this would be available on community edition?

This depends on how smooth the downsampling feature will work in an enterprise edition. There is no ETA for this.

**Comment by LightCastlePro** [comment]
> > Clould you provide an estimation on when this would be available on community edition?
> 
> This depends on how smooth the downsampling feature will work in an enterprise edition. There is no ETA for this.

hi valyala, does downsampling data can work for avg_over_time, sum_over_time, sum, max, etc ?

**Comment by joaopaulobdac** [comment]
Hi everyone, does VictoriaMetrics/MetricsQL have something like LTTB from the TimescaleDB toolkit? https://github.com/timescale/timescaledb-toolkit/blob/main/docs/lttb.md

**Comment by syepes** [comment]
Interesting feature, what function is used to down sample the data points (max, min, avg, sum)? can the method be configured like we did in the old days of Graphite?

It would be interesting to simply calculate them all so we don't have to configure anything.

**Comment by valyala** [comment]
> does VictoriaMetrics/MetricsQL have something like LTTB from the TimescaleDB toolkit? https://github.com/timescale/timescaledb-toolkit/blob/main/docs/lttb.md

No. See the related feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1775 .

> does downsampling data can work for avg_over_time, sum_over_time, sum, max, etc ?
> what function is used to down sample the data points (max, min, avg, sum)? can the method be configured like we did in the old days of Graphite?

The current [downsampling implementation](https://docs.victoriametrics.com/#downsampling) is based on [deduplication algorithm](https://docs.victoriametrics.com/#deduplication). It works perfectly for [counter metric types](https://prometheus.io/docs/concepts/metric_types/#counter) and [histogram metric types](https://prometheus.io/docs/concepts/metric_types/#histogram). It may miss some data for [gauge metric types](https://prometheus.io/docs/concepts/metric_types/#gauge) and [summary metric types](https://prometheus.io/docs/concepts/metric_types/#summary).

**Comment by valyala** [comment]
Downsampling is available in VictoriaMetrics [enterprise](https://victoriametrics.com/enterprise.html) starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/#downsampling). It can be evaluated by downloading and running enterprise binaries and Docker images.

Closing the feature request as done. Let's open new feature requests for further improvements to downsampling.

**Comment by isavcic** [comment]
> Closing the feature request as done. Let's open new feature requests for further improvements to downsampling.

Ie. we're welcome to give you ideas on what to put in the enterprise version?  🤣

**Comment by josvo** [comment]
> Closing the feature request as done. Let's open new feature requests for further improvements to downsampling.

I disagree here. This is only done for the enterprise version. However, this is the issue tracker for the open source version - and it does not work there.
If you want to keep your feature in the enterprise version - fine. But at least do not mark it as closed / resolved in this bug tracker, as it is just not true.

**Comment by valyala** [comment]
We use the following rules in order to determine whether the feature should be included in open source version:

1. If the feature is needed for wide audience, then it is included in open source version of VictoriaMetrics, so a big share of the community can benefit from the feature.
2. If the feature is easy to implement, then it is likely it is included in open source version of VictoriaMetrics.
3. If the feature is needed only for a small subset of users and the majority of these users are from enterprise world, then it is included in enterprise version of VictoriaMetrics.
4. If enterprise feature becomes needed by wider audience, then it will be eventually added to open source version of VictoriaMetrics.

We believe that downsampling matches the third rule, so it is included in enterprise version of VictoriaMetrics at first. Usually  downampling is needed for solving the following issues:
* High disk space usage.
* Slow query performance.

Both issues are addressed by open-source version of VictoriaMetrics:

* VictoriaMetrics provides the best compression for the ingested data comparing to competing solution - see [this](https://faun.pub/victoriametrics-achieving-better-compression-for-time-series-data-than-gorilla-317bc1f95932) and [this](https://valyala.medium.com/prometheus-vs-victoriametrics-benchmark-on-node-exporter-metrics-4ca29c75590f) articles. This addresses high disk space usage issue for most cases.
* VictoriaMetrics is optimized for raw samples' processing during queries - it can scan up to 50 millions of raw samples per second per CPU core and its performance scales linearly with the number of available CPU cores. See [this](https://valyala.medium.com/measuring-vertical-scalability-for-time-series-databases-in-google-cloud-92550d78d8ae) and [this](https://valyala.medium.com/billy-how-victoriametrics-deals-with-more-than-500-billion-rows-e82ff8f725da) articles. This addresses slow query performance issue.

Note also that the downsampling doesn't improve query performance for [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate) time series, since it doesn't reduce the number of time series - the downampling reduces only the number of samples per each time series. If you need reducing the number of matching time series for queries over long time ranges, then [recording rules in vmalert](https://docs.victoriametrics.com/vmalert.html#downsampling-and-aggregation-via-vmalert) can be used.

Given the above facts, the need of downsampling is considered quite low for wider audience, so it isn't included in open source version for now.

**Comment by grandich** [comment]
Just one thought: we have successfully migrated to VM a large Munin setup --which has native downsampling (RRDtool)-- with up to 1 year of retention, but migrated with only 6 months of retention due to cost limitations.

We were looking forward to this feature from the start, because it aims directly to its cost-effectiveness and low-space usage compared to other solutions.

In my opinion cost-effectiveness is always a core feature needed by a wide audience, "by default", and even more in the non-enterprise world.

**Comment by ahmadalli** [comment]
I guess we can look at the repository statistics in order to determine how much "in demand" this feature is.
- If we sort the issues by "most comments", this issue would come in third (https://github.com/VictoriaMetrics/VictoriaMetrics/issues?q=sort%3Acomments-desc+)
- If we sort by most 👍s, it'll come in first (https://github.com/VictoriaMetrics/VictoriaMetrics/issues?q=sort%3Areactions-%2B1-desc)

Also as you've stated that enterprise plan would come with "Enterprise support", I guess most of the enterprise users wouldn't bother themselves with github issues on the opensource version since they have better communication channels.
![image](https://user-images.githubusercontent.com/2167301/147349109-cdbc05e1-4910-43a5-bd59-3506e9fa4f10.png)

This is your product, and you have every right want to develop some features for enterprise users, but what makes me upset is that the first promise on this feature at the beginning of 2021 (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/36#issuecomment-756436356) didn't said anything about this feature only being available for the enterprise version, and enterprise was only mentioned later this year around June.

**Comment by derveloper** [comment]
I've asked the sales team if we (sipgate) can pay for open sourcing this feature, worth a try.

**Comment by oliverpool** [comment]
@derveloper did you get any feedback?

@valyala thank you so much for this amazing open-source project :heart: 
You don't owe "us" (non-enterprise/paying users) anything. "We" should simply be grateful for all the open source code you made freely available.

I totally understand that you want to monetize this project. Did you consider allowing github sponsors or equivalent? (some people were successful at doing ":moneybag: Sponsorware": https://github.com/sponsorware/docs ) - maybe I could open a new issue about that, if you want.

_(I just go VictoriaMetrics running on a first-gen raspberry pi with [gokrazy](https://gokrazy.org/) and it works perfectly!)_

**Comment by Shangchengzhi** [comment]
> > 抱歉，但这在现实生活中没有任何意义。第一个点可能是异常值甚至是空值，因此会扭曲下采样周期。avg() 在一般使用中更有意义，并且是其他 TSDB 的默认值。
> 
> 虽然该`avg_over_time()`功能可以很好地用作 gauges 的下采样功能[，](https://prometheus.io/docs/concepts/metric_types/#gauge)但在一般情况下它不适用于[计数器。](https://prometheus.io/docs/concepts/metric_types/#counter)最好在计数器的每个下采样间隔上获取第一个样本，因为它不会引入计算错误，例如`rate(m[d])`，并且`increase(m[d])`会在下采样间隔的下采样之前和之后返回相同的结果`d`。
> 
> 补充笔记：
> 
> * 在此之后，下采样的样本`avg`不能在更大的间隔上下采样，因为[平均值的平均值不等于真实平均值](https://convalytics.com/statistics/taking-an-average-of-averages-why-its-wrong/)。
> * 下采样间隔上的`avg`损失峰值（又名最小值和最大值）。在某些情况下，尖峰可能包含重要信息。例如，他们可以帮助回答诸如`what was the maximum memory usage for the app on the given time range?`.
> * 每种类型的下采样都会丢失一部分原始信息。最优化的下采样函数`histogram_over_time()`来自[MetricsQL](https://docs.victoriametrics.com/MetricsQL.html)，因为它保存了原始值分布，并且其结果可用于多级下采样。查看[有关 VictoriaMetrics 直方图的更多信息](https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350)。不幸的是，此函数为每个输入序列生成数十个输出序列，因此下采样序列可能比原始序列占用更多磁盘空间。
> * 大多数用户希望每个时间序列单独执行下采样。但这会随着新的监控类型（例如 Kubernetes 监控）而迅速改变。它可以在每次部署或任何 k8s 集群状态变化（又名高流失率）期间以高速率生成新系列。每个系列的下采样在减少磁盘空间和提高高流失率系列的查询性能方面可能无效，因为它不会减少系列的数量，也不能显着减少每个系列的样本数量（因为原始系列很短）。
> * [VictoriaMetrics 和 Prometheus 都返回通过/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries)`step`请求的每个间隔的最后一个原始样本值，例如，它们在查询期间使用函数的类似物  进行下采样。[在此处](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness)查看有关此内容的更多详细信息。VictoriaMetrics 中计划的下采样函数 - - 与 Prometheus 和 VictoriaMetrics 的行为更一致，例如原始数据和下采样数据上的图形看起来相似。[](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries)`last_over_time()`[](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness)`first_over_time()`
> 
> 如您所见，很难提供涵盖大多数边缘情况的通用实现。因此，我们决定从与 Prometheus 和 VictoriaMetrics 在查询期间使用的动态下采样相一致的基本实现开始。
> 
> VictoriaMetrics 已经提供了一个工具，可以设置自定义下采样 - [vmalert](https://docs.victoriametrics.com/vmalert.html)。[它允许通过记录规则](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/)设置任意下采样类型。这些规则会定期针对`-datasource.url`（例如针对 VictoriaMetrics）进行评估，评估结果会发送到`-remoteWrite.url`。请注意，`-datasource.url`and`-remoteWrite.url`可以指向具有不同设置的不同数据库，包括保留期。通过这种方式，可以仅为长期指标设置下采样，而将其余指标留在短期存储中。
> 
> > 此功能是否仅在企业版中可用？
> 
> [正如企业页面](https://victoriametrics.com/enterprise.html)上所承诺的那样，下采样将在开始时以企业包的形式提供。稍后它可以被移植到 VictoriaMetrics 的社区版。

How smooth is the down sampling function in the enterprise version?，
Clould you provide an estimation on when this would be available on community edition?

**Comment by wdeviers** [comment]
I think a good use-case for downsampling in the open-source release is actually a pretty trivial replacement case - cacti.

We use Cacti in a lot of places purely because RRD can handle graphing data points out to 5 years easily.  Having 5 or 10 year trend data is pretty important.  The options for doing that kind of thing in the Prometheus ecosystem are way, way more complex than they need to be.

So not to be snarky, but - Cacti can do it.

**Comment by VIEWVIEWVIEW** [comment]
Is this already implemented in the open source version? I currently use TimeScaleDB with aggregation buckets, but I thought about migrating over to VM and cannot find more info about this.

**Comment by odinsy** [comment]
Guys, is this feature still only for Enterprise users?

**Comment by hagen1778** [comment]
> Guys, is this feature still only for Enterprise users?

Hi @odinsy! Yes, it is a part of the Enterprise offering.

**Comment by snimavat** [comment]
Is there any hope, tht it would be available in opensouce version ?

If not, what is the workaround, how do others workaround ? scheduled jobs ?

**Comment by isavcic** [comment]
@tamcore care to share?

**Comment by tenmozes** [comment]
You can do that on the infrastructure level in OpenSource. You need to use two groups of vminsert + vmstorage, with different retention and mindedupinterval send the same data to both via vmagent. The storage groups with the higher retention should have higher mindedupscrape
