### ISSUE TITLE
Add vmctl retry-policy with backoff 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3600]
### Is your feature request related to a problem? Please describe

Add vmctl retry policy to vmctl 

### Describe the solution you'd like

Wrap in some bash script

**Comment by valyala** [comment]
The retry logic on data migration failures has been included in [vmctl](https://docs.victoriametrics.com/vmctl.html) since [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). Leaving the feature request open until the retry logic is implemented for VictoriaMetrics native protocol - see [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3859).

**Comment by valyala** [comment]
The retry logic for VictoriaMetrics native protocol has been added to `vmctl` starting from [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3859). Closing the feature request as done.
