### ISSUE TITLE
Replay scraping for certain range of time Or automatically

### ISSUE THREAD

**Issue by mabed-fr** [VictoriaMetrics/VictoriaMetrics#3635]
### Is your feature request related to a problem? Please describe

I'm frusten because when my VictoriaMetrics is DOWN i have holes in my graphs
![image](https://user-images.githubusercontent.com/25350431/211885302-f05a782d-3173-40c2-ae6f-6e3454d463be.png)

### Describe the solution you'd like

The solution is replay for a range of timestamp

### Additional information

I use netdata exporter and netdata keep minimum 1 days of metrics

**Comment by zekker6** [comment]
Hi @mabed-fr 

Due to nature of scraping process it is not possible to do a "replay'. Scraping process fetches current metrics from exporters (such as netdata agent), there is no support of providing some kind of timestamp and fetch state for the given period of time.

In order to fix that behavior you need to make your VictoriaMetrics(VM) installation more fault-tolerant.
You could use vmagent for metrics scraping and set `-remoteWrite.maxDiskUsagePerURL` flag to enable data buffering on vmagent side when your VM installation is not available. 
In this case vmagent will continue scraping data from netdata agent even when VM will not be available and when VM will become available vmagent will push buffered data so that there will be no holes in resulting graphs.
To make vmagent HA you could set up 2 vmagent instances with exactly the same config and configure [deduplication](https://docs.victoriametrics.com/#deduplication) on VM side by providing `-dedup.minScrapeInterval` flag.

Additionally, in order to make VM installation HA you could you [cluster version](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) of VM. It does not have single point of failure, so that taking one node down won't make whole installation down.

**Comment by mabed-fr** [comment]
I am looking for a way to be able to send data in the event of an incident, I manage to generate a json or csv but not in the format supported by victoria metrics

Here is an example csv


[16:12:34_01_13_2023.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10412892/16.12.34_01_13_2023.csv)

**Comment by zekker6** [comment]
@mabed-fr VictoriaMetrics does support data import in CSV/JSON - https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-import-time-series-data

As far as I can see in the example CSV file, it contains multiple metrics with different number of values/labels per each metric. Since `/api/v1/import/csv` accepts single `format` argument it won't be able to parse this format properly.

You can either export those metrics into different files and run import per metric or use JSON format if it will be easier to export in supported format.
