### ISSUE TITLE
VM count differs from prometheus

### ISSUE THREAD

**Issue by oOHenry** [VictoriaMetrics/VictoriaMetrics#365]
**Describe the bug**
I have a metric that had a few failed scrapes. The result of `count` is sometimes twice as much as it should be. See attached screenshot.

**Expected behavior**
Have the same result as prometheus has.
**Screenshots**
![prometheus query](https://user-images.githubusercontent.com/16702685/76300246-b51a6100-62bc-11ea-966c-a444ed0705b5.png)
![victoria metrics query](https://user-images.githubusercontent.com/16702685/76300256-b6e42480-62bc-11ea-85f9-f87fdc9cc446.png)

**Version**
```
$ vmselect --version
vmselect-20200303-200611-tags-v1.34.2-cluster-0-g50190263
```

**Comment by valyala** [comment]
@oOHenry , could you show graphs on the same time ranges for Prometheus and VictoriaMetrics for the following query?
```
count(count_over_time(ceph_osd_in{cluster="u01c01"}[10m])) by (cluster)
```

**Comment by oOHenry** [comment]
count_over_time:
![prometheus count_over_time](https://user-images.githubusercontent.com/16702685/76392691-59aaaa80-6372-11ea-99f1-3d519ce3e6c7.png)
![vm count_over_time](https://user-images.githubusercontent.com/16702685/76392693-5adbd780-6372-11ea-85a9-1a184b5b386e.png)

**Comment by valyala** [comment]
So it looks like there are periodically updated labels in `ceph_osd_in` metric, which result in creating new time series. The line of the graph goes 2x when the label is updated during the last 5 minutes. The line goes 3x on the time range `8:00-8:05` when the label is updated two times during the last 5 minutes.

VictoriaMetrics draws 2x spikes for the original query, because it determines the end of time series slightly differently comparing to Prometheus:
* Prometheus inserts `staleness marker` when the time series is no longer available. These markers are used later by Prometheus in order to determine the end of time series - see [these docs](https://www.robustperception.io/staleness-and-promql) for details.
* VictoriaMetrics doesn't support `staleness markers`, since it may accept data via [different ingestion protocols](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-time-series-data), which have no `staleness markers` support. So it detects the end of time series by looking at interval between samples in the time series. It assumes that the time series is alive for 2x scrape interval after the last sample. So it may count two time series when the label on the `ceph_osd_in` metric changes during 2x interval.

I'll think how to fix this issue.

In the meantime try the following workaround: `count(ceph_osd_in{cluster="u01c01"}[1s])` instead of `count(ceph_osd_in{cluster="u01c01"})` - note the added `[1s]` in the query. This should reduce the `alive` interval after the end of time series from 2x scrape interval to `1s`.

**Comment by jvikare** [comment]
Hello,

We seem to be running into issues with the lack of staleness markers support as well. This is causing a lot of discrepancies in many of our boards and its currently blocking us from proceeding with our evaluation of VM.

We have a lot of metrics which can disappear and reappear in a relatively short time, such as requests and timeouts. An example of a gauge metric displaying request timings when requests occur (which can be sporadic) show likes this in Prometheus:

![prom_samples](https://user-images.githubusercontent.com/62350770/76990386-8f422b80-6950-11ea-8392-d10489f02b96.png)

However VM continues to report samples when they don't exist:
![vm_samples](https://user-images.githubusercontent.com/62350770/76990568-d4fef400-6950-11ea-9c3b-64b56d77590d.png)

If this was a sum, the use of sum_over_time aggregation seems to mitigate to some degree - however this does not apply to aggregations with avg_over_time/max_over_time/etc.

The discrepancies are fairly visible when plotting both with the nulls as zero or connected options:
1) Null as zero (Prom/VM):
![prom_naz](https://user-images.githubusercontent.com/62350770/76991080-b2210f80-6951-11ea-9194-5575cfb239ce.png)
![vm_naz](https://user-images.githubusercontent.com/62350770/76991184-d5e45580-6951-11ea-8b54-37fbcbfea7bf.png)

2) Connected (Prom/VM):
![prom_ncon](https://user-images.githubusercontent.com/62350770/76991353-2065d200-6952-11ea-81d3-bf1761ecd19d.png)
![vm_ncon](https://user-images.githubusercontent.com/62350770/76991442-42f7eb00-6952-11ea-8b74-f491a85e21b2.png)

I was wondering if there's any plan to implement some level of support for Prometheus staleness markers. We'd like to be able to use the same dashboards against both Prometheus/VM and graph consistency is really important to us.

**Comment by valyala** [comment]
@jvikare , the [v1.34.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release gains support for `-search.maxStalenessInterval` command-line flag, which can be used as a workaround for the issue. Try setting it to the value slightly bigger than the maximum scrape interval for time series stored in VictoriaMetrics.

**Comment by valyala** [comment]
@oOHenry , did you try passing small durations in the range `[10s ... 60s]` to `-search.maxStalenessInterval` command-line flag in order to fix this issue? Note that response cache must be reset after updating `-search.maxStalenessInterval` flag in order to remove previously cached invalid responses. The cache may be reset by querying `http://vmselect:8481/internal/resetRollupResultCache` endpoint on every `vmselect` node in the cluster version of VictoriaMetrics.

**Comment by oOHenry** [comment]
@valyala I did set the `search.maxStalenessInterval` to 2m. Which is the double of my highest scrape interval as recommended in: [issue 383]( https://github.com/VictoriaMetrics/VictoriaMetrics/issues/383#issuecomment-605288117).

**Comment by valyala** [comment]
@oOHenry , try reducing the `-search.maxStalenessInterval` to a single scrape interval.

**Comment by jvikare** [comment]
@valyala, you when refer to the "maximum scrape interval"  in your comment in #383, do you maybe mean the most frequent interval? 

For example, if most of my metrics are scraped every 15 seconds and 30 seconds, and only a very small subset of metrics are scraped every 5 or 10 minutes, am I correct to presume that setting search.maxStalenessInterval to a value greater than 15 seconds (e.g. search.maxStalenessInterval=30s) would do the trick?

Because if I set it to e.g. double the maximum scrape interval of 10 minutes; (e.g. search.maxStalenessInterval=1200s) I'm still seeing VM showing samples after a metric has gone stale (using v1.35.5).

**Comment by valyala** [comment]
> when you refer to the "maximum scrape interval" in your comment in #383, do you maybe mean the most frequent interval?

Yes. Try using `-search.maxStalenessInterval=30s` or even `-search.maxStalenessInterval=15s`. Note that it is recommended using a single scrape interval across all the targets in Prometheus - see [this article](https://www.robustperception.io/keep-it-simple-scrape_interval-id) for details.

**Comment by valyala** [comment]
FYI, VictoriaMetrics and vmagent gain support for Prometheus staleness markers. This should fix the inflated `count()` results when scrape targets disappear. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526#issuecomment-898323054 for details. Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526 .

**Comment by valyala** [comment]
FYI, VictoriaMetrics and vmagent gained support for Prometheus staleness markers starting from [the release v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by oOHenry** [comment]
@valyala Thanks for implementing, I'm really happy to see this feature finally in victoria metrics. How do you recommend to set the `-maxStalenessInterval`? Just let the default value?
