### ISSUE TITLE
“count_over_time” Query results are inconsistent

### ISSUE THREAD

**Issue by dewey363** [VictoriaMetrics/VictoriaMetrics#373]
The query is right, but the result is wrong. You can try
`sum(count_over_time(metrics_name{domainName=~"xxxx.com"}[1m]))`
`sum(count_over_time(metrics_name{domainName=~"xxxx.com"}[1m] > 0))`
The results of the two queries are inconsistent (edited)

**Comment by valyala** [comment]
The second query is automatically converted by VictoriaMetrics to `sum(count_over_time(last_over_time(metrics_name[1m]) > 0)[$__interval])`. This query is different comparing to the first query, so it returns different results.

If you need calculating the number of raw data points, which are greater than the given `value` over the given `interval`, then use the following query:
`sum(share_gt_over_time(metrics_name[inyerval], value) * count_over_time(metrics_name[interval]))`

It uses `share_gt_over_time` function from [MetricsQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL).

**Comment by dewey363** [comment]
![image](https://user-images.githubusercontent.com/18144072/77026625-13d38f00-69cf-11ea-932e-b9f5393c53a1.png)
There should be no decimal point in the total

**Comment by valyala** [comment]
The `share_gt_over_time` function returns floating-point value in the range `[0...1]`. Then this value is multiplied by the number returned from `count_over_time()`. The result may be non-integer due to rounding errors. If you need integer result, then wrap the query into `round()` function:
```
round(
sum(share_gt_over_time(metrics_name[inyerval], value) * count_over_time(metrics_name[interval]))
)
```

See [docs about round function](https://prometheus.io/docs/prometheus/latest/querying/functions/#round).

**Comment by denisgolius** [comment]
Closing it as done.
