### ISSUE TITLE
Add more CPUs or reduce load

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#377]
**Describe the bug**
```
2020-03-17T17:37:14.397Z        error   VictoriaMetrics/lib/ingestserver/opentsdbhttp/server.go:90      error in "/api/put": cannot store metrics: Cannot add 10349 rows to storage in 30s, since it is overloaded with 64 concurrent writers. Add more CPUs or reduce load
```
**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./victoria-metrics-prod -version
victoria-metrics-20200226-202222-tags-v1.34.1-0-g63a88a61
```
how can i avoid this question

**Comment by hagen1778** [comment]
Hi @yincongcyincong!
The error message says that VM is overloaded by concurrent inserts and can't handle the load. This could happen because of miss-configured clients or because of limited resources. Please keep in mind, that it is recommended to have N connections for inserts, where N equal to number of CPU. Please see following article for details https://github.com/VictoriaMetrics/VictoriaMetrics#capacity-planning

It could help if you provide more info about your setup: writers, insertion rates, readers, VM hardware. I also encourage you to [monitor](https://github.com/VictoriaMetrics/VictoriaMetrics#monitoring) VM with our dashboards. It might help you to detect the issue.

**Comment by yincongcyincong** [comment]
ok， i get it
