### ISSUE TITLE
data lost question

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#378]
**Describe the bug**

i search data from vm, but the data is abnormal。
i find some data lost。
![11584680280_ pic_hd](https://user-images.githubusercontent.com/24344673/77137937-d9d7bb00-6aaa-11ea-949b-43a9d1d5b30d.jpg)
![21584680309_ pic_hd](https://user-images.githubusercontent.com/24344673/77137956-ec51f480-6aaa-11ea-9cdb-3e2ff3fa38f4.jpg)
but When I look up data from another time period，it‘s normal。
i use ```/internal/resetRollupResultCache``` to clean cache. It's still like this
i want to solve, thanks

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
/usr/local/vm/vm/victoria-metrics-prod -version
victoria-metrics-20200226-202222-tags-v1.34.1-0-g63a88a61
```

**Used command-line flags**
```
./victoria-metrics-prod -opentsdbHTTPListenAddr=:4222 -httpListenAddr=:8428 -storageDataPath=/data1/victoria-metrics-data/ -promscrape.maxScrapeSize=167772160 -search.maxUniqueTimeseries=10000000 -retentionPeriod=6 -memory.allowedPercent=50 -dedup.minScrapeInterval=60s  
```

**Comment by hagen1778** [comment]
Hi @yincongcyincong!
Could you pls post a screenshot with result for a query without `sum` function?

**Comment by yincongcyincong** [comment]
sorry，the data is deleted

**Comment by valyala** [comment]
This may be related to #360 . @yincongcyincong , could you upgrade to [v1.34.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verify whether the issue is fixed? Note that the folder `<-storageDataPath>/cache` folder must be removed after stopping the previous version of VictoriaMetrics and before starting v1.34.4 , since the folder may contain cached incomplete data.

**Comment by yincongcyincong** [comment]
ok thanks
