### ISSUE TITLE
Add Relabeling Playground into VMUI (integration with vmagent)

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3807]
### Is your feature request related to a problem? Please describe

We need to add vmagent into vmui 

Existing UI - https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/metric-relabel-debug

vmagent changes 
- combine Metrics Relabeling with Target Releveling - on vmagent side (backend) - @dmitryk-dk 

vmui changes

- add an option to specify vmagent URL 
- move UI from example tp vmui 
- provide examples 

### Describe the solution you'd like

^

**Comment by hagen1778** [comment]
> add an option to specify vmagent URL

Can it work without vmagent?

**Comment by tenmozes** [comment]
as far i know, internal implementation really on some matching between what is in the config and on UI. so you need a vmagent 

```
        targetID := r.FormValue("id")
	metric := r.FormValue("metric")
```
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/relabel_debug.go#L12

**Comment by valyala** [comment]
@Loori-R , there is an issue in [the relabel debug UI](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/relabeling) - the `enter` key doesn't create new line as most users expect. Could you fix it?

**Comment by valyala** [comment]
The [relabeling debug](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/metric-relabel-debug) functionality has been included in [vmui](https://docs.victoriametrics.com/#vmui) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this example at VictoriaMetrics playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/relabeling).

Closing the feature request as done.

P.S. the issue with `enter` key will be fixed in the next release after [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4294) will be ready for merge.
