### ISSUE TITLE
Integrate WITH template playground with vmui 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3811]
### Is your feature request related to a problem? Please describe

Integrate https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/expand-with-exprs with vmui 

It may require work from the backend side if we want to add format functionality and related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/267 ( cc @dmitryk-dk )

### Describe the solution you'd like

^

**Comment by valyala** [comment]
@Loori-R , there are two issues with [WITH templates playground at VMUI](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/expand-with-exprs):

1. The query `1 + 1` leads to an error because it is incorrectly encoded when passed to the server. It should be encoded with [url encoding](https://en.wikipedia.org/wiki/URL_encoding).
2. The entered query isn't stored in the VMUI url. This prevents from copy-n-pasting the url to colleagues via email / slack / etc.

**Comment by valyala** [comment]
The third issue is that the `enter` key on the keyboard doesn't create newline when writing the query. Also make sure that `up`, and `down` keys move the cursor up / down as most users expect.

**Comment by valyala** [comment]
[WITH template playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/expand-with-exprs) is available in [vmui](https://docs.victoriametrics.com/#vmui) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this example at VictoriaMetrics playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/expand-with-exprs).

Closing the feature request as done.

The issues mentioned at [these comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3811#issuecomment-1539629676) will be fixed in the next release after [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4294) will be ready to be merged.
