### ISSUE TITLE
Introduce Remote Write Status Endpoint 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3847]
### Is your feature request related to a problem? Please describe

As we added support of zstd compression to remotewrite at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1225 we need to introduce an endpoint that returns the compression we support on the TSDB side. 

We also need to verify the case when vmagent has a persistent queue, and we switch protocol from snappy to zstd 

### Describe the solution you'd like

new endpoint

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent.html) automatically detects whether the remote storage supports [VictoriaMetrics remote write protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol) starting from the commit c080443fef1d7af47705ab8eeea724cb2efe2681 . This commit will be included in the next release.

It is possible to force using Prometheus remote write protocol instead of VictoriaMetrics remote write protocol when sending the data to `-remoteWrite.url` by passing `-remoteWrite.forcePromProto` command-line flag.

**Comment by valyala** [comment]
Closing this issue, since it is a part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1225

**Comment by valyala** [comment]
> We also need to verify the case when vmagent has a persistent queue, and we switch protocol from snappy to zstd

`vmagent` drops packets if they are encoded with wrong format and the remote storage rejects accepting them. This means that `vmagent` should automatically drop pending data in incorrect format stored on disk after the upgrade / downgrade.
