### ISSUE TITLE
VM Agent Remote write connection saturation and push latency are high

### ISSUE THREAD

**Issue by waleedabdelwahed89** [VictoriaMetrics/VictoriaMetrics#3893]
### Describe the bug

We are running our VM Agent on 3 ec2 instances in 1 VPC, and the VM cluster on 12 ec2 instances in a different VPC, both are connected via private link

 vmagent => private link => ALB => vminsert => vm storage 

There's always a lag for the remote write for which the data is not updated instantly, also the push duration is high (5s) while it should be few ms
We couldn't find any congestion in the network layer 

There're no errors in the VM cluster logs (insert and storage) also the servers resources are optimized, but there is EOF error in vmagent log which shared below

Any suggestion will be highly appreciated. Thank you

### To Reproduce

#vmagent.yaml

[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
Type=simple
LimitCORE=infinity
LimitNOFILE=1000000
LimitNPROC=1000000

ExecStart=/server/vm/vmagent-prod \
  -promscrape.config=/server/prometheus/prometheus.yml  \
  -remoteWrite.showURL=true \
  -remoteWrite.queues=200 \
  -remoteWrite.url=http://ALB/api/v1/write \
  -promscrape.maxScrapeSize=300MB \
  -promscrape.streamParse=true \
  -promscrape.noStaleMarkers=true \
  -promscrape.dropOriginalLabels=true \
  -promscrape.suppressScrapeErrors=true \
  -promscrape.cluster.membersCount=3 \
  -promscrape.cluster.memberNum=0 \
  -promscrape.config.strictParse=false\
  -remoteWrite.maxDiskUsagePerURL=20GB \
  -remoteWrite.tmpDataPath=/server/vm/vmagent-remotewrite-data
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target 

==============
#storage

${victoria_home}/vmstorage-prod \
      -storageDataPath ${data} \
      -search.maxUniqueTimeseries=50000000 \
      -retentionPeriod 180d \
      -search.maxTagKeys=1000000 \
      -search.maxTagValueSuffixesPerSearch=1000000 \
      -search.maxTagValues=1000000 \
      -loggerFormat=json \
      -loggerTimezone ${TIMEZONE} \
      -loggerLevel ${LOG_LEVEL} &> ${log}/storage.log &

=============
#insert

${victoria_home}/vminsert-prod \
      -maxInsertRequestSize=1GB \
      -maxConcurrentInserts=1000 \
      -http.connTimeout=4000s \
      -http.idleConnTimeout=4000s \
      -loggerFormat=json \
      -maxLabelsPerTimeseries=61 \
      -replicationFactor=1 \
      -disableRerouting \
      -loggerTimezone ${TIMEZONE} \
      -loggerLevel ${LOG_LEVEL} &> ${log}/insert.log &

### Version

v1.88.1

### Logs

Mar 02 16:07:55 vmagent-prod[28569]: 2023-03-02T16:07:55.534Z        warn        VictoriaMetrics/app/vmagent/remotewrite/client.go:370        couldn't send a block with size 223056 bytes to "1:http://ALB/api/v1/write": Post "http://ALB/api/v1/write": EOF; re-sending the block in 2.000 seconds
Mar 02 16:08:21 vmagent-prod[28569]: 2023-03-02T16:08:21.783Z        info        VictoriaMetrics/lib/promscrape/scraper.go:427        eureka_sd_configs: added targets: 1, removed targets: 0; total targets: 3090
Mar 02 16:08:33 vmagent-prod[28569]: 2023-03-02T16:08:33.195Z        warn        VictoriaMetrics/app/vmagent/remotewrite/client.go:370        couldn't send a block with size 231055 bytes to "1:http://ALB/api/v1/write": Post "http://ALB/api/v1/write": EOF; re-sending the block in 2.000 seconds

### Screenshots

<img width="801" alt="image" src="https://user-images.githubusercontent.com/55146056/222494724-84010790-4942-40fa-8828-d0d7b74254b0.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/55146056/222495859-d549bdfe-03a0-4fb5-853d-64bd9ec296a0.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/55146056/222494941-d93ba318-7d90-49d4-a098-714b725e5ea0.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/55146056/222496050-6ef316f3-731d-43b8-99a7-76b49d1bd960.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/55146056/222496196-c6135a56-cca0-4ff4-ba61-3e9421126a82.png">

**Comment by waleedabdelwahed89** [comment]
Hi @f41gh7 @valyala , i'd appreciate any advise here
Thanks

**Comment by hagen1778** [comment]
Hello @waleedabdelwahed89!
There are 3 main players here:
1. vmagent, which scrapes and sends the data
2. vminsert, which receives and process the data
3. network/balancers between 1 and 2

The congestion is possible for all three. I suggest following the following troubleshooting steps:
1. Is there a contention on vmagent? If vmagent doesn't have enough resources to keep up with data stream, the saturation will be high. Check CPU and mem params to see if that's the problem.
2. Is there a contention on vminsert? vminsert could be saturated by CPU and mem as well. Please check its resource usage. Please also check connection saturation between vminsert and vmstorage (is present on the official Grafana dash). Because if connection between them is saturated, vminsert will be limited in speed and won't be able to process data from vmagent fast enough.
3. Is the balancer a bottleneck? It could be if first 2 steps showed nothing. Try to rule out the balancer by pointing vmagent directly to vminserts. Or by doing an experiment and place something (vmsingle, for example) next to vmagent in the same network and fanout data stream into it.

**Comment by hagen1778** [comment]
> "cannot decompress request with length 2254: snappy: corrupt input"

are the versions of vmagent and vminsert the same?
