### ISSUE TITLE
vmalert generates an error alert

### ISSUE THREAD

**Issue by LeonYanghaha** [VictoriaMetrics/VictoriaMetrics#3965]
### Is your question request related to a specific component?

This rule is set in vmalert, and the result is required to be greater than 100：
`sum (increase(point_total{srv="point", type="5"}/10000 [60s])) by (dc)> 100`

surprisingly, I received an alert generated by this rule。
However, when I see the corresponding indicators in grafana, there should be no alert.

![image](https://user-images.githubusercontent.com/23301914/225578331-e133c519-99b2-4d1e-bb07-f4477455b99e.png)

`Version of vmalert: v1.79.8`

### Describe the question in detail

vmalert generates an error alert

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@LeonYanghaha Could you check vmalert [alerts state UI](https://docs.victoriametrics.com/vmalert.html#alerts-state) for an alert that have fired?
This UI shows state changes for alert and includes a curl command which you can use to get exactly the same data as vmalert received to check why exactly alert was fired.

**Comment by LeonYanghaha** [comment]
@zekker6 
Thank you for your answer. I saw the information, but I can't solve my problem。

![20230316-181208](https://user-images.githubusercontent.com/23301914/225585458-8e8d6ed0-95a4-4e6c-bf41-575eaaa14a72.jpg)

**Comment by zekker6** [comment]
@LeonYanghaha Could you run command provided by vmalert to verify what was the result of query execution that triggered an alert? 
Using parameters listed there and using instant requests to build the same query in Grafana will also work.

It is important to use exactly the same parameters because vmalert uses [instant queries](https://docs.victoriametrics.com/keyConcepts.html#instant-query) to get the data for alerts and can use different `step` than Grafana will use for this query. By default, Grafana uses [`query_range`](https://docs.victoriametrics.com/keyConcepts.html#range-query) endpoint to render graphs which is processed a bit different. This might lead to different execution results than you will see when checking against same query in Grafana.

**Comment by LeonYanghaha** [comment]
@zekker6 Thank you very much for your answer. Query and query_ The results of range do vary greatly, but I would like to know more details.

**Comment by zekker6** [comment]
@LeonYanghaha The core difference is that `query` endpoint is used to evaluate query at the given point in time. When there is no data points at this exact point in time than the closest data points will be used. The most common use case for this is alerts calculation.

`query_range` is used to get a set of data points on some interval in time. These queries are evaluated on the given `[start .. end]` with `step` used as iteration. This type of queries might return so-called `ephemeral` data points in case real data point is missing for some point in time. This is most commonly used to graph some data.

You can find more examples and details in the [key concepts](https://docs.victoriametrics.com/keyConcepts.html#query-data) documentation section.

**Comment by zekker6** [comment]
Going to close this as original issue have been resolved, feel free to reopen if new questions will arise.
