### ISSUE TITLE
Can VictoriaMetrics be used in Machine Learning senario with series-like (but not monitoring) data?

### ISSUE THREAD

**Issue by lichuan0620** [VictoriaMetrics/VictoriaMetrics#3995]
### Describe the question in detail

For machine learning, we have these "score vs step" data that highly resemble time series data. We can just imagine these steps as timestamps with fixed intervals and starts at 0.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/7102510/227124982-d256f7e9-c851-4d1a-975c-526f19c93a74.png">

Each series will be tagged with metadata such as model version and training session, which are just labels.

I know VictoriaMetrics support backfilling, so my first thought was to import those data as time series with timestamps starting at 0, but that could be problematic since frequently loading data with early timestamp might not be a good idea.

So my question is, is my theory worth exploring, or is it recommended to explore VictoriaMetrics for this scenario at all?

Of course, any potential development on top of VictoriaMetrics engine is acceptable. Just discussing possibility here.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@lichuan0620 You can definitely do this, even though it will require to do some adjustments in raw data.
VictoriaMetrics uses unix timestamps as timestamps format, so writing values with 0 timestamp value would create a data point very far in the past. Instead, you could choose some specific date(and timestamp value) and write data with an offset based on step. 
Note that timestamps must be within [`retentionPeriod`](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention) as otherwise those data points will be ignored.

Another option might be to use beginning of the week/month/year so that it will be easy to directly compare models performance within some timeframe. Also, you will be able to use [`at`( `@`) operator](https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier) to shift query in time and compare previous timeframe value to current ones.
