### ISSUE TITLE
How do I write an "or" logical operator 

### ISSUE THREAD

**Issue by groobyming** [VictoriaMetrics/VictoriaMetrics#3997]
### Describe the question in detail

I need to write a MetricsQL that uses label-filter.

eg：
{id='1' or name='admin' or age='24'}

But I can't find any documentation about it

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
@groobyming you can use query like that:

```javascript
{id="1"} or {name="admin"} or {age="24"}
```

**Comment by groobyming** [comment]
> @groobyming you can use query like that:
> 
> ```js
> {id="1"} or {name="admin"} or {age="24"}
> ```
Thanks,
But it is only used in instance selector, it doesn't work when used in range select
eg:
sum_over_time({id='1' or name='admin' or age='24'}[10m])

**Comment by groobyming** [comment]
> @groobyming What if a lot of different metrics will be returned by selector? What you want to see as result?

I want all deduplicated metrics that meet the conditions

**Comment by valyala** [comment]
The proposed query above doesn't work as expected because VictoriaMetrics implicitly enables [subquery](https://docs.victoriametrics.com/MetricsQL.html#subqueries) calculations for this query. E.g. it substitutes the query:

```metricsql
sum_over_time(
  union(
    {id='1'}, 
    {name='admin'}, 
    {age='24'}
  )[10m]
)
```

With the following query before execution:

```metricsql
sum_over_time(
  union(
    default_rollup({id='1'}[1i]), 
    default_rollup({name='admin'}[1i]), 
    default_rollup({age='24'}[1i]),
  )[10m:1i]
)
```

The results of this query depend on `1i`, which equals the the `step` query arg passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyConcepts.html#range-query) or [/api/v1/query](https://docs.victoriametrics.com/keyConcepts.html#instant-query).

See [these docs](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions) for more details.

Unfortunately, VictoriaMetrics doesn't support the ability to set multiple `or` filters for **distinct** labels in a single [filter expression](https://docs.victoriametrics.com/keyConcepts.html#filtering). This request appears periodically, so, probably, it is time to add support for `{filter1 or filter2 ... or filterN}` into VictoriaMetrics. @Amper , could you investigate the possibility of adding support for `or` filters for **distinct** labels inside a single filter expression?

If you need to set multiple `or` filters for **the same** label, then just put them into regexp filter. For example, the following filter matches time series with the label `foo` with values `v1`, `v2` or `v3`: `{foo=~"v1|v2|v3"}`.

If you are searching for [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) equivalent for something like `select sum(metric) from table where id=1 or name='admin' or age='24', then try the following query:

```metricsql
sum(
  sum_over_time({id='1'})
  or sum_over_time({name='admin'})
  or sum_over_time({age='24'})
)
```

See also [Migrating from InfluxDB to VictoriaMetrics](https://docs.victoriametrics.com/guides/migrate-from-influx.html) docs.

**Comment by valyala** [comment]
FYI, VictoriaMetrics gains support for `or`-delimited series selectors inside curly braces starting from the following commits:

- Single-node version of VictoriaMetrics - 4cb024d8a3a2cdd0b14ee6850770ba114e3537e7 . See [how to build single-node VictoriaMetrics from this commit](https://docs.victoriametrics.com/#how-to-build-from-sources) in order to evaluate this functionality before the release.
- Cluster version of VictoriaMetrics - a7fdc3fcc75b99e1a41aa38c77f2911b36f92b7e . See [how to build VictoriaMetrics cluster from this commit](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

These commits will be included in the next release.
