### ISSUE TITLE
[question] Query direct on UI like Prometheus

### ISSUE THREAD

**Issue by bientt210** [VictoriaMetrics/VictoriaMetrics#401]
Hi,

I have a question, I often using Prometheus UI to check query directly, and now my VictoriaMetrics has all data of prometheus,  so how can do if i want to check query like on Prometheus UI instead of go to Grafana

Thanks you

**Comment by valyala** [comment]
Unfortunately VictoriaMetrics has no such UI at the moment. There is [a long-standing feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4) for adding `/graph` page to VictoriaMetrics like in Prometheus, but it has pretty low priority at the moment, since Grafana covers the majority of use cases for `/graph` page in Prometheus.

**Comment by valyala** [comment]
See also [vmui](https://github.com/VictoriaMetrics/vmui).

**Comment by denisgolius** [comment]
Closing it as done.
