### ISSUE TITLE
vmagent: allow viewing all target when in cluster mode

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4018]
### Is your feature request related to a problem? Please describe

When in [cluster mode](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets), vmagent splits the list of targets among the configured shards. One shard starts to scrape only 1/N fraction of all configured targets, and so it shows on /targets page as well.

Each vmagent shard has its own share of targets to scrape. But there is no way to view the global list of all configured targets via UI. 

### Describe the solution you'd like

It would be nice to have the option to see the global list of all the target via vmagent's UI or vmui. Or at least have the option to see the list of targets per selected vmagent in UI.
This can be achieved in two ways:
1. vmagents can be instructed to be aware of other cluster shards. This can be done via cmd-line flag in the same fashion as vmselects know about each other. 
2. vmui can be instructed to be aware of vmagent clusters. This can be done via cmd-line flag in the same fashion as vmselects know about each other. 

Both of the ways are appropriate for the described problem.

**Comment by jnadler** [comment]
We run `vmagent` in k8s as a statefulset.   So what we'd like is:

* pass a new config to `vmagent`, a FQDN like `vmagent-headless.namespace.svc....`
* for statefulsets, DNS lookup against the headless FQDN will return all pod IPs
* when the Targets UI is requested, if this config is set it will perform a DNS lookup, and fan-out requests for the API (JSON) versionof targets, to all pods of `vmagent`
* then consolidate and sort the returned data, and use it in the UI results instead of the local dataset

Would you consider a PR like this?   It would only solve the problem for k8s users, which perhaps isn't ideal.   But this will probably always work differently in k8s; you can't know ahead of time any way to contact the individual pods.

**Comment by valyala** [comment]
FYI, the commit 7cb8ed8271d52cc29ec6b404934f1bf5efa4c30d simplifies debugging of scrape targets at `vmagent` instances in [cluster mode](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets) by displaying all the discovered targets at the `http://vmagent:8429/service-discovery` page. Targets, which were dropped at the current `vmagent` instance because they are sharded to other `vmagent` instances, are marked as `DROPPED (sharding)` on the `/service-discovery` page now. The `status` column for such targets also contains `-promscrape.cluster.memberNum` values for `vmagent` instances, where these targets are scraped.

This commit will be included in the next release. In the mean time it is possible to test this functionality by building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5389 .

**Comment by jnadler** [comment]
Thanks!  In light of this, perhaps a smaller thought?

`The status column for such targets also contains -promscrape.cluster.memberNum`

For our end users, I am concerned that the memberNum will mean nothing.   What if we could specify a URL template, that would substitute in this memberNum, so that a user could click-thru to the `vmagent` pod that is in fact scraping this target?

The reasoning is that having all the targets visible is very nice for our users.   But the more important thing is the scrape result - if we are having some trouble scraping some target, they need to see that (and, ideally, the error message associated with the failure to scrape).

**Comment by valyala** [comment]
> What if we could specify a URL template, that would substitute in this memberNum, so that a user could click-thru to the vmagent pod that is in fact scraping this target?

This sounds reasonable. It has been implemented in the commit e373bb84d5fce8ef82acd445d1eb73efe7777306 . This commit adds an optional `-promscrape.cluster.memberURLTemplate` command-line flag, which can contain url template for `vmagent` instances in the cluster. If this flag is set, then `/service-discovery` page contains links to `vmagent` instances where the given target is scraped. Every `%d` occurrence in this template is replaced with the corresponding `-promscrape.cluster.memberNum` value for the corresponding `vmagent` instance. For example, `-promscrape.cluster.memberURLTemplate='http://vmagent-%d.namespace.svc.local:8429/targets'`.

**Comment by jnadler** [comment]
Wow, this is fantastic!   Thank you very much.

**Comment by valyala** [comment]
`vmagent` displays all the discovered targets at the `http://vmagent:8429/service-discovery` page, including the targets, which were dropped because of [`-promscrape.cluster.*` settings](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets), starting from the release [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done. then.

**Comment by hagen1778** [comment]
Here how it looks in the UI - see `exists at shard-0` link
<img width="858" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/932d5a49-33d8-4e1e-a123-2d6c054b4a1b">

**Comment by grinapo** [comment]
I'm not sure whether @valyala meant me to comment here (in a closed issue) but...

I wish for some **metrics about the snapshots**. Most obvious is their count, I don't know what other metrics do you have handy. (It was about leftover snaps from vmbackup eating up disk space.) This (or maybe their age) could be used in alerting rules.

**Comment by vm2018** [comment]
> Here how it looks in the UI - see `exists at shard-0` link <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/2902918/290242621-932d5a49-33d8-4e1e-a123-2d6c054b4a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzY2MjYsIm5iZiI6MTcxNDczNjMyNiwicGF0aCI6Ii8yOTAyOTE4LzI5MDI0MjYyMS05MzJkNWE0OS0zM2Q4LTRlMWUtYTEyMy0yZDZjMDU0YjRhMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTEzODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYyMTFhMDg5OTRjYTlmOWRmMDkzODVmYTdmMzY5OGExMDIzZTFiYjI0OTgyMzBmZTE3NTVlOGQwOWUwNjc4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMdghjhsx73kQ07w78yebx--JbISR3e339UZD_BVhVo">

i have the same issue with v1.101.0 Version, how to solve it?
