### ISSUE TITLE
can sum_over_time filter duplicate data

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#409]
when i use ```sum_over_time```, Some duplicate data are added.   
and i can't use ```-dedup.minScrapeInterval```, because some data will be sent many in one second.
can ```-dedup.minScrapeInterval``` support  ```ms```?

**Comment by valyala** [comment]
`-dedup.minScrapeInterval` supports milliseconds resolution. For instance, `-dedup.minScrapeInterval=10ms` would remove duplicate samples with timestamps closer than 10ms to each other. The minimum supported value for `-dedup.minScrapeInterval` is 8ms. The commit ded0c0d3c73eba1d05633544cb264b17513b8641 reduces the minimum supported value to 1ms. Such small value can be used for removing samples with duplicate timestamps. The commit will be included into the next VictoriaMetrics release.

Note that if you use [cluster version of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md), then `-dedup.minScrapeInterval` must be set on both `vmstorage` and `vmselect` nodes:

- `vmstorage` de-duplicates the data on the storage in order to reduce disk space usage. The de-duplication is performed during background merges, so newly added data may still contain duplicate samples, which should be removed by `vmselect`.
- `vmselect` de-duplicates the data during queries.

**Comment by yincongcyincong** [comment]
ok， thanks

**Comment by yincongcyincong** [comment]
@valyala when next version will be realeased

**Comment by valyala** [comment]
@yincongcyincong , VictoriaMetrics accepts `-dedup.minScrapeInterval` values smaller than `8ms` starting from [v1.34.8](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). The minimum supported value is `1ms` now - it allows removing samples with duplicate timestamps, since timestamps are stored with millisecond precision in VictoriaMetrics.
