### ISSUE TITLE
Why are totalSeries displayed differently for "/api/v1/status/tsdb" and "/api/v1/series/count"

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4101]
### Is your question request related to a specific component?

vmselect，vmstorage

### Describe the question in detail

Query totalSeries in my vm cluster, and find that the two api paths do not match the display of totalSeries:

# curl 127.0.0.1:8481/select/0/prometheus/api/v1/status/tsdb
{"status":"success","isPartial":false,"data":{"totalSeries":23720741,"totalLabelValuePairs":355789246,"seriesCountByMetricName"
...

# curl 127.0.0.1:8481/select/0/prometheus/api/v1/series/count
{"status":"success","isPartial":false,"data":[84057079]}

One is 23720741 and the other is 84057079.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hi @luzejia.

These APIs have a couple of differences:
- `series/count` counts all data, but `status/tsdb` counts data for a day (the default is a today)
- `series/count` unlike `status/tsdb` may count [deleted time series](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html?highlight=/series/count#how-to-delete-time-series) additionally to normal time series due to internal implementation restrictions;
