### ISSUE TITLE
vmagent 1.90.0 couldn't send a block with size

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#4139]
### Describe the bug

On an absolutely unloaded cluster of version 1.90.0, periodically (once every 30 minutes approximately) I see in the agent logs
2023-04-17T17:11:29.482+0700 warn VictoriaMetrics/app/vmagent/remotewrite/client.go:370 couldn't send a block with size 203 bytes to "7:secret-url": Post "http:// 127.0.0.1:8581/insert/multitenant/prometheus": EOF; re-sending the block in 2.000 seconds
local vmagent sends traffic to vminsert via 127.0.0.1 and gets these errors (seems like things could go wrong here)
launched tcpdump, I see that at the time of the error, RST arrives from the vminsert port

### To Reproduce

run Vmagent and VMcluster 1.90.0 on same virtual machine

### Version

vmagent:v1.90.0
vminsert:v1.90.0-cluster

### Screenshots

![2023-04-17_15-38-08](https://user-images.githubusercontent.com/3078342/232486325-beabd868-667a-4436-98b2-5b5c6bebdb9c.png)
![2023-04-17_15-39-42](https://user-images.githubusercontent.com/3078342/232486999-766add4b-d319-4734-952e-4ef6c35aafc2.png)
![2023-04-17_15-40-01](https://user-images.githubusercontent.com/3078342/232487009-0b5a8c24-b211-49d2-a57d-bbc6a9ffd863.png)
![2023-04-17_15-40-22](https://user-images.githubusercontent.com/3078342/232487012-4adf543f-8890-4b93-8a3d-f057f5956b44.png)
![2023-04-17_15-41-10](https://user-images.githubusercontent.com/3078342/232487017-be2ba66d-54ba-4db7-b933-24b2ee46bc2f.png)

### Used command-line flags

      - '--promscrape.config=/etc/vmagent/vmagent.yml'
      - '--graphiteListenAddr=:3003'
      - '--httpListenAddr=:8429'
      - '--remoteWrite.maxDiskUsagePerURL=10GB'
      - '--maxConcurrentInserts=100000'
      - '--insert.maxQueueDuration=60s'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-60s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-30s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-10s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-60s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-30s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/prometheus-10s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-60s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-30s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8581/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-10s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-60s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-30s.yml'
      - '--remoteWrite.url=http://127.0.0.1:8591/insert/multitenant/prometheus'
      - '--remoteWrite.urlRelabelConfig=/etc/vmagent/relabel/graphite-10s.yml'

**Comment by Amper** [comment]
Hi @ihard.
Are there any errors in the vminsert log?
What command-line flags are used in vminsert?

**Comment by ihard** [comment]
vminsert flag
```
      - '--httpListenAddr=:8581'
      - '--storageNode=10.111.234.4:8682'
      - '--storageNode=10.111.224.4:8682'
      - '--storageNode=10.111.225.4:8682'
      - '--replicationFactor=2'
```
vminsert log is null

**Comment by IvanZenger** [comment]
Is there any news here? We have the same problem.

The error comes about every 30 minutes `couldn't send a block with size 152176 bytes to "2:secret-url": Post "https://vminsert.example.com:8581/api/v1/write": EOF`.



We do not have another error on `vmagent`,`vminsert` or `vmstorage`.





`vmagent` has following configuration:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/49713674/54285e95-81aa-4ecb-9e5d-5e5ca815b185)




Dashboards:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/49713674/f6782980-f0b3-4f5a-93ff-6dacd75a27d8)

**Comment by wjordan** [comment]
This kind of error occurs when the HTTP client attempts to reuse an idle connection that's already been closed on the server. This can happen if the client's idle-connection timeout is greater than or equal to the timeout on the client, and both `vmagent`'s client `IdleConnTimeout` and `vminsert`'s server `IdleTimeout` are set to 1 minute by default:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2e494e2375bb010d23b9cae40685938fa00d8d03/app/vmagent/remotewrite/client.go#L121

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2e494e2375bb010d23b9cae40685938fa00d8d03/lib/httpserver/httpserver.go#L122

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2e494e2375bb010d23b9cae40685938fa00d8d03/lib/httpserver/httpserver.go#L52

I can think of two possible solutions:

1. The underlying Go issue is discussed in golang/go#22158, where a workaround was implemented that allows automatically retrying `POST` requests tagged with a special `X-Idempotency-Key` header. A PR could add this header for VictoriaMetrics client requests that are known to be idempotent. (I'm pretty sure remote-write requests are idempotent thanks to [deduplication](https://docs.victoriametrics.com/#deduplication) logic?)
2. Setting a slightly higher vminsert `-http.idleConnTimeout` config than the hard-coded 1m vmagent-client timeout (e.g., `-http.idleConnTimeout 1m5s`) might also help prevent this error, since idle connections would then be more likely to get closed by the client before the server.

**Comment by hagen1778** [comment]
As @wjordan mentioned, such errors could happen when connection timeouts on client and server doesn't match. However, this doesn't result in data loss as vmagent will retry the write attempt with a newly established connection.

**Comment by valyala** [comment]
The commit 992a1c0a3a2e4bb6ac9ad9be7c9621a3ac850a26 should instruct `vmagent` immediately retry requests to remote storage on closed idle connection, without logging the error. This should remove the `couldn't send a block with size ... bytes to "...": Post "...": EOF` error logs. This change can be tested by building and running vmagent from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources). If everything is OK, this commit will be included in the next release.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), vmagent shouldn't emit `couldn't send a block` error logs on the first unsuccessful attempt to send data to remote storage. It will retry sending the block immediately over a new connection to the remote storage in this case. Closing the issue as resolved then.
