### ISSUE TITLE
Rack Awareness in Victoria Metrics

### ISSUE THREAD

**Issue by rajeshksv** [VictoriaMetrics/VictoriaMetrics#4216]
### Is your question request related to a specific component?

vminsert, vmstorage

### Describe the question in detail

Is Victoria metrics rack aware ? If RF = 2, does vminsert places data in two vmstorage nodes from two different racks ? I could neither find vmstorage or vminsert taking rack parameter from configuration nor find VM supporting rack discovery mechanism
If it doesn't support, what's the recommendation ? 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@rajeshksv VictoriaMetrics does not handle such topology constrains via configuration. vminsert will write to 2 different storage nodes, but nodes are chosen based on consistent hashing based on metric name and labels.
In case it is required to store replicas of data on 2 separate racks you have the following options:
1) Set up 2 independent clusters and vmagents writing to both clusters.
In this case failure domain will be limited by rack, there will be 2 exact copies of data stored on each rack. Outage of any cluster does not affect second cluster.
![Untitled-2023-04-27-1825(3)](https://user-images.githubusercontent.com/1367798/234900201-9ba87e23-4e1b-4326-934f-25052181777d.png)


2) Use [multi-level cluster setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup) and set up cluster with global and local vminserts and vmselects.
In this setup you will have multi-layered write path containing rack-local and global vminsert nodes.
Global nodes will use `RF=2` to write data to both racks for every incoming request. Rack local vminsert nodes can use `RF=1` in case it is not required to store copies of data within same rack.

![Untitled-2023-04-27-1825(1)](https://user-images.githubusercontent.com/1367798/234897075-b27fad07-7a4b-4400-b2ca-2a9af5587a16.png)


Which one to use depends on your usage patterns and protocols you will use to write to cluster. Using option 1 allows scraping data and accept data for push formats and also cache data on vmagent in case cluster will be unavailable for some time.
Second option allows having a single endpoint for write to both clusters, so that consumers won't know about internal cluster setup details.

**Comment by zekker6** [comment]
> Its bit surprising that VM doesn't consider rack information while placing replicas as most distributed systems these days does out of box.

VictoriaMetrics [architecture](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview) is based on [shared-nothing](https://en.wikipedia.org/wiki/Shared-nothing_architecture) model where components are highly decoupled. Components of the same level don't even know about other instances to keep it simple to operate and use. Due to that reason there is no metadata about deployment used to make smarter decisions about data location.

> One orthogonal Q - If a vmstorage node goes down, is it fine to remove disk from that instance, reattach (logically) to another instance and join the cluster ?

Yes, each storage node is independent of other nodes, so it is safe to move disk and restart node on another physical machine. Just make sure that either IP address of node remains the same, or list of IP addresses is updated on vminsert and vmselect nodes after migration.

**Comment by rajeshksv** [comment]
In this case, it is insert nodes that need to know topology of storage nodes (not same level components). Insert nodes while determining two replicas of storage nodes can simply use static rack information and ensure both replicas are not in same rack. This will still maintain shared nothing architecture. Am I missing something ?

> Just make sure that either IP address of node remains the same
Can we use DNS entries here ? Will VM automatically connect to new instance w/o restarts ?

**Comment by zekker6** [comment]
Closing this as original question have been answered, feel free to reopen if you will have any other questions.
