### ISSUE TITLE
vmui: explore tab should explicitly specify that it is dedicated for Prometheus metrics

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4248]
### Is your feature request related to a problem? Please describe

See original ticket here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4226

### Describe the solution you'd like

Would be nice if Explore tab explained what it is for explicitly.
See more about this here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4312#issuecomment-1550860635 and here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4312#issuecomment-1552691142

**Comment by valyala** [comment]
Please do not break the `explore metrics` UI! This page is solely intended for solving the only task (and solving it well) - exploring metrics collected from Prometheus targets. These metrics always have `job` and `instance` labels, which have well defined meaning - see [these docs](https://prometheus.io/docs/concepts/jobs_instances/).

There is little sense in giving the ability to explore metric names without selecting the `job`, since metrics from distinct jobs (aka different applications) usually contain quite different values. This may confuse users without giving any visible benefits.

It would be better renaming the `explore metrics` page to `explore Prometheus metrics` and then creating completely new `explore metrics` page for exploring non-Prometheus metrics. I have no good ideas yet how this page should look to be useful. Suggestions are welcome!

**Comment by hagen1778** [comment]
Agree with @valyala! The ticket should be re-purposed to update VMUI's page description with information to make it clear that it is dedicated to Prometheus metrics only.

**Comment by hagen1778** [comment]
The issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4615
