### ISSUE TITLE
vmagent: not all Prometheus config params are supported

### ISSUE THREAD

**Issue by whitehatbuds** [VictoriaMetrics/VictoriaMetrics#4274]
### Is your question request related to a specific component?

VMAgent
Version: v1.79.3

### Describe the question in detail

I notice VMAgent follows the promscrape specification from the official prometheus documentation [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/)

But I encountered an error when I imported a promscrape config from a prometheus instance. 
![image](https://user-images.githubusercontent.com/73067032/237030195-be50371e-9ee0-499f-bf98-0a9251af037c.png)

This is an example of a scrape config I have
`
- enable_http2: true
  follow_redirects: true
  honor_timestamps: true
  job_name: something_metrics
  metric_relabel_configs:
  - action: replace
    regex: (.*)
    replacement: $1
    separator: ;
    source_labels:
    - exported_instance
    target_label: instance
  - action: labeldrop
    regex: exported_instance
    replacement: $1
    separator: ;
  metrics_path: /metrics
  scheme: http
  scrape_interval: 30s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - "something" 
`

line 1035: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1058: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1062: field enable_http2 not found in type http.SDConfig
  line 1063: field follow_redirects not found in type http.SDConfig
  line 1064: field refresh_interval not found in type http.SDConfig
  line 1079: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1084: field enable_http2 not found in type kubernetes.SDConfig
  line 1085: field follow_redirects not found in type kubernetes.SDConfig
  line 1100: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1105: field enable_http2 not found in type kubernetes.SDConfig
  line 1106: field follow_redirects not found in type kubernetes.SDConfig
  line 1121: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1126: field enable_http2 not found in type kubernetes.SDConfig
  line 1127: field follow_redirects not found in type kubernetes.SDConfig
  line 1142: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1147: field enable_http2 not found in type kubernetes.SDConfig
  line 1148: field follow_redirects not found in type kubernetes.SDConfig
  line 1163: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1168: field enable_http2 not found in type kubernetes.SDConfig
  line 1169: field follow_redirects not found in type kubernetes.SDConfig
  line 1184: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1189: field enable_http2 not found in type kubernetes.SDConfig
  line 1190: field follow_redirects not found in type kubernetes.SDConfig
  line 1205: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1210: field enable_http2 not found in type kubernetes.SDConfig
  line 1211: field follow_redirects not found in type kubernetes.SDConfig
  line 1226: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1231: field enable_http2 not found in type kubernetes.SDConfig
  line 1232: field follow_redirects not found in type kubernetes.SDConfig
  line 1248: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1253: field enable_http2 not found in type kubernetes.SDConfig
  line 1254: field follow_redirects not found in type kubernetes.SDConfig
  line 1269: field enable_http2 not found in type promscrape.ScrapeConfig
  line 1274: field enable_http2 not found in type kubernetes.SDConfig
  line 1275: field follow_redirects not found in type kubernetes.SDConfig

Im currently on VMAgent version v1.79.3, May I know what is the correct version of VMAgent I should use if I want to support the following scrape configs from prometheus version 2.x ?

The fields that had these errors are actually fields that most likely are auto generated by prometheus with default values

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @whitehatbuds! 
Thanks for reporting this. Indeed, vmagent should support `follow_redirects` per each configured SD, and support `enable_http2` setting. See the following issues for details:
- [ ] https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4282
- [ ] https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4283

Regarding `refresh_interval` param, it is intentionally not supported as listed here https://docs.victoriametrics.com/vmagent.html#unsupported-prometheus-config-sections.

**Comment by valyala** [comment]
FYI, the support for `enable_http2` option is disabled explicitly in vmagent and single-node VictoriaMetrics because of the following issues:

- http2 is used very rarely comparing to http for Prometheus metrics exposition and service discovery
- http2 is much harder to debug than http
- http2 has very bad security record because of its complexity - see https://portswigger.net/research/http2
    
VictoriaMetrics components are compiled with nethttpomithttp2 tag because of these issues.

See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4283 for more details.

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent.html) and [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) may miss support for some configuration options from Prometheus in [Prometheus config file](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). Some of these options may miss support on purpose (such as `enable_http2` (see [the reason here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4274#issuecomment-1624418977)) or `refresh_interval`). Other options may be missing because they just recently appeared in Prometheus, so they didn't back-ported yet to VictoriaMetrics.

It is still possible to run vmagent and single-node VictoriaMetrics with Prometheus config containing unsupported options - just pass `-promscrape.config.strictParse=false` command-line option to vmagent / single-node VictoriaMetrics. In this case it will just ignore all the unsupported options. It isn't recommended using `-promscrape.config.strictParse=false` option in general case, since it may hide typos and small errors in the provided `-promscrape.config` file.

**Comment by jiekun** [comment]
@whitehatbuds Hi Please check valyala's comment above. Since `enable_http2` and `follow_redirects` are available, you can try them out. I'm closing this ticket as completed. Please feel free to re-open it and comment if you have questions.
