### ISSUE TITLE
vmagent: support `enable_http2` param

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4283]
### Describe the bug

According to https://prometheus.io/docs/prometheus/latest/configuration/configuration/ scrape config should support `enable_http2` param. vmagent should support it as well.

### To Reproduce

Try creating a scrape_config with `enable_http2` param.

### Version

v1.90

**Comment by valyala** [comment]
FYI, the change, which adds support for the `enable_http2` option has been explicitly disabled in the commit 8a07621a0c48b83dbccef39387db4eae6cb4c443 . Reasons for disabling this option:

- http2 is used very rarely comparing to http for Prometheus metrics exposition and service discovery
- http2 is much harder to debug than http
- http2 has very bad security record because of its complexity - see https://portswigger.net/research/http2
    
Production build of VictoriaMetrics components are compiled with `nethttpomithttp2` tag because of these issues.
