### ISSUE TITLE
Cluster dashboard shows No Data on multiple panels

### ISSUE THREAD

**Issue by matej-bellus-w** [VictoriaMetrics/VictoriaMetrics#4317]
### Describe the bug

Multiple panels on the latest Grafana dashboard show "No Data" by default.

To make it work I've added `[$__interval]` to the queries. 

For example **Total datapoints** panel does:
```
sum(vm_rows{job=~"$job_storage", type!~"indexdb.*"})
```
which results in No Data. Time frame is set to 7 days.

When adding `[$__interval]` to the query like so:

```
sum(vm_rows{job=~"$job_storage", type!~"indexdb.*"}[$__interval])
```
the panels start to show data.

---

Maybe the `[$__interval]` should be added to the panels where it's missing (or other solution?), so the dashboard works out-of-the-box?

### To Reproduce

Install the cluster version, start scraping vm compenents and use the official dashboard in Grafana.

### Version

v1.90.0 (all cluster components)

**Comment by hagen1778** [comment]
Hello @matej-bellus-w!

> Multiple panels on the latest Grafana dashboard show "No Data" by default.
To make it work I've added [$__interval] to the queries.

This doesn't make sense. `[interval]` isn't needed for [sum](https://docs.victoriametrics.com/MetricsQL.html#sum) function. When you add that interval to time series selector VM performs [implicit subquery conversion](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions) which is very likely not what you want it to be.

I think the change you made to the query is wrong. The reason why you haven't seen results before the change is very likely caused by something else. Like cached empty result after backfilling or some other misconfiguration. I recommend going through https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results.

**Comment by matej-bellus-w** [comment]
I agree that `[interval]` should not be there.

Upon further looking into this, it seems our vmselect is configured with `-search.maxLookback 1ms`, which looks at max 1ms to the history for the datapoint. Since these data are not scraped at such small interval, it's very unlikely that the query would hit just in right time.

**Comment by hagen1778** [comment]
Hm, yes. It could be a reason for instant queries to fail.
Should we mark this issue as solved?
