### ISSUE TITLE
Setup Victoria Metrics together with Prometheus

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#4335]
### Is your question request related to a specific component?

VictoriaMetrics, vmagent

### Describe the question in detail

I am trying to create a monitoring solution that can better handle the bottleneck created by several devices sending metrics to a single Prometheus instance, to do this I have setup a docker environment where I have a Prometheus Federation composed by a "top" node and 2 "lower" Prometheus nodes. Now I want to setup several Victoria Metrics containers that will be scraping metrics from the host device and then supply those metrics to the 2 lower Prometheus nodes.

-How do I go about setting up both the docker compose file and the prometheus.yaml? Should I create several instances of vmagent? Should I clone several Victoria Metrics containers?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @DaRealCapz!
> Now I want to setup several Victoria Metrics containers that will be scraping metrics from the host device and then supply those metrics to the 2 lower Prometheus nodes.

I don't understand what "supply those metrics to lower nodes" means. Could you please elaborate?

Apart of this, I think federation is not the best way to go. Federation was a "workaround" for delivering metrics from multiple clients to a single storage. With VictoriaMetrics you don't need that anymore. You can follow two ways:
1. Configure your lower Proms to remote-write to VictoriaMetrics instance (single-node would fit, I think)
2. Or run vmagents to do the job Proms are doing (because vmagents are more efficient) and deliver that to VictoriaMetrics instance.

**Comment by DaRealCapz** [comment]
![proposta](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/9dc80611-c1fd-4700-8b21-efcf25784ada)

I have setched this solution in order to achieve your second suggestion, but I am having trouble creating the docker compose files to achieve it, do you have any tips?

**Comment by hagen1778** [comment]
@DaRealCapz I see you opened a new ticket with the same question here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4963
So I'm closing this ticket then.
