### ISSUE TITLE
MetricsQL: allow disabling implicit query conversions

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4338]
### Is your feature request related to a problem? Please describe

MetricsQL supports [implicit query conversions](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions). While it may sound handy, in fact it results more in confusion than better experience. There are some [issues on github](https://github.com/VictoriaMetrics/VictoriaMetrics/issues?q=label%3Asubquery+) caused only by this, not counting various discussions in community channels.

### Describe the solution you'd like

Provide a command-line flag for enabling "strict parse" which would disable implicit conversions into subqueries. This would prevent users for misusing this mechanism and will remain backward compatible. We should explain how to convert queries into the correct form.

cc @valyala

**Comment by hagen1778** [comment]
> Provide a command-line flag for enabling "strict parse" which would disable implicit conversions into subqueries. This would prevent users for misusing this mechanism and will remain backward compatible. We should explain how to convert queries into the correct form.

We should provide an instrument for system administrators to know in advance if the implicit query conversion is taking place in their VM installation. I suggest adding a new cmd-line flag `-search.logQueryImplicitConversions`. When enabled, vmselect/vmsingle would start emitting logs when implicit conversion happens and for what origin query it happens. With this info, system administrator will be able to detect and locate the source of queries that are being implicitly converted.

**Comment by Haleygo** [comment]
> I suggest adding a new cmd-line flag -search.logQueryImplicitConversions. When enabled, vmselect/vmsingle would start emitting logs when implicit conversion happens and for what origin query it happens. 

I don't see how logs can help with explaining the problem. From my perspective, it's hard to connect `seeing unexpected results` with `checking vmselect logs`. Ofc we can add some tips in the [troubleshooting doc](https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results), but it still requires enabling extra flag like `-search.logQueryImplicitConversions` and hard to make users understand what is changing for their "incomplete" query expression, which normally is too long to read in log. 
I think put more info in the query trace might be better, since it doesn't have to be enabled by flag and trace breaks the expression into small ones, providing more details.

Currently we have four cases in [implicit query conversions](https://docs.victoriametrics.com/metricsql/#implicit-query-conversions):
>1. avg_over_time(temperature) -> avg_over_time(temperature[1i])
>2. foo -> default_rollup(foo)
>3. avg_over_time(rate(http_requests_total[5m])[1h]) -> avg_over_time(rate(http_requests_total[5m])[1h:1i])
>4. rate(sum(up)) -> rate((sum(default_rollup(up)))[1i:1i])

So apart from p2, they are all "incomplete" in some way. I think it's cool to let users get results from "incomplete" query like `rate(http_request_total)`, but it's dangerous to allow them keeping using the expression without knowing what's a implicit query. So the recommendation normally is **"avoid using implicit query, add explicit step to the expression"**.
I think we should add a new cmd-line flag like `-search.disableImplicitConversions`, when enabled, metricsQL returns errors when parsing expression like `rate(http_request_total)` or `avg_over_time(rate(http_requests_total[5m])[1h])`, like promQL.

And a breaking change proposal, might be a bad idea:) 
To keep compatibility, `-search.disableImplicitConversions` is disabled by default. But what about enabling it for range query by default? Since range queries are normallly coming from grafana or VMUI, which give inconsistent&unexpected results and causes confusion in the first place. And we can leave instant query as legal now, since users might using it in recording/alerting rules, and with fixed `step`, it's ok.

What do you think? @hagen1778 @valyala

**Comment by hagen1778** [comment]
>I don't see how logs can help with explaining the problem.

The main purpose for `-search.logQueryImplicitConversions` is for database administrators to see how often implicit conversion is used in the system. The expected workflow for disabling the automatic conversion is the following:
1. Enable `-search.logQueryImplicitConversions` and wait for few days.
2. Collect logs generated by `-search.logQueryImplicitConversions`. Having the exact query expression, identify the sources of these queries and update them to avoid using the conversions.
3. Once all sources are sorted, enable `-search.disableImplicitConversions`. This would reject queries requiring the conversion on the future.

This approach provides a gradual transition without disrupting the process right away.

> And currently we have four cases in [implicit query conversions](https://docs.victoriametrics.com/metricsql/#implicit-query-conversions):

I think we should classify harmful and harmless conversions. While p1 and p2 from your example are harmless, the p3 and p4 are harmful. I'd try to disabling only p3, p4 and still allow using p1 and p2.

**Comment by valyala** [comment]
@hagen1778 , @Haleygo , please see the follow-up commit 61d794c5e759025366d39d477d8a2ad63e0cacf5 . It basically denies passing anything other than [series selector](https://docs.victoriametrics.com/keyconcepts/#filtering) into [rollup functions](https://docs.victoriametrics.com/metricsql/#rollup-functions), since this is the main source of unexpected query results. For example, the following queries are denied if VictoriaMetrics runs with `-search.disableImplicitConversion` command-line flag:

- `rate(sum(m))` - [aggregate function](https://docs.victoriametrics.com/metricsql/#aggregate-functions) is passed into [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions)
- `rate(abs(m))` - [transform function](https://docs.victoriametrics.com/metricsql/#transform-functions) is passed into [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions)
- `rate(foo + bar)` and `rate(foo > 123)` - binary operation is passed into [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions)
- `rate(rate(m))` - [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions) is passed into [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions).

These types of queries are improperly constructed, so the return unexpected results most of the time.

Other query types with implicit conversions are allows for now, since they return the expected results most of the time. For example, `rate(m)` is allowed, since it is more convenient than `rate(m[$__interval])`. Other invalid query types can be added to the check in the future releases of VictoriaMetrics.

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/61d794c5e759025366d39d477d8a2ad63e0cacf5 is going to be included in the upcoming `v1.102.0` release.

**Comment by valyala** [comment]
See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8
