### ISSUE TITLE
inconsistent behavior when same statements query

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#436]
**Describe the bug**
the second query's result is different than the first. 
see screenshot 

**Expected behavior**
return same data

**Screenshots**
![111](https://user-images.githubusercontent.com/3345153/80175387-093c9300-8628-11ea-97cd-b4053f700323.jpg)

**Version**
```
$ ./vmselect -version
vmselect-20200229-003528-heads-cluster-0-gd23df53

$ ./vmstorage-prod -version
vmstorage-20200424-005935-heads-cluster-0-g387a21c9
```

**Used command-line flags**
default, expect vmselect add
`-search.maxQueryDuration 86400s `

**Additional context**
1. when add `-search.disableCache` flag to `vmselect`, everything is ok.
2. when adjust the `-search.cacheTimestampOffset` flag. for example `10m`, the last 10m data is difference.

**Comment by valyala** [comment]
It looks like that samples with timestamps older than 10 minutes from the current time are ingested into VictoriaMetrics. In this case `vmselect` can return partial results from response cache, since it assumes that it is safe to cache responses on time ranges up to `now - search.cacheTimestampOffset`. So it doesn't see newly added samples with timestamps older than `-search.cacheTimestampOffset`. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) for more details.

There are the following workarounds:

* To set `-search.cacheTimestampOffset` command-line flag on `vmselect` to value higher than the maximum lag between the current time and timestamps in ingested samples (if it is known).
* To disable response cache by passing `-search.disableCache` to `vmselect` if ingested samples can have timestamps from the past and there is no hard limit on the lag for these timestamps.
* To query `/internal/resetRollupResultCache` page individually on every `vmselect` node after samples with historical timestamps are ingested into VictoriaMetrics.

Note that the response cache must be reset on every `vmselect` node after updating `-search.cacheTimestampOffset` value in order to remove old cached responses.

**Comment by n4mine** [comment]
I'm confused that the explain above.

![111](https://user-images.githubusercontent.com/3345153/80270541-9268ce00-86eb-11ea-9bdb-2ba9fb4a108b.jpg)

i make a diagram. (assumes `-search.cacheTimestampOffset` set to 10m)

[0, now-10m] will response by cache, so it's no gap between the response of the 1st query and the 2nd in [0, now-10m]

but in [now-10m], why the response of 2nd query is **lower than** 1st. this confused me.

**Comment by n4mine** [comment]
**update**

1st, snapshot:
https://snapshot.raintank.io/dashboard/snapshot/qFIyN2DSwKPiVOWQZCoqwoPoX9REMGW0?orgId=2

2nd, snapshot:
https://snapshot.raintank.io/dashboard/snapshot/yJa0jBkAcpbTmhbss6IArgFBfkfWBz9w?orgId=2

the last 5 minutes(which `-search.cacheTimestampOffset` set default) is difference.
and the 2nd query's response data is `lower than` the 1st query's response

hope that will be help

**Comment by valyala** [comment]
@n4mine , could you look into the following?

* Verify that system time on all the `vmselect` nodes is the same.
* Verify error logs on `vmselect` nodes. Probably, certain `vmselect` nodes experience connection errors with `vmstorage` nodes.
* Try passing `-search.denyPartialResponse` command-line flag to `vsmelect` nodes and verify whether `vmselect` returns all the responses or fails to return certain responses.
* Try querying each `vmselect` node directly without load balancer or any proxy. This can help determining misbehaving `vmselect` node.

**Comment by n4mine** [comment]
@valyala 
> Verify that system time on all the vmselect nodes is the same.

yes, all the vmselect nodes time is same

> Verify error logs on vmselect nodes. Probably, certain vmselect nodes experience connection errors with vmstorage nodes.

nothing in the log files when query occur

>Try passing -search.denyPartialResponse command-line flag to vsmelect nodes and verify whether vmselect returns all the responses or fails to return certain responses.

the behavior doesn't change In pass `-search.denyPartialResponse` before and after 

> Try querying each vmselect node directly without load balancer or any proxy. This can help determining misbehaving vmselect node.

the behavior doesn't change In with/without `lb` before and after

**Comment by valyala** [comment]
@n4mine , does this issue still exist in [newer releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by n4mine** [comment]
@valyala the issue was disappeared. thanks.
