### ISSUE TITLE
vmselect takes too much time to startup with large amount of storage nodes

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#4364]
### Describe the bug

  vmselect performs handshake with storage nodes at startup. It happens sequentially and takes too much time ( above 1 minute) with big numbers of storage nodes.

 It would be great to init connections in parallel. 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/netstorage/netstorage.go#L2709

### To Reproduce

 Configure vmselect with storage nodes > 50

### Version

any version

**Comment by Haleygo** [comment]
@f41gh7 Can I take this one :)
Seems [vminsert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c30f0e51d75f6b9fceec5fc4a276a1dd5ea4596c/app/vminsert/netstorage/netstorage.go#L505) only have some simple init work, doesn't need this enhancement.

**Comment by hagen1778** [comment]
Fix was included to [1.91.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.1)
Thanks to @Haleygo !

**Comment by valyala** [comment]
A few notes regarding this issue:

- The handshake between vmselect and vmstorage usually takes a few milliseconds if vmselect and vmstorage nodes are located in the same network with low latency (this is [the recommended setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#high-availability) for VictoriaMetrics cluster).
- Sequential handshake between vmselect and all the vmstorage nodes specified via `-storageNode` command-line flag at vmselect startup shouldn't take too much time in low-latency network. For example, if a single handhake between vmselect and vmstorage takes 10ms, then sequential handshake for 100 vmstorage nodes will take less than `100*10ms=1s`.

This means that the patch makes sense only for VictoriaMetrics cluster setup for high-latency networks. For example, if `vmstorage` nodes are located in different availability zones or datacenters comparing to `vmselect` nodes. Such a setup [isn't recommended in general case](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#high-availability), since it may lead to performance degradation and reduced reliability for VictoriaMetrics cluster.

**Comment by valyala** [comment]
There is another case when parallel initialization of `vmselect` -> `vmstorage` connections fix can improve `vmselect` startup times - when some of `vmstorage` nodes are temporarily unavailable in the cluster. In this case the handshake attempt to unavailable `vmstorage` nodes can take a long time because of various DNS or networking issues.
