### ISSUE TITLE
vmstorage: disk space capacity planning 

### ISSUE THREAD

**Issue by LauraToderita** [VictoriaMetrics/VictoriaMetrics#4374]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Hello,
We have a victoriametrics cluster implementation using 20 vmstorages each with 16G memory, 1T storage, 2vCPU. 
The average storage use on each server is 830G (356G index, 474G data), that overruns the 20% free storage recommendation.  
We are using retention of 1 year and our traffic patterns are ~875K datapoints/second, ~500 Mib/s traffic in, ~24 Tri datapoints, ~0.43B bytes/point, ~22 Mil active timeseries, ~15 weeks ETA to full storage.
No vmstorages have triggered the vm_merge_need_free_disk_space.  
Many versions ago, victoriametrics documentation had some formulas for capacity planning which are no longer present in the current documentation.
Considering our use case described above, does anybody have any recommandation whether we should increase storage space on each server, or scale up the number of servers?
Do you have an updated formula to ensure that the hardware resources are enough for certain volumes of traffic and data?

Thank you!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hi @LauraToderita 

The formula for capacity planning was more related to CPU and memory usage. Not to disk space occupied. 
The estimation for disk space usage is expressed in ETA panel chart of Grafana dashboard. It calculates the speed of adding new data samples to disk. However, this formula works only for current ingestion workload. Everything can change tomorrow if data shape will change, or more churn rate will start to happen. 

I'd recommend keeping not less than 300-400GB of free disk space on vmstorage nodes. If you see that limit is approaching, consider expanding disks or scale horizontally. 

There are also other ways how you can reduce disk space usage:
* https://docs.victoriametrics.com/#downsampling
* https://docs.victoriametrics.com/stream-aggregation.html

**Comment by hagen1778** [comment]
> Many versions ago, victoriametrics documentation had some formulas for capacity planning which are no longer present in the current documentation.

Those were recommendations for memory and CPU, afaik.

> Considering our use case described above, does anybody have any recommandation whether we should increase storage space on each server, or scale up the number of servers?

The requirement of 20% disk space is caused by two things:
1. The majority of HDDs start having degradation performance when there is less than 20% of free disk space left.
2. VM needs additional disk space for parts merging. See more [here](https://docs.victoriametrics.com/#storage).

If you're sure you're not affected by p1 and there are no delayed merges because of lack of space - you're fine. But please be cautious if you don't have the option to extend storage size at will. Because adding more vmstorage shard or migration to bigger disks may take some time.

> Do you have an updated formula to ensure that the hardware resources are enough for certain volumes of traffic and data?

Such formula would require data details. Since each installation is unique in terms of stored data - this formula doesn't exist. Moreover, there are no guarantees that data won't change with time. For example, you can have 0.5B per data point and then new service will start writing data with high churn or data values with bad compression ratio. In result, your previous calculation would become wrong. So we rely on ETA calculation instead.

**Comment by hagen1778** [comment]
> Asked in a different manner: what are the conditions that would recommend more nodes vs increasing the diskspace?

I believe, this question is answered here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning.

In short, increase disk space if you're ok with the current performance:
* CPU is below 50% (soft cap), 80% (hard cap)
* memory is below 50% (soft cap), 80% (hard cap)
* no ingestion delays
* read latency is acceptable

If something from above doesn't meet your expectations - consider vmstorage scaling:
1. Scale vertically or horizontally if there is not enough CPU or mem
2. Scale horizontally if there is not enough disk throughput (slow writes/reads, IOPS limits)

**Comment by jiekun** [comment]
close as answered.
