### ISSUE TITLE
VictoraMetrics cluster: capacity planning question

### ISSUE THREAD

**Issue by nulldoot2k** [VictoriaMetrics/VictoriaMetrics#4409]
### Is your question request related to a specific component?

Require: 5Tb for storage metrics and can improve 
About how many servers do I have to spend for this victoria metrics cluster
with vminsert
- how many replicationFactors?
- how much is dedup.minScrapeInterval?
with vmtorage
- how much is dedup.minScrapeInterval?
- How much is retentionPeriod?
- how much is finalMergeDelay ?
with vmselect
- how much is replicationFactor

### Describe the question in detail

Currently, the problem I want to meet is the amount of storage and the frequency of query metrics.
The amount of storage I give is approximately 5Tb Metrics
About how many nodes should I divide to meet the needs of this problem
Victoria metrics Cluster version 1.92 with 12 nodes ?
each node will have 600Gb ?

-- Now
i use 3Tb for storage metrics but disk 85% used so i need help from someone, can solve  

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> About how many servers do I have to spend for this victoria metrics cluster
with vminsert

Answers to these questions mostly depend on you as service architecture. The knowledge about each of these params is available at http://docs.victoriametrics.com/. If you need additional help or consulting with setting up the cluster and running it at production grade - reach sales@victoriametrics.com

> About how many nodes should I divide to meet the needs of this problem
Victoria metrics Cluster version 1.92 with 12 nodes ?
each node will have 600Gb ?

"It is preferred to run many small vmstorage nodes over a few big vmstorage nodes, since this reduces the workload increase on the remaining vmstorage nodes when some of vmstorage nodes become temporarily unavailable."
from https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-setup

12 nodes with 600GB will be 7.2TB, though.

**Comment by nulldoot2k** [comment]
Thanks bro so much @hagen1778
