### ISSUE TITLE
vmagent lost interval when reload config

### ISSUE THREAD

**Issue by xbsura** [VictoriaMetrics/VictoriaMetrics#448]
**Describe the bug**
reload sd_file will stop all workers and restart, this will make scraper interval not ok, for example, if set interval 30s, the real interval may become 10, 80s

in grafana, this action will cause metrics lost, and alert such as changes() will fire

**To Reproduce**
reload config

**Expected behavior**
just reload changed rule, or remember interval before restart

Our env, a lot of people manager config file with promgen, so config file changes offen, this bug makes our metrics lost data very often

**Comment by valyala** [comment]
This should be fixed in the following commits:

* 3b234d82e541395628951db1b70f0d5079ae9918
* e4aac6ea40d208777f0b3e90273eea4f822dc573

These commits will be included in the next release.

@xbsura , thanks for the bug report and for the initial attempt to fix it at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/449 !

**Comment by valyala** [comment]
The commits mentioned above have been included in [release v1.35.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@xbsura , feel free re-opening the issue if you encounter additional issues related to the original issue.
