### ISSUE TITLE
project depency use go mod replace vendor

### ISSUE THREAD

**Issue by xbsura** [VictoriaMetrics/VictoriaMetrics#451]
**Is your feature request related to a problem? Please describe.**
to make pr review more easy

**Comment by valyala** [comment]
Unfortunately I'm not going to remove `vendor` directory from VictoriaMetrics source code because of the following reasons:

* This allows building VictoriaMetrics binaries in environments without network access, since all the third-party code is already located in `vendor` directory. This is impossible without `vendor` directory, since `go` needs to download third-party dependencies before compiling VictoriaMetrics code.

* This allows keeping third-party dependency bloat under control, since all the code for third-party dependencies is clearly visible inside `vendor` directory. See https://medium.com/@valyala/stripping-dependency-bloat-in-victoriametrics-docker-image-983fb5912b0d for the details.

* This simplifies reviewing code changes in third-party dependencies during upgrading their versions. These changes are stored as an ordinary commits in the repository, so they could be inspected and rolled back at any time if anything wrong is detected in these commits.

**Comment by valyala** [comment]
Closing this feature request as `won't fix`.
