### ISSUE TITLE
Why are the data and lens of items stored separately in two files: items.bin and lens.bin in indexdb

### ISSUE THREAD

**Issue by andyli029** [VictoriaMetrics/VictoriaMetrics#4594]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Why are the data and lens of items stored separately in two files：items.bin and lens.bin in indexdb

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by andyli029** [comment]
@valyala

**Comment by zekker6** [comment]
@andyli029 The initial idea was that there would be a use-case when `items.bin` contents can be read separately from `lens.bin` and splitting this into separate files will allow reducing amount of IO operations required to read contents from a single file.
As turned out, this will not be possible since you have to read `lens.bin` to unpack `items.bin` contents. But since it does not have a big performance penalty it is kept as is to keep backward compatibility with previous versions.

**Comment by andyli029** [comment]
@zekker6，Thank you very much.
