### ISSUE TITLE
MetricName sortTags

### ISSUE THREAD

**Issue by oronsh** [VictoriaMetrics/VictoriaMetrics#4610]
### Is your question request related to a specific component?

vmstorage, vmselect

### Describe the question in detail

hello,
as i get it, `vmstorage` is doing `MetricName.SortTags` for disk locality optimization on inserting entries to `index_db`.
as the comment in the code mention it, it's a slow operation.
also, if i get it correctly, `vmselect` has to re-order the tags on query.
my question is, would it be possible to just add 2 more fields to `MetricName`, `JobID` and `InstanceID` which are both `uint64`
then you could hash the values and encode them as prefix, just like `TSID` is doing, by that maybe there won't be any need to sort tags at all?
of course it's adding 16 bytes per `MetricName` but maybe tradeoff worth it.
and maybe I'm getting it all wrong :)

thanks a lot!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @oronsh 

`MetricName.SortTags` primary function is actually to create a "canonical form" of storing different timeseries.
This is required because samples can be ingested with different sorting being applied to labels. If we would store samples as-is(without sorting labels) that would make search inefficient.
Storing labels in a sorted format allows to use search based on prefix match which is more efficient. As an additional benefit it imporoves disk locality.

**Comment by oronsh** [comment]
I see, thank you very much @zekker6
