### ISSUE TITLE
vmagent: skip TLS cert check in -dryRun

### ISSUE THREAD

**Issue by jplanckeel** [VictoriaMetrics/VictoriaMetrics#4625]
### Is your feature request related to a problem? Please describe

Hello, we want run vmagent in different context like CI to check configuration as you could do with the prometheus promtool. But in this context i don't have certificat SSL to run the dry run. And we have an error in dryrun, vmagent cannot open the certificate. 

### Describe the solution you'd like

The solution would be to be able to add an option not to check certificates in the configuration with an option in dryrun 

example: disable check tls.

**Comment by wasim-nihal** [comment]
Hi @hagen1778 , I would like to contribute here. Please find the PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4642
Request you to review and let me know if any changes are required.

**Comment by hagen1778** [comment]
> Describe alternatives you've considered

@jplanckeel what stops you from removing cmd-line flags you don't want to check before running in dryRun mode?

To clarify my intention, `-dryRun` in the current implementation verify all the config options passed to vmagent. If something fails on dryRun - it will fail in production. If there are options that don't need to be tested - they should be omitted.

https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4642 was rejected because it changed default behaviour of dryRun cmd-line flag. That would mean users who intend to check all the options they want to check may found the change surprising.

I'm not in favor of https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4699 either, as it introduces an extra complexity and extra cmd-line option. It brings no additional value and can be substituted by simple ` ./vmagent -dryRun -promscrape.config=scrape_config.yml ` call.

**Comment by valyala** [comment]
FYI, `./vmagent -dryRun` shouldn't return errors when TLS certificates are missing starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4959) for details.

Closing the feature request as done.

**Comment by jplanckeel** [comment]
Thank you ;)
