### ISSUE TITLE
VictoriaLogs: adding the ability to display data in grafana

### ISSUE THREAD

**Issue by serrrios** [VictoriaMetrics/VictoriaMetrics#4630]
### Describe the solution you'd like

We provide a logging system as a service. Some of our users, who are not advanced technical specialists, have a need to build analytics based on logs. Typically, Kibana or Graylog is used for this purpose. An intuitive and user-friendly interface for this task is important. Even Grafana does not always seem to have a user-friendly interface to them. Currently, VictoriaLogs does not have the ability to create analytical dashboards.

One of the following options could be considered to solve this problem while visualizing log data in Grafana:

- Developing a custom plugin for Grafana.
- Ensuring backward compatibility with Elasticsearch.
- Ensuring backward compatibility with Loki.

**Comment by JakeCooper** [comment]
Mentioned it in the original VictoriaLogs thread, but we would love backwards compatibility with loki

Something like a `select/<tenant_number>/loki/api/v1/query` and the ability to add it into Grafana as a Loki source would be gamechanging

**Comment by valyala** [comment]
Please see also https://github.com/VictoriaMetrics/VictoriaMetrics/issues/816#issuecomment-1665672676

**Comment by uhthomas** [comment]
https://github.com/VictoriaMetrics/victorialogs-datasource

**Comment by valyala** [comment]
Closing this feature request, since there is a Grafana plugin for VictoriaLogs - https://github.com/VictoriaMetrics/victorialogs-datasource . Please file bugreports and feature requests at this project instead.

VictoriaLogs also provides built-in web UI for logs' analysis - see [these docs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui).

> we would love backwards compatibility with Loki

This isn't on [VictoriaLogs roadmap](https://docs.victoriametrics.com/victorialogs/roadmap/), since it provides **much better** query language for logs - [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) - than the query language for Loki. LogsQL has the following features, which are missing in the [query language for Loki](https://grafana.com/docs/loki/latest/query/):

- Ability to calculate multiple [stats](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe) in a single query. For example, you can calculate the total number of logs, the number of logs with `error` word, plus the number of unique `user_id` field values across some logs matching the given filter on the given time range, in a single query.
- Ability to use arbitrary complex logical filters with `AND`, `OR` and `NOT` operators - see [these docs](https://docs.victoriametrics.com/victorialogs/logsql/#logical-filter).
- Ability to use subquery results in filters - see [this docs](https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter).
- Ability to use conditional transformations. See [these docs](https://docs.victoriametrics.com/victorialogs/logsql/#conditional-extract).
- More clear syntax and more practical functionality - see [LogsQL docs](https://docs.victoriametrics.com/victorialogs/logsql/).

On top of this, query language for Loki lacks functionality for working with non-stream log fields (which may contain high-cardinality values), because Loki didn't support such fields in the first place. VictoriaMetrics supports [high-cardinality non-stream log fields](https://docs.victoriametrics.com/victorialogs/keyconcepts/#data-model) from the beginning, so LogsQL provides very easy filtering and access to these fields via simple `field_name:filter` pattern.

That's why it is very unlikely VictoriaLogs will support Loki query language.

**Comment by hagen1778** [comment]
VictoriaLogs datasource plugin is officially available in Grafana - see https://grafana.com/grafana/plugins/victoriametrics-logs-datasource/
