### ISSUE TITLE
How to handle counter resets?

### ISSUE THREAD

**Issue by jessetane** [VictoriaMetrics/VictoriaMetrics#4660]
I tried `increase` but this sometimes shows a decrease when there are periods where the counter does not change. Is there a simple version of this function where it literally only makes sure that values can only increase?

**Comment by hagen1778** [comment]
Hello @jessetane! Could you please provide an example where it doesn't work as you expect?

Looking at the following [example](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.range_input=2h3m27s406ms&g0.end_input=2023-07-14T07%3A04%3A14&g0.tab=0&g0.relative_time=none&g0.expr=vm_http_requests_total%7Bcluster%3D%22sandbox%22%2Ccontainer%3D%22analytic-exporter%22%2Cpath%3D%22%2Fmetrics%22%7D&g0.step_input=1m&g1.expr=increase%28vm_http_requests_total%7Bcluster%3D%22sandbox%22%2Ccontainer%3D%22analytic-exporter%22%2Cpath%3D%22%2Fmetrics%22%7D%5B5m%5D%29&g1.range_input=2h3m27s406ms&g1.end_input=2023-07-14T07%3A04%3A14&g1.tab=0&g1.relative_time=none&g1.step_input=1m&g2.expr=remove_resets%28vm_http_requests_total%7Bcluster%3D%22sandbox%22%2Ccontainer%3D%22analytic-exporter%22%2Cpath%3D%22%2Fmetrics%22%7D%29&g2.range_input=2h3m27s406ms&g2.end_input=2023-07-14T07%3A04%3A14&g2.tab=0&g2.relative_time=none&g2.step_input=1m) I see that increase properly accounts for counter reset and decreases only because one or two scrapes were missed.

You can compare this behavior to Prometheus behavior here http://demo.robustperception.io:9090/graph?g0.expr=prometheus_http_requests_total%7Bhandler%3D%22%2Fmetrics%22%7D&g0.tab=0&g0.stacked=0&g0.range_input=1h&g0.end_input=2023-07-17%2009%3A34%3A37&g0.moment_input=2023-07-17%2009%3A34%3A37&g1.expr=increase(prometheus_http_requests_total%7Bhandler%3D%22%2Fmetrics%22%7D%5B5m%5D)&g1.tab=0&g1.stacked=0&g1.range_input=1h&g1.end_input=2023-07-17%2009%3A34%3A37&g1.moment_input=2023-07-17%2009%3A34%3A37

cc @Amper
