### ISSUE TITLE
gaps when plotting metrics in Grafana

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#4697]
### Describe the bug

I'm running a highly available VictoriaMetrics cluster and multiple VMAgents using the Kubernetes operator.

- [VMCluster manifest](https://github.com/uhthomas/automata/blob/4233ec64acf0d6a7df4f9ecc65f1fafb27898b50/k8s/unwind/vm/vm_cluster_list.cue#L17)
- [VMAgent manifest](https://github.com/uhthomas/automata/blob/4233ec64acf0d6a7df4f9ecc65f1fafb27898b50/k8s/unwind/vm/vm_agent_list.cue#L17)

Following the guides on deduplication, I have the [deduplication argument](https://github.com/uhthomas/automata/blob/4233ec64acf0d6a7df4f9ecc65f1fafb27898b50/k8s/unwind/vm/vm_cluster_list.cue#L76) set as such:

```cue
extraArgs: "dedup.minScrapeInterval": "30s"
```

Unfortunately, I see lots of gaps in the metrics.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/61ed79ce-6104-4741-8fcf-618876a74c3e)

Intuitively, it would seem the scrape intervals are mis-matched. I am pretty confident however this is not the case given:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/2be37ff5-8f96-4eea-a2eb-d8814a77db07)

### To Reproduce

Deploy VM as I have done and observe the reported behaviour.

### Version

docker.io/victoriametrics/vmstorage:v1.91.0-cluster

**Comment by uhthomas** [comment]
Actually, I see this even without deduplication. I disabled deduplication and switched to using a single agent and still see this.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/2e150f06-8a66-4d2e-b577-28028ed0f6f4)

**Comment by hagen1778** [comment]
Hello @uhthomas! Could you please go through https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3878 and see if it is relevant for your case?

**Comment by uhthomas** [comment]
@hagen1778 Thanks, it looks like it's relevant. There's a few other linked issues too.

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1773

How is VM calculating staleness? I remember it was fine when I first deployed VM and only became a problem when I tried to deploy multiple vmagents. The problem seems to have persisted even though I reverted that change days ago. Could VM just be hanging on to a bad staleness value?

**Comment by uhthomas** [comment]
I would have to investigate, but I don't believe the data is becoming irregular. vmagent has plenty of resources and there are no reports of scrape errors or dropped metrics. I have a sneaky suspicion that it would resolve itself if I were to reset the vmstorage nodes.

Regardless, this seems to be a major problem lots of people hit. VM should just work out of the box without this quirk or else I have a bit of a hard time recommending it as a Prometheus alternative. I'd really like to work together to figure out how to fix this.

**Comment by uhthomas** [comment]
So, it looks like setting `search.minStalenessInterval to 5m fixed this. I am struggling to understand why this is needed though. The vmagent is configured to scrape every 30s and there are _no_ reports of any scrape errors or dropped rows.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/f0accb2a-e385-4712-af63-788d6ebc5718)

The only exception is `vm-operator`, which I will fix.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/8d2486a1-fac3-4441-8af3-46c8780ded1b)

There should be no reason at all for victoriametrics to mark the metrics as stale. I'm happy to help provide more info if possible, but from what I can see this is purely a bug with how victoriametrics considers metrics stale.

**Comment by hagen1778** [comment]
@uhthomas may I request the following info:
1. Ensure you're using a single instance of vmagent (for better isolation)
2. Along with data gaps on the panel, plot `rate(vm_promscrape_stale_samples_created_total)` expression and attach the screenshot
3. Locate one time series which has gaps when plotted, export it via [/api/v1/export API](https://docs.victoriametrics.com/url-examples.html#apiv1export) on a limited time range (approx couple of hours where issue can be reproduced) with `reduce_mem_usage=1` query param and send it to roman@victoriametrics.com. Feel free to obfuscate sensitive data - I'm interested only in reproducibility

Thanks!

**Comment by uhthomas** [comment]
Sure, let me set some stuff up and I'll get back to you.

fwiw, the orange in this screenshot I believe is with one vmagent and without any changes to min staleness.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/9b081c9f-6990-47fa-ab94-c9b8e7cc3ff8)

**Comment by uhthomas** [comment]
I deployed a test cluster with one vmagent in an isolated namespace and let it run for a few hour.

https://github.com/uhthomas/automata/tree/a025f2b501c9857d7ad92ce4ef5bc42439bd9bf5/k8s/unwind/vm4697

The results show the same gaps in time series:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/c195f0be-1400-4edc-b7b3-e7fbdb2bd355)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/a97e772a-2538-4d86-908a-54f1ab2fb79b)

Stale samples metric:

`rate(vm_promscrape_stale_samples_created_total{prometheus="vm4697/vm4697"})`

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/e19b77d6-6f6f-452a-bba6-b6da0ae9682b)

I've exported the time series as requested and thought it would be easier to upload it to GitHub than email it.

```
❯ curl http://localhost:8481/select/0/prometheus/api/v1/export -d 'match[]=container_memory_working_set_bytes&reduce_mem_usage=1' > vm4697.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.5M    0 63.5M  100    61  50.1M     48  0:00:01  0:00:01 --:--:-- 50.2M
```

https://github.com/uhthomas/vm4697/blob/fca6deb33972389386e75c0b92fcbabd2275dcb8/vm4697.json

Hope this helpful.

**Comment by hagen1778** [comment]
Thanks for detailed info! 
I used the exported data from  here https://github.com/uhthomas/vm4697/blob/fca6deb33972389386e75c0b92fcbabd2275dcb8/vm4697.json and selected one specific time series with gaps when plotted:
```

container_memory_working_set_bytes{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",cluster="unwind",container="ceph-crash",feature_node_kubernetes_io_cpu_cpuid_AESNI="true",feature_node_kubernetes_io_cpu_cpuid_AVX="true",feature_node_kubernetes_io_cpu_cpuid_AVX2="true",feature_node_kubernetes_io_cpu_cpuid_CMPXCHG8="true",feature_node_kubernetes_io_cpu_cpuid_FMA3="true",feature_node_kubernetes_io_cpu_cpuid_FXSR="true",feature_node_kubernetes_io_cpu_cpuid_FXSROPT="true",feature_node_kubernetes_io_cpu_cpuid_LAHF="true",feature_node_kubernetes_io_cpu_cpuid_MOVBE="true",feature_node_kubernetes_io_cpu_cpuid_OSXSAVE="true",feature_node_kubernetes_io_cpu_cpuid_SYSCALL="true",feature_node_kubernetes_io_cpu_cpuid_SYSEE="true",feature_node_kubernetes_io_cpu_cpuid_VMX="true",feature_node_kubernetes_io_cpu_cpuid_X87="true",feature_node_kubernetes_io_cpu_cpuid_XSAVE="true",feature_node_kubernetes_io_cpu_cpuid_XSAVEOPT="true",feature_node_kubernetes_io_cpu_hardware_multithreading="true",feature_node_kubernetes_io_cpu_model_family="6",feature_node_kubernetes_io_cpu_model_id="63",feature_node_kubernetes_io_cpu_model_vendor_id="Intel",instance="talos-avz-rb5",job="kubelet",namespace="rook-ceph",node="talos-avz-rb5",pod="rook-ceph-crashcollector-talos-avz-rb5-7d57c857db-zhv8m"}
```

<img width="1309" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/7554381e-012f-4ae9-8095-b214edd7b6fb">


The gaps are there, indeed. So I checked the raw data via custom script which goes through timestamps and compares `TimeStamp N` to `TimeStamp N-1`. Here's sample of the script output
```
step 0s
step 26s
step 0s
step 18s
step 0s
step 35s
```
With my eyes, I see duplicates in the raw data:
<img width="157" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/a7bb124e-ad34-4b69-8f9e-c30a59badc80">

So apparently there are more than 1 vmagent or other metrics collector in this setup and they do produce duplicates. Duplicates, as I mentioned above, skew the staleness detection algorithm:
<img width="1288" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/34387ce1-dc01-4820-bf6c-a7ae293568eb">

I decided to apply `-dedup.minScrapeInterval=1ms` to remove the duplicates - there are much less gaps now:
<img width="1308" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/75232a60-1232-48db-9c0a-e2fb82ab7c49">

But still, there are gaps. Let's check what `scrape_interval` reports now:
<img width="1305" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/b4fc2b7c-d01a-4999-841e-7d2c48ee09ec">

Now we see that step fluctuates between 15s and 45s but still not stable. However, it shows how staleness detection is affected by the raw data VM gets ingested with.

Now let's get back to the question why raw data looks like this:
1. From the exported data it is clear there are more than 1 vmagent scraping the same targets. I see you set dedupMinInterval on storage level, but you also should set it on vmselect level - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#deduplication
2. Rate of `rate(vm_promscrape_stale_samples_created_total{prometheus="vm4697/vm4697"})` shows frequent changes. Stale sample is a mark generated by vmagent or Prometheus when target goes off (becomes unreachable). This mark is needed to skip staleness detection and immediately interrupt the line continuation for the target metrics. From what I see, targets are unstable - otherwise metric  `vm_promscrape_stale_samples_created_total` won't change so frequently. If you don't vmagent to react on these events - you can disable this behavior by passing ` -promscrape.noStaleMarkers ` flag to vmagent.

**Comment by uhthomas** [comment]
This is really interesting, thank you for investigating @hagen1778. I promise there is only one vmagent pushing to vm here. Could there be an issue with vmagent?

Thanks for pointing out the dedupMinInterval, I have this set on both [vmstorage](https://github.com/uhthomas/automata/blob/a537cdaada1f83d030cc4ba686cabc7536553708/k8s/unwind/vm/vm_cluster_list.cue#L99) and [vmselect](https://github.com/uhthomas/automata/blob/a537cdaada1f83d030cc4ba686cabc7536553708/k8s/unwind/vm/vm_cluster_list.cue#L53) already and it works okay.

So, to conclude, why is vmagent collecting metrics so inconsistently? As I mentioned before there is definitely only one vmagent active with the data I exported. There is only one `VMServiceScrape` object, and the target discovery from the vmagent shows there are no duplicates.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/9d114fb9-1b3b-4326-8639-5f8f3d04650d)

**Comment by uhthomas** [comment]
For what it's worth, I do observe the same behaviour with `scrape_interval` for that metric.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/e9cb2df4-bef4-49fc-ad55-4788f61e84c4)

Other metrics seem perfect, though...

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/600c5dce-ae78-4674-bf4a-6523d6067192)

**Comment by hagen1778** [comment]
ah! I should have remembered that...
cadvisor sets timestamps to the exported time series. While 99% of the exporters return you the following data:
```
metric1 10 
metric2 25
```
where 1st word is a metric **name**, 2nd is its **value** on the moment of scrape.

cadvisor returns:
```
metric1 10 1690480863
metric2 25 1690480863
```
where 3rd word is a **timestamp** when cadvisor last time cached the **value**. This cache time on cavisor side is controlled via `housekeeping_interval` param.

So if vmagent scrapes cadvisor more frequently than cadvisor updates its cache - you get duplicated values. Or you get unstable step, because cadvisor is not synchronized with time when vmagent scrapes this.

In Prometheus this didn't bother you, because Prometheus always set staleness interval to 5m, it is static. If you scrape metric each 5s and then it disappeared - Prometheus will continue plotting it for 5m. VM will stop plotting it in 10s. The opposite will happen with scrape intervals > 5m.

So what you can do here is to manually set `search.minStalenessInterval` to bigger interval and it will behave like Prometheus. Or ignore cadvisor timestamps by setting `honor_timestamps: false` in promscrape config for this target on vmagent side.

**Comment by uhthomas** [comment]
Yep, this makes sense. I was just looking into the cAdvisor implementation and realised the metrics are exported with explicit timestamps.

I'm glad we were able to figure out what was happening and why, but this then leaves what can we do to fix it? I recognise the two solutions you proposed will work, but they are not the default behaviour. VictoriaMetrics should be able to handle this case without any additional configuration.

**Comment by hagen1778** [comment]
> VictoriaMetrics should be able to handle this case without any additional configuration.

I see no good way to solve this and I'm open to suggestions.
So far I recognize this behavior of cadvisor as incorrect. Exposing timestamps in pull model is a bad practice. Consider the following issues:
* https://github.com/google/cadvisor/issues/2526
* https://github.com/prometheus-operator/kube-prometheus/pull/695
* https://github.com/prometheus/prometheus/issues/11565

Should Prometheus have lower staleness default or cadvisor higher housekeeping default - everything will break. This won't be a problem for anyone if cadvisor will just give up exposing timestamps.

I'd be glad to set `honor_timestamps` on vmagent side as `false` by default, but this can't be done for compatibility reasons with Prometheus.

**Comment by uhthomas** [comment]
I think unfortunately custom timestamps are here to stay and we just have to support it correctly. Many other projects also make use of it, like when forwarding metrics from other sources. Even the official Prometheus exports do this sometimes.

https://github.com/prometheus/influxdb_exporter/blob/4d655874d2f77c2e00ca09cd3e561cfc92fec126/main.go#L289-L291

I don't think I have enough domain knowledge to help with ideas on how to fix this. The only suggestion I have is to set the minScrapeInterval to 5m by default like Prometheus does.

**Comment by hagen1778** [comment]
> Many other projects also make use of it, like when forwarding metrics from other sources

Forwarding metrics from other sources don't produce duplicates. It is unlikely an application will push the same time series with the same timestamp twice. 
Dynamic staleness detection was added to VictoriaMetrics specifically because of native push model support. Because VM had to figure out how to detect stale series incoming from various sources with various resolution. Staleness is calculated for each time series independently which makes VM usable as a central TSDB which could store and process time series no matter if they have millisecond (high-frequency data, like one produced by netdata) or hour resolution (heavy recording rules calculated periodically or cronjobs). 
Ofc, Prometheus allows you to configure staleness interval as well. But it does it globally. As VM is supposed to be used as a central storage - there are better approaches to follow.

> Even the official Prometheus exports do this sometimes.

This exporter has it disabled by default. But anyway, this doesn't mean adding timestamp to pull model is the right thing to do. Take a look at this [comment](https://github.com/prometheus/prometheus/issues/11565#issuecomment-1557165722), for example. 

> The only suggestion I have is to set the minScrapeInterval to 5m by default like Prometheus does.

This only hides the problem, isn't it? You'll still have duplicates with identical timestamps stored in TSDB. Or when you apply `rate` in Prometheus it will capture an inconsistent number of data points for calculation, because the resolution of the metric is spiky. The thing that Prometheus doesn't plot gaps in this case only hides the real problem.

I think we should advocate for changing the cadvisor default behavior in the first place.
I'll try to bring more attention to this topic among the community and VM teammates, since my opinion could be different to others.

And thanks for not giving up on this issue and bringing more light to this problem!

**Comment by uhthomas** [comment]
I respect your position, and agree that custom time stamps does complicate things but there are genuine uses for it and that can't be ignored. It is not a solution to tell everyone not to use it, hundreds of metrics exporters already do. I agree that setting the default to 5m does not fix anything, but merely hides it. I don't really know what else to suggest though.

The reality is that VictoriaMetrics is not a drop-in replace for Prometheus because of this. Basically every single Kubernetes cluster uses cAdvisor and anyone who tries to view those metrics will see an incorrect and different representation compared to what Prometheus shows. There has to be a better way for VM to detect staleness as at current it does not seem sufficient.

Do you agree with my thoughts? What do you think VM can do to help with this?

**Comment by valyala** [comment]
The following solutions may be better to use:

- To manually set `honor_timestamp: false` for `cadvisor` [scrape config](https://docs.victoriametrics.com/sd_configs.html#scrape_configs). This will improve the situation in two ways:
   1. `vmagent` will use its own timestamps for metrics scraped from `cadvisor`. This will give graphs without gaps.
   2. The collected time series from `cadvisor` will have better compression rate because of constant interval between samples. This will result in lower disk space usage for these time series, and higher query performance.

- To set `honor_timestamps: false` by default for all the [scrape configs](https://docs.victoriametrics.com/sd_configs.html#scrape_configs). This will fix issues not only with `cadvisor`, but with other exporters, which may export metrics with incorrect timestamps. Actually, the `honor_timestamp` option was set to `false` by default until [the release v1.68.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.68.0). This option was set to `true` starting from this release (in [this commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c37f2854666150939e4a61a164dfb5f0392e5e5c)) for the sake of better compatibility with Prometheus. Now I think this was bad decision, since it brings more harm than benefits:
   1. It breaks staleness detection at VictoriaMetrics querying side
   2. It increases disk space usage for the collected metrics from exporters with broken timestamps
   3. It slows down query performance for such metrics
   There are a few legitimate cases for scrape targets, which export valid timestamps - for example, [scraping Prometheus via /federate endpoint](https://prometheus.io/docs/prometheus/latest/federation/). But this case is deprecated long time ago in favor of [setting up remote_write to long-term storage such as VictoriaMetrics](https://prometheus.io/docs/practices/remote_write/).

Given the above facts, I'm going to set the `honor_timestamps: false` by default starting from the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The commit e3ef3df938fb8f6afe8694ad9308e22e5f0b8ba8 should fix the issue with gaps on graphs for metrics collected from `cadvisor` or similar exporters, which export invalid timestamps. This commit will be included in the next release. In the mean time it is possible to test this fix by building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verifying that VictoriaMetrics stops producing gaps on graphs for `cadvisor` metrics collected by the `vmagent` built from the commit.

**Comment by valyala** [comment]
@f41gh7 and @Amper, could you check whether `cadvisor` is scraped with `honor_timestamps: false` in [VictoriaMetrics operator](https://github.com/VictoriaMetrics/operator) and [VictoriaMetrics helm charts](https://github.com/VictoriaMetrics/helm-charts)? If this isn't the case, then it must be fixed - see [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1656540535) for details.

**Comment by f41gh7** [comment]
> @f41gh7 and @Amper, could you check whether `cadvisor` is scraped with `honor_timestamps: false` in [VictoriaMetrics operator](https://github.com/VictoriaMetrics/operator) and [VictoriaMetrics helm charts](https://github.com/VictoriaMetrics/helm-charts)? If this isn't the case, then it must be fixed - see [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1656540535) for details.

`grep -r 'honor_timestamps' helm-charts/charts/` - shows nothing.


 @valyala  it's not a `BUGFIX`. It's a breaking change that we must mention at changelog. It may break users configuration.

**Comment by hagen1778** [comment]
@f41gh7 see the update note here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c36259fca5ae9c8e58e9d6c56512cdcbedd091c3

**Comment by valyala** [comment]
FYI, starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html), [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) and [vmagent](https://docs.victoriametrics.com/vmagent.html) ignore timestamps provided by scrape targets by default unless the `honor_timestamps: true` option is set at the corresponding [scrape_configs](https://docs.victoriametrics.com/sd_configs.html#scrape_configs).

This should remove gaps from graphs built from metrics obtained from scrape targets, which improperly set timestamps for the exported metrics (such as [cadvisor](https://github.com/google/cadvisor) ). This should also reduce disk space usage for such metrics and increase query performance. Closing the issue as fixed then.

**Comment by valyala** [comment]
FYI, the bugfix described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1675936197) has been back-ported to [v1.87.7 long-term support release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.7).

**Comment by GrahamDennis** [comment]
I know this issue is closed, but I hit a similar issue myself and actually root-caused it to vmagent inserting staleness markers if a series didn't have data every scrape. Passing `-promscrape.noStaleMarkers` to vmagent resolved the problem for me.  This feels like a better solution here (or making vmagent a little less aggressive at inserting staleness markers by default) than discarding timestamps from source systems?

**Comment by valyala** [comment]
> This feels like a better solution here (or making vmagent a little less aggressive at inserting staleness markers by default) than discarding timestamps from source systems?

[Staleness markers](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) logic isn't related to handling of timestamps provided by scrape targets (aka `honor_timestamps` option). Currently `vmagent` follows `Prometheus` logic for handling staleness markers as described [here](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers). Probably, this logic could be made less aggressive by default.

**Comment by uhthomas** [comment]
These metrics don't seem to export timestamps.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/5b98e555-b8be-4bf6-9f6c-3cc89bfdb5fe)

**Comment by hagen1778** [comment]
Hey @uhthomas! Could this be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5388 ?
Could you try running your queries with cache disabled? Or try upgrading vmselect to 1.96?

**Comment by uhthomas** [comment]
@hagen1778 Should we discuss on #5576?

I am running vmsingle, so vmselect is not relevant here.

**Comment by uhthomas** [comment]
> > I am running vmsingle, so vmselect is not relevant here.
> 
> vmsingle reuses the same codebase as cluster. So both versions were vulnerable to the mentioned bug.

Thanks, I will try v1.96.0 later. However, the vmsingle instance is not restarting at all during those times so I am not confident the issue will be fixed?

**Comment by hagen1778** [comment]
> Thanks, I will try v1.96.0 later

You can try it on 1.95.1 with cache disabled (via GET param or by using vmui).

>  the vmsingle instance is not restarting at all

The mentioned bug isn't related to restarts; that was a coincidence.

**Comment by uhthomas** [comment]
> > Thanks, I will try v1.96.0 later
> 
> You can try it on 1.95.1 with cache disabled (via GET param or by using vmui).
> 
> > the vmsingle instance is not restarting at all
> 
> The mentioned bug isn't related to restarts; that was a coincidence.

Ah, this does seem to fix it. Thank you. I will try the new version to verify later also.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/85aa3c40-2807-44cc-aef7-d2405a446591)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/6a72b8d8-e329-41c1-93be-1125e20254db)
