### ISSUE TITLE
Do I have to use vmauth between Prometheus and VMinsert if I don't have enterprise license ?

### ISSUE THREAD

**Issue by hasanawad94** [VictoriaMetrics/VictoriaMetrics#4700]
### Is your question request related to a specific component?

Cluster version
VMinsert

### Describe the question in detail

I'm trying to create a secure communication between Prometheus and VMinsert.
Can't I simply use a TLS certificate for VMinsert and Prometheus or do I need to have enterprise to do this ?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @hasanawad94.
You can use vmauth without enterprise license. All the functionality you need (users with basic auth / bearer tokens) is available in the open-source version of vmauth :)
At the moment, only ip-filters are enterprise functionality.

You can also use TLS, but:
- Not as a replacement, but as an addition to authorization so that credentials cannot be hijacked
- It only makes sense if prometheus and vmauth/VictoriaMetrics communicate over an insecure network

**Comment by Amper** [comment]
Ah, you meant [mTLS for cluster components](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection) of VM.
Yes, it is available only in enterprise version.

**Comment by hasanawad94** [comment]
Will use vmauth
