### ISSUE TITLE
vminsert gets overloaded with ingestion request when vmstorage goes off

### ISSUE THREAD

**Issue by andyli029** [VictoriaMetrics/VictoriaMetrics#4703]
### Describe the bug

`When one storage node goes down, inserting is failed`

### To Reproduce

When one node goes down, inserting is failed.

### Version
```
$ /usr/local/bin/vmstorage-prod--version
vmstorage-20230602-113236-tags-v1.91.2-cluster-0-ga1b6a9317
```
### Logs

Logs on the other storages are:
```
vminsert-prod[1553]:  2023-07-21T09:36:25.501Z#011warn#011VictoriaMetrics/app/vminsert/main.go:245#011remoteAddr: "10.90.120.8:51378"; 
requestURI: /insert/0/prometheus; 
cannot read compressed request in 60 seconds: cannot process insert request for 60.000 seconds because 64 concurrent insert requests are executed. 
Possible solutions: to reduce workload; to increase compute resources at the server; 
to increase -insert.maxQueueDuration; to increase -maxConcurrentInserts
```

**Comment by hagen1778** [comment]
Hello @andyli029! Have you gone through https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion ?

**Comment by andyli029** [comment]
> Hello @andyli029! Have you gone through https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion ?

I have browsed it.

@hagen1778 
Are there any similar situations or recommended links

**Comment by hagen1778** [comment]
@andyli029 Troubleshooting section should help to understand what is happening in most of cases. I'd recommend reading the whole page in order to understand how VM cluster works and what to expect. Probably, after reading it you can share additional details like: here's how many vmstorage and vminstert instances I have, here's my config, here's Grafana dashboard showing what happens when vmstorage node goes off, etc. These details would help us to communicate in a more productive way.

**Comment by hagen1778** [comment]
Hi @danielkza! I'd recommend upgrading to the latest versions of VM as they contain many improvements to re-routing mechanism and to the performance of registering new time series (what happens during rerouting). 

I'd also recommend checking https://docs.victoriametrics.com/cluster-victoriametrics/#improving-re-routing-performance-during-restart. Please note, the mentioned settings are available in recent versions only.

**Comment by jiekun** [comment]
Close as answered.
