### ISSUE TITLE
vmstorage crashes when built with an old version of glibc

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#4714]
### Describe the bug

We have been running vm-cluster version 1.91.3 for a few weeks.
We have met this for serveral times:
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

### To Reproduce

N/A  Do not know the circumstance that will trigger this issue

### Version

v1.91.3-cluster  (is built by us)

### Logs

[crash.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12167551/crash.log)

### Screenshots

![screencapture](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/33677006/2fd1658e-4a2f-43ff-9ebb-2b5156d62958)

### Used command-line flags

```./vmstorage-prod -search.maxUniqueTimeseries=2000000 -storageDataPath=/lingtian/opt/vmstorage-data -retentionPeriod=31d -bigMergeConcurrency=1```

### Additional information

```
uname -a 
 5.12.12-1.el7.elrepo.x86_64 #1 SMP Thu Jun 17 10:00:40 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

We have 40 vmstorage in two physically separated cluster; each have 20 vmstorage.

**Comment by zekker6** [comment]
Relabed thread in community slack - https://victoriametrics.slack.com/archives/CGZF1H6L9/p1690342896377589

**Comment by renchili** [comment]
@zekker6  hi, well, they are a similar topic but not pointing to solving the same issue.
This issue raised here aims to have a solution to stop the crash.

The question raised in Slack aims to understand better the compile logic and the support of cgo or no cgo.
Is more like a general question with DIY second development based on VM source code.

**Comment by renchili** [comment]
as 
 Nick said in Slack, the fatal error seems no direct link with running cgo or not, so shall we treat them not the same issue/question?
@zekker6

**Comment by renchili** [comment]
@zekker6  any update?

**Comment by renchili** [comment]
@zekker6 Hi we did some tests:
We tried to build without CGO but failed. We cannot provide https://www.musl-libc.org/ because our building server did not have this. 
We are now running with the official binary and since then no crashes. 

We wonder how to build from source code. We see it is possible to build the binary with docker-go.
As there is already have docker deployment method, can you make a build command that uses the docker golang container to generate the binary.

**Comment by zekker6** [comment]
@renchili As per instruction referenced above you need to run the following command from repository root:
```
make vminsert-prod vmselect-prod vmstorage-prod
```
This will use docker to build binaries inside containers and will put resulting binaries into `bin/`.

You can find build build steps which are used by this command in the following make files:
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/Makefile
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/Makefile
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmstorage/Makefile
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vminsert/Makefile

**Comment by renchili** [comment]
@zekker6, how about vmagent vmalert?

**Comment by renchili** [comment]
@zekker6  

> @renchili As per instruction referenced above you need to run the following command from repository root:
> 
> ```
> make vminsert-prod vmselect-prod vmstorage-prod
> ```
> 
> This will use docker to build binaries inside containers and will put resulting binaries into `bin/`.
> 
> You can find build build steps which are used by this command in the following make files:
> 
> * https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/Makefile
> * https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/Makefile
> * https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmstorage/Makefile
> * https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vminsert/Makefile

This version is CGO enabled or without CGO? What is the running os requirement?

**Comment by zekker6** [comment]
@renchili You can find make files for vmagent/vmalert and other application in master branch under `app/{application}/Makefile`:
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/Makefile
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/Makefile

> This version is CGO enabled or without CGO? What is the running os requirement?

This will build a version with CGO enabled. Build will be performed inside docker container managed by make file, so the only requirement to the OS is to have docker running and ensure CLI is configured to have access to docker daemon.

**Comment by renchili** [comment]
@zekker6  i mean the host os where vm binary will run on; if it asks for CGO, we are afraid that our kernel version and glibc
version will cause some issues.

```
uname -a 
 5.12.12-1.el7.elrepo.x86_64 #1 SMP Thu Jun 17 10:00:40 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

```
 ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by zekker6** [comment]
@renchili Binaries built with commands which has `-prod` suffix will be statically linked. You can check this by running:
```
ldd ./bin/vminsert-prod
        not a dynamic executable
```

**Comment by renchili** [comment]
hi  after trying a lot we still wonder why the official building 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/33677006/8d89f579-a76a-4205-87c2-890bf96c82ae)

and why the production mode was built using an `alpine` such not common Unix-like system.
this made our work very difficult to do secondary development.

our building system cannot provide any support to run `alpine` like system. And they forcing us to standardize using Centos.
well, I cannot agree with them, but at least, Victoria Metric should use a common base image or a standardized building procedure.

**Comment by zekker6** [comment]
Hi @renchili 

> and why the production mode was built using an alpine such not common Unix-like system.
this made our work very difficult to do secondary development.

There are two reasons for this:
- it has much smaller disk footprint than using some more streamlined distros
- it uses musl which suits CGO builds better

On arm64 musl builds are working up to 15-20% faster(see https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a8acad7453365254ae4e59a91bfcd66556d8dfdd) so it is used for VM builds by default.

CGO is used because VictoriaMetrics uses zstd compression performed by C wrapper library by default(wrapper library is https://github.com/valyala/gozstd). In case you cannot use CGO on your environment, you can use pure Go builds instead.
Pure go builds will be slightly slower due to usage of Go instead of C library, but will be easier to build in your case.
Pure go build targets are suffixed with `-pure` for in make targets.

>  well, I cannot agree with them, but at least, Victoria Metric should use a common base image or a standardized building procedure.

Actually, there are both a common base image and standardized building procedure in place.
Base image is built by using:
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2e04ddbd327962f1b355c9381be9b97915169844/deployment/docker/Makefile#L8-L28
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/builder/Dockerfile
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/base/Dockerfile

Building procedure is based on using make file so it is pretty standard and works well on different platforms. Production builds are using docker to perform reproducible builds. Also, this allows to make sure that there are no issues with toolchain setup for some specific dev environments.

**Comment by valyala** [comment]
Pure go builds (without cgo) can be created by passing `CGO_ENABLED=0` environment variable to `go build` command. See [these instructions](https://docs.victoriametrics.com/#pure-go-build-cgo_enabled0). VictoriaMetrics repository contains Makefile targets for building all the components without cgo - these targets end with `-pure` suffix as @zekker6 mentioned above. For example, in order to build cluster components of VictoriaMetrics without cgo, you can run the following command from the root directory of VictoriaMetrics repository:

```
make vmstorage-pure vmselect-pure vminsert-pure
```

Then the `bin` directory will contain the built binaries:

```
$ ls -l bin/
total 42200
-rwxrwxr-x 1 valyala valyala 13341350 Sep  6 17:25 vminsert-pure
-rwxrwxr-x 1 valyala valyala 16630321 Sep  6 17:25 vmselect-pure
-rwxrwxr-x 1 valyala valyala 13208273 Sep  6 17:25 vmstorage-pure
```

If you want building production-ready cluster components of VictoriaMetrics without cgo (these components are built inside Docker containers), then run the following command:

```
make vmstorage-pure-prod vmselect-pure-prod vminsert-pure-prod
```

The built binaries will be available in the `bin` directory after that:

```
$ ls -l bin
total 39960
-rwxr-xr-x 1 valyala valyala 12568131 Sep  6 17:26 vminsert-pure-prod
-rwxr-xr-x 1 valyala valyala 15869654 Sep  6 17:26 vmselect-pure-prod
-rwxr-xr-x 1 valyala valyala 12451416 Sep  6 17:26 vmstorage-pure-prod
```

**Comment by zekker6** [comment]
Closing this issue as stale. Please, reopen if more related questions will arise.
