### ISSUE TITLE
vmstorage OOM killed before indexdb merged every week

### ISSUE THREAD

**Issue by victzhao** [VictoriaMetrics/VictoriaMetrics#4726]
### Describe the bug

We have a cluster of 9 nodes using the Victoriametrics cluster version as vmstorage-20221014-073231-tags-v1.82.1-cluster-0-gb942dd77c for a long time, but recently, oom events often occur on a random node, such as:
[Thu Jul 27 09:22:58 2023] Out of memory: Kill process 1473 (vmstorage-prod) score 922 or sacrifice child

We set retentionPeriod=1w, so this cluster recycles data at 12 o'clock (utc+8) every Thursday, after oom occurs this node cannot merge indexdb normally like other nodes，we can see from the monitoring：
![1](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/69293305-edcb-40ad-b1ae-b8686d115d9d)

However, oom often occurs about 3 hours before 12:00 every Thursday. The following is the monitoring when oom occurs. It can be seen that before oom, this node has a large number of disk read requests, and the load is relatively high, while other nodes are normal.
![2](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/40ea4e4a-481f-4a5c-a865-8d5ab9037da3)
![3](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/8d5f3c14-662d-4c21-8de6-a28fff1c03be)
![4](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/0b9fc1d4-929a-45df-8fef-7bfbed2e5a43)
![5](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/6620fb4c-e688-4c8b-a491-7533f2cfe556)
![6](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/0fee23b7-33a6-4627-8cff-c5632c0c5af9)
![7](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/0c527a0c-b65b-4321-9f22-bf7dadb06573)
![8](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/ea444816-a0f3-45f3-b433-48b513b86e65)
![9](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/1a6d00b8-acf5-4f02-b7da-b555b81920f0)
![10](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/0740874c-8ce4-475b-a4e7-12eaab557cef)

And our cluster is quite special, the size of indexdb is much larger than storage/small and storage/big data, as follows:

![11](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15981202/0f5136dc-1b3f-4225-ad07-e565f89287f4)

### To Reproduce

nothing

### Version

vmstorage-20221014-073231-tags-v1.82.1-cluster-0-gb942dd77c

**Comment by valyala** [comment]
@victzhao , thanks for filing the bugreport! It looks very similar to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401 . This issue should be fixed in the next release.

Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401 .

**Comment by valyala** [comment]
> And our cluster is quite special, the size of indexdb is much larger than storage/small and storage/big data

The size of `indexdb` is usually smaller than the size of `data` for typical workloads. The `indexdb` size can be big under [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate), since VictoriaMetrics needs to store all the labels for every newly ingested time series in the `indexdb`. Your VictoriaMetrics has quite big churn rate according to the provided graphs - from 5k to 30k new time series per second. This translates to `5k*3600*24=432 million` of new time series per day. If VictoriaMetrics is configured with the [retention](https://docs.victoriametrics.com/#retention) of 7 days, then the `indexdb` contains the information about `432M*7 = 3 billion` time series. VictoriaMetrics maintains two `indexdb` parts - one for the current retention, and another one for the previous retention. This increases the number of time series registered in the `indexdb` to `2*3= 6 billion`. VictoriaMetrics puts the `label=value` entries per each label per each time series in the `indexdb`, which are called `inverted index` - it is needed for fast lookup of time series for a particular [label filters](https://docs.victoriametrics.com/keyConcepts.html#filtering). So the size of `indexdb` is proportional to the average length of metric name plus all its labels. For example, if you store some kind of Kubernetes metrics with 30 labels per each series and with the average label value length of 20, then a single time series takes at least 30*20=600 bytes in the `indexdb`. So, in your case, 6 billion time series registered in the `indexdb` will occupy at least 6B * 600= 3.6TB of disk space. This number is close to what you have according to the provided `indexdb size` graph above.

**Comment by victzhao** [comment]
@valyala  Thank you very much, the problem is solved after we upgrade to v1.92.1
