### ISSUE TITLE
Does VictoriaMetric support Date Ranges?

### ISSUE THREAD

**Issue by arianitu** [VictoriaMetrics/VictoriaMetrics#474]
**Is your feature request related to a problem? Please describe.**
We are looking to use VictoriaMetrics for data on bandwidth usage but we are wondering if we can query the data by a date range, such as "Bandwidth used in April", "Bandwidth used between X date and Y date"

We need exact numbers as well so we are wondering if the returned data is exactly accurate.

**Describe the solution you'd like**

Date range support or a query that VictoriaMetrics supports.

**Describe alternatives you've considered**
In Prometheus, a lot of people recommend using increase() with an interval. We are actually unsure how that works and how it would allows us to do date ranges. 

Generally the sentiment is that Prometheus is a poor solution for anything non-trailing, but we really don't want to introduce another database just to get bandwidth usage between X and Y dates.

**Comment by arianitu** [comment]
Oh, one other question, does VictoriaMetrics work with https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go or do we need to use VictoriaMetrics API?

**Comment by arianitu** [comment]
The more I look into this, the more people suggest log-centric monitoring to get exact numbers of bandwidth for things like billing.

I understand that's the case for Prometheus, but is there anything in VictoriaMetrics that could give us exact measurement of bandwidth for a period of time? 

It would really suck to have to introduce another analytical system, maybe recording rules can help us? The metrics we are looking to collect exactly are:

1. Monthly Bandwidth
2. Monthly Unique Visits

Both could be achieved by parsing nginx/apache logs and summing them as the data comes in, but we would love to use just stick to one system as every other metric does not need to be exact.

**Comment by valyala** [comment]
VictoriaMetrics supports the following functions, which can be used for calculating metric sum on date ranges:

* `increase(m[d])` returns the increase of counter `m` over the duration `d`. Counter is a time series, which starts from 0 and then may only grow. It may reset to 0 only on service reset. For instance, `increase(bytes_sent_total[7d])` would return the amount of data sent during the last 7 days.

* `sum_over_time(m[d])` returns the sum of all the values for gauge `m` over the duration `d`. A gauge is a time series, which can go up and down at any time. For instance, `sum_over_time(bytes_sent_since_last_scrape[7d])` would return the sum of all the values for `bytes_sent_since_last_scrape` time series over the last 7 days.

See the full list of functions supported by VictoriaMetrics at [MetricsQL page](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL).

So it is possible to store and calculate monthly bandwidth with `increase` or `sum_over_time` functions depending on time series type.

I'm afraid it is impossible to calculate monthly unique visits with VictoriaMetrics, since you need storing all the visitor_ids somewhere in order to calculate unique count for these visitor_ids over the specified time range. VictoriaMetrics supports only time series with `(timestamp, value)` pairs where `value` is a floating-point number. Though `visitor_id` could be stored in time series label, this is bad solution, since it may result in high number of time series, which may lead to high cardinality issues - slow performance and high memory usage.

**Comment by arianitu** [comment]
1. is there any way to get an Increase for a date range? For example, if it's May 15th, how would you calculate the date range April 1st - April 30th.

Do you have to do some special math were you use an offset or something?

2. Ah okay, that makes sense. I think the more I think about this, the better it is to just process the stream and calculate exact sums for things like unique visitors and bandwidth, but it was worth a shot to see if we could do it all inside something like VictoriaMetrics.

Thanks for the insight. Just that last question, does VictoriaMetrics have its own client, or can we just use the Prometheus API to connect to VictoriaMetrics?

**Comment by valyala** [comment]
> is there any way to get an Increase for a date range? For example, if it's May 15th, how would you calculate the date range April 1st - April 30th.
> Do you have to do some special math were you use an offset or something?

VictoriaMetrics supports [PromQL offsets](https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier). For isntance, the following query would return week-old `increase` results `increase(bytes_sent_total[30d] offset 7d)`.

If you need just a single number for the increase on specific date range, then it is easier to do via a query to [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-queries). For instance, the following command would return increase for `bytes_sent_total` metric on the date range April 1st - April 30th:
```
curl http://victoriametrics-host:8428/api/v1/query -d 'query=increase(bytes_sent_total[30d])' -d 'time=2020-05-01T00:00:00Z'
```

> does VictoriaMetrics have its own client, or can we just use the Prometheus API to connect to VictoriaMetrics?

VictoriaMetrics doesn't provide a client yet. But since [it supports Prometheus API](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#prometheus-querying-api-usage), arbitrary client for Prometheus should work with VictoriaMetrics. I'd recommend just sticking with either `curl` or with standard http client + json libraries for the preferred programming language. This usually ends up with simpler code than using specialized client for Prometheus.

**Comment by arianitu** [comment]
Amazing, thank you! 

I'll try using the Golang Prometheus API, but if it does not work correctly, we can switch to a plain HTTP client.
