### ISSUE TITLE
vmselect: error parsing regexp: invalid nested repetition operator: `**`

### ISSUE THREAD

**Issue by serrrios** [VictoriaMetrics/VictoriaMetrics#4826]
### Describe the bug

When use servicegraph in grafana with generated metrics from tempo:

422: error when executing query="histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"GET /actuator/health/**\"}[3600s])) by (le))" for (time=1691997627463, step=300000): cannot expand WITH expressions: invalid regexp in span_name="GET /actuator/health/**": error parsing regexp: invalid nested repetition operator: `**`

### Version

1.92.*

**Comment by Amper** [comment]
Hey @serrrios. It's not a bug.
The problem is that instead of the `=` operator, you use the `=~` operator, which compiles the label value as a regular expression. And `**` - it's incorrect regular expression.

The same result you can see in Prometheus: http://demo.robustperception.io:9090/graph?g0.expr=traces_spanmetrics_latency_bucket%7Bspan_name%3D~%22GET%20%2Factuator%2Fhealth%2F**%22%7D&g0.tab=1&g0.stacked=0&g0.range_input=1h

**Comment by serrrios** [comment]
Yes, I understand. Requests are generated by grafana itself. And there is no way to change them. As a result, the service graph does not work. I'll leave another issue in the grafana.

**Comment by Amper** [comment]
Hey @serrrios, this issue is still relevant to you?
