### ISSUE TITLE
topk/bottomk performance and correctness

### ISSUE THREAD

**Issue by fuochuy** [VictoriaMetrics/VictoriaMetrics#4844]
### Describe the bug

I have had a few issues with topk, bottomk functions. Follow your docs, topk and bottomk return up to k points with the smallest values or biggest values across all the time series returned by q. But sometimes, bottomk function returns no data, or points are returned less k.

### To Reproduce

I use query_range with match[] below:
- topk(3, (avg(avg_over_time(metric_name)) by (pod)))
- bottomk(3, (avg(avg_over_time(metric_name)) by (pod)))

### Version

v1.79.0

**Comment by wanghaao** [comment]
I also found it.

Moreover, the performance of topk and bottomk is much worse than standard Prometheus.

**Comment by hagen1778** [comment]
> But sometimes, bottomk function returns no data, or points are returned less k.

Could you please elaborate more on that or provide an example when it works like that? We have a [playground](https://play.victoriametrics.com/select/0/prometheus/graph/) where we can try to reproduce the issue.

Apart of that, have you tried updating to more recent versions? Even if there is a bug, it is unlikely the fix will make it to v1.79. So it is worth trying newer versions of VM.

**Comment by hagen1778** [comment]
> I also found it.
Moreover, the performance of topk and bottomk is much worse than standard Prometheus.

Would be great if you can provide more specifics to that. Like how to reproduce the issue or how "much worse" looks like?

I did a quick test: found metric names with about equal cardinality (of 2k series) and used topk at Prometheus and VM instances on 24h time interval:
* Prometheus, `topk(10, caddy_http_response_duration_seconds_bucket)`, load time: 3030ms. Try [here](http://demo.robustperception.io:9090/graph?g0.expr=topk(10%2C%20caddy_http_response_duration_seconds_bucket)&g0.tab=0&g0.stacked=0&g0.range_input=1d). _Prometheus doesn't allow to disable caching_.
* VictoriaMetrics, `topk(10, storage_operation_duration_seconds_bucket)`, load time 500ms. Try [here](https://play.victoriametrics.com/select/0/prometheus/graph/#/?g0.range_input=24h&g0.end_input=2023-08-18T06%3A32%3A38&g0.tab=0&g0.relative_time=last_24_hours&g0.tenantID=0&g0.expr=topk%2810%2C+storage_operation_duration_seconds_bucket%29&g0.step_input=42m30s). _VM allows disabling caching_.

That's not ideal case, because we don't know how much resources mentioned Prom has. But at least it allows us to compare numbers.

**Comment by wanghaao** [comment]
I did the test based on the prometheus-benchmark project. @hagen1778 
case 1:
```
bottomk(3, node_softnet_processed_total)
timeseries cardinality: 160k
range: 10min
Prometheus: 3808ms, VM: 9299ms
```

case2:
```
bottomk(3, node_cpu_seconds_total)
timeseries cardinality: 1280000
range: 10min
Prometheus: 32141ms, VM: 93664ms
```

**Comment by wanghaao** [comment]
https://github.com/VictoriaMetrics/prometheus-benchmark

**Comment by hagen1778** [comment]
I see there is a separate discussion about functions performance here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4853

**Comment by Joey777210** [comment]
Same issue, bottomk returns less result than expected.
case: `bottomk(5, cpu_usage)` only returns 1 result.

**Comment by hagen1778** [comment]
@Joey777210 which version of VM do you use? Could you try the same query on 1.97+?
See potentially related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5506

**Comment by jiekun** [comment]
Close due to inactivity.
