### ISSUE TITLE
Q: VM Histogram supported `vmrange` label values

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#489]
Do I understand correctly: for VM Histogram label `vmrange` can contain any meaningful and disjoint with other "buckets" range, including negative values?

I assume that the `start` and `end` values of the `vmrange` are then converted using `strconv.ParseFloat`:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2392a359e1dd5a4cd2215515aa60772b795e8e29/app/vmselect/promql/transform.go#L317
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2392a359e1dd5a4cd2215515aa60772b795e8e29/app/vmselect/promql/transform.go#L322

So, can I use, for example, the following ranges, and not just those generated by the https://github.com/VictoriaMetrics/metrics package?

```
test_bucket{vmrange="-5.0e+3...0"}
test_bucket{vmrange="0...5.0e+3"}
```

**Comment by valyala** [comment]
It looks like it should work as expected, but there are no guarantees, since the code for histogram processing in [MetricsQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL) was optimized for histograms generated by https://github.com/VictoriaMetrics/metrics package.

Feel free sending pull requests that fix any issues related to processing of non-standard `vmrange` values in `MetricsQL`.

**Comment by Allineer** [comment]
Thanks.

**Comment by valyala** [comment]
Note that the most important property of histograms from https://github.com/VictoriaMetrics/metrics is that value ranges (i.e. all the possible `vmrange` labels) are statically defined there. This allows aggregating different histograms. If this property is violated, then such histograms cannot be aggregated as described in [this post](https://medium.com/@valyala/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350).
