### ISSUE TITLE
Timeout for vmalert checking rules in a group

### ISSUE THREAD

**Issue by wanghilbert** [VictoriaMetrics/VictoriaMetrics#491]
**Is your feature request related to a problem? Please describe.**
When the performance of network or storage is not good, or a group contains a lot of rules, it could be timeout for vmalert checking rules in a group and sending alerts.

**Describe the solution you'd like**
It could be nice to allocate a goroutine for a rule query.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hagen1778** [comment]
Hi @wanghilbert! Sounds interesting! I'm not sure if running rules in parallel will help with slow storage. Very likely that it will make situation even worse. We already running every group concurrently, so it is possible just to re-arrange rules into separate groups. Although having too much rules is more likely than having too much groups, so we don't need to control number of goroutines here. However, it is easy to set some `concurrency-level` per-group, where user can set how many rules to run at once.

But there is more serious question here - chaining of rules execution.  This is important, because originally Prometheus defined rule concept the same for alerts and recording rules. And we have feature requests to do the same - support recording rules and compatibility with Prometheus.
The sequential nature of rule execution in group means that you can use rules you create in subsequent rules. This allows to create a metric from a rule and then reuse that metric in a later rule.

So if we want to keep compatibility with Prometheus here we need to address rules chaining when executing them concurrently. What do you think @valyala @tenmozes @wanghilbert ?

**Comment by tenmozes** [comment]
For me idea sounds good, i guess the concurrent running can suite for majority of users who don't have depended rules. We can introduce static param and define the number of goroutines for the group or dynamic based on the number of rules.

**Comment by valyala** [comment]
IMHO, it would be great to leave sequential rules' execution in each group like Prometheus does.

We can add an additional `-groupConcurrency` command-line flag or per-group `concurrency` option, which could be set inside each group config, so users could control per-group concurrency if they really want this.

**Comment by wanghilbert** [comment]
Hi @hagen1778, I got the point of chaining rules. I think it may be also nice to optimize the doc to make clear that a group is a batch of related rules, and it is better to keep independent between groups. @valyala Valyala's idea is also very nice, but I think it could be more complicated to avoid data race between goroutines.

**Comment by valyala** [comment]
FYI, the concurrency-per-group feature has been added in`vmalert` [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
