### ISSUE TITLE
Assistance with configurating components

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#4963]
### Is your question request related to a specific component?

VictoriaMetrics, vmagent, vmalert

### Describe the question in detail

![proposta](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/ba3bae67-fd5d-41b2-ab5a-0b09e412a167)

From the diagram above it is possible to see my intentions. I want to create a monitoring system that scrapes metrics using vmagent from several node exporters into a VictoriaMetrics instance that will store them and allow it to be visualized. Also there is a need to monitor alerts as close to the metric scrapping source as possible while managing all alerts in a centralized entity such as the AlertManager .
I am having some trouble in developing the correspondent docker files to achieve this. Is there any sample yaml or docker files you would suggest me to look over to better comprehend how to do this?
What advices would you give me as well as possible optimization suggestions to improve the system.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
Hey @DaRealCapz , did you see our guide - https://docs.victoriametrics.com/guides/multi-regional-setup-dedicated-regions.html ?
![Untitled-2023-09-06-1111](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/5650611/bd774f2b-b291-4203-a9b4-3a7603adc95f)

Your diagram looks okay but it has some mistakes like the connection between vmagent and vmalert. Let me explain: vmalert [can connect to](https://docs.victoriametrics.com/vmalert.html#vmalert) VictoriaMetrics Single, Cluster, or other compatible with Prometheus HTTP API but it can't query vmagent. [vmagent](https://docs.victoriametrics.com/vmagent.html) helps you collect metrics from various sources, [relabel and filter the collected metrics](https://docs.victoriametrics.com/vmagent.html#relabeling), accept data via all the ingestion protocols supported by VictoriaMetrics (see [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-push-data-to-vmagent)). 

I would recommend running a local VM database for every region. All vmagent will scrape metrics from exporters and send them to the local VM database and duplicate them to the Main VM database with a big retention period. Or if you want to use Prometheus instead of VM for every region - it should be fine too. See also https://docs.victoriametrics.com/FAQ.html#can-i-use-victoriametrics-instead-of-prometheus. 

See updated diagram:

**Comment by DaRealCapz** [comment]
Hello @denisgolius, first of all thank you for the link provided, had not seen it yet was very enlightening.
Would also like to thank you for clearing up the design I presented and showing the adjustments that meet the Victoria Metrics documentation.

After seeing the design presented I started theorizing on a new system that would comprise of 2 subsystems:
One would be focused exclusively on alerting, this meaning it would evaluate metrics received every second for example.
The second would focus on presenting metrics to the system admin on demand, meaning that only if requested then a Grafana would graphically show the metrics graph after the vmagent supplied them. This system aims at resource optimization since it would minimize data transfers between the agents and the TSDB while keeping alert detection and propagation as fast and soon as possible.

But when sketching this new system some questions appeared:
1- Is there a possibility to use a vmagent to poll data from a VictoriaMetrics when the system admin requires it?

2- Since vmagents have a cache for the scrapped metrics, is there a way of the vmalert to access that cache and evaluate the rules established thus optimizing the time taken to detect a possible alert instead of evaluating it only when the metrics reach the VM TSDB? If not, is it possible for me to develop this, or is it not allowed?

3- Lets say I have several vmagents close to the edge layer scrapping metrics from smartphones, Iots etc... Is there a way for me to. when those metrics are scrapped, associate with them where these are coming from, what service is running on those devices? This would allow for the top level system admin to pinpoint what region is running what services and in case of alerts being triggered, it would help the admin to know where it comes from and what service might have caused it.

Thank you for your assistance!

**Comment by jiekun** [comment]
> Is there a possibility to use a vmagent to poll data from a VictoriaMetrics when the system admin requires it?

No. vmagent is used to scrape metrics or receive remote-write data. VictoriaMetrics instance does not support remote write to export data.

> is there a way of the vmalert to access that cache and evaluate the rules established thus optimizing the time taken to detect a possible alert instead of evaluating it only when the metrics reach the VM TSDB?

No.

> Is there a way for me to. when those metrics are scrapped, associate with them where these are coming from

You could try relabeling. See https://docs.victoriametrics.com/relabeling/
