### ISSUE TITLE
how to confirm exactly is it a query visit the data from big directory

### ISSUE THREAD

**Issue by jingb** [VictoriaMetrics/VictoriaMetrics#4992]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

i am try to mount the storageDataPath/data/big directory of vmstorage to the distributed file storage system. and the small directory still in local disk. and i want to compare the performance of the two different way under same benchmark pressure. 
I will use the tools https://github.com/VictoriaMetrics/prometheus-benchmark to do the benchmark. And i specially care about the query performance related about the big directory, cause i describe above that is was mount to the remote storage. And get some measurable metrics like query latency P95\P99.
**the question is how could i confirm exactly is it a query visit the data from big directory？**
or are there any convenient method to achieve the comparement goal i describe above 
thanks

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
Hello @jingb !
Could you share more information about your `distributed file storage system`?

**Comment by jingb** [comment]
@denisgolius 
it it a product that developed by another team not a product from public cloud vendor. 
from a user perspective, i could use it as a volume, conveniently scale the capacity, if i set the replica of the volume in 2, it could guarantee the 2 replica of every file in the system were distributed into two different physical machine or vm or any other？of cause we could set the replica of volume higher. It is a comprehensive result that takes into account cost, availability and complexity.

**Comment by denisgolius** [comment]
You can try to make queries to historical data and it will be queries to big parts, but we can't guarantee anything because we don't have such metrics. Perhaps some exporter for file systems will show queries to the disk subsystem you mentioned - but this hypothesis should be tested on a test bench.

**Comment by jingb** [comment]
@denisgolius thanks 
and do you think it it a good design that mount the big directory into remote storage and keep the small directory in local disk. 
or any case or suggestion that i could refer about hot/cold data separating

**Comment by valyala** [comment]
VictoriaMetrics stores recently ingested data into `data/small` subdirectory at the directory pointed by `-storageDataPath`. Then the ingested data is [merged](https://docs.victoriametrics.com/#storage) in background from smaller parts into bigger parts. When the size of the output part starts exceeding the maximum allowed part size for storing in `data/small` directory, then the output part is stored in the `data/big` directory. The maximum allowed part soze in `small` dorectory depends o  the RAM size available to VictoriaMetrics (or to each vmstorage node in cluster version of VictoriaMetrics) at the host it runs. This is needed to increase the probability that all the data from `small` directory is cached by the operating system in page cache (e.g. in RAM), in order to decrrase disk read IO during queries over recently ingested data, and to improve performance for such queries.

As ypu can see, this algorithm gradually moves previously ingested data (aka historical data) from `small` to `big` directory. So, as @denisgolius wrote above, you need to query historical data in order to read this data from `big` directory. The https://github.com/VictoriaMetrics/prometheus-benchmark doesnt contain queries, which could 
read historical data - these queries are located at https://github.com/VictoriaMetrics/prometheus-benchmark/blob/main/chart/files/alerts.yaml . You can either modify these queries by replacing short lookbehind windows in square braces with bigger ones, in orser to trigger reading historical data from `big` directory, or to add some kind of SLI/SLO-like queries, which usually perform calculations over data on long lookbehind windows. Such queries can be obtained from https://github.com/slok/sloth 

> do you think it it a good design that mount the big directory into remote storage and keep the small directory in local disk.

This idea is great! Actually the initial design decision to separate data into `small` and `big` directories assumes that these directories can be mounted to fast yet small (e.g. SSD) and slow yet large (e.g. HDD) persistent storage layers.

**Comment by jiekun** [comment]
Close as answered.
