### ISSUE TITLE
vmalert: timestamp in ALERTS time series and actual execution timestamps are different

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5049]
### Describe the bug

vmalert performs periodical evaluation of rules. On each interval, vmalert executes rules with consistently incremented timestamps. However, when the actual query is sent, the timestamp could be different to the one logged by vmalert. Or the timestamp associated with ALERTS time series persisted back to the datasource if alert has been triggered.

The source of discrepancy is `datasource` package which can adjust the timestamp under following conditions:
1. if `-datasource.queryTimeAlignment=true` (default is true) is set
2. if `-datasource.lookback` is set
3. if `eval_offset` is set

### To Reproduce

Try running a vmalert which would trigger an alert. And then compare the timestamp of the generated ALERTS and the timestamp when raw expression crossed the alert threshold. It should be especially visible for groups with evaluation_interval of couple of minutes, because this interval is used to truncate the timestamps in datasource package.

Possible solutions:
1. Do timestamp adjustment before passing it to datasource
2. Do not adjust timestamps for alerting rules. Recording rules should keep the adjustment, as it produces samples consistent with raw query results in Grafana - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1257

Please note, that disabling alignment completely may result into discrepancy between multiple replicas of vmalert since used for interval `ticker` doesn't guarantee such alignment. And, as result, because of ticker `evalTS` can be different for vmalert replicas.

### Version

Any

**Comment by hagen1778** [comment]
@Haleygo wanna take a look?

**Comment by artli** [comment]
To expand on the last point: if `-datasource.queryTimeAlignment` is turned off and multiple vmalert instances are used, evalTS might get initialized slightly differently on different vmalert instances because it is just set to `time.Now()` after a sleep: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/71a17dfcbec26bf5c4fd2da459fffc70cea365b7/app/vmalert/group.go#L306. This might lead to discrepancies between different vmalert instances in some edge cases.

Given that the sleep before initializing `evalTS` has a deterministic target (last `interval` boundary plus a deterministically determined `randSleep` delay), evalTS could simply be set to that target, which will make sure it's aligned between instances.

**Comment by Haleygo** [comment]
Hello! @artli 
>if -datasource.queryTimeAlignment is turned off and multiple vmalert instances are used, evalTS might get initialized slightly differently on different vmalert instances

Actually it won't be a problem, since we already unify the group start timepoint when calculating delay 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/34a9d1f818af48a4d5bb4dcde4148e390a0c2d4a/app/vmalert/group.go#L407-L428

You can see the effect here[consider each test case as an independent vmalert instance], we always try to start the real group evaluation using the nearest timestamp which aligned with interval[in the test is 5min] then plus randSleep[calculate by groupID, in the test is 30s]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/34a9d1f818af48a4d5bb4dcde4148e390a0c2d4a/app/vmalert/group_test.go#L551-L555

**Comment by artli** [comment]
> since we already unify the group start timepoint when calculating delay
Yep! That's what I mean by "the sleep before initializing evalTS has a deterministic target". However, `evalTS` doesn't get set to that target; instead it's set to `time.Now()` after waking up from the sleep, which is non-deterministic (and which the above test doesn't cover).

In practice this additional non-determinism is probably usually quite small but it could become larger if e.g. the CPU is loaded. And even a small difference can lead to different results between vmalert instances: e.g. if `randSleep` is calculated to be 4.99 seconds and two vmalerts wake up at times 4.995 and 5.005 after an `interval` boundary, they will initialize `evalTS` differently and might see different results e.g. if `-dedup.minScrapeInterval=5s` or simply if there is some sample that happens to have a timestamp between 4.995 and 5.005.

**Comment by Haleygo** [comment]
> > since we already unify the group start timepoint when calculating delay
> 
> Yep! That's what I mean by "the sleep before initializing evalTS has a deterministic target". However, `evalTS` doesn't get set to that target; instead it's set to `time.Now()` after waking up from the sleep, which is non-deterministic (and which the above test doesn't cover).
> 
> In practice this additional non-determinism is probably usually quite small but it could become larger if e.g. the CPU is loaded. And even a small difference can lead to different results between vmalert instances: e.g. if `randSleep` is calculated to be 4.99 seconds and two vmalerts wake up at times 4.995 and 5.005 after an `interval` boundary, they will initialize `evalTS` differently and might see different results e.g. if `-dedup.minScrapeInterval=5s` or simply if there is some sample that happens to have a timestamp between 4.995 and 5.005.

Thanks for the explanation!
Then I think it's inevitable when there are multiple vmalert instances. Even if we manage to force their query timestamp to be exact same, when multiple query requests reach to vmcluster at different time[due to network or concurrency limit of vmselect], there are chances that vmcluster return partial or old/updated response to some of them, which lead to the different results eventually. 
But even for the current code, the chance of this problem is very small, and I suppose all the results can be seen as a right one.

**Comment by artli** [comment]
> when multiple query requests reach to vmcluster at different time[due to network or concurrency limit of vmselect], there are chances that vmcluster return partial or old/updated response to some of them

But in that case we would consider that cluster degraded, right? Of course, if the cluster is returning partial responses due to some nodes being down, then we should not be surprised to see weird results in anything that queries it--that's indeed unavoidable. However, during normal operation (of a properly redundant cluster) we would expect to see exactly identical results when we use the same timestamp, but with the current implementation the timestamps are not the same, so the results are pretty much guaranteed to be different in a small percentage of cases.

**Comment by Haleygo** [comment]
>But in that case we would consider that cluster degraded, right?

Fair points! Sorry for mixing up two problems.

@artli Please check https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5066/commits/50dec583a6c9652982ad0473251236167768c491, that should make sure the timestamp of group's first and following evaluation timestamp be the same on vmalert side.

**Comment by artli** [comment]
Thanks a lot, I think that's what I had in mind!

**Comment by valyala** [comment]
The issue should be fixed since the `vmalert` release [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html) with the help of `eval_alignment` option at [group level](https://docs.victoriametrics.com/vmalert.html#groups). Closing the issue then.
