### ISSUE TITLE
applying `extra_filters` might hit `maxUniqueTimeSeries` limit for label_values, labels, series API requests

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5055]
### Is your feature request related to a problem? Please describe

Requests for /api/v1/label/name/values and other APIs are processed by different code path if `extra_filters` is set.

Without `extra_filters`, VM simply selects first N results from index search. `maxUniqueSeries` limit isn't involved.

With `extra_filters` VM performs metricIDs search first and uses `maxUniqueSeries` limit during the search.

The problem is that user can have `/api/v1/label/name/values` API call executed without any issues, but once they add `extra_filters` the request can breach the complexity limit. This is controversial, as it is expected that specifying additional filters always reduces the complexity of the query.

### Describe the solution you'd like

 It'd be great to implement different approach. 

1) At first execute original request with given limit. 
2) Construct new filter that include found label value plus extra_filters
3) make a search for the first metricID with given filter. 
4) If previous filter returns at least 1 metricID keep original result. Otherwise drop it and go to the next.

 It makes sense only if limit LTE 1000.

**Comment by valyala** [comment]
FYI, the commit 5d66ee88bdb2bbab6419a2854a130c8838998923 removes checking for the `-search.maxUniqueTimeseries` limit at [`/api/v1/labels`](https://docs.victoriametrics.com/url-examples/#apiv1labels) and [`/api/v1/label/.../values`](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) handlers. This should prevent from returning `the number of matching timeseries exceeds ...` errors in default configuration for VictoriaMetrics. This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics doesn't use `-search.maxUniqueTimeseries` command-line flag value when processing requests to `/api/v1/labels` and `/api/v1/label/.../values`, starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as resolved.

**Comment by f41gh7** [comment]
I have doubts about current design for `extra_label` and `extra_filters` support for `/api/v1/series`, `/api/v1/labels` and `/api/v1/label/values` apis.

 By default, those API uses an index for searching results. It allows to perform fast and efficient search operations.

 Current index has two versions:
1) single node `TAG:VALUE:metric_ids`
2) cluster node `TENANT_ID:TAG:VALUE:metric_ids`.

`extra_filters` cannot be used with those indexes. Since it has to perform a join operation.

It's possible to use two different join strategies:
1) join metricName for matched metrics_id. 
2) join metrics_ids for matched `extra_filters`.

 First approach has inconsistent performance. It may work really fast for some cases and incredibly slow for others. Good case for it, when you have a small churn rate at match patterns for search requests. E.g. search for `/api/v1/label/low_churn_metric/values with `extra_filters={env="prod"}`.

Second approach has consistently slow performance and it depends on the number of filters and matched metric_ids. Other problem with it, that it's not scalable. With more than 100M active series request will be constantly timeout. 


 But what's reason behind using this api enchantment? Mostly, it's a replacement for current tenant implementation. And instead of tenants, it's possible to use labels as a tenant id.


 It looks, that the efficient way to implement that - provide a custom index creation feature for tags. It allows to perform fast search operation with low resource usage.

E.g. -customTagIndexLabels="env,team".

 It must create following indexes for tags:
`env=value:team:value:tag:value:metric_ids`
`env=value:tag:value:metric_ids`
`team:value:tag:value:metric_ids`

It makes request with extra_labels - `{env="prod", team="dev"}` or {env="dev"} fast and reliable. But it increases disk usage, storage complexity and cpu usage.

**Comment by valyala** [comment]
FY, the [v1.97.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.3) takes into account `-search.maxUniqueTimeseries` when requesting `/api/v1/labels` and `/api/v1/label/.../values` as it was in `v1.97.1`.

**Comment by valyala** [comment]
FYI, commits fab02faa3f7c80d76bb28dc118fc7398abcfe544 and 0b7a23a91d5f29535c3c485f0c1d92f87ae91fef add `-search.ignoreExtraFiltersAtLabelsAPI` command-line flag, which can be set in order to ignore `match[]`, `extra_filters[]` and `extra_label` query args at `/api/v1/labels` and `/api/v1/label/.../values`. This allows reducing CPU usage and disk read IO usage when the `match[]`, `extra_filters[]` or `extra_label` match too many time series. The downside is that additional labels and label values can be returned from the the APIs, which do not match the ignored filters. See [these docs](https://docs.victoriametrics.com/#resource-usage-limits) for more details.

These commits will be included in the next release.

**Comment by valyala** [comment]
There was a bug in `-search.ignoreExtraFiltersAtLabelsAPI` implementation, which broke requests to `/api/v1/series`. This bug has been fixed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/271173294407937cae4452464348672ff5699ae5 .

**Comment by valyala** [comment]
Additional information, which could be useful for users, who encounter slow queries to [`/api/v1/labels`](https://docs.victoriametrics.com/url-examples/#apiv1labels) and [`/api/v1/label_values`](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) when loading Grafana dashboards with the defined `Label values` [template variables](https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/): make sure to always specify the `Metric` field when editing the template variable. This field must contain a name of metric, which contains all the label values, which should be shown by the given template variable. If this field is left empty, then Grafana sends too broad request to [`/api/v1/label/.../values`](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) at VictoriaMetrics, which needs to scan labels for all the metrics instead of scanning labels only for the requested metric.

**Comment by valyala** [comment]
FYI, the commits 2d31fd7855bf304175348b502059eaf7b606af95 and d1d2771bee6e4d8807322ec4ad77fb95cd4ade36 improve performance for `/api/v1/labels` and `/api/v1/label/.../values` calls when `match[]` filter contains metric name. For example, `/api/v1/label/instance/values?match=up` should be executed must faster now. These commits will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
FYI, the performance of `/api/v1/labels` and `/api/v1/label/.../values` APIs has been improved significantly starting from [v1.100.0 release](https://docs.victoriametrics.com/changelog/) when the `match[]` filter contains metric name. For example, `/api/v1/label/instance/values?match[]=up` now works much faster when VictoriaMetrics contains big number of time series. Such queries are usually used by Grafana during auto-suggestion and template variable population at dashboards as described in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5055#issuecomment-1980859446), so VictoriaMetrics should process `/api/v1/labels` and `/api/v1/label/.../values` requests much faster starting from `v1.100.0`.
