### ISSUE TITLE
Alert/metric to check upon days of metrics stored in the db

### ISSUE THREAD

**Issue by ivankovnatsky** [VictoriaMetrics/VictoriaMetrics#5081]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

This is a follow up of this: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5062.  We thought about setting an alert that would tell how many days (of metrics) we have stored in our VictoriaMetrics db.  I've started to play around grafana sql-fu, but figured if there might be a common victoria-way to asses that.  We have 30 days retention and I though if I could count to 30 running a query for 30d range that would mean we're healthy.

We're running spots for victoria, thus short interruptions is fine, meaning that alerting on "No Data" or "Timeout" is not an option. So we thought about setting one alert to showcase that. We have a VM dashboard setup, but the alert would be really great.

If there's some other logic we could use instead, and that will help us understand if Victoria is healthy, I mean not the exactly 30 days of metrics, that would also be really great.

Can you please advice?

Thanks,
Ivan.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@ivankovnatsky For an issue like the one fixed in [v1.93.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.1) it's near to impossible to define a trustworthy alert based on length of series(e.g. checking for presence over 30d).
This is because this issue deleted only small subset of metrics for some users, but more metrics for others. So there is no stable way to check for this to ensure this does not happen.

A better option might be to monitor number of restarts. VictoriaMetrics always exists with non-zero status code in case data corruption was detected and prints a `FATAL` log message with an explanation of what is corrupted.
In case you're using spot instances you can monitor for more than one restart over time or to use alerts based on logs to create an alert in case `FATAL` log line was printed by VictoriaMetrics.

**Comment by ivankovnatsky** [comment]
@zekker6 got it, thanks!
