### ISSUE TITLE
Does retentionFilter apply during a vmctl import

### ISSUE THREAD

**Issue by daenney** [VictoriaMetrics/VictoriaMetrics#5086]
### Is your question request related to a specific component?

VictoriaMetrics and `vmctl prometheus`

### Describe the question in detail

I have a VictoriaMetrics Enterprise configured with the following `retentionFilter` and `retentionPeriod`:

```
-retentionFilter='{__name__=~"sensors_.+"}:10y' -retentionPeriod=1y
```

I'm trying to import a snapshot of Prometheus metrics, which has metrics older than 1 year. However, that results in the following getting logged:

```
vmctl-prod prometheus --prom-snapshot=/data/prometheus/snapshots/20230928T134212Z-145f2547d94005b2 --prom-filter-label='__name__' --prom-filter-label-value="sensors_.+"
```

```
warn        VictoriaMetrics/lib/storage/storage.go:1888        warn occurred during rows addition: cannot insert row with too small timestamp 1633076807472 outside the retention; minimum allowed timestamp is 1664378870000; probably you need updating -retentionPeriod command-line flag; metricName: sensors_<redacted>        
```

It seems that during an import like this, only the `retentionPeriod` applies?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @daenney ! `vmctl` uses `/api/v1/import` when importing data to storage. So when you define `-retentionPeriod` flag it will be applied to all ingested data to the storage. So that is why you see this warning message. 
As a workaround, you can define `-retentionPeriod` to `10y` and retention filter `-retentionFilter='{__name__!~"sensors_.+"}:1y' and this should work for your situation.

**Comment by daenney** [comment]
I see. Thank you so much for the quick response and explanation. I'll invert it then and give that a go!

**Comment by daenney** [comment]
I assume that once I'm done with the import, I can revert it again? So having the default retention period of 1yr?

**Comment by daenney** [comment]
This doesn't quite seem like it works the way I expected.

If I configure the cluster with:
```        -retentionFilter='{__name__!~"sensors_.+"}:14w' \
-retentionPeriod=10y \
```

Then I can:
* Import all metrics starting with `sensors_` from way back
* Query all the way back, like 2 years for example

However, if I then change the configuration to:
```
-retentionFilter='{__name__=~"sensors_.+"}:10y' \
-retentionPeriod=14w \
```

Now, I can no longer query for the `sensors_*` metrics all the way back. I assume that also means they'll get deleted. But I don't understand why. The two configurations would appear to be identical. As far as I understand from the docs, the `retentionFilter` should apply and only if it doesn't match, then does it fall back to `retentionPeriod`.

**Comment by dmitryk-dk** [comment]
Hi @daenney ! We may have a bug with retentionFilters and retentionPeriod. I will check it and come back with more information.

**Comment by dmitryk-dk** [comment]
Hi @daenney ! I discussed your question with teammates and checked the code. A retention period with a lower value will always delete data older than the defined period. The data will be eventually deleted during [background merge](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282). It happens because deleting data via `retentioPeriod` and filter data via `retentionFilter` are separate processes.
In that case retention filter must be determined within the specified `retentionFilter`. I think we should clarify this in our documentation that the retention filter must be within the specified retention period.

**Comment by daenney** [comment]
Got it, that indeed explains the behaviour I was seeing. Then I also know how to set things up on my side to get the expected behaviour.

Thanks a lot for the help!
