### ISSUE TITLE
Cluster vmselect returns empty results

### ISSUE THREAD

**Issue by zunkree** [VictoriaMetrics/VictoriaMetrics#51]
At the beginning of tests of cluster version there was no issue but after some time vmselect returns empty response for most requests from grafana. There is no errors in vmselect and vmstorage logs. Will provide any additional info to help debug that issue.

**Comment by valyala** [comment]
This may be related to the following issues:
1) `-storageNode` args passed to `vmselect` nodes don't match `-storageNode` args passed to `vminsert` nodes. In this case a part of data may be written to `vmstorage` nodes, which are invisible to `vmselect`, because these nodes are absent in `-storageNode` args.
 Make sure that `-storageNode` args are identical among `vmselect` and `vminsert` nodes: navigate to `/metrics` page for each `vmselect` and `vminsert` node and verify that they have identical `flag{name="storageNode"...}` lines.

2) Certain `vmstorage` nodes are unhealthy. Check `vm_partial_*` metrics on the `/metrics` page for `vmselect` nodes. If these metrics are constantly increasing when refreshing Grafana dashboards with graphs built from VictoriaMetrics datasource, then this means that `vmselect` cannot access certain `vmstorage` nodes, so `vmselect` returns partial results. This may be related to incorrect addresses passed to `-storageNode`. Check for `vm_tcpdialer_errors_total` metric in order to determine which addresses don't work.

3) Incorrect response caching interference with the back-filled data. If you are writing data points to VictoriaMetrics with timestamps in the past (more than 5 minutes ago) and concurrently querying VictoriaMetrics for these data points, then VictoriaMetrics could cache data gaps in the past and skip the data points added later instead of these gaps. Pass `nocache=true` query arg to `/api/v1/query_range` API in order to disable response caching for the particular request. If the response with disabled caching returns all the data, this points to bad response caching interference with data back-filling.

@zunkree , could you check each case outlined above and return with details for your case?

**Comment by valyala** [comment]
@zunkree , are there any updates on this issue?

**Comment by valyala** [comment]
This could be related to [the issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/52#issuecomment-499704316) with improper filtering on `__name__`. It has been fixed starting from [v1.18.11](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by tenmozes** [comment]
@zunkree is it still relevant?

**Comment by zunkree** [comment]
Sorry for delay, no it is not relevant any more. Issue could be closed.

**Comment by tenmozes** [comment]
cool, thanks
