### ISSUE TITLE
Better understanding the implication of many unique log fields (aka columns) in a log entry

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5118]
### Is your question request related to a specific component?

Victorialogs

### Describe the question in detail

From what I can see, the `-insert.maxFieldsPerLine` flag has been added to address issue #4762 although I would like to get a better understanding of this at a lower level.

With Elasticsearch, the maximum number of unique fields is an **index level** setting which is set to 1000 by default.  It can be updated via the `index.mapping.total_fields.limit` configuration parameter at runtime (see [docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/mapping-settings-limit.html)).    Depending on the frequency new indices are generated (hourly, daily, weekly, by size, num docs, etc) you might manage to remain under the default limit, but I've had many cases where I've had to increase it permanently via a [component](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/indices-component-template.html) or [index template](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/indices-put-template.html).  

In some cases, if the number of unique fields per index is excessive, it's advised to attempt (if possible) to place them all underneath a top-level field and map it as a [flattened field](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/flattened.html).  This types of field does have some disadvantages although the notable benefit is that the only the top level field affects the total count of unique fields as it's stored and considered as a single object, regardless of the number of nested fields under it.

Now to come back to Victorialogs, does this new flag limit only the number of fields per each ingested line, or is it also applicable at the block level or even at the stream level?   My main concern here is if there could be any long term impacts of having a considerable number of new field names generated on a daily basis in a given stream.   I would very much appreciate if you could provide some additional details for this so that I can better understand the comparison with Elasticsearch.   

Thanks for your help

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by valyala** [comment]
The `-insert.maxFieldsPerLine` command-line allows limiting the number of fields per each log line. It is set to 1000 by default in VictoriaLogs [v0.4.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.4.1-victorialogs). It doesn't limit the number of fields per block in a [stream](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#stream-fields). E.g. distinct log lines in a stream block may have distinct set of fields, and the number of unique fields across log lines in a single stream block may exceed the value passed to `-insert.maxFieldsPerLine` command-line flag.

The maximum limit on the number of unique fields in stream block is [hard-coded to 10000](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/590bd50df48edcf2f6f17295fafee1d17856e5d2/lib/logstorage/consts.go#L17) right now. This limit is hard-coded, because a single block in a stream is limited in size [by 4Mb](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/590bd50df48edcf2f6f17295fafee1d17856e5d2/lib/logstorage/consts.go#L11). This effectively limits the number of log lines a single block can contain.

For example, if an average log line size equals to 1Kb, then the block may contain up to `4Mb/1Kb=4000` log lines. It is very unlikely that these 4K log lines, which belong to a single [stream](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#stream-fields), will contain more than 10K fields with unique names.

If you hit this limit, then something is wrong with the data ingestion pipeline as described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4762#issuecomment-1743477461), and this must be fixed in order to improve efficiency of VictoriaLogs for the given workload.

**Comment by valyala** [comment]
Closing the question as answered
