### ISSUE TITLE
Is it possible to limit CPU per query to more fairly process requests?

### ISSUE THREAD

**Issue by Bruno-DaSilva** [VictoriaMetrics/VictoriaMetrics#5139]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Right now we run a couple 5-cpu vmselect pods that query 5 vmstorage nodes.

We're noticing that if we get a particularly expensive query incoming, it will saturate all 5 cores of the vmselect it is executed on.

That means that if another query comes in, it must fight for resources from the expensive query.

Is there a way to limit the number of cpus that a single query can consume within a vmselect node? For example, limit queries to use 2 cpus max, so that other queries can execute concurrently without contending for resources?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Is there a way to limit the number of cpus that a single query can consume within a vmselect node? For example, limit queries to use 2 cpus max, so that other queries can execute concurrently without contending for resources?

There is no way for limiting CPU usage per query on vmselect. But this usually isn't needed because query processing involves a lot of IO delays:
1. vmselect needs to wait for vmstorage to return requested data (io intensive)
2. vmselect needs to decompress received data (cpu intensive)
3. vmselect needs to process received data (cpu intensive)
4. vmselect needs to respond to client (io intensive)

When thread becomes idle on IO operation, the CPU time can be used by another thread.
Limiting CPU per query would also mean that both queries will be delayed. Or when there is only one query occupying resources, the processing speed will be lower because of limits. So the overall user experience will be worse.

I'd recommend scaling read load by adding more vmselects instead. Although, if this is a problem of untrusted clients (which can run ridiculously expensive queries affecting production), I'd recommend running a dedicated set of vmselects specifically for them and use vmauth for routing requests to specified vmselects.

**Comment by Bruno-DaSilva** [comment]
@hagen1778 just read through recent changelogs and saw this added as part of v1.95.0
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5195/files#diff-22edd94c512ef8044f9b703e982cb6e74928f8e4479afb5dcc7c1c16a2b7884b

I assume this could likely be used to limit cpu (but i understand you dont recommend it above). 
We are moving to use a separate vmselect for our alert queries as it has higher availability requirements, and a separate vmselect for "untrusted clients" (where its less of a big deal if vmselect restarts/has issues).

You're welcome to close this issue!

**Comment by Bruno-DaSilva** [comment]
Understood. We likely won't use it. Thanks!
