### ISSUE TITLE
vmui: how to connect null values

### ISSUE THREAD

**Issue by mson2203** [VictoriaMetrics/VictoriaMetrics#5152]
### Is your question request related to a specific component?

vmui

### Describe the question in detail

My data on VictoriaMetrics:
metric_name 504 1696949858000   # 2023-10-10 09:57PM
metric_name 1000 1696951658000 # 2023-10-10 10:27PM
metric_name 800 1696952858000   # 2023-10-10 10:47PM
metric_name 637 1696953458000   # 2023-10-10 10:57PM

I have queried these data and they are displayed in vmui as below screenshot. Seems it tries to locate the closest sample on the left in chart.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/76061250/f7df0dbb-977a-483d-9e12-ddb88ccb88dd)

But I want to create a chart that connects four points in my data only (like black line below). How do I achieve this?
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/76061250/389df883-1c83-404d-959b-d2e02d82f8dc)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by mson2203** [comment]
Does anyone take a look on my question?
Thank you.

**Comment by mson2203** [comment]
Any solution/workaround for my issue, please share me.
Thanks.

**Comment by hagen1778** [comment]
Hi @mson2203! Sorry, I didn't see this. Try pinging someone from VM team instead. Otherwise, we don't receive notifications :)

> But I want to create a chart that connects four points in my data only (like black line below). How do I achieve this?

vmui will connect datapoints only if they're consistently distributed on the graph. It takes the median distance between first 20 data points in order to determine the time range on which datapoints need to be connected, and when they need to be disconnected. See more details here https://docs.victoriametrics.com/keyConcepts.html#range-query

You can achieve that in Grafana, though. See example below on testing data:
1. Plotting data points as is:
<img width="871" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/24111eb3-454c-4de1-8607-3edaf7bee9de">

2. Plotting data points with "Connect always" option:
<img width="1777" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/e3dde75c-07ba-43de-b13a-fdabdd7ad6b8">


@YuriKravetc do you think we should add similar option to vmui?

**Comment by valyala** [comment]
[vmui](https://docs.victoriametrics.com/#vmui) provides an option for filling gaps on graphs starting from [v1.99.0](https://docs.victoriametrics.com/changelog/). Closing the feature request as done.
