### ISSUE TITLE
Allow maxSearchQuerySize to be configurable

### ISSUE THREAD

**Issue by KyleJHarper** [VictoriaMetrics/VictoriaMetrics#5154]
### Is your feature request related to a problem? Please describe

When adjusting the -search.maxQueryLen, we discovered that there is a hard-coded limit of 1024*1024 for maxSearchQuerySize packets, effectively creating an upper limit.  While not ideal, there are cases where we need to send a laundry-list of things (such as host names) which come from another source and/or tenant and therefore cannot leverage a join.

### Describe the solution you'd like

Allow maxSearchQuerySize to be adjustable as a runtime option/config option.

**Comment by tenmozes** [comment]
There is a hardcoded limit on vmselectapi level 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/lib/vmselectapi/server.go#L368

It results into errors like that 

```
cannot process vmselect conn address:port: cannot process vmselect request: cannot execute "search_v7": cannot read searchQuery: too big data size: 1262131; it mustn't exceed 1048576 bytes
```

**Comment by hagen1778** [comment]
Probably, we should increase this limit to 5MB.

**Comment by valyala** [comment]
The constant at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8b42a1733cdcaf6aa7ad20ccd84d9204b7f87ad3/lib/vmselectapi/server.go#L368 limits the maximum size of "search query" request, which can be sent from `vmselect` to `vmstorage`. This limit is checked at `vmstorage` side, while the `-search.maxQueryLen` command-line flag is set and checked at `vmselect`. That's why the `-search.maxQueryLen` cannot be used for overcoming the limit at `vmstorage` side.

The purpose of the hardcoded limit at `vmstorage` side is to prevent from excess memory usage when unexpectedly long queries are sent from `vmselect`. Currently this limit is hard-coded to 1MB. This is pretty big value, which should cover most real-world queries. It has been appeared that the limit can be exceeded in some rare cases like this one. There are the following options exist in order to allow accepting bigger "search query" requests at `vmstorage` side:

1. To expose an additional command-line flag at `vmstorage` side for limiting the maximum length of "search query" request from `vmselect`. I don't like this solution, since it complicates the configuration - you need to set both `-search.maxQueryLen` at `vmselect` and an additional command-line flag at `vmstorage`.
2. To remove the limit at `vmstorage` side. The maximum "search query" request size is limited at `vmselect` by the value provided via `-search.maxQueryLen` command-line flag. So there is no much sense in limiting the "search query" request size at `vmstorage` in general case. The only case where this limit may be useful is to protect `vmstorage` from improperly configured or maliciously configured `vmselect`.
3. To increase the hard-coded limit at `vmstorage` from 1MB to 5MB as @hagen1778 proposed above. I hope that 5MB limit will never be reached by real-world queries, so it should prevent from improperly or maliciously configured `vmselect`.

So let's just increase the hard-coded limit at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8b42a1733cdcaf6aa7ad20ccd84d9204b7f87ad3/lib/vmselectapi/server.go#L368 to 5MB and see how it will go.

**Comment by valyala** [comment]
FYI, [VictoriaMetrics v1.93.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6) increases the hard-coded limit on the size of RPC request, which can be accepted by `vmstorage`, from 1MB to 5MB.

**Comment by valyala** [comment]
Closing the issue as resolved

**Comment by valyala** [comment]
FYI, the limit on the maximum `search query` RPC, which can be accepted by `vmstorage`, has been increased from 1MB to 5MB starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).
