### ISSUE TITLE
Loss of data when using the VictoriaMetrics

### ISSUE THREAD

**Issue by Williamcs1400** [VictoriaMetrics/VictoriaMetrics#5223]
### Is your question request related to a specific component?

VictoriaMetrics - use of the function `running_sum(increase(my_metric)).`

### Describe the question in detail

Greetings!

I'm trying to capture all metrics calculated from a Java Spring application (counters) over time and keeping the data even with restarts of the monitored application, that is, continuing where I left off.

I was using Prometheus for this type of monitoring, but it provided very wrong data. I saw on forums that using VictoriaMetrics would be more accurate, in fact! But there are still errors, it loses data as we restart the spring application.

As in the image below. Total number is correct, but success (sucesso) and failure (falha) numbers are incorrect - success should be 2 and failure 6.
![Captura de tela 2023-10-21 112526](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39714540/1a98f6fc-93ce-4601-bb9b-aaf0686de863)

Accuracy was improved by following the forum tips: [https://github.com/VictoriaMetrics/VictoriaMetrics/issues/80](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/80). However, it still has errors.

My question is whether the function to be used for accounting is really the `running_sum(increase(my_metric[$__interval]))`.
And if there is a way to reduce the amount of error or even reset it to zero.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @Williamcs1400.

> My question is whether the function to be used for accounting is really the running_sum(increase(my_metric[$__interval])).

It depends on what you want to achieve.
If you use this query for [instant query API](https://docs.victoriametrics.com/keyConcepts.html#instant-query) (like on attached picture), then using `$__interval` looks weird, because it will calculate the increase in the metric value over some very small period of time, depending on the one specified in the time picker. See [the variable description](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval). This query is suitable for [range query](https://docs.victoriametrics.com/keyConcepts.html#range-query).

For using in instant query this is more suitable:

```
increase(my_metric[$__range])
```

This query calculates the increase in the metric over the period selected in the time picker.

> And if there is a way to reduce the amount of error or even reset it to zero.

From your text it is not quite clear what errors we are talking about, I would like more clear examples. For example, maybe you take for errors the specifics of the `increase` algorithm, you can try to replace it with `increase_pure`.

**Comment by Williamcs1400** [comment]
Hey, @Amper. Thank you for your attention!

I applied the suggestion to use the ` $__range` instead of `$__interval` and also `increase_pure` instead of `increase `. The results remain the same.

**Describing the problem better:**
I'm running automated tests in a java spring application that is being monitored by micrometer using counters.
Each test cycle, it accesses this endpoint (client_token) four times in the image below. With one success (sucesso) and three failure (falha). 

- In other words, from a round of automated tests we have:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39714540/937eec72-68ac-450b-bf3e-502df90d49b6)

- After running the tests, I reset the Java application that is being monitored e and run the automates tests again. And I get the result in the image below, the total and failure numbers are correct, but the success number should be 2 but remains 1.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39714540/82d8fcfc-2cce-4dbe-80eb-33589f0b8b95)

The query use in grafana for the total number: `running_sum(increase(OauthAPI_total{method="CLIENT_AUTH"}[$__interval]))`
For success number: `running_sum(increase(OauthAPI_SUCCESS_total{method="CLIENT_AUTH"}[$__interval]))`
And for failure number: `running_sum(increase(OauthAPI_ERROR_total{method="CLIENT_AUTH"}[$__interval]))`

I would like to understand and correct why this count is wrong when I restart the monitored application.

**Comment by Amper** [comment]
@Williamcs1400 could you provide [raw data](https://docs.victoriametrics.com/url-examples.html#apiv1export) for these metrics for an interval covering two rounds of running tests?

**Comment by Williamcs1400** [comment]
Hi @Amper!
part1.json - Automated test like this when I uploaded the server
part2.json - I restarted and ran the automated tests

[part1.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/13117215/part1.json)
[part2.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/13117216/part2.json)

**Comment by Amper** [comment]
@Williamcs1400, it's query_range results, not [exported raw data](https://docs.victoriametrics.com/url-examples.html#apiv1export).

**Comment by Williamcs1400** [comment]
I used the reference query: `curl http://localhost:8428/api/v1/export -d 'match[]=vm_http_request_errors_total' > filename.json`.
Just applying my metric: `curl http://localhost:8428/api/v1/export -d "match[]=OauthAPI_SUCCESS_total" > part1.json`

Isn't this the query I have to use?

**Comment by Amper** [comment]
Hey, @Williamcs1400.

I think that these files were corrupted with some your software after export, because export create jsonl-files with one full entry in each line, but this files  was formatted as regular json files and import doesn't work with them.
But i managed to fix them and import.

The problem is illustrated in the graph:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/eb2723bb-0b20-4606-8471-6f6bfe6b9235)

Such a graph looks like an unchanged value for increase function - it will be counted once.
To give you an example, this is what the graphs look like for most of the other timeseries:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/0806c876-7513-47c6-b73d-625033b0bca6)

These timeseries will be processed correctly.

I think, the problem is that for some series, a zero value is not being written, which could be handled as a counter reset.
