### ISSUE TITLE
can i send metrics from single node victoriametrics to a thanos/victoriametrics cluster?

### ISSUE THREAD

**Issue by timam** [VictoriaMetrics/VictoriaMetrics#5245]
### Is your question request related to a specific component?

single node victoria metrics

### Describe the question in detail

in prometheus we can send metrics with remote write to a cluster.
i wanted to know if i deploy a single node victoriametrics, will i be able to send those metrics to remote cluster like thanos/victoriametrics or even a prometheus ?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @timam 

VictoriaMetrics Single does not support remote-writing ingested metrics.
In order to send metrics to both VM Single and Thanos/VictoriaMetircs cluster you will need to use [vmagent](https://docs.victoriametrics.com/vmagent.html) to scrape metrics(or receive via supported push protocols) and fan-out metrics to multiple remote-write endpoints.
