### ISSUE TITLE
Support "Idempotency-Key" or "X-Idempotency-Key" headers in query api

### ISSUE THREAD

**Issue by yuweizzz** [VictoriaMetrics/VictoriaMetrics#5276]
### Describe the question in detail

it's possibly that VictoriaMetrics support to those headers in query api?

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @yuweizzz!
Could you please elaborate more on how Idempotency can be applied to read queries?

**Comment by yuweizzz** [comment]
We use http.Client to send query request to VM, but sometimes get 'connect reset by peer',  we try to add "Idempotency-Key" header in request so http.Client can replay request,  what i thought is than maybe VM can handle those header?

**Comment by hagen1778** [comment]
@yuweizzz unfortunately I fail to understand how this should work. If you received 'connection reset by peer' it means connection has already been closed and there is nothing to do except of re-establishing a new one. I don't understand how idempotency header will prevent from abrupt connection termination.

@zekker6 @f41gh7 do you know know something about this?

**Comment by zekker6** [comment]
I think this is related to the following comment: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4139#issuecomment-1591853722

The issue there was that when using keepalive and inconsistent timeout configurations at load balancer and in Go http client there was a chance that connection which is treated as "alive" for the application was already closed by LB. In order to solve this there is a "hack" in http client which automatically retries requests which contain `X-Idempotency-Key` when this error occurs.

From my point of view, it is better to figure out inconsistency between configurations and fix it instead of adding `X-Idempotency-Key` and relying on this "hacky" solution.

**Comment by yuweizzz** [comment]
@zekker6 I think this is a better way,  and I wannt to know does VM provides ways to set connect timeout ?

**Comment by zekker6** [comment]
@yuweizzz You will need to adjust the following flags:
```
  -http.idleConnTimeout duration
     Timeout for incoming idle http connections (default 1m0s)
  -http.connTimeout duration
     Incoming http connections are closed after the configured timeout. This may help to spread the incoming load among a cluster of services behind a load balancer. Please note that the real timeout may be bigger by up to 10% as a protection against the thundering herd problem (default 2m0s)
```

**Comment by yuweizzz** [comment]
@zekker6 @hagen1778 thank you!
