### ISSUE TITLE
Table view does not sort by time correctly

### ISSUE THREAD

**Issue by rul-hydro** [VictoriaMetrics/VictoriaMetrics#5300]
### Describe the bug

When viewing log entries from more than one month in VictoriaLogs, the table view will sort the `time` column by its alphanumerical value, so Nov<Oct.

### To Reproduce

- Pick a log query that will return entries from October and November
- Switch to Table view

The table will have the latest entries from October first, then earlier entries from October, and then entries from November

### Version

victoria-logs-20231004-080357-tags-v0.4.1-victorialogs-0-g8fe44dadaa

**Comment by valyala** [comment]
@rul-hydro , thanks for filing the bugreport! The issue with improper sorting by time in [web UI for VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/querying/#web-ui) has been fixed in [v0.4.2-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.4.2-victorialogs) release.

Closing the issue as fixed then.
