### ISSUE TITLE
NaNs with blackbox_exporter

### ISSUE THREAD

**Issue by alub** [VictoriaMetrics/VictoriaMetrics#5334]
### Describe the bug

Hello,

I’m using VictoriaMetrics with [blackbox exporter](https://github.com/prometheus/blackbox_exporter), and I see some occurrences of NaNs in queries and exports for all related series. These happen everytime I stop blackbox exporter for example.

In queries, I see `"NaN"` as a value, and a JSON `null` in export.

Quoting the [documentation](https://docs.victoriametrics.com/MetricsQL.html#metricsql):
> MetricsQL removes all the NaN values from the output, so some queries like (-1)^0.5 return empty results in VictoriaMetrics, while returning a series of NaN values in Prometheus.

I didn’t expect to see NaNs anywhere, so can you confirm if this is a bug of an expected behaviour?

I did not manage to reproduce this manually (e.g. with the import API).

Thank you for your help.

### To Reproduce

I cannot share the full configuration files, but I can reproduce the issue by stopping blackbox exporter and querying VictoriaMetrics for any `probe_success{instance="<some instance>"}[5m]` and I see one datapoint with `"NaN"`.

### Version

Tested with VictoriaMetrics 1.84.0 and 1.94.0.

### Used command-line flags

```
/usr/bin/victoria-metrics \
    -promscrape.config /etc/prometheus/config.yml \
    -storageDataPath <some path> \
    -storage.minFreeDiskSpaceBytes 256MB \
    -promscrape.suppressScrapeErrors \
    -retentionPeriod 14d
```

**Comment by valyala** [comment]
VictoriaMetrics can return `NaN` from [instant query api](https://docs.victoriametrics.com/keyConcepts.html#instant-query) only when [staleness markers](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) are inserted into the queried time series. For example, the following query returns `NaN` because the given instance stops existing:

```
curl https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/query -d 'query=up{instance="10.71.1.87:8080"}[2m]' -d 'time=2023-11-16T08:21:20Z' | jq .
```

```json
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "up",
          "namespace": "monitoring",
          "cluster": "sandbox",
          "service": "vmalert-main",
          "job": "vmalert-main",
          "instance": "10.71.1.87:8080",
          "pod": "vmalert-main-6c4c99b7b6-cmpsg",
          "container": "vmalert",
          "endpoint": "http",
          "prometheus": "monitoring/monitoring-vmagent"
        },
        "values": [
          [
            1700122761.572,
            "1"
          ],
          [
            1700122776.572,
            "1"
          ],
          [
            1700122791.545,
            "0"
          ],
          [
            1700122806.545,
            "0"
          ],
          [
            1700122819.042,
            "NaN"
          ]
        ]
      }
    ]
  }
}
```

The staleness markers are also returned from [export API](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) as `null` values:

```
curl https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/api/v1/export -d 'match[]=up{instance="10.71.1.87:8080"}' -d 'start=2023-11-16T08:19:20Z' | jq .
```

```json
{
  "metric": {
    "__name__": "up",
    "namespace": "monitoring",
    "cluster": "sandbox",
    "service": "vmalert-main",
    "job": "vmalert-main",
    "instance": "10.71.1.87:8080",
    "pod": "vmalert-main-6c4c99b7b6-cmpsg",
    "container": "vmalert",
    "endpoint": "http",
    "prometheus": "monitoring/monitoring-vmagent"
  },
  "values": [
    1,
    1,
    0,
    0,
    null
  ],
  "timestamps": [
    1700122761572,
    1700122776572,
    1700122791545,
    1700122806545,
    1700122819042
  ]
}
```

The `NaN` values shouldn't be returned by VictoriaMetrics from regular queries as documented at [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html). See [the corresponding code, which removes samples with `NaN` values before returning the result to the client](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2ea03cf80d265fac44579aa98b93f9fd339954d9/app/vmselect/prometheus/prometheus.go#L936-L975).
