### ISSUE TITLE
Is in memory part must be merged into file parts to become search visible?

### ISSUE THREAD

**Issue by satjd** [VictoriaMetrics/VictoriaMetrics#5410]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

It seems that in memory parts is become search visible BEFORE it is merged into file parts. Is there any misleading information in code comments below?

["// It must be merged into either smallParts or bigParts to become visible to search."](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8eddccfbb41a916db59e4320eb62ec7f78eea818/lib/storage/partition.go#L145)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Yeah, looks like a wrong comment here.
`inmemoryParts` should be able to search in the same way as the data stored on disk since we get all the part when search
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/47307c7a37e204123422b6aacbafd22e86dd26a5/lib/storage/partition_search.go#L83
And in-memory data will only lose on unclean shutdown (hardware power loss, OOM crash, SIGKILL).

**Comment by valyala** [comment]
@satjd , thanks for raising the attention to the misleading comment. This comment has been removed in the commit 90768aa418fbb01b486314b0179b56475c09556a . Closing the issue as fixed.
