### ISSUE TITLE
Alerting for if an instance goes down.

### ISSUE THREAD

**Issue by shivtej-opsverse** [VictoriaMetrics/VictoriaMetrics#5454]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

- I have 10 machines from which I am getting `node-exporter` metrics.
- I need to set up an alert whenever one of these instances goes down and need a resolved message only when the instances is back up.
- The expression i am using currently is `(group(last_over_time(up{job="integrations/node-exporter"}[1m])) by (instance) OR on() vector(0)) !=1`
- However the problem with the above expression is I will get an alert notification when the instance goes down and  get  a resolved message after the interval over which I am querying this expression even if the instance is still down.
- Is there a better way to do this 
- Any help would be appreciated

Thanks

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
I think the problem with expr `(group(last_over_time(up{job="integrations/node-exporter"}[1m])) by (instance) OR on() vector(0))` is that when `up{job="integrations/node-exporter"}=0` which also means instance is down, it still return 1 instead of 0. 
So you shouldn't use `group by` here, how about `(sum(last_over_time(up{job="integrations/node-exporter"}[1m])) by (instance) > 0 OR on() vector(0))`?
