### ISSUE TITLE
How to set tlsCAFile to be used by VMInsert

### ISSUE THREAD

**Issue by lucker7777** [VictoriaMetrics/VictoriaMetrics#5458]
Hello,
I am using _victoria-metrics-cluster_ helm chart and in values.yaml I have following set up for VMInsert:
_extraArgs:
    tls: "true"
    tlsCertFile: "/crt/tls.crt"
    tlsKeyFile: "/crt/tls.key"_
 (of course, I have secrets mounted)
 
I would like to set up tlsCAFile here as well, but in [docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html), I only see cluster.tlsCAFile, which is a different thing. What I want to achieve is mTLS between Prometheus and VMInsert.
So, how can I add tlsCaFile for VMInsert?

Thank you.

**Comment by lucker7777** [comment]
Hi,

Aha, I see that option to have CA cert in VMInsert is missing in VMInsert itself, not just in the helm chart.

So, what I do not need is mTLS between VMInsert and other VM components (that I know is an enterprise feature).

I need mTLS between Prometheus and VMInsert. I am using Prometheus remoteWrite to push metrics into VMInsert.
I have enabled TLS and set up certificates in VMInsert and the only thing missing is VMInsert having CA cert to authenticate Prometheus's certificate.

**Comment by valyala** [comment]
@lucker7777 , all the [VictoraMetrics Enterprise](https://docs.victoriametrics.com/enterprise.html) components will support [mTLS](https://en.wikipedia.org/wiki/Mutual_authentication) for https requests sent to `-httpListenAddr` in the next release. See [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#mtls-protection) and [this commit](7bc3af1224b66bc9d10b49a4a03f06aa1769172f) for details.

**Comment by lucker7777** [comment]
@valyala Ok, so according to what I read in the commit, I can use TLS (by setting tls, tlsCertFile, tlsKeyFile) without an Enterprise license, but when I want to have a certificate to be verified, by setting tlsCAFile, I need to have an Enterprise licence?

Just a reminder, that I do not need mTLS between VM's components, just mTLS between external component (Prometheus) and VMInsert.

**Comment by valyala** [comment]
> according to what I read in the commit, I can use TLS (by setting tls, tlsCertFile, tlsKeyFile) without an Enterprise license, but when I want to have a certificate to be verified, by setting tlsCAFile, I need to have an Enterprise licence?

Correct. All the [VictoriaMetrics Enterprise](https://docs.victoriametrics.com/enterprise.html) components gained the ability to verify client TLS certificates at `-httpListenAddr` when they run with `-mtls` command-line flag as described [here](https://docs.victoriametrics.com/cluster-victoriametrics/#mtls-protection), starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html). The `-tlsCAFile` can be optionally specified when using custom Root TLS CA instead of system-wide one.

You can evaluate this functionality by requesting trial Enterprise license as described [here](https://docs.victoriametrics.com/enterprise/#valid-cases-for-victoriametrics-enterprise).

Closing the feature request as done.
