### ISSUE TITLE
Does vmagent reload CA file used in tls_config for jobs configured?

### ISSUE THREAD

**Issue by brucelee138** [VictoriaMetrics/VictoriaMetrics#5526]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

We could see that vmagent supports auto-reload of the client certs after https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2171 (Implement TLS certs auto-reload)
But it seems the same functionality for re-reading the certs is missing for CA cert configured for a job in config. Was this a miss or intentionally implemented(for some reason)?

Thanks in advance!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @brucelee138 
#2171 was referring to TLS certificates which are used to expose HTTP APIs for the components. Certificates which are used for scraping are cached only up to 1 second, so if certificate was updated on disk new one will be used in a second when cache will be reset.

**Comment by brucelee138** [comment]
@zekker6 Thanks for the response!
We had meant the CA file we configure for scraping a job.
For ex:
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - etcd
        tls_config:
          **ca_file: /var/run/secrets/vmagent/client/ca.crt**
          cert_file: /var/run/secrets/vmagent/client/tls.crt
          key_file: /var/run/secrets/vmagent/client/tls.key

Aleast from what I understand the CA file or certs for a endpoint configured is only initialized once during startup by "initFromTLSConfig()". For certs, we have used a func pointer which always returns new certs from disk (this was done for #2171)
But for the CA, I think this change was missed (intentionally?)
Currently, we are observing that though the certs are updated on disk, vmagent still uses the old certs causing tls errors.

**Comment by zekker6** [comment]
@brucelee138 Thanks for clarification!
In order to lower resource consumption HTTP client for different discovery/scrape jobs are always initialized once and re-used later. 
See this for an example:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d5a599badce3ff84c3ef236e1e8c3fb38514f272/lib/promscrape/client.go#L84-L192

As a part of HTTP client initialization `http.Transport` with `tls.Config` is created. `http.Client.Transport` type is [`tls.Client`](https://pkg.go.dev/crypto/tls#Config) which defines root CA as:
```
// RootCAs defines the set of root certificate authorities
// that clients use when verifying server certificates.
// If RootCAs is nil, TLS uses the host's root CA set.
RootCAs *x509.CertPool
```
So there is no way for us to provide a function which would reload CA once it will be changed on disk, similar to how this works for certificate itself.

I'll mark this issue as a feature request as it seems like a good feature to implement.

**Comment by brucelee138** [comment]
@zekker6 Thanks for the detailed feedback. So I understand this rootCA would be common for all hosts?

It is mentioned avove in comment as "If RootCAs is nil, TLS uses the host's root CA set." - We are setting a host CA and using this. This gets loaded here in inittlsfromConfig() again

else if tc.CAFile != "" {
		path := fs.GetFilepath(baseDir, tc.CAFile)
		data, err := fs.ReadFileOrHTTP(path)
		if err != nil {
			return fmt.Errorf("cannot read `ca_file` %q: %w", tc.CAFile, err)
		}
		tctx.rootCA = x509.NewCertPool()
		if !tctx.rootCA.AppendCertsFromPEM(data) {
			return fmt.Errorf("cannot parse data from `ca_file` %q", tc.CAFile)
		}
	}

I was thinking this host root CA would also get refreshed if we implement it similarly like we do for host client certs (just above in the function)

else if tc.CertFile != "" || tc.KeyFile != "" {
		tctx.getTLSCert = func(*tls.CertificateRequestInfo) (*tls.Certificate, error) {
			// Re-read TLS certificate from disk. This is needed for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1420
			certPath := fs.GetFilepath(baseDir, tc.CertFile)
			keyPath := fs.GetFilepath(baseDir, tc.KeyFile)
			cert, err := tls.LoadX509KeyPair(certPath, keyPath)
			if err != nil {
				return nil, fmt.Errorf("cannot load TLS certificate from `cert_file`=%q, `key_file`=%q: %w", tc.CertFile, tc.KeyFile, err)
			}
			return &cert, nil
		}

**Comment by zekker6** [comment]
@brucelee138 

> So I understand this rootCA would be common for all hosts?

Yes, it will be using system root CAs in case `tls_config.ca_file` is not set.


> I was thinking this host root CA would also get refreshed if we implement it similarly like we do for host client certs (just above in the function)

Actually, this is already implemented in the same way here:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/01f9edda64496ff897dfc9f75f4ea0865a5cebdf/lib/promauth/config.go#L795-L816


This implementation is than used to construct `promauth.Config` here:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/01f9edda64496ff897dfc9f75f4ea0865a5cebdf/lib/promauth/config.go#L607-L623

Because of this when constructing a new TLS config [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/01f9edda64496ff897dfc9f75f4ea0865a5cebdf/lib/promauth/config.go#L453-L474) it will re-read CA files from disk. The problem is that `tls.Config` is only created once and than used to perform all the requests. And since `tls.Config` does not provide an option to fetch CA files dynamically(like for regular `Certificate`) it is required to intiialize a new client to load new CA certificates.

**Comment by zekker6** [comment]
Hello @brucelee138, one of my colleagues pointed out that even though reloading TLS Root CA does not work dynamically, it is still expected to work when reloading process configuration by sending request to `/-/reload` or `SIGHUP` signal to vmagent process(see https://docs.victoriametrics.com/vmagent.html#configuration-update).

I've tested this and found out that reloading `tls_config` on the job root level(`scrape_configs[].tls_config` works, but it does not for service discovery configs(such as `kubernetes_sd_configs` -> `scrape_configs[].kubernetes_sd_configs[].tls_config`). I've converted this issue into a bug report and will work on fixing this shortly.

**Comment by brucelee138** [comment]
@zekker6 Thanks a lot for taking this!

**Comment by zekker6** [comment]
Hi @brucelee138, commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/fe10f036070166682672b1978c06b9a84527e8d3 adds an ability to detect change of root CA and apply new certificate automatically. It would be great if you could try building [vmagent from this commit](https://docs.victoriametrics.com/vmagent/#how-to-build-from-sources) and sharing the result.

**Comment by brucelee138** [comment]
@zekker6 thanks for taking this up! I would surely test this commit and share the result.

**Comment by brucelee138** [comment]
@zekker6 sorry for the delayed response. I got around to testing the fix now. Would we get any logs too in vmagent indicating that CA certs are refreshed.

**Comment by zekker6** [comment]
@brucelee138 No, refresh will not produce any logs.

**Comment by brucelee138** [comment]
@zekker6 I have tested this by creating a CA which gets rotated periodically and the vmagent (built from commit) seem to use the new CA cert thereby not causing any tls issues.
I was seeing tls handshake errors ("certificate signed by unknown authority"in the tls endpoint pods while using the vmagent without this fix, no such errors were seen and metrics were scraped.
Thanks for your help on this!
