### ISSUE TITLE
Which version of vector can be used to match victorytorialogsv0.4.2

### ISSUE THREAD

**Issue by frankbaozun** [VictoriaMetrics/VictoriaMetrics#5528]
### Is your question request related to a specific component?

Which version of vector can be used to match victoria-logs v0.4.2

### Describe the question in detail

Which version of vector can be used to match victoria-logs v0.4.2

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @frankbaozun 
You can find an example configuration that we tested to work with vector here - https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker/victorialogs/vector-docker , it uses `vector:0.30.0`.

A newer version should also work since our example uses Elasticsearch protocol, and it did not change recently.
