### ISSUE TITLE
Disk read between each vm-storage node are quite different

### ISSUE THREAD

**Issue by yrka5180** [VictoriaMetrics/VictoriaMetrics#5537]
### Is your question request related to a specific component?

vmstorage 1.87.5

### Describe the question in detail

**Background:**
We currently have vm-cluster with 42 vmstorage, 10 vmselect and 6 vminsert instances, each vmselect/vminsert instance connect with all 42 vmstorages.  

We first had 12 vmstorage running, and then continuously adding another 30 vmstorage instances.

Total datapoints is about 140 Tri, ingestion rate is about 14 Mil and active series is around 317 Mil. And the data retention period is 365d.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/76882301/0738fa6e-b5e7-4486-906f-fbcc8d008892)

We recently discovered a significant discrepancy in disk read performance between different VM storage nodes.
The consequences of this imbalance could be severe, potentially leading to saturation of disk I/O, then the VM storage node is incapable of handling other read and write requests. Finally, this could result in the collapse of the entire cluster.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/76882301/f181bd1b-2ecd-4d04-9912-1ee93347247d)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/76882301/6a29cad8-22f7-46de-953f-f752bd6a33ec)

As what we expected, with each query request, vmselect should send queries to all vmstorage nodes, and disk I/O should be evenly distributed.

**Question:** 
1. Why there is significant discrepancy in disk read performance between different VM storage nodes.
2. Why can the disk read speed of a single node even reach 700MB/s?

How should we troubleshoot the issue? 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @yrka5180 

> We first had 12 vmstorage running, and then continuously adding another 30 vmstorage instances.

Based on this I can suggest that there will be a different amount of data stored across storage nodes because VictoriaMetrics does not perform any data rebalancing after changing number of vmstorage nodes. After new nodes are added vminsert will distrubute new datapoints across all available storage nodes.

Because of this when vmselect will execute query different amount of data needs to be processed on each storage node. The more datapoints is stored on the storage node the higher read rate will be.

You can confirm this by running this query (you need to have [monitoring configured](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring) for the cluster):
```
sum(vm_rows{type!~"indexdb.*"}) by (instance)
```
It will display amount of datapoints stored across different storage nodes. I'd expect this number to correlate with vmstorage node age - the older storage node is the more datapoints will be present.

**Comment by SRE-Rick** [comment]
What's the latest?

**Comment by jiekun** [comment]
Close as answered.

And Hi @SRE-Rick I'm not sure about your question. If you found something strange, feel free to raise an issue.
