### ISSUE TITLE
Exception result from VM

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#555]
**Describe the bug**
the sum result is not correct

**To Reproduce**
1. one series (assume name is q) with 2 sample (from export api)
```
1591808010: 1
1591883230: 1
```

2. query_range param
```
start=1591804800
end=1591891140
step=60
```

3. query_range: q, result
```
1591808040: 1
1591808100: 1 

...repeat every 60s...

1591883280: 1

...repeat every 60s...

1591891080: 1 
1591891140: 1 
```

**Expected behavior**
get
```
1591808040: 1
1591883280: 1

other timestamp's value is non exist
```

4. query_range: sum(q), result
``` same as step 3```

**Expected behavior**
get
```
1591808040: 1
1591883280: 1

other timestamp's value is non exist
```

5. query_range: count_over_time(q)[5m], result
```
1591808040: 1
1591808100: 0

...repeat every 60s...

1591883280: 1
1591883340: 1 
1591883400: 1 
1591883460: 1 
1591883520: 1 
```

**Expected behavior**
get
```
1591808040: 1
1591883280: 1

other timestamp's value is 0 or non exist
```

**Version**
```
$ ./bin/victoria-metrics --version
victoria-metrics-20200612-073655-heads-master-0-ge53ee763
```

**Comment by valyala** [comment]
VictoriaMetrics fills gaps in time series with the previous values if they are located closer than 2x scrape_interval  (aka interval between data points). This is intentional behaviour, which conforms [Prometheus data model](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness).

The behaviour can be modified by setting `-search.maxStalenessInterval` command-line flag to small durations:

>  -search.maxStalenessInterval duration
>        The maximum interval for staleness calculations. By default it is automatically calculated from the median interval between samples. This flag could be useful for tuning Prometheus data model closer to Influx-style data model. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness for details. See also '-search.maxLookback' flag, which has the same meanining due to historical reasons

For example, try running VictoriaMetrics with `-search.maxStalenessInterval=10s` in order to obtain the expected result described in the original message above.

Additionally, the ` count_over_time(q)[5m]` query looks incorrect. It is likely it must be written as `count_over_time(q[5m])`. In this case it will return the number of data points in `q` for the last 5 minutes. The `count_over_time(q)[5m]` is automatically translated into `last_over_time(count_over_time(q[step])[5m])` by VictoriaMetrics, so it returns the number of data points in `q` for the last `step` seconds (60s in your case). This is called [subquery](https://medium.com/@valyala/prometheus-subqueries-in-victoriametrics-9b1492b720b3).

**Comment by n4mine** [comment]
`count_over_time(q)[5m]` it's a typo, i mean `count_over_time(q[5m])` actually. :)

> For example, try running VictoriaMetrics with -search.maxStalenessInterval=10s in order to obtain the expected result described in the original message above.

it seems `max_lookback` not work as expected?  or it's a wrong understanding from me?
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/570
