### ISSUE TITLE
Trace failing queries

### ISSUE THREAD

**Issue by rul-hydro** [VictoriaMetrics/VictoriaMetrics#5588]
### Is your feature request related to a problem? Please describe

I run into the message "Duplicate series found {}" frequently. Since the same query sometimes works, and sometimes not, I would like to dig deeper into the problem. However, the "Trace query" button in VMUI has no effect when the query fails.

### Describe the solution you'd like

If a query fails in the middle of doing something, the "Trace query" button should show all subqueries and evaluations up to the point where the error occurs.

**Comment by xiaozongyang** [comment]
I'd like to try to add this feature, but it will increase query latency and consume more memory and cpu.
cc @hagen1778 @valyala 

Maybe we can add a new bool flag nemed `autoTrace`, when this flag is set to true the queryTracer is always enabled. But when we write response, we write trace json to client lf there is any error in this trace, otherwise we ignore this trace. 
```go
// Write Response
if tracerEnbaledByURLParameter || tracerHasError {
     appendTraceJSON
}
```

**Comment by rul-hydro** [comment]
I'm not sure if you get my intention correctly. I was trying to re-run the query with tracing enabled *after* it failed, but the trace would not show up.

**Comment by xiaozongyang** [comment]
You want the trace  printed in error log stream?

**Comment by rul-hydro** [comment]
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/85218380/58f825c9-a3a6-4325-8ead-3fcc094f4ba9)
The query for `remoteman_busy_nodes_info` returns samples, but after the `label_del` operation, the samples will not be unique any more. It would help a lot if the trace showed the succeeding and failing subqueries. As it is, it does not show anything.
