### ISSUE TITLE
Handle 'undefined' values in PromQL queries to match compatibility with prometheus and mimir

### ISSUE THREAD

**Issue by Bruno-DaSilva** [VictoriaMetrics/VictoriaMetrics#5629]
### Describe the bug

When I send a request like this:
```
curl '.../api/v1/query' 
  --data-raw 'query=sum%28kube_node_info%29&instant=true&step=undefined&range=false&start=undefined&end=undefined' 
```

Victoriametrics responds with:
```
{
    "status": "error",
    "errorType": "422",
    "error": "cannot parse \"step\"=\"undefined\": cannot parse duration \"undefined\""
}
```

whereas prometheus responds with:
```
{
    "status": "success",
    "data": {
        "resultType": "vector",
        "result": [data here...]
    }
}
```

and Mimir responds with the same:
```
{"status":"success","data":{"resultType":"vector","result":[data here...]}}
```

### To Reproduce

send victoriametrics a PromQL query with data: `'query=sum%28kube_node_info%29&instant=true&step=undefined&range=false&start=undefined&end=undefined'`

Observe the following error returned: 
```
{
    "status": "error",
    "errorType": "422",
    "error": "cannot parse \"step\"=\"undefined\": cannot parse duration \"undefined\""
}
```

### Version

running the docker image: `victoriametrics/vmselect:v1.87.1-cluster`:
`vmselect-20230209-232944-tags-v1.87.1-cluster-0-ga68bb879d`

### Logs

No logs!

### Screenshots

This is encountered when using the `Grafana Kubernetes Monitoring` plugin in Grafana Cloud.
<img width="1800" alt="Screen Shot 2024-01-16 at 5 14 10 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8520801/8370bb23-f9d5-4bfc-a1d6-14d18d07f68c">

### Additional information

I know this is technically 'undefined behaviour' and probably isn't in the API spec, but could we match the behaviour here so VM is compatible with this kubernetes monitoring plugin?

**Comment by Bruno-DaSilva** [comment]
I'm separately opening up a support ticket with Grafana to have them not send `undefined` where possible, and instead send nothing.

**Comment by Bruno-DaSilva** [comment]
Note that if you send the payload `query=sum%28kube_node_info%29&instant=true&range=false` (removing the undefineds) victoriametrics returns data.

**Comment by Haleygo** [comment]
Hi,
Thanks for the detailed report! 
So the problem here is parameter `step`, to prometheus&mimir, `step` is not a valid param in [instant query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries), so they will just ignore the value. As for [victoriametrics instant query api](https://new.docs.victoriametrics.com/keyconcepts/#query-data), step is optional and stands for the maximum [interval](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations) for searching for raw samples in the past, so the value will be parsed and report error when the value is illegal.
Maybe we can add special case in victoriametrics api for this, but I don't think grafana's way to pass some param with `undefined` values is a good thing.

**Comment by Bruno-DaSilva** [comment]
@Haleygo @valyala is this in 1.97.0? I see the commit in that tag, but don't see it in the changelog.

**Comment by Haleygo** [comment]
> @Haleygo @valyala is this in 1.97.0? I see the commit in that tag, but don't see it in the changelog.

Yes, it is. Changelog seems to be loss though)

Close this as completed, feel free to reopen if it's not working since v1.97.0.
