### ISSUE TITLE
for most case, mmap file use copy is no need

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#5644]
### Is your feature request related to a problem? Please describe

see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e374c227fe079a6f30fc98e80fe32e04d3c2c3b/lib/fs/reader_at.go#L71

for most case,  in memory block will read data from items.bin/lens.bin. After load data, next step is unmarshal.
So, no need to copy when file data is in a short time use.

Suggest:
1.add a new `GetReadonlyBufferFromMMap()` method of ReadAt;
2.Everytime when use `partSearch.readInmemoryBlock()`, use the no copy version  

### Describe the solution you'd like

N/A

**Comment by valyala** [comment]
This may be dangerous in the sense that the byte slice returned from `GetReadonlyBufferFromMMap()` becomes invalid after the `mmap`ed file is unmapped. This can be tracked in theory, but the resulting code becomes more fragile and much harder to debug.

Additionally, the `readInmemoryBlock()` calls `UnmarshalData()`, which spends multiple orders of magnitude more CPU time comparing to the `copy()` inside `ReaderAt.MustReadAt()`. So it is better to do not add `GetReadonlyBufferFromMMap()` function to `ReaderAt`, since performance gains are negligible comparing to potential problems this function could bring.

**Comment by ahfuzhang** [comment]
understood.Thank you.
