### ISSUE TITLE
Export and Import APIs are not reliable and have no guarantees for read/write requests. 

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5645]
### Describe the bug

 Both Export (native, reduce_mem_usage) and import (native, jsonline, etc) are http stream based.

 Currently, there is no way to return a error to the client, if error happened in the middle of the stream. 

 For Export API, it's not possible that data transfer was started and 200 Ok response was returned to the client, but in meanwhile one of storage nodes crashed or returned max.search* error. 

 For Import APIs, any errors must be checked at logs of vminsert/vmsingle, since API always return status code 204. 

### To Reproduce

 Setup cluster version with uneven distributed data. Some storage nodes may return search.max* error, when other already started to reply with metricBlocks to the client.
 Same for the import APIs. 

### Version

any version is affected.

### Additional information

 It'd be great to implement parsing of requests for export API at vmctl side. Currently, it only transfers bytes with stream from source to destination.

 For curl based clients it's possible to add `Transfer-Encoding: chunked` or `Trailer` header. https://www.rfc-editor.org/rfc/rfc2616#section-14.40

**Comment by valyala** [comment]
The commit 8ab0ce3ded091e8fb5d92e7494c67d22761c967f aborts client connections at `-httpListenAddr` when `httpserver.Error()` is called after sending http response headers. This should help detecting errors after [`/api/v1/export*`](https://docs.victoriametrics.com/#how-to-export-time-series) starts streaming the data to client such as [vmctl](https://docs.victoriametrics.com/vmctl.html).

**Comment by valyala** [comment]
> For Import APIs, any errors must be checked at logs of vminsert/vmsingle, since API always return status code 204.

This is partially true for [all the text-based import APIs supported by VictoriaMetrics](https://docs.victoriametrics.com/#how-to-import-time-series-data), in the sense that VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent.html) do not return errors in the response for invalid input text lines. This allows importing the rest of the provided text lines without issues instead of returning an error on the first invalid text line, since it is quite common to have some invalid text lines in the imported data. Note that all the errors related to the server side, are immediately returned to the client. For example, if there is no enough free disk space for the imported data, then this error is immediately returned to the client.

The logic above doesn't apply to [data import via native binary protocol](https://docs.victoriametrics.com/#how-to-import-data-in-native-format) (aka `/api/v1/import/native`). VictoriaMetrics and vmagent immediately return all the errors to the client, including data parsing errors. This should help detecting incomplete or invalid data at [vmctl](https://docs.victoriametrics.com/vmctl.html) when it [migrates the data via native protocol](https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics).

**Comment by valyala** [comment]
FYI, all the VictoriaMetrics components starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html) break HTTP response stream on internal errors, which can occur after sending HTTP response headers. This should help notifying [vmctl](https://docs.victoriametrics.com/vmctl.html) on errors, which may occur in the middle of [native export](https://docs.victoriametrics.com/#how-to-export-data-in-native-format).
