### ISSUE TITLE
check for `bsm.prepareBlock()` is not make sense

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#5655]
### Describe the bug

see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9c153d07101a52632df0d77d836b38c5e13f670d/lib/mergeset/merge.go#L180

I want write a callback func to drop some index when merge.
But the check logic for `bsm.prepareBlock()` is so strange.

I think the code might be:
```go
	if bsm.prepareBlock != nil {
		data, items = bsm.prepareBlock(data, items)  // at there, call back might be drop some index
		if len(items) == 0 {
			// Nothing to flush
			return
		}
		bsm.firstItem = append(bsm.firstItem[:0], items[0].String(data)...)
		bsm.lastItem = append(bsm.lastItem[:0], items[len(items)-1].String(data)...)
		//
		bsm.ib.data = data
		bsm.ib.items = items

                 // no need to check, not make sense
		// Consistency checks after prepareBlock call.
		// firstItem := items[0].String(data)
		// if firstItem != string(bsm.firstItem) {
		// 	logger.Panicf("BUG: prepareBlock must return first item equal to the original first item;\ngot\n%X\nwant\n%X", firstItem, bsm.firstItem)
		// }
		// lastItem := items[len(items)-1].String(data)
		// if lastItem != string(bsm.lastItem) {
		// 	logger.Panicf("BUG: prepareBlock must return last item equal to the original last item;\ngot\n%X\nwant\n%X", lastItem, bsm.lastItem)
		// }
		// Verify whether the bsm.ib.items are sorted only in tests, since this
		// can be expensive check in prod for items with long common prefix.
		if isInTest && !bsm.ib.isSorted() {
			logger.Panicf("BUG: prepareBlock must return sorted items;\ngot\n%s", bsm.ib.debugItemsString())
		}
	}
```

### To Reproduce

N/A

### Version

v1.96.0 cluster

**Comment by valyala** [comment]
@ahfuzhang , please see the commit 4e26ad869b13642a22e6238aa0183740d9683c74 . The `mergeset` assumes that:

- all the items in block are sorted
- blocks remain sorted after `prepareBlock` modifications

If these assumptions fail, then this will make the output merge result invalid.

In theory, the first and the last items in every block can be modified if the modification doesn't break surrounding blocks' order. For example, it is possible to drop the first and the last items without breaking surrounding blocks' order. The consistency checks must remain in the `prepareBlock()` function in order to prevent from `mergeset` data corruption by improperly implemented `prepareBlock` callback. But these checks may become less restrictive, while guaranteing the assumptions mentioned above.

**Comment by ahfuzhang** [comment]
I understand the following settings:
1. All items must be sorted
2. The fisrtitem of the entire inmemoryBlock must be less than or equal to the lastItem of the previous block.
3. The lastitem of the entire inmemoryBlock must be greater than or equal to the lastItem of the next block.

However, the writing method in v1.96.0 obviously restricts the change of the first and last items, which I think is unreasonable.

**Comment by valyala** [comment]
@ahfuzhang , thanks for the suggestion - the commit 1c5163ae51b1eae921b39644d0d2e8ef3d26f562 relaxes the checks for the first and the last item after `prepareBlock()` call a bit.

**Comment by valyala** [comment]
Closing the issue as addressed then.
