### ISSUE TITLE
Samples saved with different precision in two similar vmstorage

### ISSUE THREAD

**Issue by perederyaev** [VictoriaMetrics/VictoriaMetrics#5752]
### Describe the bug

We work with process_start_time_seconds metric from some apps and found strange issue.
In two vmstorages samples saved differently. Both vmstorages are same version and work behind one vminsert so always get the same samples.

```
$ curl http://localhost:8498/select/0/prometheus/api/v1/export -d 'match[]=process_start_time_seconds{job="promxy-pprof"}' -d 'start=1706712720' -d 'end=1706713140' | jq
{
  "metric": {
    "__name__": "process_start_time_seconds",
    "namespace": "default",
    "service": "promxy-pprof",
    "job": "promxy-pprof",
    "instance": "10.116.68.99:8081",
    "pod": "promxy-7fd66c6664-cghcg",
    "clusterid": "prod",
    "endpoint": "pprof-port",
    "prometheus": "monitoring/vmagent"
  },
  "values": [
    1706710122.87,
    1706710122.87,
    1706710122.87,
    1706710122.87,
    1706710122.87,
    1706710122.87,
    1706710122.87
  ],
  "timestamps": [
    1706712752875,
    1706712812875,
    1706712872875,
    1706712932875,
    1706712992875,
    1706713052875,
    1706713112875
  ]
}
```

After restarting vmselect with second vmstorage
```
$ curl http://localhost:8498/select/0/prometheus/api/v1/export -d 'match[]=process_start_time_seconds{job="promxy-pprof"}' -d 'start=1706712720' -d 'end=1706713140' | jq
{
  "metric": {
    "__name__": "process_start_time_seconds",
    "namespace": "default",
    "service": "promxy-pprof",
    "job": "promxy-pprof",
    "instance": "10.116.68.99:8081",
    "pod": "promxy-7fd66c6664-cghcg",
    "clusterid": "prod",
    "endpoint": "pprof-port",
    "prometheus": "monitoring/vmagent"
  },
  "values": [
    1706710122.87,
    1706710122.87,
    1706710122.87,
    1706710122.8700001,
    1706710122.8700001,
    1706710122.8700001,
    1706710122.8700001
  ],
  "timestamps": [
    1706712752875,
    1706712812875,
    1706712872875,
    1706712932875,
    1706712992875,
    1706713052875,
    1706713112875
  ]
}
```

### To Reproduce

Don't have exact steps to reproduce. Probably need to generate some samples with digits after decimal point.

### Version

vmstorage-20231210-124834-tags-v1.93.9-cluster-0-g0773f3ff6
vmselect-20231210-124831-tags-v1.93.9-cluster-0-g0773f3ff6

**Comment by valyala** [comment]
This is expected behavior - VictoriaMetrics stores up to 12 decimal digits without loss. It may lose precision in lower digits for values with more than 12 decimal digits - see [these docs](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for details. Note that samples with too many noisy decimal digits have not so good compression rate, which may result in bigger disk space requirements for storing such a data.

VictoriaMetrics components provide the following additional features, which can help when dealing with the precision of samples stored in it:

- [round](https://docs.victoriametrics.com/metricsql/#round) function, which can be used for rounding values to the needed number of decimal digits.
- `-remoteWrite.roundDigits` command-line flag at [vmagent](https://docs.victoriametrics.com/vmagent.html):

>      Round metric values to this number of decimal digits after the point before writing them to remote storage. Examples: -remoteWrite.roundDigits=2 would round 1.236 to 1.24, while -remoteWrite.roundDigits=-1 would round 126.78 to 130. By default, digits rounding is disabled. Set it to 100 for disabling it for a particular remote storage. This option may be used for improving data compression for the stored metrics (default 100)

- `-remoteWrite.significantFigures` command-line flag at [vmagent](https://docs.victoriametrics.com/vmagent.html):

>      The number of significant figures to leave in metric values before writing them to remote storage. See https://en.wikipedia.org/wiki/Significant_figures . Zero value saves all the significant figures. This option may be used for improving data compression for the stored metrics. See also -remoteWrite.roundDigits (default 0)

- `-datasource.roundDigits` command-line flag at [vmalert](https://docs.victoriametrics.com/vmalert.html):

>      Adds "round_digits" GET param to datasource requests. In VM "round_digits" limits the number of digits after the decimal point in response values.

**Comment by perederyaev** [comment]
Thank you!
