### ISSUE TITLE
move flags for remoteWrite and remoteRead to configuration file

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#576]
**Is your feature request related to a problem? Please describe.**

 Both vmagent and vmalert have remote flags with a lot of options, bound to URLs by flag id.

 If you have multiple remoteWrite targets, let it be target1, target2 and target3. And I want to add basicAuth to target2, tls config to target3.
 So,  I have to add flags with correct order and specify empty flags for default values.
```bash
-remoteWrite.URL=http://target1
-remoteWrite.basicAuth.password=""
-remoteWrite.basicAuth.username=""
-remoteWrite.tlsCAFile=""
-remoteWrite.tlsCertFile=""
-remoteWrite.tlsKeyFile=""

-remoteWrite.URL=http://target2
-remoteWrite.basicAuth.password="password1"
-remoteWrite.basicAuth.username="user1"
-remoteWrite.tlsCAFile=""
-remoteWrite.tlsCertFile=""
-remoteWrite.tlsKeyFile=""

-remoteWrite.URL=http://target3
-remoteWrite.basicAuth.password=""
-remoteWrite.basicAuth.username=""
-remoteWrite.tlsCAFile="/tmp/ca"
-remoteWrite.tlsCertFile="/tmp/cert"
-remoteWrite.tlsKeyFile="/tmp/file"
```

Also, flag args can be replaced by one flag with multiple values:

```bash
-remoteWrite.URL='http://target1,http://target2,http://target3'
-remoteWrite.basicAuth.password=',"password1",'
-remoteWrite.basicAuth.username=',user1,'
-remoteWrite.tlsCAFile=',,/tmp/ca'
-remoteWrite.tlsCertFile=',,/tmp/cert'
-remoteWrite.tlsKeyFile=',,/tmp/file'
```

 It`s hard to maintain and a bit confusing. 

Maybe I`m wrong?

**Describe the solution you'd like**

It would be nice to configure such option with remote_write and remote_read sections, as Prometheus did:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

**Comment by valyala** [comment]
Agreed that it would be useful to configure `-remoteWrite.*` flags via [remote_write secion](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) in config file. Note that `-promscrape.config` file cannot be used for storing `remote_write` configs, since this file is used only for configuring Prometheus scraping. It isn't used for processing data ingested via [other protocols supported by VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-time-series-data).

So it would be great to have a separate `-remoteWrite.config` command-line flag pointing to configs related to remote_write.

**Comment by Allineer** [comment]
@valyala maybe common config file with all of vm*'s options?

**Comment by valyala** [comment]
> @valyala maybe common config file with all of vm*'s options?

There is a separate feature request for this - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/138 . It would be great if somebody could provide a list of pros & cons for config file for all the VictoriaMetrics options in this feature request.

**Comment by valyala** [comment]
Closing this feature request as won't implement. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/138#issuecomment-1932951181 for more details.
