### ISSUE TITLE
vmselect may crash after automated /tmp cleanup

### ISSUE THREAD

**Issue by lukepalmer** [VictoriaMetrics/VictoriaMetrics#5770]
### Describe the bug

vmselect fails with:
panic: FATAL: cannot determine free disk space on "/tmp/searchResults": no such file or directory

At almost exactly this time /var/log/messages shows:

2024-02-06T11:06:11.009845-05:00 <hostname> systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
2024-02-06T11:06:11.010223-05:00 <hostname> systemd[1]: Started Cleanup of Temporary Directories.

So: systemd is coming along and removing things from /tmp, which makes vmselect unhappy.

We can of course control the behavior of systemd, but I wanted to call this out because automatic /tmp cleanup is a reasonable behavior that some linux distributions would have out-of-the-box.

### To Reproduce

Run vmselect for longer than the threshold that systemd will take to delete things.

### Version

1.96

**Comment by valyala** [comment]
`vmselect` stores temporary data, which it obtains from `vmstorage` nodes on every incoming search query, to a temporary directory at `/tmp/searchResults` by default.

It is possible to change the directory for storing these results via `-cacheDataPath` command-line flag at `vmselect`. For example, if `vmselect` runs with `-cacheDataPath=/some/path/to/cache`, then `vmselect` will store temporary data from `vmstorage` nodes in the directory `/some/path/to/cache/tmp/searchResults`, while query caches will be stored in `/some/path/to/cache/rollupResult` directory on `vmselect` restart. Note that it is advised to point `-cacheDataPath` to a storage with fast IO in order to maintain high query speed. RAM-based storage such as [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) or [ramfs](https://wiki.debian.org/ramfs) is the best, HDDs with low IO bandwidth and high IO latency is the worst.


See the following source code for details:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/dc340a83a936bc440f5ba3c2ff60c5ce8a517281/app/vmselect/main.go#L112-L120

**Comment by lukepalmer** [comment]
I think that's totally reasonable in my case.

I'll leave it to your judgement if it's worth thinking about if this is broadly the right default behavior. Depending on linux distribution, it's possible for an unsuspecting user to hit this issue without changing any settings.

**Comment by jiekun** [comment]
Thank you for this issue report. As discussed above, I think it would be nice to add it to the doc.

**Comment by hagen1778** [comment]
@jiekun @lukepalmer the docs were improved in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6708
