### ISSUE TITLE
Reducing egress bandwidth utilization for remote-write

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5937]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I'm looking to forward an existing metrics stream from prometheus services from one cloud provider to Victoriametrics cluster in another data center.   Due to the cost of this bandwidth as well as the limited bandwidth available, I've considered having our Prometheus instances first remote-write to a local vmagent instance, which would then remote-write to the vminsert component of our Victoriametrics cluster in the target data center.   

Can you confirm if this is in fact a logical approach?   Is there anything else I should take in consideration for a setup such as this one?   Please note I am aware that enabling remote-write on Prometheus can result in approximately a 25% increase in memory usage.

Thank you for your help.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @hartfordfive, this approach will definitely be useful to save bandwidth.
You can also use `-remoteWrite.vmProtoCompressLevel` command-line flag to configure compression ration which vmagent will use. Bigger values reduce network usage at the cost of higher CPU usage. Negative values reduce CPU usage at the cost of higher network usage. The default value for the compression level is `0`, the minimum value is `-22` and the maximum value is `22`.

**Comment by valyala** [comment]
I wouldn't recommend increasing the default value for `-remoteWrite.vmProtoCompressLevel` command-line flag, since it may result in excess CPU usage without significant reduction in network bandwidth usage.

See also https://docs.victoriametrics.com/vmagent/#victoriametrics-remote-write-protocol and https://victoriametrics.com/blog/victoriametrics-remote-write/

**Comment by hartfordfive** [comment]
Thank you for that clarification.   With regards to memory usage, how much memory on average should I expect these vmagent instances to consume in relation to the stream of metrics they are receiving from the prometheus instances?   Also, to which degree should the vmagent statefulset be scaled up (in terms of # of instances) in order to safely and effectively handle remote-write requests from multiple prometheus HA pairs?

**Comment by zekker6** [comment]
@hartfordfive 

> With regards to memory usage, how much memory on average should I expect these vmagent instances to consume in relation to the stream of metrics they are receiving from the prometheus instances? Also

Please, check out [this](https://play-grafana.victoriametrics.com/d/G7Z9GzMGz_vm/victoriametrics-vmagent-vm?orgId=1) dashboard to see the resource usage on our public benchmark. It simulates scraping metrics and writing to the cluster deployment of VictoriaMetrics. In your case it might use a bit less resources since there will be no scraping performed.

> Also, to which degree should the vmagent statefulset be scaled up (in terms of # of instances) in order to safely and effectively handle remote-write requests from multiple prometheus HA pairs?

It is enough to have 2 instances to make it HA. You can use more replicas in order to make it easier to scale it horizontally and dedicate less resources to each replica.
