### ISSUE TITLE
Corruption after VM host crash

### ISSUE THREAD

**Issue by ossimoi** [VictoriaMetrics/VictoriaMetrics#5945]
### Describe the bug

Starting VictoriaMetrics after virtual machine crashing resulted in:

```
Mar 10 03:04:38 shima victoria-metrics-prod[4100713]: 2024-03-10T01:04:38.664Z        panic        VictoriaMetrics/lib/mergeset/part.go:97        FATAL: cannot unmarshal metaindexRows from "/var/lib/victoria-metrics-data/indexdb/17A2CC2544B94808/17A52EC3EDD9FF1D": cannot decompress metaindex data: cannot decompress zstd block with len=43 to a buffer with len=0: decompression error: Src size is incorrect; block data (hex): 28B52FFD20339901002201016E6F64655F73797374656D645F756>
Mar 10 03:04:38 shima victoria-metrics-prod[4100713]: panic: FATAL: cannot unmarshal metaindexRows from "/var/lib/victoria-metrics-data/indexdb/17A2CC2544B94808/17A52EC3EDD9FF1D": cannot decompress metaindex data: cannot decompress zstd block with len=43 to a buffer with len=0: decompression error: Src size is incorrect; block data (hex): 28B52FFD20339901002201016E6F64655F73797374656D645F756E69745F73746174650117A52EC3EA56F0
```

Moving corrupted indexes outside of VM data dir and trying to start VM gives:

```
2024-03-10T01:18:12.994Z	panic	VictoriaMetrics/lib/fs/reader_at.go:66	BUG: off=0 is out of allowed range [0...-1] for len(p)=46
panic: BUG: off=0 is out of allowed range [0...-1] for len(p)=46
```

### To Reproduce

Don't know how to repro.

### Version

victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565

### Used command-line flags

-storageDataPath=/var/lib/victoria-metrics-data -httpListenAddr=127.0.0.1:8428 -enableTCP6 -promscrape.config /etc/prometheus/prometheus.yml -promscrape.config.strictParse=false

**Comment by zekker6** [comment]
Hello @ossimoi 
Based on the error messages it seems like data on disk was corruped after virtual machine crash.
VictoriaMetrics tried to decompress the data and noticed the corruption, that's why the first error was thrown.

Removing parts of IndexDB is not recommended as this means loosing access to the data which was addressed by these index parts. Also, since data on disk was corrupted there might be multiple corruption across the file systems, so removing data piece by piece can lead to further data corruption or unstable behaviour.

In order to restore data properly it is required to restore data from the backup created with [vmbackup](https://docs.victoriametrics.com/vmbackup/).
