### ISSUE TITLE
Request to support ASLR in VictoriaMetrics

### ISSUE THREAD

**Issue by VeenaThimmegowda** [VictoriaMetrics/VictoriaMetrics#5962]
### Describe the solution you'd like

Following UK TSR requirement provided by the UK Department for Digital, Culture, Media and Sport in conjunction with the UK NCSC

V.D.4: Address Space Layout Randomisation
The vendor only ships executable code that has been compiled using modern ASLR techniques.
Why it matters: Widely used to make it more difficult for an attacker to exploit any security issues.
Evaluation (Security Declaration):The Security Declaration states whether the vendor’s products use ASLR throughout their product.
Evaluation (Customer or third-party lab test): Verify that address space layer randomization mitigations are enabled by (automatically) inspecting the product for this mitigation.

**Comment by hagen1778** [comment]
Hello @VeenaThimmegowda!
VictoriaMetrics is written in [Go](https://go.dev/) programming language that appears to be resilient to the common problems [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) is supposed to protect from. Please follow [this thread](https://groups.google.com/g/golang-nuts/c/Jd9tlNc6jUE) for more details. 

The potential vulnerability ASLR protects from could be in VictoriaMetrics using libraries written in C programming language, but VictoriaMetrics has only one such dependency - https://github.com/valyala/gozstd. In order to avoid using this dependency, VictoriaMetrics components can be built without `cgo` via the following command [make victoria-metrics-pure-prod](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/47e7ad2e01c8e6b1986703dc2111659f7d4d8260/app/victoria-metrics/Makefile#L12C1-L13).
