### ISSUE TITLE
vmselect: gracefully handle errors if cache dir was deleted

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5985]
### Is your feature request related to a problem? Please describe

By default, vmselect stores search cache at `temporary` directory. Temporary directories are different for each OS:
> // TempDir returns the default directory to use for temporary files.
//
// On Unix systems, it returns $TMPDIR if non-empty, else /tmp.
// On Windows, it uses GetTempPath, returning the first non-empty
// value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory.
// On Plan 9, it returns /tmp.

Sometimes, OS can be configured to periodically clean up temporary dirs. This could result into vmselect panic, as it expects exclusive access to cache dir created on startup.

### Describe the solution you'd like

vmselect should gracefully handle the error `[no such file or directory](panic: FATAL: cannot determine free disk space on "/tmp/searchResults": no such file or directory)` and make an attempt to re-create the folder if possible. It should crash if folder can't be re-created.

### Describe alternatives you've considered

Specify directory for caches explicitly via `-cacheDataPath` cmd-line flag and ensure that vmselect has exclusive access to specified destination.

**Comment by valyala** [comment]
VictoriaMetrics always makes sure that directories it access are created before the first access. If the directory isn't available during the access, this always means that the directory has been deleted by some third party. This is unexpected case. The best option from the operation and debuggability PoV is to crash with the `directory not found` error. This is what VictoriaMetrics does. 

Attempting to automatically handle unexpectedly deleted directories is the way to hell. If the OS deletes files inside `/tmp` directory, then there are the following valid options exist:
- To configure the OS to stop deleting recently accessed files at `/tmp` directory.
- To run `vmselect` with `-cacheDataPath` command-line flag pointing to the directory path, which won't be deleted by the OS.

If the directory, which is controlled by running VictoriaMetrics, is deleted by the user, then it is 100% better to crash with the clear `directory doesn't exist` error instead of trying to re-create the deleted directory, since otherwise this may end up in debuggability nightmare.

**Comment by valyala** [comment]
Closing this question as answered
