### ISSUE TITLE
Implement sanitize logic for graphite as in other protocols .

### ISSUE THREAD

**Issue by shayefarti** [VictoriaMetrics/VictoriaMetrics#6077]
### Is your feature request related to a problem? Please describe

As I was in the process of migrating  my old **Graphite** into **VictoriaMetrics**  I started to changes between them in the metrics names 

**In **Graphite****
sending `double..dots..test.testing.name1` displays the metric name as `double.dots.test.testing.name1`
In MictoraMetrics 

**But in VictoraMetrics** I see the following  `double..dots..test.testing.name1`
graphite has this capability built-in
When metrics are processed and stored by Graphite, it automatically sanitizes the metric names to ensure they adhere to its naming conventions. This sanitization process involves normalizing consecutive dots (..) into a single dot (.) in metric names

### Describe the solution you'd like

VictoriaMetrcis already has sanitize logic for various protocols. I think we should implement that for graphite as well.

This behavior is design and helps avoid unintended namespace segmentation caused by typographical errors or inconsistent naming practices. For instance, if a metric inadvertently includes multiple dots between namespace segments (like double..dots..test.testing.name1), Graphite will store this metric as double.dots.test.testing.name1, treating the extra dots as a single delimiter. This

**Comment by shayefarti** [comment]
Thanks you for the great news

**Comment by valyala** [comment]
The `-graphite.sanitizeMetricName` command-line flag is available in [vmagent](https://docs.victoriametrics.com/vmagent/) and in [single-node VictoriaMetrics](https://docs.victoriametrics.com/) starting from [v1.102.0](https://docs.victoriametrics.com/changelog/). When this flag is set, then multiple dots are substituted with a single dot in metric names and tags. Also, all the chars other than `a-zA-Z0-9:_.` are replaced with `_`, since these chars aren't supported by Prometheus datasource in Grafana.

Closing the feature request as done.
