### ISSUE TITLE
When I execute delete_series, will the files of indexdb on the disk be deleted?

### ISSUE THREAD

**Issue by cigarl** [VictoriaMetrics/VictoriaMetrics#6092]
### Is your question request related to a specific component?

victoriametrics

### Describe the question in detail

hi,
I have some scenes that I need to delete series,and i have to make sure that the indexdb is also deleted.

when i look through the code about `delete_series` and `indexdb merge`,i find that the deletion is recorded an item,and merge to all parts(these metrics are not deleted during merge).All deleted metricIDs is updated **in memory** when `OpenStorage` and `delete_series`.

That means,deleted metric can be **removed from disk** only after a retention period has been triggered?
If it is not deleted from disk, will it affect performance when my queries need to fall to disk?
I might run out of memory if I delete too many series?

I don't know if I'm missing something, and it bothers me.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @cigarl 

>  I have some scenes that I need to delete series,and i have to make sure that the indexdb is also deleted.

IndexDB entries are only deleted once IndexDB is rotated, this happens once per retention period.

> That means,deleted metric can be removed from disk only after a retention period has been triggered?
If it is not deleted from disk, will it affect performance when my queries need to fall to disk?
I might run out of memory if I delete too many series?

Please, note that metrics data itself is removed during subsequent background merge which happens more often.

>  If it is not deleted from disk, will it affect performance when my queries need to fall to disk?
I might run out of memory if I delete too many series?

Yes, deleting many series impacts query performance since it is required to apply filters to exclude such series from results. As described in the [documentation](https://docs.victoriametrics.com/#how-to-delete-time-series) delete operation is supposed to be used frequently or on regular basis. It is designed to be a one-off operation which is required in rare cases.

**Comment by cigarl** [comment]
> IndexDB entries are only deleted once IndexDB is rotated, this happens once per retention period.

Is it possible if I delete these items during the merge process?

> Please, note that metrics data itself is removed during subsequent background merge which happens more often.

Yes,but in my case, there are a lot of metrics that are written for a while and no longer used.Data was deleted and series is always exists until a retention period is triggered.It costs memory and affects query performance.

**Comment by zekker6** [comment]
@cigarl 

> Is it possible if I delete these items during the merge process?

No, that is not possible due to IndexDB architecture.

**Comment by zekker6** [comment]
Closing as initial question have been answered.
