### ISSUE TITLE
The same query produces different results from prometheus and victoria-metrics datasource

### ISSUE THREAD

**Issue by strobil** [VictoriaMetrics/VictoriaMetrics#612]
**Describe the bug**
The same query produces different results from `prometheus` and `victoria-metrics` datasource.
Data in the both datasources are equal. I'm using remote write APIs for populating data in Victoria Metrics.

For prometheus datasource result is always equal to `1`.
For victoria-metrics datasource result is periodically changes.

**To Reproduce**
Run the query for both datastores with the same data.

**Expected behavior**
The query should return exactly the same result as from `prometheus` datasource.

**Screenshots**
![prometheus](https://user-images.githubusercontent.com/6442572/86924078-a4c5a600-c137-11ea-97ee-080e7f99d1ea.png)
![victoria_metrics](https://user-images.githubusercontent.com/6442572/86924081-a5f6d300-c137-11ea-833e-7b37f4b3bb35.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
[root@elastic-log ~]# victoria-metrics -version
victoria-metrics-20200701-124459-tags-v1.37.4-0-g8da3f773a
```

**Used command-line flags**
-storageDataPath /mnt/storage/victoria-data -retentionPeriod 24

**Additional context**
This query is taken from [linkerd2](https://github.com/linkerd/linkerd2/tree/main/grafana/dashboards) grafana dashboards.

**Comment by valyala** [comment]
Note that the graph with Prometheus data has `0.7 ... 1.3` value range, while the graph with VictoriaMetrics data has `0.999(many nines here)9 ... 1.000(many zeroes here)1` value range. That's why the line for VictoriaMetrics looks jumpy - the jumps are in the range of `0.000(many zeroes here)1`, which looks like [floating-point rounding error](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html). It should look identical to the line from Prometheus on the `0.7 ... 1.3` value range. Make sure both graphs have identical settings in Grafana.

**Comment by strobil** [comment]
> Note that the graph with Prometheus data has `0.7 ... 1.3` value range, while the graph with VictoriaMetrics data has `0.999(many nines here)9 ... 1.000(many zeroes here)1` value range. That's why the line for VictoriaMetrics looks jumpy - the jumps are in the range of `0.000(many zeroes here)1`, which looks like [floating-point rounding error](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html). It should look identical to the line from Prometheus on the `0.7 ... 1.3` value range. Make sure both graphs have identical settings in Grafana.

On the first graph - data from VictoriaMetrics, on the second - from Prometheus.

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/6442572/86951402-275f5d00-c15a-11ea-8f01-7d8020c166e3.png">
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/6442572/86951443-33e3b580-c15a-11ea-8f60-a645d14c7de1.png">

**Comment by strobil** [comment]
On the graphs where Y Min and Y Max is not set its looks like this:

Prometheus
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/6442572/86951871-c7b58180-c15a-11ea-95f0-e9d42dcc4508.png">

VictoriaMetrics
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6442572/86951902-d56b0700-c15a-11ea-8849-fce5a6604984.png">

**Comment by valyala** [comment]
There are the following pssible reasons the discrepancy on the last screenshots:

* Prometheus may round values with big number of floating-point digits.
* VictoriaMetrics may accumulate floating-point errors during slightly different calculations.

Try the following workarounds:
* Replacing `irate` with `increase` in the original query in order to reduce the probability of accumulating floating-point errors during calculations.
* Wrapping the original query into `round(q, 0.01)`. This will limit the [floating-point errors](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems) to 2 decimal digits after the point.
* Explicitly setting `ymin` and `ymax` in Grafana dashboard settings.

**Comment by strobil** [comment]
Thanks for your help. Replacing `irate` with `increase` really helped for me.

`irate`
```
        "values": [
          [
            1594367625,
            "0.9999999999999998"
          ],
          [
            1594367640,
            "1"
          ],
          [
            1594367655,
            "0.9999999999999999"
          ],
          [
            1594367670,
            "1"
          ],
          [
            1594367685,
            "1.0000000000000002"
          ],
          [
            1594367700,
            "1.0000000000000002"
          ],
          [
            1594367715,
            "1.0000000000000002"
          ],
          [
            1594367730,
            "1.0000000000000002"
          ],
          [
            1594367745,
            "1.0000000000000002"
          ],
          [
            1594367760,
            "1.0000000000000002"
          ],
```
`increase`
```
"values": [
          [
            1594367625,
            "1"
          ],
          [
            1594367640,
            "1"
          ],
          [
            1594367655,
            "1"
          ],
          [
            1594367670,
            "1"
          ],
          [
            1594367685,
            "1"
          ],
          [
            1594367700,
            "1"
          ],
          [
            1594367715,
            "1"
          ],
          [
            1594367730,
            "1"
          ],
          [
            1594367745,
            "1"
          ],
          [
            1594367760,
            "1"
          ],
```
