### ISSUE TITLE
server doesn't respect maxConcurrentInserts env if it > count of cores

### ISSUE THREAD

**Issue by floppy-engineer** [VictoriaMetrics/VictoriaMetrics#632]
Hi,

Setting -maxConcurrentInserts with number more, than cores available does nothing.

**To Reproduce**
1. count you cores (lets say 8)
2. start victoriametrics with -maxConcurrentInserts=16
3. check the actual max cuncurent threshold via the metric vm_concurrent_addrows_capacity.
4. ensure that vm_concurrent_addrows_capacity=cores count not the env

**Expected behavior**
vm_concurrent_addrows_capacity should obey parameter settings

**Version**
victoria-metrics-20200708-173419-tags-v1.38.0-0-gb66c7c13a

Thanks in advance

**Comment by valyala** [comment]
VictoriaMetrics has two independent limits for data ingestion path:
* `-maxConcurrentInserts`, which limits the maximum number of concurrent inserts from remote clients into the database. This limit is exposed as `vm_concurrent_insert_capacity` metric. The current number of concurrent inserts is exposed as `vm_concurrent_insert_current` metric. There are also `vm_concurrent_insert_limit_reached_total` and `vm_concurrent_insert_limit_timeout_total` metrics, which may be useful for alerting.

* Internal limit on the number of concurrent calls to `Storage.AddRows` function. This limit is exposed as `vm_concurrent_addrows_capacity` metric. This limit equals to the number of available CPU cores.

@hagen1778 , I think we should update the official dashboard for Grafana - it should use `vm_concurrent_insert_*` metrics described above instead of `vm_concurrent_addrows_*` metrics in order to reduce confusion for users.

**Comment by hagen1778** [comment]
Closing as solved. Feel free to reopen if you still observe the issue
