### ISSUE TITLE
metricsql: ability to query value within and outside of range

### ISSUE THREAD

**Issue by thomas725** [VictoriaMetrics/VictoriaMetrics#6336]
### Is your question request related to a specific component?

Using the `prometheus/api/v1/query_range` endpoint

### Describe the question in detail

I can use `query=metric{label="value"}>6000` to get all the times+values where the metrics exceeds 6000.

I would like to also have a query filter that allows me to fetch times+values where the value of the metrics is between two values and also a filter for not between two values.

I found I can use `query=abs(metric{label="value"})>6000` to get the times for symetric "betweens" around zero, but that way the value looses the sign. Is there maybe a syntax that allows specifying a filter on one expression while outputting a different value for the same timestamp?

Or the most simple solution for this problem would be if there's someway to have multiple filter conditions and concatenate them with a logic AND.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hi @thomas725, In order to get the result when value is withing range you can use the following query:  `metric{label="value"} > X < Y`
See an example [here](https://play.victoriametrics.com/select/0/vmui/#/?g0.expr=vm_cache_entries%7Btype%3D%22multitenancy%2Ftenants%22%7D+%3E+0+%3C+2&g0.range_input=7m10s675ms&g0.end_input=2024-05-24T07%3A11%3A50&g0.tab=0&g0.relative_time=none&g0.tenantID=0).

In order to get the results when value is not within range you can use the following query: `metric{label="value"} < X or metric{label="value"} > Y`
See an example [here](https://play.victoriametrics.com/select/0/vmui/#/?g0.expr=%28vm_cache_entries%7Btype%3D%22indexdb%2FdataBlocks%22%7D+%3C+200%29+or+%28vm_cache_entries%7Btype%3D%22indexdb%2FdataBlocks%22%7D+%3E+800%29&g0.range_input=2m35s842ms&g0.end_input=2024-05-24T07%3A38%3A14&g0.tab=0&g0.relative_time=none&g0.tenantID=0&g0.step_input=1s)

**Comment by thomas725** [comment]
thank you, that's amazing! 🤩
Though it would be even better if there where a similar concise way to express the "outside range" as the "inside range" case 😉

**Comment by zekker6** [comment]
@thomas725 I've converted this issue into feature request regarding adding an ability to query the data within and outside specific range.

**Comment by thomas725** [comment]
thank you for the amazing support, even though I'm just using the open source version and am not a paying customer! You are absolutely amazing :)

Can I ask another question? Today I wanted to query for times where a metric's value was equal to 0. I've found I can workaround by using the syntax you've shown me to query for a small range around 0 - But I wonder if there is some syntax that queries for exact equality?

**Comment by zekker6** [comment]
@thomas725 You need to use `== 0` to compare the value. See [this for example](https://play.victoriametrics.com/select/0/vmui/#/?g0.expr=up+%3D%3D+0&g0.range_input=30m&g0.end_input=2024-05-30T07%3A27%3A08&g0.tab=0&g0.relative_time=last_30_minutes&g0.tenantID=0).
The list of all supported operators can be found [here](https://prometheus.io/docs/prometheus/latest/querying/operators/) as VictoriaMetrics' MetricsQL is a superset of PromQL.

**Comment by thomas725** [comment]
Thank you @zekker6, you are a great help for me! Also thanks for that documentation link!

Now for my next query I'm not sure if it's possible: I would like to find the start and end of events that are defined by a certain metric being 0 for the whole duration. They always take somewhere between 1 and 7 minutes. By querying for equality to zero I get very many data points (depending on the `steps` parameter) for each event. Can you think of some way to filter it to get just the first and last for each event?

For now all I've came up with was piping my output (where I produce a human readable date anyway) to `| sort | uniq --check-chars=14` to only output one line per hour, since this event usually happens once per day.

**Comment by zekker6** [comment]
@thomas725 I would suggest trying the following query: 
```
share_eq_over_time(fronius.power{type="watt",device="AC"}[1m], 0) == 1
```
This query uses [share_eq_over_time](https://docs.victoriametrics.com/metricsql/#share_eq_over_time) function which calculates share (in the range `[0...1]`) of [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) on the lookbehind window `1m`, which are equal to 0. You can also set step to 1m so that this query will produce less samples.
This query result will return `1` at timestamps where all values for `1m` before are 0.
See an example [here](https://play.victoriametrics.com/select/0/vmui/?#/?g0.expr=share_eq_over_time%28up%5B1m%5D%2C+1%29+%3D%3D+1&g0.range_input=30m&g0.end_input=2024-05-31T08%3A52%3A41&g0.tab=0&g0.relative_time=last_30_minutes&g0.tenantID=0&g0.step_input=1m).

**Comment by zekker6** [comment]
Closing as original question have been answered. Feel free to reopen if additional questions will appear.
