### ISSUE TITLE
VictoriaMetrics cannot use the alert list dashboard on Grafana?

### ISSUE THREAD

**Issue by Alexis-cmyk-a11y** [VictoriaMetrics/VictoriaMetrics#6341]
### Describe the question in detail

![Annotation 2024-05-24 155629](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/82816977/a5d7c582-4b44-4863-b6df-36a251e26ac2)
From the vmalert page, it appears that there is alarm information, but the list cannot be seen from the Grafana alert list dashboard
![Uploading Annotation 2024-05-24 161438.png…]()
May I ask if it is currently an alarm list that does not support Grafana?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
@Alexis-cmyk-a11y In order to enable alerts view in Grafana it is needed to configure `-vmalert.proxyURL` on [VictoriaMetrics single-node](https://docs.victoriametrics.com/single-server-victoriametrics/#vmalert) of [vmselect in VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#vmalert):
> -vmalert.proxyURL string
   Optional URL for proxying requests to vmalert. For example, if -vmalert.proxyURL=http://vmalert:8880 , then alerting API requests such as /api/v1/rules from Grafana will be proxied to http://vmalert:8880/api/v1/rules

Once this command-line flag will be configured Grafana will be able to fetch alerts list.

**Comment by Alexis-cmyk-a11y** [comment]
The problem has been resolved, thank you very much
