### ISSUE TITLE
Not seeing performance improvement with Victoria Metrics

### ISSUE THREAD

**Issue by HarshitaJha** [VictoriaMetrics/VictoriaMetrics#6361]
### Is your question request related to a specific component?

VMStorage, VMAgent, VMInsert

### Describe the question in detail

Hi. We are doing a POC to replace Prometheus in our existing setup with VictoriaMetrics. However, I am not seeing any performance improvement with VM. Is there something wrong with the way I have deployed VM? If so, please help me with this.

Currently we are testing with -
1. 2 shards and 2 replicas of vm-agent pod. 
Doubt here: Do we need replicas of vm-agent? If one vm-agent pod goes down, will vm-operator assign those targets to the other pod, or will those targets not get scraped till a new vm-agent pod comes up? If we can get rid of vm-agent replica without affecting functionality, that would be great. Each vmagent pod is taking about 10GB-11GB memory.

2. Two replicas each of all vm-select, vm-insert and vm-storage.  (replication factor is 2, deduplication flag has been added for vm-select and vm-storage)
3. 1 pod each for vm-alert, vm-alertmanager and vm-operator.
4. scrape interval is 1 minute
5. Have deployed vm-storage with emptyDir and it is taking upto 35GB memory

Description of test environment:
I am currently testing with there are more than 200 metrics present a namespace which has 75-80 pods. Also, there is a label, label_d, with cardinality of 3000. So, there are 200 metrics per pod, where each metric has the pod label (cardinality 75-80) and label_d with cardinality 3000. So, total number of of time series = 80*500*3000= 120,000,000
Apart from this there are other namespaces as well, which are pegging stats, but that is very low and does not have any high cardinality labels like this namespace. We are aware that we should not ideally have such cardinality labels, but it is necessary for our use case.  Also, there are record rules which are defined on top of the raw metrics.

Can someone please suggest how to best configure VM to support such load? At

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
Hey @HarshitaJha.

In brief (but be sure to read the "Related links"):
- Shards are needed if you have too [many scraping targets](https://docs.victoriametrics.com/vmagent/#scraping-big-number-of-targets) and have reached your vertical scaling limits. If you're migrating from a single Prometheus instance, you probably don't need sharding.
- If you really wish to achieve HA at the scraping level, then yes you need replication, but instead of cluster mode in vmagent you can just use [HA pair](https://docs.victoriametrics.com/vmagent/#high-availability) - two equally configured vmagent replicas + deduplication at the database level. This is exactly how replicaCount works for [vmagent in vm-operator](https://docs.victoriametrics.com/operator/resources/vmagent/#high-availability). But that's up to you, the vmagent load doesn't last that long, so maybe losing a couple of scrape intervals on restart isn't a big deal for you.
- It all depends on what you want to achieve. Did you choose a cluster because you really need HA and unlimited scalability? In this case, it's not fair to compare performance (with the same amount of resources) because you've chose other benefits (HA, replication, per-component scalability) instead. If you don't need it, you may prefer Single-version, it will work faster with the same resources, see more details in [this question](https://docs.victoriametrics.com/faq/#which-victoriametrics-type-is-recommended-for-use-in-production---single-node-or-cluster).
  I would also like to point out that in its current form your cluster (replicationFactor=2 with 2 vmstorages) will not be able to support HA correctly If one storage node is unavailable, there is  nowhere to reroute the second replica of the data (see [Replication and data safety](https://docs.victoriametrics.com/cluster-victoriametrics/#replication-and-data-safety), [Cluster availability](https://docs.victoriametrics.com/cluster-victoriametrics/#cluster-availability) and other related links).

For all other points I believe that you can find the answers in the attached "Related links".

Related links:
- vmagent:
  - [Scraping big number of targets](https://docs.victoriametrics.com/vmagent/#scraping-big-number-of-targets)
  - [vmagent High-Availability Examples](https://victoriametrics.com/blog/vmagent-high-availability-examples/)
  - [High availability (vmagent)](https://docs.victoriametrics.com/vmagent/#high-availability)
- vmcluster:
  - [Which VictoriaMetrics type is recommended for use in production - single-node or cluster?](https://docs.victoriametrics.com/faq/#which-victoriametrics-type-is-recommended-for-use-in-production---single-node-or-cluster)
  - [Cluster resizing and scalability](https://docs.victoriametrics.com/cluster-victoriametrics/#cluster-resizing-and-scalability)
  - [Capacity planning](https://docs.victoriametrics.com/cluster-victoriametrics/#capacity-planning)
  - [Understand your setup size](https://docs.victoriametrics.com/guides/understand-your-setup-size/)
  - [Replication and data safety](https://docs.victoriametrics.com/cluster-victoriametrics/#replication-and-data-safety)
  - [Cluster availability](https://docs.victoriametrics.com/cluster-victoriametrics/#cluster-availability)
  - [Slow data ingestion](https://docs.victoriametrics.com/troubleshooting/#slow-data-ingestion)
  - [Slow queries](https://docs.victoriametrics.com/troubleshooting/#slow-queries)
