### ISSUE TITLE
LogsQL queries with `|` fail to parse

### ISSUE THREAD

**Issue by zaphar** [VictoriaMetrics/VictoriaMetrics#6410]
### Describe the bug

I'm running `1.101.0` which I believe is the latest on a mac laptop to run it through it's paces. Everytime I try to query something with a pipe of any kind it gives an error message that it can't parse the query. Queries without a pipe seem to do just fine.

It's possible that you just don't support that part of logsql yet but your docs and roadmap aren't super clear on it.

### To Reproduce

Run victoria-logs version 1.101.0

```sh
$> curl http://localhost:9428/select/logsql/query -d 'query=error | limit 10'
remoteAddr: "127.0.0.1:50201"; requestURI: /select/logsql/query?query=error+%7C+limit+10; cannot parse query [error | limit 10]: unexpected tail: " limit 10"
```

### Version

```sh
$> victoria-logs --version
1.101.0
```

### Used command-line flags

-httpListenAddr="127.0.0.1:9428"
-storageDataPath="/path/to/data"

**Comment by zekker6** [comment]
Hello @zaphar 
Could you elaborate on how did you install VictoriaLogs?

[v1.101.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.101.0) is referring to a VictoriaMetrics release tag, not the VictoriaLogs. The latest release for VictoriaLogs is v0.17.0, you can find release binaries here - https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.17.0-victorialogs
Or use docker image - https://hub.docker.com/layers/victoriametrics/victoria-logs/v0.17.0-victorialogs/images/sha256-de9aa18937be52c51014be19f75b748fcfc2ee0c71faab32f7a4c4f445290086

Could you try v0.17.0 and see if the issue is still relevant?

**Comment by zaphar** [comment]
I'm building from source at that repo tag. Is there a tag I can target for that specific victoria-logs tag to test with? I much prefer building from source rather than using binaries.

**Comment by zaphar** [comment]
Okay, I found the correct tag for the latest version of the log daemon and the problem appears to be fixed there. Looks like I was just confused on how to get the latest version of the logs server. Thanks!
