### ISSUE TITLE
vmui page blank

### ISSUE THREAD

**Issue by surethink** [VictoriaMetrics/VictoriaMetrics#6422]
### Is your question request related to a specific component?

vmui

### Describe the question in detail

I have brew installed and opened the victoriametrics on macOS, and the scraping process is normal(scraps number is increasing)
but when I open http://localhost:8428/vmui/  the page is blank. 

victoria version is v1.101.0

ps: the network tab of chrome is like this
![1717598401250](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23416921/608914c2-9722-4e70-9858-54a6d57d9ab6)

http://localhost:8428/vmui/dashboards/index.js 200
http://localhost:8428/vmui/static/js/main.59c17910.js. 404
http://localhost:8428/vmui/static/css/main.d0b400e3.css 404

it says "You need to enable JavaScript to run this app.", but I never disabled JavaScript of chrome and other website works well. maybe what it mean is to enable JavaScript in victoriametrics, but I found no such command in the document

pls help me, is there anything I ignored? I have browsed the documents and github issues for hours

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @surethink 
This is caused by the release tag which did not contain a full update needed for VMUI. This was discussed [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6224) and fixed in [this](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/879170221ca0f254b00a319bc9e7852e593198b9) commit.
As a workaround I would suggest to get a release binary from the release page - https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.101.0 . These binaries were correctly built and include assets for VMUI.

**Comment by surethink** [comment]
Got it,thanks
