### ISSUE TITLE
Using Query from the beginning of the day

### ISSUE THREAD

**Issue by ZaytsevPavel8** [VictoriaMetrics/VictoriaMetrics#6485]
### Describe the question in detail

Is it possible to use Query to get counter data from the beginning of the day, rather than for a certain number of hours, without changing the time range?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
There is no shorthand way to do this using using promql or metricsql since they relay on [go duration](https://pkg.go.dev/maze.io/x/duration#section-readme) which only support static time ranges. There only ways I'm aware of doing this are
* setting the time window VMUI
* setting the time window in Grafana to "Today So Far"
* [not specifying a start time while using the query range api](https://docs.victoriametrics.com/url-examples/#apiv1series). Which will show data from 0:00UTC from the current day.
