### ISSUE TITLE
Add VM helm chart to https://github.com/helm/charts

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#65]

**Comment by valyala** [comment]
@tenmozes , could you look into this, since you are more familiar with helm charts.

**Comment by tenmozes** [comment]
sure will do

**Comment by byakku** [comment]
Any progress/plans @tenmozes ?

I just made a very basic and working deployment & service helm chart, I'm willing to add a PR so we can discuss there about how it should look later.

**Comment by valyala** [comment]
Just FYI, working helm chart already exists in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#helm). It should be adapted to https://github.com/helm/charts .

**Comment by byakku** [comment]
Oh nice! Do you plan to merge it to master or you just gonna keep it on charts repo later?

**Comment by valyala** [comment]
`master` branch contains code for single-node version of VictoriaMetrics, while `cluster` branch contains code for cluster version of VictoriaMetrics. Helm chart is intended for cluster version, so it is located in the `cluster` branch. There are no plans to move it to `master` branch.

We want moving the Helm chart for VictoriaMetrics cluster to https://github.com/helm/charts later.

**Comment by StianOvrevage** [comment]
In the mean time may I propose a "self-hosted" repo just using GitHub until it's officially in the `stable` repo (which may be a bit of work and waiting)?

It's probably many ways of doing it but a simple one is just using GH Pages: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

Would make it much easier adding VM as a standard helm component instead of manually cloning and keeping in sync with upstream manually.

**Comment by tenmozes** [comment]
Hi @StianOvrevage thank you for a link. I will take a look and create "self-hosted" repo.

**Comment by tenmozes** [comment]
@StianOvrevage repo is exist via https://github.com/VictoriaMetrics/helm-charts/
tomorrow i will add more docs,

**Comment by StianOvrevage** [comment]
Awesome! I will try it out tomorrow!
