### ISSUE TITLE
Suggested vmcluster configuration changes to allow for usage with high cardinality queries 

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#6605]
### Is your question request related to a specific component?

Victoriametrics, vmselect, vmstorage 

### Describe the question in detail

As much as users know to attempt to keep cardinality at a reasonable level, there are many cases where it's mostly unavoidable or even required.  For example (but not limited to): 

- collection of metrics from large kafka cluster with many topics and many partitions (multiple metrics per topic and partition)
- collection of metrics from a large elasticsearch cluster hosting many indices, each with potentially 2 to 3 shards (multiple mettics per index and potentially also for each shard of specific exporter flags enabled)
- collection of metrics from kubernetes clusters with hundreds or even 1000+ pods running at any given time, which also consequently is a major source of churn on a daily basis.
- collection of per-user metrics (where unique user count could easily exceed 1k) for compute job statistics in a high performance distributed job scheduler such as Slurm 
- prer-cpu metrics of hosts running in large distributed compute grids (some of these hosts are large and typically have 64+ cores

In cases such as these ones, the cardinality is necessary as it provides valuable context.  The minimum retention for each type of these metrics can vary, but can reach up to 12 months in some cases to allow for certain things such as historical trends snd forecasting.   Given this situation, which parameters should be modified in the vmstorage/vmselect components in order to allow the quries to run and as fast as possible?   I  realize that this will also come down to CPU and memory partially and that's acceptable given the query response times are fast.   What I'm more concerned about are issues I've observed when querying large datasets such as this one : 

`
the number of matching timeseries exceeds 300000; either narrow down the search or increase -search.max* command-line flag values at vmselect
`

I've already encountered this performing a benchmark with the prometheus-benchmark repo (with 1500+ unique endpoints configured) and I would like to avoid having similar issues if we decide to  migrate to Victoriametrics from Prometheus/Thanos.   Considering that Victoriametrics is typically reported to consume less resources than Prometheus+Thanos, or would be acceptable in my situation to have to significantly increase resources allocated to the vmcluster components given we can get the return in investment, which we consider primarily to be a substantial reduction in query execution time and few timeouts/errors when executing queries over longer periods (e.g.: 1 year)

Thanks for your help.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Thank you for your report and for explaining why high cardinality is common in queries.

> Given this situation, which parameters should be modified in the vmstorage/vmselect components in order to allow the quries to run and as fast as possible

The flags that need to be modified depend on the your use case. By default, cluster components of VictoriaMetrics are tuned for an optimal resource. And you could check this [doc: #resource-usage-limits](https://docs.victoriametrics.com/cluster-victoriametrics/#resource-usage-limits) to adjust your flags case by case.

> What I'm more concerned about are issues I've observed when querying large datasets such as this one: the number of matching timeseries exceeds 300000...

If I understand your question correctly, you are planning to query over 300k+ time series and consider it safe. In this case you can simply adjust the `search.maxUniqueTimeseries` flag to accommodate the higher number of time series.

However, please note that "**raising the default limits for these flags to allow querying high cardinality data**" may not happen quickly, as those flags are aim to protect user from wrongly estimated the resource usage and slow down the whole system.

Please let me know if I am not addressing your question correctly.

**Comment by hagen1778** [comment]
> In cases such as these ones, the cardinality is necessary as it provides valuable context.

The sources of cardinality are infinite. The question is usually whether the user needs that context. For example, the highest cardinality is usually generated by histograms, because each histogram can be configured with arbitrary number of buckets. This is true even for our playground:
<img width="1336" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/8bd0a334-c30d-4639-b829-ebb389413942">
<img width="1342" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/1a5dfa97-16dd-450f-8dda-f68be87e08cd">
> See source [here](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality) 

But users don't plot those 14k series on the dashboards. Instead, users usually do `historgram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket)) by(path, le))` to see the 0.99 percentile latency per-path which would produce about 10 series in result. Ideal case to fight the cardinality would be to calculate these aggregates without affecting database capabilities, and this is what [stream aggregation](https://docs.victoriametrics.com/stream-aggregation/) should help with. You can read more about techniques to fight the data complexity [here](https://victoriametrics.com/blog/reducing-costs-p2/).

However, this wasn't the original question. So I'd think that you actually need that context and cardinality. In this case, the query performance over data with high-cardinality will depend on the following params:
**1. The amount of memory available on storage nodes.** Enough mem capacity helps to retain in memory index entries and caches to speed up data lookup from disk. If memory isn't enough, vmstorage will have to do more disk seeks slowing down the response.
**2. The amount of CPU on storage nodes.** Enough CPU helps to ingest, select, merge and optimize data on the disk. If CPUs are saturated, vmstorage may start to de-prioritize select queries in order to retain its ingestion capabilities.
**3. The disk bandwidth on storage nodes.** After the metrics selector returned the names of data blocks that had to be read from disk, the query performance start to depend on how fast vmstorage can read it from disk. Since time series are supposed to be sequential, the data layout on disk is optimized for sequential read. High churn rate would mean that reading from disk will require more seek operations, because distinct time series are stored in distinct data blocks. In other words, reading 1 Bil of data samples that belong to one distinct series is faster than reading 1Bil samples that are distributed across 1 Mil distinct series. The faster are disks, the faster vmstorage can read the requested data.
**4. Resources on vmselect.** Since vmselect acts as a query frontend, it is responsible for receiving data blocks from vmstorage, unpacking data blocks and processing received series. The speed of unpacking will depend on the amount of CPU resources. 

Based on the above, there is no a setting to deal with high cardinality and churn rate. In the end, it is all about resources that can be dedicated to the task. The more resource you have, the faster query will be. [Troubleshooting guide](https://docs.victoriametrics.com/troubleshooting/#slow-queries) and [VictoriaMetrics dashboards ](https://docs.victoriametrics.com/#monitoring) will help to determine the bottleneck.

> What I'm more concerned about are issues I've observed when querying large datasets such as this one: the number of matching timeseries exceeds 300000...

As @jiekun mentioned, all the [complexity limits](https://docs.victoriametrics.com/#resource-usage-limits) are there to protect the user and database from malformed query. Otherwise, user could execute something like `{__name__!=""}` and this will make database read terabytes of data and crash Grafana in the end. So limits are just sanity checkers, and if you know what you're doing feel free to set it to appropriate values.

**Comment by hartfordfive** [comment]
Thank you @hagen1778 for the detailed response.   One of the concerns I have is that I observed that warning messages in my initial post while attempting to run a query that vmalert is executing in the prometheus-benchmark suite:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3722736/2216853d-0689-463b-854e-be9104a4082d)

For reference, I have set the [targetsCount](https://github.com/VictoriaMetrics/prometheus-benchmark/blob/main/chart/values.yaml#L13) value to 1500.   It seems odd to me that I would encounter this issue while running a simple benchmark.   I initially had this at 3000 although I had to lower it gradually as the vmagent pod was constantly getting OOM killed.

**Comment by hagen1778** [comment]
>  One of the concerns I have is that I observed that warning messages in my initial post while attempting to run a query that vmalert is executing in the prometheus-benchmark suite

I think that's ok. The benchmark writes only nodeexporter metrics, and default rules query nodeexporter metrics. So the higher is `targetsCount`, the higher will be cardinality for series touched by the alerting query. We could try setting the rly high default limits for benchmark only, though.

> For reference, I have set the [targetsCount](https://github.com/VictoriaMetrics/prometheus-benchmark/blob/main/chart/values.yaml#L13) value to 1500. It seems odd to me that I would encounter this issue while running a simple benchmark. I initially had this at 3000 although I had to lower it gradually as the vmagent pod was constantly getting OOM killed.

This is unexpected. We run this benchmark to feed [the playground](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1). The settings of this benchmark are the following:
```
helm:
      valuesObject:
        vmtag: "v1.102.0-rc2"
        targetsCount: 2000
        scrapeInterval: 10s
        queryInterval: 10s
        scrapeConfigUpdatePercent: 1
        scrapeConfigUpdateInterval: 10m
        writeConcurrency: 16
        remoteStorages: ...
```

Here's what dashboard for vmagent that generates the load shows:
<img width="1347" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/1d41bbbf-7297-415c-b60c-53d0b54316fa">

> You can explore it yourself here https://play-grafana.victoriametrics.com/d/G7Z9GzMGz_vm/victoriametrics-vmagent-vm

According to these stats, vmagent needs 1.3 vCPU and 200MiB of mem to scrape 2k targets with 10s scrape interval.

**Comment by hagen1778** [comment]
Closing as answered.
