### ISSUE TITLE
streaming aggregation (i.e., interval:1d)

### ISSUE THREAD

**Issue by smallyao** [VictoriaMetrics/VictoriaMetrics#6656]
### Is your question request related to a specific component?

victoriametrics, vmagent

### Describe the question in detail

Assuming there is a data write rate of 1 million entries per second into VictoriaMetrics, due to the large volume of data, I am considering using the streaming aggregation function. If I want to calculate the maximum, minimum, and average values of these metrics on a daily basis (i.e., interval:1d), what would happen? Does this mean that the aggregation operation will only be triggered after the data has been retained for one day? With 1 million entries per second, over the course of one day, that amounts to 100 million * 3600 * 24 entries. Are these data stored in memory or on disk? How does VictoriaMetrics handle this situation?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @smallyao 
>  Does this mean that the aggregation operation will only be triggered after the data has been retained for one day?

Data will be flushed once per configured `interval`. This means that in order to receive the result vmagent neeeds to be running for `interval` amount of time.
It is also possible to enable `flush_on_shutdown` option of an [aggregation configuration](https://docs.victoriametrics.com/stream-aggregation/#stream-aggregation-config), so that vmagent will flush an aggregation state before the shutdown.
There is an open feature request regarding adding persistence support so that vmagent will be able to resume aggregation after a restart - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3775

>With 1 million entries per second, over the course of one day, that amounts to 100 million * 3600 * 24 entries. Are these data stored in memory or on disk? How does VictoriaMetrics handle this situation?

The processing itself is done in a streaming manner: vmagent keeps aggregation states in memory in order to calculate a min/max/average values. Aggregation state represents a minimal amount of information which is needed for calculation.
For example, for minimal value calculation it only needs to keep the lowest value, for max it will be the max value.

**Comment by smallyao** [comment]
@zekker6
Thanks for your prompt reply

**Comment by smallyao** [comment]
If I want to perform aggregation at multiple time intervals, such as 5 minutes , 1 hour , and 1 day , on the data received by vmagent, how should I configure it? Is it possible to aggregate data received by just one vmagent into various intervals? Or is it necessary to set up multiple vmagents, each handling aggregation for different time intervals?

**Comment by zekker6** [comment]
@smallyao You need to define multiple aggregation rules with different intervals. For example:
```
- interval: 30s
  outputs: [last,avg,max,min]
  match: '{__name__=~"go.*"}'
- interval: 1m
  outputs: [last,avg,max,min]
  match: '{__name__=~"go.*"}'
```

The only difference is `interval`, metrics will be aggregated for each interval separately.

**Comment by smallyao** [comment]
@zekker6 
Thanks a lot.
