### ISSUE TITLE
VMAgent in-memory data buffering with -remoteWrite.disableOnDiskQueue=true

### ISSUE THREAD

**Issue by cah-rita-kassar** [VictoriaMetrics/VictoriaMetrics#6658]
### Describe the question in detail

We have vmagent up and running on our devices, sending metrics via remote write to VictoriaMetrics with the following configuration parameters:
-	remoteWrite.tmpDataPath=<remote_write_dir>
-	remoteWrite.maxDiskUsagePerURL=1
-	memory.allowedPercent=5
-	remoteWrite.relabelConfig <relabel_config.yml>
-	remoteWrite.url=<remote_write_url>
-	remoteWrite.label=instance=<instance_label>
-	remoteWrite.basicAuth.username=<username>
-	remoteWrite.basicAuth.passwordFile=<password_file>
-	remoteWrite.proxyURL=<proxy_url>

After upgrading vmagent from version 1.87.6 to 1.101.0, we added the following flag "--remoteWrite.disableOnDiskQueue=true" in the vmagent configuration to disable data buffering in case of network cutoffs.
We then disconnected our device (with vmagent up and running) and after restoring the network connection, we were expecting a gap in the metrics on Grafana from the moment the network was cut to the moment the connection was restored. However, we received metrics for the first 30mins after the network disconnection, suggesting there is some in-memory data buffering for the first 30min of a network disconnection.

How is the in-memory data sent after the network is restored?
What would be the behavior of VictoriaMetrics and VMAgent if multiple devices were to report 30mins of buffered metrics at the same time, in a way that the server could not handle the load?
And finally, is there a way to disable this in-memory buffering as well?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @cah-rita-kassar
`vmagent` uses the following logic to calculate amount of data to be stored in memory:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/db557b86ee483a6dea726f6021afe1755737a865/app/vmagent/remotewrite/remotewrite.go#L302-L311

Where `queues` is controlled by `remoteWrite.queues`  and equal to `CPU_CORES*2` by default.

To be more specific, it splits amount of memory which is available to `vmagent` (as per `memory.allowedPercent`) between all remote write URLs and number of queues per URL. There is also lower bound limit of in-memory blocks which is `2`.

> How is the in-memory data sent after the network is restored? What would be the behavior of VictoriaMetrics and VMAgent if multiple devices were to report 30mins of buffered metrics at the same time, in a way that the server could not handle the load?

`vmagent` will try to push the data without any limits in terms of amount of requests or bandwidth. If the remote target will not be able to keep up and will not acknowledge that data was successfully saved vmagent will retry the request with an exponential backoff.
It is also possible to limit bandwidth to use when writing metrics by using the following command-line flag:
```
  -remoteWrite.rateLimit array
     Optional rate limit in bytes per second for data sent to the corresponding -remoteWrite.url. By default, the rate limit is disabled. It can be useful for limiting load on remote storage when big amounts of buffered data is sent after temporary unavailability of the remote storage. See also -maxIngestionRate (default 0)
     Supports array of values separated by comma or specified via multiple flags.
     Empty values are set to default value.
```

>  And finally, is there a way to disable this in-memory buffering as well?

It is not possible to disable in-memory buffer completely. The only option is to lower amount of memory available to vmagent so that it will keep fewer data blocks in memory as a buffer.

**Comment by cah-rita-kassar** [comment]
@zekker6 Thank you!
