### ISSUE TITLE
VictoriaLogs uses the stream_context function added in 0.26.0 to query data, prompting an error: cannot calculate [stream_context before 1], since it requires more than 285MB of memory

### ISSUE THREAD

**Issue by zoutao0909** [VictoriaMetrics/VictoriaMetrics#6730]
### Is your question request related to a specific component?

VictoriaLogs uses the stream_context function added in 0.26.0 to query data, prompting an error: cannot calculate [stream_context before 1], since it requires more than 285MB of memory

### Describe the question in detail

VictoriaLogs version used: 0.28.0 
Request: `curl http://localhost:9248/select/logsql/query -d 'query=SERVER | stream_context before 1 after 0 | limit 2 ' `
Response: `remoteAddr: "127.0.0.1:56836 "; requestURI: /select/logsql/query?query=SERVER+%7C+stream_context+before+1+after+0+%7C+limit+2+; cannot execute query [SERVER | stream_context before 1 | limit 2]: cannot calculate [stream_context before 1], since it requires more than 285MB of memory`

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. I could reproduce it when setting memory limit like `-memory.allowedBytes=102400`. So typically it means the query require more memory resource than available.

**Comment by zoutao0909** [comment]
> Hi. I could reproduce it when setting memory limit like `-memory.allowedBytes=102400`. So typically it means the query require more memory resource than available.

Hello, can I understand that if I need to use the stream_context function, I must set up sufficient memory? However, in actual use, my memory resources must be limited. In my scenario, the disk space occupied by the data is currently only 4.5G, and the memory is given as 2G. At this time, this function can no longer be used. I think the stream_context function is a very practical function, but the available scenarios of the stream_context function are too demanding. As a result, it is almost unusable in real scenarios. I hope it can be optimized.

**Comment by valyala** [comment]
@zoutao0909 , the commit 4b1611267f9baf100fed3efbe60e96d57ec309f2 should reduce memory usage when using [`stream_context` pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stream_context-pipe) over [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) with big number of log entries. This commit will be included in the next release. In the mean time you can build VictoriaLogs from this commit according to [these instructions](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code) and verify whether this helps reducing memory usage in your case.

General recommendation: `stream_context` pipe needs to scan all the log messages in the [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) with the found log lines, in order to find the contextual lines. This means that `stream_context` pipe can be slow when working on log streams with tens of millions of log entries. The performance of `stream_context` pipe may be improved a bit by limiting log lines, which needs to be selected, with [`fields` pipe](https://docs.victoriametrics.com/victorialogs/logsql/#fields-pipe). For example, the following query selects only `_time`, `_msg` and `_stream` fields, so it should be executed faster than the same query without the `fields` pipe:

```logsql
panic | stream_context after 100 | fields _time, _stream, _msg
```

**Comment by valyala** [comment]
VictoriaLogs should use much lower amounts of RAM and CPU when processing `stream_context` pipes over log streams with many log entries starting from the release [v0.30.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).

Closing this issue as fixed then.
