### ISSUE TITLE
Don't add default scrape port

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6792]
### Is your feature request related to a problem? Please describe

VictoriaMetrics single-node and vmagent will automatically add :80 for HTTP or :443 port for HTTPS targets during scraping. 
However, this is usually not needed and instead may lead to connectivity issues when targets are exposed via proxy.

See similar change in Prometheus - https://github.com/prometheus/prometheus/issues/13959

### Describe the solution you'd like

Do not add default ports to scrape targets unless the`__address__` meta label contains the address with port.

**Comment by valyala** [comment]
The issue is that the port is automatically added to scrape url if it is missing there. This port shouldn't be added there, while the port should be still added to `__address__` label if this label contains just the hostname without the port. In this case the fix won't lead to new time series after the upgrade of `vmagent`, since the `instance` label shouldn't change.

**Comment by valyala** [comment]
@jiekun , could you return back adding the missing port to `__address__` label, while skipping the automatic addition of the missing port to the scrape url?

**Comment by jiekun** [comment]
Sure. I will take a look.

**Comment by jiekun** [comment]
> ould you return back adding the missing port to __address__ label, while skipping the automatic addition of the missing port to the scrape url

Aha this is what I want to discuss in the original pull request. I am fixing it and it should be included in this week's release.

**Comment by hagen1778** [comment]
This change was included into [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030) release.
