### ISSUE TITLE
scrape_series_added equivalent metric for vmagent

### ISSUE THREAD

**Issue by blakebarnett** [VictoriaMetrics/VictoriaMetrics#683]
**Is your feature request related to a problem? Please describe.**
The `scrape_series_added` metric in prometheus since v2.10 is very help for tracking down misbehaving applications, the instance or kubernetes app labels are added which makes it trivial to attribute spikes in new series to the culprit.

**Describe the solution you'd like**
It would be great to have the same or an equivalent metric provided by vmagent.

**Describe alternatives you've considered**
I looked through all the metrics vmagent provides and couldn't find something equivalent.

**Comment by valyala** [comment]
The commit 23c9e6b727cc75e9c9bbd6cc50fb33efbb88f1ec adds per-target `scrape_series_added` metric similar to the metric exported by Prometheus. It returns non-zero value if target scrape collects new metrics comparing to the previous scrape for this target. Note that it returns non-zero values during the first scrape for each target after `vmagent` restart, since the were no the previous scrapes yet.

@blakebarnett , could you build `vmagent` from the commit 23c9e6b727cc75e9c9bbd6cc50fb33efbb88f1ec and verify whether it generates correct values for `scrape_series_added` metric? See build instructions for vmagent - https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources

**Comment by valyala** [comment]
`vmagent` exports `scrape_series_added` metric starting from [v1.39.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done. @blakebarnett , feel free re-opening the issue if the exported metric doesn't work as expected.

**Comment by blakebarnett** [comment]
Thanks for the awesome turn-around on this!
