### ISSUE TITLE
High Cardinality Concerns with Logging File Paths

### ISSUE THREAD

**Issue by s5unty** [VictoriaMetrics/VictoriaMetrics#6838]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I’m an amateur seeking advice on a technical issue. I’m considering including the log filename (including its absolute path) as a field in a logging stream. However, I’m concerned about potential high cardinality problems.

Here’s the scenario: some log filenames change daily (with a date suffix %d), and the file paths also change monthly (organized by year, month, and day). With either 10,000 or even just 100 virtual machine instances, each having 100 such log files, would it be appropriate to include the log filename (with its absolute path) as one of the fields in the stream?

I appreciate any insights or advice you can provide.

Thank you!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
it would be ok to log the absolute path of a message but it should not be set as stream field in this case since it doesn't remain consistent over the lifetime of the application. Only stream fields are indexed and contribute to cardinality. There more details in the documentation. https://docs.victoriametrics.com/victorialogs/keyconcepts/#how-to-determine-which-fields-must-be-associated-with-log-streams 

If you are logging to a file in an environment centralized loggigng setup you can setup a static log file with a log rotate and only keep a couple versions of the file since long term storage and searching based on a date range is handled by the centralized logging system. In the case it will be acceptable to use the path as stream field since it remains consistent.
