### ISSUE TITLE
vmagent support blackbox_exporter  like  exporter  metrics  process

### ISSUE THREAD

**Issue by rongfengliang** [VictoriaMetrics/VictoriaMetrics#684]
*  yaml config

> one blackbox_exporter static scrape config,current test with latest vmagent not works 

```code
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [dns_udp_example]  # Look for  dns response
    static_configs:
      - targets:
        - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: black:9115  # The blackbox exporter's real hostname:port.% 
```

**Comment by valyala** [comment]
@rongfengliang , could you provide the output of `http://vmagent:8428/targets` page after a few minutes `vmagent` starts? It would be great also to see error logs for vmagent when it scrapes the blackbox exporter. It is assumed that `vmagent` runs without `-promscrape.suppressScrapeErrors` command-line flag.

**Comment by rongfengliang** [comment]
@valyala  so sorry i do some test with docker-compose   it works,  and the vmagent targets  also right ,i will do more test for virtual machine  vmagent , thanks !

**Comment by rongfengliang** [comment]
@valyala  all test works ,it's my fault

**Comment by r0fls** [comment]
@rongfengliang @valyala can either of you provide more documentation or information on configuring this? I'm coming from this helm chart which looks @ it doesn't work with VictoriaMetrics, since it relies on the coreos prometheus operator: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml#L224-L231
