### ISSUE TITLE
vmselect support different strategy to query multi cluster

### ISSUE THREAD

**Issue by leiwingqueen** [VictoriaMetrics/VictoriaMetrics#6907]
### Is your feature request related to a problem? Please describe

The size of time series data is too large, and the query performance is poor. So I want to split the data into two cluster. one cluster's retention is 7 days and the other one is 6 months. 

vmselect query data from two cluster depend on the query range. I expect that vmselect query recently 7 days time series data from the 7 days retention cluster, and query the other data from the 6 months retention cluster.

I am not sure that this solution will help

### Describe the solution you'd like

vmselect support different strategy to query multi cluster.

**Comment by zekker6** [comment]
Before splitting the cluster I would suggest going over troubleshooting checklist for slow queries - https://docs.victoriametrics.com/troubleshooting/#slow-queries
This will help to identify a bottleneck and decide if splitting clusters will help to address that.

**Comment by nemobis** [comment]
In this scenario, how do metrics get to the second cluster? Do you just ingest everything twice? Unless vmselect heavily dominates resource usage in your cluster, doubling the ingestion would probably cause a significant cost increase. If slow queries become intractable despite the troubleshooting steps linked above, [downsampling](https://docs.victoriametrics.com/cluster-victoriametrics/#downsampling) may be a more straightforward solution, to have your longer-term storage in place.

Otherwise, one option is to use something like [promxy](https://github.com/jacksontj/promxy) (or vmselect itself) in front of vmselect. For example, if you have metrics scraped by Prometheus and remote-written to VictoriaMetrics, you could set promxy with `relative_time_range` to query Prometheus for the last 7 days and VictoriaMetrics for the older metrics. Then if you only care about making the recent queries fast you can focus on that (e.g. just throw more memory at Prometheus).

**Comment by leiwingqueen** [comment]
> In this scenario, how do metrics get to the second cluster? Do you just ingest everything twice? Unless vmselect heavily dominates resource usage in your cluster, doubling the ingestion would probably cause a significant cost increase. If slow queries become intractable despite the troubleshooting steps linked above, [downsampling](https://docs.victoriametrics.com/cluster-victoriametrics/#downsampling) may be a more straightforward solution, to have your longer-term storage in place.
> 
> Otherwise, one option is to use something like [promxy](https://github.com/jacksontj/promxy) (or vmselect itself) in front of vmselect. For example, if you have metrics scraped by Prometheus and remote-written to VictoriaMetrics, you could set promxy with `relative_time_range` to query Prometheus for the last 7 days and VictoriaMetrics for the older metrics. Then if you only care about making the recent queries fast you can focus on that (e.g. just throw more memory at Prometheus). (I used to do this, but in the end it was easier to route all queries to a single VictoriaMetrics cluster and just tweak its settings so that queries would always be reasonably fast.)

thanks for your suggestion. It's reasonable for me to use promxy and downsampling is a great feature for me to do that

**Comment by leiwingqueen** [comment]
> Before splitting the cluster I would suggest going over troubleshooting checklist for slow queries - https://docs.victoriametrics.com/troubleshooting/#slow-queries This will help to identify a bottleneck and decide if splitting clusters will help to address that.

Copy that. The main purpose  of split cluster is that I care about the recent queries's cost time. So maybe downsampling and promxy is a good solution for me.
