### ISSUE TITLE
rate() burst when there are missing data

### ISSUE THREAD

**Issue by joejoe2** [VictoriaMetrics/VictoriaMetrics#6916]
### Describe the bug

<img width="955" alt="image" src="https://github.com/user-attachments/assets/3b402b45-235a-4052-bfd9-7375eb93bed9">
When there are some missing data points, we get an extremely high burst with the rate() function.
<img width="960" alt="image" src="https://github.com/user-attachments/assets/56456843-a22a-43b4-b6b8-6ced103d09f0">

### To Reproduce

I do not know really, it does not happen on every data missing range.

### Version

  single node ver 101.0

**Comment by Haleygo** [comment]
Hi,
Could you share raw samples of the metric using [export API](https://docs.victoriametrics.com/url-examples/#apiv1export)?

**Comment by joejoe2** [comment]
Here is the raw data. Besides if I use irate it will spike serverely on the latest part.
[raw.txt](https://github.com/user-attachments/files/16844893/raw.txt)

**Comment by joejoe2** [comment]
<img width="917" alt="image" src="https://github.com/user-attachments/assets/acb5c8df-5004-4ed8-927d-435618b3dbfe">

Additional: irate() will spike serverely on the latest part.

**Comment by Haleygo** [comment]
Hi @joejoe2 ,
I exported your data, and the sample timestamps look interesting. Here are some of the sample timestamps:
```
2024-09-03T08:25:12.425
2024-09-03T08:25:13.089
2024-09-03T08:30:18.645
2024-09-03T08:30:19.263
2024-09-03T08:35:15.912
2024-09-03T08:35:16.533
2024-09-03T08:40:17.485
2024-09-03T08:40:18.104
2024-09-03T08:45:33.513
2024-09-03T08:45:34.196
2024-09-03T08:50:33.419        172004101095150112
2024-09-03T08:50:34.037        172004135179413504
2024-09-03T08:55:30.179        172004653664730752
2024-09-03T08:55:30.866        172004685891745120
```
I assume the target is scraped by two agents with `scrape_interval: 5m`, resulting in sample intervals of `~1s` sometimes and `~5min` at other times. Also the metric value changes rapidly even within 1s.

Since you didn't specify a lookbehind window in [rate](https://docs.victoriametrics.com/metricsql/#rate), VM automatically calculates the window as `max(step, scrape_interval)`, where step is the query arg value passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyconcepts/#range-query), while scrape_interval is the interval between [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for the selected time series.
VM calculates the scrape_interval based on 20 samples if I remember correctly, resulting in a value of `<5m` according to your samples. And the pannel you posted above has `step: 25s`. So the lookbehind window for `rate()` will be `<5m` which is less than the `scrape_interval`. It's not good because you won't have enough data points for rate calculations sometimes.
You can fix this in two ways:
1. Add a lookbehind window inside your query like `rate(bytes-sent[10m])`, to ensure there are enough datapoints to calculates the average. See compared results below:
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/4c2af782-741d-4588-8e49-a8b66220cd3e">
2. Set flag `-dedup.minScrapeInterval=5m` on vmselect or vmsingle if you're running single node version. It leaves only the last sample for this metrics every 5m. It can help increasing the auto `scrape_interval` result, and gives better results.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/897d6347-6d94-483f-8c45-8e6811d01208">

**Comment by Haleygo** [comment]
I believe `irate()`  is not what you need, see the difference between `rate()` and `irate()` [here](https://valyala.medium.com/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832).

**Comment by joejoe2** [comment]
@Haleygo 
Thank ypou very much ! 
You are right, I verified the raw data. There are several short intervals and large value spikes.

I have another question about `-dedup.minScrapeInterval=5m`. Does the `every 5m` means the every 0:00, 0:05, 0:10, ... ?

**Comment by Haleygo** [comment]
It's not strictly aligned to 00:00, but only ensure single [raw sample](https://docs.victoriametrics.com/keyconcepts/#raw-samples) with the biggest [timestamp](https://en.wikipedia.org/wiki/Unix_time) for each [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) per each -dedup.minScrapeInterval discrete interval.
Normally, agent should scrape the target periodically. Even if there are multiple agents, and they scrape the target at different time, one agent should always has largest timestamps and pushes samples to VM, ensuring that `-dedup.minScrapeInterval` retains samples from that agent.
OFC, it's ok to mix data from multiple agent sources, as long as they're all correct.

I'd also recommend to check if your agent is overloaded and fix if it's, as the timestamp intevals are always fluctuating.

And please note, `-dedup.minScrapeInterval=5m` applies to all the metrics. If other metrics have smaller intervals, you shouldn't set it. It's better to add specific lookbehind window inside your query like `rate(bytes-sent[10m])`.

**Comment by Haleygo** [comment]
It is recommended to use at least `2*scrapeInterval` as the rate() window, as there is no much sense to calculate average for a single point. 
Regarding `step`, you don't need to worry about it if you specify the window; if you're using Grafana, it will automatically adjust the step according to the resolution.
