### ISSUE TITLE
cannot find tag filter matching less than 300001 time series

### ISSUE THREAD

**Issue by seanlook** [VictoriaMetrics/VictoriaMetrics#697]
**Describe the bug**
When I upgrade from v1.28.0 to v1.39.2, my history data cannot be accessed.
```
error when executing query=\"max_over_time(sum(metricxx.value{app=\\\"198\\\",zone=~\\\"2\\\"}[5m]) by (zone))\" on the time range (start=1595950200000, end=1595951700000, step=300000): cannot execute query: cannot evaluate \"max_over_time(sum(metricxx.value{app=\\\"198\\\", zone=~\\\"2\\\"}[5m]) by (zone))\": search error after reading 0 data blocks: error when searching tsids for tfss [\"{__name__=\\\"metricxx.value\\\", app=\\\"198\\\", zone=\\\"2\\\"}\"]: cannot find tag filter matching less than 300001 time series; either increase -search.maxUniqueTimeseries or use more specific tag filters
```

The time range is 30mins.

I've ran `curl -g 'http://localhost:8428/api/v1/series?' --data-urlencode 'match[]=metricxx.value{app="198",zone=~"2"}' >a` to get series number that is 8439, far smaller than 3000001.

Only the metrics that has much series have this issue, but not much than 300001

**To Reproduce**
I'm not sure the upgrade action leads to this. 

**Expected behavior**

**Screenshots**

**Version**
```
old:
victoria-metrics-20191009-135323-tags-v1.28.0-0-gf6334bff

current run:(upgraded)
victoria-metrics-20200730-173321-tags-v1.39.2-0-ge7959094f
```

**Used command-line flags**
```
victoriametrics -storageDataPath=/data1/victoriametrics -retentionPeriod=12 -httpListenAddr=:8428 -opentsdbHTTPListenAddr=:4242 -selfScrapeInterval=10s
```

**Comment by valyala** [comment]
The issue looks like a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/290 . The workaround is to wait for a day - and the history data should become visible again.

**Comment by valyala** [comment]
> I've ran curl -g 'http://localhost:8428/api/v1/series?' --data-urlencode 'match[]=metricxx.value{app="198",zone=~"2"}' >a to get series number that is 8439, far smaller than 3000001.

The `-search.maxUniqueTimeseries` limit is applied individually per each label filter in the query. For instance, the query `metricxx.value{app="198",zone=~"2"}` contains three filters: `{__name__="metricxx.value"}`, `{app="198"}` and `{zone=~"2"}`. VictoriaMetrics tries to find the filter for the query that matches the minimum number of time series before intersecting it with the rest of filters. If all the filters match more than `-search.maxUniqueTimeseries` time series, then the error is returned. The solution against this issue is to increase `-search.maxUniqueTimeseries` command-line flag value or to add more specific label filter to the query that matches lower number of time series than `-search.maxUniqueTimeseries`.

As for your case, it looks like it is related to the upgrade bug mentioned above - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/290 . Just wait for a day and then verify whether the `cannot find tag filter matching less than 300001 time series` error disappears.

**Comment by TenDBCluster** [comment]
I do upgrade in 2020-08-03, and this issue never disapper even today. I set `-search.maxUniqueTimeseries` to 1000000 to solve this issue. 

I'm curious that does `-search.maxUniqueTimeseries` filter by time range? In fact my range-query above has condition `start=1595951400&end=1595951700&step=300` that has time range `6m`.
The same time range `6m` appied to data before upgrade has the `xxx time series` issue, but ok in today's data.

**Comment by seanlook** [comment]
I do upgrade in 2020-08-03, and this issue never disapper even today. I set -search.maxUniqueTimeseries to 1000000 to solve this issue.

I'm curious that does -search.maxUniqueTimeseries filter by time range? In fact my range-query above has condition start=1595951400&end=1595951700&step=300 that has time range 6m.
The same time range 6m appied to data before upgrade has the xxx time series issue, but ok in today's data.

**Comment by valyala** [comment]
> I'm curious that does -search.maxUniqueTimeseries filter by time range?

The `-search.maxUniqueTimeseries` is applied to time range, but with per-day granularity.

Closing the issue as duplicate for #290 .
