### ISSUE TITLE
Function limit_offset not preserve the order of the timeseries.

### ISSUE THREAD

**Issue by githubsach** [VictoriaMetrics/VictoriaMetrics#7068]
### Describe the bug

Hi @valyala, 

**issue**
its preserve the order if sort by value, but if use the sort_by_label_numeric it breaks.
Observed on latest version 1.102.0

**workaround**:
sorting again on returned series by limit_offset

Thanks! 

### To Reproduce

sorted=sort_by_label_numeric(s1,"label1"),
p=limit_offset(10,0,sorted),

### Version

v1.102.0

**Comment by githubsach** [comment]
Hi @valyala ,

its related to the issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1920

**Comment by AndrewChubatiuk** [comment]
this issue is related to a way how default sorting in vmselect works
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/24b6e117dd857044725600a8933c9169d5ff061f/app/vmselect/promql/exec.go#L107
possible solutions:
 - add `limit_offset` and similar functions to ignore list of maySortResults crutch function
 - add `Sorted` method to metricsql.Expr interface and add implementation to each expr implementation to decide if sorting is needed
 - leave it for a user to decide and add query param and add a toggle on UI, which enables/disables sorting by metric name

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7402 has been merged and will be included into the next release.

**Comment by f41gh7** [comment]
The bugfix was included into [v1.106.1](https://docs.victoriametrics.com/changelog/#v11061)
