### ISSUE TITLE
VictoriaLogs analytical query performance

### ISSUE THREAD

**Issue by Andrey36652** [VictoriaMetrics/VictoriaMetrics#7070]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

Hello, I deployed single node VictoriaLogs v0.29.0 on k8s cluster using Helm.
It has been working for approximately 6 days and accumulated 1.96 bil of records. Disk usage is 12.4 GiB at this point. 205 streams.
Now I'm executing this query against VictoriaLogs
```
* | stats by (_stream) min(_time) as earliest_time | sort by (earliest_time) | limit 20 | fields _stream, earliest_time
```
and it takes approximately 1.5 minutes to complete.
resources for VictoriaLogs pod:
```yaml
  resources:
    requests:   
      cpu: 200m
      memory: 400Mi
    limits:
      cpu: 1000m
      memory: 1Gi
```
Metrics for VictoriaLogs resource utilization during multiple executions of the query (last one is in fact 3 merged executions because of scroll in VictoriaLogs datasource in Grafana).
![image](https://github.com/user-attachments/assets/efb5da7d-1e6b-4f39-b33b-8db5ea50771c)
RSS Memory % usage
```
max(max_over_time(process_resident_memory_bytes{job=~"$job", instance=~"$instance"}[$__rate_interval]) / vm_available_memory_bytes{job=~"$job", instance=~"$instance"}) by (instance)
```
RSS Anonymous Memory % Usage
```
max(max_over_time(process_resident_memory_anon_bytes{job=~"$job", instance=~"$instance"}[$__rate_interval]) / vm_available_memory_bytes{job=~"$job", instance=~"$instance"}) by (instance)
```
CPU % Usage
```
max(rate(process_cpu_seconds_total{job=~"$job", instance=~"$instance"}[$__rate_interval]) / vm_available_cpu_cores{job=~"$job", instance=~"$instance"}) by (instance)
```
CPU
```
rate(process_cpu_seconds_total{job=~"$job", instance=~"$instance"}[$__rate_interval])
```
![image](https://github.com/user-attachments/assets/e29157ef-2c2e-4c3b-ba21-963f77ca71e6)
Disk read/writes
```
sum(rate(process_io_storage_read_bytes_total{job=~"$job", instance=~"$instance"}[$__rate_interval])) by (instance)
```
and
```
sum(rate(process_io_storage_written_bytes_total{job=~"$job", instance=~"$instance"}[$__rate_interval])) by (instance)
```

The pod for tests is placed on c5.xlarge https://instances.vantage.sh/aws/ec2/c5.xlarge node in AWS. As a storage I use 150 GiB gp3 volume. 

As you can see from the charts, CPU is not utilized fully during execution of query. Is it expected performance or can it be better (by tweaking settings)?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Andrey36652** [comment]
Thank you for the thorough answer, will experiment

**Comment by valyala** [comment]
@Andrey36652 , the following commits should speed up the original query, since they avoid reading unneeded data from disk:

```logsql
* | stats by (_stream) min(_time) as earliest_time | sort by (earliest_time) limit 20
```

* 4599429f516116ae96c7a6b99e0729626f5e9d9c
* 65b93b17b1a87c970184f026e34ee735613e10b5

Could you try executing the same query on VictoriaLogs Docker container based on `docker.io/victoriametrics/victoria-logs:heads-public-single-node-0-ge9950f6307`? This Docker image includes the commits mentioned above.

Alternatively, you can build VictoriaLogs from the commit 65b93b17b1a87c970184f026e34ee735613e10b5 according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code).

**Comment by Andrey36652** [comment]
@valyala Tried it. It's much better now (3-5 sec for my original query). Thank you!
Will this version of docker image be permanent? Can I point to it in values.yaml?

**Comment by valyala** [comment]
> Will this version of docker image be permanent? Can I point to it in values.yaml?

Yes, but it is better switching to [v0.30.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release tag, since it includes all the optimizations mentioned above. It also includes an additional optimization in b82bd0c2ec2c3a3d0031bd0c4ec7ff32c2777d0d , which can further reduce query time in your case.

Closing this issue as resolved then.
