### ISSUE TITLE
What are the best practices for determining node count in various scenarios?

### ISSUE THREAD

**Issue by Wudadada** [VictoriaMetrics/VictoriaMetrics#7071]
### Is your question request related to a specific component?

vmselect、vminsert、vmstorage

### Describe the question in detail

Are there any recommendations on adjusting the ratio between vmselect, vminsert, and vmstorage nodes to optimize performance in different deployment scenarios?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by f41gh7** [comment]
There is no specific requirements to the nodes count per components. VictoriaMetrics components could utilize all available node resources. And it's actual limitation for scaling. If given node cannot be longer scaled vertically, you have to increase nodes count. 
 It's only tricky for vmstorage components. Since there is no data re-balancing, you have to plan storage nodes count in advance according to the disk utilization and retention period. 

 See this docs for details https://docs.victoriametrics.com/#capacity-planning

**Comment by jiekun** [comment]
Close as answered. Feel free to re-open it if you have more questions on this topic.
