### ISSUE TITLE
vmui: can't build UI with yarn

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#7142]
### Describe the bug

js crash and every component don't work.
![image](https://github.com/user-attachments/assets/be7eb6e0-08c4-41d7-a0bc-bac1cbd8c246)

uPlot dependence append a NULL at this line. may be some config is wrong.
![image](https://github.com/user-attachments/assets/f41ddab9-87e9-490d-9f88-2fa80913e02b)

### To Reproduce

compile master branch vmui vmlogs.

### Version

latest

**Comment by hagen1778** [comment]
@yincongcyincong could you please share commands you use to build vmui and victoria logs?

**Comment by yincongcyincong** [comment]
yarn build:logs
rm -rf ../../../vlselect/vmui/*
cp -R build/* /Users/yincong/go/src/github.com/yincongcyincong/VictoriaMetrics/app/vlselect/vmui/

**Comment by hagen1778** [comment]
@yincongcyincong I'm not sure if using `yarn build:logs` is enough. Could you try building the UI as I suggested [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7142#issuecomment-2383243016)?

**Comment by yincongcyincong** [comment]
> ```shell
> make vmui-logs-update
> ```

actually, this `make` command need docker enviroment. i don't have docker on my pc. so it's failed

**Comment by yincongcyincong** [comment]
i use `"npm install && npm run build:logs` to  compile vmui. it work normally. i also want to know why yarn don't work.

**Comment by hagen1778** [comment]
> i use "npm install && npm run build:logs to compile vmui. it work normally. i also want to know why yarn don't work.

Have no idea :) Maybe @Loori-R knows?
But from my PoV, running it in docker env is more universal as you don't need to have npm at all for this.

**Comment by yincongcyincong** [comment]
@hagen1778 how about add a `make` command that don't need docker.

**Comment by Loori-R** [comment]
> i use `"npm install && npm run build:logs` to compile vmui. it work normally. i also want to know why yarn don't work.

When running `npm install`, the existing `package-lock.json` is used, where `uPlot` version 1.6.30 is specified. However, when using `yarn`, since there is no `yarn.lock` file, the latest version of `uPlot` (1.6.31) is installed, which causes an error. For now, you can explicitly install version 1.6.30 to avoid the issue.

I will update the code to upgrade to the latest version and resolve the error.

**Comment by Loori-R** [comment]
> @hagen1778 how about add a `make` command that don't need docker.

@yincongcyincong What do you want to do? Build only the UI for victorialogs?

**Comment by yincongcyincong** [comment]
> > @hagen1778 how about add a `make` command that don't need docker.
> 
> @yincongcyincong What do you want to do? Build only the UI for victorialogs?

i can have try today.

**Comment by valyala** [comment]
[Web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) is intended to be built with `make vmui-logs-update` command. This command expects Docker to be installed on the host where it runs. This requirement guarantees that the `make vmui-logs-update` is executed in the the same environment provided by the corresponding Docker image. This environment doesn't depend on the host system, so the `make vmui-logs-update` can be run on any host with any environment. There is no need in installing bloated JS build shit on the host in order to build `vmui` - the only dependency is Docker.

We aren't going to add commands, which could build `vmui` without Docker dependency, since in this case they will require the bloated JS build shit. These requirements are much more fragile and harder to meet than the only requirement to have Docker on the host.

Closing this issue as answered.
