### ISSUE TITLE
search.maxQueryLen option is questionable

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#715]
**Describe the bug**
`search.maxQueryLen` seems to be a placeholder for some optimization-- the value is only used to generate an error

Our use case is grafana dashboard templating, where a template variable generates a long list, which is in turn used by panel queries (via POST).  The list will grow with time.

**Expected behavior**
If the configuration option is not essential, and deployments can arbitrarily hit the default limit, perhaps it's better to remove the option.

**Comment by valyala** [comment]
The `-search.maxQueryLen` prevents from processing accidentally generated heavy queries. Default value - 16KiB - is quite good limit for the majority of use cases. It looks like your use case doesn't fit this majority. So you can just increase this limit to the desired value.

**Comment by belm0** [comment]
I found there are other safeguard settings that don't effect the implementation and only exist to fail queries, such as `maxUniqueTimeseries`.

It would be helpful in the docs to say something like "To avoid heavy queries, VM adds configurable limits which do not exist in other implementations such as Prometheus.  You may want to review the following options and ensure that the defaults are suitable for your deployment: ..."

**Comment by valyala** [comment]
> It would be helpful in the docs to say something like "To avoid heavy queries, VM adds configurable limits which do not exist in other implementations such as Prometheus. You may want to review the following options and ensure that the defaults are suitable for your deployment: ..."

I think this is unnecessary, since it pushes users to investigate and tune more configs than necessary, which isn't recommended in general - see [troubleshooting section](https://victoriametrics.github.io/#troubleshooting) for details. The most important selling point of VictoriaMetrics is that it just works out of the box without the need to tune many configs. On the other hand, VictoriaMetrics provides many tuning knobs for advanced users. But these knobs aren't needed for the majority of users.

**Comment by belm0** [comment]
> The most important selling point of VictoriaMetrics is that it just works out of the box without the need to tune many configs.

This is not our experience.  The query workload migrated from prometheus has triggered several of VM's query limits.   Where as prometheus / thanos work "out of the box", VM has tight default limits that we are hitting unexpectedly and at inconvenient times, which then require researching what the setting is, what the default is, and what the consequences are of increasing the limit.  In the cases so far, the default limits have been off by about 2 orders of magnitude for our needs-- even though our usage runs effortlessly on a single-node VM.

So having these arbitrary and tight limits is not a good experience for the user migrating from another implementation.  I understand that having no limits by default would have its own issues (users would complain about OOM crash and poor performance), but that is the right time for the user to decide what the correct limits are for his use case (as opposed to out of the box when just starting).

**Comment by valyala** [comment]
> This is not our experience. The query workload migrated from prometheus has triggered several of VM's query limits. Where as prometheus / thanos work "out of the box", VM has tight default limits that we are hitting unexpectedly and at inconvenient times, which then require researching what the setting is, what the default is, and what the consequences are of increasing the limit. In the cases so far, the default limits have been off by about 2 orders of magnitude for our needs-- even though our usage runs effortlessly on a single-node VM.

Probably default limits must be adjusted in the source code in order to cover cases like yours. The best approach would be if the limits are automatically adjusted depending on the available CPU and RAM.

**Comment by leoskyrocker** [comment]
I totally understand where this limit is trying to get at.

Although, IMHO, a long query may not be equivalent to a heavy query.
In our use case, some grafana dashboards is just generating an extremely long query because it's generating a regex to match all of the pods in the namespace

On the other hand, some queries may be short but heavy.

Given long != heavy, I wonder if there may be other limits that can be applied that targets heavy query instead. Also, given how many knobs there are in VictoriaMetrics in 2023, maybe there's already ones that supersedes this particular setting.

**Comment by valyala** [comment]
All the configuration parameters, which can affect resource usage of VictoriaMetrics, are documented in the following places:

- [Resource usage limits for single-node VictoriaMetrics](https://docs.victoriametrics.com/#resource-usage-limits)
- [Resource usage limits for VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#resource-usage-limits)

We aren't going to remove the `-search.maxQueryLen` option and all the other options mentioned in the docs above, since they help preventing from excess resource usage (CPU, RAM, disk IO, network IO), which could lead to various issues such as significant slowdowns for querying and data ingestion or out of memory (OOM) crashes.

Closing this issue as won't fix then.
