### ISSUE TITLE
avg_over_time works incorrectly for boolean query

### ISSUE THREAD

**Issue by SmilingNavern** [VictoriaMetrics/VictoriaMetrics#718]
**Describe the bug**
Difference between behavior in prometheus and VM. In prometheus we get parse error, in VM we get strange results for following query:
```
avg_over_time(up == up)[1h]
```

**To Reproduce**
Use UI to execute above query.

**Expected behavior**
It should be parse error in both cases.

**Version**
VM: 1.36.3-cluster, prometheus: 2.19.2

**Comment by valyala** [comment]
This is intended behavior. The `avg_over_time(up == up)[1h]` query uses two features from [MetricsQL](https://victoriametrics.github.io/MetricsQL.html):

* ability to skip square brackets inside range function: `avg_over_time(m)` in MetricsQL is equivalent to `avg_over_time(m[$__interval])` in PromQL (it is assumed that `$__interval` is automatically substituted with the appropriate value by Grafana).
* ability to skip colon and step value in [subqueries](https://medium.com/@valyala/prometheus-subqueries-in-victoriametrics-9b1492b720b3). 

VictoriaMetrics rewrites the original query to the following according to features mentioned above:

`last_over_time(avg_over_time((up==up)[$__interval])[1h:$__interval])`

This query can return 1 or emty result depending on the `$__interval` value and the interval between raw samples stored in the database.

It is likely the query is incorrect, since it has little sense. Try `avg_over_time(up[1h])` instead - it returns uptime percentage during the last hour. Take a look also at `share_le_over_time` and `share_gt_over_time` functions from [MetricsQL](https://victoriametrics.github.io/MetricsQL.html), which may be useful for calculating SLI/SLO and similar indicators.

**Comment by SmilingNavern** [comment]
Thanks for your answer, i am going to close this ticket then. Original query was a little bit different and it still had no sense, but i was a little bit confused that we had different results in prom/vm.
