### ISSUE TITLE
Dropping metrics when exceeding configured limit of unique labels and/or metric names

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#7205]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Based on my understanding of the relevant [documentation](https://docs.victoriametrics.com/keyconcepts/#labels-1), victoriametrics can limit the number of labels via the `-maxLabelsPerTimeseries` flag:
>  By default, VictoriaMetrics limits the number of labels per measurement to 30 and drops other labels. This limit can be changed via -maxLabelsPerTimeseries command-line flag if necessary (but this isn’t recommended).

I assume this is the max number of unique labels presented by the whole metrics endpoint or is it per individual metrics presented by the endpoint?   Also, based on the explanation above, it seems like it only drops the additional labels that go beyond this max configured value?   If so, how is the list of labels to be dropped chosen?   Is there a way to cause the entire scrape of the endpoint to fail if the number of max unique labels or metrics is exceeded?   I much prefer that method (which Prometheus uses - see [configuration documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) for **label_limit**) as it allows you to immediately detect that there's an issue with a given endpoint instead of figuring it out by eventually noticing some metrics  and/or labels are missing.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi.

> I assume this is the max number of unique labels presented by the whole metrics endpoint or is it per individual metrics presented by the endpoint?

> how is the list of labels to be dropped chosen?

The `maxLabelsPerTimeseries` config works on **each time series** like the following codes.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a5d101304207590fe1669f73dd11f388a6f25153/lib/storage/metric_name.go#L513-L517

VictoriaMetrics Single Node or vminsert will drop labels based on the sequence they stored in a **list**. And this list could be generated by vmagent during scraping.

As for the vmagent side, please see `-sortLabels` flag [here](https://docs.victoriametrics.com/vmagent/#advanced-usage). If it's not set, you should assume those labels are **out of order**. So you cannot predict which label will be dropped.

> Is there a way to cause the entire scrape of the endpoint to fail if the number of max unique labels or metrics is exceeded?

During scrape time, vmagent may not be able to determine the total unique labels. Because user could apply metrics relabeling, or add more labels during remote write.

As for the vminsert or remote write receiver in VictoriaMetrics Single Node, data are not grouped by a `scrape job`.

Also, IIRC, it's hard to do it with [stream parsing mode](https://docs.victoriametrics.com/vmagent/#stream-parsing-mode) enabled for big scrape targets:
> When this mode is enabled, vmagent processes the response from the scrape target in chunks. This allows saving memory when scraping targets that expose millions of metrics.

**Comment by jiekun** [comment]
I could not label this issue as feature request, as this feature is discussed before and declined. Please feel free to drop more question on this topic.

**Comment by jiekun** [comment]
> the entire scrape will fail

Yes.
```
the response from %q exceeds sample_limit=%d; either reduce the sample count for the target or increase sample_limit
```

> this same functionality isn't yet available for labels_limit

Yes.
