### ISSUE TITLE
High iowait and memory usage of the vmstorage with version 1.39.4

### ISSUE THREAD

**Issue by saclive** [VictoriaMetrics/VictoriaMetrics#723]
**Describe the bug**
There are eight Prometheus nodes whitch remote-write to five vm_insert nodes through nginx . and each vm_insert nodes write to five vm_storage nodes
The five vm_storage nodes started with the same command-line flag and the same version
![image](https://user-images.githubusercontent.com/69297441/91276523-41a9d480-e7b4-11ea-8310-8566633bcb84.png)
One day, the five vm_storage nodes became very slowly with high iowait and finally be killed with oom
 
![image](https://user-images.githubusercontent.com/69297441/91276581-54bca480-e7b4-11ea-963f-52ba2d8e1c90.png)
![image](https://user-images.githubusercontent.com/69297441/91276621-5f773980-e7b4-11ea-9511-6ed949b42a48.png)

We collected the active time series information and found that the vm_cache_entries increased from 6mil to 12 mil.
 
![image](https://user-images.githubusercontent.com/69297441/91276640-643bed80-e7b4-11ea-858e-c979ede33105.png)
![image](https://user-images.githubusercontent.com/69297441/91276734-7fa6f880-e7b4-11ea-8a17-b1018f1840e0.png)

There is a new dir be created in vm_storage path , just the time when problem happened
 
![image](https://user-images.githubusercontent.com/69297441/91276652-6900a180-e7b4-11ea-88c5-a42321218e41.png)

We confused:
	why the active time series doubled?  There is no change with all the time series labels and no change with all monitored k8s node.
	Is this problem related to merge? 
	What is the merge mean? When the merge action will be triggered

**To Reproduce**
vmstorage run for several days 

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
[root@vm-10-185-192-52-centos victoria]# ./vmstorage-prod -version
vmstorage-20200815-132622-tags-v1.40.0-cluster-0-gd9f7ea1c6

**Comment by hagen1778** [comment]
Hi @saclive! The pictures are hardly readable, could you plz update with better resolution?
The dashboard also contains `Troubleshooting` row - could you pls add it as well? Would be nice to get screenshots for all the panels if this possible.

>  What is the merge mean? When the merge action will be triggered

Merges are happening all the time - it is a process of merging smaller parts with data into bigger ones to improve compression and reduce number of files on disk.

**Comment by saclive** [comment]
Thank you for showing me details of the merge. @hagen1778 
I m sorry for the unclear picture. 
I recollect them again as the following picture:
![image](https://user-images.githubusercontent.com/69297441/91370616-6ac47680-e841-11ea-8fca-ec0fa23bf3fc.png)
![image](https://user-images.githubusercontent.com/69297441/91370631-7879fc00-e841-11ea-9b1b-9bc3a0242699.png)
![image](https://user-images.githubusercontent.com/69297441/91370649-80d23700-e841-11ea-8daf-6d9e7bef94e3.png)
![image](https://user-images.githubusercontent.com/69297441/91370706-a19a8c80-e841-11ea-9db6-663c44eae53b.png)
![image](https://user-images.githubusercontent.com/69297441/91370726-aa8b5e00-e841-11ea-8525-d7c6e184d9de.png)
![image](https://user-images.githubusercontent.com/69297441/91370735-b7a84d00-e841-11ea-9e75-de1352d3f506.png)
![image](https://user-images.githubusercontent.com/69297441/91370762-c42ca580-e841-11ea-8ddd-a5e6942df331.png)
![image](https://user-images.githubusercontent.com/69297441/91370781-d6a6df00-e841-11ea-86ca-0cf904102ed1.png)
![image](https://user-images.githubusercontent.com/69297441/91370803-e3c3ce00-e841-11ea-82c5-d3a8bda8e4ac.png)
![image](https://user-images.githubusercontent.com/69297441/91370822-ed4d3600-e841-11ea-9154-b23abd5d4547.png)
![image](https://user-images.githubusercontent.com/69297441/91370839-f807cb00-e841-11ea-80d0-e47e69f320ca.png)
![image](https://user-images.githubusercontent.com/69297441/91370871-1241a900-e842-11ea-815a-3ef0fb3e70e7.png)


in addition, each node have 12G ram and 8 core cpu

I've been puzzled with this problem for weeks,  so  eager for some expert to explain it,thanks again

**Comment by hagen1778** [comment]
From the pictures you linked I can say the following:
1. At ~17:00 something happens and writers start to send new time series to VM. New time series are series with unique not registered before labels combination. For example, k8s re-deploy will always result into new time series since pods are getting unique names. New time series need to be registered and indexed so it is CPU and memory extensive operation.
2. Immediately number of "slow inserts" starts to grow. Every insert does a lookup in the VM index caches to understand if received series are already exist (and then we just get series IDs and continue to add points to it) or they are new and must be registered. Such lookups are usually served from the index cache, but when it is not enough RAM to fit the caches - it needs to read from disk. So "slow insert" is when VM starts to read index data from disk and obviously it is slow operation. 
If you press on the dashboard panel Info button - you'll get a hint:
```
The percentage of slow inserts comparing to total insertion rate during the last 5 minutes. 

The less value is better. If percentage remains high (>50%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of active time series. 

In general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on may other factors such as the number of labels per time series and the length of label values.
```
3. When slow inserts start to grow - some vmstorage node become unreachable. It is likely they are overloaded. So vminsert starts to `reroute` received data to the healthy ones exhausting their limits and memory as well.

I'd say you need to increase memory size for storage nodes. The following link well explains memory constraints - https://github.com/VictoriaMetrics/VictoriaMetrics#capacity-planning

**Comment by saclive** [comment]
Thank you very much @hagen1778 

The long time scaled query may be another rootcause i think. Because  when i query one month data from granfana today, the vm crashed.

There is some questions for your help. 

1. When query data for a long time such as a month , does vmstorage get data from the folder "/data/storage/data/big/2020_08" to create a new time series ?  
2.Are these datafiles stored every data point ingested from promtheus? If there are 240 datapoints in an active time series,  will they all be stored  in bigdata? Or loss some datapoints for compress such as LSM tree compaction?  What is the diffrence between big folder and small folder? What is the use of cache file and when to use it
3.Is there some metrics to calculate the data size quering from datafiles when a query excuted? 

VM is so powerful, but I am so unfamilia with it.  In addition to the source code, is there any principle article?

**Comment by valyala** [comment]
@saclive , please see answers below:

> When query data for a long time such as a month , does vmstorage get data from the folder "/data/storage/data/big/2020_08" to create a new time series ?

Querying doesn't create new time series - they are created only when new metric with new set of labels is sent to ``vmstorage`. `vmstorage` reads data from `<-storageDataPath>/indexdb`, `<-storageDataPath>/data/big` and `<-storageDataPath>/data/small` folders during query processing. It reads only the data for the time series matching the the query filter. `vmstorage` may read big amounts of data when processing heavy queries that match big number of time series and / or big number of samples on the selected time range. For instance, `{__name__!=''}` filter matches all the time series, so it requires reading all the data on the selected time range. This may take long time, CPU, RAM and disk read IO resources.

> Are these datafiles stored every data point ingested from promtheus? If there are 240 datapoints in an active time series, will they all be stored in bigdata? Or loss some datapoints for compress such as LSM tree compaction?

VictoriaMetrics stores all the ingested raw samples in these data files. And all these raw samples are read on every query for the matching time series on the selected time range. VictoriaMetrics drops samples only if their timestamps become older than the configured retention via `-retentionPeriod` command-line flag. See https://victoriametrics.github.io/#retention for details.

>  What is the diffrence between big folder and small folder?

Newly ingested data is stored in `storage/small` folder into small files. Then this data is gradually merged into bigger files. When file sizes reach certain limits that depend on available RAM size, these files are moved to `data/big` folder. This is needed in order to keep recently added data in OS file cache (aka [page cache](https://en.wikipedia.org/wiki/Page_cache)). This improves query performance over recently added data by avoiding slow disk read IO operations.

> What is the use of cache file and when to use it

VictoriaMetrics maintains multiple in-memory caches for speeding up data ingestion and querying. The size of these caches depends on available RAM and `-memory.allowedPercent` or `-memory.allowedBytes` command-line options (pass `-help` command-line flag to any VictoriaMetrics component in order to see description for these options). VictoriaMetrics flushes these caches to `<-storageDataPath>/cache` folder on graceful shutdown, i.e. after `SIGINT` or `SIGTERM` signal is sent to it. Then these caches are read on the next startup. This helps maintaining good performance level immediately after the startup without the need to warm up inmemory caches.
Every inmemory cache is limited in size (it depends on available RAM and `-memory.*` command-line flags as mentioned above). If cache size becomes small for the current workload, then this may lead to sharp increase in disk IO, CPU and, possibly, RAM usage. It is likely your case. The solution is to move to hosts with more RAM or to reduce the workload as Roman mentioned above.

> Is there some metrics to calculate the data size quering from datafiles when a query excuted?

There are the following metrics:

* `vm_fs_read_bytes_total` - it shows the amount of bytes read from data files during queries. This metric is exported by `vmstorage`.
* `vm_metric_rows_read_total` - it shows the number of rows (raw samples) read during query processing. This metric is exported by `vmselect`.

These metrics may be wrapped into `rate()` function in order to estimate the rate of read bytes and raw samples during query processing.

**Comment by valyala** [comment]
> In addition to the source code, is there any principle article?

See articles at [this page](https://victoriametrics.github.io/Articles.html).

**Comment by saclive** [comment]
@valyala Thank you very much. I  learned a lot from your answers. I think I'm getting started with VM now.  *^_^*
When I replaced the mechanical hard disk with SSD hard disk, no problem happens again
