### ISSUE TITLE
configs should be unified somehow

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#727]
**Is your feature request related to a problem? Please describe.**
promscrape.config and relabelConfig are handled quite differently:

  * promscrape allows a regular prometheus.yaml file, and ignores irrelevant sections
  * relabelConfig requires the raw relabel_config entries, with no header section.  (We couldn't find any documented example, so it was trial and error...)
  * promscrape supports interval for checking changes, relabelConfig does not

**Describe the solution you'd like**
Perhaps there should only be one config yaml, which follows prometheus yaml roughly and extends it.  So scrape config and relabel config will both come from that file, and it supports checking interval.

**Comment by valyala** [comment]
Single-node VictoriaMetrics and vmagent already support Prometheus-compatible relabeling rules at [scrape configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) in the following sections:

* relabel_configs
* metric_relabel_configs

The `-relabelConfig`, `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` cannot be unified and merged with `-promscrape.config`, since these options aren't supported by Prometheus. These relabeling configs are applied to all the metrics received from [any supported data ingestion protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-time-series-data), while Prometheus supports only a single data ingestion protocol via scraping metrics from the configured targets.

As for missing documentation for `-relabelConfig`-like command-line options, this should be definitely fixed. Contributions are welcome.

**Comment by valyala** [comment]
> promscrape supports interval for checking changes, relabelConfig does not

This also should be fixed. There are the following temporary workarounds for reloading updated relabeling configs:

* To send SIGHUP signal to `vmagent`
* To query `/-/reload` endpoint.

**Comment by valyala** [comment]
Closing this feature request, since trying to merge all the configs in a single unified file may break existing setups. This also may significantly complicate the source code without measurable benefits, since it needs to support both old and new schema for the configs.

See also related issues: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/138 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/576
