### ISSUE TITLE
VictoriaLogs: support extra time window in `/select/logsql/stats_query_range` API

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#7289]
### Is your feature request related to a problem? Please describe

VictoriaLogs provides `/select/logsql/stats_query_range?query=<query>&start=<start>&end=<end>&step=<step>` HTTP endpoint, which returns log stats for the given [query](https://docs.victoriametrics.com/victorialogs/logsql/) on the given [start ... end] time range with the given step interval. This can be used in Grafana pannel and for [rule backfilling](https://docs.victoriametrics.com/vmalert/#rules-backfilling) in vmalert.
For example, the following query returns the number of logs per each level [field](https://docs.victoriametrics.com/victorialogs/keyconcepts/#data-model) across logs over 2024-01-01 day by UTC with 6-hour granularity:
```
query=* | stats by (level) count(*)&start=2024-01-01Z&end=2024-01-02Z&step=6h
```

Additionally, in a Prometheus compatible system, user can also add a lookbehind window to the expression. For instance, the following query returns the average cpu usage for the last 5m every 1m.
```
query=rate(cpu_usage[5m])&step=1m&start=2022-05-10T09:59:00.000Z&end=2022-05-10T10:17:00.000Z
```

Currently, there is no similar function in [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/).

### Describe the solution you'd like

Support adding an extra window to the expression, maybe like:
```
_time: [start, end] | stats by (_time: 5m:1m) count() as total
```
This query should return the count of log entries for time windows `[start-5m, start], [start-4m, start+1m] [start-3m, start+2m], ....,  [end-5m, end]`

### Describe alternatives you've considered

Perform stats query `_time: 5m | stats count() as total` multiple times with setting `time` arg to `start`, `start+1m`,`start+2m`, ..., `end`.

### Additional information

related https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7289.

**Comment by valyala** [comment]
The main purpose of [`/select/logsql/stats_query_range` HTTP endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) is to build graphs in [VictoriaLogs plugin for Grafana](https://docs.victoriametrics.com/victorialogs/victorialogs-datasource/) and in [VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui). The most expected use case is to display a graph showing the calculated stats (such as the number of matching logs) per every `step` on the graph (where `step` is the corresponding query arg passed to [`/select/logsql/stats_query_range` endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats). Most users don't expect querying per-`step` stats on the lookbehind window other than `step`. So I don't think we should complicate the HTTP API and/or [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) for being able to calculate stats on other lookbehind windows.

The ability to specify arbitrary lookbehind window in PromQL (and [MetricsQL](https://docs.victoriametrics.com/metricsql/)) such as `rate(some_metric[lookbehind_window])` is the most misleading feature of PromQL when building graphs (this may be a good feature for alerting and recording rules where the `step` arg is replaced with either [the `interval` option](https://docs.victoriametrics.com/vmalert/#groups) or with the explicitly set lookbehind window in the query. BTW, VictoriaLogs already supports explicit setting of lookbehind window in alerting queries via [`_time:lookbehind_window`](https://docs.victoriametrics.com/victorialogs/logsql/#time-filter) filter). That's why the majority of PromQL queries in Grafana use `$__interval` (aka `step`) instead of arbitrary lookbehind window.

Closing this feature request as `won't implement`.
