### ISSUE TITLE
When does it make sense to decrease memory.allowedPercent on vmstorage?

### ISSUE THREAD

**Issue by grdq** [VictoriaMetrics/VictoriaMetrics#7299]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Hi,

We run a VM cluster of v1.00.1, which has an average active time series count of ~460M, ingestion of ~4M, and churn rate of 14K. Supporting this are 54 vmstorage pods of 3cpu and 55Gi of memory running on a k8s cluster, but with the pods set without a cpu limit, and just a request in k8s, so they can spike above as needed.

We are wanting to make sure that we are not "wasting" too much of this total memory footprint of 2970Gi to cache (we use the default 60%), when we do run into the occasional OOM or ServiceDown alert due to a pod locking up and failing its readiness probe. Across all our vmstorage pods as per the "RSS anonymous memory % usage" our vmstorage pods hover around 74%, and for "RSS memory % usage" that is ~95%

Currently we don't see cache miss ratio spikes above 70%. 

I see that in this old [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/142#issuecomment-518994326) from a good few years ago you say that 1GB of memory should handle 1M active time series. 

So the question is, given we have a pretty large amount of memory in total, is 60% (1782Gi) _too_ high? Would it be sane to decrease that percentage to match a total figure more in line with the 1GB per 1M guidance?

Thanks!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
Hey @grdq !

Please use https://docs.victoriametrics.com/#cache-tuning as guidance.
Please note, caches aren't reserving the memory in advance. They're consuming memory only when they actually have to store cached entries. And those entries has their expiration time (with some details). So normally, underutilized caches just don't use that 60% of mem and it can be used by a process.

> I see that in this old https://github.com/VictoriaMetrics/VictoriaMetrics/issues/142#issuecomment-518994326 from a good few years ago you say that 1GB of memory should handle 1M active time series.

You can get the cache size in bytes by querying `vm_cache_size_bytes` metric and calculate utilization via `vm_cache_size_max_bytes` metric. This is how you can get actual cache usage and make decisions based on this.
Please note, memory usage by vmstorage also heavily depends on the read queries.

**Comment by hagen1778** [comment]
>  If we can right-size the memory available to cache it allows us to squeeze some more load out of the existing memory footprint we have, but I only want to do so if it is not dangerous to do so cache wise.

I can't say for sure. Do you observe caches that have significant memory usage and high miss ratio? If yes, these caches are the first target for optimization. But if there are no such caches - touching something could result into performance degradation for write or read path. I don't think it will crash something, though.

Also, the target of `1GB / 1M` is probably outdated since 2019. It also heavily depends on the query load. However, on our playground, where only ingestion and alerting exists (not much of ad-hoc queries), vmstorage takes 4GiB of caches for 3.7Mil actie series:
<img width="667" alt="image" src="https://github.com/user-attachments/assets/7dd5c841-e3d2-4e83-87c6-b73c4db6321e">
https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1&var-ds=P6E2B03337A022E16&var-job=vmstorage-benchmark-vm-cluster-staging&var-job_insert=All&var-job_select=All&var-job_storage=All&var-instance=All
