### ISSUE TITLE
How to implement vmagent persistent storage?

### ISSUE THREAD

**Issue by XMingG99** [VictoriaMetrics/VictoriaMetrics#7314]
### Describe the question in detail

How to implement vmagent persistent storage? I only see one method related to fastqueue, is that it?Can you provide an introduction to the architecture diagram or something similar?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. 

By default vmagent stores pending data, which cannot be sent to the configured remote storage systems in a timely manner, in the folder set by `-remoteWrite.tmpDataPath` command-line flag. By default vmagent writes all the pending data to this folder until this data is sent to the configured `-remoteWrite.url` systems or until the folder becomes full. The maximum data size, which can be saved to `-remoteWrite.tmpDataPath` per every configured -remoteWrite.url, can be limited via `-remoteWrite.maxDiskUsagePerURL` command-line flag. When this limit is reached, vmagent drops the oldest data from disk in order to save newly ingested data.

You can find out more on the vmagent documentation here: https://docs.victoriametrics.com/vmagent/#disabling-on-disk-persistence

**Comment by XMingG99** [comment]
> Hi.
> 
> By default vmagent stores pending data, which cannot be sent to the configured remote storage systems in a timely manner, in the folder set by `-remoteWrite.tmpDataPath` command-line flag. By default vmagent writes all the pending data to this folder until this data is sent to the configured `-remoteWrite.url` systems or until the folder becomes full. The maximum data size, which can be saved to `-remoteWrite.tmpDataPath` per every configured -remoteWrite.url, can be limited via `-remoteWrite.maxDiskUsagePerURL` command-line flag. When this limit is reached, vmagent drops the oldest data from disk in order to save newly ingested data.
> 
> You can find out more on the vmagent documentation here: https://docs.victoriametrics.com/vmagent/#disabling-on-disk-persistence

yes, I know how to use it, but I want to know how it works. I am reading the source code, but I am not very clear, so I want to know its architecture or persistence function entry

**Comment by jiekun** [comment]
You can go through the codes under `lib/persistentqueue`. `FastQueue.pq` is file-based queue while `FastQueue.ch` is the in-memory queue. And `func (q *queue) MustWriteBlock(block []byte)` write block to the `pq`.
