### ISSUE TITLE
/api/v1/series query does not default to all time

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#735]
**Describe the bug**
query like `/api/v1/series?match[]={category=~".+"}` does not include old series unless `&start=0` is appended

Prometheus implementation of this API returns series of all time by default

**Expected behavior**
Default range is all time.

**Version**
victoria-metrics-20200815-125320-tags-v1.40.0-0-ged00eb3f3

**Comment by valyala** [comment]
VictoriaMetrics return time series for the last 5 minutes by default from [/api/v1/series](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) if `start` and/or `end` query args aren't set. This is an optimization, which prevents from executing accidental heavy queries when the database contains big number of time series with high churn rate.

Grafana passes the selected time range in `start` and `end` args to `/api/v1/series` when `label_values()` function is called, so VictoriaMetrics correctly returns time series for the selected time range.

It is recommended to pass `start` and `end` query args to `/api/v1/series` in order to get time series on the given time range. Note that VictoriaMetrics accepts relative times in these query args. For example, `/api/v1/series?start=-1d&match[]=...` would return time series for the last day.

**Comment by belm0** [comment]
Thank you.  I'm not necessarily in agreement about the departure from prometheus API, but at least this default should be documented in the VM README?

And docs for `delete_series` should explicitly note to use `start=0`, because it suggests using `/api/v1/series` to confirm before the delete.

**Comment by valyala** [comment]
@belm0 , thanks for suggestions! Docs have been updated in the commit fe98ba5a606d22f7c5abc40ebab6a7107b684d32 .
