### ISSUE TITLE
Creating graphs in Grafana with VictoriaLogs

### ISSUE THREAD

**Issue by jackmachine3d** [VictoriaMetrics/VictoriaMetrics#7353]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

In Loki, it is possible to create graphs in Grafana based on logs. For example, there is a LogQL query that shows the number of open ssh sessions and users
```
sum by (username) (count_over_time({application="sshd",facility=~"auth|authpriv",host=~"$instance"} |="sshd" |=": session opened for" | pattern `<_> session opened for user <username> <_>` | username !~".* by " | __error__="" [$__interval]))
```
and I get a graph like this where users are marked (different colors)
![image](https://github.com/user-attachments/assets/6f751e93-a623-4b32-8578-b4291bf864a0)
But I don't understand at all how I can make the same graph using the LogsQL syntax. All I could get was this request
```
{hostname=~".+",app_name="sshd"} |" session opened for user" | extract "session opened for user <username>" 
```
And when I apply the visualization of time series or bar chart, I get an error on the panel "Data is missing a number field"
Can you tell me if LogsQL has a similar ability to build graphs? I really like Victoria Logs for its performance and ease of setup, but I need similar graphics as when using Loki

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
To get Victorialogs responses to appear as a timeseries in Grafana you need to add a couple of transforms. [There is an open issue in the Victorialogs datasource to get this fixed](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/61) 

![image](https://github.com/user-attachments/assets/60954f34-8aaa-454a-bd57-f757df333b19)

**Comment by jackmachine3d** [comment]
@tiny-pangolin thanks for the reply. I hope that the possibility of building a time series of graphs will make it more convenient, for the first time the current offer will be suitable.

**Comment by valyala** [comment]
The following Loki query:

```
sum by (username) (
  count_over_time(
    {application="sshd",facility=~"auth|authpriv",host=~"$instance"}
      |= "sshd"
      |= ": session opened for user"
      | pattern `<_> session opened for user <username> <_>`
      | username !~".* by "
      | __error__="" [$__interval]
  )
)
```

is roughly equivalent to the following [LogsQL query](https://docs.victoriametrics.com/victorialogs/logsql/):

```logsql
{application="sshd",facility=~"auth|authpriv",host=~"$instance"} "sshd"  ": session opened for user"
  | extract "session opened for user <username> "
  | stats by (username) count() as hits
```

This query returns per-`username` number of logs for the given `{application="sshd",factility=~"auth|authpriv",host=~"$instance"}` [stream filter](https://docs.victoriametrics.com/victorialogs/logsql/#stream-filter), which contain the `sshd` [word](https://docs.victoriametrics.com/victorialogs/logsql/#word-filter) and `: session opened for user` [phrase](https://docs.victoriametrics.com/victorialogs/logsql/#phrase-filter). The query doesn't contain [time filter](https://docs.victoriametrics.com/victorialogs/logsql/#time-filter), that's why it calculates the stats over all the logs. If you want building graphs for this stats over some `start` ... `end` time range with some `step`, the this query must be passed to [`/select/logsql/stats_query_range`](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) HTTP endpoint together with the desired `start`, `end` and `step` query args. This endpoint is going to be used by [VictoriaLogs plugin for Grafana](https://docs.victoriametrics.com/victorialogs/victorialogs-datasource/) and by [VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) soon. See the corresponding feature requests:

- [The feature request to add support for building graphs over VictoriaLogs stats in Grafana plugin](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/61)
- [The feature request to add support for building graphs over VictoriaLogs stats in Web UI](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6963).

Closing this feature request because it is split into the two feature requests above.

**Comment by hagen1778** [comment]
> But I don't understand at all how I can make the same graph using the LogsQL syntax.

To plot a time series panel grouped by time with VictoriaLogs simply pick TimeSeries type of panel, switch to `RangeQuery` and type a select query of your choice. See docs https://github.com/VictoriaMetrics/victorialogs-datasource/blob/main/src/README.md#time-series-panel. And see[ playground example here](https://play-grafana.victoriametrics.com/d/be5zidev72m80f/k8s-logs-via-victorialogs?orgId=1&from=now-24h&to=now&timezone=browser&var-ds=P566C6523BE02F42C&var-namespace=slack2logs&var-namespace=vmlogs&var-namespace=vm-operator&var-pod=$__all&var-container=$__all&var-filter=%2A&var-limit=100&var-Filters=&editPanel=8):

<img width="1063" alt="Image" src="https://github.com/user-attachments/assets/c9880359-6c37-406d-b726-50b06477f3ef" />

--------

VictoriaLogs datasource plugin is officially available in Grafana - see https://grafana.com/grafana/plugins/victoriametrics-logs-datasource/
