### ISSUE TITLE
vmselect: raising any series to power of 0 in range queries returns non-existing data points

### ISSUE THREAD

**Issue by trearcul** [VictoriaMetrics/VictoriaMetrics#7359]
### Describe the bug

Hi,

I've encountered an issue in VictoriaMetrics. When raising any series to the power of 0 in a range query, the result contains a data point for every step in the queried range - even if the series has only a single data point within that range.

The correct behavior should be similar to the output produced by the `group without ()` function. This means that if the series being raised has no data at a particular step of the range query, it should return no data point for that timestamp.

This issue affects both the clustered and single-node versions of VictoriaMetrics.

Thank you.

### To Reproduce

To reproduce the issue, run `(hour() == 12)^0` as a range query over a 24-hour time range.

### Version

victoria-metrics-20241021-132758-tags-v1.105.0-0-g05f6ea621d

### Screenshots

Result of `(hour() == 12)^0`
![Screenshot 2024-10-25 at 15 23 06](https://github.com/user-attachments/assets/fd6d6141-20f0-4b47-ad3b-64855fd29030)

Expected result
![Screenshot 2024-10-25 at 15 23 22](https://github.com/user-attachments/assets/a16f7ca8-e980-40ab-8393-74b65503d985)

**Comment by jiekun** [comment]
Thanks for the bug report.

I will raise a pull request for this. Please help verifying the result for query `(hour() == 12)^0` below with my patch:
<details>

![image](https://github.com/user-attachments/assets/d34e7404-dfb0-496b-b2f2-1221decb9cc0)

</details>

**Comment by trearcul** [comment]
Hi! According to the screenshot you provided, it looks like the issue has been fixed by your changes. 👍 Thank you!

**Comment by jiekun** [comment]
Thanks. It will be reviewed by maintainers.

---
And also wanna to clarify the reason behind this.

1. Currently, the `^` in VictoriaMetrics simply wrapped Go's native implementation. So `anything ^ 0` is `1` (which will be corrected in my PR), you should always observe `1` as output. See example [here](https://play.victoriametrics.com/select/0/vmui/?#/?g0.range_input=24h&g0.end_input=2024-11-04T14%3A42%3A00&g0.relative_time=last_24_hours&g0.tab=0&g0.tenantID=0&g0.expr=%28hour%28%29+%3D%3D+12%29+%5E+0).
    - left time series ^ right time series: `[NaN, NaN, 12, NaN] ^ [0, 0, 0, 0] = [1, 1, 1, 1]`
3. However you may observe that when selecting a smaller time range, it may return `no data` instead of `1`. See example [here](https://play.victoriametrics.com/select/0/vmui/?#/?g0.range_input=30m&g0.end_input=2024-11-04T14%3A41%3A45&g0.relative_time=last_30_minutes&g0.tab=0&g0.tenantID=0&g0.expr=%28hour%28%29+%3D%3D+12%29+%5E+0) This is because VictoriaMetrics will simplify time series when no valid data point exists.
   - `[NaN, NaN, NaN] ^ [0, 0, 0] = Empty ^ [0, 0, 0] = Empty`

Line 175 returns empty result.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/92de6ea3407ad35ad816baf9278ae9dc470a3d63/app/vmselect/promql/binary_op.go#L170-L176

**Comment by trearcul** [comment]
Thank you. That’s the behavior (after the fix) I would expect. I just hope no one is relying on the current behavior in their queries. 🤞

**Comment by f41gh7** [comment]
The bugfix was included into [v1.107.0](https://docs.victoriametrics.com/changelog/#v11070), [v1.102.8](https://docs.victoriametrics.com/changelog/#v11028) and [v1.97.13](https://docs.victoriametrics.com/changelog/#v19713).
