### ISSUE TITLE
oidc for frontend victoria logs

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/VictoriaMetrics#7413]
### Is your feature request related to a problem? Please describe

authentication and authorization in frontend 

### Describe the solution you'd like

oidc for gitlab

### Additional information

this will solve the problem with access to logs only for internal users

**Comment by tiny-pangolin** [comment]
Instead of implementing this in all VictoriaMetrics components we recommend placing them behind a reverse proxy that can handle OIDC. This can be achieved using [vmgateway](https://docs.victoriametrics.com/vmgateway/index.html#jwt-signature-verification) with VictoriaMetrics Enterprise, [Oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/gitlab), [Caddy](https://caddyserver.com/docs/caddyfile/directives/forward_auth), or [Traefik](https://doc.traefik.io/traefik/middlewares/http/forwardauth/)

**Comment by Nello-Angelo** [comment]
sorry for the speech, I was talking about Victoria Logs

**Comment by tiny-pangolin** [comment]
Apologies for not making it clear when I said all VictoriaMetrics components I meat Victoriametrics and Victorialogs. Is there something that adding authorization to the UI would achieve that using a reverse proxy wouldn't?

**Comment by Nello-Angelo** [comment]
I won’t get the same functionality as in Grafana or Argosd

**Comment by hagen1778** [comment]
@Nello-Angelo I agree with @tiny-pangolin.
If extra authentication methods will be added, they will be added to vmauth or vmgateway.
vmui in victorialogs will remain similar to vmui in victoriametrics - focused on UI only. The security features are responsibility of other tools.
Closing as won't implemented
