### ISSUE TITLE
Quickstart guide for Victorialogs and vmalert can break existing configs

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#7418]
### Describe the bug

[The quickstart docs for using vmalert to evalutate rules against Victorialogs ](https://docs.victoriametrics.com/victorialogs/vmalert/#quick-start) suggests using the `-rule.defaultRuleType=vlogs` flag. Adding this flag will break existing vmalert rules that don't have a `type`. I think the example rules should include `type: vlogs` to avoid breaking existing rules. An alternative would be to mention that changing this flag can break rules that do not have a specified type.

### To Reproduce

1. Follow vmalert quickstart start guide and add ` -rule.defaultRuleType=vlogs` to my vmalert config
2. Restart vmalert
3. receive errors from existing rules that do not specify the prometheus as the query language

### Version

vmalert-20241031-131801-heads-master-0-gc5b36138e

### Logs

```
vmalert-1  | invalid group "blackbox_latency_1d" in file "/rules/blackbox.yaml": invalid expression for rule  "http:response:time:1d": bad LogsQL expr: "quantile_over_time(.5,http_response_response_time{}[1d])", err: missing whitespace after the search word "quantile_over_time"; context: [quantile_over_time(]
vmalert-1  | invalid group "blackbox_uptime_1d" in file "/rules/blackbox.yaml": invalid expression for rule  "http:uptime:1d": bad LogsQL expr: "sum by (server,host) (clamp(http_response_result_code,0,1))", err: query filter cannot start with pipe keyword "sum"; see https://docs.victoriametrics.com/victorialogs/logsql/#query-syntax; please put the first word of the filter into quotes; context: [sum]
vmalert-1  | invalid group "blackbox_uptime_7d" in file "/rules/blackbox.yaml": invalid expression for rule  "http:uptime:7d": bad LogsQL expr: "sum by (server,host) (clamp(http_response_result_code,0,1))", err: query filter cannot start with pipe keyword "sum"; see https://docs.victoriametrics.com/victorialogs/logsql/#query-syntax; please put the first word of the filter into quotes; context: [sum]
```

### Used command-line flags

```
    command:
      - "-datasource.url=http://vmauth:8427"
      - "-datasource.bearerToken=vmalert"
      - "-notifier.url=http://10.0.0.161:9093"
      - "-remoteWrite.url=http://victoriametrics:8428"
      - "-remoteRead.url=http://victoriametrics:8428"
      - "-httpListenAddr=0.0.0.0:9093"
      - "-rule=/rules/*.yaml"
      - "-rule=/rules/*.yml"
      - "-configCheckInterval=1m"
      - "-rule.defaultRuleType=vlogs"
```

**Comment by valyala** [comment]
@Haleygo , could you look into this issue?

**Comment by tiny-pangolin** [comment]
I would be happy to update the docs. Before I start I want to know if I should
* update the comment for `-rule.defaultRuleType=vlogs`
* update the example rules to contain `type: vlogs`

**Comment by hagen1778** [comment]
> update the example rules to contain type: vlogs

I think this is a sensible thing to do.

> update the comment for -rule.defaultRuleType=vlogs

I'd suggest adding a note to https://docs.victoriametrics.com/victorialogs/vmalert/#quick-start that  -rule.defaultRuleType can be applied only if all rules are for VictoriaLogs.

wdyt @Haleygo ?

**Comment by Haleygo** [comment]
>update the example rules to contain type: vlogs

That's unnecessary when `-rule.defaultRuleType=vlogs`, and in [this page](https://docs.victoriametrics.com/victorialogs/vmalert/) `-rule.defaultRuleType` is `vlogs` as it focuses on VictoriaLogs as the datasource.

>update the comment for -rule.defaultRuleType=vlogs

Currently, the flag comments are like below which suggest the default rule type is changing to `vlogs` when using this flag.
>-rule.defaultRuleType=vlogs \            # Set default rules type to VictoriaLogs.

>-rule.defaultRuleType
   Default type for rule expressions, can be overridden by type parameter inside the rule group. Supported values: "graphite", "prometheus" and "vlogs".
   Default is "prometheus", change it to "vlogs" if all of the rules are written with LogsQL.

In general, I do not recommend that new users of vmalert, or those with many rules for both metrics and logs, use a single vmalert instance for both VictoriaMetrics and VictoriaLogs(And we don't mention the vmauth as the proxy way in the doc now). Since this approach requires setting rule type specificly for rules that have different type from the `-rule.defaultRuleType`, and there are global flags like `-rule.evalDelay`, `-external.alert.source` which can be set differently for different datasources.
It should be more clearer and simpler to set up two seperate vmalert instances, while reusing Alertmanager and VictoriaMetrics as the remote write destination.
cc @tiny-pangolin @hagen1778

**Comment by hagen1778** [comment]
> And we don't mention the vmauth as the proxy way in the doc now

I mentioned this here https://docs.victoriametrics.com/victorialogs/vmalert/#frequently-asked-questions

> It should be more clearer and simpler to set up two seperate vmalert instances, while reusing Alertmanager and VictoriaMetrics as the remote write destination.

I agree with that. But I think we should explicitily say about this in QuickStart first sentences. The flag should mentioned only together with `if all rules are in vlogs format then set the flag`.
