### ISSUE TITLE
How to improve the speed of VictoriaLogs count()?

### ISSUE THREAD

**Issue by linux-time** [VictoriaMetrics/VictoriaMetrics#7504]
### Is your question request related to a specific component?

VictoriaLogs 

### Describe the question in detail

I use victoriaLogs as the data source and display it in grafana, but I find that queries like stats by(_time:1m) count() are very slow. Is there any way to increase the speed of count()?

**Comment by tiny-pangolin** [comment]
to increase the speed of count you can use a stream selector so their are fewer logs to count. if you find your self running the same count queries over and over you can pre- compute the results with [recording rules](https://docs.victoriametrics.com/victorialogs/vmalert/index.html)

**Comment by valyala** [comment]
@linux-time , the [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) query performance depends on many factors:

- The amounts of logs the query selects with [log filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters). It is recommended following [these tips](https://docs.victoriametrics.com/victorialogs/logsql/#performance-tips) in order to reduce the amounts of selected logs.
- The particular types of [filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters) used in the query. Some filters are fast, while some are slow:
    - The fastest filters are: [`_time` filter](https://docs.victoriametrics.com/victorialogs/logsql/#time-filter), [`_stream` filter](https://docs.victoriametrics.com/victorialogs/logsql/#stream-filter) and [`_stream_id` filter](https://docs.victoriametrics.com/victorialogs/logsql/#_stream_id-filter). These filters allow skipping large volumes of logs, by narrowing down the search to a tiny subset of logs.
    - Quite fast filters: [word filter](https://docs.victoriametrics.com/victorialogs/logsql/#word-filter), [phrase filter](https://docs.victoriametrics.com/victorialogs/logsql/#phrase-filter), especially if they search for rarely occurred word or phrase (aka "needle in the haystack" search). These filters rely on [bloom filters](https://en.wikipedia.org/wiki/Bloom_filter) in order to speed up search speed.
    - The slowest filters: [regexp filter](https://docs.victoriametrics.com/victorialogs/logsql/#regexp-filter), [case-insensitive filter](https://docs.victoriametrics.com/victorialogs/logsql/#case-insensitive-filter). These filters require reading all the logs and applying the slow filter to every log entry. It is OK to add slow filters to a set of fast filters, which significantly reduce the amounts of logs to inspect. In this case slow filters are applied only to a small number of log entries, which match fast filters, so the final query performance remains fast.

- Disk read IO performance for the data stored at directory pointed by `-storageDataPath` command-line flag. VictoriaLogs could need reading a lot of data from disk when performing queries over large number of logs. In this case disk read IO performance may become a bottleneck. Note that the performance of disks at popular cloud providers can depend on the disk type and/or size - see, for example, [these docs](https://cloud.google.com/compute/docs/disks/performance#performance_limits).

- The particular [pipes](https://docs.victoriametrics.com/victorialogs/logsql/#pipes) used in the LogsQL query. You mention [`stats by(_time:bucket)` pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-by-time-buckets). This pipe is usually quite fast. It may be slow in the following cases:
    - When the amounts of selected logs is large (e.g. hundreds of millions or more). For example, `* | stats by (_time:1m) count()` may be quite slow if `*` selects a billion of rows.
    - When the number of `bucket` groups on the selected time range is too large (e.g. exceeds a few thousand). For example, `_time:10d | stats by (_time:1m) count()` can be quite slow, since the number of `1m` buckets on the `10d` interval is quite large: `10d/1m=14400`.

@linux-time , could you provide more details on the query you use and the amounts of logs this query needs to process?

**Comment by linux-time** [comment]
@valyala 
![image](https://github.com/user-attachments/assets/361d43f4-e9db-45ad-b903-150b230fa66f)
There are about 1.7 billion logs in 24 hours.

Use a query statement similar to the following to draw a chart in Grafana
* | by(_time:1m) count()
Querying in Grafana will be very slow or even time out. The solution I can think of now is to call the http api to query every 5 minutes, then write the data to VictoriaMetrics, and Grafana uses the VictoriaMetrics data source to draw the chart.

**Comment by tiny-pangolin** [comment]
I'm closing this issue since [recording rules](https://docs.victoriametrics.com/victorialogs/vmalert/index.html) are implemented in vmalert and can return results faster than performing a stat on 1.7 billion logs. @linux-time please let me know if you have any questions on how to use recording rules with victorialogs.
