### ISSUE TITLE
vmalert docs do not include vlogs is not listed as a type in the reference config

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#7585]
### Describe the bug

in the [groups section the vmalert docs](https://docs.victoriametrics.com/vmalert/index.html#groups) vlogs is not listed as a type only prometheus and graphite

### To Reproduce

1. go https://docs.victoriametrics.com/vmalert/index.html#groups
2. look at type example
3. notice `vlogs` is not a type

### Version

N/A

**Comment by Haleygo** [comment]
Thanks for the issue! 
`vlogs` was not mentioned [there](https://docs.victoriametrics.com/vmalert/index.html#groups) cause the page is under VictoriaMetrics, and users who visit the page don't need to use `vlogs` type. 
But since we also redirect to the same group chapter on the [vmalert page under VictoriaLogs](https://docs.victoriametrics.com/victorialogs/vmalert/), I suppose we need to mention the `vlogs` type.

**Comment by hagen1778** [comment]
Addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7595
