### ISSUE TITLE
VM documentation license

### ISSUE THREAD

**Issue by ccollie** [VictoriaMetrics/VictoriaMetrics#7586]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

What is the license covering the docs ? I'm creating a project based on the VictoriaMetrics and would like to be able to re-use portions of the docs (with attribution, of course)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
VictoriaMetrics license is listed here https://github.com/VictoriaMetrics/VictoriaMetrics?tab=Apache-2.0-1-ov-file#readme
Since docs are a part of the repo, everything listed in the repo (except parts that has their own licenses, such as dependencies) are automatically covered by the repo license. Including docs content.
