### ISSUE TITLE
force reindex indexdb

### ISSUE THREAD

**Issue by pilipyukaaa** [VictoriaMetrics/VictoriaMetrics#7697]
### Is your question request related to a specific component?

i think you need to release feature for force retention index db

### Describe the question in detail

i have victoriametrics single node installation and i have a problem with disk usage
693M	/var/lib/victoria-metrics/cache
74G	/var/lib/victoria-metrics/data
0	/var/lib/victoria-metrics/flock.lock
510G	/var/lib/victoria-metrics/indexdb
8.0K	/var/lib/victoria-metrics/metadata
4.0K	/var/lib/victoria-metrics/snapshots
8.0K	/var/lib/victoria-metrics/tmp

i have retention 1m because of this and i am lost metrics because indexdb doestn flush, its very awful, and i need to wait vm_next_retention_seconds 2kk seconds for retention, its bad

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
Hello @pilipyukaaa !

Indexdb size heavily depends on the [churn rate](https://docs.victoriametrics.com/faq/#what-is-high-churn-rate). The higher churn rate is, the worse compression VM can achieve. Discrepancy of 510GiB for indexdb and 74GiB and for raw data is the highest I've ever seen yet. If you can't reduce churn rate of the data, then it could be that VM is not the best tool for what you're doing. It is likely that [TooHighChurnRate](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cd89923e3c32d1a766b2927dd40bd1cb47196ce5/deployment/docker/rules/alerts-cluster.yml#L91-L107) alerting rule was constantly firing for you.

The mitigation options:
1. vm_next_retention_seconds 2kk means the next rotation of indexdb will happen in 20days. This would drop part of the index and disk space will be re-claimed.
2. Reduce churn rate as much as possible. The normal ratio for most of installations I had experience with is 20% of disk for index, and 80% for raw data. All other ratios signalize about problem with the data, and that problem comes with cost.
3. Reduce retentionPeriod to lower value to re-claim disk space faster.

There is no such feature as "re-index". I don't see ways how it could be implemented. Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7599

Closing as answered.

**Comment by WojciechKuk** [comment]
I noticed, that many directories/files in indexdb are 3-4x older than retention time. I.e. I have files from April, May on instance with 28d retention - and now It's end of December.
