### ISSUE TITLE
How do I know how many time series vm has stored in total?

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#776]
I only found total datapoints in the dashboard.

**Comment by faceair** [comment]
Is the index size equal to the number of unique timeseries? It says in the description that they are proportional.

**Comment by faceair** [comment]
Hi @valyala , respond to my question when you have a moment.

I'm writing an article to share how we got Graphite to run on VictoriaMetrics, and the project code has plans to open source to help more Graphite users migrate to VictoriaMetrics. Our solution has been production-proven and the performance is much, much better than the previous whisper.

We're now storing 15 trillion datapoints, and I'm confirming the number of unique timeseries.

**Comment by belm0** [comment]
`/api/v1/series/count` - it returns the total number of time series in the database

https://github.com/VictoriaMetrics/VictoriaMetrics#prometheus-querying-api-usage

**Comment by faceair** [comment]
Thanks, man. I found the number.
But I wonder if we could show this unique timeseries count on the dashboard as well.

**Comment by belm0** [comment]
It's possible, but you'll likely have to increase the query limits to execute this query.

Make sure you make it an instant query, not range query.

`count({__name__=~".*"})`

**Comment by faceair** [comment]
No, this query is expensive. I mean we store this count somewhere and increase it when new metrics are available, if that's convenient.

**Comment by faceair** [comment]
Seems fine, I made sure the code only scanned the index when it fetched count. It's just a bit slow because of the large amount of metrcis.
Thank you very much for your answer.

**Comment by valyala** [comment]
The `/api/v1/series/count` counts the number of unique time series by scanning the inverted index containing records for every time series. That's why it may be slow if the number of time series in the database exceeds tens of millions. There is `vm_cache_entries{type="storage/hour_metric_ids"}` metric, which shows the number of active time series, i.e. time series with recently added samples - see [monitoring docs](https://victoriametrics.github.io/#monitoring) for details. If no new data is ingested for the time series during long periods of time (i.e. more than a hour), then such time series isn't counted by `vm_cache_entries{type="storage/hour_metric_ids"}` metric.

The total number of time series in the database can be much bigger than the number of active time series if there is high churn rate, i.e. if old time series are constantly substituted by new time series. Time series are uniquely identified by its name plus a set of its' labels. If at least a single label value changes, then new time series is created. For example, `foo{bar="baz1"}` and `foo{bar="baz2"}` are distinct time series.

**Comment by heliodor** [comment]
@valyala, since this already has a lengthy discussion that comes up in google search, can you please explain the difference between the number returned by `/api/v1/series/count` vs the result of the query `sum(vm_rows{type="indexdb"})`, which is labeled "index size" in one of the dashboards?

In my particular case, the the api returns 2 million while the query returns 65 million.

**Comment by hagen1778** [comment]
Hi @heliodor!
`vm_rows{type="indexdb"}` shows number of entries in the indexdb, but relation between series and index entries is not 1-to-1. 
After your comment I realized that the panel for `sum(vm_rows{type="indexdb"})` on the dashboard isn't practical for users. So I'll replace it with something different. Thanks!

**Comment by valyala** [comment]
Additional details about indexdb. It contains entries of multiple types:
1. The `metric{labels} -> internal_series_id` entries, which map every ingested time series into its internal id. The `/api/v1/series/count` returns the number of these entries, since it matches the number of time series in the database.
2. The `internal_series_id -> metric{labels}` entries, which allow locating time series name with its labels for the given internal series id.
3. The `{label="value"} -> internal_series_id` entries (aka global inverted index), which map every `label="value"` pair for every time series to its internal id. These entries are used for fast location of time series matching the given [label filter](https://docs.victoriametrics.com/keyConcepts.html#filtering).
4. The `(date, {label="value"}) -> internal_series_id` entries (aka per-day inverted index), which map every `label="value"` pair for every time series to its internal id on a particular `date`. These entries are used for fast location of time series matching the given label filter on a particular time range.

**Comment by Tarasovych** [comment]
Is there any other way to count all timeseries? `count({__name__=~".*"})` is too heavy
