### ISSUE TITLE
VictoriaLogs Bug: execute logql, memory not enough

### ISSUE THREAD

**Issue by worker24h** [VictoriaMetrics/VictoriaMetrics#7903]
### Describe the bug

![image](https://github.com/user-attachments/assets/bb8d63cd-4c2f-4983-82c0-343a45ec30da)

+ I used to the latest of the master
+ The memory size of My MacBook Pro is 16GB

I think the memory should be enough 

### To Reproduce

None

### Version

The latest master

**Comment by valyala** [comment]
It is expected that the [`stream_context` pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stream_context-pipe) results are consumed by humans, not computers. An average human cannot inspect surrounding logs for tens of thousands of the found logs. That's why the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/afd926a0b0d52608fe51d754aab00c14b98eeb0a limits the number of logs and/or [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields), which can be passed to `stream_context` pipe. This should prevent from excess resource usage (CPU, RAM, disk IO) when too many matching logs are passed to `stream_context` pipe. The solution is to reduce the number of matching logs and log streams by using more specific [LogsQL filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters). Replace ` | stream_context ...` with ` | stats count() logs, count_uniq(_stream) streams` in the query in order to determine the number of matching logs and log streams, which are passed to `stream_context` pipe.

The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/afd926a0b0d52608fe51d754aab00c14b98eeb0a has been included in [v1.4.0-victorialogs release](https://docs.victoriametrics.com/victorialogs/changelog/). Closing this issue as resolved.
