### ISSUE TITLE
vminsert: issues of reroute mechanism when storage node is temporarily unavailable

### ISSUE THREAD

**Issue by dxtrzhang** [VictoriaMetrics/VictoriaMetrics#791]
**Describe the bug**
Once one(some) of the storage node(s) get killed, our vm cluster will lose the ability to ingest data into storage, and it is hard to recover if we don't get involved. The behaviour is:
1. high rerouted_from rate, not only from the down nodes, but also some other healthy nodes(basically all the nodes)
![image](https://user-images.githubusercontent.com/13900390/94270265-6095b500-ff72-11ea-9064-c143776245af.png)
2. slow data ingestion rate. The normal rate is about 25k per node but the minimum rate is actually under 1k per node. This is the graph of one node, others are all the same.
![image](https://user-images.githubusercontent.com/13900390/94270522-c08c5b80-ff72-11ea-9b2b-30a0d6b44392.png)
3. high index_write rate, more than 50X normal
    > It's not a official panel from the grafana vm-cluster dasboard, the MetricQL is: 
    > `sum(rate(vm_rows{type="indexdb"}[10m]))`

    ![image](https://user-images.githubusercontent.com/13900390/94270998-8ff8f180-ff73-11ea-9cea-6452f66e07c6.png)
4. High IO usage and CPU usage:
![image](https://user-images.githubusercontent.com/13900390/94271401-2a593500-ff74-11ea-9fa8-7fc9340106fa.png)
![image](https://user-images.githubusercontent.com/13900390/94271424-33e29d00-ff74-11ea-876b-8493847a2f90.png)
Not sure if it is the cause or a phenomenon.

PS: We have over 100 vmstorage nodes, and have a life-keeper process to re-launch the storage node immediately after it gets killed(within 1m).

---
Since the high rate of rerouted_from and index_write, we assume that maybe it is caused by reroute in vminsert, This is the hypothesis based on our cases:
We have two main reasons which get vmstoage killed:
1. manually kill vmstorage or other processes's high memory usage gets vmstorage OOM
2. some slow queries increase vmstorages' memory usage, and it gets OOM

After the storage node is down, vminsert reroutes data to other healthy nodes, and the new data increase the resource usage including IO, CPU, and the data ingestion of the healthy nodes get slow, so the reroute mechanism reroute data to any other healthy node, and boom, it causes avalanche！！！

--- 
To re-produce the situation, we build a cluster and use some other methods to keep the high IO and CPU usage, in the meanwhile, we scrape parts of our prod data into the cluster by vmagent, every is fine until we shut down one of our nodes, and the situation described above shown up.

In order to prove our hypothesis, we update the code to let vminsert stop rerouting the data from storage-x but still rerouting data from other nodes(we simply drop the data instead of rerouting).
We've done two operations here, 18:00 at storage-6 and 18:07 at storage-5. As you can see, after I shut down and restart storage-6 at 18:00, every thing seems fine because I stop the reroute from storage-6. But the same situation comes up when I shut down and restart vm-5 at 18:07.
![image](https://user-images.githubusercontent.com/13900390/94274108-dbad9a00-ff77-11ea-972d-e88218dc232c.png)
![image](https://user-images.githubusercontent.com/13900390/94274133-e49e6b80-ff77-11ea-9f53-63a9cb44f4ee.png)

**Version**
v1.39.4-cluster

**Comment by dxtrzhang** [comment]
What I am trying to say in this issue is that the rerouting mechanism in vminsert maybe not performed well as expected in actual prod env with heavy pressure.
And If this situation happens, It is hard to recover if we're not invoked in.  
What we did to recover is:
1. stop the vminsert and let data gets pending at vmagent.
2. start vminsert one by one after the IO/CPU usage, index_write rate and ingestion rate back to normal.
3. sometimes we decrease the instance of vmselect

This surely makes vm service unavailable.

Any ideas about this issue? @valyala 

If you need any details,  I'm available on slack and I 'll also update the info to this issue.

**Comment by valyala** [comment]
@dxtrzhang , it looks like you hit the worst case for rerouting algorithm. When a single vmstorage node becomes unavailable, then vminsert reroutes new data for time series from this node to other vmstorage nodes. This means that every remaining vmstorage node starts receiving `1/N` part of time series from failing vmstorage node. When data for new time series arrives to vmstorage node, it should register this time series in inverted index and in in-memory metainfo caches for active time series. The registration process for new time series in inverted index is up to 100x slower comparing to the process of adding new samples to already registered time series. Big number of labels per time series and long label names/values slows down the registration process. This means that the ingestion rate per each vmstorage node may slow down for _some time_ until new time series are registered in the inverted index.

If the number of time series in failing vmstorage node is big, then the time frame for slow down may be quite big. This time may be enough to trigger the second part of re-routing algorithm - if `vminsert` notices that the buffer with pending data for a particular `vmstorage` node is full, then it tries re-routing new data from this `vmstorage` node to the remaining `vmstorage` nodes. This prevents from overall data ingestion slow down when a particular `vmstorage` node becomes temporarily slow. But this may lead  to complete re-routing of all new data for every `vmstorage` node if the buffer with pending data for every `vmstorage` node becomes full. Buffers for every `vmstorage` node may become full due to slow registration of new time series after a single `vmstorage` node goes down as described above.

This leads to the worst case for re-routing algorithm when the number of new time series per each remaining `vmstorage` node becomes 2x. This increases the number of active time series per each `vmstorage` node by 2x. If these nodes have no enough memory for caching metainfo for doubled number of active time series, then this may lead to significantly increased disk IO and CPU usage as shown on graphs above. Additional disk IO and CPU is used for filling the in-memory cache with missing metainfo for active time series. This metainfo is read from files. The process never stops if vmstorage has no enough memory for metainfo for all the active time series, since old metainfo is constantly evicted from cache by new metainfo.

The workaround against worst-case re-routing described above is to make sure that `vmstorage` nodes have enough memory for caching metainfo for doubled number of active time series.

I tried reducing the probability of worst-case re-routing in commits referred above. These commits increase the maximum data ingestion bandwidth between every vmstorage and vminsert node in two ways:
* by removing unnecessary delays in data transfer on vminsert side;
* by processing incoming data from a single connection on vmstorage side in multiple threads.

@dxtrzhang , could you build VictoriaMetrics components from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster/) and verify whether they help avoiding the worst-case re-routing for your workload?

**Comment by valyala** [comment]
FYI, all the improvements mentioned above have been included in [v1.42.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by dxtrzhang** [comment]
Sorry for the delay, We‘re still running some tests.
According to the code, there're two kinds of re-route in vminsert:
1. located in function `sendBufToReplicas`. When data ingestion is failing for the routed storage, it will send data to next node and will take a tour at the entire storage list if the data still not satisfy the replication setting.
2. if the `br` of the storage struct is full, data will be appended into `reroutedBR` and some reroute worker will run the spread the data into other storages.

We're not  sure which re-route mechanism causes the issue above. If it's the first one, fix above may not work.

Still looking into it, we will attach any updates if we find anything.

---
FYI, fix above may cause another issue:
If the data in `reroutedBR > reroutedBufMaxSize`, data push will get blocked. It's OK  for vmagent because data will get pending at local file, but not so lucky for the other service sending data via vminsert APIs. And this surely increase the memory usage to store the reroutedBR.  

Also, It seems like vminsert doesn't have local storage logics like vmagent, why?

**Comment by xbsura** [comment]
We made a policy change for this issue, when some node becomes slow, vminsert will pending data in local storage(same as vmagent), but not do reroute, this works good in our environment

In order to deal with machine down, we made another change, instead of giving storage node directly, we start vminsert with group, such as ./vminsert -g xx1/node1, node2 -g xx2/node3,node4, the route change from node to group, all the node in one group will receive same data, and vmselect will try to select data from all nodes of all groups, so if one node down, all the cluster still can work

so will this method apply to you?

**Comment by dxtrzhang** [comment]
@valyala pending data in local storage(like vmagent) when storage is temporary unavailable works pretty good in our cases.

**Comment by waldoweng** [comment]
maybe vmstorage should recalculate hash to determine which vmstorage the request should be reroute to, so that all other vmstorage share the burden of one offline vmstorage?

**Comment by valyala** [comment]
> maybe vmstorage should recalculate hash to determine which vmstorage the request should be reroute to, so that all other vmstorage share the burden of one offline vmstorage?

This is how it works right now - if certain vmstorage node is temporarily unavailable, then all the incoming data for this node is spread across all the remaining vmstorage nodes. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1ee5a234dcfb83f8457f1ede1cbe5197db4a7c42/app/vminsert/netstorage/netstorage.go#L607-L612 for details.

**Comment by valyala** [comment]
> pending data in local storage(like vmagent) when storage is temporary unavailable works pretty good in our cases.

`vminsert` cannot buffer pending data in local storage when a vmstorage node is temporarily unavailable because of the following reasons:

* The buffer may grow to unlimited sizes if the corresponding vmstorage node remains unavailable for long periods of time. `vmagent` solves this issue by dropping the oldest data if the buffer grows beyond `-remoteWrite.maxDiskUsagePerURL` command-line value. Such approach cannot be used by `vminsert`, since this will mean incoming data loss when it could be re-routed to the remaining vmstorage nodes.

* The data buffered at `vminsert` is invisible in queries. This means that `vmselect` may return incomplete responses when a vmstorage node is temporarily unavailable.

**Comment by dxtrzhang** [comment]
Reasonable :)
But still, the reroute algorithm kinda perform worse if we hit the worst case(everytime in our env).
Anyway it's a great solution in our case, we'll keep searching for a more efficient solution though. Thanks for the reply.

**Comment by valyala** [comment]
FYI, the probability of the rerouting issue should be decreased starting from [v1.59.0](https://docs.victoriametrics.com/CHANGELOG.html#v1590), since it improves the registration speed for new time series on multi-CPU hosts. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1244 for details.

**Comment by valyala** [comment]
vminsert contains the improved re-routing mechanism starting from [v1.61.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It should reduce the probability, the duration and the severity of the global re-routing storm if all the `vmstorage` nodes cannot keep up with the current ingestion rate.

Additionally, vminsert v1.61.0 supports the ability to disable the rerouting with `-disableRerouting` command-line option. Below is the corresponding description for this option obtained from `/path/to/vminsert -help`:

>  -disableRerouting
>        Whether to disable re-routing when some of vmstorage nodes accept incoming data at slower speed compared to other storage nodes. By default the re-routing is enabled. Disabled re-routing limits the ingestion rate by the slowest vmstorage node. On the other side, disabled re-routing minimizes the number of active time series in the cluster

**Comment by valyala** [comment]
The next version of VictoriaMetrics will contain improved logic for data re-routing in the event if some of vmstorage nodes are temporarily unavailable or if some of vmstorage nodes temporarily slow down the processing speed for incoming data. The following improvements will be included in the next release of VictoriaMetrics cluster:
* Even series distribution among the remaining vmstorage nodes. Previously some vmstorage nodes could start receiving multiple times more series than other vmstorage nodes if some vmstorage nodes were unavailable or were slower than other vmstorage nodes.
* Reduced the maximum increase in the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) on the remaining vmstorage nodes after some vmstorage nodes become unavailable or become slow. It will be limited by 100% of the initial number of active time series per vmstorage node in the worst case (e.g. when vmstorage nodes have no enough resources to keep up with the increased load). Under normal conditions the increase in the number of active time series shouldn't exceed `1/N` of the initial number of active time series per vmstorage node, where `N` is the number of `vmstorage` nodes in the cluster. Previously the typical increase in the number of time series per vmstorage node after the re-routing was closer to 100%, while in the worst case it could reach `(N-1)`x.
* The placement of time series among `vmstorage` nodes doesn't depend on the order of `vmstorage` addresses passed to `-storageNode` command-line flag at `vminsert` nodes thanks to the changed consistent hashing algorithm (from [jump hash](https://arxiv.org/abs/1406.2294) to [rendezvous hash](https://www.eecs.umich.edu/techreports/cse/96/CSE-TR-316-96.pdf) ). Previously samples for the same time series could be placed to multiple `vmstorage` nodes if multiple `vminsert` nodes had different order of `vmstorage` nodes passed to `-storageNode` command-line flag. This could result in increased number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) across all the vmstorage nodes, which, in turn, could result in higher resource usage (RAM, CPU, disk IO, disk space) at `vmstorage` nodes.

These improvements should improve the stability of the mode with enabled rerouting in the cluster (e.g. when `-disableRerouting=false` command-line flag is passed to `vminsert`. The re-routing is disabled by default starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660) ).

The next release of VictoriaMetrics also adds an ability to drop incoming samples if vmstorage nodes are temporarily unavailable and/or overloaded if `-dropSamplesOnOverload` command-line flag is passed to `vminsert` nodes. By default vminsert slows down accepting new samples if vmstorage cannot keep up with the ingestion rate. This may result in increased number of pending samples at client side, which sends data to vminsert. This increases the delay between samples' generation and samples' ingestion into vmstorage. This may result in incomplete query results, which rely on recently ingested data (e.g. alerting and recording rules). In this case the `-dropSamplesOnOverload` mode may help receiving the most recently generated samples at the cost of dropping older samples. The number of dropped samples is tracked in per-`vmstorage` counter at `vminsert` nodes - `vm_rpc_rows_dropped_on_overload_total` . See more details at [changelog](https://docs.victoriametrics.com/CHANGELOG.html).

The features mentioned above can be tested by building cluster components of VictoriaMetrics from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) (currently this is 755e26e67b44962bada3a427e114d3f6ae284b5b ) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 .

**Comment by valyala** [comment]
FYI, the improvements mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337#issuecomment-1031538669 have been integrated into [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
Closing this issue as resolved.

See [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#improving-re-routing-performance-during-restart) on how to improve rerouting performance during rolling restarts of `vmstorage` nodes.

@dxtrzhang , please create a new issue if you encounter rerouting problems on [the latest available release of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest).
