### ISSUE TITLE
Proposal: Create VictoriaLogs

### ISSUE THREAD

**Issue by zbindenren** [VictoriaMetrics/VictoriaMetrics#816]
**Is your feature request related to a problem? Please describe.**
[Grafana Loki](https://grafana.com/oss/loki/) is a log aggregation system inspired by Prometheus. It does not index the contents of the logs, but rather a set of labels for each log stream.

Unfortunately it is hard to run it on premises because it has dependencies to Cassandra, S3 etc...

**Describe the solution you'd like**
It would be greate to extend `vmstorage`, `vminsert` and `vmselect` to support `loki` protocol. I think `vminsert` and `vmselect` would not be a problem, but I am not sure about `vmstorage`.

**Comment by faceair** [comment]
I've finished a very early version of this. https://github.com/faceair/VictoriaLog

**Comment by syepes** [comment]
OMG! This would be just amazing and a great addition to the Victoria Family!

**Comment by faceair** [comment]
These are the changes I made:
* vmstorage:
  * change value format from float64 to []byte, use zstd compression
  * added option to fetch only timestamps, which can improve performance when [query logging metrics](https://grafana.com/docs/loki/latest/logql/#metric-queries)
* vmselect:
  * extend support logql filter expression
  * support loki http api & response format
* vminsert
  * support loki push api
  * support prometheus-style data writing via tcp

I changed some code in vminsert & vmselect that was necessary, and I'm not sure how I'm going to keep it in sync with the VictoriaMetrics repository code in the future.
The bigger problem is that I have modified the storage data type of vmstorage so that I have no way to directly import the VictoriaMetrics repository and it is difficult to merge VictoriaLog into VictoriaMetrics.

Here's my new proposal https://github.com/VictoriaMetrics/VictoriaMetrics/issues/819

**Comment by zbindenren** [comment]
Cool, I wonder if this gets accepted...

I see that you @faceair already started with this 5 days ago. So we had basically the same idea 😄

**Comment by syepes** [comment]
@valyala What is your take on this functionality? Or are you guys going to focus just on the metrics?

**Comment by valyala** [comment]
> What is your take on this functionality? Or are you guys going to focus just on the metrics?

We are focusing on metrics right now, but VictoriaLogs is in our plans. It can be based on https://github.com/faceair/VictoriaLogs .

**Comment by faceair** [comment]
It looks like I can maintain VictoriaLogs on my own for a while, and later I will improve the compatibility with Loki and test the real performance.
I look forward to merging VictoriaLogs into VictoriaMetrics in the future.

**Comment by te4336** [comment]
@zbindenren If you happen to have the capability you can provide an S3 compatible service using Minio and then just use the Bolt-DB shipper function in the latest version of Loki. While having this as part of the Victoria Metrics family would be awesome not sure it's worth people re-inventing the wheel when there are solutions to get around some of the extraneous requirements for Loki.

**Comment by misiek08** [comment]
@te4336 almost 2 years passed and Loki is still unusable for scenarios with real logging data. Trying to query anything hitting more than 50k logs is exploding servers :)

I'll try to contribute to VictoriaLogs and I'm glad I found this issue and VictoriaLogs repo ❤️

**Comment by mxssl** [comment]
Do want!

**Comment by v1gnesh** [comment]
Hello,

Post the recent community day and expressed interest to create VictoriaLogs, please see if there are patterns & methods from this that can be rebuilt in Go, for VL.

https://www.youtube.com/watch?v=23iHoDeO7M4
https://www.uber.com/en-IN/blog/reducing-logging-cost-by-two-orders-of-magnitude-using-clp/

**Comment by tenmozes** [comment]
We started working on Victoria Logs, you can find some information here https://www.youtube.com/live/Gu96Fj2l7ls?feature=share&t=1952

**Comment by zbindenren** [comment]
> We started working on Victoria Logs, you can find some information here https://www.youtube.com/live/Gu96Fj2l7ls?feature=share&t=1952

Hope that there will be a grafana datasource. Looks good.

**Comment by itsmjeu** [comment]
looking forward to see a datasource for grafana or to use it as Loki one,  and the possibility to use victoriametrics cluster that already exists

**Comment by valyala** [comment]
Good news - the initial release of VictoriaLogs is ready for use - see [these docs](https://docs.victoriametrics.com/VictoriaLogs/).

VictoriaLogs accepts logs from Filebeat, Fluentbit, Logstash and Vector - see [these docs](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/). Promtail and Fluentd support is on the way.

VictoriaLogs provides user-friendly query language - LogsQL. See [these docs](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html)

VictoriaLogs integrates with existing command-line tools such as less, tail, grep, jq, awk, head, etc . See [these docs](https://docs.victoriametrics.com/VictoriaLogs/querying/#command-line)

**Comment by arrowcircle** [comment]
Hey! Great work! Is it possible to access these logs from grafana?

**Comment by StefanSa** [comment]
Hi there,
Also very interested in an Integartion with Grafana

**Comment by denisgolius** [comment]
> hi，does VictoriaLogs has cluster version？

Hello,
not for now, but we have it in roadmap - see https://docs.victoriametrics.com/VictoriaLogs/Roadmap.html

**Comment by denisgolius** [comment]
> looking forward to see a datasource for grafana or to use it as Loki one, and the possibility to use victoriametrics cluster that already exists

FYI: starting from [v0.3.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.3.0-victorialogs) VictoriaLogs support data ingestion via Promtail (aka default log shipper for Grafana Loki)

**Comment by zbindenren** [comment]
> > hi，does VictoriaLogs has cluster version？
> 
> 
> 
> Hello,
> 
> not for now, but we have it in our roadmap - see https://docs.victoriametrics.com/VictoriaLogs/Roadmap.html

Is graphana datasource not on the roadmap anymore?

**Comment by valyala** [comment]
> Is grafana datasource not on the roadmap anymore?

Grafana datasource for VictoriaLogs will be added eventually. There are the following options exist:

1. To add a new datasource to Grafana, which is specifically optimized for VictoriaLogs. There are high chances that Grafana won't include this datasource to standard Grafana installation, so it should be installed by users via inconvenient hacks. See the [example with VictoriaMetrics datasource for Grafana](https://github.com/VictoriaMetrics/grafana-datasource). We were trying to include this datasource into standard Grafana installation, but it wasn't included. They proposed yearly subscription for including VictoriaMetrics datasource into standard Grafana installation, but the price was too high for us.

2. To implement an API at VictoriaLogs for one of the supported datasource for logs in Grafana. For example, Loki or Elasticsearch. Then these existing datasources could be used for querying VictoriaLogs. This solution may prevent to use [LogsQL](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html) if these datasources parse or validate queries before sending them to Loki / Elasticsearch. In this case we need to add support for Loki query language or for Elasticsearch query language into VictoriaLogs. This isn't a good solution, since [LogsQL](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html) is the essential part of VictoriaLogs, which simplifies writing typical queries for logs.

There is a third option - to evolve [native web UI included in VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/querying/#web-ui), in order to make it useful for most cases with log analysis and debugging.

**Comment by lddlww** [comment]
why victoriaLogs can't support Loki query like victoriaMetrics support promql？

**Comment by helmut72** [comment]
Is web ui planned to get (also that much free) features like Grafana?

**Comment by QuentinN42** [comment]
Hello, I don't see in the [roadmap](https://docs.victoriametrics.com/VictoriaLogs/Roadmap.html) if it will be compatible with grafana (as a Loki datasource), I currently get this :

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/32516498/c863e743-252d-4716-9147-0b55dfae5615)

Is someone working on making VL Loki compatible ?

**Comment by JakeCooper** [comment]
We L O V E VictoriaMetrics at Railway

Currently looking to setup a Grafana -> LGTM stack and don't want to host Loki

Would use this in a heartbeat if it spoke Loki for querying through Grafana 😍 . Happy to contribute/sponsor/etc

**Comment by valyala** [comment]
> why victoriaLogs can't support Loki query like victoriaMetrics support promql？

It shouldn't be hard from technical perspective adding support for Loki query language into VictoriaLogs. Probably, it will be added in the future. But I personally don't like this direction, since Loki query language - [LogQL](https://grafana.com/docs/loki/latest/query/) - is awful query language for logs from usability and readability perspective comparing to [LogsQL](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html) - query language for VictoriaLogs. A few practical examples:

1. Select all the log entries with the `error` word in the [log message](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#message-field):
    - Loki: in general, it is impossible - you need specifying [log stream selector](https://grafana.com/docs/loki/latest/query/log_queries/#log-stream-selector), which matches all the [log streams](https://grafana.com/docs/loki/latest/get-started/labels/) stored in Loki. You need to know a common label, which exists across all the streams in order to construct such a selector. For example, if you know that all the log streams contain `host` label, then the log stream selector, which selects all the streams, may be expressed as `{host=~".+"}`. In this case the query, which selects all the log lines with the `error` word will look like `{host=~".+"} |= "error"` - it uses [`|=` line filter](https://grafana.com/docs/loki/latest/query/log_queries/#line-filter-expression). But this query can return only a part of matching log entries, because Loki limits the number of results a single query can return. The limit is set to 5000 by default - see `max_entries_limit_per_query` config option [here](https://grafana.com/docs/loki/latest/configure/#limits_config). Of course, you can set bigger limit, but this may result in increased RAM usage at Grafana Loki.
    - VictoriaLogs: just type `error` word in the query - that's it! You can try executing the following command on the host where VictoriaLogs runs in order to test how does it work:
    ```bash
    curl http://localhost:9428/select/logsql/query -d 'query=error'
    ```
    This query returns all the log entries from all the log streams, which contain the `error` word in the [log message](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#message-field). If VictoriaLogs contains billions of log entries with the `error` word inside log message, then all these billions of log entries will be returned in query results - there are no any limits on the number of returned matching log entries at VictoriaLogs side. Such queries do not crash VictoriaLogs and do not use additional RAM, CPU and disk space, because VictoriaLogs performs the query and returns query results in streaming manner, e.g. it reduces query execution speed when the client reads query response slowly. It pauses query execution when the client pauses reading query results. It cancels the query and frees up all the occupied resources when the client closes response connection. This allows processing arbitrary number of matching log entries at client side in command-line mode via Unix pipes. See [these docs](https://docs.victoriametrics.com/VictoriaLogs/querying/#command-line) for details.

1. Select all the logs, which contain the `error` word written in any case. For example, `error`, `Error`, `ERROR`, `eRrOr`, etc.
    - Loki: `{host=~".+"} |~ "(i)error"` . Loki forces using non-trivial regexp in this case, which is hard to write, read and maintain. It also may slow down the query significantly comparing to a specialized syntax.
    - VictoriaLogs: `i("error")` . See [case-insensitive filters](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#case-insensitive-filter) in LogsQL.

1. Select all the logs, which contain either `error` or `warn` words:
    - Loki: `{host=~".+"} |~ "error|warn"` . Loki forces using regular expression for such a simple query, since it has no syntax, which allows selecting logs with the listed words. Regular expression are non-trivial to write, read and maintain. They also may execute much slower comparing to simple word filters.
    - VictoriaLogs: `error OR warn` . The `OR` operator is used here - see [these docs](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#logical-filter) for details.

1. Select all the logs with the following list of errors / phrases: `error`, `auth failed` and `invalid password`:
    - Loki: `{host=~".+"} |= "error" |= "auth failed" |= "invalid password"` . This `|=` syntax look very unnatural in the query.
    - VictoriaLogs: `error "auth failed" "invalid password"` or `error AND "auth failed" AND "invalid password"` . The `AND` operator is used here - see [these docs](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#logical-filter) for details.

1. Select all the logs with the `error` word, while dropping logs which contain simultaneously `auth failed` and `invalid password` phrases. For example, the message `error: auth failed: backend error` should match, since it doesn't contain "invalid password" phrase, while the message `error: auth failed: invalid password` should be filtered out, since it contains both `auth failed` and `invalid password` phrases:
    - Loki: this query cannot be expressed in Loki :(
    - VictoriaLogs: `error !("auth failed" AND "invalid password")` . The `!` operator (aka `NOT`) and parenthesis are used here. See [these docs](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#logical-filter) for details.

1. Select all the logs with the `error` word followed by "auth failed", while skipping logs where "auth failed" goes in front of `error` word:
    - Loki: `{host=~".+} |~ "error.+auth failed"` . Again, Loki forces using non-trivial regular expressions for such a simple query.
    - VictoriaLogs: `seq("error", "auth failed")` . The [sequence filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#sequence-filter) is used here.

On top of this, contrary to Grafana Loki, VictoriaLogs supports efficient ingesting and querying high-cardinality labels (aka [log fields](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#data-model) ) such as `trace_id`, `ip`, `user_id`, etc., with a simple syntax: `field_name:query_here`. For example, the following VictoriaLogs query returns logs where the `trace_id` label contains `ABCD-EFGH` string and the `ip` field is in the range `[127.0.0.0 - 127.0.0.255]`:

```logsql
trace_id:"ABCD-EFGH" ip:ipv4_range("127.0.0.0/24")
```

Grafana Loki [doesn't support high-cardinality labels](https://grafana.com/docs/loki/latest/get-started/labels/bp-labels/), so it doesn't provide query syntax for selecting on such labels.

This makes dubious implementing Loki query language support in VictoriaLogs.

**Comment by valyala** [comment]
> Is web ui planned to get (also that much free) features like Grafana?

We are going to evolve [web UI for VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/querying/#web-ui) in the direction of better usability. TBH, Grafana UI for logs isn't the best example of useful UI for logs. VictoriaLogs will have much better UI from usability perspective than Grafana over time.

**Comment by helmut72** [comment]
> > Is web ui planned to get (also that much free) features like Grafana?
> 
> We are going to evolve [web UI for VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/querying/#web-ui) in the direction of better usability. TBH, Grafana UI for logs isn't the best example of useful UI for logs. VictoriaLogs will have much better UI from usability perspective than Grafana over time.

Thanks for answering. Yes, of course it's not a good UI for logs, but can be used for more than logs and does have free multiuser support with different auth flavors like OIDC, LDAP. Also the builder in explorer view helped a bit getting used to.

**Comment by zbindenren** [comment]
> > > Is web ui planned to get (also that much free) features like Grafana?
> 
> > 
> 
> > We are going to evolve [web UI for VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/querying/#web-ui) in the direction of better usability. TBH, Grafana UI for logs isn't the best example of useful UI for logs. VictoriaLogs will have much better UI from usability perspective than Grafana over time.
> 
> 
> 
> Thanks for answering. Yes, of course it's not a good UI for logs, but can be used for more than logs and does have free multiuser support with different auth flavors like OIDC, LDAP. Also the builder in explorer view helped a bit getting used to.

And additionally it is nice to correlate metrics with logs.

**Comment by JakeCooper** [comment]
^^And traces! Though maybe we'll have to wait* for VictoriaTraces 😆 

*EAGERLY

**Comment by freshpr** [comment]
I also do hope there is some sort of temporary solution with a loki api db abstraction if it's not too much from a tech perspective.

I absolutely love VM and now VL. The simplicity and resource management is miles ahead.

I agree the Grafana UI isn't the best for logs but it isn't bad either. Creating a single pane dashboard to show the logs is basically all that's needed.
Building a proper UI requires a ton of work. Especially to integrate uam permissions & dashboard capabilities like Grafana has.
The combination with Grafana Tempo to correlate logs and traces in the same UI and Grafana being an industry standard for visualization may also open up VL to more users.
In the long term, I can see a bright future for a dedicated ui for Victoria

I'll also wait eagerly 🥲

**Comment by air3ijai** [comment]
Elasticsearch/Kibana and Loki/Grafana has a limits for a number of returned rows and we are trying to find a logging solution with an unlimited scrolling like [AWS CloudWatch](https://aws.amazon.com/cloudwatch/) or [GCP Cloud Logging](https://cloud.google.com/logging).

Current [Web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui), has similar limitations, with a plans to remove it in the future
> This is the first version that has minimal functionality. It comes with the following limitations:
> - The number of query results is always limited to 1000 lines. Iteratively add more specific [filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters) to the query in order to get full response with less than 1000 lines.
> - Queries are always executed against [tenant](https://docs.victoriametrics.com/victorialogs/#multitenancy) 0.
>
> These limitations will be removed in future versions.

Will it eventually support an unlimited scrolling?

**Comment by valyala** [comment]
> Will it eventually support an unlimited scrolling?

Unlimited scrolling is already supported by VictoriaLogs via [CLI](https://docs.victoriametrics.com/victorialogs/querying/#command-line). There are plans to add support for unlimited scrolling into [Web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) via Websockets, so the Web UI could request more data for the currently executed query from VictoriaLogs when needed.

P.S. VictoriaLogs query language - [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) - has been improved significantly over the last month - see https://docs.victoriametrics.com/victorialogs/changelog/ .

We are going to improve [Web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) and [VictoriaLogs plugin for Grafana](https://github.com/VictoriaMetrics/victorialogs-datasource) during the next few weeks, so they could take advantage of [recently added VictoriaLogs HTTP APIs](https://docs.victoriametrics.com/victorialogs/querying/#http-api).

**Comment by zwpaper** [comment]
hi @denisgolius, as for the cluster version is on roadmap but not yet have a ETA, I would like to ask about more details to design should we use it in experiments.

1. Is there any plans that the preview version could somehow upgrade to the cluster one without or with only few broken or downtime?
2. How should we do backup in this preview version so that we can cover some unexpected disasters.

**Comment by valyala** [comment]
> Is there any plans that the preview version could somehow upgrade to the cluster one without or with only few broken or downtime?

Single-node version of VictoriaLogs has the same on-disk storage format as cluster version will have. So it should be easy migrating from single-node VictoriaLogs to cluster version - just substitute single-node binary with vlstorage (storage component of VictoriaLogs cluster).

> How should we do backup in this preview version so that we can cover some unexpected disasters.

VictoriaLogs doesn't support [snapshot functionality](https://docs.victoriametrics.com/#how-to-work-with-snapshots) yet. So, in order to make reliable backups, you need to stop VictoriaLogs, copy it's [data directory](https://docs.victoriametrics.com/victorialogs/#storage) and then start VictoriaLogs. VictoriaLogs stores data in per-day partitions, which are put into separate sub-directories under the `-storageDataPath` directory. So it is easy backing up data for separate days by just copying the corresponding directories while VictoriaLogs isn't running.

**Comment by valyala** [comment]
Closing this feature request as complete. Further development of VictoriaLogs can be tracked at the [changelog](https://docs.victoriametrics.com/victorialogs/changelog/). Please open separate bugreports and feature requests for VictoriaLogs instead of adding them as comments under this issue.
