### ISSUE TITLE
use NewCounter() where appropriate

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#828]
**Describe the bug**
It seems many VM local metrics are monotonically increasing counters, but are instantiated with `NewGauge()` rather than `NewCounter()`.   It seems important to assign the correct type to metrics, so that metrics consumers know the legal functions that can be applied (e.g. `increase()` is only suitable for counters).

An example is the recently-added `vm_rows_added_to_storage_total`.

(Note: beware about changing types of existing prometheus metrics.  Some components, like pushproxy, don't like it.)

**Expected behavior**
Monotonically increasing counters exposed by VM implementation should have type COUNTER, not GAUGE.

**Comment by belm0** [comment]
> these metrics make sense only for vmstorage component, while they have no sense for vminsert or vmselect

I'm not sure I understand how gauge vs. counter addresses this.

>  It is better to determine counters by _total suffix at /metrics page according to Prometheus metric naming recommendations

I understand the naming convention, but toolchains consuming prometheus data like Grafana use the type information of the metric for hints, etc. so I think it's important to have the correct type on metrics.

**Comment by valyala** [comment]
> I'm not sure I understand how gauge vs. counter addresses this.

Any metrics cannot be registered via [github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) package inside [lib/storage](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/lib/storage). Otherwise they will appear at `/metrics` page in all the apps that import `lib/storage` package, i.e. in `vminsert` and `vmselect` components of VictoriaMetrics cluster. The workaround is to use atomic counters inside `lib/storage` and expose them via Gauges at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/28353e48ca28e719ef7b9eb1757e85210b9d3037/app/vmstorage/main.go#L290 .

> I understand the naming convention, but toolchains consuming prometheus data like Grafana use the type information of the metric for hints, etc. so I think it's important to have the correct type on metrics.

[github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) package doesn't expose metric type information at `/metrics` page - see [these docs](https://github.com/VictoriaMetrics/metrics/blob/master/README.md#why-the-metricswriteprometheus-doesnt-expose-documentation-for-each-metric) and [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/643) for details.

**Comment by valyala** [comment]
This issue has been resolved in the commit 7fc2bd04129f59b6c390ce24cfa573d83460b383 . This commit has been included in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this issue as resolved.
