### ISSUE TITLE
cluster version benchmark 

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#863]
I pressure test the cluster version according to this document. One vminert, one vmseclet, one vmstorage。The machine parameters are 96c400G nvme。there is the data
![image](https://user-images.githubusercontent.com/2275120/97389434-3b031f00-1915-11eb-88ba-84ff05fbcb66.png)
According to the data, it takes 36h to write 200billion of data

but when i change to single-node verison, there is the data
![image](https://user-images.githubusercontent.com/2275120/97389523-743b8f00-1915-11eb-90c4-e37dec76095d.png)
Performance increased by 25 times

What is the reason

thx

**Comment by hagen1778** [comment]
Hi @jinlongwang! Thanks for doing this!

If not dive into details, benchmark result for two processes `data=>vminsert=>vmstorage` will be always slower than benchmark for one process `data=>victoriametrics`. There are various reasons for that, like performance of each component, network penalty, need to move data between processes memory etc.

But 25x difference is unexpected and if you care about understanding why - I'd recommend to setup monitoring for both tests and find a bottleneck. Pls see the following link https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster#monitoring
Having Grafana dashboard in place will give you more insights about cluster state during the benchmark. 
Hope that helps!

**Comment by jinlongwang** [comment]
hi, @hagen1778 
thank you for your reply
I did another stress test today, one vminsert, one vmseclet, one vmstorage,
`data->vminsert->vmstorage` 
The machine environment is the same as yesterday, 96c400G NVMe
Data are as follows

![image](https://user-images.githubusercontent.com/2275120/97573608-febee400-1a24-11eb-8e45-2b419991b7ba.png)

cpus is not squeezed out
![image](https://user-images.githubusercontent.com/2275120/97575236-68d88880-1a27-11eb-90c8-0e21adf51312.png)

vmstorage monitoring dash
![image](https://user-images.githubusercontent.com/2275120/97574256-ea2f1b80-1a25-11eb-9a02-3cd0eb21aa0b.png)

vminsert monitoring dash
![image](https://user-images.githubusercontent.com/2275120/97574335-06cb5380-1a26-11eb-8873-e10336345870.png)

Looking forward to your cluster version stress test article

By the way, today the VictoriaMetrics cluster version is uploaded to our production environment, which may be the largest vm cluster in the world :)

there is the monitoring dashboards
![image](https://user-images.githubusercontent.com/2275120/97574734-9ffa6a00-1a26-11eb-8083-8e9bce2d3f9f.png)

![image](https://user-images.githubusercontent.com/2275120/97574763-adafef80-1a26-11eb-8cfb-c709db62b9ed.png)

![image](https://user-images.githubusercontent.com/2275120/97574809-bbfe0b80-1a26-11eb-8730-0cfe4190d140.png)

**Comment by hagen1778** [comment]
Strange, dashboard screenshots are confusing. I'm under impression that you're using [VictoriaMetrics single-server overview](https://grafana.com/grafana/dashboards/10229) instead of [VictoriaMetrics cluster overview](https://grafana.com/grafana/dashboards/11176). Here's what I see on my laptop and [docker-compose with clustered VM up](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster/deployment/docker).
Here's benchmark started and almost immediately my laptop's hyperkit started to throttle:
![image](https://user-images.githubusercontent.com/2902918/97626982-9b33b700-1a22-11eb-96f3-71d6c448303c.png)
![image](https://user-images.githubusercontent.com/2902918/97627047-b272a480-1a22-11eb-97df-46deb9036b82.png)

Vminsert hit the ceil of max concurrent queries - the sign of storage being overloaded:
![image](https://user-images.githubusercontent.com/2902918/97627173-e51c9d00-1a22-11eb-87b1-c9c8c04db9c1.png)
The tip over the panel has some recommendations:
![image](https://user-images.githubusercontent.com/2902918/97627242-fa91c700-1a22-11eb-9c35-c4966680cd21.png)

Interconnection row shows that RPC errors started to appear between vminsert and vmstorage:
![image](https://user-images.githubusercontent.com/2902918/97627305-18f7c280-1a23-11eb-9879-e1c749d525ef.png)

Then `Troubleshooting` row will show that almost 40% of all inserts were marked as "slow" and give some explanation:
![image](https://user-images.githubusercontent.com/2902918/97627475-552b2300-1a23-11eb-8290-c83bf43133c5.png)

I can't continue benchmark any further if I want my laptop to stay alive but this might help you in your investigation!

> Looking forward to your cluster version stress test article

Yeah! That what we thinking to do but there is always lack of time for this... Btw, benchmarks done by independent companies or individuals are always more valuable than benchmarks made by maintainers :-) Feel free to ask for any help or recommendations if want to compile one or make a comparison with other systems.

> By the way, today the VictoriaMetrics cluster version is uploaded to our production environment, which may be the largest vm cluster in the world :)

Wow, that's exciting! Would you mind to share your story? We'd also appreciate a case study since it always helps other people to better understand and evaluate VM.

**Comment by davidsome** [comment]
@jinlongwang how big are your cluster？

**Comment by hagen1778** [comment]
Please see relevant benchmarks [here](https://docs.victoriametrics.com/Articles.html#benchmarks). 
Also see [benchmarking](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#benchmarks) section in docs.
We'll be glad to help with independent benchmarks or publish links to the results in the docs.
