### ISSUE TITLE
vmstorage RAM does not decrease when active time series is zero

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#914]
**Describe the bug**
After metrics ingestion goes down to 0 (no active time series at all) the vmstorage RAM does not go down, and only grows bigger

**To Reproduce**
Send metrics into VM - cluster, then stop sending and wait for a few hours.

**Expected behavior**
The vmstorage RAM should have decreased when no active time series are written into VM

**Screenshots**
You can see in the picture, once the active time series go up, the vmstorage RAM also goes up, but when active time series goes down
the RAM stays the same.
<img width="1350" alt="Screen Shot 2020-11-19 at 13 14 19" src="https://user-images.githubusercontent.com/7746785/99661543-a780c200-2a6c-11eb-8110-f3caa2e8a030.png">

**Version**
helm charts, victoria-metrics-cluster-0.8.1 - **1.46.0**

**Comment by valyala** [comment]
This is expected behavior - VictoriaMetrics is written in Go. Go runtime manages the memory. Sometimes it can keep unused memory and doesn't return it back to the operating system. See https://github.com/golang/go/issues/42330 . This should be fixed in the next Go release - see https://tip.golang.org/doc/go1.16#runtime .

**Comment by Alon-Katz** [comment]
Thanks for the explanation! closing this as its not a bug :)
