### ISSUE TITLE
/api/v1/series returns "cannot find tag filter matching" if start is not specified

### ISSUE THREAD

**Issue by Civil** [VictoriaMetrics/VictoriaMetrics#95]
In VM 1.22.0 if I do following query:
```
/api/v1/series?match[]={name=~"[^.][^.]*"}
```

I always get:
```
2019-07-11T20:15:25.012+0000    error   app/vmselect/main.go:165        error in "/api/v1/series": cannot fetch data for "MinTimestamp=1970-01-01 00:00:00 +0000 UTC, MaxTimestamp=2019-07-11 20:15:25 +0000 UTC, TagFilters=[\n{Key=\"\", Value=\"[^.][^.]*\", IsNegative: false, IsRegexp: true}\n]": search error: error when searching tsids for tfss [", [isNegative=false, isRegexp=true, prefix=\"\\x01\\x01\", orSuffixes=[], reSuffixMatch=0x823140]"]: cannot find tag filter matching less than 100000000000001 time series; either increase -search.maxUniqueTimeseries or use more specific tag filters
```

even if `search.maxUniqueTimeseries` is specified to be very high number.

```
$ wget -O- -q 'http://127.0.0.1:8428/api/v1/series?match[]={name=~".*"}' | jq '.data | length'
375
$ wget -O-  'http://127.0.0.1:8428/api/v1/series?match[]={name=~"[^.][^.]*"}' 
--2019-07-11 22:57:53--  http://127.0.0.1:8428/api/v1/series?match[]=%7Bname=~%22[%5E.][%5E.]*%22%7D
Connecting to 127.0.0.1:8428... connected.
HTTP request sent, awaiting response... 422 Unprocessable Entity
2019-07-11 22:57:53 ERROR 422: Unprocessable Entity.
```
However, if you do the same query with "&start=$(date +%s --date="5 minutes ago")" - original query will also start to work.

Everything was also fine in 1.21.2

P.S. For now I've replaced that particular query with `match[]={name=~".*"}` as a workaround. So that's not very urgent

**Comment by valyala** [comment]
Well, this is somewhat related to #91 :( I'm trying to figure out what went wrong. Will return back with findings.

**Comment by Civil** [comment]
This also happens for `match[]={name=~"[^.].*"}` or `match[]={name=~"..*"}`

**Comment by valyala** [comment]
OK, let's try narrowing down the bug.

1. What does the `wget -O- -q 'http://127.0.0.1:8428/api/v1/series/count' | jq '.data[0]'` return? This is the number of unique time series in the storage.

2. Which value for `-search.maxUniqueTimeseries` do you set? This value should be higher than the number returned from the previous command in order to be able to return labels for all the time series via `/api/v1/series` call.

3. Does the same error return for `match[]={name=~".+"}`?

**Comment by valyala** [comment]
@Civil , could you verify whether the issue has been fixed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/fc90ebf43c83a96b1caf4078c359506e27194b37 ?

**Comment by Civil** [comment]
Seems to be fixed in 1.22.1, thanks!

**Comment by jsvisa** [comment]
@valyala Sorry to bother you,  I'm using v1.49.0 in cluster mode, I have two `accountID`, the first one has 1846601  series, and the second one has 1477 series. While request `select/0/prometheus/api/v1/series?match[]={name=~".*"}` failed, but `select/0/prometheus/api/v1/series?match[]={name=~"..*"}` succeed, but only return a part of all series:

```bash
http ":8481/select/0/prometheus/api/v1/series?match[]={name=~"..*"}"
{
"status": "success",
"isPartial": false,
"data": [
....
}

http ":8481/select/0/prometheus/api/v1/series?match[]={name=~".*"}"

{
"status": "error",
"errorType": "422",
"error": "cannot fetch data for \"AccountID=0, ProjectID=0, MinTimestamp=2020-12-29 15:00:46 +0000 UTC, MaxTimestamp=2020-12-29 15:05:46 +0000 UTC, TagFilters=[\\n{Key=\\\"name\\\", Value=\\\".*\\\", IsNegative: false, IsRegexp: true}\\n]\": error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage vmstorage-0:8401: cannot execute rpcName=\"search_v4\" on vmstorage \"172.18.0.6:8401\" with timeout 30.000 seconds (elapsed 0.106 seconds); the timeout can be adjusted with `-search.maxQueryDuration` command-line flag: error when searching for tagFilters=[AccountID=0, ProjectID=0 {}] on the time range [2020-12-29 15:00:46 +0000 UTC - 2020-12-29 15:05:46 +0000 UTC]: error when searching tsids: the number of unique timeseries exceeds 300000; either narrow down the search or increase -search.maxUniqueTimeseries"
}
```

but query the second accountID, the result was opposite:

```bash
http ":8481/select/1/prometheus/api/v1/series?match[]={name=~"..*"}"
# return empty data
{
"status": "success",
"isPartial": false,
"data": [ ]
}

http ":8481/select/1/prometheus/api/v1/series?match[]={name=~".*"}"
# return 1000 series
```

So here comes my question:

1. Does this was a feature or bug :)?
2. In the second accountID, why it only returns 100 series, not all of them, it's there any way to return all of them?

**Comment by valyala** [comment]
@jsvisa , try adding `start=0` query arg to `/api/v1/series` query in order to obtain all the series over all the time. By default `/api/v1/series` returns time series for the last 5 minutes if `start` query arg isn't set. See https://victoriametrics.github.io/#prometheus-querying-api-enhancements for details.

As for the error when trying to fetch all the series from the first accountID, the error message states `the number of unique timeseries exceeds 300000; either narrow down the search or increase -search.maxUniqueTimeseries`. This means that you must increase `-search.maxUniqueTimeseries` command-line flag value at `vmstorage` nodes to a value higher than the total number of series in a particular accountID. The `-search.maxUniqueTimeseries` is set to 300000 by default. If the accountID has more than 300K series, then this error will be returned.
