### ISSUE TITLE
Question regarding simple use case of collecting metrics

### ISSUE THREAD

**Issue by mtfelian** [VictoriaMetrics/VictoriaMetrics#954]
Hello! I am relatively new to metrics collection systems. I have read readme and docs here but still i have some unclear points. Thanks in advance for addressing this. So: 

- what is the right strategy for using VM: in what cases we need vmagent, and is it necessary at all? 
- can we use just JSON HTTP API import and export (`/api/v1/import` and `/api/v1/export`) endpoints to get and put (`push` strategy, not `pull`) into VM ?
- what is the simplest use case? Just VM (no vmagent) + pushing app (an app which will use `/import` method or any other ingestion way), right? 
- what is the right way to configure VM for pulling (scraping) metric endpoints from app? Documentation says a lot about Prometheus configuration file but how it relates to VM? All this became a mess in my mind. 

Thanks in advance. Sure that there are simple answers for this.

**Comment by valyala** [comment]
> what is the right strategy for using VM: in what cases we need vmagent, and is it necessary at all?

The following docs describe cases for `vmagent` - https://victoriametrics.github.io/vmagent.html#use-cases .

> can we use just JSON HTTP API import and export (/api/v1/import and /api/v1/export) endpoints to get and put (push strategy, not pull) into VM ?

yes.

> what is the simplest use case? Just VM (no vmagent) + pushing app (an app which will use /import method or any other ingestion way), right?

yes.

> what is the right way to configure VM for pulling (scraping) metric endpoints from app? Documentation says a lot about Prometheus configuration file but how it relates to VM?

Single-node VictoriaMetrics can scrape Prometheus-compatible exporters. It accepts the path to Prometheus configuration file via `-promscrape.config` command-line flag. The Prometheus configuration file should contain configs for scrape targets according to [this specification](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). See more details at https://victoriametrics.github.io/#how-to-scrape-prometheus-exporters-such-as-node-exporter .

**Comment by mtfelian** [comment]
@valyala Oh thank you! Docs are very cool but a bit confusing for first-time experience with metrics gathering solution. 

So to have full picture of things (in simple case) in our Grafana we need, as i understood, the following (except the VM and Grafana itself): 

- Unix exporter in case of Unix server (https://github.com/prometheus/node_exporter)
- Windows exporter in case of Windows server (https://github.com/prometheus-community/windows_exporter)
- imported library in apps to instrument Go code (https://github.com/prometheus/client_golang)
- exposed /metrics endpoint for _pull_ strategy or HTTP client to VM (or other type of client) for _push_ strategy in apps

Is my understanding right?

**Comment by valyala** [comment]
Yes, your understandings are correct. I'd recommend taking a look at https://github.com/VictoriaMetrics/metrics instead of https://github.com/prometheus/client_golang for exporting app metrics.

**Comment by hagen1778** [comment]
Hi @mtfelian! Here's a how-to library for collecting metrics if you're writing a Go application. It includes VM and Grafana configuration https://victoriametrics.medium.com/how-to-monitor-go-applications-with-victoriametrics-c04703110870

**Comment by jelmd** [comment]
Finally, after e.g. having configured  vmagent, how can one verify, whether it sends the right data to the vmdb?
I.e. an easy way to make sure, that certain labels/values get replaced/inserted/modified on the right metrics?

**Comment by jelmd** [comment]
E.g something like
```
curl -s -H 'Accept-Encoding: gzip' http://localhost:8428/api/v1/export -d 'match[]={__name__!=""}' | gunzip -c | sed -e 's/"values.*//'
```
but faster, more efficient.

**Comment by valyala** [comment]
>  how can one verify, whether it sends the right data to the vmdb? I.e. an easy way to make sure, that certain labels/values get replaced/inserted/modified on the right metrics?

`vmagent` exports various metrics about its internal state at `/metrics` page. There are metrics starting with `vmagent_remotewrite_` prefix, which can be used for determining whether `vmagent` successfully sends data to remote storage. See https://victoriametrics.github.io/vmagent.html#monitoring for more details.

**Comment by jelmd** [comment]
Yepp, but "sent something" does not answer "sent what". The "what" here means: a) the final outcome of \*relabel\* and b) whether the correct type got inferred (e.g. because of things like [this](https://github.com/NVIDIA/gpu-monitoring-tools/issues/126) ).

Somewhere I read, that VM does not care about the type (i.e. whether it is counter, gauge, etc.). Is it still the case? If so b) is answered - does not apply. For a) I found the solution:
```
 curl -s http://localhost:8428/api/v1/series  -d 'match[]={__name__!=""}'
```

**Comment by valyala** [comment]
> Somewhere I read, that VM does not care about the type (i.e. whether it is counter, gauge, etc.). Is it still the case?

Yes - VictoriaMetrics ignores `TYPE` and `HELP` comments at scraped `/metrics` pages, since they can be misleading or incorrect like in the case of https://github.com/NVIDIA/gpu-monitoring-tools/issues/126 . Another reason for ignoring this info is that it isn't supported by [other data ingestion formats which are supported by VictoriaMetrics](https://victoriametrics.github.io/#how-to-import-time-series-data).

The best approach to check the final outcome stored in VictoriaMetrics after all the relabeling is applied is via `/api/v1/export`. Note that you can reduce the amounts of returned data by providing more specific label filters at `match[]` query arg and by providing smaller time range for the returned data with `start` and `end` query args. See [these docs](https://victoriametrics.github.io/#how-to-export-data-in-json-line-format) for details.

**Comment by denisgolius** [comment]
The issue seems to be answered so closing it.

@mtfelian , feel free re-opening the issue or creating new one (and linking to this one) if you have the related questions / issues.
