### ISSUE TITLE
it can support prometheus remote_read api?

### ISSUE THREAD

**Issue by vipsql** [VictoriaMetrics/VictoriaMetrics#96]
the wiki said the not support it,because it send amount of data; but i think the remote_read api can resovled alerts problem.  we can start an prometheus instance,it only has the remote_read config section and rule section。 the victoriaMetrics alerts is perfert!!

**Comment by valyala** [comment]
This won't work because of [this issue](https://github.com/prometheus/prometheus/issues/4456) in Prometheus. Prometheus remote read API isn't designed for reading data written into remote storage by other Prometheus instances.

As for alerting in Prometheus, then set Prometheus local storage retention to the duration that covers all the configured alerting rules. Usually 24 hours is enough: `--storage.tsdb.retention.time=24h`. In this case Prometheus will execute alerting rules on locally stored data, while replicating all the data to the configured `remote_write` url as usual.

**Comment by valyala** [comment]
Closing this question as resolved.
