### ISSUE TITLE
kubernetes pods discovery print error log

### ISSUE THREAD

**Issue by cocotyty** [VictoriaMetrics/VictoriaMetrics#966]
**Describe the bug**
print 
```text
skipping duplicate scrape target with identical labels;
....
```
my config:
![image](https://user-images.githubusercontent.com/2241753/102170723-fb49c400-3ecf-11eb-821c-a7cd9d72ced8.png)

This pod has two container,so generate two same targets.
Maybe this is not error.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55
```

**Used command-line flags**
Command-line flags are listed as `flag{name="httpListenAddr", value=":443"} 1` lines at `/metrics` page.
See the following docs for details:

* [monitoring for single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring)
* [montioring for VictoriaMetrics cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#monitoring)

**Additional context**
Add any other context about the problem here such as error logs from VictoriaMetrics and Prometheus,
`/metrics` output, screenshots from the official Grafana dashboards for VictoriaMetrics:

* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

**Comment by valyala** [comment]
This is expected behavior. The error message can be suppressed with `-promscrape.suppressDuplicateScrapeTargetErrors` command-line flag if the root cause for this message cannot be fixed. See https://victoriametrics.github.io/vmagent.html#troubleshooting for details on how to find and fix the root cause of the error message. It is also recommended upgrading `vmagent` to the [latest release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it may contain more informative error message for this case.

**Comment by cocotyty** [comment]
@valyala thank you!
