### ISSUE TITLE
balanced disk usage after cluster reszing

### ISSUE THREAD

**Issue by overstep123** [VictoriaMetrics/VictoriaMetrics#985]
I have a VM cluster now,and I want to add a vmstorage node to improve cluster scalability. But the old vmstorage node have high disk usage,while the new vmstorage node has low disk usage. Is there ang way to balanced them?

**Comment by valyala** [comment]
There are the following options for balancing disk usage after adding new vmstorage nodes to [VictoriaMetrics cluster](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html):

* To remove temporarily old vmstorage nodes from `-storageNode` list passed to `vminsert` nodes. This way newly incoming data will be written to new vmstorage nodes. Old vmstorage nodes could be returned to the `-storageNode` list at `vminsert` when disk usage on new vmstorage nodes will become equal to disk usage on old storage nodes.
* To wait for automatic data deletion on old vmstorage nodes due to the configured `-retentionPeriod`. After that disk usage should become equal between old and new vmstorage nodes. This is the recommended approach, since it guarantees linear scalability for data ingestion and querying for typical workloads, which touch recently ingested data.

P.S. We are working on a tool for manual data re-balancing among vmstorage nodes. This tool will be available in [enterprise version of VictoriaMetrics](https://victoriametrics.com/enterprise.html).

**Comment by overstep123** [comment]
OK,Thanks. Maybe the first way or the tool is better. Because we are using VM for long time storage.
