### ISSUE TITLE
Functions over `bool` modifier do not work

### ISSUE THREAD

**Issue by raags** [VictoriaMetrics/VictoriaMetrics#993]
**Describe the bug**
Screenshots below show the difference. Using the `bool` modifier `sum_over_time` doesn't sum the values. Which means the `1` after using `bool` is treated differently than a normal value. Is this expected? The behaviour seems different from Prometheus.

![Screenshot 2021-01-05 at 5 30 25 PM](https://user-images.githubusercontent.com/697714/103644055-bc150d00-4f7b-11eb-8c78-bb2dca73fe76.png)

**To Reproduce**
Any aggregation `*_over_time` doesn't work when `bool` modifier is used.

**Expected behavior**
Aggregation should work, this is useful for e.g. to count the number of events for a series
```
count_over_time(my_app_status == bool 0)
```

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ /victoria-metrics-prod --version
victoria-metrics-20201227-122315-tags-v1.51.0-0-g70df5f497
```

**Used command-line flags**
```
--storageDataPath=/vmdata --graphiteListenAddr=:2003 --httpListenAddr=:8428 -selfScrapeInterval=0
```
Vmagent scrate at `15s` interval.

**Comment by valyala** [comment]
The `count_over_time(my_app_status == bool 0)` query doesn't work as expected, because [MetricsQL](https://victoriametrics.github.io/MetricsQL.html), like PromQL, expects metric name with optional label filters inside `count_over_time()` function and any other function, which accepts optional lookbehind window duration in square brackets (i.e. `count_over_time(metric_name[1h])`. Lets' name such functions as `range functions`. VictoriaMetrics automatically sets the lookbehind window to `step` value passed to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) handler by Grafana. Grafana automatically calculates `step` value depending on the following params:
* time range for the graph
* horizontal resolution of the graph
* `resolution` option in graph settings

When MetricsQL query contains a range function with some expression inside it instead of metric name with optional label filters (for example, `count_over_time(my_app_status == bool 0)` instead of `count_over_time(my_app_status)`), then VictoriaMetrics automatically converts such query to the following [subquery](https://valyala.medium.com/prometheus-subqueries-in-victoriametrics-9b1492b720b3):

```metricsql
count_over_time((my_app_status == bool 0)[1i:1i])
```

Such subquery is evaluated in the following way: the inner expression - `my_app_status == bool 0` is calculated for each data point on the given `start ... end` time range with the given `step` duration between data points (`start`, `end` and `step` args are automatically passed by Grafana to `/api/v1/query_range` handler). Then the outer function - `count_over_time()` - is applied for the calculated data points with the same `start`, `end` and `step` args. So the end result is a graph with constant `1` value, since each `step` contains only a single calculated data point for the inner expression.

If you need calculating the number of raw data points with zero value, then use `count_eq_over_time(my_app_status, 0)` range function. See also other useful `*_over_time` functions provided by MetricsQL at https://victoriametrics.github.io/MetricsQL.html

**Comment by raags** [comment]
@valyala Thanks for the detailed explanation. I think describing this behaviour (of using subqueries when expressions are used) in the MetricsQL document will help users understand this scenario.
