### ISSUE TITLE
Vmstorage sizing disk question

### ISSUE THREAD

**Issue by guliangsi** [VictoriaMetrics/VictoriaMetrics#998]
**Describe the bug**
Hello,
We have 4 vmstorage each with 1TB of storage. Current usage is around 82%.
We are therefore considering increasing the storage capacity!

Hence our question: is it viable to upgrade each vmstroage to 2TB or is it better to add 4 vmstorage of 1TB?
Are there problems with having large vmstorage rather than several small ones? (it's more easier for us to add disk than to add new servers!)

Thank you for the answer
Regards

**Comment by hagen1778** [comment]
Hello @guliangsi! I believe, this question is not VM specific, but related to any distributed system. If we consider every vmstorage as a `shard` then adding more shards improves the read performance by reducing the amount of work every shard needs to do. For example, your read query needs to process 1mil of data points and those data points are evenly distributed across all shards. Then in system of 4 shards every shard will need to process 250k data points, and in system of 8 shards every shard will need to process only 125k data points. Hence, ideally read speed will improve two times!

Unfortunately, in the real world things are usually different. Having more shards implies more load on network, more communication and synchronization. Although, every time you spent while executing a query will be always bound by the slowest shard in your cluster. This effect is well known as [Universal Scalability Law](https://cdn2.hubspot.net/hubfs/498921/eBooks/scalability_new.pdf) which affects any distributed system. I'd worry about USL only on scale of 12+ shards in the cluster. But it depends on the data and use cases, so may require proper testing before making the decision.

However, my feeling is that in your case the scale from 4 to 8 will result into better performance. I'd also recommend to take a look on read speed on your disks while making read queries. If the read speed never hits 50-80% of max speed there may be no sense in adding more shards, since performance of current disks is underutilized.

**Comment by guliangsi** [comment]
Thank you @hagen1778  for the detailed and very clear answer! We are going to add 4 nodes to avoid futur performance problems !

**Comment by valyala** [comment]
Closing this question as resolved.
